### ISSUE TITLE
Embedded code in review comments breaks code

### ISSUE THREAD

**Issue by ignasi35** [refined-github/refined-github#1307]
See https://github.com/lagom/lagom/pull/1345/files#r186639290.

Adding a link to a GH line of code embeds the code in the comment. That view works as expected in the PR Conversation:

![screen_shot_2018-05-08_at_11_47_33](https://user-images.githubusercontent.com/762126/39750671-18e00b22-52b6-11e8-80dd-e387ebffe9de.png)

but remove the trailing character in `files` view:

![screen_shot_2018-05-08_at_11_47_17](https://user-images.githubusercontent.com/762126/39750679-1f072bc0-52b6-11e8-90b1-80b916e0d849.png)

**Comment by bfred-it** [comment]
I have a suspicion that it’s because of removeDiffSigns 🙂
