### ISSUE TITLE
Tab completion of @-mentions inserts tab instead of completing

### ISSUE THREAD

**Issue by wmertens** [refined-github/refined-github#1412]
Basically, the tab shouldn't be inserted while the @-completion dropdown is showing…

**Comment by yakov116** [comment]
Been having this issue for a while now

**Comment by bfred-it** [comment]
They probably changed a class. There’s a `if select.exists` in there that needs to be updated

**Comment by FloEdelmann** [comment]
This was reintroduced a few days ago. (Possibly when the functionality was extracted into a separate package?)

Also happens when tab-completing an issue/PR number after typing `#`.
