### ISSUE TITLE
Autocompletion for commit SHA

### ISSUE THREAD

**Issue by stefanbuck** [refined-github/refined-github#1547]
When I work on code review comments, I often refer to a commit where this particular issue was solved. This requires manually copy & pasting the commit sha and this really annoys me.

Wouldn't it be cool, if you could trigger an autocomplete prompt for commit sha like you can do for GitHub users with the `@`-Sign?

![image](https://user-images.githubusercontent.com/1393946/46129550-5c294b00-c237-11e8-8774-28394b03572b.png)

**Comment by busches** [comment]
The users prompt has a nice start with the `@` sign, what would be the trigger to call for a commit sha prompt, 0-9 and a-f? Doing that seems like we'll hit the API limit quickly unless we require 3 or more characters to match. Curious to what your thoughts are on implementation pattern.

**Comment by stefanbuck** [comment]
Ohh I just realised that my description is a bit lacking. Initially I was just referring to commits within the current Pull Request (not all commits from a repository). However, from a user perspective it would be better to take all commits into account to avoid confusions. 

It should behave similar to the username or issue autocompletion which can be invoked with `@` or `#`. Since those two keys are already taken, I thought that the tilde key would be perfect trigger for the commit autocompletion.

**Comment by sindresorhus** [comment]
This would be very useful. I often need to reference commits, and end up having to open a new tab and waste time. I'm ok with using tilde.

Does GitHub have an API endpoint we could use for this, to search for commits by SHA or title? How would you implement this?

**Comment by sindresorhus** [comment]
Also make sure to suggest this feature to GitHub too: https://github.com/contact

**Comment by stefanbuck** [comment]
Sure, I'll drop them a message.

Implementation wise, there is an API endpoint to search through commits, but it's currently in preview which means it can change any time. https://developer.github.com/v3/search/#search-commits

**Comment by bfred-it** [comment]
This is a rather complex feature. Maybe it can be done by reusing GitHub's own endpoints and UI. Help wanted to reverse engineer the existing `@` or `#` autocompletion

**Comment by artusm** [comment]
@fregante 
> Help wanted to reverse engineer the existing `@` or `#` autocompletion
```javascript

async function fakeApiRequest(text) {
  const values = ["value", "value1", "value2", "test1", "value2"];

  return values.filter((value) =>
    value.toLowerCase().includes(text.toLowerCase())
  );
}

async function searchSHA(text) {
  const autocompleteValues = await fakeApiRequest(text);

  const fragment = document.createElement("ul");
  fragment.setAttribute("role", "listbox");
  fragment.className =
    "suggester-container suggester suggestions list-style-none position-absolute";

  fragment.innerHTML = autocompleteValues
    .map(
      (
        value,
        i
      ) => `<li role="option" id="suggester-example-${i}" data-value="${value}">
    <span>${value}</span>
    <small>${value}</small>
  </li>`
    )
    .join("");

  return {
    matched: autocompleteValues.length > 0,
    fragment,
  };
}

const textExpander = document.querySelector("text-expander");
textExpander.setAttribute("keys", `${textExpander.getAttribute("keys")} !`);
textExpander.addEventListener("text-expander-change", (event) => {
  const { key, provide, text } = event.detail;
  if (key !== "!") return;

  provide(searchSHA(text));
});
textExpander.addEventListener("text-expander-value", (e) => {
  if ("!" !== e.detail.key) return;

  e.detail.value = `--__${e.detail.item.dataset.value}__--`;
});

```

![Peek 2020-08-20 03-18](https://user-images.githubusercontent.com/36174850/90702447-f82d2700-e293-11ea-94cb-be96d2313199.gif)

**Comment by fregante** [comment]
Not too bad. Do we have to handle the list generation and API rate limiting ourselves? I thought that the UI would at least be handled by GitHub

**Comment by fregante** [comment]
That looks correct according to https://github.com/github/text-expander-element :tada:

I suppose your code is only missing the `api.v4` call to get the filelist

**Comment by artusm** [comment]
> Also it can use JSX to generate the fragment effortlessly

I know. It was just an example.


> I suppose your code is only missing the `api.v4` call to get the commit list

event listener (`text-expander-change`) added from Content Scripts `detail: null`
![Screenshot from 2020-09-06 00-22-28](https://user-images.githubusercontent.com/36174850/92313777-3044a180-efd8-11ea-8b23-c73185f8d71f.png)
event listener (`text-expander-change`) added from console `detail: {...}`
![Screenshot from 2020-09-06 00-28-06](https://user-images.githubusercontent.com/36174850/92313785-3b97cd00-efd8-11ea-85a2-c9cb4b8e9d13.png)
It looks like we can't access to `event.detail` from Content Scripts

**Comment by fregante** [comment]
That's likely due to [isolation](https://developer.chrome.com/extensions/content_scripts#isolated_world). I thought events were somewhat safe from this…

We worked around this for `resolve-conflict`, even if it's not pretty.

**Comment by fregante** [comment]
This issue comes from year 2 BC (Before Covid) and shall now be terminated. It's a complex feature that might be great as a separate extension or as part of the command palette by GitHub. I suggest spamming GitHub for this feature request.
