### ISSUE TITLE
Can the new "save for later" functionality be used in lieu of the hacked on "mark as unread" persistence?

### ISSUE THREAD

**Issue by Qix-** [refined-github/refined-github#1606]
Github just released "save for later" (_finally_) for notifications.

Not all browsers are configured to keep local state around after they're closed, and as well moving between browsers or systems makes it impossible to keep those unread notification around via Refined Github, making the functionality both incredibly valuable but a little inadequate.

Could we potentially revamp them into piggy-backing off the "save for later" system, which is persisted for us by Github? It would then sync nicely between all installations of RG and not be bound by the browser's persistence layer.

The green notification icon would simply be whether or not there are any notifications saved for later.

It looks as though there is a new GraphQL mutator but no REST endpoint, so I'm not sure how hard that'd be to do.

**Comment by bfred-it** [comment]
We can't.

"Saved for later" are plain old notifications and we can't create new notifications. I don't see any way to add _any_ issue directly there, so we can't piggy-back it.

I don't see the GraphQL for Notifications at all: https://platform.github.community/t/notifications-and-events-apis-seem-to-be-missing/3114

**Comment by yakov116** [comment]
> It looks as though there is a new GraphQL mutator but no REST endpoint, so I'm not sure how hard that'd be to do.

@Qix- Where do you see this added?
