### ISSUE TITLE
Notification preview z-index issue

### ISSUE THREAD

**Issue by karaggeorge** [refined-github/refined-github#1721]
Another similar z-index issue:
<img width="749" alt="screen shot 2019-01-15 at 2 29 08 pm" src="https://user-images.githubusercontent.com/8822835/51204639-0950cd80-18d2-11e9-9131-d8df368f82b1.png">

**Comment by yakov116** [comment]
Same as #1719 its the same popup

**Comment by bfred-it** [comment]
That’s weird. Is that caused by us? I don’t think we do anything in the notifications (except mark-unread and open-all-notifications)
