### ISSUE TITLE
Wait for successful checks when using administrator privileges

### ISSUE THREAD

**Issue by LeoColomb** [refined-github/refined-github#1771]
When using administrator privileges to merge a pull request, the wait for successful checks is not respected and the PR is directly merge.

<img width="715" alt="capture d ecran 2019-02-11 a 16 27 56" src="https://user-images.githubusercontent.com/846943/52573247-05a15f80-2e1a-11e9-9e81-ca394ef1778d.png">

**Comment by bfred-it** [comment]
This is probably because the selector is different and the button click isn’t caught. Can you copy the whole block’s HTML and paste it here? Or maybe try submitting a PR

**Comment by bfred-it** [comment]
The feature wasn't working correctly on regular merges too, c6a3bd2 fixes that.

Can you wait for tomorrow's RGH release and see if that works for you already?

**Comment by LeoColomb** [comment]
You are too quick to let me submit a PR! 😉 
The HTML change should be recent, I use it with success on a regular merge not so long ago.
But sure, I'll try as soon as the released is published!
Thanks! 👍

**Comment by LeoColomb** [comment]
👌

**Comment by bfred-it** [comment]
Thanks for the update :)

**Comment by fahhem** [comment]
This seems to be happening again/still:

![image](https://user-images.githubusercontent.com/306100/67445471-e6221f80-f5c1-11e9-92a7-aefdfebb7752.png)

**Comment by CAFxX** [comment]
Confirm, just happened to me again:

![image](https://user-images.githubusercontent.com/408018/73330513-4fda5580-42a4-11ea-93d0-c82c8b209d16.png)

**Comment by fregante** [comment]
I finally tested this. The checkbox appears but once "Confirm squash and merge" is pressed it will still be awaited as usual

**Comment by drewlustro** [comment]
This isn't working for me. PR merged without waiting for successful checks :\

**Comment by fregante** [comment]
Let's disable the feature when it detects this setup since it's useless here:

- if the PR requires administrator privileges, it means the repo has branch restrictions, so it means you can add the additional "Passing checks" requirement
- if you're and administrator, it means you can enable the feature autonomously as well

**Comment by cheap-glitch** [comment]
@fregante Can we set up something to test this? If not, we need at least some relevant HTML to make a matching exclude or something

**Comment by fregante** [comment]
To test this, you need to be the administrator in a repo. If you're an admin on the sandbox:

- create a branch
- add branch protections to that branch
- open a PR to that branch
