### ISSUE TITLE
Autocomplete for file in repo

### ISSUE THREAD

**Issue by connorjclark** [refined-github/refined-github#2176]
Example URL: any comment textbox

`#` autocompletes on issue/pr titles.

`@` autocompletes on file names.

what if `!` autocompletes on filenames in the repo?

**Comment by bfred-it** [comment]
Related: https://github.com/sindresorhus/refined-github/issues/1547

**Comment by fregante** [comment]
Happy 30th monthversary 🎉  Unfortunately closing

**Comment by fregante** [comment]
See https://github.com/refined-github/refined-github/issues/1547#issuecomment-985677241
