### ISSUE TITLE
PR review "final report box" to show before merging

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#2579]
When about to merge PRs:

<img width="756" alt="Screenshot 2019-11-30 at 16 44 43" src="https://user-images.githubusercontent.com/1402241/69898814-bddfca80-1390-11ea-885d-322c479f4336.png">

we could show a final "report" box listing what's about to happen:

- full list of commits that will be merged/squashed/rebased, as suggested in https://github.com/sindresorhus/refined-github/issues/2564#issuecomment-557433237
- issues/PRs that will automatically be closed (via `closes #11` keyword) or if none will be closed
- any potential issues to be aware of:
  - unrebased `!squash`/`!fixup` commits: https://github.com/sindresorhus/refined-github/issues/2385
  - reviews that haven't been resolved
  - CI that hasn't completed or passed
- TODOs added by the PR https://github.com/sindresorhus/refined-github/issues/2634

What else could this include?

**Comment by fregante** [comment]
> full list of commits that will be merged/squashed/rebased

This would be a good start for this feature, coupled with the easier https://github.com/sindresorhus/refined-github/issues/2564

**Comment by fregante** [comment]
> * issues/PRs that will automatically be closed (via `closes #11` keyword) or if none will be closed

Actually I'd like to see this more. Sometimes new users forget to mark "closes X" correctly so it'd be good to see "No issues will be closed when merging this PR" as well as "X Y and Z will be closed after merging.

**Comment by rkrisztian** [comment]
I need the warnings or even merge checks for `!squash` and `!fixup` commits the most. I'm concerned that https://github.com/13rac1/block-fixup-merge-action still [does not support merge queues](https://github.com/13rac1/block-fixup-merge-action/issues/31), already has [deprecation warnings](https://github.com/13rac1/block-fixup-merge-action/issues/30) and it has not received updates since 2021.

**Comment by cooljeanius** [comment]
> I'm concerned that [13rac1/block-fixup-merge-action](https://github.com/13rac1/block-fixup-merge-action) still [does not support merge queues](https://github.com/13rac1/block-fixup-merge-action/issues/31)

I mean, support for merge queues isn't really that widespread in general; see also #6850

**Comment by fregante** [comment]
Closing in favor of:

- https://github.com/refined-github/refined-github/issues/7894

After 5 years, this issue isn't any closer to being done. Consider other requests rejected for now.
