### ISSUE TITLE
Fit tall images to the viewport (rich diff display)

### ISSUE THREAD

**Issue by mfulton26** [refined-github/refined-github#2616]
Viewing large images in the rich diff file viewer in a pull request is difficult. It would be nice to shrink the image to a smaller size to fit within my viewport so that I can view the whole image at once.

**Comment by sindresorhus** [comment]
Can you link to an example of a problematic case?

**Comment by mfulton26** [comment]
Hmm, I only have some for some private repositories but I can create something to demonstrate this.

**Comment by mfulton26** [comment]
example: https://github.com/sindresorhus/refined-github/pull/2617

**Comment by sindresorhus** [comment]
👍 Makes sense to me.

**Comment by jerone** [comment]
This should not conflict with the other smaller image, because people expect both images to be 100%.

**Comment by fregante** [comment]
2 years, a pandemic, no PR, unfortunately closing
