### ISSUE TITLE
Sort files and folders by natural order ("100" follows "2")

### ISSUE THREAD

**Issue by marcobiedermann** [refined-github/refined-github#2977]
Add option to sort folders alphabetically

#### Expected order

```
1-foo
20-bar
110-baz
```

#### Actual order

```
1-foo
110-baz
20-bar
```

### Example

![image](https://user-images.githubusercontent.com/5244986/78505725-b0d74b80-7775-11ea-8a85-8616d47fe919.png)

**Comment by fregante** [comment]
I verified that this is not just due to the hyphen; it also fails with number-only filenames:

<img width="117" alt="100 2" src="https://user-images.githubusercontent.com/1402241/78508624-82af3700-7788-11ea-8606-6aa16771b8ea.png">

**Comment by sindresorhus** [comment]
They are already sorted alphabetically, what you're requesting is called [natural sorting](https://en.wikipedia.org/wiki/Natural_sort_order).

Don't forget to also send a feature request to GitHub as it would be better if they fixed this natively: https://github.com/contact

**Comment by rrsouzza** [comment]
November 2021 and apparently this is still going on
Just renamed all my folder in my repository in order to try and order them naturally... looks like they haven't changed anything about it

**Comment by fregante** [comment]
Funny coincidence, I run into an issue with natural sorting in macOS and thus I think it might be *always* beneficial:

The folder had a list of files with hashes in the filename, causing this unexpected order:

- `a4bced`
- `a30deg`
- `a240da`

You'd expect "a2" to come before "a4", but natural sorting meant that it was sorted as "a4...a240". This meant that the list was completely unsorted for me

**Comment by kidonng** [comment]
@fregante hashes just cannot be sorted in a reasonable manner. Natural sorting is for _natural_ names, not random characters. 

Your point is valid though, sorting alphabetically can't be wrong. I don't see there's a huge need to implement this, one can just use leading zeroes.

**Comment by kidonng** [comment]
There's also this question: how do we consider the role of GitHub's file tree? Should it stay humble like ordinary command line programs, or should it be friendlier and smarter like a file explorer? For one thing, we developers may prefer the former unambiguous way. For another, GitHub it's beyond code and people treat it more like the file explorer on your system.

**Comment by rrsouzza** [comment]
Bottom line is: It'd be nice to have multiple options on how to order and organize our repositories. That way everybody could choose the setup they desire.

**Comment by cheap-glitch** [comment]
> That way everybody could choose the setup they desire.

Sadly we can't provide multiple settings in RGH, because given the number of features the extension would just balloon out of proportion.

You should ask GitHub to implement it, it's a valid request and it seems they've become keener on adding small QOL improvements like this.

**Comment by fregante** [comment]
> hashes just cannot be sorted in a reasonable manner.

They can: in their "unnatural" alphabetical sorting. 

I needed it to be sorted because I was looking for a specific file by visually scanning the list (the hash was after a keyword)

**Comment by fregante** [comment]
This belongs to a userscript or extension as it's not "always better" nor has there been a PR. I'd suggest asking GitHub

**Comment by AayushSameerShah** [comment]
Ahh, any update or a hack on this issue? I really am managing the files in the order, but after reaching at `9` the `10th` file is moved to second position. Any help would be beneficial 😄

**Comment by josealvarez97** [comment]
Public repositories may be intentional about the order of files. It's kind of annoying that I order my files in a certain way when I am working on Visual Studio Code but cannot display them in the same order for the public.

**Comment by NiekBeijloos** [comment]
> Ahh, any update or a hack on this issue? I really am managing the files in the order, but after reaching at `9` the `10th` file is moved to second position. Any help would be beneficial 😄

What you can do is prefix numbers 0 to 9 with another 0, so: 01, 02...09, 10. This will 'revive' the ordering.

**Comment by vytarasju** [comment]
> What you can do is prefix numbers 1 to 9 with a 0. This means your numbering should look like so: 01 02 ... 09 10

Such a simple solution and it works. Thanks!

**Comment by nearlystardust** [comment]
I know this is closed, but thank you! This helped :)
