### ISSUE TITLE
"Send now" button may lose the review (`submit-review-as-single-comment`)

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#2978]
I can't replicate it anymore but it happened twice for me.

1. Click "Send now"
2. The comment disappears
3. Nothing happens (the "new comment" form) should reappear.

Maybe one of these 2 `await`s are not happening:

https://github.com/sindresorhus/refined-github/blob/9fa2a1dd71a0b2465fb67ab29918a7b63bdac0fa/source/features/submit-review-as-single-comment.tsx#L83-L91

Losing a comment is pretty bad.

https://github.com/sindresorhus/refined-github/issues/1598 could be useful too.

**Comment by fregante** [comment]
I'd suggest adding:
- a 10s timeout on the `observeOneMutation` (via https://github.com/sindresorhus/p-timeout)
- `window.onbeforeload` to avoid users leaving the page (and also a `'pjax:start'` listener)

**Comment by fregante** [comment]
I found an error. `getNewCommentField` does not return a `textarea` as expected, in fact I have to select the `textarea` again later:

https://github.com/sindresorhus/refined-github/blob/75f4cc8b5fa9b75aa315a9b9a036e60d5abbadd0/source/features/submit-review-as-single-comment.tsx#L67-L72

`getNewCommentField` should probably be replaced with `elementReady` or a plain `select`

**Comment by cheap-glitch** [comment]
This feature has been completely broken for a while now (the button doesn't even appear anymore), and nobody complained or even seemed to notice. I suggest dropping it.

Besides, I never really got the point of this. It seems like a lot of complexity, just to avoid opening the main review dropdown and clicking on "Comment" :thinking:

**Comment by fregante** [comment]
The main issue with that is that a new "review" is created, so if you're just trying to leave a comment on a review it will appear twice on the main page. 

This is not really an issue on single comments however, you're right. And it's kinda complex and dangerous. 🥲 So many reasons to drop it but that'd hurt my feelings. 

It might be easier to hide those fake reviews instead. 

DROP IT LIKE IT'S December 31st 2019
