### ISSUE TITLE
Customize issue/PR subscriptions in 1-click

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#3005]
Try subscribing to this issue’s closure, it takes 4 clicks. Can this be reduced to 1 click?

Examples:

<img width="232" alt="group" src="https://user-images.githubusercontent.com/1402241/79323609-ba4b7b00-7f0e-11ea-8f1d-22b6298ac7c6.png" align=top> <img width="241" alt="icons" src="https://user-images.githubusercontent.com/1402241/79323631-c0415c00-7f0e-11ea-91ea-398f3896bd9d.png">

Or 3 clicks 😬 (but nearer/easier)

<img width="260" alt="" src="https://user-images.githubusercontent.com/1402241/79324444-ef0c0200-7f0f-11ea-9fbd-b6789dd976d0.png"> <img width="266" alt="" src="https://user-images.githubusercontent.com/1402241/79324446-efa49880-7f0f-11ea-808b-1c4d135f2290.png">

<details>
<summary>Dropdown demo code</summary>

```html
<details class="details-reset details-overlay" open="">
  <summary aria-haspopup="true" class="btn btn-block btn-sm thread-subscribe-button">
	{unmuteIcon()} Subscribe
  </summary>
  <div class="SelectMenu right-0">
    <div class="SelectMenu-modal">
      <header class="SelectMenu-header">
        <h3 class="SelectMenu-title">Customize</h3>
        <button class="SelectMenu-closeButton" type="button">
          {xIcon()} 
        </button>
      </header>
      <div class="SelectMenu-list">
        <button class="SelectMenu-item" role="menuitemcheckbox">
          {checkIcon()} Unsubscribed
        </button>
        <button class="SelectMenu-item" role="menuitemcheckbox">
          {checkIcon()} All notifications
        </button>
        <button class="SelectMenu-item" role="menuitemcheckbox">
          {checkIcon()} Merged
        </button>
        <button class="SelectMenu-item" role="menuitemcheckbox">
          {checkIcon()} Closed
        </button>
        <button class="SelectMenu-item" role="menuitemcheckbox">
          {checkIcon()} Reopened
        </button>
      </div>
    </div>
  </div>
</details>

```

</details>

**Comment by fregante** [comment]
Keeping the "Custom" section always open would also bring it down to 3 clicks:

<img width="443" alt="" src="https://user-images.githubusercontent.com/1402241/79325342-4d85b000-7f11-11ea-98f9-c90e72284dd2.png">

**Comment by fregante** [comment]
I think a relatively-easy compromise would be to add a button that subscribes you to status changes only (closed, merged, reopened) in one click

<img width="279" alt="" src="https://user-images.githubusercontent.com/1402241/94219303-206bff00-feac-11ea-8a7d-6d20e9a3854c.png">

At the very least, it can just exist and be able to submit the form.

As an improvement, it could keep show a "pressed" style if the current subscription settings are `merged, closed, reopened`

**Comment by yakov116** [comment]
We can reuse
https://github.com/sindresorhus/refined-github/blob/0eedc2c2b98f6acc7fd886f28f8de90761d103e3/source/features/conversation-activity-filter.tsx#L107-L121


Should make this somewhat simple

**Comment by fregante** [comment]
I’d rather see the one-click alternative I mentioned in my last comment. DOM-wise is just a button and a groupButtons() call.
