### ISSUE TITLE
`sync-pr-commit-title` and `wait-for-build` sometimes don't appear

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#3041]
I don't know how this happens exactly, but sometimes the update note (highlighted in yellow below) doesn't appear (and therefore the PR’s title isn't updated)

<img width="487" alt="" src="https://user-images.githubusercontent.com/1402241/80547454-85343380-89b8-11ea-8768-33604804020e.png">

Same goes for `wait-ci`:

<img width="750" alt="Screen Shot 2020-04-29 at 19 28 25" src="https://user-images.githubusercontent.com/1402241/80627053-a2681100-8a4f-11ea-8a69-341726f4b0cb.png">

---

This might happen when GitHub updates the content for the merge box but we don't detect it. Maybe `on-replaced-element.ts` can help us detect this change.

**Comment by H4mza96** [comment]
Wait until they appear  or refresh

**Comment by fregante** [comment]
This can likely be fixed by #3084

**Comment by fregante** [comment]
I think `wait-for-ci` is completely broken because I never see it anymore

**Comment by cheap-glitch** [comment]
Is this still a thing? Those features work fine for me.

**Comment by fregante** [comment]
I think this happens when that box is updated by GitHub on some minor event, for example when reactions come in or a comment is updated (elsewhere). This triggers a UI update, deleting our DOM. 

If nobody else see this, it can be closed, I'll reopen it if I see it again.
