### ISSUE TITLE
Deduplicate, cleanup, sort CI runs (GitHub Actions etc)

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#3136]
CI runs could be:

- Deduplicated (`push` and `pull_request` runs pass? Hide one)
- Cleaned up ("push" is the most common type, let's hide its label)
- Sorted (by Workflow. Jobs are already in order)

# Before

![](https://user-images.githubusercontent.com/1402241/82824994-a9e1d500-9eaa-11ea-97d9-eed0fc974f8a.png)

# After

![](https://user-images.githubusercontent.com/1402241/82825854-42c52000-9eac-11ea-8ccb-793e996c12c4.png)

# Example URL

https://github.com/sindresorhus/refined-github/commit/247ae2f9dbc6e005241554077466d99bbbb0cab6 (regular commit)
https://github.com/sindresorhus/refined-github/pull/3126#commits-pushed-b29cf13 (commit in PR)

**Comment by tooomm** [comment]
Adding to this:
In your "Before" picture the build results are ordered alphabetically already... that seems to not be always the case per default and things can be mixed up quite a lot.
It would help a lot to display similar content next to each other with a simple alphabetical ordering instead spreading them over all job list. I found no way to order them alphabetically or logically from the Actions config.

**Comment by fregante** [comment]
From a quick look, none of those would be dropped though; they’d just be sorted. I think your best bed would be to improve that with emojis

**Comment by fregante** [comment]
However, taking from https://github.com/sindresorhus/refined-github/issues/3075, it would be good to group them as well (but without collapsing them). Perhaps after sorting we’d just need to:

- highlight the workflow name
- thicken the border between each workflow group

**Comment by tooomm** [comment]
>From a quick look, none of those would be dropped though; **they’d just be sorted.**

Exactly that's what I'm looking for and would help a lot.

**Comment by fregante** [comment]
You will soon-ish see this feature making its way to your browser (Safari: August; Chrome: September, Firefox: 2023):

- https://github.com/refined-github/refined-github/pull/5858

It's not meant to be a _fix_ for this issue, but I think it covers what most people are trying to achieve: **focusing on what needs your attention**.

Leave a comment on that PR if you have further ideas on style/sorting, keeping in mind that it's a CSS-only feature.

<img width="561" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/1402241/181188098-c5691813-b2f1-4bea-bf6f-d91b9555b9a3.png">

**Comment by fregante** [comment]
I'm hesitant to make changes to this widget because it's dynamic, GitHub might lose track of the elements and we'd break it. Also hiding some runs might be troublesome/controversial.

I think `clean-checks-list` already sorts them by what's needed _right now_ and the rest should probably be fixed by GitHub.

Closing for now
