### ISSUE TITLE
Show latest tag and the changelog when you're creating a tag

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#3183]
When you create a tag, for example on https://github.com/fregante/github-url-detection/releases/new

<img width="753" alt="" src="https://user-images.githubusercontent.com/1402241/83907244-64a08b80-a765-11ea-92bf-4bac13d501f4.png">

To help you understand what your next version should be, the page should tell you:

- what is the latest tag?
  
	Showing this should be relatively easy since we already have that information from `latest-tag-button`

- what will your new tag contain?

	We can add a **link** to the changelog, e.g. https://github.com/fregante/github-url-detection/compare/v1.1.5...master. This is a little harder since it depends on the Target selector and needs to be updated.

**Comment by fregante** [comment]
This feature would be complementary to https://github.com/sindresorhus/refined-github/issues/2389, not a replacement.

**Comment by sindresorhus** [comment]
> what is the latest tag?

Can you also make it clickable? And when clicked, it's set as the tag.

**Comment by fregante** [comment]
Hmmm the intent was to create a brand new tag rather than associate an existing tag to a release. But perhaps your suggestion makes more sense. If the tag already has a release, GitHub will already inform the user.

**Comment by fregante** [comment]
> * what is the latest tag?

Implemented by GitHub:


<img width="389" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/1402241/130846699-18c1e8cb-d791-4260-9ded-9f1fa2e9b7aa.png">


> * what will your new tag contain?


We already have `unreleased-commits` for that, we just need to add it to this page. Recreated as an extension of the existing feature:

- https://github.com/refined-github/refined-github/issues/7895
