### ISSUE TITLE
Add "view file before commit/PR"

### ISSUE THREAD

**Issue by OliverJAsh** [refined-github/refined-github#3289]
When viewing a commit page, GitHub provides a link to view each file. The link points to the file at the current commit. [Example](https://github.com/jshttp/http-errors/commit/e11f87db72bec8b3c457cf0e3df9e0cbb09c7e62).

<img width="300" src="https://user-images.githubusercontent.com/921609/85848863-d0dd4080-b7a1-11ea-8a98-c257128d13b9.png" />

However, sometimes we want to view the version of a file _before the commit was made_.

For the longest time I have been doing this manually, by clicking "view file" and then editing the URL to add a `^` at the end of the commit (to reference the parent commit).

It would be very useful if this was added as a link in the menu, so we don't have to resort to hacking the URL like this.

This would also be useful in PRs, where GitHub similarly shows a "view file" link for each file in the diff. Sometimes we want to view the version of a file _before all of the commits in this PR_.

<img width="300" src="https://user-images.githubusercontent.com/921609/85848997-0f72fb00-b7a2-11ea-9020-3fce80d604db.png" />

**Comment by yakov116** [comment]
> For the longest time I have been doing this manually, by clicking "view file" and then editing the URL to add a `^` at the end of the commit (to reference the parent commit).

What about an `alt-click` to go to the parent commit?


> Sometimes we want to view the version of a file _before all of the commits in this PR_.

I think this would make sense as its own button. Also it would need to handle files created with this pr.

**Comment by OliverJAsh** [comment]
@yakov116 That would work, although it's less discoverable.

**Comment by fregante** [comment]
I find the lack of this really annoying. Is it possible that there’s no path to that page? I think it’s at least 3 clicks/pages away, which isn’t good. 

Suggestions welcome. Alt-click isn’t ideal in this case.

**Comment by OliverJAsh** [comment]
> Is it possible that there’s no path to that page?

Isn't it just as simple as replacing the commit param in the URL with the following?

- For commits, `${COMMIT}^`
- For PRs, the name of the base branch

**Comment by fregante** [comment]
My question was: how is it possible that GitHub didn’t add this feature? Is there any other non-obvious way to reach that page?

I’m not talking about “how to fix it,” because as you said it’s pretty easy.

**Comment by yakov116** [comment]
How about this?

![image](https://user-images.githubusercontent.com/16872793/85947890-62bc8900-b91b-11ea-8805-65980792ad65.png)

**Comment by yakov116** [comment]
@OliverJAsh Where do you expect to see the commit on the base branch or the head branch?

**Comment by OliverJAsh** [comment]
On the base branch/commit I think? (The existing "view file" points to the head branch/commit.)

**Comment by fregante** [comment]
This is possible:

![](https://user-images.githubusercontent.com/1402241/89709088-a5d73680-d974-11ea-8755-7df325e5c95d.gif)

Made by:

1. Wrap the existing `.dropdown-item` link into `.d-flex`
2. Add identical link but use icon instead of text
3. `width: min-content; padding-left: 8px`

```jsx
<div class="d-flex">
  {previousLink}
  <a {… previousLink classes} style="padding-left: 8px !important;width: min-content;">
    <GitHistoryIcon/>
  </a>
</div>
```

This should be applied to regular commits as well.

If a file is deleted by the current commit, the "View file" already points to the old commit, so in that case perhaps we should add the icon inside the existing link; this would indicate that the link points to the old commit.

**Comment by Vyvy-vi** [comment]
That feature is much needed. Could I work on this?

**Comment by fregante** [comment]
Yes please! Refer to my last implementation example

**Comment by fregante** [comment]
Not one-click, but this is possible via the `View History` link added by `more-file-links`

**Comment by aslafy-z** [comment]
This is still highly desirable! I see me View file, change branch to main, and update the org in the url too often!
The design you @fregante made at https://github.com/refined-github/refined-github/issues/3289#issuecomment-670919743 would work verry well for me!
