### ISSUE TITLE
Button to search in current path

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#3612]
We can [search by file location](https://docs.github.com/en/free-pro-team@latest/github/searching-for-information-on-github/searching-code#search-by-file-location) using `path:foo`. It may be helpful to make search scoped to the current path by default, so we don't have to type the path by hand or copy and paste.

URL the feature should appear:

- `isRepoTree` (https://github.com/sindresorhus/refined-github/tree/master/source)
- `isSingleFile` (https://github.com/sindresorhus/refined-github/blob/master/source/background.ts)

Some thoughts:

1. If the user has modified the search, then it will be persisted
2. It should not activate on `isRepoRoot`
3. For files, search in its parent path (e.g. `path:foo` when viewing `foo/bar.ts`)
   - And according to 2, it should not activate on root level files (e.g. `/foo.ts`)

## Demo

![1tqWPWcmQP](https://user-images.githubusercontent.com/44045911/94982458-1cf00c00-056d-11eb-852a-4326042354b2.gif)

<details>
<summary>A rough implementation</summary>

```ts
import select from 'select-dom';
import onetime from 'onetime';
import * as pageDetect from 'github-url-detection';

import features from '.';
import {getCleanPathname} from '../github-helpers';

let search = '';

function getSearch(): string {
	const path = getCleanPathname().split('/');

	if (pageDetect.isRepoTree() && !pageDetect.isRepoRoot()) {
		return `path:${path.slice(4).join('/')} `;
	}

	if (pageDetect.isSingleFile() && path.length !== 5) {
		return `path:${path.slice(4, path.length - 1).join('/')} `;
	}

	return ''
}

function setSearch(): void {
	const searchInput = select<HTMLInputElement>('[data-hotkey="s,/"]')!;

	if (searchInput.value === search) {
		search = getSearch();
		searchInput.value = search;
	}
}

function init(): void {
	setSearch();
	document.addEventListener('pjax:end', setSearch);
}

features.add({
	id: __filebasename,
	description: '',
	screenshot: '',
}, {
	include: [
		pageDetect.isRepoTree,
		pageDetect.isSingleFile
	],
	init: onetime(init)
});
```

</details>

**Comment by kidonng** [comment]
I changed my mind, filling the search box with default value is not a good idea as it can break many users' muscle memory.

We can consider adding a button to search in current path in the three dots menu, inside the navigation bar (note potential clash with `download-folder-button`):

![image](https://user-images.githubusercontent.com/44045911/152241645-137d0034-a2a2-43f4-9c7a-709d953448b6.png)

**Comment by fregante** [comment]
I think the only arguments against the feature are:

- noisy (extra text in the header)
- needs to be cleared when looking outside the current repo

As for muscle memory I don't see the issue as this doesn't silently change the behavior: the field the user will enter a keyword in will be prefilled with the content and therefore it's painfully clear. 

Adding another button in a dropdown I'm sure will just get lost/forgotten. 

I think the right way to implement this is to add another item in the dropdown:

- search in current folder

To the preexisting ones:

- search in current repo
- search in current user


This would solve every single problem

**Comment by fregante** [comment]
By GitHub

<img width="580" alt="Screenshot 2" src="https://github.com/refined-github/refined-github/assets/1402241/0711372c-bb50-4d06-a43c-6b11760e7f2c">
