### ISSUE TITLE
Assist with releasing from pull request

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#3619]
After merging a PR, Refined GitHub could show a link to create a new release, like: https://github.com/sindresorhus/refined-github/releases/new

Rough mockup:

<img width="728" alt="" src="https://user-images.githubusercontent.com/1402241/95032866-b6a8dd80-0681-11eb-80fb-f73cbc6a0c47.png">

---

_As discussed in https://github.com/sindresorhus/refined-github/issues/3607_

**Comment by yakov116** [comment]
Would you care what branch it was merged into? (Default or not)

**Comment by fregante** [comment]
It should, either by only showing the link when merging into _default_ or by setting the target (it's possibly by [`target` URL parameter](https://github.com/sindresorhus/refined-github/releases/new?target=hotfix))

**Comment by fregante** [comment]
This has similar logic to `pr-branch-auto-delete`

PR welcome

**Comment by fregante** [comment]
Markup also similar to https://github.com/refined-github/refined-github/pull/5643
