### ISSUE TITLE
Show reactions on PR listing

### ISSUE THREAD

**Issue by vbouchet31** [refined-github/refined-github#3905]
The title is quite descriptive. I would love to see the reactions on the PR listing page. For example, on https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed, we should see 👍 and 🎉 near #3893.

**Comment by fregante** [comment]
I think there's enough clutter on the page:

<img width="1096" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/105097837-de745380-5a6e-11eb-84f6-0f7c5cb716a8.png">

However GitHub shows the _last update_ date when you sort by _last update_, so it'd make sense to show the reactions **when sorting by reaction.**

**Comment by fregante** [comment]
🎉 
https://github.com/refined-github/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

<img width="565" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/175321788-2b01b0b7-ca0b-4726-89fa-edb7fbb61a0d.png">
