### ISSUE TITLE
`bypass-checks` breaks codecov link on PR

### ISSUE THREAD

**Issue by fisker** [refined-github/refined-github#3938]
On page like `https://github.com/sindresorhus/eslint-plugin-unicorn/pull/1088`, the codecov link is `https://github.com/sindresorhus/eslint-plugin-unicorn/pull/1088/checks?check_run_id=1797833452`, but enables `bypass-checks`, the link will be `https://codecov.io/`, should link to the page for this RR on codecov.io

**Comment by fregante** [comment]
This depends on the GitHub app I think, everyone can chose what the "More details" link points to. One would think that it leads to a page with more information, but here they're using it to advertise the app.

<img width="178" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/106792005-41dbb500-661b-11eb-9e6b-7e8143f11620.png">


As a generic solution, what if tried to detect this and avoid "bypassing the checks page"? A naive check would be "if details.pathname.length < 10, leave as is"

**Comment by jaredallard** [comment]
Just ran into this while developing a Github app, it drove me crazy thinking that there was some regression in my own code. Thankfully, it wasn't :sweat_smile:

**Comment by fisker** [comment]
How about 

```js
if (directLink.details_url === 'https://codecov.io') {
	link.href = `https://codecov.io/gh/${owner}/${repo}/pull/${prNumber}?src=pr&el=h1`
}
```


Or maybe we can just change this feature to not directly link to `details_url`, but show a popover with `output.summary` and `details_url`? (I prefer this)

**Comment by fregante** [comment]
> How about
> 
> ```js
> if (directLink.details_url === 'https://codecov.io') {
> ```

I suggested the generic version to avoid having to customize this for every service. Perhaps you can contact codecov to fix their link if you want a better one.

> but show a popover with `output.summary` and `details_url`? (I prefer this)

Not a bad idea, we could add a second link or icon pointing to `details_url` _next to_ the native link. It would make it less seamless, but it wouldn't have a chance of breaking like this (which happened before for a similar reason)

> It's a required insertion by Github

I get that, but doesn't your GitHub App exist on its own domain as well? Or do you _only_ show this data on GitHub Checks?

**Comment by jaredallard** [comment]
> > It's a required insertion by Github
> 
> I get that, but doesn't your GitHub App exist on its own domain as well? Or do you _only_ show this data on GitHub Checks?

Yep, my application uses GitHub Checks specifically so it can avoid the complexity of a web interface.

**Comment by laughedelic** [comment]
I observed the same issue with Mergeable: https://github.com/mergeability/mergeable/issues/520

**Comment by fregante** [comment]
> we could add a second link or icon pointing to `details_url` _next to_ the native link

We could do this. It would solve the issue for everyone, we only need to figure out how/where/what icon to show for this new link.

**Comment by kidonng** [comment]
I feel like an allowlist (e.g. only bypass known ones) will be a better solution.

**Comment by fregante** [comment]
Let's do that. Searching for "bypass-checks" in this repo might surface some of those "known ones"
