### ISSUE TITLE
PRs merge box automatically open (after opening them once)

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4101]
1. Open an PR you can merge
2. Click "Merge PR" to open the merge form, to look like this:

<img width="618" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/111133836-95a5bc00-8540-11eb-8d90-909b701234ad.png">

From now on, every time you visit that PR, the form will be automatically open. This behavior probably stops once a new commit comes in or maybe when the session ends.

This isn't strictly caused by RG, but RG likely triggers some internal auto-opening behavior of GitHub. It might be due to `clear-pr-merge-commit-message`

**Comment by cheap-glitch** [comment]
> for example by delaying `clear-pr-merge-commit-message` until the user opens the dropdown

I think it's already delayed? Since it has `onlyAdditionalListeners: true`.
