### ISSUE TITLE
Disable image auto-links if they point to themselves

### ISSUE THREAD

**Issue by cheap-glitch** [refined-github/refined-github#4132]
Follow-up of https://github.com/sindresorhus/refined-github/pull/4127#issuecomment-802730145

This would help distinguish useless auto-links from actual, custom links. (The locations of images would still by accessible from the right-click context menu.)

Two examples with auto-linked images (demo screenshots) and purposely-linked images (sponsor logos) :point_down: 
 * https://github.com/sindresorhus/refined-github
 * https://github.com/chalk/chalk

**Comment by kidonng** [comment]
Would also love to see this includes replacing `camo.githubusercontent.com` image **links** (not image `src`) on GitHub with image's [data-canonical-src] attribute.

Currently I've [rolled a script](https://github.com/kidonng/cherry/tree/master/scripts#camo-detective) for myself.

**Comment by fregante** [comment]
Not a good idea, GitHub does that to avoid tracking. https://stackoverflow.com/a/57862219

May be ok for a local script but not in RG

**Comment by kidonng** [comment]
I've said above it's to change the link, not the image source. The image source can stay using `camo.githubusercontent.com`.

**Comment by kidonng** [comment]
Though said above, I'd like to make it clear: jt's to change `<a href>` not `<img src>`. The latter can stay using `camo.githubusercontent.com`.

The point is that knowing where the original image come from can be handy and you don't want to hunt for it in Devtools every time.

I also changed my mind and agree what you said [here](https://github.com/sindresorhus/refined-github/pull/4151#discussion_r600717656), that this feature should only deal with links **literally** pointing to the same url as images. The change I'm proposing above are also included.

**Comment by fregante** [comment]
PR welcome, I think this feature is basically:

```js
for img of select.all('a img')
	if img.src === a.href
		a.replaceWith(img)

**Comment by fregante** [comment]
Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it.
