### ISSUE TITLE
`avoid-accidental-submissions` throws on pre-fork edit pages

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4194]
URL: https://github.com/MatthewL246/hello-world/edit/main/CONTRIBUTING.md

```
Refined GitHub → hide-markdown-diff → TypeError: undefined has no properties
    init hide-markdown-diff.tsx:24
    runFeature index.tsx:125
    setupPageLoad index.tsx:147
    add index.tsx:248
    $e pjax.ts:98
    Ne pjax.ts:311
    execute navigation.ts:62
    execute navigation.ts:17
    Y index.js:96
```

Console error only, not a real issue. I'm not sure if we should start fixing these issues in more direct ways instead of through `exclude`, which might not work with `elementReady` features.

For example in this case, if the first expected item isn't found, let the error throw only if it's not `isEmptyPage`. I wonder if this mechanism should be implemented via some sort of "deferred exclude" list of checks, or if `exclude` should just be treated this way (likely troublesome)

**Comment by yakov116** [comment]
In the past we did a check on these pages to make sure the selector exists

**Comment by fregante** [comment]
We have that in many other pages but then we make all errors silent, we need a better way to handle that

**Comment by yakov116** [comment]
> we need a better way to handle that

But that is in general, by having a detection if a specific selector exists. I think such a thing will be very hard if we are supporting GHE. Since the DOM will change and the warning will be moot for some users.

**Comment by cheap-glitch** [comment]
Renamed because we dropped `hide-markdown-diff`.

That said, the discussion is still valid, as exemplified by this error when visiting the URL in the first post:

```
❌ avoid-accidental-submissions 0.0.0 → TypeError: select_dom__WEBPACK_IMPORTED_MODULE_1__["default"](...) is undefined
    addQuickSubmit moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:3322
    runFeature moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:8019
    setupPageLoad moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:8037
    add moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:8092
    add moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:8093
    tsx moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:3356
    __webpack_require__ moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:25475
    <anonymous> moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:25731
    <anonymous> moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:25947
    <anonymous> moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:25949
refined-github.js:7942:11
```

The faulty line:

https://github.com/refined-github/refined-github/blob/4f270c4f50e0a2a20085a6e92095117f10340322/source/features/avoid-accidental-submissions.tsx#L10
