### ISSUE TITLE
`follow-file-renames` should handle branch names with slashes, but doesn't

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4196]
https://github.com/sindresorhus/refined-github/commits/Slash/slash?after=ee8b6422d2ddd1199f557594d03e7ee850e843f0+34&branch=Slash%2Fslash&path%5B%5D=webpack.config.ts

As a consequence of recent changes outlined in #4179 and fixed in #4193, slashed branches are not currently supported in commits pages. 

#4187 might fix it.

Follows #4193

**Comment by ahmed2m** [comment]
I'm not sure if this issue addresses this problem with `default-branch-button` in the commits page too.
Like with this link
https://github.com/iberianpig/fusuma/commits/feature/device_capabilities

**Comment by yakov116** [comment]
No that is a different issue will also be fixed by #4187 (We made a quick fix then and we dropped too much code)
