### ISSUE TITLE
`submit-review-as-single-comment`: Cannot read property 'removeAttribute' of undefined

### ISSUE THREAD

**Issue by xneek** [refined-github/refined-github#4242]
* crashes when trying to add 160 lines of suggestions (indentation in enum)
* clearing local storage brings back to life, but comment hangs in pending
* ![image](https://user-images.githubusercontent.com/9931355/114849548-8a1c0e00-9de8-11eb-9958-99431210fde2.png)
* When trying to «Send now»
* window alert 
![image](https://user-images.githubusercontent.com/9931355/114849937-f39c1c80-9de8-11eb-8ea4-4a06f846d6e1.png)
* in console ![image](https://user-images.githubusercontent.com/9931355/114850034-0adb0a00-9de9-11eb-88ea-645901fff01b.png)

**Comment by yakov116** [comment]
Hmm I just tried it now and I did not get an error.

What version of the extension are you using? And are you on enterprise?

**Comment by fregante** [comment]
I got the same error forever on Safari, I assumed it was broken just there.

**Comment by xneek** [comment]
> Hmm I just tried it now and I did not get an error.
> 
> What version of the extension are you using? And are you on enterprise?

* Google chrome 89.0.4389.128
* Enterprise

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/blob/44f4ddc09618b2dadea8ff1a7aa19380708f2e1a/source/features/submit-review-as-single-comment.tsx#L55

Needs to be changed `.js-suggested-changes-contents`

**Comment by cheap-glitch** [comment]
Closing as the feature was dropped in #5217.
