### ISSUE TITLE
Extend "markdown" features to more applicable pages

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4244]
As discovered in https://github.com/sindresorhus/refined-github/pull/4151, we have some features that are applied only to Markdown files but could be applied to a whole host of file types like CSV and SVG.

Please analyze what makes a feature applicable to other filetypes and don't just blindly include random extensions.

Some of these features are:

- `link-to-changelog-file`
- `vertical-front-matter`
- `view-markdown-source` (we may want to revert #4535 to support more types of files)
- `hide-markdown-diff` -> if compatible with other files, it needs to be reimplemented because it was added by GitHub… only on markdown files.
- ~~`collapse-markdown-sections` should be changed to **only** apply to wikis, as discussed in https://github.com/sindresorhus/refined-github/issues/4008#issuecomment-820515283~~ done in #4335 

Some useful links:

- [GitHub Docs: Working with non-code files](https://docs.github.com/repositories/working-with-files/using-files/working-with-non-code-files) (you can find more types of file here)
- [GitHub Markup](https://github.com/github/markup/blob/46908504f5099b15a88030749f0aeb52cd2f6799/README.md#markups) (like the above link 👆 but more technical)
- [Test files](https://github.com/github/markup/tree/master/test/markups)
- [CSV Test files](https://github.com/maxogden/csv-spectrum/tree/master/csvs)

**Comment by yakov116** [comment]
Are we able to use https://github.com/sindresorhus/is-md?

**Comment by fregante** [comment]
The point is to enable these features on pages other than markdown, so no.

**Comment by fregante** [comment]
Is this still applicable?
