### ISSUE TITLE
Duplicate releases in tabs and `more-dropdown`.

### ISSUE THREAD

**Issue by jtagcat** [refined-github/refined-github#4254]
https://github.com/sindresorhus/refined-github/issues/new?assignees=&labels=change+request&template=change_request.md

![image](https://user-images.githubusercontent.com/38327267/115150896-e76ac600-a059-11eb-91e8-f526d6910671.png)

Is this intended, why?

**Comment by fregante** [comment]
Thanks for the bug report! The bug disappears when you resize the window back and forth, so it's probably a new calculation issue on load

<img width="391" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/115153377-cb8a1300-a09f-11eb-9125-4745c00c225e.png">

**Comment by busches** [comment]
I can't recreate this. Is this still an issue?

**Comment by jtagcat** [comment]
I'm on an x230, HD screen as well. I might have a sidebar open as well, reducing the width.

> I have this all the time on my small laptop screen
