### ISSUE TITLE
`selection-in-new-tab` should not be enabled everywhere

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4272]
`selection-in-new-tab` is enabled on every page and it attaches a `keypress` handler even when not necessary. At the very least, this feature should be limited to places with navigations using `include`, like `isRepoConversationList`, `isRepoTree` and `isNotifications`

Are there any other pages where this feature applies?

**Comment by yakov116** [comment]
I would rather do a select where exists `.navigation-focus a.js-navigation-open[href]`

**Comment by fregante** [comment]
I think that really applies to every global feature. We could query the DOM everywhere or we could use a more efficient `include`

**Comment by fregante** [comment]
- `hide-navigation-hover-highlight` should hare the same `include` list
- `navigate-pages-with-arrow-keys` same for I think
- `reload-failed-proxied-images` likely only markup files and hasComments. But those might be enough pages that maybe it can stay global

The rest of them can really be on almost every page

**Comment by shinenelson** [comment]
This issue has been open for too long. It looks like an easy change. Should we leave it longer for someone new to come along and pick it up? Or shall I pick it up?

**Comment by fregante** [comment]
> Or shall I pick it up?

It's all yours! It's mostly a matter of exploring GitHub and looking for pages that have lists (commits, files, notifications):

1. Open page
2. Press `j` to see if there's any selectable item

Please try to be thorough in this search or else we'd end up disabling it on pages that use it

**Comment by shinenelson** [comment]
I was looking for small, quick wins :wink: This is probably not it. I think I have already amassed enough issues for myself to do over the weekend :sweat_smile: But if no one gets to it, I will pick it up.

**Comment by fregante** [comment]
Done in #5727
