### ISSUE TITLE
Meta feature: Automatically fill in browser+extension information on issue reports

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4292]
On
- https://github.com/sindresorhus/refined-github/issues/new?assignees=&labels=bug&template=1_bug_report.md
- [https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=1_bug_report.md&title=%60clean-conversation-sidebar%60%3A+Cannot+re(...)%0A%09](https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=1_bug_report.md&title=%60clean-conversation-sidebar%60%3A+Cannot+read+property+%27remove%27+of+undefined&body=%0AURL%3A+https%3A%2F%2Fgithub.com%2Fsindresorhus%2Frefined-github%2Fissues%2F4288%0A%0A%60%60%60%0ATypeError%3A+Cannot+read+property+%27remove%27+of+undefined%0ATypeError%3A+Cannot+read+property+%27remove%27+of+undefined%0A++at+clean+%28chrome-extension%3A%2F%2Fmcpkcdopehdnjeollbocpopkbdcahhej%2Fbuild%2Frefined-github.js%3A4352%3A106%29%0A++at+runFeature+%28chrome-extension%3A%2F%2Fmcpkcdopehdnjeollbocpopkbdcahhej%2Fbuild%2Frefined-github.js%3A8785%3A17%29%0A++at+setupPageLoad+%28chrome-extension%3A%2F%2Fmcpkcdopehdnjeollbocpopkbdcahhej%2Fbuild%2Frefined-github.js%3A8803%3A11%29%0A++at+chrome-extension%3A%2F%2Fmcpkcdopehdnjeollbocpopkbdcahhej%2Fbuild%2Frefined-github.js%3A8867%3A15%0A%60%60%60%0A%0A%3C%21--+Please+also+include+a+screenshot+if+the+issue+is+visible+--%3E%0A%09) (pre-filled URL)

We can automatically append this information to the text:

```
Refined GitHub: {version} {getAdditionalPermissions().hosts.length > 0 ? 'has GHE' : ''}
Browser: {navigator.userAgent}
```

**Comment by fregante** [comment]
Forget about the userAgent 😅 

https://github.com/refined-github/refined-github/pull/5113#discussion_r761665067

**Comment by kidonng** [comment]
> Let the user enter the browser, which may be reported as "chrome" when in reality it's Vivaldi.

It would be astonishing if some part of RGH works in Chrome but not other Chromium-based browsers.
Let's split the difference: we still fill this info, but in the "Description" field instead.

> We don't need to parse this information because it's so fickle

It's not parsing the entire `userAgent`, just the specific part regarding browser version. It also prefers the new API currently implemented in Chromium.

As fickle as it can get, the format has not changed and the version is still being updated even after `userAgent` is deprecated a long time.

I've tested it in Chrome/other Chromium-based browsers (Edge, Opera, Brave, Vivaldi), Firefox and Safari. Other non-matching browsers are still required to be specified.

**Comment by fregante** [comment]
> It would be astonishing if some part of RGH works in Chrome but not other Chromium-based browsers.

You'd be surprised! I don't want to be surprised, especially because we don't want to waste time trying to replicate those non-Chrome issues. 

> Other non-matching browsers are still required to be specified.

The problem is that they wont, because the field is already filled in. You know they'll open that link and submit the issue as is without any comment 😅

**Comment by kidonng** [comment]
> > It would be astonishing if some part of RGH works in Chrome but not other Chromium-based browsers.
> 
> You'd be surprised! I don't want to be surprised, especially because we don't want to waste time trying to replicate those non-Chrome issues. 

That's why I proposed the alternative approach to append the info in the "Description" field.

> because the field is already filled in

This is not true with my last commit: https://github.com/refined-github/refined-github/commit/d047eec7d6e331788065cc5d302961ab2bb1886f

**Comment by kidonng** [comment]
Related: https://github.com/refined-github/refined-github/pull/5298#pullrequestreview-853544750

**Comment by kidonng** [comment]
We can put userAgent in comments:

```js
// Won't overwrite error messages (https://github.com/refined-github/refined-github/blob/6c6e2799cd1499f6e629cf9764e0e23b3fd19ce5/source/features/index.tsx#L74-L78)
text-field-edit.insert(description, `<!-- UserAgent: ${navigator.userAgent} -->`)
```

The info is retained while keeping the issue from looking too verbose.

**Comment by kidonng** [comment]
@fregante I don't get why are you so opposed. All your worries are answered. Is any animal harmed during this? 

If people don't like providing userAgent they can just delete it. The browser info doesn't even have to be filled in automatically, it can be a button, thus avoiding making "Description" field actually optional.

**Comment by fregante** [comment]
Resolved by https://github.com/refined-github/refined-github/pull/5364
