### ISSUE TITLE
Confirmation before unsubscribing from multiple notifications 

### ISSUE THREAD

**Issue by rdsedmundo** [refined-github/refined-github#4314]
On [the notifications page](https://github.com/notifications) it's very easy to do "Select All" (ticking the checkbox) then click "Unsubscribe" when you meant to mark them as "Done" because the buttons are so close to each other.

This has happened to me 3x in the new UI so I'm pretty sure other users had had this problem too, and it's really frustrating because you may lose valuable subscriptions that you have for old issues that you're following waiting for resolution, for example.

![Screen Shot 2021-05-03 at 13 52 54](https://user-images.githubusercontent.com/5482378/116907270-bf619200-ac17-11eb-9266-09c797f3d7e3.png)

I think just a `window.confirm` would do it.

**Comment by yakov116** [comment]
Please! Just unsubscribed  from 20 items by mistake.

**Comment by fregante** [comment]
Please send a request to GitHub. Ideally we'd get a temporary "Undo" popup instead of asking for confirmation
