### ISSUE TITLE
Write Webpack loader for readme.md 

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4320]
I think we’re parsing readme.md the wrong way. Instead of asking webpack to replace magic variables we parse and handle manually, we should be able to write `import featuresInfo from './readme.md'` and have a loader parse and keep track of the file as part of the dependency graph (as originally discussed in https://github.com/sindresorhus/refined-github/pull/3678)

We still need to “parse” refined-GitHub.ts to get the list of active features, but maybe there’s a solution to that too (separately)

**Comment by fregante** [comment]
Docs: https://webpack.js.org/contribute/writing-a-loader/#guidelines

Probably the `/build/readme.loader.ts` file will look something like:


```js
export default function (source) {
  const list = /* extract feature list from `source` */
  return `export default ${JSON.stringify(list)}`;
}
```

The difference with [the current extraction code](https://github.com/sindresorhus/refined-github/blob/main/build/readme-parser.ts) is that that looks for each specific feature by name, while this loader should just detect and parse all lines that include a feature name/description/screenshot.

**Comment by fregante** [comment]
The problem however is that this will no longer cause the build to fail since the build no longer looks for specific features in the file. Suggestions welcome.

**Comment by fregante** [comment]
> The problem however is that this will no longer cause the build to fail since the build no longer looks for specific features in the file. Suggestions welcome.

Found a solution: Move this check to GHA https://github.com/sindresorhus/refined-github/issues/4008#issuecomment-855429007

**Comment by fregante** [comment]
This would allow us to switch to esbuild instead 😃 

It also has a loader-like feature: https://esbuild.github.io/plugins/#load-callbacks

**Comment by kidonng** [comment]
I actually prefer the old way of specifying feature meta. For single source of truth we can generate the README via a script, which is a lot more easier to deal with. Apparent downsides would be duplicate README template content and you will have to remember to generate it whenever you update the info...

**Comment by kidonng** [comment]
Not am I asking to revert the whole efforts of parsing info from README, I just thought this separation feels unnatural for me, and exotic for casual contributors.

**Comment by fregante** [comment]
> Not am I asking to revert the whole efforts of parsing info from README, I just thought this separation feels unnatural for me, and exotic for casual contributors.

Not sure what's exotic about writing documentation in Markdown. If anything, following some specific (parseable) format in a JS comment is exotic. 

The only exotic part is importing the magic variable `from '../readme.md'`, which happens exclusively in the options and background page maybe.

> This would allow us to switch to esbuild instead 😃

We might also just use Parcel since it takes `manifest.json` as the entry point, handling everything else. I opened a PR that switches to Parcel (but requires this issue to be solved first)
