### ISSUE TITLE
Link "Contributor" label to commit list

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4362]
<img width="288" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/118348049-d0909400-b571-11eb-8f30-90eaf0494582.png">

On https://github.com/sindresorhus/refined-github/issues/4359, this label could link to https://github.com/sindresorhus/refined-github/commits?author=SirWindfield

What other labels could be linked and where?

- owner: ?
- collaborator: ?
- member: ?

All pointing to the same commit list?

**Comment by kidonng** [comment]
I think they are all indicators of whether someone (may have) contributed to a repository and should link to the same page.

**Comment by FloEdelmann** [comment]
The <kbd>Member</kbd> badge could link to the members overview of the organization, e.g. https://github.com/orgs/editorconfig/people

**Comment by jtagcat** [comment]
In that case, `Member` should also have a button next to it. [`git-commit`](https://primer.style/octicons/git-commit-16) octicon seems like a good fit.

**Comment by kidonng** [comment]
> Or instead, add the commits button to the profile card:

Possibly related: #4657

**Comment by fregante** [comment]
If we're going to linkify that label I think it should always point to the commits list, for consistency. Also because the member list is not really related to the user itself, but it's about the organization, which already has a link next to the repo name.

**Comment by fregante** [comment]
We could link to the contributors page in the insights tab, ideally with deep-linking. This page will have exact stats for the user and also link to the commit list.

**Comment by kidonng** [comment]
> We could link to the contributors page in the insights tab, ideally with deep-linking. This page will have exact stats for the user and also link to the commit list. 

That only works if they are in the top 100.

**Comment by kidonng** [comment]
It seems new labels are coming:

<img width="927" alt="Screen Shot 2021-09-30 at 18 47 37" src="https://user-images.githubusercontent.com/44045911/135441755-efe7b2a5-5345-4dde-9c2c-0f5675f2e136.png">
:

**Comment by fregante** [comment]
"First-time contributor" is not new 😃
