### ISSUE TITLE
Sticky comment editor header

### ISSUE THREAD

**Issue by Araxeus** [refined-github/refined-github#4368]
I'm talking about the header with [Write | Preview] and all the insert code buttons

This would be nice for longer posts

its currently pretty annoying to try and insert using the buttons but they aren't on screen 

also having the option to switch between write and preview mode fast when comparing would be nice :)

![non-sticky header](https://user-images.githubusercontent.com/78568641/118436031-b4fbc980-b6e8-11eb-8b6f-0222c02036c0.gif)

**Comment by Dev-CasperTheGhost** [comment]
> also having the option to switch between write and preview mode fast when comparing would be nice :)

If keyboard shortcuts are possible, this would be nice

**Comment by Araxeus** [comment]
@fregante
I see this still have the "under discussion" tag, is this in enhancement in scope?

**Comment by fregante** [comment]
I don’t think it's worth fighting this. If you like that behavior, then disable `fit-textareas`. GitHub’s own textarea-stretcher does the same thing but avoids pushing the header and footer outside the window.
