### ISSUE TITLE
GitHub bug: PR lists have a broken layout in some situations

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4405]
1. Visit https://github.com/sindresorhus/refined-github/pulls?q=Drop+support+for+the+old+GitHub+layout
2. Resize window to about 900px

Possible solution: That line probably shouldn't be display flex, but I haven't checked

## Native

<img width="1020" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/119622648-8c36ab00-be31-11eb-8006-a354ed59a7fe.png">

## Refined

<img width="1019" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/119622625-84770680-be31-11eb-9e99-3960c07828c3.png">

**Comment by cheap-glitch** [comment]
I'm seeing this even with RGH disabled (at 800px width):

![image](https://user-images.githubusercontent.com/46634000/120324240-b206f880-c2e6-11eb-9958-d746fd05d23b.png)

**Comment by fregante** [comment]
<img width="732" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/144640318-62653d75-ca8b-4870-af4c-93585c372a0c.png">

This just needs a `flex-wrap: wrap` on the right element
