### ISSUE TITLE
PR scrolls up every second while the CI runs

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4430]
This happens on every PR for me. Example: https://github.com/sindresorhus/refined-github/pull/4394

I think it happens every time the page receives an update, so sometimes it pauses and then it resumes scrolling. You can see that some scroll happen exactly when some CI items go from "in progress" to "completed"

Anyone else has been seeing this? I'm on Safari

1. Visit PR with several workflows
2. Push commit
3. Scroll to CI section

![agif](https://user-images.githubusercontent.com/1402241/120095191-c7e1b580-c14e-11eb-813a-5b6d15c83d1a.gif)

**Comment by cheap-glitch** [comment]
> Anyone else has been seeing this? I'm on Safari

Yes I've seen this a few times of Firefox. I think reloading the page makes it go away.

**Comment by cheap-glitch** [comment]
I haven't seen this one in a while now. Maybe it was GitHub bug that got fixed.

**Comment by fregante** [comment]
I just saw it unfortunately. A few jobs running

**Comment by cheap-glitch** [comment]
> I just saw it unfortunately.

I've too seen it a couple of time since. But I'm still not sure this is our bug and not GitHub's.

**Comment by fregante** [comment]
Last time I checked it was our fault. It might be because of some mergeability-box feature which either changes the state enough to break RG or causes the scroll directly.

If it happens again, let's try this:

1. Use incognito without RGH, does it happen there too? 

If yes, it's not RGH and we can close this. 

If no, then in the non-incognito window:

3. Reload page, does it happen again?
4. Disable RG
5. Reload page, does it happen again?

If yes on step 4, it _may_ mean that RG breaks the state but it does not cause the scroll directly.

Step 2 is just to verify step 4 is consistent.

**Comment by fregante** [comment]
eh, not seeing it again. I'm gonna guess it's GH. Either way not a big deal, too difficult to track and likely fix
