### ISSUE TITLE
`deep-reblame` stays "loading" after going back

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4439]
1. Visit https://github.com/sindresorhus/refined-github/blame/77e11bd49548f5ff883aad34b4e3e94346c3ccf2/source/background.ts#L3
2. alt-click reblame icon on 3rd line
3. Go "back" in the browser history

![agif](https://user-images.githubusercontent.com/1402241/120615157-2de97800-c482-11eb-9447-8030f3a7ec7d.gif)

**Comment by yakov116** [comment]
Not happening to me in chrome.
