### ISSUE TITLE
Extend contributors guide

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4485]
Following https://github.com/sindresorhus/refined-github/pull/4200

The project could include further documentation: https://github.com/sindresorhus/refined-github/blob/main/collaborators.md

> What else should we include? This is different from the generic contributors guide, which is more of an entry point and doesn't need to include a lot of details about the codebase.
> 
> This file could include instructions on how the codebase is organized and nitpicks to ensure consistency when reviewing, which currently are "unwritten rules" and lints like:
> 
> - [ ] how to cache API calls correctly
> - [ ] sort imports a certain way
> - [ ] when to use elementReady and what it is
> - [ ] keep in mind GHE when using absolute URLs
> - [ ] use `// TODO[2021-10-01]: GHE #1234` comments to remind us to drop old code after a year
> - [ ] GHE support policy: I suggest dropping code a year after it has changed on GitHub.com
> - [ ] GHE code: preserve unchanged instead of mixing it with new code, unless it's a single selector change. When dropping it, it'll be as easy as deleting whole lines instead of untangling it from live code.
> 
> Also in the contributors guide we could add:
> - general code instructions (e.g. use this listener instead of that)
> - how to reverse engineer GitHub

**Comment by kidonng** [comment]
Now this issue is regarding the contributors, but what I had asked in https://github.com/refined-github/refined-github/issues/4288#issuecomment-829353106 is more user-facing, about feature caveats and helpful info like #5501. They are scattered around thousands of issues, and we frequently need to dig around to provide these for users. Wouldn't it be optimal if we can enable wiki in this repo so we have a central place to store these knowledge instead of opening obscure aggregation issues like #2960?

**Comment by kidonng** [comment]
> Keep in mind however that the vast majority of the knowledge will continue to be _lost_ in the conversations and commits, because nobody will spend time to move it out after a PR has been merged.

I will spend time maintaining the wiki 😉 I've complained lack of detailed docs a few times already.

> As for the CSS stuff, I would not spend time on that at all. If enough people complain, we just make the feature disableable, it makes no sense to maintain undo styles. Our intention is to just avoid having to move every single CSS change to a JavaScript file.

Writing reverts still takes time and effort, however simple it is. Put them somewhere easy to find save both users and our time.

**Comment by fregante** [comment]
We can also move this issue to the wiki:

- https://github.com/refined-github/refined-github/issues/2209

And add more links to core test URLs like

- https://github.com/refined-github/refined-github/pull/4030

**Comment by kidonng** [comment]
So... enable wiki?

**Comment by fregante** [comment]
YUP
