### ISSUE TITLE
`user-local-time` breaks positioning of some hovercards

### ISSUE THREAD

**Issue by cheap-glitch** [refined-github/refined-github#4527]
Go to https://github.com/sindresorhus/refined-github and hover on the contributors avatars:

![image](https://user-images.githubusercontent.com/46634000/123799930-03f06d80-d8e9-11eb-928d-0902e46941a3.png)

This is caused by the CSS added in https://github.com/sindresorhus/refined-github/pull/4384. The weird thing is that it happens on some hovercards but not all. I don't know if it's the "Sponsor" button or the "Committed to this repo" notice which makes this bug appear (or both).

**Comment by fregante** [comment]
The solution should probably be to reserve the space via CSS like we do for the tag changelog link feature. This way we don't change the height of the hovercard after it's loaded

**Comment by cheap-glitch** [comment]
> The solution should probably be to reserve the space via CSS

This is what https://github.com/sindresorhus/refined-github/pull/4384/files did, but while it fixed the cropping bug it also created this new one.
Maybe the positioning itself should be fixed, but only if the card contains certain elements (that might be loaded asynchronously) like a sponsor button or "Collaborator" infos.

**Comment by fregante** [comment]
How's that possible? How/when is GitHub calculating this? Should the padding be increased? Keep in mind some cropping just isn't avoidable if there's not enough space in either direction

**Comment by fregante** [comment]
I think our "space reservation" isn't working anymore (if we ever had it). The feature adds the time "too late" so it changes the height of the hovercard
