### ISSUE TITLE
Include artifact in release workflows

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4595]
In the `Version` job, we should also use `upload-artifact` like we already do in the Test workflow

**Comment by mowies** [comment]
Hi @fregante !
I would like to work on this issue.
Do I understand correctly that during the release workflow, the artifact that's about to be released should also be attached as an artifact to the workflow run?

**Comment by fregante** [comment]
Sort of, yes. The artifact to be attached to the release is actually this one, it's created by `npm test` and available in `/distribution`:

https://github.com/refined-github/refined-github/blob/eb6cc1221b745cc1149a49f325350548d5d41c94/.github/workflows/release.yml#L27

That `distribution` folder should be attached to the release generated just a few lines alter.

**Comment by mowies** [comment]
Ok then. I would replace the github-script for creating the release [here](https://github.com/refined-github/refined-github/blob/main/.github/workflows/release.yml#L32-L40) with using the GitHub CLI where the files can be attached directly.
It would look like this then:
```
name: Create release
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
run: |
  tar -czvf "distribution.tar.gz" "./distribution/"
  gh release create "${{ steps.daily-version.outputs.version }}" --generate-notes "distribution.tar.gz"
```
