### ISSUE TITLE
Summer feature freeze

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4596]
We keep adding new features but some existing features are partially or fully broken. Let’s favor bugfixes over new features for the rest of the summer. 

- [bugs (label)](https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Acreated-asc)
- [please ♥ (label)](https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+label%3A%22Please%21+♥%EF%B8%8E%22+sort%3Areactions-%2B1-desc)
- [meta (label)](https://github.com/sindresorhus/refined-github/issues?q=is%3Aopen+label%3Ameta+sort%3Areactions-%2B1-desc)
- issues meant to **slightly** extend/improve/refactor existing features might also be ok

![Stop, summer time](https://user-images.githubusercontent.com/1402241/126462612-f280eaf0-400a-4eab-8fe3-1f434ed1b71f.jpg)

We can go back to adding new features when we bring the number of bugs to a more reasonable level ☀️

**Comment by kidonng** [comment]
From `2021-07-22T00:00:00.000Z` to the post time of this comment, **172 issues** created during this time has been closed and **144 pull requests** created during this time has been merged.

We have been **closing issues 1.56 times faster** `(172 / 3) / (2504 / 68)` and **merging pull requests 1.67 times faster** `(144 / 3) / (1951 / 68)`!

<details>
<summary>Data source</summary>

Query:

```graphql
{
  repository(owner: "refined-github", name: "refined-github") {
    issues(last: 100, states: [CLOSED], filterBy: {since: "2021-07-22T00:00:00.000Z"}) {
      nodes {
        createdAt
      }
    }
    pullRequests(last: 100, states: [MERGED]) {
      nodes {
        createdAt
      }
    }
  }
}
```

Filter:

```js
start = new Date('2021-07-22T00:00:00.000Z').getTime()
res.data.repository.issues.nodes.filter(i => start < new Date(i.createdAt).getTime()).length
res.data.repository.pullRequests.nodes.filter(i => start < new Date(i.createdAt).getTime()).length
```

</details>

**Comment by fregante** [comment]
It was a long and productive summer my friends. Refined GitHub has been under attack from GitHub’s continuous breaking changes 😅 

We can continue adding features, but the bar to entry should be a bit higher since supporting many _complex_ features will just kill the extension altogether in the long run.

Let's keep Refined GitHub about ✨ Refinements ✨

Thanks for contributing!

**Comment by fregante** [comment]
Gotta especially thank @cheap-glitch and @kidonng for killing all bugs on sight during this period! 🐛🚫
