### ISSUE TITLE
`pr-branch-auto-delete` should warn the user when it happens

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4604]
Related:

- https://github.com/sindresorhus/refined-github/issues/3636
- https://github.com/sindresorhus/refined-github/issues/2267
- https://github.com/sindresorhus/refined-github/issues/3964

Possible solutions:

- add "☑️ Attempt to delete `branch` after merge" checkbox in merge box similar to `sync-pr-commit-title`
- Add a small timeout after merge: "Refined GitHub will delete the branch in 5…4…3…2…1… seconds"
- add a temporary timeline event informing the user AFTER it was merged, to inform the user about the feature so that they can disable it if they don't like it

**Comment by jasonvarga** [comment]
Would the ability to (optionally) disable this feature for forks be useful?
For instance, if I merge a PR from a collaborator, it feels a little odd for me to delete a branch on _their_ repo.

**Comment by jasonvarga** [comment]
Fair!

**Comment by wusendong** [comment]
Agree should exclude this feature by default. 

I recently ran into a situation where a branch was accidentally deleted automatically, and after consulting GitHub Support I found out that I wasn't the first person to submit a similar inquiry, and that most people ended up with some browser plugin installed (like this one)

**Comment by fregante** [comment]
> * add a temporary timeline event informing the user AFTER it was merged, to inform the user about the feature so that they can disable it if they don't like it

This can copy the JSX from:

-  https://github.com/refined-github/refined-github/pull/5643
