### ISSUE TITLE
Add undo button for `sync-pr-commit-title` and `clear-pr-merge-commit-message`

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4606]
Since these 2 features are "destructive", maybe we should add a button to allow the user to undo them in place.

<img width="704" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/126858267-7bfce07f-f625-4b8b-ab00-ed4ec9bc3a4b.png">

How:

- both features should try to add that notice if they changed the content
- the original value of the title is stored in the `value` attribute and the textareas’s is in the `textContent` property
- the button should read these 2 original values, set them back, and disappear

The logic should probably be in `sync-pr-commit-title.tsx`:

- `export function addNotice() {add notice if it doesn't exist}`
- `function onButtonClick() {removeButton && remove `sync-pr-commit-title`’s checkbox}`

Related:

- https://github.com/sindresorhus/refined-github/issues/3964

FYI: `sync-pr-commit-title` has 2 parts:

- sets the commit title to the PR title
- changes the PR title

**Comment by jedwards1211** [comment]
@fregante I'm wondering if `clear-pr-merge-commit-message` should be disabled by default...we had a CI process break because it was relying on the PR description being automatically included in the merge commit message.  One of our engineers already changed that process to look up the associated PR description, but it caught us by surprise, I had no idea `refined-github` was clearing the merge commit message.

**Comment by jedwards1211** [comment]
or maybe a better default would be a button to clear the commit message instead of an undo button

**Comment by fregante** [comment]
> should be disabled by default.

We don’t have features disabled by default. 

> we had a CI process break because it was relying on the PR description being automatically included in the merge commit message.

Sorry to hear that but that’s not a common scenario. Also the feature is visible and can be disabled. 

> I had no idea refined-github was clearing the merge commit message.

There’s a clear message just below the field that specifically mentions Refined GitHub. 

- https://github.com/refined-github/refined-github/pull/6019

> maybe a better default would be a button to clear the commit message 

I already tried but it was not well received, it complicated things a lot and “automation > manual actions”

- https://github.com/refined-github/refined-github/issues/5155

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/6181
