### ISSUE TITLE
`quick-file-edit` links should not be AJAXed

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4638]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

Some links are AJAXed but GitHub returns the whole page, so the page will break immediately/once you make another navigation:

- ~~`latest-tag-button`: https://github.com/sindresorhus/refined-github/pull/4631#discussion_r682548229~~

  **EDIT**: no longer a bug, see https://github.com/sindresorhus/refined-github/pull/4641#issuecomment-901225714

- `edit-files-faster`: 

  https://user-images.githubusercontent.com/44045911/128181902-0a128898-53f5-4890-8f43-a2081501667b.mov

  This is harder to fix because we need to find a way to disable the AJAX behavior

### Example URL

https://github.com/sindresorhus/refined-github

### Browser(s) used

Chrome

**Comment by fregante** [comment]
Weird. Some links are automatically ajaxed, others need an attribute. The edit links don't have any attributes.

As for #4631 we can make sure it's using the right selector for that.

**Comment by kidonng** [comment]
> Some links are automatically ajaxed, others need an attribute. The edit links don't have any attributes.

I guess there are no "automatically ajaxed" things. Links in a container with `[data-pjax]` are all ajaxed, they don't need to have the attribute individually. The edit links are in this container:

```html
<div role="grid" aria-labelledby="files" class="Details-content--hidden-not-important js-navigation-container js-active-navigation-container d-md-block" data-pjax>
```
