### ISSUE TITLE
`linkify-labels-on-dashboard` is broken

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4640]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

From https://github.com/sindresorhus/refined-github/issues/4491#issuecomment-864557196

### Example URL

https://github.com/

### Browser(s) used

Chrome

**Comment by yakov116** [comment]
@kidonng I think your screen shot is incorrect. The feature made the following clickabe.

![image](https://user-images.githubusercontent.com/16872793/128191475-7832f061-b028-423a-af1c-9b0fad315bcd.png)

**Comment by kidonng** [comment]
@yakov116 The "Recent activity" used to be on top of "All activities" and has labels in it which is also linkified by Refined GitHub. I've never actually noticed a label appearing in "All activity" so I thought about the case in the screenshot.

However I think if we can linkify the labels in the popup that would also be awesome

**Comment by yakov116** [comment]
But that has nothing to do with the dashboard. I think that would be a new feature request.

**Comment by fregante** [comment]
-> https://github.com/sindresorhus/refined-github/issues/4643

**Comment by fregante** [comment]
> But that has nothing to do with the dashboard. 

I think that's incorrect and this feature request is right:

https://github.com/sindresorhus/refined-github/blob/c201bf251385f36d756438329ca5dfe2109c1883/source/features/linkify-labels-on-dashboard.tsx#L14

- [ ] Fix feature
- [ ] Drop references to Recent activity 
- [ ] Update screenshot

**Comment by fregante** [comment]
I see that there was a screenshot in the first post and the removal of it confused me a bit at first. Sorry for the noise 😃
