### ISSUE TITLE
Filter "We went looking everywhere, but couldn't find those commits" notification

### ISSUE THREAD

**Issue by rvl** [refined-github/refined-github#4648]
### Description

Is there some way to change that really annoying "We went looking everywhere, but couldn't find those commits" screen which comes from clicking a PR update notification where the branch was force pushed.

Perhaps it could:
1. Show a better message (illustration below).
2. Just skip the annoying message and show the new diff.
3. Filter out Notifications which come from force pushes.

Cheers

### Screenshot

Current:
![image](https://user-images.githubusercontent.com/1019641/128656957-6ff4174e-3c0c-473b-88f7-0ca547918a7e.png)

Possible improvement:
![image](https://user-images.githubusercontent.com/1019641/128657180-a47df2a0-f6f0-42be-8441-dc791c04eaf0.png)

### Example URL

https://github.com/sindresorhus/refined-github/pull/4646/files

**Comment by fregante** [comment]
I don't remember we have that information exactly. GitHub already shows what happened anyway

**Comment by gregoirenovel** [comment]
It would be nice to skip the annoying message and show the new diff, as suggested by @rvl 
The extension could "auto click" the "latest changes here" link to save a click and:
- see the latest changes automatically
- actually clear the notification

**Comment by fregante** [comment]
I’d accept a PR to simply drop `/files` from the links on the notifications page so they always automatically point to the Conversation tab. Every time a notification leads me to the Files tab (for a single commit) I never know what to do with that information, I always have to see the whole Files or recent conversation.


_Originally posted by @fregante in https://github.com/refined-github/refined-github/issues/6646#issuecomment-1655867618_

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/2779

**Comment by rvl** [comment]
Hi @fregante, sorry it's been a while.

I _could_ make such a PR to drop `/files` from the notifications link. That would remove the silly "we went looking everywhere" message.

Although, as I remember, part of the problem for me was that I was getting notifications which were quite confusing. Because sometimes it seemed to me like nothing had changed in the PR since the last time I clicked it. Actually, the branch had been updated with a force push. Can we do anything to make the notification more useful and informative?

**Comment by fregante** [comment]
> Can we do anything to make the notification more useful and informative?

We can't change the notification itself, but by dropping the `/files` part you will end up on the Conversations tab, where every change and (force) push will be visible
