### ISSUE TITLE
Raw / Source of comment.

### ISSUE THREAD

**Issue by jtagcat** [refined-github/refined-github#4714]
### Description

Sometimes, while referencing other's comments, just copying (or selecting and replying) doesn't work that well.

 - Add a ~~'raw'~~ 'View source' button.

### Screenshot

![image](https://user-images.githubusercontent.com/38327267/130875744-6b1881c3-907b-4ccd-bfcb-e735948f7fea.png)

### Example URL

https://github.com/sindresorhus/refined-github/issues/3543

**Comment by j4k0xb** [comment]
Could this please be reconsidered?
I needed it many times in the past, it's rarely the case that you're a collaborator and pressing <kbd>R</kbd> misses *a lot* of crucial information

Example: https://github.com/relative/synchrony/issues/62#issue-1695052483, multiple `*` chars get removed
idk why the author didn't use codeblocks but here it would be useful to view the raw content

**Comment by SavageCore** [comment]
I created my own user-script to add this functionality. Comments and PRs welcome!

https://github.com/SavageCore/github-comment-view-source
