### ISSUE TITLE
Improve the file action buttons on a commit

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4722]
### Description

When viewing a file on a specific commit/tag/whatever (not on a branch), the file action buttons (open in GitHub desktop, edit and delete) have tooltips "You must be on a branch to *", however they are not disabled but pointing to the login page along with a redirect to the same page, which is quite confusing:

```
https://github.com/sindresorhus/refined-github/blob/3775e52/source/features/useful-not-found-page.tsx
⬇️
https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fsindresorhus%2Frefined-github%2Fblob%2F3775e52%2Fsource%2Ffeatures%2Fuseful-not-found-page.tsx
```

I suppose we can improve the buttons a bit:

- One option is to disable them entirely. GitHub does put a `.disabled` class but that doesn't invalidate the links.
- Another option is to have these buttons work like if we are on the default branch, maybe with a prompt "Do you want to take this action on the default branch?"
- Make them work like `default-branch-button` or just point the user to `default-branch-button`, something like that.

### Screenshot

![image](https://user-images.githubusercontent.com/44045911/130963079-3d1f68e9-1e61-4290-9254-0c8c935fec04.png)

### Example URL

https://github.com/sindresorhus/refined-github/blob/3775e52/source/features/useful-not-found-page.tsx

**Comment by kidonng** [comment]
I just noticed something similarly (in spirit): on a PR you don't have write access to, the "Edit file" and "Delete file" is disabled:
![image](https://user-images.githubusercontent.com/44045911/135742863-722eafe0-f4dc-4e13-8e41-da2ac977d7c9.png)

Would be cool if they become "Edit on default branch" and "Delete on default branch".

**Comment by fregante** [comment]
I think that won't make sense on PRs. I don't want to just edit the file, my intention is to edit the PR

**Comment by kidonng** [comment]
That makes sense. The intention is to simplify the following steps to one click:

1. Click "View file"
2. Click `default-branch-button`
3. Click edit button

If the original request in this issue is resolved, the second step can be saved.
