### ISSUE TITLE
PR list: changes requested, but resolved (actually pending review).

### ISSUE THREAD

**Issue by jtagcat** [refined-github/refined-github#4730]
### Description

![image](https://user-images.githubusercontent.com/38327267/131193047-e235e0e9-1ad2-49cd-9e3f-efae36521dd8.png)

Changes were requested, **but** they were resolved, and re-review was requested.

As such, the state should rather be 'pending review' or related.

This would probably require using the API.

### Example URL

https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

**Comment by fregante** [comment]
The state is still "Changes requested" and we can't changed that, but we *could* add an additional "Review requested" icon ***if*** the review request came after the change request. 

In short I want to avoid the situation where 2 reviews are requested, 1 review is added, and technically this would still be in a "1 review requested" state… even though 1 review was just added.

**Comment by fregante** [comment]
I think this feature would require too much data to be fetched and the lack of interest doesn't seem to justify it. I'd ask GitHub for this or even just add a filter for "review requested". The closest filter is "await review from you"

https://github.com/refined-github/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+user-review-requested%3A%40me
