### ISSUE TITLE
The user’s CSS is injected before Refined GitHub’s

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4731]
The CSS field in the options is supposed to be used as overrides to Refined GitHub's styles but it's actually injected earlier than RG's, so RG ends up overriding it instead. 

We need to find alternative solutions for the injection. For example:

- how does Stylus inject them?
- can it be registered via contentScript.register()? Does the behavior differ in Chrome's polyfill?
- is there any new way to register stylesheets? For example some CSSOM api

**Comment by eqvinox** [comment]
>     * how does Stylus inject them?

Ostensibly in the same way — because it has exactly the same result, i.e. doesn't work either.  Screenshot:

![css2](https://user-images.githubusercontent.com/1715611/131217631-db6fe2f7-f6ce-4706-8faf-3f5e85179f0a.png)

**Comment by fregante** [comment]
Wow. Thanks for checking and for the screenshot!

**Comment by cheap-glitch** [comment]
> ...is injecting duplicate styles when navigating to different pages via AJAX:

Can't reproduce this on Firefox.

> can it be registered via contentScript.register()?

Yes we can register CSS using `contentScript.register()`, or use [`tab.insertCSS()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/insertCSS) directly like your polyfill does.

> is there any new way to register stylesheets? For example some CSSOM api

I haven't found an API to register a whole stylesheet, but we could use [`insertRule()`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule) on the main RGH stylesheet to append the user-CSS to it. (Although that might mean manually splitting the CSS into several rules before injecting it.)

**Comment by fregante** [comment]
> > ...is injecting duplicate styles when navigating to different pages via AJAX:
> 
> Can't reproduce this on Firefox.

I assume this is https://github.com/refined-github/refined-github/issues/4827#issuecomment-956768588

**Comment by fregante** [comment]
> or use [`tab.insertCSS()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/insertCSS) directly like your polyfill does.

That'd mean keeping track of each load from the background page. That API does it automatically (in Firefox)

> I haven't found an API to register a whole stylesheet

https://developers.google.com/web/updates/2019/02/constructable-stylesheets

Not sure if it's cross-browser yet

**Comment by eqvinox** [comment]
So… the Tab size workaround has broken somewhere along the way (Firefox 94? Refined GH update? I don't know…)

I now need to have this in my Custom CSS to get 8-char tabs:

```
:root * {
    -moz-tab-size: 16 !important;
    tab-size: 16 !important;
}
[data-rgh-whitespace="tab"] {
    background-size: calc(var(--tab-size, 8) * 1ch) 1.25em !important;
}
```

I have no clue why it needs "16" for the tab size now, I looked through font settings but can't find any difference in size or anything. I'm not a web developer at all, so I'm not sure where to look. The "8" value is correctly propagated into `tab-size`. But it's only 4 wide in the diff/"files changed" view. But the background visualization arrows are sized for 8. It's super confusing and annoying :disappointed:

**Comment by fregante** [comment]
> So… the Tab size workaround has broken somewhere along the way

Refined GitHub dropped the custom tab size in https://github.com/refined-github/refined-github/releases/tag/21.10.4 because GitHub now lets you customize it directly. 

- https://github.com/refined-github/refined-github/issues/4806
- https://github.com/refined-github/refined-github/pull/4833

Your custom CSS can be avoided. Also it's off-topic here.

**Comment by cheap-glitch** [comment]
> Not sure if it's cross-browser yet

It's only supported in Chrome & derived: https://caniuse.com/?search=adoptedStyleSheets.

We could use `contentScript.register` on Firefox and `adoptedStyleSheets` on Chromium-based browsers. Although I don't know if either of these methods can guarantee that user styles take precedence over RGH's.

Or, maybe we could register an empty CSS file directly in `manifest.json`, and modify its contents at runtime?

**Comment by fregante** [comment]
> We could use `contentScript.register` on Firefox and `adoptedStyleSheets` on Chromium-based browsers

One is enough, it's poly filled.



> Although I don't know if either of these methods can guarantee that user styles take precedence over RGH's

The native version probably does, the polyfill I'm not too sure, even if there's a test for it (but it occasionally fails I think)



> Or, maybe we could register an empty CSS file directly in `manifest.json`, and modify its contents at runtime?

Can't

**Comment by fregante** [comment]
Let's use `contentScript.register` in the background script, right here:

https://github.com/refined-github/refined-github/blob/b9c951ae7e151164940662e178e83ce68e0c4553/source/background.ts#L11

**Comment by fregante** [comment]
This is actually kind of a pain because:

- even with `contentScript.register`/`insertCSS` we can't guarantee that the order is what we expect
- there's no way to catch the injection of the static CSS file, although we could detect it via `getComputedStyle`
- an installation might have multiple CSS due to Enterprise support, so this should probably be done in the content script instead of the background page, because that would be rather [complicated](https://github.com/fregante/webext-options-sync-per-domain/blob/master/index.ts)

Could something as simple as `document.body.prepend(<style/>)` work? The rest of the stylesheets should be in the HEAD and `refined-github.css` presumably has the same weight.

CSS layers could be a solution, but still [no Chrome/Safari support.](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer#browser_compatibility)

**Comment by kidonng** [comment]
> CSS layers could be a solution, but still [no Chrome/Safari support.](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer#browser_compatibility)

Actually recently released [Chrome 99 adds support to layers](https://developer.chrome.com/blog/new-in-chrome-99/#layers), but still.
