### ISSUE TITLE
`unfinished-comments` not working if user hasn't filled all required fields

### ISSUE THREAD

**Issue by WEGFan** [refined-github/refined-github#4737]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

1. Open the [example URL](https://github.com/sindresorhus/refined-github/issues/new?assignees=&labels=under+discussion&template=3_discussion.md)
2. Write something in comment, leaving the title field empty
3. Switch to another tab, "(Draft comment)" doesn't show in tab title
4. Write something in title, switch to another tab
5. "(Draft comment)" shows in tab title

I guess it's because when the title field is empty, "Submit new issue" button is disabled because title is required, however RGH thinks the issue is being submitted according the code here:

https://github.com/sindresorhus/refined-github/blob/7e96d94b06d8f522fdbc5baeb9277f7c2b3da2fc/source/features/unfinished-comments.tsx#L13

### Example URL

https://github.com/sindresorhus/refined-github/issues/new?assignees=&labels=under+discussion&template=3_discussion.md

### Browser(s) used

Firefox 91.0.2 & Chrome 92.0.4515.159

**Comment by fregante** [comment]
Suggested solution: https://github.com/sindresorhus/refined-github/pull/4826#discussion_r720666321
