### ISSUE TITLE
Cannot read property 'append' of null, GH Enterprise

### ISSUE THREAD

**Issue by seglo** [refined-github/refined-github#4747]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

This plugin used to work with my company's GitHub enterprise, but something broke in the past few weeks.

```
refined-github.js:1910 ❌ faster-pr-diff-options 21.8.22 GHE → TypeError: Cannot read property 'append' of null
    at init (refined-github.js:5465)
    at runFeature (refined-github.js:1935)
    at setupPageLoad (refined-github.js:1948)
    at HTMLDocument.<anonymous> (refined-github.js:1971)
```

There are some other info level messages about a personal access token required, but not sure what that's about.

### Screenshot

![image](https://user-images.githubusercontent.com/1148412/131368582-28cadead-ee76-4b64-b9ab-7167d3375517.png)

### Console errors

```shell
ℹ️ update-pr-from-base-branch → Personal token required for this feature
refined-github.js:1909 ℹ️ remove-label-faster → Personal token required for this feature
refined-github.js:1909 ℹ️ bugs-tab → Personal token required for this feature
refined-github.js:1910 ❌ faster-pr-diff-options 21.8.22 GHE → TypeError: Cannot read property 'append' of null
    at init (refined-github.js:5465)
    at runFeature (refined-github.js:1935)
    at setupPageLoad (refined-github.js:1948)
    at HTMLDocument.<anonymous> (refined-github.js:1971)
refined-github.js:1910 Search issue
refined-github.js:1911 https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+Cannot%20read%20property%20'append'%20of%20null
refined-github.js:1915 Open an issue
refined-github.js:1915 https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=1_bug_report.md&title=%60faster-pr-diff-options%60%3A+Cannot+read+property+%27append%27+of+null&body=%0A%3C%21--+Please+also+include+a+screenshot+if+the+issue+is+visible+--[redacted]%28chrome-extension%3A%2F%2Fhlepfoohegkhhmjieoechaddaejaokhf%2Fbuild%2Frefined-github.js%3A5465%3A60%29%0A++at+runFeature+%28chrome-extension%3A%2F%2Fhlepfoohegkhhmjieoechaddaejaokhf%2Fbuild%2Frefined-github.js%3A1935%3A24%29%0A++at+setupPageLoad+%28chrome-extension%3A%2F%2Fhlepfoohegkhhmjieoechaddaejaokhf%2Fbuild%2Frefined-github.js%3A1948%3A40%29%0A++at+HTMLDocument.%3Canonymous%3E+%28chrome-extension%3A%2F%2Fhlepfoohegkhhmjieoechaddaejaokhf%2Fbuild%2Frefined-github.js%3A1971%3A60%29%0A%60%60%60%0A%09
refined-github.js:1909 ℹ️ bugs-tab → Personal token required for this feature
```

### Example URL

https://ghe.internal.zone/Org/Repo/pull/497/files

### Browser(s) used

Vivaldi (Chrome)

**Comment by busches** [comment]
What version of GHE? Not seeing an error for this feature. Also can you be more descriptive with your URL? Doubt this was running on the repos homepage.

**Comment by seglo** [comment]
> What version of GHE?

GitHub Enterprise Server 2.22.15

> Also can you be more descriptive with your URL? Doubt this was running on the repos homepage.

I can't reproduce the issue on github.com and the GHE instance is private.  The format of the URL was:

https://github.svc.internal.zone/Org/Repo/pull/497/files

**Comment by williammck** [comment]
Seeing similar issues on Enterprise Cloud / GitHub.com.
pjax appears to be breaking Refined Github on PR pages.

Trying to run `bisect` to find the issue doesn't work, https://github.com/sindresorhus/refined-github/blob/d8cadc830723728ab5c32f36cea31ea3f6aee814/source/helpers/bisect.tsx#L54 `document.body` is somehow null.

`highlight-deleted-and-added-files-in-diffs` is breaking due to https://github.com/sindresorhus/refined-github/blob/d8cadc830723728ab5c32f36cea31ea3f6aee814/source/features/highlight-deleted-and-added-files-in-diffs.tsx#L43 trying to call `cloneNode` on undefined.

Sometimes refreshing the page can get it to work. non-Enterprise repos are encountering similar issues. De-authing with GHEC doesn't seem to help.

**Comment by busches** [comment]
I cannot recreate on GHE 3.0. We're open to patches, but keep in mind that 2.22 is out of support in about six weeks. https://docs.github.com/en/enterprise-server@2.22/admin/release-notes#2.22.15

**Comment by fregante** [comment]
In short, this selector needs to be updated. PR welcome to fix it if it's a minimal fix.

https://github.com/sindresorhus/refined-github/blob/d8cadc830723728ab5c32f36cea31ea3f6aee814/source/features/faster-pr-diff-options.tsx#L73

**Comment by busches** [comment]
Closing as 2.22 is no longer supported as of 2021-09-23 and 3.0 (the next version) doesn't have the issue.
