### ISSUE TITLE
Make copying file contents instantaneous

### ISSUE THREAD

**Issue by aheckler** [refined-github/refined-github#4802]
### Description

GitHub has just added a button that does the same thing:

https://github.blog/changelog/2021-09-20-quickly-copy-the-contents-of-a-file-to-the-clipboard/

This would seem to make `copy-file` unnecessary, but I'm not sure what the usual procedure is when this happens.

### Screenshot

![Markup on 2021-09-20 at 20:04:06](https://user-images.githubusercontent.com/5512652/134092591-8fd5fc5e-5c32-40c8-a38d-ceb6fa810a73.png)

### Example URL

https://github.com/sindresorhus/refined-github/blob/main/readme.md

**Comment by fregante** [comment]
Neat! Too bad GitHub doesn’t show it on mobile though… where Refined GitHub does 😃

 
![DE6F612D-899F-43DA-B43F-D896ACEC2C73](https://user-images.githubusercontent.com/1402241/134115179-69711515-eff1-494c-af6c-6fc085be5b74.png)

**Comment by aheckler** [comment]
@cheap-glitch Which browser are you using? The GitHub post I linked in the OP does say:

> This feature is available in most desktop web browsers.

So if you're using an uncommon browser, maybe that's the reason?

**Comment by fregante** [comment]
I think they're hiding it based on the useragent 😬 because it's not showing on the iPhone or if I set the "iPhone emulator" and then refresh.

**Comment by gamemaker1** [comment]
I'm using Firefox and not seeing it

**Comment by kidonng** [comment]
This doesn't seem to be on Gists yet.

**Comment by fregante** [comment]
So… GitHub’s feature is slower because it (will) probably work on partial diffs as well, whereas ours only works if the full file is available on the page.

Suggestion:

- keep the feature, but override GitHub’s button where we can, to make it instantaneous.

**Comment by kidonng** [comment]
What else can we do here? @fregante are you interested in making our copy button like GitHub if it's not present?
