### ISSUE TITLE
`comments-time-machine-links` breaks after review comments

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4813]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

It seems the solution commited in https://github.com/sindresorhus/refined-github/commit/b3cf351c1e1b4c975fe2370e470f3657c7551409 doesn't work anymore.

Also I think we should make the feature work on review comments instead of skipping them.

### Console errors

```shell
❌ comments-time-machine-links 0.0.0 → TypeError: Cannot read properties of undefined (reading 'attributes')
    at init (refined-github.js:4829)
    at runFeature (refined-github.js:8013)
    at refined-github.js:15952
    at Set.forEach (<anonymous>)
    at HTMLElement.run (refined-github.js:15951)
```

### Example URL

https://github.com/sindresorhus/refined-github/pull/1932#pullrequestreview-226419297

### Browser(s) used

Chrome

**Comment by fregante** [comment]
> Also I think we should make the feature work on review comments instead of skipping them.

👍 

The hard part has basically been finding the comment time, because it's not always inside the comment element.
