### ISSUE TITLE
`show-associated-branch-prs-on-fork` not working on organizations

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4822]
_Originally posted by @fregante in https://github.com/sindresorhus/refined-github/issues/4772#issuecomment-917599860_

### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

The feature works on https://github.com/kidonng/refined-github/branches

But not on: https://github.com/bfred-it-org/github-sandbox/branches

<img width="832" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/132982471-3af3a507-a9c9-44e4-9f41-50bafafb8d1a.png">

It shows the local PR: https://github.com/bfred-it-org/github-sandbox/pull/1
Not the PR in the upstream repo: https://github.com/fregante/github-sandbox/pull/8

### Example URL

https://github.com/bfred-it-org/github-sandbox/branches

### Browser(s) used

Safari 15

**Comment by yakov116** [comment]
One second @fregante it is working

https://github.com/bfred-it-org/github-sandbox/branches/all

Unless I am missing somthing

**Comment by fregante** [comment]
Indeed I can see it working:

### Native
<img width="176" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/177401617-2a4ed287-4f4b-4ba2-bd33-d4ecbbd7ba3a.png">

### RGH

<img width="128" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/177401636-16e9f196-0fdf-4fa1-b0de-b2fae9bbf8c1.png">


But see my notes:

> It shows the local PR: [bfred-it-org/github-sandbox#1](https://github.com/bfred-it-org/github-sandbox/pull/1)
> Not the PR in the upstream repo: [refined-github/sandbox#8](https://github.com/refined-github/sandbox/pull/8)

Is this expected? Is it "not working" simply because the branch already has a PR? Probably can be closed in that case 🤔

**Comment by yakov116** [comment]
> simply because the branch already has a **_local_** PR?

If I understood you correctly. Yes.

This feature will only work if the compare button is there.

**Comment by fregante** [comment]
Thanks for checking! I'm not sure how I ended up on this issue
