### ISSUE TITLE
Drop `view-markdown-source` feature

### ISSUE THREAD

**Issue by iamandrewluca** [refined-github/refined-github#4834]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

GitHub announced native `view-markdown-source` that makes this feature duplicated if using refined-github

https://github.com/sindresorhus/refined-github/blob/main/source/features/view-markdown-source.tsx
https://twitter.com/github/status/1443572280924147717

### Screenshot

![image](https://user-images.githubusercontent.com/1881266/135468539-89a51253-1949-4d56-b01d-cff9455a2873.png)

### Example URL

https://github.com/sindresorhus/refined-github/blob/main/readme.md

### Browser(s) used

Any

**Comment by yakov116** [comment]
Did they addd it to all

`() => pageDetect.isSingleFile() && /\.(mdx?|mkdn?|mdwn|mdown|markdown|litcoffee|rst)$/.test(location.pathname),`

**Comment by iamandrewluca** [comment]
- [ ] [`rst`](https://github.com/iamandrewluca/issue-view-markdown-source/blob/main/file.rst)
- [x] [`mkdn`](https://github.com/iamandrewluca/issue-view-markdown-source/blob/main/file.mkdn)
- [x] [`mkd`](https://github.com/iamandrewluca/issue-view-markdown-source/blob/main/file.mkd)
- [ ] [`mdx`](https://github.com/iamandrewluca/issue-view-markdown-source/blob/main/file.mdx)
- [ ] [`mdwn`](https://github.com/iamandrewluca/issue-view-markdown-source/blob/main/file.mdwn)
- [x] [`mdown`](https://github.com/iamandrewluca/issue-view-markdown-source/blob/main/file.mdown) 
- [x] [`md`](https://github.com/iamandrewluca/issue-view-markdown-source/blob/main/file.md)
- [x] [`markdown`](https://github.com/iamandrewluca/issue-view-markdown-source/blob/main/file.markdown)
- [ ] [`litcoffee`](https://github.com/iamandrewluca/issue-view-markdown-source/blob/main/file.litcoffee)

**Comment by fregante** [comment]
@yakov116 don't add the label to issues unless they're the only reference to it (which usually isn't the case), or else:

<img width="537" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/135581322-ec276e56-f812-4660-8f56-801a8a1abe08.png">

**Comment by fregante** [comment]
We can drop this feature altogether. The [missing extensions](https://github.com/refined-github/refined-github/issues/4834#issuecomment-931400778), if still missing, can be reported to GitHub

**Comment by kidonng** [comment]
Will miss it for `.mdx` and `.rst` 🥲

**Comment by fregante** [comment]
On the other hand, the source is still available in the blame view in these cases. 

Contacting GitHub support would be useful

**Comment by kidonng** [comment]
`?plain=1` works, I just don't remember them all the time 🤷

**Comment by stdedos** [comment]
Seems to me that Github was contacted https://github.com/community/community/discussions/7999#discussioncomment-1690899, but they ignore us 🤷 

Would've been nice to revive that 🙏
