### ISSUE TITLE
Option to delete all workflow runs (cleanup old workflows)

### ISSUE THREAD

**Issue by ssbarnea** [refined-github/refined-github#4838]
### Description

While github added the ability to remove old workflow runs and documented it on https://github.blog/changelog/2020-07-07-github-actions-ability-to-delete-workflow-runs/ it failed to provide an option to delete all workflow runs for a particular workflow.

This means that user may need to perform tens-hundreds of manual deletions to cleanup the list of project workflows.

### Screenshot

![](https://sbarnea.com/ss/Screen-Shot-2021-10-01-12-15-20.91.png)

### Example URL

https://github.com/ansible-community/ansible-lint/actions/workflows/arch_packaging.yml

**Comment by fregante** [comment]
Tentatively allowing it, hopefully it can be done without excessive code, including a paginated API. We have a `v3paginated` method that we can use to retrieve all this data if necessary.

The main concern is that we do not have proper handling of API rate limits so if this requires hundreds of requests it might very well fail — or make the feature too big for RG.

**Comment by fregante** [comment]
This is best done via cli: https://github.com/cli/cli/issues/6449

Closing because it's too complex/niche here
