### ISSUE TITLE
`remove-label-faster` was renamed to `quick-label-hiding`, when it actually removes the label

### ISSUE THREAD

**Issue by altrisi** [refined-github/refined-github#4839]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

In #4694, `remove-label-faster` was renamed to `hide-label-faster` (and later it has been renamed to `quick-label-hiding`).

However, the feature actually removes labels from the issues/PRs it's used on, not just hides them.

Originally mentioned in https://github.com/sindresorhus/refined-github/pull/4694#issuecomment-921944668.

### Example URL

https://github.com/sindresorhus/refined-github/blob/main/source/features/quick-label-hiding.tsx

### Browser(s) used

Firefox 92

**Comment by fregante** [comment]
Should be `quick-label-removal` probably
