### ISSUE TITLE
Linkify usernames in issues created from discussions

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4854]
### Description

When you click the "Create issue from discussion" link in a discussion, GitHub creates an reference issue with some additional markup:

![image](https://user-images.githubusercontent.com/44045911/135726601-b573e247-92f8-46ed-b7ad-300d9785bc41.png)

As you can see the username is just ordinary text, so it doesn't get a link:

![image](https://user-images.githubusercontent.com/44045911/135718787-c3f84ba6-d76c-4281-a276-d641eafd138b.png)

We may linkify the username (`[type="discussions-op-text"] > p:first-child > sup:first-child strong`), possible question: is it important enough?

Maybe this could be an extension to `linkify-user-edit-history-popup` (and rename that feature to something like `linkify-usernames`, not sure)

### Example URL

https://github.com/vercel/vercel/issues/6794

**Comment by fregante** [comment]
This should be relatively easy as part of an existing "linkify" feature. The only concern is that this feature is so rare that it's basically non-existent as far as RGH is concerned. If you find a way to integrate it in a lightweight way, feel free to send a PR, but I'm going to close this for now.

**Comment by kidonng** [comment]
Indeed, the usage is not particularly high:

https://github.com/search?o=desc&q=discussions-op-text+is%3Aissue&s=created&type=Issues

<img width="705" alt="image" src="https://user-images.githubusercontent.com/44045911/177761247-a56bd651-bf37-435b-8c3b-398b1a4ad749.png">
