### ISSUE TITLE
Maintainer invitation

### ISSUE THREAD

**Issue by sindresorhus** [refined-github/refined-github#4868]
@cheap-glitch and @kidonng: We appreciate all your good contributions lately. Would you be interested in joining Refined GitHub as a maintainer? 🙏

**Comment by cheap-glitch** [comment]
Yup, definitely! :+1: I'll try to make more time for it too.

This is probably a separate discussion, but should we make a RGH org? Since there's now a number of maintainers working on the project. Just a thought, not sure if worth the hassle :smile:

**Comment by sindresorhus** [comment]
@cheap-glitch Awesome! Glad to have you onboard.

**Comment by sindresorhus** [comment]
> This is probably a separate discussion, but should we make a RGH org? Since there's now a number of maintainers working on the project. Just a thought, not sure if worth the hassle 😄

We have discussed this before, but I forgot about it. Done.

**Comment by cheap-glitch** [comment]
Thank you for the sponsorship too @sindresorhus!

**Comment by kidonng** [comment]
I would be honored to join the wonderful maintainers of Refined GitHub!

Now I'm going to edit my email filters and retrain my muscle memory of typing `sindresorhus/refined-github` 😃

**Comment by sindresorhus** [comment]
@kidonng Great. Welcome :)

**Comment by yakov116** [comment]
Welcome aboard!

**Comment by kidonng** [comment]
@waldyrious members join an organization in private by default, they will need to change the status themselves. Currently most people should show up there.

Now that things have settled, this can be closed 😃

**Comment by waldyrious** [comment]
> Currently most people should show up there.

Confirmed, I now can see cheap-glitch, fregante, kidonng, notlmn, sindresorhus and 
yakov116 listed there :)
