### ISSUE TITLE
Organization updates

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4869]
Now that the repository has been moved to a standalone organization (`sindresorhus/refined-github` -> `refined-github/refined-github`), we may want to do a few things:

- Update all links, not necessary but saves a (or many) redirect(s)

  EDIT: done in 4232313404c9d4afaa711217ce539680b7e3799e

- Also transfer https://github.com/fregante/github-sandbox to the organization (or make a new one) as a testbed
- @fregante what do you think of transferring some of related Node.js packages to the organization (e.g. [github-url-detection](https://github.com/fregante/github-url-detection) and [shorten-repo-url](https://github.com/fregante/shorten-repo-url)). They feel like a part of "Refined GitHub ecosystem" and will possibly catch more attention.

**Comment by fregante** [comment]
FYI the transfer also broke some meta features, for example this title isn't linkified https://github.com/refined-github/refined-github/issues/4870

**Comment by yakov116** [comment]
Until the next release, since `usNotRefinedGithub` url was changed.

**Comment by busches** [comment]
@yakov116 you can. I follow the repo, but to be honest I don't use most features since Enterprises are silly and don't just use GH for everything. 😀

**Comment by kidonng** [comment]
Issue resolved (again), thanks everyone 🎉!
