### ISSUE TITLE
Duplicate features  on `isGlobalConversationList`

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4870]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

<details>
<summary>Outdated</summary>

If the global Pull Requests page (the one on the header, i.e. https://github.com/pulls) is opened with some filters (`?q=...`), there is a _high chance_ that the "Merged" filter added by `extend-conversation-status-filters` is placed after "Open" instead of "Closed":

![image](https://user-images.githubusercontent.com/44045911/136051044-065e9a2d-3fc9-4b31-bb6e-5077e2abdf5f.png)

There are also some other glitches if it happens:
- There may be multiple check icons (as shown in the screenshot above)
- Clicking the "Merged" filter doesn't navigate you two a new URL

</details>

- If navigate back and forth, some feature are duplicated:

![image](https://user-images.githubusercontent.com/44045911/136051653-b3751ce1-fc26-4a46-8189-cfbf1d7948bc.png)

- `conflict-marker`
- `open-all-conversations`

### Example URL

https://github.com/pulls?q=is%3Aopen+is%3Apr+author%3A%40me+archived%3Afalse

### Browser(s) used

Chrome

**Comment by fregante** [comment]
Can't replicate with your link (Safari)

**Comment by kidonng** [comment]
The previous PR doesn't fix it for `global-conversation-list-filters`. Can still reproduce in 21.12.21:

![image](https://user-images.githubusercontent.com/44045911/147364710-64179ce7-e65e-494b-9869-dde8d4b79398.png)

**Comment by cheap-glitch** [comment]
> Can still reproduce in 21.12.21

Weird, I can't reproduce this on 21.12.12 (Firefox)

**Comment by cheap-glitch** [comment]
@kidonng can you still see this? If yes, what are the exact steps you followed to get the bug?

**Comment by kidonng** [comment]
@cheap-glitch Yes, I still see this. Just click "Merged" and go back and forth to reproduce.
