### ISSUE TITLE
Linkify repo reference in repo transfer notice

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4873]
### Description

After transferring a repo, GitHub will mention the new address but it won't make it clickable. This is likely because the repo isn't always immediately ready, but… still not good UX.

We can extend the usual branch linkifier feature and rename it to be a broader `linkify-missing-github-references` or something.

<img width="709" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/136082687-7bbe40f8-d663-4175-b62b-0f1c3dca100e.png">

```html
<div class="flash flash-full flash-notice ">
  <div class="container-lg px-2">
    <button class="flash-close js-flash-close" type="button" aria-label="Dismiss this message">
      <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" class="octicon octicon-x">
    <path fill-rule="evenodd" d="M3.72 3.72a.75.75 0 011.06 0L8 6.94l3.22-3.22a.75.75 0 111.06 1.06L9.06 8l3.22 3.22a.75.75 0 11-1.06 1.06L8 9.06l-3.22 3.22a.75.75 0 01-1.06-1.06L6.94 8 3.72 4.78a.75.75 0 010-1.06z"></path>
</svg>
    </button>
    
      Moving repository to refined-github/github-sandbox. This may take a few minutes.

  </div>
</div>

```

### Example URL

The feature appears on https://github.com/dashboard after a transfer

**Comment by fregante** [comment]
@kidonng did https://github.com/refined-github/refined-github/pull/4820 cover this?

**Comment by kidonng** [comment]
No, you can tell from the `include`.

**Comment by fregante** [comment]
Merged into https://github.com/refined-github/refined-github/issues/4740
