### ISSUE TITLE
`clean-conversation-filters`: undefined has no properties

### ISSUE THREAD

**Issue by cheap-glitch** [refined-github/refined-github#4874]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

Seeing this error in the console (even after clearing the cache):

```text
❌ clean-conversation-filters 21.10.4 → TypeError: undefined has no properties
    hideProjects moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/build/refined-github.js:7027
    init moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/build/refined-github.js:7037
    runFeature moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/build/refined-github.js:2043
    setupPageLoad moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/build/refined-github.js:2056
```

This probably happens now because RGH is an org, so the org-related code might be the culprit:
https://github.com/refined-github/refined-github/blob/e7260f66ce34f579e93f5a77e6e10425ed84d713/source/features/clean-conversation-filters.tsx#L46-L60

(The `'[data-hotkey="p"]'` element is missing on the page.)

### Example URL

https://github.com/refined-github/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

### Browser(s) used

Firefox 92.0.1

**Comment by cheap-glitch** [comment]
@sindresorhus did you by any chance disable Projects in this org? This would explain why I don't see the same error here: https://github.com/npmhub/npmhub/issues.

**Comment by sindresorhus** [comment]
Yes, we don't use them.

**Comment by kidonng** [comment]
This error is cramming the console on this repo and somehow Chrome's filter cannot hide it 🙃

**Comment by fregante** [comment]
@kidonng Are you encountering this bug? https://twitter.com/fregante/status/1453125315849490441?s=20
