### ISSUE TITLE
`Cancel` button when creating/editing releases

### ISSUE THREAD

**Issue by tooomm** [refined-github/refined-github#4881]
### Description

This is very similar to https://github.com/refined-github/refined-github/issues/4460.

There is no intuitive way to cancel the creation of a new release or when editing a release and simply go back to the release overview.

### Screenshot

![release](https://user-images.githubusercontent.com/9874850/136281022-21a2093f-981f-4523-8edf-3def5f6af42f.png)

### Example URL

https://github.com/refined-github/refined-github/releases/new

**Comment by yakov116** [comment]
Would easy just to extend https://github.com/refined-github/refined-github/blob/main/source/features/cancel-wiki-edit-button.tsx want to send a PR?
