### ISSUE TITLE
Show all reviews under "Review Requests" tab, not just unreviewed PRs

### ISSUE THREAD

**Issue by zbs** [refined-github/refined-github#4888]
### Description

In github.com/pulls, it shows these tabs
![](https://i.imgur.com/FOCFIDG.png)
Clicking on "Review Requests" shows all PRs that you have been requested as reviewer on, but not reviewed. This means that any time I want to find a PR that I have reviewed (e.g. to see the pusher's responses to my comments), I need to change the query from `review-requested:me` to `reviewed-by:me`. I find this design decision needlessly frustrating, and was hoping your extension has been considering a way to fix that behavior.

### Example URL

github.com/pulls

**Comment by kidonng** [comment]
We can add a "Reviewd" link to `global-conversation-list-filters` feature, just like "Commented" and "Yours".

**Comment by zbs** [comment]
Ideally the solution would be a one-stop shop: a tab that has the combined output of `review-requested` and `reviewed-by`. AFAICT, both of these solutions still only show one of the two modes at a time. 

If the filter drop-down included a `Everything you've reviewed and have been review-requested for` option, I would be game. Especially if the UI remembered my preference, so next time I didn't need to go back into the drop-down.

**Comment by zbs** [comment]
how is this going?

**Comment by cheap-glitch** [comment]
> how is this going?

PR welcome :)

**Comment by fregante** [comment]
We can't change this button but we can add a way to customize the additional links. Refer to this issue for a similar feature that can be then ported to the global filters list:

- https://github.com/refined-github/refined-github/issues/5316

Alternatively just create a browser bookmark 🤷‍♂️ 😃
