### ISSUE TITLE
Drop `sort-milestones-by-closest-due-date`

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4891]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

`sort-milestones-by-closest-due-date` is a little "default search params" feature added more than 4 years ago in #457.

It has a bug, [introduced in the original implementation PR](https://github.com/refined-github/refined-github/pull/457/commits/d2d83fa6b0310c6917c66d820dadcbdbc544495d#diff-1f93cd4783614fe92bbb9d7fba4cd2b31ba1a47c0c2e9b00be36bd3246e5af7fR477). Now I dare you to find it... just kidding.

To reproduce, just go to [some random repo's issue page](https://github.com/microsoft/vscode/issues) and click the "Milestones" link. Now try changing the sort criteria to the default "Recently updated". It won't work because all "milestones" link without explicit criteria are affected.

---

Now you may think, "not a big thing, let's just fix it". Instead, I don't see this feature useful for most people.

- First, the bug has been there for more than 4 years and no one noticed/questioned about it. That alone proves "Milestones" isn't that frequently* used.
  \* To be objective, it is still used more than "Projects", but still.
- Second, GitHub has a sane default in this case. Remember we have a `sort-conversations-by-update-time` feature for this?
- Finally, if you argue (quoting from the [implementation PR](https://github.com/refined-github/refined-github/pull/457#issue-123211247)): "Milestones are used to manage releases; where as the closest one is often more important than the last updated one."

  Well... that's not how things work in reality. Reusing [the random repo](https://github.com/microsoft/vscode/milestones?state=open&direction=asc&sort=due_date) example, you will find it just sorts milestone by their ID/create time, from old to new. If that doesn't sound like an issue to you, take a look at the [closed](https://github.com/microsoft/vscode/milestones?state=closed&direction=asc&sort=due_date) milestones.

  Think about it again, VSCode is maintained by a company, with a fixed release cycle. That's not how most open source projects work. Let's try again with [another random but real™️ open source project](https://github.com/fish-shell/fish-shell/milestones?direction=asc&sort=due_date). Wait, the results looks very similar...

  OK, so you want a project from someone familiar, [here's one](https://github.com/sindresorhus/got/milestones?direction=asc&sort=due_date).

  Did you noticed something? Yes, (almost) all these milestones **do not have a due date**. "That's not how milestones are used!" Sure, but **making due dates aren't how most open source projects work either.** That's why the "sane" default we set aren't particularly useful for people.

---

So with all those said, my intention is pretty simple: drop this feature fixing an issue most people never have.

### Example URL

https://github.com/microsoft/vscode/milestones?state=open&direction=asc&sort=due_date

### Browser(s) used

Chrome

**Comment by kidonng** [comment]
@fregante what are your thoughts on this? Drop it or fix the bug first?

**Comment by fregante** [comment]
🚀 👉 yessssss
