### ISSUE TITLE
Delete fork button on merged PR

### ISSUE THREAD

**Issue by Metacinnabar** [refined-github/refined-github#4892]
### Description

Add an extra button to delete the fork when merging a PR into a head repository from a fork.

### Screenshot

![forkk](https://user-images.githubusercontent.com/45357714/136483254-a1d7efb3-6c67-45a3-b23d-e812de0409c0.png)

### Example URL

https://github.com/refined-github/refined-github/pull/4883

**Comment by busches** [comment]
I see this all the time on GHE, is it not built in?

**Comment by Metacinnabar** [comment]
Doesn't seem like it, sadly. I could be mistaken though.

**Comment by fregante** [comment]
It was removed because GitHub added it natively: https://github.com/refined-github/refined-github/issues/1786

**Comment by fregante** [comment]
It's there: 

<img width="925" alt="Screen Shot 17" src="https://user-images.githubusercontent.com/1402241/139593824-8839d78d-8af5-4869-a1c7-5770e6d63379.png">

It requires many clicks to delete it, but we can't make it one-click here. `quick-repo-deletion` is one-click but it depends on some elements that only appear on the fork’s own page, not in the PR.

I think the native solution is fine. Your alternative would be to scroll back up, visit your fork and then delete it there with one click
