### ISSUE TITLE
Store renames permanently and use them in our meta features

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4897]
Currently we store renames as temporary migrations:

https://github.com/refined-github/refined-github/blob/54f7a885aec1cb97eaccd55456bf90c95e7d6968/source/options-storage.ts#L21

It might be ok for now, but ideally it would be the opposite:

- have a regular, static object/map with the renames
- use the object to create all migrations at once
- use the object for the feature linkifier and `rgh-feature-description`

We can also drop the dates and make them permanent, even recovering the past renames we had over the years

_Originally posted by @fregante in https://github.com/refined-github/refined-github/issues/4865#issuecomment-934402648_

**Comment by kidonng** [comment]
A starting point: https://github.com/refined-github/refined-github/pull/4865/commits/6bb969834b146577707dd9c56c9aeed4d5bf2d88

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/4801

**Comment by fregante** [comment]
> A good starting point: [`6bb9698` (#4865)](https://github.com/refined-github/refined-github/pull/4865/commits/6bb969834b146577707dd9c56c9aeed4d5bf2d88)

It's not, refer to the first comment here

**Comment by kidonng** [comment]
> > A good starting point: [`6bb9698` (#4865)](https://github.com/refined-github/refined-github/pull/4865/commits/6bb969834b146577707dd9c56c9aeed4d5bf2d88)
> 
> It's not, refer to the first comment here. All `featureWasRenamed` calls should be replaced by a single migration function that reads the `renamedFeatures` object/array

I'm not saying the exact implementation details, it's just to demonstrate the - - feature seen time should at least be handled.
