### ISSUE TITLE
Add `multiple-linked-prs-dropdown` feature

### ISSUE THREAD

**Issue by cheap-glitch** [refined-github/refined-github#4901]
### Description

I often use the links in the issue list to jump to their corresponding PR, and it always bugged me that GitHub didn't offer that shortcut when there were 2 or more linked PR for a single issue.

So I propose to fix this with a feature (tentatively) named `multiple-linked-prs-dropdown`, which looks like this:
![screenshot-1633873218](https://user-images.githubusercontent.com/46634000/136698346-3e3c48ff-40a9-4846-a707-426db67e29e8.png)

It can also work in reverse for PRs closing multiple issues:
![screenshot-1633873201](https://user-images.githubusercontent.com/46634000/136698370-a70b0356-de49-4b70-ab9d-bf5bc03ff8ee.png)

(So I guess the correct name would be `multiple-linked-prs-and-issues-dropdown` but that's quite a mouthful.)

### Example URL

https://github.com/refined-github/refined-github/issues?page=2&q=sort%3Aupdated-desc+linked%3Apr

**Comment by fregante** [comment]
I'll close this because it seems to require quite a bit of JSX, but if you feel like picking up your PR again feel free to complete it and merge it.

**Comment by cheap-glitch** [comment]
> I'll close this because it seems to require quite a bit of JSX

Yeah, it's too much code for a relatively niche feature. Plus the API call was kind of a hack to begin with.
