### ISSUE TITLE
`releases-tab` causes duplicate highlights

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4903]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

![image](https://user-images.githubusercontent.com/44045911/136703076-295201a0-7fea-4a63-b9aa-177953bdd69e.png)

To reproduce:

1. Go to a repo homepage (https://github.com/refined-github/refined-github)
2. Click the release links **on the right** (the tab we added does not have this issue)
3. Notice the duplicate highlights

This is similar (?) to #4782.

The cause could be #4902 but note that it occurs **regardless of whether you enable the feature preview or not**.

### Example URL

https://github.com/refined-github/refined-github

### Browser(s) used

Chrome

**Comment by cheap-glitch** [comment]
It also happens when you select a single release from the list, but _only with the preview active_.\
:point_right: Basically, this is caused by the AJAX navigation.
