### ISSUE TITLE
Add "Involved" filter to conversation search

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4905]
### Description

I just saw this today: https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-a-user-thats-involved-in-an-issue-or-pull-request

`conversation-filters` and `global-conversation-list-filters` could have an additional `involved:@me` filter.

Related: 
- https://github.com/refined-github/refined-github/issues/4888#issuecomment-938062175

### Example URL

https://github.com/refined-github/refined-github/issues

**Comment by kidonng** [comment]
Maybe this is also a good chance to make a list of available filters in the codebase, so we don't end up using `getUsername()` here and `@me` there.

**Comment by fregante** [comment]
Technically we should be able to use @me everywhere already. I had replaced all getUsername calls a couple years ago but it broke GHE. PR welcome for that.
