### ISSUE TITLE
Add `small-user-avatars` feature

### ISSUE THREAD

**Issue by moussetc** [refined-github/refined-github#4906]
### Description

Goal: be able to **identify which user has created the PRs directly from the PR list**

Current behaviour: 
- the GitHub userid is displayed, but when that userID is made of random numbers because of your company policy, it's _not that useful_...
- you can hover on the user id of a PR to see user details (including full name and avatar) but it's less useful that having the info displayed automatically for each PR without having to hover on each one

There are several ways to do that:
- add user avatar for graphic recognition
- add full username after the userid (like on PR comments)
- replace userid by username (reduce cluttering but would probably not be used by teams that work with meaningful userids)
- ....

### Example URL

https://github.com/refined-github/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

**Comment by kidonng** [comment]
Quickly made it up:

https://user-images.githubusercontent.com/44045911/136881363-29a6df8b-7dcf-4134-90ab-3854262b31b8.mov

**Comment by fregante** [comment]
PR welcome to add a `pr-list-avatars` feature to only add avatars.

**Comment by yakov116** [comment]
Wrote something up. Not sure I like this at all.

@kidonng want to take a look at https://github.com/refined-github/refined-github/tree/avatar_list

I can't figure out the CSS.

**Comment by kidonng** [comment]
I've been using this ever since I wrote it. You just have to get used to it 😉

You can [take a look at my script](https://github.com/kidonng/cherry/blob/725edf6775f526093a79d42ec6be2a384229ab95/scripts/github-conversation-list-avatars.user.tsx) for reference.

**Comment by fregante** [comment]
@kidonng mind sending a PR to merge that feature into Refined GitHub so we can close this issue?

**Comment by ChillarAnand** [comment]
@kidonng Did you get a chance to submit PR?

**Comment by kidonng** [comment]
Thanks for the heads up, I only returned to this project just recently. Will work on it.
