### ISSUE TITLE
release updates should be collapsible and collapsed by default

### ISSUE THREAD

**Issue by rahgurung** [refined-github/refined-github#4911]
### Description

Release updates from people you follow should be collapsible as it takes the whole of my home feed when someone does a lot of releases, it should be collapsed by default too. Thus the user will only expand the person's releases, he wants to see.

### Screenshot

![Screenshot from 2021-10-11 19-04-37](https://user-images.githubusercontent.com/30543444/136799544-108f2f1a-977c-46f6-947d-602f110e3277.png)

### Example URL

github.com

**Comment by kidonng** [comment]
Have you disabled the `hide-noisy-newsfeed-events` feature?

**Comment by gurrrung** [comment]
> Have you disabled the `hide-noisy-newsfeed-events` feature, which hides all release events? That may not be what you want but you will likely get used to it.

Thanks, that resolved my issue.
