### ISSUE TITLE
`clean-dashboard` is uncollapsing the releases too

### ISSUE THREAD

**Issue by gurrrung** [refined-github/refined-github#4916]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

`clean-dashboard` should uncollapse only the starred updated. Releases updates in the newsfeed should be kept collapsed.

### Example URL

github.com

### Browser(s) used

Chrome

**Comment by cheap-glitch** [comment]
> Also this happens when `clean-dashboard` is disabled, so there must be some style leaks

My bad, this was caused by my own custom CSS :sweat:
