### ISSUE TITLE
`expand-all-hidden-comments` doesn't work for PR conversations

### ISSUE THREAD

**Issue by Nokel81** [refined-github/refined-github#4921]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

I would expect that the `expand-all-hideen-comments` feature to work on expanding large sections of hidden conversations on PRs. But it does not, it only expands 20 at a time.

### Example URL

https://github.com/lensapp/lens/pull/3910

### Browser(s) used

firefox

**Comment by cheap-glitch** [comment]
I'm afraid this feature cannot be restored, because the form's `action` attribute doesn't contain the `first` parameter anymore:
```
/lensapp/lens/pull/3910/timeline_more_items?after_cursor=Y3Vyc29yOnYyOpPPAAABfErOH7gH2gAyNzQ1NjQzOTk4OjVjNDFiODYxMmUxMmMzZTUzMWEwNjQxYWM5NTdiZDQ4NGFlYzEyYzk%3D&before_cursor=Y3Vyc29yOnYyOpPPAAABfMRyWigAqTk1MzQyMTM2NQ%3D%3D
```
So we can't modify the number of items that will be loaded.

**Comment by fregante** [comment]
> So we can't modify the number of items that will be loaded.

Indeed, even those cursors are base64 of private data:

<img width="541" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/147803809-26cf3776-6646-4cbd-b2b0-ff9c69b2e20e.png">

**Comment by cheap-glitch** [comment]
Should we drop the feature then?

**Comment by yakov116** [comment]
Yes

**Comment by fregante** [comment]
Maybe @artusm has a better idea since it was implemented by him at some point

**Comment by fregante** [comment]
We can implement it with a loop. Didn't we do that at some point? Or maybe I'm just thinking of the dashboard infinite scroll

On alt-click:

1. Let it load
2. Wait for next button appearance
3. click it
4. GOTO 1 three times

**Comment by kidonng** [comment]
I met this issue a few days ago, and thought we have an open issue for it (it does!)

If we are going to fix it with a loop, mind possible network error.

**Comment by SuperSandro2000** [comment]
When looking at PRs like https://github.com/NixOS/nixpkgs/pull/165406 this feature is very handy if you don't want to click and wait for a minute. Can we please try to workaround this issue somehow?

**Comment by cheap-glitch** [comment]
@SuperSandro2000 Sure! Pull requests are welcomed ;)
