### ISSUE TITLE
Option to always show name of branch in PR list

### ISSUE THREAD

**Issue by mrkev** [refined-github/refined-github#4924]
### Description

Hello! I love refined Github. I have been yearning for a feature that would make make Github much more useful to me: to always have branch names for PRs shown.

I noticed an issue suggesting this already exists (https://github.com/refined-github/refined-github/issues/190) and is closed, because the feature was implemented in https://github.com/refined-github/refined-github/pull/1641.

For a second I thought maybe I had it disabled, but after looking through the settings and reading the thread in the PR, I realized this functionality was actually removed before the PR was merged: https://github.com/refined-github/refined-github/pull/1641#issuecomment-446735058.

**I'm happy to have a jab at implementing this**, but am wondering— it sounds like a configuration on an existing feature. Should I add it as a new feature? Is there a way to make existing features configurable?

## Motivation

This would be useful to me on two fronts. I imagine people with similar workflows might find it useful for similar reasons too.

- **This feature would help me find my own PRs.** I'm often working on several branches, all of which have associated PRs. My workflow has me working on several PRs a week, so it's hard to keep track of the "PR Name" <=> "branch name" map. 
- **This would be very useful to quickly checkout PRs by other contributors/co-workers.** I imagine the branch names to be copy-able (maybe with a copy button next to them, or just by virtue of being selectable.
- **This can help me keep my repo clean**. Some people manually delete: seeing which branches are merged in the list-view, without having to open them one-by-one makes the process much quicker. I personally use a script, so this is not always a concern of mine. Nonetheless, if a PR has local changes that weren't pushed before it was merged (say, a rebase to the latest `main`), it won't show up in `git branch --merged` and I it won't be automatically deleted for me. I'd find this feature useful in those cases.

## Resolution

As previously mentioned, I can have a jab at this. Thought I'd open a discussion before attempting to implement it to get a general sense of direction pertaining the questions above **Should I add it as a new feature? Is there a way to make existing features configurable?**

### Screenshot

Using the screenshot in https://github.com/refined-github/refined-github/pull/1641 as a starting point, I'd imagine it looking something like this:

![49306954-03468f00-f4d4-11e8-82e6-08b0bb54841f](https://user-images.githubusercontent.com/1285131/137408004-8a9dd73c-9d3e-4e5b-9e09-d1363c49935a.png)

### Example URL

https://github.com/refined-github/refined-github/pulls

**Comment by cheap-glitch** [comment]
I'm -0 on this, seems like a lot of noise on an already dense page (as already said in the PR you mentioned).

> it sounds like a configuration on an existing feature. Should I add it as a new feature? Is there a way to make existing features configurable?

RGH features are not made to be configurable, see https://github.com/refined-github/refined-github/issues/2960#issuecomment-606765658 for reasons.

> so it's hard to keep track of the "PR Name" <=> "branch name" map

I feel GitHub already gives a decent overview on [the repo branches page](https://github.com/refined-github/refined-github/branches), and it's further enhanced by RGH (`show-associated-branch-prs-on-fork`).

Also if you give your PR the same title as the first commit of your local branch, you can jusk ask git:
```bash
for branch in $(git --no-pager branch | cut -c3- | grep -v '^main$'); do
	printf '%-35s%s\n' "${branch}" "$(git --no-pager log --oneline "main..${branch}" | tail -1)"
done
```

<details>
<summary>Output for me in RGH repo</summary>

```
add-multiple-prs-dropdown          b40dd75a Add `multiple-linked-prs-dropdown` feature
fix-clean-conv-filters             0e98b9c4 Fix console error in `clean-conversation-filters`
fix-next-gh-action                 5fd9657f Fix deduplication of `next-scheduled-github-action`
fix-on-pr-merge-panel-open         afd6efab Fix console errors caused by `onPrMergePanelOpen`
fix-open-all-notifications-error   deb2d63f Fix console error in `open-all-notifications`
meta-add-lint-for-imports          842eaadd Meta: Add lint rule to sort imports in cascading order
refactor-tab-highlighting          4247572f Meta: Refactor custom tab highlighting
```
</details>

> This would be very useful to quickly checkout PRs by other contributors/co-workers

GitHub's own official CLI is pretty handy for this:
```
gh pr checkout <PR number>
```

> Nonetheless, if a PR has local changes that weren't pushed before it was merged (say, a rebase to the latest main), it won't show up in git branch --merged and I it won't be automatically deleted for me

I don't know which script you use, but [`git-cleanup` from git-toolbelt](https://github.com/nvie/git-toolbelt/blob/master/git-cleanup) is pretty good at this (especially with the `-s` option & combined with `git pull --prune`).

**Comment by diskostu** [comment]
Why not make this feature optional? We already have the ability to turn features on and off.
"Noise" is highly subjective. What's noise for one person, is helpful for another, and vice versa. Let's have choice.

**Comment by SunsetTechuila** [comment]
> Why not make this feature optional?

https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#2-it-makes-sense-as-a-default-for-everyone

<img width="950" height="286" alt="Image" src="https://github.com/user-attachments/assets/1563c8b0-7295-4b77-aa6c-7028f40a383e" />

> "Noise" is highly subjective.

https://github.com/refined-github/refined-github/blob/3b0552081803834b5f3646b31d17d7501fd9b2cb/readme.md?plain=1#L398
