### ISSUE TITLE
[Releases UI Refresh] Always expand the view

### ISSUE THREAD

**Issue by panva** [refined-github/refined-github#4941]
### Description

The new Releases UI (currently in preview) truncates the contents of individual releases. Because this behaviour has shown to be undesirable for some users (me included) there's been a query parameter option [added](https://github.com/github/feedback/discussions/6138#discussioncomment-1498963) to always expand them.

I'd love an option in refined-github to always have the releases expanded, e.g. always decorate the `/releases` URL with `(?|&)expanded=true`

### Screenshot

default:
<img width="869" alt="Screenshot 2021-10-19 at 9 22 58" src="https://user-images.githubusercontent.com/241506/137862543-569c5e19-9e45-4116-ac8a-d3098338d8e2.png">

with query parameter:
<img width="872" alt="Screenshot 2021-10-19 at 9 23 17" src="https://user-images.githubusercontent.com/241506/137862583-321e353b-a7e0-4b85-b8de-b675c354965b.png">

### Example URL

https://github.com/evanw/esbuild/releases

**Comment by yakov116** [comment]
I see more releases.

**Comment by fregante** [comment]
> I would rather have a "Expand all release notes" link that points to `?expanded=true`.

I like that. @panva can you update your PR?

**Comment by yakov116** [comment]
Is it just me? It looks like github changed it to always be expanded.

**Comment by kidonng** [comment]
From https://github.com/github/feedback/discussions/6138#discussioncomment-1555668:

> We did a review with an accessibility expert internally at GitHub this week and found that the current truncated experience does not play nicely with screen readers after much consideration we are going to be removing truncated releases from the default experience in the next week.

So this is no longer relevant, closing.

**Comment by fregante** [comment]
Man, refined GitHub had it easy when GitHub was dormant. Then Microsoft bought it and it's *move fast break things* every day 😰

**Comment by kidonng** [comment]
> Then Microsoft bought it and it's _move fast break things_ every day 😰

Don't forget our tests run on GitHub Actions which is also brought by them 😄
