### ISSUE TITLE
Dim more bots

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4952]
### Description

Extend `dim-bots` to include more bots:

- @actions-user: belongs to GitHub. it seems to be used by GitHub's example initially, and now a [widely used](https://github.com/search?o=desc&q=author%3Aactions-user&s=committer-date&type=Commits) placeholder besides `github-actions[bot]`.
- @web-flow: belongs to GitHub. See its bio
- @ImgBotApp: [usage](https://github.com/search?o=desc&q=author%3AImgBotApp&s=committer-date&type=Commits)
- @bors (@rust-lang bot user) and [bors](https://github.com/apps/bors) (GitHub app). Note these are "merge bots" in the sense that the duty of them is to merge commits, so they are already dimmed out by `mark-merge-commits-in-list`. But I think it makes sense enough to fold them via `dim-bots`.
- @Octomerger: as can be seen in https://github.com/github/docs

Adding more popular bots from https://github.com/marketplace is welcome.

### Example URL

N/A

**Comment by cheap-glitch** [comment]
Maybe @snyk-bot from https://snyk.io? (It's the successor of Greenkeeper).

**Comment by kidonng** [comment]
Reopening due to https://github.com/refined-github/refined-github/pull/5192#discussion_r767273718

**Comment by fregante** [comment]
Just push a commit to make that single change 😃
