### ISSUE TITLE
Highlight non-trivial changes in feature files history

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4953]
### Description

Differentiate regular commits from lint/meta commits in our codebase, making the history page for feature files more useful.

We used to have a "Feature history" dropdown that does similar things, but it was dropped because of inconvenience to work with. More context on #4804.

### Example URL

https://github.com/refined-github/refined-github/commits/main/source/features/action-used-by-link.tsx

**Comment by fregante** [comment]
We can use `dim-bots`’ code and classes to dim the commits, only changing the filter that decides what to hide

**Comment by fregante** [comment]
Here's the regex to use to identify these commits and dim them. Something like:

```js
observe('.commit', commit => {
  if (metaRegex.test(commit.title)) {
    commit.classList.add('rgh-dim-commit')
  }
})
