### ISSUE TITLE
Add dimming effect to `quick-comment-hiding`

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4954]
### Description

Mimic the dimming effect of "Update comment" in our `quick-comment-hiding` feature.

One question though, when unhiding a comment, GitHub behaves just like our `quick-comment-hiding` at the moment, i.e. they do nothing special. Maybe it's not worth the effort?

More context in https://github.com/refined-github/refined-github/pull/4857#issuecomment-934082247

### Example URL

https://togithub.com/refined-github/refined-github/pull/4857

**Comment by fregante** [comment]
ys plz

**Comment by fregante** [comment]
Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it.
