### ISSUE TITLE
Dim notifications from bots

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4956]
### Description

Apart from commits and conversations, notifications from bots can also be noisy. We can take the same approach as `dim-bots` to dim them in the notifications list.

More context on https://github.com/refined-github/refined-github/issues/4523#issuecomment-871094215. Note while the aforementioned issue says "this is covered in its entirety by that other extension", I think it would also be a nice addition to the native interface.

### Example URL

https://github.com/notifications

**Comment by fregante** [comment]
I'm not sure this is useful in pratice. The notification already landed in your inbox and you must deal with it. Dimming it won't change that fact. I

**Comment by kidonng** [comment]
That makes sense, but it makes notifications from human stand out, which are usually more important than notifications from bots.

**Comment by fregante** [comment]
:+0.5:

**Comment by fregante** [comment]
I prefer this proposal:

- https://github.com/refined-github/refined-github/issues/5780
