### ISSUE TITLE
Project Boards: Select default sorting method

### ISSUE THREAD

**Issue by gronert-m** [refined-github/refined-github#4957]
### Description

**Goal: Sorting options are not just in the moment but can be set as default.**

In issue #982 the idea that multiple ways of sorting ought to be introduced was discussed. This has since happened (see screenshot, taken from that same issue).

However, the default will always revert to "Newest". That is, I can sort by something else, but if I leave the site and go back, I am again having the info shown sorted by "Newest".

I would like to be able to pin one project, or create some order in the boards. As a team we can agree on naming conventions whose alphanumeric order (if ordered by Name) will create a hierarchy. Thus I would like to have "sort by name" to be set as my default. Others may want some other structure as default.

I apologize if this is possible or has been discussed elsewhere. In my online research I have not found an answer to this.

### Screenshot

![image](https://user-images.githubusercontent.com/63501500/138248138-adfadac5-173c-4ecd-8a96-0a04ad17499c.png)

### Example URL

https://github.com/worldbank/gld/projects

**Comment by gronert-m** [comment]
Thanks! I take that this might go beyond what is feasible but appreciate the help.

I will close the issue.

**Comment by kidonng** [comment]
Reopen until we implement https://github.com/refined-github/refined-github/issues/4957#issuecomment-948458819 (or if it is rejected by other maintainers).
