### ISSUE TITLE
Make check results easier to read

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4958]
### Description

- Related: #3136

[Some](https://github.com/refined-github/refined-github/issues/4809#issuecomment-946336652) [people](https://github.com/refined-github/refined-github/issues/4809#issuecomment-948083620) [argue](https://github.com/refined-github/refined-github/issues/4809#issuecomment-948085193) that always expanding check lists is useful, but it could potentially make the interface be overwhelmed by them.

Instead of always expanding the list, we can add a "Expand" link which applies the style when clicked, next to the "Show/Hide all checks" link. Additionally, we can also:

- Dim (and/or fold) **skipped** and **successful** checks
- Highlight **failing** checks

### Example URL

https://github.com/swc-project/swc/pulls

**Comment by kidonng** [comment]
> [The issue is that it also opens automatically](https://github.com/refined-github/refined-github/issues/4809#issuecomment-944061001
)

So if we go for them "show all" buttons that would be two clicks and has a weird user experience. A separate button would be better.

**Comment by fregante** [comment]
The button already is "show ALL checks", we can't add a "show ALL BUT REALLY ALL checks" right next to it.

If the list is already open automatically, there should ideally be an expand button. 

Maybe: We can restore the "Show all checks" button even when the list is open, in this case, but it's not a perfect solution.

<img width="609" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/139651453-8f5fe279-eacc-4700-8f1d-ccfe9085bdad.png">

**Comment by kidonng** [comment]
> The button already is "show ALL checks", we can't add a "show ALL BUT REALLY ALL checks" right next to it.

I'm referring to pages with expanded by default checks, e.g. if there are running or failing ones.

**Comment by fregante** [comment]
Mockup please

**Comment by dashed** [comment]
Unsure if this is off-topic, or if it deserves a new Issue ticket, but often, I'd like to see a convenience button to to open "Details" of  just **failing** (required) checks as new windows/tabs. For Sentry (https://github.com/getsentry/sentry), we have a number of checks, which can be cumbersome to scroll thru to just find and open the failing checks:

<img width="927" alt="Screen Shot 2021-12-12 at 11 05 36 PM" src="https://user-images.githubusercontent.com/139499/145750912-8b2dd195-03c0-419f-901d-fdbf6a03c225.png">

Because all of this is packed tightly in a small real estate, I'm +1 on making this easier to read.

**Comment by fregante** [comment]
Related:

- https://github.com/refined-github/refined-github/issues/3136

**Comment by janpio** [comment]
Additional realted but not 100% identical requests that were closed as duplicates:
- https://github.com/refined-github/refined-github/issues/5621
- https://github.com/refined-github/refined-github/issues/5062

**Comment by fregante** [comment]
This issue is not "related" to https://github.com/refined-github/refined-github/issues/3136, but it's just a different wording. Closing

**Comment by kidonng** [comment]
I see #3136 as a bigger task that involving manipulating DOM, while I opened this smaller one to propose some style-only changes.

**Comment by fregante** [comment]
Other than recently with `:has`, what you're suggesting also required manipulating the DOM, it's just a different type (add class vs move nodes). The complexity is the same, both require an active MutationObserver.

**Comment by dashed** [comment]
For anyone interested in this, @asottile-sentry has created a user script that sorts required failing checks first: https://github.com/getsentry/sentry-user-scripts#fails-first

**Comment by fregante** [comment]
@dashed Refined GitHub will have that soon thanks to #5858 

However browser support is limited at the moment.
