### ISSUE TITLE
`minimize-upload-bar` replacement icon and tooltip don't communicate that it's for arbitrary file upload

### ISSUE THREAD

**Issue by akien-mga** [refined-github/refined-github#4960]
### Description

I'm a happy user of Refined GitHub, but every now and then I've found myself having to disable the extension to be able to upload ZIP files to comments, as RG hides the upload bar button.

Today I finally decided to look into config options to see if I could disable that and found that the bar is actually converted to an icon button via `minimize-upload-bar`, which is good. The problem is that I never noticed this icon because I use this feature to upload ZIP files (minimal reproduction projects) on a daily basis, and I never made the connection to the picture icon.

I did look for an "attach" or "upload" button and couldn't find one, so I thought you folks had just removed the feature altogether as files can also be uploaded via drag and drop.

So my suggestion would be to replace the icon by one which is more reminiscent of an upload or file attachment feature.

That's just my workflow and I'm aware that others might use this first and foremost to attach screenshots, so I just throw this here as a suggestion :)

<details>
<summary>List of supported file types for GH file upload</summary>

![image](https://user-images.githubusercontent.com/4701338/138274716-db5caf84-3221-4469-9e33-449c1ae67018.png)

</details>

### Example URL

https://github.com/refined-github/refined-github/issues/new?assignees=&labels=enhancement%2C+under+discussion&template=2_feature_request.yml

**Comment by fregante** [comment]
It may be time to drop this feature. RGH used to be more about _cleaning the interface_ than it is now, as it's become not just "for power users" but for anyone.

**Comment by kidonng** [comment]
I do like the current style. Maybe we just swap the icon and tooltip.

**Comment by fregante** [comment]
Pinging dr @SiNdReSoRhUs

**Comment by fregante** [comment]
> I do like the current style

Agreed. GitHub actually has the same style on mobile, including the "Picture" button that can also select any files. Refined GitHub just extends this to the desktop.

<img width="300" src="https://user-images.githubusercontent.com/1402241/234843009-53c58746-8a61-4575-a119-2624ef5d0f19.jpg">

`minimize-upload-bar` is CSS feature and it's not worth complicating it to just replace an icon.
