### ISSUE TITLE
`file-finder-buffer` loses focus after navigation with Gitako

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4963]
### Please ensure:

- [ ] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

https://user-images.githubusercontent.com/44045911/138296324-c35ac5a4-2f20-4f21-9d9f-59c8998d1a82.mov

If you refer to the screenshot of the feature, you will notice it preserves the focus after navigation:

![](https://user-images.githubusercontent.com/1402241/75542106-1c811700-5a5a-11ea-8aa5-bea0472c59e2.gif)

### Example URL

https://github.com/refined-github/refined-github

### Browser(s) used

Chrome

**Comment by cheap-glitch** [comment]
The focus is correctly kept for me on Firefox.

> There is another bug presented in the demo video above: if you are on repository homepage, trigger file-finder-buffer, then navigate to the Code tab, the buffer will show up.

:+1:

**Comment by kidonng** [comment]
No longer reproducible, assuming this is fixed in Gitako.
