### ISSUE TITLE
Drop `clone-branch`

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4964]
### Description

Assuming you are on https://github.com/refined-github/refined-github/branches/all:

## Process to clone a branch with branch dropdown

1. Find the source branch
2. Click the branch name to open it
3. Open the branch dropdown
4. Enter new branch name
5. Click "Create branch"

## Process to clone a branch with `clone-branch`

1. Find the source branch
2. \-
3. Click the "Clone this branch" button
4. Enter new branch name
5. Click "OK"

As you can see the feature only saves one click (second step), I don't think it worth the effort to maintain it, also because I have never used this feature myself (the dropdown is much more convenient, because **you don't have to go to the branch page**).

### Example URL

https://github.com/refined-github/refined-github/branches/all

**Comment by yakov116** [comment]
I have used this so many times when testing a CI.

FYI this creating a branch from the current branch is a new thing. I have never seen it before.
