### ISSUE TITLE
Apply tab size preference to more places

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4966]
### Description

#4833 is a good start but not perfect:

- [Tab size adjustment won't work for regular code blocks (`<pre>`) in comments](https://github.com/refined-github/refined-github/pull/4833/files#r733884651), once we drop the variable from `:root`
- [File blocks in comments use a fixed tab size of 4](https://github.com/refined-github/refined-github/pull/4833/files#diff-54bfb879ebd6799fb6b7e5754d4fa6fe36b05adbd69fd7f5a457a2cc2d85bcf3R10-R11) instead of following user preference
- Tab size adjustment doesn't work for editors

For the second and third points, maybe we can fetch user preference from https://github.com/settings/appearance#tab-size-heading (or look at DOM) and reference it in our code. We can use a long expire timeout since it should be a rarely-changed setting.

Tweaking the editors are just my thoughts though, it may not be trivial or worth the effort.

---

A bit of context about editors:

- [New file](https://github.com/refined-github/refined-github/new/main) and [new gist](https://gist.github.com/) always uses **Spaces** with an indentation size of **2**
- [Editing files indented with **Tabs**](https://github.com/refined-github/refined-github/edit/main/package.json) will always use an indentation size of **8** (or **2** if [there are no indentation](https://github.com/refined-github/refined-github/edit/main/collaborators.md) for the editor to figure out)
- Editing files indented with **Spaces** will always inherit the indentation size of the file

### Example URL

N/A

**Comment by fregante** [comment]
> * [Tab size adjustment won't work for regular code blocks (`<pre>`) in comments](https://github.com/refined-github/refined-github/pull/4833/files#r733884651), once we drop the variable from `:root`
> * [File blocks in comments use a fixed tab size of 4](https://github.com/refined-github/refined-github/pull/4833/files#diff-54bfb879ebd6799fb6b7e5754d4fa6fe36b05adbd69fd7f5a457a2cc2d85bcf3R10-R11) instead of following user preference


Fixed in #5715


> * Tab size adjustment doesn't work for editors

If you still want this, open a new issue so it can be discussed and tracked specifically. As you mentioned:

> it may not be trivial or worth the effort.
