### ISSUE TITLE
`comments-time-machine-links` only works if clicked the three dots menu

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4977]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

`comments-time-machine-links` used to work on all comments automatically. But [`86b173b` (#4893)](https://github.com/refined-github/refined-github/pull/4893/commits/86b173b03a3ad385da7a7a3cabcdef6bb83f236f#r735152647) changed it to work only if you clicked the three dots icon of a comment. This behavior is not documented nor is it commented somewhere.

(Reviews said nothing about it,is the change intended or is it just went unnoticed?)

### Example URL

https://togithub.com/denoland/dotland/issues/1768

### Browser(s) used

Chrome

**Comment by FranklinYu** [comment]
To prevent regression like this in future, shall we add a screenshot of inline links to the documentation?
