### ISSUE TITLE
Support GitHub redirect domains in `shorten-links`

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4981]
### Description

Popular bots like Dependabot and Renovate [uses redirect domains for references](https://github.com/refined-github/refined-github/issues/4480#issuecomment-862357937) instead of linking directly, so they won't flood the original discussion.

We can swap those domains with `github.com`, which is technically also `shorten-links`.

Known redirect domains:

- `togithub.com`* (Renovate)
- `github-redirect.dependabot.com` (Dependabot)

\* This domain has a pretty obvious (and easy to type) name! I highly encourage contributors [use it for demo links](https://github.com/fregante/github-issue-link-status/issues/61#issuecomment-867530395). Also, if this issue is resolved, we can get the best of two worlds: direct links without disturbance.

### Example URL

https://togithub.com/renovatebot/renovate/pull/12293

**Comment by fregante** [comment]
PR welcome in https://github.com/refined-github/shorten-repo-url

**Comment by kidonng** [comment]
@cheap-glitch thanks for implementing it! Unfortunately it is not exactly what I asked for, so reopening.

The important part is this:

> We can swap those domains with `github.com`

Which is to say I would like the links to behave just like they points to `github.com`, without redirects.

**Comment by cheap-glitch** [comment]
> Which is to say I would like the links to behave just like they points to github.com (modifying href), without redirects.

Shouldn't it be a new feature then? Since the goal is not to shorten the anchor text, but to avoid a redirection, this seems outside the scope of `shorten-links` imo.

**Comment by kidonng** [comment]
That makes sense, `shorten-links` should stay as a cosmetic feature.

**Comment by fregante** [comment]
> Which is to say I would like the links to behave just like they points to `github.com` (modifying `href`), without redirects.

Interesting. I'd implement this as a `avoid-redirects` feature that is just a `delegate('a', 'mousedown')` which changes the links before navigation happens.
