### ISSUE TITLE
`preview-hidden-comments` shows "Nothing to preview" after hiding a comment

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4983]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

https://user-images.githubusercontent.com/44045911/138731183-e0629617-140a-42df-868a-81cb2c1ee4f2.mov

Also, the preview content is duplicated, maybe there's some unrelated DOM changes which made the preview run twice.

### Example URL

https://togithub.com/refined-github/refined-github/issues/4976

### Browser(s) used

Chrome

**Comment by fregante** [comment]
Strange, this only happens right after hiding that comment
