### ISSUE TITLE
[Question] Issue icon colors

### ISSUE THREAD

**Issue by lonix1** [refined-github/refined-github#4990]
They just [changed](https://github.blog/changelog/2021-10-26-updates-to-our-issue-status-icons-and-colors/) closed issue icon color from red to purple.

Is there a way I can use this extension to change back to red?

**Comment by kidonng** [comment]
FYI, installing [my user style](https://github.com/kidonng/cherry/tree/master/styles#github) and enable "Blue open issues/pull requests and green closed issues/merge pull requests" option provides an alternative look. (*sadly closed issues are still not red*)

**Comment by sscotth** [comment]
https://github.com/Katsute/GitHub-Red-Issues
