### ISSUE TITLE
Make features with similar names distinctive

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4992]
### Description

We have two features with similar names: `conversation-filters` and `conversation-activity-filter`. It's not clear from the names they do very different things, and I think it's best to distinguish them via a different name.

I suppose rename `conversation-filters` to `more-conversation-filters`, since that's what the feature does actually. It's not adding a whole feature of conversation filters.

### Example URL

https://github.com/refined-github/refined-github/issues

**Comment by kidonng** [comment]
The same could also applies to `quick-review` and `quick-review-buttons`. There could be more.

**Comment by fregante** [comment]
> The same could also applies to `quick-review` and `quick-review-buttons`. There could be more.

I was gonna open an issue for this 😃

**Comment by kidonng** [comment]
Maybe also [`hide-tips`](https://github.com/refined-github/refined-github/blob/main/source/features/hide-tips.css) and [`hide-obvious-tooltips`](https://github.com/refined-github/refined-github/blob/main/source/features/hide-obvious-tooltips.css). I know they are not the same but still.

**Comment by fregante** [comment]
They could even be merged

**Comment by cheap-glitch** [comment]
Side note: while we're at it, `quick-pr-diff-options` should probably be renamed to `quick-diff-options`, since it also runs on commit and compare pages.

**Comment by alirezaayande** [comment]
> ### شرح
> ما دو ویژگی با نام های مشابه داریم: `conversation-filters`و `conversation-activity-filter`. از نام‌ها مشخص نیست که آنها کارهای بسیار متفاوتی انجام می‌دهند، و به نظر من بهتر است آنها را از طریق یک نام متفاوت تشخیص دهیم.
> 
> من فکر می کنم نام را `conversation-filters`به تغییر دهید `more-conversation-filters`، زیرا این همان کاری است که ویژگی در واقع انجام می دهد. این یک ویژگی کامل از فیلترهای مکالمه را اضافه نمی کند.
> 
> ### اسکرین شات
> _بدون پاسخ_
> 
> ### URL مثال
> https://github.com/refined-github/refined-github/issues

I am an unemployed Iranian youth and I have no involvement in foreign policy. Why should I earn money and receive bitcoins and other digital currencies !?

**Comment by fregante** [comment]
Any more suggestions
