### ISSUE TITLE
Enhance Discussions

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4993]
### Description

Ideas for enhancing the Discussions feature on GitHub.

We do a lot for issues and pull requests, but conversations seems to be left out. It's not as frequently used as the former ones but there are indeed many chances to enhance the experience there as well.

What's on my mind:

- [ ] Sort answers by "Top". [An example discussion](https://github.com/vercel/community/discussions/49?sort=top#discussioncomment-739107) where it makes a difference, the linked answer is higher in the thread with "Top" sort.
- [ ] Extend `highest-rated-comment` to Discussions: for "answered" discussions ([example](https://github.com/vercel/vercel/discussions/3684)), GitHub provides a inconspicuous link to the marked answer:

   <img width="789" alt="Screen Shot 2021-10-27 at 22 40 32" src="https://user-images.githubusercontent.com/44045911/139088398-10c2f25c-3271-459b-8d34-170f683b67f3.png">

  We can extend `highest-rated-comment` to Discussions, this way we have a consistent location/appearance across different GitHub features, and most users would expect it that way.
  Alternatively, we could highlight the link provided by GitHub.
  One question on extending `highest-rated-comment`: that feature looks for **reactions** while we generally favor **votes** for Discussions. But this is a topic for a separate issue.

- [ ] Bold usernames in Discussions list: this is forgotten in #4899
- [ ] Link the numbers to commenter in the Most helpful section: this may be useful for maintainers to identity active users, but I agree it's less useful than above
  
  ![image](https://user-images.githubusercontent.com/44045911/139090114-2473edc6-67c4-4c3a-943b-3c03725db211.png)
- [ ] A GitHub bug: when you are in a specific category, the big green "New discussion" button on the top right links to the current category, however the small blue link (only shown in empty category) below doesn't. Probably uncommon enough, not worth fixing it.

   <img width="762" alt="Screen Shot 2021-10-27 at 22 50 35" src="https://user-images.githubusercontent.com/44045911/139090498-627050fa-18ab-49ac-aa80-84259a5ec1ce.png">
- [ ] The formatting toolbar is on the left, but why?

  <img width="923" alt="2021-11-06 23 33 14" src="https://user-images.githubusercontent.com/44045911/140615093-d95e3bd0-3505-41e7-8d0f-6b7d8b3620ed.png">
- [ ] GitHub's monospace textarea option doesn't work there:

  ![image](https://user-images.githubusercontent.com/44045911/140615129-3e27f034-81c1-4eed-95c7-a814f2d83b3c.png)

### Example URL

See above

**Comment by fregante** [comment]
Feel free to suggest more and address them as you see fit, but for now I'll close this issue
