### ISSUE TITLE
Distinguish different status of `conversation-activity-filter`

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4994]
### Description

Currently choosing both "Hide events" and "Hide events and collapsed comments" in `conversation-activity-filter` shows a [red](https://github.com/refined-github/refined-github/pull/4029/commits/215d6c5a807d9f084ea2146446d74ea4e58e9939) eye icon. It will probably be better if they have different appearance to distinguish them.

### Example URL

https://togithub.com/refined-github/refined-github/pull/4029

**Comment by kidonng** [comment]
GitHub's pallette is really conservative, the primary color was green (for open/success), and the rest are purple (for closed/merged), red (for closed/danger), yellow (change request/warning), and probably gray (draft/unactionable).

I choose purple because of recent color changes. Maybe yellow is a better choice.

**Comment by fregante** [comment]
> Maybe yellow is a better choice.

I don’t think it's visible on white

**Comment by fregante** [comment]
We can add a tiny label on one of them:


<img width="291" alt="Screen Shot 10" src="https://user-images.githubusercontent.com/1402241/183050497-7172c6a4-9f39-47f7-8a30-705f951996f7.png">

<img width="291" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/1402241/183050481-3598e402-11bd-4262-b4f1-4e08456394a9.png">

<img width="291" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/1402241/183050489-0f4020fe-a883-40ce-b799-0e398e377b6c.png">


Similar to what GitHub does with whitespace (except that ours is a dropdown, not a button)

<img width="154" alt="Screen Shot 11" src="https://user-images.githubusercontent.com/1402241/183050768-9f371a49-21d9-410b-904a-a92d1970c236.png">
