### ISSUE TITLE
`conversation-activity-filter` doesn't reset its state when opening another page

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4997]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

https://user-images.githubusercontent.com/44045911/139123222-aae0d26b-e680-4955-b989-c169d7f90581.mov

Steps to reproduce:

1. Activate `conversation-activity-filter`
2. Navigate to another discussion
3. Notice it stays "enabled" despite the effect no longer take place

### Example URL

Here

### Browser(s) used

Chrome

**Comment by WardenDrew** [comment]
Can confirm this is happening to me as well, chrome as well. The selection stays the same between pages, but the actual displayed conversation timeline defaults back to showing everything

Is the intended behavior to reset on every page load, or for that setting to be sticky across page loads? The latter would be preferable in my own usage.

**Comment by cheap-glitch** [comment]
@WardenDrew If you want this setting to become persistent, I suggest opening a new issue so it can be discussed there (either as an improvement or a "change request").

Note that such a change would have to benefit the majority of users to be considered for implementation.

**Comment by kidonng** [comment]
Requesting here is OK since we _are_ going to change ("fix") the current behavior anyway. 

But I'm with @cheap-glitch that making it sticky/persistent is unlikely going to happen. However as is often the case, I'm willing to write user scripts (provisional name: Refined Extras™) for these niche wishes.

**Comment by fregante** [comment]
> The latter would be preferable in my own usage

I never implemented that because I'm concerned that people forget about this thing and are susprised when _half the comments are gone._ The "red eye" icon is visible enough when _you just interacted with it_ but not across reloads. It'd need a banner, etc etc…

My solution for this would be to make it togglable/cyclable with a shortcut so that you can just open an issue and press the <kbd>®</kbd> key for example 😜
