### ISSUE TITLE
`conversation-activity-filter` also hides unresolved review comments

### ISSUE THREAD

**Issue by ryzngard** [refined-github/refined-github#5000]
### Description

`conversation-activity-filter` seems to be intended to reduce clutter when looking at a pull request and comments. I haven't found a good combination of settings where I see unresolved comments still though. I thought this was originally handled by https://github.com/refined-github/refined-github/issues/3966 

However, this hides all comments that are pulled from in code files. 

Version Used: `21.10.25`

### Screenshot

Screenshot of "hide events and collapsed comments", where comments from files are hidden. 

![image](https://user-images.githubusercontent.com/475144/139162582-a507f49b-d566-4c7f-806c-a2e047d602d4.png)

### Example URL

https://github.com/dotnet/roslyn/pull/56957

**Comment by kidonng** [comment]
> What you're suggesting would bring it back to the original PR that suggested adding checkboxes and stuff, requiring multiple clicks to get to the core of the feature: leaving unresolved comments visible. 

That's the reason I didn't bother to open an issue myself. But I think hiding only events _or_ resolved comments should be enough most of the time. The change would just make it two clicks instead of one, while opening up for more possiblity. I do think it's worth it.

**Comment by fregante** [comment]
phew we blew past 5000 conversations and we didn't even notice!

## Happy FIVE THOUSANDS @refined-github/maintainers! 🍰

**Comment by sshmaxime** [comment]
I had a hard time realizing that the `conversation-activity-fillter` doesn't provide the ability to hide resolved comments in a PR.

**Comment by kidonng** [comment]
> `conversation-activity-fillter` doesn't provide the ability to hide resolved comments in a PR

Are you referring to resolved comment which are not reviews?

**Comment by sshmaxime** [comment]
@kidonng I'm talking about collapsed resolved comments.  We should be able to hide them completely as welll.

**Comment by fregante** [comment]
@sshmaxime open a new bug issue for that, that should already work.
