### ISSUE TITLE
"Copy permalink" button to use link with short-hash instead of full-hash

### ISSUE THREAD

**Issue by privatenumber** [refined-github/refined-github#5001]
### Description

When clicking "Copy permalink" on a file line entry, it gives me a really long URL like:

```
https://github.com/webpack/webpack/blob/758269e81456c946a96b521ee936dbec99d07132/lib/TemplatedPathPlugin.js#L84
```

I would like it to use the 7-character short-hash instead:
```
https://github.com/webpack/webpack/blob/758269e/lib/TemplatedPathPlugin.js#L84
```

It's more easily readable when sharing the URL.

### Screenshot

<img width="826" alt="Screen Shot 2021-10-27 at 8 34 27 PM" src="https://user-images.githubusercontent.com/1075694/139166605-34f7d29e-bee7-45f3-a2fe-4ef75717a62a.png">

### Example URL

https://github.com/webpack/webpack/blob/758269e81456c946a96b521ee936dbec99d07132/lib/TemplatedPathPlugin.js#L84

**Comment by fregante** [comment]
We already have a feature that shortens links on GitHub: https://github.com/refined-github/refined-github/blob/main/source/features/shorten-links.tsx

I don't think it's worth changing a behavior outside GitHub.com
