### ISSUE TITLE
`clean-dashboard` makes background transparent

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5018]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

![image](https://user-images.githubusercontent.com/44045911/139573659-5c01d927-52d9-4d4a-b6e3-148a74c83991.png)

### Example URL

https://github.com/

### Browser(s) used

Chrome

**Comment by cheap-glitch** [comment]
Not seeing this on Firefox:

![image](https://user-images.githubusercontent.com/46634000/139573854-26bcbbd0-4e22-4500-a459-2e4a6d0ae754.png)

**Comment by fregante** [comment]
Confirmed in Chrome. Safari still looks good. Looks like they changed the background color variable once again

<img width="619" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/139576526-e3977ccb-78a7-47ad-9807-2e0ac2f42ced.png">
