### ISSUE TITLE
Extend `conflict-marker` to PR title

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5019]
### Description

This is like #4086 but for `conflict-marker`.

The info can be obtained from the page directly, no need for API.

### Example URL

https://togithub.com/npm/cli/pull/2912

**Comment by fregante** [comment]
I think this piece of information is not any more important than everything else in the mergeability box, once you're on the PR already:

- CI passes?
- reviews are positive/required?
- branch is up to date?
- etc

I'd be more interested in

- https://github.com/refined-github/refined-github/issues/4086
