### ISSUE TITLE
Hide sponsor items in `hide-noisy-newsfeed-events`

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5020]
### Description

They are similar to follow items which we already hide.

Sponsor items have `.sponsor` classes on them.

### Screenshot

![](https://user-images.githubusercontent.com/44045911/139573659-5c01d927-52d9-4d4a-b6e3-148a74c83991.png)

### Example URL

https://github.com/

**Comment by fregante** [comment]
I was thinking the same when I saw #5018, but sponsorship events are a positive thing in the community so I'd like to keep them visible
