### ISSUE TITLE
`wait-for-build` merges without all checks completed

### ISSUE THREAD

**Issue by 4310V343k** [refined-github/refined-github#5023]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

### Description

![](https://i.imgur.com/yVEFT5A.png)
I checked the `Wait for successful checks` checkbox, pressed the merge button and switched to another tab and window. When i switched back to the PR tab, i noticed that the PR was already merged without all of the checks completed

<details><summary>Console output</summary>

![](https://i.imgur.com/n9GUZ5w.png)

</details>

### Example URL

https://github.com/Terrania/Baystation12/pull/29

### Browser(s) used

Yandex.Browser

**Comment by kidonng** [comment]
> When i switched back to the PR tab, i noticed that the PR was already merged without all of the checks completed

Could you please provide an evidence of this?

**Comment by 4310V343k** [comment]
> > When i switched back to the PR tab, i noticed that the PR was already merged without all of the checks completed
> 
> Could you please provide an evidence of this?

The screenshot?

**Comment by yakov116** [comment]
I have had it when check run one after the next. (Not together)

For example on this repo if you click the check box it will merge before safari test completes.

**Comment by kidonng** [comment]
> The screenshot?

Sorry, I didn't notice the "2 of 5 checks passed". From [your workflow file](https://github.com/Terrania/Baystation12/blob/a859928c7da1d6cef9056c8a0905b873c6d62dbb/.github/workflows/test.yml), I suppose it's the "Maps" check (which has a `matrix`) hadn't passed yet when `wait-for-build` merged the PR.

Implementation-wise [the feature just look at GitHub's check icon](https://github.com/refined-github/refined-github/blob/db1e5682e925cdc7bf3b6e091befe51a3c703b7e/source/github-helpers/pr-ci-status.ts#L20-L38), if GitHub shows the checks as passing, the we assume the checks have passed. The real situation could be what @yakov116 described.

**Comment by fregante** [comment]
I thin it may be time to retire the feature or switch to using the API instead, we can't risk it go through like this.

GitHub’s new merge queue feature might be a good replacement for the feature
