### ISSUE TITLE
`clean-dashboard` doesn't keep right margin when uncollapsing groups

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5024]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

Notice the last item has no right margin:

<img width="692" alt="Screen Shot 2021-10-31 at 19 42 17" src="https://user-images.githubusercontent.com/44045911/139581669-08d4bc61-3712-43c0-8106-ec071bebd644.png">

![image](https://user-images.githubusercontent.com/44045911/139590038-1aa31a17-6260-46a6-8960-cdaaf9f9200e.png)

### Example URL

https://github.com/

### Browser(s) used

Chrome

**Comment by fregante** [comment]
I think this is due to the hiding of the star/unstar buttons, which make it look like there's some extra space. Some `margin-right: 8px` welcome
