### ISSUE TITLE
Button to load all missing repositories that have subscribed issues

### ISSUE THREAD

**Issue by h1nk** [refined-github/refined-github#5038]
### Description

The [`/notifications/subscriptions`](https://github.com/notifications/subscriptions) [feature](https://github.com/isaacs/github/issues/283#issuecomment-471686419) has a `Repository`/`Filter by repository` dropdown on the [page](https://github.com/notifications/subscriptions). Unfortunately it only includes a small and seemingly random (from what I can tell) subset of repositories containing issues you have subscribed to. The filter list is generated by [this](https://github.com/_render_node/query/notification_subscriptions/repository_filter) SSR endpoint. The feature I'm proposing to add is a button that once clicked would background load the missing repositories containing subscribed issues by using some form of this API query:
```graphql
query { 
  viewer { 
    issues(filterBy: {viewerSubscribed: true}, first: 100) {
      nodes {
        repository {
          id
          nameWithOwner
          owner {
            avatarUrl(size: 30)
          }
        }
      }
    }
  }
}
```
Any repositories missing from the filter list would be merged into the SSRed DOM fragment so they would be present and searchable in the dropdown.

### Screenshot

![image](https://user-images.githubusercontent.com/12993584/139701624-e7f9b54a-92ab-4dcd-ae2f-c1f18f0887a8.png)

An example of a repository that's completely missing from the list.

![image](https://user-images.githubusercontent.com/12993584/139789539-b385473b-577c-4b35-a237-6a1c38c0b2f9.png)

The location where the `"Load All"`/`"Load Missing"` button should be added

### Example URL

https://github.com/notifications/subscriptions

**Comment by kidonng** [comment]
You should also send this report to GitHub, that looks like their bug.

**Comment by fregante** [comment]
My assumption is that they did this to avoid excessive load since there could be hundreds of repos there. I don’t think we'll add this as it would involve managing API pagination and lazy-loading in an already-interactive widget.

Asking GitHub would be best as it would be easier to add it natively.

**Comment by h1nk** [comment]
I've created a GitHub Issues Feedback discussion for this problem. Feel free to close this one out in favor of https://github.com/github/feedback/discussions/7144.

**Comment by h1nk** [comment]
FYI for anyone trying to work around this, the GraphQL query I mentioned is completely useless for solving this problem and doesn't even do what I originally thought it did. The `viewerSubscribed` filter in the GraphQL API is a complete lie, it doesn't `List issues subscribed to by viewer.` as it says it does. It only includes issues which you have created and subscribed to (which is the default after creation) and does not include additional issues not created by you that you subscribe to.
