### ISSUE TITLE
Some features are running on unrelated pages

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5040]
1. Clear the cache
2. Reload this issue
3. Run this in the extension’s console: `chrome.storage.local.get(console.log)`
4. Notice the `workflows`, `list-prs-for-file`, and `tag-ahead-by` cache items, neither of which appears on an issue

<img width="598" alt="Screen Shot 13" src="https://user-images.githubusercontent.com/1402241/140050175-99ad6b29-5c10-427b-a403-eb3ad62653cd.png">

### Example URL

This issue

### Browser(s) used

Safari

**Comment by cheap-glitch** [comment]
I do see `workflows` in Firefox, but not the others.

**Comment by fregante** [comment]
I think the others don't appear on the issue page, but on the PR page. Closing for now. If you see unusual entries on other pages feel free to reopen
