### ISSUE TITLE
Restore `infinite-scroll` on user profiles

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5046]
### Description

Details on the drop of `infinite-scroll` on user profiles is in #1627.

While I acknowledge [the technical issues](https://github.com/refined-github/refined-github/issues/1627#issuecomment-439459434) with user profile page, I don't think there is a need to disable it on all profile pages. Instead, we can check the contribution graphs and see if it is useful to enable the feature on that page, thus no more "useless autoloading".

In my opinion, `infinite-scroll` should only be enabled on user profiles with:

- More than 10 contributions in the last year: `Number(document.querySelector('.js-yearly-contributions .f4').textContent.match(/\d+/)[0]) > 10`
- Alternatively, more than 10 days with contributions in the last year: `[...document.querySelectorAll('.ContributionCalendar [data-count]')].filter(i => i.dataset.count !== '0').length > 10`

### Example URL

https://github.com/johannes-bucher

**Comment by fregante** [comment]
> While I acknowledge [the technical issues](https://github.com/refined-github/refined-github/issues/1627#issuecomment-439459434) with user profile page

If that issue still exists, then we can't enable it for the same reason why we disabled it: It's bad UX

**Comment by kidonng** [comment]
There's not a compelling way to _fix_ the issues, however we can _mitigate_ it.

The criteria listed are just examples. The whole idea is that, we just look at the contributions calendar (so there's no API calling cost) and if it's not worth loading more, then do nothing.

**Comment by kidonng** [comment]
Instead of trying to load more activities in vain, we can be smarter and load months with actual activities instead. It is also helpful aside from help extending `infinite-scroll`, so I submitted a separate feature request.

**Comment by fregante** [comment]
The thing is, if scrolling adds history events, then it doesn't matter whether we do it all the time or just sometimes; It's broken every time we do it. Can't do
