### ISSUE TITLE
Enable `infinite-scroll` on compare pages

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5047]
### Description

Glad to see GitHub implemented a "Load more commits" button on compare pages, it used to show all the commits between the two compared refs. However as with all "load more" buttons, it may require repetitive clicks in order to find the desired info.

Enabling `infinite-scroll` on compare pages would be trivial but I'd like to open an issue first since it may not be welcoming to click all "load more" buttons automatically.

EDIT: it seems [Projects pages](https://github.com/kidonng/refined-github/projects) can also have a load more button, though Projects is less used.

### Example URL

https://github.com/NixOS/nixpkgs/compare/nixpkgs-unstable...master

**Comment by FloEdelmann** [comment]
It could also be enabled on release list pages. Searching (with <kbd>ctrl</kbd>+<kbd>f</kbd> in the browser) e.g. for breaking changes in packages with many releases is much easier if everything relevant is on one page.

Test URL: https://github.com/refined-github/refined-github/releases

**Comment by fregante** [comment]
Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it.
