### ISSUE TITLE
Auto-complete for github advanced search

### ISSUE THREAD

**Issue by Milo123459** [refined-github/refined-github#5051]
### Description

Github advanced search is something that takes a while to master, and for people like me who only use it for very certain things and often forget *how they search for it, auto-complete with a nice UI would be amazing. 

I think it should probably effect the search in the top left and searching for issues / PRs, and any other places that advanced search can be used.

* = what commands

### Screenshot

N/A

### Example URL

https://github.com/rust-lang/rust/issues

**Comment by cheap-glitch** [comment]
Seems like way too complicated a feature, especially when you can just bookmark [the relevant manual page](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests) and refer to it as needed.

**Comment by Milo123459** [comment]
I literally mean a faint text element that pops up in the box, it's not that complicated (I think?)

**Comment by fregante** [comment]
I've always wanted this and I've been always hopeful that they did it first. They do have a UI component they've been using in the notifications page for years, but no luck yet. 

Either way this a large feature that would be great as its own extension.
