### ISSUE TITLE
Download Directory feature isn't working for a directory

### ISSUE THREAD

**Issue by mattalexx** [refined-github/refined-github#5053]
When I try to download any directories at https://github.com/JetBrains/intellij-community, I am unable to.

### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

## Repro steps

1. Create a fresh profile (Ungoogled Chromium).
2. Install [Chromium Webstore](https://github.com/NeverDecaf/chromium-web-store), then Refined GitHub.
3. Generate a GitHub token using the link in the Refined GitHub options and install it.
4. Log into GitHub.
1. Go to https://github.com/JetBrains/intellij-community/tree/master/platform/platform-resources/src/keymaps. 
1. Click "Download directory"

https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2FJetBrains%2Fintellij-community%2Ftree%2Fmaster%2Fplatform%2Fplatform-resources%2Fsrc%2Fkeymaps

## Expected

I'm redirected to a page at https://download-directory.github.io/ where I'm passed a zip or something of the directory.

## What happened

I'm redirected to a page at https://download-directory.github.io/ where I get "No files to download". No error.

## Screencast

[Screencast](https://user-images.githubusercontent.com/250466/140621405-03ad431f-7364-4243-ae30-352c2c902141.mp4)

## Related notes

- It seems like it might be related to the https://github.com/JetBrains/intellij-community repo. I run into the same problem downloading the parent to that directory as well. But I do not have a problem downloading, say, [/build](https://github.com/refined-github/refined-github/tree/main/build) from https://github.com/refined-github/refined-github.
- The screencast doesn't use a fresh profile with only Refined Github installed, but it doesn't seem to make a difference anyway. Let me know if you need to see me recreate in a fresh profile and I'll send a new screencast.

## Dev tools log

```log
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
index.js:105 Source: {user: 'JetBrains', repository: 'intellij-community', ref: 'master', dir: 'platform/platform-resources/src/keymaps'}
index.js:15 Retrieving directory info…
/favicon.ico:1 GET https://download-directory.github.io/favicon.ico 404
index.js:15 No files to download
```

### Example URL

https://github.com/JetBrains/intellij-community/tree/master/platform/platform-resources/src/keymaps

### Browser(s) used

Chromium Version 95.0.4638.69 (Official Build, ungoogled-chromium) Arch Linux (64-bit)

**Comment by mattalexx** [comment]
As I write up this bug report, I'm realizing that the download-directory.io URL looks pretty good to me, and that the problem may be with that project and not this one.

If you look over this and agree with me, I'll go report it at https://github.com/download-directory/download-directory.github.io/ and reference this issue.

**Comment by fregante** [comment]
Thank you for the detailed report. I think it's https://github.com/download-directory/download-directory.github.io/issues/41

**Comment by mattalexx** [comment]
Alright, I'll copy it over.
