### ISSUE TITLE
Add filter successful actions

### ISSUE THREAD

**Issue by eranelbaz** [refined-github/refined-github#5062]
### Description

Add button to filter out successful gh actions 
currently i'm using this script to do that

```
$$('.merge-status-item').forEach(item => {
    let icon = item.querySelector('.color-text-success'); // remove success
    if(icon) item.remove();
});

$$('.merge-status-item').forEach(item => {
    let icon = item.querySelector('.neutral-check'); // remove skipped
    if(icon) item.remove();
});
```

hope you can add this as a button in the github actions as you have the pull request events filter

### Screenshot

![image](https://user-images.githubusercontent.com/29000470/140900556-519d00c6-c968-472a-a33a-d8feef4f9881.png)

![image](https://user-images.githubusercontent.com/29000470/140900597-9cef0f95-2875-4c76-8b85-1a5d2bd2c56e.png)

### Example URL

https://github.com/refined-github/refined-github/pull/5036

**Comment by kidonng** [comment]
Does #4958 cover your needs?

**Comment by eranelbaz** [comment]
> Does #4958 cover your needs?

It can defiantly help for that
