### ISSUE TITLE
Seperate issue / pr links (#id) from `linkify-code`

### ISSUE THREAD

**Issue by amithm7** [refined-github/refined-github#5063]
### Description

Linking issue or PR id in comments is much more useful than making a hyperlink of a URL which already exists in the code.

For example, this feature could be called `linkify-hash-id` maybe ?

And would linkify `#5063` in code comments but not `example.com`

### Example URL

https://cloud.githubusercontent.com/assets/170270/25370217/61718820-29b3-11e7-89c5-2959eaf8cac8.png

**Comment by kidonng** [comment]
> than making a hyperlink of a URL which already exists in the code.

To me it is the other way around, links in code comments are _enormous_ and nobody wants to manually select and open via context menu/drag and drop. 
 
> For example, this feature could be called `linkify-hash-id` maybe ?

> And would linkify `#5063` in code comments but not `example.com`

First, it's not "hash id" but "number sign and number".
Second, we are unlikely to split it into two  features that are pretty much the same Implementation.

**Comment by amithm7** [comment]
> code comments are enormous

Some maybe, but you can't select and right-click `#5063` to open it.

> it's not "hash id" but "number sign and number".

Never heard of "number sign", I see that it's what used in USA maybe? Never been there.
`id` because because it identifies a PR / Issue.

> we are unlikely to split it into two features that are pretty much the same Implementation.

Implementation maybe but I am asking for a different option for each.

**Comment by fregante** [comment]
As far as Refined GitHub is concerned, we want to linkify both, so we don't split features just to increase granularity. Splitting the feature would duplicate a lot of code and lower performance. For example there's a simple watcher/loop that calls those 2 functions; If we split the feature, we'd need 2 watchers… and then both of them will be enabled by default.

Also I don't see the need to split this specific feature; If you don't want to click full links, don't click them.

**Comment by amithm7** [comment]
@fregante , `linkify-code` can remain, but it can have sub-features, right?

```
linkify-code
  |_ urls
  |_ issues
```

Also, the preferences / options page needs some organization.

**Comment by kidonng** [comment]
> @fregante , `linkify-code` can remain, but it can have sub-features, right?
> 
> ```
> linkify-code
>   |_ urls
>   |_ issues
> ```

Please keep the conversation constructive. As mentioned above this is a _very_ niche request and we are not going to support it.

If you really want it, please consider maintaing a fork yourself (it's not difficult and can be automated).

> Also, the preferences / options page needs some organization.

Organized feature descriptions with categories are present in the README.
