### ISSUE TITLE
`bugs-tab` does not appear if the bug label emoji has a `-` in it

### ISSUE THREAD

**Issue by pschmitt** [refined-github/refined-github#5068]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

Hi and thanks a ton for making this addon!

I manage a few repositories where I renamed the default bug label and can't find a way to make the "Bugs" tab appear in this circumstance.

Here's the thing: I like emojis and therefore like to name this category `🐞 bug`
This may be easily addressable by extending the `supportedLabels` in `source/features/bugs-tab.tsx`

Hope you guys consider this type of request a bug and not a feature request, I wasn't too sure about the issue category for this one.

### Example URL

https://github.com/zdharma-continuum/zinit

### Browser(s) used

Firefox

**Comment by yakov116** [comment]
What emoji is that?

**Comment by pschmitt** [comment]
> What emoji is that?

🐞 https://emojipedia.org/lady-beetle/

**Comment by pschmitt** [comment]
🐛,  🦗, 🦟 etc. might be quite popular too for this.

**Comment by yakov116** [comment]
@refined-github/maintainers where do we put the line? We don't want every day a new emoji being added.
I have seen `lady-beetle` in the wild.

**Comment by yakov116** [comment]
NVM I see the issue.

[/^(bug|confirmed-bug|type:bug|kind:bug|:\w+:bug)$/i](https://github.com/refined-github/refined-github/blob/4f270c4f50e0a2a20085a6e92095117f10340322/source/features/bugs-tab.tsx#L15)

Since `lady-beetle` has `-` in the regex does not match

**Comment by kidonng** [comment]
> 🐛, 🦗, 🦟 etc. might be quite popular too for this.

We already have `:bug:`, add `:lady_beetle:` is fine, I've seen it in the wild too. Iskepticalcal about `:beetle:`; `:cricket:` and `:mosquito:` definitely not make sense.

**Comment by fregante** [comment]
This is a 4-character fix. The regex should use `[\w_-]` instead of `\w` I thin
