### ISSUE TITLE
Hide the username/organization from the dashboard quick links

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5069]
### Description

I always found this widget noisy since long `usernames/repos` wrap. Now they added icons so I think they're distinguishable enough without the username. These are also the repos you interact with the most, so I suppose you don't need the full repo.

## Before

<img width="282" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/141468989-011a1edd-1c2a-47ba-a44b-546c41464176.png">

## After

<img width="248" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/141468974-23fe0543-7d66-4a10-9afb-84dae34dc254.png">

The change can apply to the visible items, the rest of the list can stay unchanged.

<img width="266" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/1402241/141478781-0ddf5595-e52c-413f-9237-065a51a43d20.png">

Screenshot done with:

```hs
$$('.color-text-primary.lh-0.mb-2.markdown-title').forEach(x => x.firstChild.remove())
$$('.color-text-primary.lh-0.mb-2.markdown-title').forEach(x => x.firstChild.remove())
```
### Example URL

https://github.com

**Comment by kidonng** [comment]
I'm also confused like @yakov116, and suppose the best we can do is to do this only for your own repos.

> I always found this widget noisy since long `usernames/repos` wrap.

I don't have many repos whose name is long enough to wrap, but in my opinion two lines are fine and three lines are rare.

> Now they added icons so I think they're distinguishable enough without the username.

I would say they added it simply to be consistent with issue/pr icons below. 16px avatars are not distinguishable enough on its own, not to say many avatars just don't click.

> These are also the repos you interact with the most

Not entirely correct, it is also somehow based on "frecency" i.e. how frequent *and* when you interact with a repo.

> so I suppose you don't need the full repo.

The question is that repo names are almost always shown with `<username>/<repo>` etiquette, except e.g. on user/repository profile pages. I don't think the potential confusion is worth cleaning up the interface a tiny bit.

**Comment by fregante** [comment]
> Not entirely correct, it is also somehow based on "frecency" i.e. how frequent _and_ when you interact with a repo.

Whatever the exact metric, if they're up there you likely know all of them by name, right? That's why IMHO they should be hidden.

**Comment by kidonng** [comment]
Then let's try, if people don't like it we can just disable it.

**Comment by fregante** [comment]
Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it. If it was accepted before, I may still accept a PR in the next 6 months.
