### ISSUE TITLE
Add new notification indicator to Favicon

### ISSUE THREAD

**Issue by hjylewis** [refined-github/refined-github#5070]
### Description

It would be helpful to have a visual queue that tells me when there's a new notification.

Gmail does this (see screenshot) and reminds me to check my email.

### Screenshot

<img width="56" alt="Screen Shot 2021-11-12 at 1 25 22 PM" src="https://user-images.githubusercontent.com/6494737/141523549-e959be8f-21bb-4fa2-9ee1-3e5a84ac8622.png">

### Example URL

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
This requires constant fetching of the notifications (every few seconds), which Refined GitHub can't do. 

There's an extension that does this (when a tab is active) so you can add the request there. 

https://github.com/tanmayrajani/notifications-preview-github

**Comment by fregante** [comment]
Actually I think it's best to just use https://chrome.google.com/webstore/detail/notifier-for-github/lmjdlojahmbbcodnpecnjnmlddbkjhnn
