### ISSUE TITLE
`reactions-avatars` doesn't work on URLs with extra slashes

### ISSUE THREAD

**Issue by ShadowJonathan** [refined-github/refined-github#5076]
### Please ensure:

- [X] ~~The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.~~ (Well technically nothing happens anyways if i disable the extension, but this is true)

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

![image](https://user-images.githubusercontent.com/22740616/141844573-46d717df-5fbd-4f73-9b37-680de81fe1f7.png)

This issue doesn't seem to display reaction avatars.

I tested some other issue, it still works, just not on this one.

I also tested other issues in the repo, it still works then and there.

### Example URL

https://github.com//vector-im/element-meta/issues/56

### Browser(s) used

Brave, Linux

**Comment by ShadowJonathan** [comment]
I just figured it out, this happens when adding extra slashes in github URLs, github still sends the "right" page contents, but refined github doesn't pick up on it.

Link that works: https://github.com//vector-im/element-meta/issues/56

Link that doesn't: https://github.com/vector-im/element-meta/issues/56

**Comment by cheap-glitch** [comment]
_If_ we want to support this, it should probably be implemented in `github-url-detection`.

**Comment by kidonng** [comment]
I briefly checked some different types of pages and it seems whether a trailing slash is present or not does not make a difference. Perhaps we can just ignore it all the time and add exceptions (if any) later.

**Comment by kidonng** [comment]
Pardon for my ignorance, I just realized it's not about trailing slashes, but rather slashes in between. I corrected my previous title renaming.
