### ISSUE TITLE
Color gradient for files age

### ISSUE THREAD

**Issue by slavaGanzin** [refined-github/refined-github#5081]
### Description

Hi

I'm constantly looking for new GitHub projects and one thing that I care the most is maintenance activity (e.g. date of last commit).
So, I created a little extension, which runs only on GitHub pages. So fresh commits would become green and old — red. 
```javascript
Array.from(document.querySelectorAll('[datetime]')).map(x => 
  x.innerHTML = `<span style='filter: sepia(1) saturate(80) hue-rotate(${100 - 25 * (new Date() - new Date(x.getAttribute('datetime')))/(365 * 24 * 60 * 60 * 1000)}deg);'>${x.innerText}</span>`
) 
```
You can paste this in console on any [repository page](https://github.com/refined-github/refined-github)

Maybe it would be interesting for you to merge if I would create a PR?

### Screenshot

![2021-11-17_15-49](https://user-images.githubusercontent.com/1011721/142213102-99265c18-cc33-485f-a806-10697074eb0c.png)

### Example URL

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
The feature is reasonable and it would match the blame page. The only issue I see is ensuring the colors are accessible and native-looking. We can try using the colors from the blame page itself. Mockup welcome.

**Comment by slavaGanzin** [comment]
@fregante I was misguided by blame colors: red is a color of problem, while green is a color of change. It's natural: like fresh crops, and autumn leaves. Maybe, it would be better to make fresh changes green, and old - pale yellow/red? I think it's not a problem that `.editorconfig` is old, so it shouldn't be red. 
![2021-11-18_11-38](https://user-images.githubusercontent.com/1011721/142390025-b330f7cd-66af-4aa0-89c4-7e1103bfd7d0.png)

**Comment by fregante** [comment]
Red and green are not good for this purpose. Try blame colors as suggested https://github.com/refined-github/refined-github/blame/main/contributing.md

**Comment by slavaGanzin** [comment]
I dont think this way

**Comment by kidonng** [comment]
> The feature is reasonable and it would match the blame page.

Thanks for the reminder, I remember there is something similar on GitHub already but cannot find it.

**Comment by kidonng** [comment]
Reopening since the feature request itself is valid. We can go through implementation details later in the PR, not to mention colors can be easily overridden with custom CSS.

**Comment by yakov116** [comment]
@fregante I tried this out I am not sure I like it.

Please let me know if I should continue.

![image](https://user-images.githubusercontent.com/16872793/178278788-277724fd-530b-420f-a3d0-d3597d7acfe8.png)

To try this out
```js
dd = (d1) => {
const date1 = new Date(d1);
const date2 = new Date();
const diffTime = Math.abs(date2 - date1);
const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
return diffDays    
}

timeAgo = $$('.js-navigation-item time-ago')

for (const t of timeAgo) {
    t.classList.add('blame-commit-date');
    t.style.fontSize = '14px'
    t.style.lineHeight = '18px'
    const dateDiff = dd(t.attributes['datetime'].value)
    if  (dateDiff <= 3) {
        t.dataset.heat = 1
        continue;
    }
    if  (dateDiff <= 6) {
        t.dataset.heat = 2
        continue;
    }
    if  (dateDiff <= 15) {
        t.dataset.heat = 3
        continue;
    }    
    if  (dateDiff <= 24) {
        t.dataset.heat = 4
        continue;
    }
    if  (dateDiff <= 40) {
        t.dataset.heat = 5
        continue;
    }    
    if  (dateDiff <= 70) {
        t.dataset.heat = 6
        continue;
    }
    if  (dateDiff <= 100) {
        t.dataset.heat = 7
        continue;
    }    
    if  (dateDiff <= 160) {
        t.dataset.heat = 8
        continue;
    } 
    if  (dateDiff <= 275) {
        t.dataset.heat = 9
        continue;
    }    
    if  (dateDiff > 275) {
        t.dataset.heat = 10
        continue;
    } 
}
```

How I found out when GitHub changes the heat value (its not perfect but you get an idea). Run this on any blame page.

```
b = []
dd = (d1) => {
const date1 = new Date(d1);
const date2 = new Date();
const diffTime = Math.abs(date2 - date1);
const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
return diffDays    
}
$$('.blame-commit-date').forEach(a =>{
    const r = [dd(new Date(a.children[0].attributes['datetime'].value)), a.dataset.heat]
    b.push(r)
})
p= b.reduce((accumulator, value) => {
  return {...accumulator, [value]: (accumulator[value] || 0) + 1};
}, {});
```

**Comment by kidonng** [comment]
@yakov116 Awesome! I think the colors actually look nicer in dark mode (they don't change in different modes though):

<img width="886" alt="image" src="https://user-images.githubusercontent.com/44045911/178301951-9cd720bd-3439-4921-9749-14057fbe28c7.png">

However I'm not sure we want this feature to be default on. It makes sense on blame page because you are explicitly looking for changes there, but in the file tree timestamps are less significant.

**Comment by yakov116** [comment]
> However I'm not sure we want this feature to be default on.

⬆️ This ⬆️

**Comment by yakov116** [comment]
@fregante were good?

**Comment by fregante** [comment]
Rather than freshness I think this natural leads our focus to important files and ignore the static configuration files, like a natural version of https://chrome.google.com/webstore/detail/hide-files-on-github/lpnakhpaodhdkleejaehlapdhbgjbddp

**Comment by fregante** [comment]
I just tried and indeed maybe it does attract more attention that it should. 

On older repos it does nothing, like the blame view, and that's probably also ok. Test URL: https://github.com/sindresorhus/mem

This means that this feature will attract attention to **files modified within the last 6 months**. We have to decide:

- Is it useful?
- Is it distracting?

I'm gonna load this as a userscript for a while to answer these questions. For now I'm +⅓

**Comment by fregante** [comment]
I like it. Let's go! 🛳

**Comment by yakov116** [comment]
Anyone can take this up as I am away for  the next week.

If not I will do it.

**Comment by yakov116** [comment]
@foolmoron want to take a stab at this?

**Comment by momin-tf** [comment]
Most likely can't sorry!
