### ISSUE TITLE
Refined Github get deleted commit when delete and recreate repo with same name.

### ISSUE THREAD

**Issue by MisileLab** [refined-github/refined-github#5082]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

When delete and recreate repository new one with same name in 1 minute, It detect deleted commit, not recreated one.

Example) https://github.com/MisileLab/PoggyChat

![스크린샷, 2021-11-18 05-30-52](https://user-images.githubusercontent.com/74066467/142277762-4883583b-28c3-4b4e-b309-5962c65a1532.png)
![스크린샷, 2021-11-18 05-31-18](https://user-images.githubusercontent.com/74066467/142277775-60a9438e-9d54-4568-ba0c-f976a1d349cd.png)

### Example URL

https://github.com/MisileLab/PoggyChat

### Browser(s) used

Brave Browser

**Comment by busches** [comment]
Are you referring to the repository age? That value is cached since it doesn't often change. Manually clearing the cache will resolve it.

**Comment by MisileLab** [comment]
> Are you referring to the repository age? That value is cached since it doesn't often change. Manually clearing the cache will resolve it.

How delete cache of Refined Github?

**Comment by cheap-glitch** [comment]
> How delete cache of Refined Github?

There's a "Clear cache" button at the bottom of the options page.

**Comment by MisileLab** [comment]
thank you
