### ISSUE TITLE
Better UI for required status checks (branch protection settings)

### ISSUE THREAD

**Issue by asmeurer** [refined-github/refined-github#5083]
### Description

GitHub has perhaps the worst UI I've ever seen in its setting page for adding required status checks for branch protection. 

Instead of just listing all the status checks that can be added, there is a search box that you have to type in to select the checks you want. The search box autofills, so you can theoretically find every status check by typing every letter and number into the box. But to make things even worse, the autolists checks that have already been added, so you can't even tell which ones are missing. Typically when I am on this page I want to make every or almost every status check required, and this UI makes it annoyingly difficult to do this. It's particularly obnoxious if you split your GitHub actions into several distinct jobs, which each get their own separate status.  

To see this, go to the settings page for a repo, click "Branches" on the left, click "edit" on one of the branches (or "add rule" if you've never enabled branch protection), then check "Require status checks to pass before merging".

Literally any other UI would be better here, but I would suggest just listing every status check that is available, with checkboxes for whether they are enabled or not. This could then perhaps be *filtered* with a search box for repos with an insane number of checks (presumably that happens or else GitHub would never have made the UI like this). I don't know if the "try searching for every letter number and symbol" trick will work to find every possible status check (it depends on whether the checks can contain arbitrary non-ASCII characters or not).

### Screenshot

This is what it looks like for the SymPy repo. <img width="765" alt="Screen Shot 2021-11-17 at 5 55 47 PM" src="https://user-images.githubusercontent.com/71486/142330992-35f2b0c1-ab9a-4e9f-80d6-aed15e8073f7.png">

### Example URL

(A repository's branch protection settings page, see above)

**Comment by fregante** [comment]
I _really_ don't see an issue with the existing solution. There's nothing more simple than a list of well-explained checkboxes that expand when enabled.

<img width="712" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/142412655-8dd0b835-b04d-4861-97e8-37b9106143dc.png">

Also what you're suggesting is a heavy rework of the interface, which is too much for Refined GitHub (we generally only remove small pieces or add very small widgets/buttons)

**Comment by asmeurer** [comment]
The example repo I showed has dozens of jobs. This interface is even less usable the more jobs there are.
