### ISSUE TITLE
Increase emoji size in the comment reaction selection box

### ISSUE THREAD

**Issue by IanButterworth** [refined-github/refined-github#5085]
### Description

It's pretty difficult to tell the difference between the two face emojis when selecting an emoji response because they're so small.

This changes the `g-emoji` class font-size from `1em` to `1.6em`. Perhaps the spacing could be increased too if click-ability was diminished. The whole popup could be a bit bigger

### Screenshot

<img width="163" alt="Screen Shot 2021-11-18 at 5 31 46 PM" src="https://user-images.githubusercontent.com/1694067/142507506-af0c1e18-907c-4e98-bc58-00f0e74bfec4.png">
<img width="171" alt="Screen Shot 2021-11-18 at 5 33 52 PM" src="https://user-images.githubusercontent.com/1694067/142507512-bd6aab2c-046a-413a-9458-ae2c02655a15.png">

### Example URL

https://github.com/refined-github/refined-github/issues/5085#issue-1057916229

**Comment by fregante** [comment]
Not a terrible idea honestly: they _are_ kinda small, the change is CSS only, the hit area is already that big, the container doesn't change.

```css
.js-pick-reaction .emoji {
	font-size: 1.6em;
}
```

![gif](https://user-images.githubusercontent.com/1402241/142640988-59efd252-892a-4b2a-9a32-fb0d8504e4ce.gif)

They do need to be better aligned vertically though.

**Comment by kidonng** [comment]
> It's pretty difficult to tell the difference between the two face emojis when selecting an emoji response because they're so small.

They are not close to each other, so it's easy to remember their location. Also the similarity between them depends on your emoji font.

> This changes the `g-emoji` class font-size from `1em` to `1.6em`. Perhaps the spacing could be increased too if click-ability was diminished. The whole popup could be a bit bigger

Isn't GitHub already enlarging the emoji when hovering?

**Comment by kidonng** [comment]
Also the emoji size in your screenshot is smaller than it should be, see @fregante's screenshot for reference.

**Comment by IanButterworth** [comment]
I'm on MacOS, maybe @fegante isn't and the macos emoji font is smaller? I could file that as a github UI bug if so

**Comment by kidonng** [comment]
No, me and @fregante are both on macOS and have normal emoji size. You can try clearing the browser cache and see if it is fixed.

**Comment by IanButterworth** [comment]
Yeah, ok that solved it. It appears I had github zoomed out without noticing. Apologies for the noise
