### ISSUE TITLE
Show API quota status on extension options page

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5089]
### Description

We already query the API to check the token scope, it would be better to make more use of the response.

The following headers are available in the response:

- `x-ratelimit-limit`: total quota
- `x-ratelimit-remaining` / `x-ratelimit-used:`: remaining/used quota
- `x-ratelimit-reset`: time at which the quota will reset

We can show these info on the extension options page as an additional "feature", which can also help debugging potential issues with rate limit. 

### Example URL

chrome://extensions/?options=balgliakcbamepammkbcjdepogihccmj

**Comment by fregante** [comment]
Quota varies by the minute, right? Also I'm guessing RGH does not get anywhere near the limit. Have you had issues with it?

**Comment by kidonng** [comment]
> Quota varies by the minute, right?

No, they reset an hour after your first API request.

("First" in the sense that since your last quota reset)

> Also I'm guessing RGH does not get anywhere near the limit. Have you had issues with it?

I myself haven't had any issue with it, I just had this idea lately. RGH is probably making API requests more than most GitHub extensions out there, but unless one use it _very extensively_ it will still be difficult to hit the limit.

The most common scenario I can think of is:
- You request large batch of data via GraphQL, which can consume your quota quickly
- You have many automations using your account's token to interact with GitHub
- You are experimenting/developing things with GitHub API, so you are making requests frequently

I just think it's an feature we can have that will come handy without extra cost.

**Comment by fregante** [comment]
> without extra cost.

Except UI and bikeshedding 😃 

What does the information look like? Can it be represented as one line of text?

```
Token quota: 34% left this hour
```

**Comment by kidonng** [comment]
> What does the information look like? Can it be represented as one line of text?
> 
> ```
> Token quota: 34% left this hour
> ``` 

Yeah, one line would do it.

**Comment by fregante** [comment]
Rather than seconds I'd use a fixed time. We can also add a "check/refresh" button anywhere near the field. For example

```
API quota: 34% left until 14:50. _Refresh_
```

The button would just need to dispatch an input event in the token field to refresh, probably.

**Comment by fregante** [comment]
The quota is so high, it's not worth it. Use a token only for Refined GitHub and it's unlikely you'll ever run out.
