### ISSUE TITLE
`show-whitespace` stucks with huge (but visible) file

### ISSUE THREAD

**Issue by xnuk** [refined-github/refined-github#5092]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description
![A huge json, with browser showing "Refined Github is slowing down".](https://user-images.githubusercontent.com/3071003/142735440-662a7fd4-a7a4-4a02-b2e8-5aa58c54dd15.png)

In this case, `element.textContent.length === 478130 && element.textContent.split(' ').length === 47609`.  That means `show-whitespace` will make (at least) 47609 * 2 = 95218 `<span>` and text nodes.

### Example URL
https://github.com/github/copilot.vim/blob/03a11aded57a78975effc87770ade4059c058dc7/copilot/dist/tokenizer.json

Note: Example URL can make your browser tab stuck, so you might want to double-check `show-whitespace` is disabled or not.

### Browser(s) used
Firefox Developer Edition 95 on Arch Linux x64

**Comment by fregante** [comment]
I think we had a line length limit at some point
