### ISSUE TITLE
`new-repo-disable-projects-and-wiki` fails to remove the relevant tabs

### ISSUE THREAD

**Issue by cheap-glitch** [refined-github/refined-github#5107]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

### Description

Upon creating a new repo:

```
❌ new-repo-disable-projects-and-wikis 0.0.0 → TypeError: select_dom__WEBPACK_IMPORTED_MODULE_1__["default"](...).closest(...) is null
    disableWikiAndProjects moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:9528
    runFeature moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:8049
    setupPageLoad moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:8067
    add moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:8125
    tsx moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:9554
    __webpack_require__ moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:25647
    <anonymous> moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:25879
    <anonymous> moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:26119
    <anonymous> moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:26121
refined-github.js:7972:11
```

"Projects" and "Wiki" are actually disabled, it's just the tabs that are left in the header. They disappear upon refreshing the page.

### Example URL

https://github.com/new

### Browser(s) used

Firefxox 94

**Comment by yakov116** [comment]
I think we can just Exclude `isEmptyRepo`

**Comment by fregante** [comment]
> "Projects" and "Wiki" are actually disabled, it's just the tabs that are left in the header. They disappear upon refreshing the page.

So it's a GitHub bug.

Annoyingly I've been seeing something similar on all of my repos: Discussions are disabled, but GitHub will still show a Discussions tab until I enable and disable them again… 😠 

> They disappear upon refreshing the page.


Not a big deal either way then
