### ISSUE TITLE
Tree view sidebar for quicker navigation of the code

### ISSUE THREAD

**Issue by mattalexx** [refined-github/refined-github#5110]
### Description

It would be a nice time saver to be able to hop around on the tree quicker. I was hoping to hear your thoughts.

I'm worried that this falls under [Rule #4](https://github.com/refined-github/refined-github/issues/2960#issuecomment-606767200):

> 4. It doesn't require a lot of view/UI, code and effort to maintain.

But it's a cool idea, and I figured it was worth a post, even if it's shot down.

### Screenshot

https://user-images.githubusercontent.com/250466/143183769-1ba92afa-cfa6-43cf-9187-73d50d85b7d8.mp4

### Example URL

https://github.com/ansible/ansible-examples/tree/master/lamp_haproxy/roles

**Comment by fregante** [comment]
Oh yeah that's a gigantic feature _and_ it already exists, so [rule 1](https://github.com/refined-github/refined-github/issues/2960#issuecomment-606764895) and 4 😃

**Comment by fregante** [comment]
https://chrome.google.com/webstore/detail/gitako-github-file-tree/giljefjcheohhamkjphiebfjnlphnokk

**Comment by mattalexx** [comment]
Thanks for digging up that link for me. :-)
