### ISSUE TITLE
Hide reviews by non-reviewers

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5118]
...namely the gray review icon you see [on](https://togithub.com/refined-github/refined-github/pull/5033#pullrequestreview-812368721) [random](https://togithub.com/dotnet/sdk/pull/22262#pullrequestreview-786624962) [places](https://togithub.com/ytdl-org/youtube-dl/pull/25717#pullrequestreview-435313299):

![image](https://user-images.githubusercontent.com/44045911/143877628-6e77a105-91e2-4fc6-b6f5-5d3eee35665e.png)

Actually, this sort of stuff is common on any popular repository.

What is a "review by non-reviewer": if the `aria-label` of the review icon reads "Only reviews by reviewers with write access count toward mergeability".

In general, these reviews are not useful, however there are exceptions:

- Reviews by contributors or organization members ([example](https://togithub.com/NixOS/nixpkgs/pull/147010#pullrequestreview-817111882)). However I don't find a way to tell if a user falls into this category (and if someone do, please leave a comment as it may also benefit other features of RGH).
- Reviews by yourself. This is in the same spirit as the rule above, except that we can reliably tell if a review is left by you or not.
- Reviews with a comment. They may still be of little value but the risk of filtering them out is not worth it.

---

Implementation-wise, there are two places to look out:

- The timeline. This is where the feature would be most useful, probably in the same fashion as `hide-low-quality-comments`.
- The sidebar. I'm not sure about this, as it is less annoying and serves as a neat indicator that _someone_ did review.

---

Worth mentioning that **GitHub _sort of_ implemented this feature**, in the sense of [Preventing drive-by pull request approvals and requested changes](https://github.blog/2021-11-01-github-keeps-getting-better-for-open-source-maintainers/#preventing-drive-by-pull-request-approvals-and-requested-changes). So maybe we should not implement it at all.

However, there are some caveats of GitHub's solution:

- Too radical. To allow or not to allow, that's a serious question. In particular, approvals from outside contributors are almost always useful.
- Some projects can't employ it. Take the [nixpkgs](https://github.com/NixOS/nixpkgs) example above, this is a project consisting of _thousands_ of maintainers, however only a handful of them are "committers" with write access, or "reviewers" regarding this issue. Maintainers review PRs in a regular manner, but those reviews will never be considered "valid" by GitHub.

###### Also, this is my 100th issue opened in RGH 🤯

**Comment by fregante** [comment]
> * However I don't find a way to tell if a user falls into this category

Won't GH color them green?

> * probably in the same fashion as [`hide-low-quality-comments`](/refined-github/refined-github/blob/main/source/features/hide-low-quality-comments.tsx).

Yeah that sounds like the perfect place. It's basically a +1 comment, without text at all.

Seen under that light, I'm +1 on this

> GitHub _sort of_ implemented this feature

It's a per-repo feature, to which collaborators don't have access to. I'd still consider it.

> * those reviews will never be considered "valid" by GitHub.

This might bring it back to a -1. If we can't reliably consider this "noise" without an API call, then we can't risk hiding potentially good content.

In `hide-low-quality-comments` we consider the labels GH adds to each comment, but those don't exist on empty reviews.




> ###### Also, this is my 100th issue opened in RGH 🤯

Time to take a vacation!! 😜

**Comment by kidonng** [comment]
> Won't GH color them green?

Only "reviewers with **write access**" counts, even if you have some sort of relation with the repository.

**Comment by kidonng** [comment]
@busches Could you please share why you don't like this? If this is ever going to be implemented， it will definitely exclude GHE.

**Comment by fregante** [comment]
Unfortunately it's not easy to determine whether a review is spam or not. A comment-less review by a third party could be even left by the author of the request issue. While it's not great that they left an empty review, it's still a positive signal that we can't hide.

I'd probably ask GH to allow reporting reviews as spam and deleting them instead

**Comment by yakov116** [comment]
Github has on their roadmap an option to ignore them
