### ISSUE TITLE
Hide Milestones link

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5120]
- Hide "Assignee": if no assignee can be seen on the whole page, the repository probably doesn't use Assignee anyway. It's better to just hide the filter.
- Hide "Milestones" link:

  <img width="384" alt="截屏2021-11-29 22 34 44" src="https://user-images.githubusercontent.com/44045911/143886821-09ce32a9-6729-49ca-bcbc-de6eee9878be.png">

  It is probably out of the scope of this feature but worth mentioning anyway.

**Comment by fregante** [comment]
> * Hide "Assignee": if no assignee can be seen on the whole page, the repository probably doesn't use Assignee anyway. It's better to just hide the filter.

Just because there are no assignees on the current page, it doesn't necessarily mean there are no assignees anywhere, even though what you're saying is likely. It's not a safe change.



> * Hide "Milestones" link:

I thought we did at some point

**Comment by kidonng** [comment]
> Just because there are no assignees on the current page, it doesn't necessarily mean there are no assignees anywhere

The same can be said to Milestones, though that's less popular than Assignees.

How about we dim a little bit the label instead?

**Comment by fregante** [comment]
> The same can be said to Milestones, though that's less popular than Assignees.

No. Milestones show the total number of active milestones; We do not have a total number of assigned issues.

What can be said is that we hide milestones and projects _even if they exist,_ although only when they're completed.



> How about we dim the label a little bit instead?

The milestones label? Wouldn't that look weird since it's part of the same "btn-group"?

**Comment by fregante** [comment]
Ok maybe this:

<img width="334" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/144181073-241cf535-25ed-425d-a9dd-3399a0eef173.png">


I think we can't hide it altogether because there are no other links to the page. Maybe it's not worth to _move_ it elsewhere.
