### ISSUE TITLE
Remove/Reset addon settings

### ISSUE THREAD

**Issue by haoadoresorange** [refined-github/refined-github#5130]
Hi,

Where do I remove the addon settings ? Wanted to reset to default but the settings persist across reinstallation.

**Comment by fregante** [comment]
> the settings persist across reinstallation.

I suppose you're using Firefox?

We don't have a way to clear the settings, but unless you disabled a lot of features there are only 2 fields to reset.

**Comment by fregante** [comment]
> disabling a lot of it to know what was causing a problem

We have a "Find feature" at the bottom to do that 😉 👍 



> So like no way at all ?

1. Open `about:debugging#/runtime/this-firefox`
2. Find Refined GitHub
3. Click "inspect"
4. Paste:
