### ISSUE TITLE
Make debugging more visible/findable

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5134]
<img width="549" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/144167318-b2839b8e-1093-4ee7-94b3-3fd9008ca087.png">

I suggest to:

- move the debugging section above the Features
- hide it
- add a "Show debugging" button that temporarily shows the section
	- the button exclusive adjusts the DOM until the tab is closed, nothing is stored

# Default

> #### Custom CSS
> 
> ```
> 
> ```
> 
> #### Debugging
> 
> <kbd>Show debugging</kbd>
> 
> #### Features
> 
> ```
> ```
> 
> - [ ] action-used-by-link
> - [ ] etc

# After clicking the button

> #### Custom CSS
> 
> ```
> 
> ```
> 
> #### Debugging
> 
> - [ ] Show the features enabled on each page
> - [ ] etc
> 
> #### Identify feature
>
> This process will help you identify what Refined GitHub feature is making changes or causing issues on GitHub.
> 
> <kbd>Start process to identify feature</kbd>
> 
> #### Features
> 
> ```
> ```
> 
> - [ ] action-used-by-link
> - [ ] etc

**Comment by kidonng** [comment]
That mockup is brilliant 👍
