### ISSUE TITLE
Quick move from pr files tab to file history

### ISSUE THREAD

**Issue by KSH-code** [refined-github/refined-github#5138]
### Description

When I review PRs, check file history and also blame.
the steps
1. click `view files` option
2. click history or blame 

### Screenshot

![스크린샷 2021-12-02 오후 5 13 38](https://user-images.githubusercontent.com/29705162/144383450-f378e4cb-db9e-44a9-b9ad-d0caaf955f65.png)

![스크린샷 2021-12-02 오후 5 17 15](https://user-images.githubusercontent.com/29705162/144383749-fb9b42e9-f7b6-40be-b96d-f5f475860784.png)

### Example URL

https://github.com/refined-github/refined-github/pull/5124/files

**Comment by kidonng** [comment]
I was going to say you just to click _once_ more, then I realized I do this on a daily basis.

**Comment by yakov116** [comment]
Should be an easy thing to add. The logic exists in another feature (can't remember the name off hand)
