### ISSUE TITLE
GitHub bug: GitHub Actions logs add scrolling bar to each line separately

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5152]
### Description

This is only visible if your OS does not hide the scrollbars

### Screenshot

<img width="1175" alt="Screen Shot 10" src="https://user-images.githubusercontent.com/1402241/144740625-912046e3-a72a-4360-963e-65f5ec867939.png">

### Example URL

https://github.com/pixiebrix/pixiebrix-extension/runs/4421465201?check_suite_focus=true

**Comment by fregante** [comment]
This could probably be fixed by dropping the fixed width that each line might have and then adding `overflow-x: scroll` to the whole log section (step)

**Comment by kidonng** [comment]
That's unfortunate, I thought GitHub would wrap in this case.

**Comment by fregante** [comment]
Reported to GitHub for now

**Comment by fregante** [comment]
Fixed via CSS hotfix just to try it, but it doesn't appear to be working https://github.com/refined-github/refined-github/issues/5165

**Comment by fregante** [comment]
Still no fix. I closed this issue on an _excess of confidence_ that they would have fixed it quickly. Nope.

**Comment by kidonng** [comment]
GitHub does wrap on that page. What's the difference?

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/44045911/154837125-fe1af47a-6061-48ed-8af3-ec8e5a394a47.png">

**Comment by fregante** [comment]
We have a hotfix, disable RG

**Comment by kidonng** [comment]
> We have a hotfix, disable RG and try safari

That's without RG, but indeed not Safari (it's Chrome).

On Safari with `overflow: visible` things do go back to normal, except the page itself now has a horizontal scrollbar.

> Still no fix. I closed this issue on an _excess of confidence_ that they would have fixed it quickly. Nope.

Maybe they are mostly using Chrome or have scrollbar hidden 🤷
