### ISSUE TITLE
Add buttons to `clear-pr-merge-commit-message` and related features

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5155]
### Description

Instead of automatically clearing the field, I wonder if we could add some buttons in the mergeability box to:

- `sync-pr-commit-title`
- `clear-pr-merge-commit-message`
- https://github.com/refined-github/refined-github/issues/2103
- https://github.com/refined-github/refined-github/issues/1264

This issue replaces:

- https://github.com/refined-github/refined-github/issues/4606

Avoiding automatic replacement would also avoid:

- https://github.com/refined-github/refined-github/issues/4101 (the issue would still exist since it's GitHub’s, probably, but since we won't automatically change the fields, it won't happen "because of RGH")

Related:

- https://github.com/refined-github/refined-github/issues/3964
- https://github.com/refined-github/refined-github/issues/4531

### Screenshot

<img width="631" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/144755763-6d9302ef-3110-47ea-bf18-96fe1b5e9473.png">

### Example URL

https://github.com/refined-github/refined-github/pull/3

**Comment by fregante** [comment]
This would probably merge the features into one, even just a little at a time. The UI needs to be thought out a bit, I'm thinking maybe a dropdown or radios. Maybe I'd even add those fields until the user clicks "customize"

Example: 
> **Title:** 🔵 PR title 🔘 "Merge X into B" <kbd>Customize</kbd>
> **Message:** 🔵 List of commits 🔘 Only collaborators <kbd>Customize</kbd>

**Comment by yakov116** [comment]
I like option 2.

Do you feel that we will run into https://github.com/refined-github/refined-github/issues/2960#issuecomment-606765658?

**Comment by fregante** [comment]
Those are not options, they're UI of the feature itself

**Comment by fregante** [comment]
GitHub added some controls over this, which are likely to stay "per-repo":

https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/

We need to decide what to do with our current features regarding PR titles, if we can detect a custom setting and avoid overriding it.

**Comment by JelteF** [comment]
> We need to decide what to do with our current features regarding PR titles, if we can detect a custom setting and avoid overriding it.

Since one of the settings that github provides is exactly what is being done by refined github now, I don't think there's a reason to keep these settings. In the current state it gives you less configurability than Github does.

**Comment by styfle** [comment]
I was wondering why the setting wasn't working until I saw the notice added in https://github.com/refined-github/refined-github/pull/6019

I agreed, I think `sync-pr-commit-title` and `clear-pr-merge-commit-message` should be disabled by default so the repo's settings can take precedence.

**Comment by fregante** [comment]
> should be disabled by default

Refer to:

- https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#2-it-makes-sense-as-a-default-for-everyone
- https://github.com/refined-github/refined-github/pull/5967

### New suggested solution

- [ ] Add "Undo" button to the [new notice](https://github.com/refined-github/refined-github/pull/6019)

<img width="567" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/205433405-f861ee0d-c7df-49d6-8ccf-5c1869c469c7.png">

**Comment by karfau** [comment]
The main problem I see with this destructive action being enabled is the conflict it causes for repos that use conventional commits, in which case it is important to add the `BREAKING CHANGE: ` to the commit, which most likely is already part if the PR description.

So to adhere to rules of "shoud a feature be added" which say that it needs to be enabled by default, either we need to find rules to male it more clever, in which cases clearing should be avoided (not sure this is possible without opening a huge options discussion/  maintainance burden), or if it should rather be dropped completely (is there a process for such cases?)

**Comment by fregante** [comment]
We think it's good default and those who disagree can already disable it *and* are alerted every time. This means:

- we won't drop the feature
- we won't make it "on demand" (PR already attempted this and was closed)

These two are not up for discussion because, again, those who don't like it can already disable it.

**Comment by JelteF** [comment]
Honestly I still feel like the default of this setting is wrong, for the reasons I described in my previous comment. But I didn't feel strong enough to continue complaining. However, I think it's quite weird that my original comment is now marked as "hidden" and requires login to view. Seemingly only because it doesn't agree with the opinion of the repository owners.

**Comment by karfau** [comment]
> We think it's good default and those who disagree can already disable it *and* are alerted every time. This means:
> 
> - we won't drop the feature
> - we won't make it "on demand" (PR already attempted this and was closed)
> 
> These two are not up for discussion because, again, those who don't like it can already disable it. 

I see, even though I tried to follow the discussions on this topics in the various issues and PRs, I was not aware that this is the current status. Thx for clarifying.

My opinion still is, that since GitHub provides the configuration to set the description to something that makes more sense per repo, the prerequisite
> 2. It makes sense as a default for everyone.

is no longer valid.

And as long as this is enabled by default, I can not recommend it (without the caveat of making sure everybody disables this option...) in any group that uses semantic releases.

But since you said this is not up for discussion, this will be my last comment on the matter, if I'm not asked for it.

**Comment by fregante** [comment]
Closing in favor of a more specific issue:

- https://github.com/refined-github/refined-github/issues/6181
