### ISSUE TITLE
Adding tooltip for copy to clipboard

### ISSUE THREAD

**Issue by Ashwin-op** [refined-github/refined-github#5157]
### Description

Adding a helpful tooltip like 'Copy to Clipboard' or 'Copy branch name' might help in understanding what the icon is for

### Screenshot

![image](https://user-images.githubusercontent.com/60032753/144792605-48066b11-b3d6-401d-ba8c-1ad606b25d7f.png)

### Example URL

https://github.com/refined-github/refined-github/pull/5156

**Comment by kidonng** [comment]
Please ask GitHub for this on https://github.com/github/feedback/discussions. We are not going to _add_ tooltips for native controls.

**Comment by Ashwin-op** [comment]
Ohh sorry my bad, I thought Refined Github added it 😅
