### ISSUE TITLE
Don't collapse `dim-bots` after hover

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5158]
### Description

Expanding PRs in order takes so long because you have to wait for 2 animations to complete. I think that we can just leave the line "hovered". This can be done by using an infinite delay (or even just 60s)

### Screenshot

![gif](https://user-images.githubusercontent.com/1402241/144845077-5d9a76c7-621d-4edf-9ba3-5cc76ed608b9.gif)

### Example URL

https://github.com/pixiebrix/pixiebrix-extension/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+bump+

**Comment by kidonng** [comment]
Leave them expanded but *still* dimmed right?

**Comment by fregante** [comment]
If it's not too much trouble to split the transitions, sure.
