### ISSUE TITLE
bugs-tab does not appear in Firefox 95

### ISSUE THREAD

**Issue by Dentrax** [refined-github/refined-github#5160]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

![Screen Shot 2021-12-08 at 09 18 03](https://user-images.githubusercontent.com/16493751/145158266-3a536894-3324-4355-8910-cee4cf9122b7.png)

![Screen Shot 2021-12-08 at 09 19 08](https://user-images.githubusercontent.com/16493751/145158388-a35b4124-9a13-4c95-b0e4-407869fda90f.png)

Version: `21.11.23`
Firefox: `95.0`
OS: `macOS 11`

Any ideas? :thi

### Example URL

https://github.com/refined-github/refined-github

### Browser(s) used

Firefox 95

**Comment by fregante** [comment]
Have you tried ~~turning it off and on again~~ refreshing the page? 

I also occasionally don't see the tab in Safari, this might not be a Firefox issue.

**Comment by cheap-glitch** [comment]
Weird, I'm also on Firefox and I've never seen this bug. Are there any error messages logged to console when it happens?

**Comment by yakov116** [comment]
No error, I have it on chrome too sometime

**Comment by Dentrax** [comment]
> Are there any error messages logged to console when it happens?

Oh, just saw this on the logs: 🙈 
```
The token seems to be incorrect or expired. Update it in the options.
```

How would we get notified once Refined GitHub token got expired? I think we can add a small icon that indicated this situation. Furthermore, we can add this case in the FAQ section to remind whether token is expired or not. Wdyt? ❤️

**Comment by fregante** [comment]
Closing for now since the issue was an expired token. Related discussion can continue in  #5168

If anyone sees this issue, comment here **including any messages in the console** and we can reopen it.
