### ISSUE TITLE
Download a file by one-click

### ISSUE THREAD

**Issue by realliyifei** [refined-github/refined-github#5163]
### Description

 See screenshot from another extension from chrome

### Screenshot

<img width="903" alt="image" src="https://user-images.githubusercontent.com/32441766/145492362-1d468fdc-f10a-4a08-9402-47f0df86eb02.png">

### Example URL

https://github.com/refined-github/refined-github

**Comment by busches** [comment]
If there's already an extension that does this, what makes it a better fit in RGH?

**Comment by kidonng** [comment]
This extension? https://github.com/softvar/enhanced-github

**Comment by fregante** [comment]
Indeed there are at least two extensions for this:

- https://github.com/softvar/enhanced-github
- https://chrome.google.com/webstore/detail/github-downloader/jplmabjbdhggnlhndkdfciacklbjcfel
