### ISSUE TITLE
Lists-related issues tracker

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5164]
### Description

GitHub is testing a new "Lists" feature:

https://github.blog/changelog/2021-12-09-lists-are-now-available-as-a-public-beta/

Apparently it comes with some appearance changes:

<img src="https://user-images.githubusercontent.com/44045911/145522418-019ee59a-3d63-4384-a629-59b336ad5858.png" width="50%">

- Star now has a dropdown
- Star and Fork swapped location
- "Social counts" (watch, star, fork) are now styled as badges (with gray background)
- "Social counts" also shown in the sidebar
- On user profile page, link to Stars are moved from the left side to the navbar

There are definitely rooms for improvement and some of our features may break. Opening this issue to track them. 

### Example URL

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
Related:

- https://github.com/refined-github/refined-github/issues/5161

**Comment by kidonng** [comment]
The "Stars" heading makes sense on your own stars page:

<img src="https://user-images.githubusercontent.com/44045911/145599292-c7818ac1-9dc3-4c28-8f4e-2d7345497421.png" width="75%">

...but not on other users':

<img src="https://user-images.githubusercontent.com/44045911/145599364-18cbd2f2-bbf0-4ea3-98ac-99f51e016079.png" width="75%">

---

What's with these dropdowns 🤔

https://user-images.githubusercontent.com/44045911/145599637-38014a24-858a-480c-a9ce-7cf2e65af154.mov

**Comment by fregante** [comment]
Unrelated, stars have been there for a while: https://github.com/refined-github/refined-github/issues/2589

**Comment by kidonng** [comment]
> Unrelated, stars have been there for a while: https://github.com/refined-github/refined-github/issues/2589

_*had_

**Comment by fregante** [comment]
> #2589 is the unrelated one

It was just an issue showing what it looked like and it was discussing it.

> I posted that comment because

Sure, but it's not an issue, it's a feature request. I suppose you're using this issue to track both of them though, so 👍

**Comment by fregante** [comment]
I think we're good for now. Specific issues can be opened for each bug we find
