### ISSUE TITLE
What to do when the token has expired?

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5168]
_Originally posted by @Dentrax in https://github.com/refined-github/refined-github/issues/5160#issuecomment-990683936_

> 
> > Are there any error messages logged to console when it happens?
> 
> Oh, just saw this on the logs: 🙈 
> ```
> The token seems to be incorrect or expired. Update it in the options.
> ```
> 
> How would we get notified once Refined GitHub token got expired? I think we can add a small icon that indicated this situation. Furthermore, we can add this case in the FAQ section to remind whether token is expired or not. Wdyt? ❤️

I'm wary of bothering users with popups and notices, so I'd probably treat an expired token the same way as a missing token: Just show a notice in the console and in the options page.

Now the question is: Are we showing "token is expired" in the options page? 

@Dentrax what's in the options page? Were the icons all red?

**Comment by fregante** [comment]
> I'd probably treat an expired token the same way as a missing token

Rather, as an _invalid_ token because a missing token can be determined synchronously but an invalid token needs an API call so it can only be determined after the call is made.

**Comment by cheap-glitch** [comment]
> Are we showing "token is expired" in the options page?

If I remember correctly, the text below the field becomes ":no_entry_sign: The token is invalid or expired" as soon as it becomes (or is made) invalid.

**Comment by Dentrax** [comment]
> @Dentrax what's in the options page? Were the icons all red?

I could not remember much, but probably the icons were red and there was a warning text as @.cheap-glitch said.

Since checking the token whether it is expired or not in the `Setings > Extensions > Refined GitHub > Preferences`, we had better to move another place to make it more visible to users.

What about turning this blue color to red? Or adding a warning icon left next to the notification icon. Wdyt?

<img width="153" alt="Screen Shot 2021-12-11 at 20 07 15" src="https://user-images.githubusercontent.com/16493751/145685288-08450bb2-a594-4997-8a1d-2f9a0102a3a4.png">

**Comment by cheap-glitch** [comment]
> Since checking the token whether it is expired or not in the Setings > Extensions > Refined GitHub > Preferences, we had better to move another place to make it more visible to users.

If you set your token to auto-expire after a certain time, GitHub will notify you in advance via mail anyway, right?

**Comment by Dentrax** [comment]
That's right. But it's easy to miss; probably that's how i missed. 🙈

**Comment by fregante** [comment]
I think an expired token warrants some UI. The difference between a missing token and an expired one is that the user took an action and inputted a valid token at some point, so they _want_ to make use of the token. 

How do we show this message without being too much in the way? Maybe we use `showToast` once every 4 hours at most. To hide the toast, the user can then just remove the token.

This is particularly important now that fine-grained tokens have a mandatory expiration (up to 1 year)

- https://github.com/refined-github/refined-github/issues/6092

**Comment by fregante** [comment]
We're handling this now.

- Active actions (e.g. `restore-file`) will show a popup with an error
- The options page shows that the token is invalid
- The "Report bug" page shows a banner telling the user to add a token
- Soon token-less users won't be able to open issues here: https://github.com/refined-github/refined-github/issues/7231
