### ISSUE TITLE
`addSidebarReviewButton` TypeError: Cannot read properties of undefined (reading 'append')

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5171]
### Description

1. Visit https://github.com/refined-github/refined-github/pull/5150#ref-issue-1076541009
2. Click the link to issue `#5169`
3. See error in console

### Browser(s) used

Chrome

**Comment by cheap-glitch** [comment]
That's because `quick-review` has an additional listener that triggers whenever the sidebar is replaced, and because of AJAX it persists on the issue page.

Should we fix the underlying logic in `setupPageLoad`, or should this be a quick feature-specific bandage?

**Comment by fregante** [comment]
deinit is our friend. I think if we add the listeners to an array they'll be removed. Whatever pattern works best for this feature.
