### ISSUE TITLE
`clean-dashboard` cannot handle correctly "star button" in GitHub homepage.

### ISSUE THREAD

**Issue by VergeDX** [refined-github/refined-github#5182]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

GitHub updates the star buttons recently, now it supports star list.
After that, star buttons in homepage cannot display correctly, like the screenshot:

![image](https://user-images.githubusercontent.com/25173827/145574777-40813958-203d-4e1e-973b-aa2fb75924b7.png)

After disable feature `clean-dashboard`, it shows fine:

![image](https://user-images.githubusercontent.com/25173827/145574916-d5455aee-d1d3-472f-92b8-837528da04e1.png)

### Example URL

https://github.com/

### Browser(s) used

Chromium

**Comment by VergeDX** [comment]
Related code is here: https://github.com/refined-github/refined-github/blob/main/source/features/clean-dashboard.css#L86

**Comment by kidonng** [comment]
Thanks for reporting, related to #5164
