### ISSUE TITLE
Copy button for Code blocks in Gist comments

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5183]
### Description

The main site (`github.com`) provides a copy button for code blocks, but this is not the case for Gist.

### Example URL

https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236#gistcomment-1926696

**Comment by fregante** [comment]
To be honest I find that feature more annoying than useful. We also rejected it before

**Comment by kidonng** [comment]
> We also rejected it before

Searching "gist copy" doesn't give me a related result though 😅

**Comment by yakov116** [comment]
https://github.com/refined-github/refined-github/issues/1095 and https://github.com/refined-github/refined-github/issues/2423

**Comment by kidonng** [comment]
#2423 is unrelated. Things are also different from #1095 in the sense that this is GitHub native feature (at least on the main site).

**Comment by fregante** [comment]
Codecopy still exists, so the same reason for closing still applies:

https://github.com/zenorocha/codecopy/blob/a2dea68899664ab0e53b39cfd3e8b9d27852f3ca/dist/manifest.json#L52

There'a also a userscript that works on gists, so twice the reason: https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-copy-code-snippet

**Comment by kidonng** [comment]
I forgot why I didn't reply in time, but here I am;

> Codecopy still exists, so the same reason for closing still applies:
> 
> [zenorocha/codecopy@`a2dea68`/dist/manifest.json#L52](https://github.com/zenorocha/codecopy/blob/a2dea68899664ab0e53b39cfd3e8b9d27852f3ca/dist/manifest.json#L52)

Sadly, not available for the moment: https://github.com/zenorocha/codecopy/issues/71

> There'a also a userscript that works on gists, so twice the reason: [Mottie/GitHub-userscripts/wiki/GitHub-copy-code-snippet](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-copy-code-snippet)

That works on Gists, but duplicate with native ones on main site:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/44045911/155522705-35598fc9-75c1-4f71-a464-56a5f0ae9664.png">
