### ISSUE TITLE
`profile-gists-link` is not responsive

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5184]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

https://user-images.githubusercontent.com/44045911/145593519-f93e98f0-001f-4df0-b0e6-b3b5dca18dd3.mov

### Example URL

https://github.com/kidonng

### Browser(s) used

Chrome

**Comment by yakov116** [comment]
I think this is a new thing from github. Probably needs the same logic as `more-dropdown`

**Comment by kidonng** [comment]
> I think this is a new thing from github.

It could be, the Stars are moved from the left side. Then #5164

**Comment by fregante** [comment]
Related: https://github.com/refined-github/refined-github/issues/4008#issuecomment-828173667

**Comment by kidonng** [comment]
Things are still a little chunky:

https://user-images.githubusercontent.com/44045911/154839468-d6abaa33-f500-4cc7-82df-d766855e38d4.mov

But since it goes away when resized and doesn't appear when hiding the "Packages" tab (which is what I do), maybe consider it a "known bug"?
