### ISSUE TITLE
Restore `monospace-textareas`/`suggest-commit-title-limit`

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5188]
### Description

Part feature request, part bug.

One of our features was to use fixed-width fonts in the commit fields to know when it reaches the end: `suggest-commit-title-limit`

This no longer works. We should probably restore `monospace-textareas` in some capacity.

The last relevant piece of code still lives here:

https://github.com/refined-github/refined-github/blob/f843b8b97605a9f0b7d0b810f2ac1aad6bace373/source/features/github-bugs.css#L45-L47

And one selector was removed in in: [`5b7282a` (#5113)](https://github.com/refined-github/refined-github/pull/5113/commits/5b7282afc40b013f5928271fb6740cf70b4e4295)

### Screenshot

<img width="554" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/145638221-1ec6f774-c3c5-414d-87dc-2a4905880804.png">

### Example URL

https://github.com/refined-github/refined-github/pull/5139

**Comment by fregante** [comment]
Related link with demo of what it looked like:

- https://github.com/refined-github/refined-github/pull/4070

**Comment by kidonng** [comment]
> And one selector was removed in in: [`5b7282a` (#5113)](https://github.com/refined-github/refined-github/pull/5113/commits/5b7282afc40b013f5928271fb6740cf70b4e4295)

That's unrelated, it is the commit SHA button on commit lists.
