### ISSUE TITLE
`rgh-linkify-features` is not working in a title in a specific instance

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5189]
Look at the issue title, it works here: https://github.com/refined-github/refined-github/issues/4146

But it doesn't work here: https://github.com/refined-github/refined-github/issues/5188

Could it be because the first `code` element does not match any features so it bails?

### Screenshot

<img width="989" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/145639225-58a55477-e117-4ffb-bd1e-da421aca8d3f.png">

### Console

No errors in the console. 

### Browser

Safari

**Comment by fregante** [comment]
I lost count of how many issues I opened today. Sorry 😅

**Comment by cheap-glitch** [comment]
> Could it be because the first `code` element does not match any features so it bails?

No, it's just caused by a trailing space after the feature name: `suggest-commit-title-limit `.

Worth fixing?

**Comment by fregante** [comment]
No 🥲
