### ISSUE TITLE
reaction avatars not working on review comment

### ISSUE THREAD

**Issue by mischnic** [refined-github/refined-github#5190]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [x] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

There are no avatars for the reactions on review comments

<img width="927" alt="Bildschirmfoto 2021-12-11 um 10 12 32" src="https://user-images.githubusercontent.com/4586894/145671211-b747c080-5fb9-4bad-9889-7a476c36d40a.png">

### Example URL

https://github.com/parcel-bundler/parcel/pull/7418#pullrequestreview-828068246

### Browser(s) used

Chrome 96.0.4664.55

**Comment by kidonng** [comment]
See https://github.com/refined-github/refined-github/pull/5150#issuecomment-991133953
