### ISSUE TITLE
Have the PR option preselected instead of commit to main/master

### ISSUE THREAD

**Issue by pvinis** [refined-github/refined-github#5201]
### Description

Too many times I go to do a small change, and want to make it into a PR so that others see and approve first, even if its a small change.

Because I usually do this fast, I keep hitting the button and missing the option to make a PR.

I think having the PR option be the preselected one makes sense for most people and most repos. Definitely more sense than direct commit to main 🤔.

### Screenshot

https://f.p0l.co/file/dropshare-public-pavlos/Screen-Recording-2021-12-14-at-09.08.36.mov

### Example URL

https://github.com/artsy/eigen/blob/main/src/lib/store/config/features.ts

**Comment by yakov116** [comment]
I would only want this on a public repo

JMHO

**Comment by pvinis** [comment]
I agree for the public repos. totally.

**Comment by kidonng** [comment]
No, you should use [branch protection rule](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#:~:text=Require%20a%20pull%20request%20before%20merging)

![image](https://user-images.githubusercontent.com/44045911/146027693-ae0ad1ee-6a99-4165-8893-7c50c3ebcdf1.png)

(You may also need this:

![image](https://user-images.githubusercontent.com/44045911/146027732-d1c1d0a5-c56a-4ca0-93a4-9e7358ea4520.png)
)

Result:

![image](https://user-images.githubusercontent.com/44045911/146027763-00ef60f2-93c7-4941-a90e-3fd16618b4b7.png)
