### ISSUE TITLE
Safari test should work with signing certificate

### ISSUE THREAD

**Issue by sindresorhus** [refined-github/refined-github#5202]
Previously, there was no signing certificate set in the Xcode project, but it's annoying for me to change it to the correct certificate each time. It's better to force `xcodebuild` command to run without a certificate instead.

https://github.com/refined-github/refined-github/runs/4524894735?check_suite_focus=true

https://github.com/refined-github/refined-github/blob/a79f49bdb7e571bd8402f3cddba8154220bd0e0c/package.json#L13

---

I have disabled the test until this is resolved: https://github.com/refined-github/refined-github/commit/a79f49bdb7e571bd8402f3cddba8154220bd0e0c#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R79

**Comment by fregante** [comment]
I have a solution for this that goes through a local ENV file. This allows you to set your own certificate without setting it for everyone (the change on main broke CI as well as my build)
