### ISSUE TITLE
"+Create list" not working

### ISSUE THREAD

**Issue by berezovskyi** [refined-github/refined-github#5214]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

<img width="1536" alt="Screen Shot 2021-12-16 at 11 53 52" src="https://user-images.githubusercontent.com/64734/146358688-3d48f221-443e-4c3d-a442-94c59db0aba6.png">

The list creation button is not clickable.

Feature finder says it's the fault of `warning-for-disallow-edits` but disabling it has no effect. Fun thing is that the bug disappears when the feature finder is started.

### Example URL

https://github.com/enqueue/metabase-clickhouse-driver

### Browser(s) used

FF 95

**Comment by berezovskyi** [comment]
Even more curious is that the bug also disappears when the dev tools panel takes too much vertical space:

<img width="1680" alt="Screen Shot 2021-12-16 at 12 04 49" src="https://user-images.githubusercontent.com/64734/146360470-81b86265-5990-4c98-88cb-dd0f0478ab35.png">

<img width="1680" alt="Screen Shot 2021-12-16 at 12 04 56" src="https://user-images.githubusercontent.com/64734/146360491-ed9413b9-fa2f-434e-9202-bed8aab4e983.png">

Note: there is a log message about `close-out-of-view-modals`. Disabling it does not seem to help either.

**Comment by berezovskyi** [comment]
Seems to be related to #5164

**Comment by cheap-glitch** [comment]
Thanks for the detailed report! This is likely a z-index issue caused by `sticky-sidebar`.

**Comment by fregante** [comment]
I specifically remember setting a z-index for that header widget at some point. Since the recent changes, it's possible that it's creating issues.

**Comment by fregante** [comment]
> Even more curious is that the bug also disappears when the dev tools panel takes too much vertical space:

That's because it's due to the sidebar being sticky and with a higher z-index.

This specific bug is due to a native CSS rule though:

<img width="953" alt="Screen Shot 15" src="https://user-images.githubusercontent.com/1402241/146507975-acce902e-64e6-41d9-979f-2eca8ee82a9e.png">

**Comment by fregante** [comment]
I'm not sure I understand why they'd want this still to apply only on `:active`

I pushed a hotfix. PR to fix it properly welcome. Should this change be limited to cases where `sticky-repo-sidebar` is active?

`.page-actions` is there to limit the selector to that specific item up there.
