### ISSUE TITLE
`useful-forks` disappeared from Network graph page

### ISSUE THREAD

**Issue by smowtenshi** [refined-github/refined-github#5225]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

Network graph page should display a link to [useful-forks.github.io](https://useful-forks.github.io), but apparently it doesn't, for some time already.
![Screenshot](https://user-images.githubusercontent.com/7839556/146650654-51a255a4-8fa5-41ae-b3b9-efaefd497378.png)

Having "Show the features enabled on each page..." actually doesn't show `useful-forks` in the console, no matter what page I visit.

### Example URL

https://github.com/refined-github/refined-github/network

### Browser(s) used

Firefox Nightly 97.0a1

**Comment by cheap-glitch** [comment]
Related to #5164. It's just a selector that needs updating.

**Comment by smowtenshi** [comment]
Ooh, thank you for the explanation.
