### ISSUE TITLE
The content of `latest-tag-button` and `list-prs-for-file` is not aligned

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5232]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

<img width="310" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/147105461-0b1d2e23-109b-4a9c-af8f-5802e271acf1.png">

### Example URL

https://github.com/refined-github/refined-github/blob/main/source/refined-github.ts 
https://github.com/timolins/react-hot-toast/blob/main/src/core/store.ts

### Browser(s) used

Safari 15.1

**Comment by cheap-glitch** [comment]
Is the issue that the icons are misaligned with the text? Or that the buttons are too narrow compared to the native branch picker? (Or both?)

**Comment by fregante** [comment]
The icons are too high. The `sup` should probably also be lowered

**Comment by cheap-glitch** [comment]
The alignment seems fine for me on Firefox:

![image](https://user-images.githubusercontent.com/46634000/147074234-1fe2d8f3-2c82-406e-8e69-a41e2f9b1712.png)

**Comment by kidonng** [comment]
It's very subtle... I guess this is the outcome of using smaller buttons. I don't think it's an issue since they are not of the same size anyway.

**Comment by fregante** [comment]
Not they're misaligned to the text, not just the button

**Comment by kidonng** [comment]
Maybe I misunderstood, are you referring to the two buttons RGH added are misaligned, or all of the three?

And to be honest, I didn't really see the issue here. For comparison, this is what I got on Chrome:

![image](https://user-images.githubusercontent.com/44045911/147415574-986db544-92fc-4f75-ac0b-b4483f81cbaa.png)

**Comment by fregante** [comment]
Look closer. Compare the padding above the tag icon with the one below. They're all closer to the top edge
