### ISSUE TITLE
`list-prs-for-branch` should exclude "reverse" pull requests

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5234]
### Description

By "reverse" pull requests I mean merging _upstream_ into forks. Nobody is interested in them.

![image](https://user-images.githubusercontent.com/44045911/146808196-4b8bed51-3969-4e9c-a41f-7f79649bea5b.png)

---

Also I feel `list-prs-for-branch` probably needs to be shown on more pages (currently it's only `isRepoCommitList`). I almost forgot it until this issue.

### Example URL

https://github.com/refined-github/refined-github/commits/hotfix

**Comment by fregante** [comment]
Is this as easy by filtering by user/repo? Or is there some field in the API call to do the same? I'd prefer the latter

**Comment by fregante** [comment]
I'm confused. We're already specifically asking the API for PRs open on the current repo. Why is that PR appearing here?

https://github.com/refined-github/refined-github/blob/dbb4cf8d6503ccfbdad00d13054aff8e15f3b7cd/source/features/list-prs-for-file.tsx#L69-L73

**Comment by fregante** [comment]
Can you create a permanent repro on the sandbox?

**Comment by fregante** [comment]
Can't repro
