### ISSUE TITLE
`quick-comment-edit` should only shown on editable DIscussions comments

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5235]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

Like #4712 but for DIscussions:

<img width="933" alt="截屏2021-12-21 02 06 29" src="https://user-images.githubusercontent.com/44045911/146812726-b334f902-3f53-4f1c-915c-ef86e46d08f6.png">

### Example URL

https://github.com/PatrickF1/fzf.fish/discussions/190

### Browser(s) used

Chrome

**Comment by gamemaker1** [comment]
Looks like this is because GitHub uses the `.lock-toggle-link` class on the `Create issue from discussion button` 🤦🏾

![image-of-devtools-and-the-example-url](https://user-images.githubusercontent.com/34235681/146868217-a96f5d6e-5d56-486b-a573-0e068be4d0b2.png)

**Comment by kidonng** [comment]
That's... technically correct because it indeed locks the discussion.

**Comment by gamemaker1** [comment]
Oh I didn't know that creating an issue from a discussion locks it 🤔 

I did open a PR to fix this though - https://github.com/refined-github/refined-github/pull/5236

**Comment by kidonng** [comment]
Sorry, I was mislead by this: https://github.com/vercel/vercel/discussions/6793

![chrome_screenshot_1640079835539.png](https://user-images.githubusercontent.com/44045911/146908169-d346bed6-d81d-40bb-9218-6299087fc889.png)

There's no relation between them. Maybe GitHub's just being lazy and reusing the markup here.
