### ISSUE TITLE
Several icons and text are vertically misaligned

### ISSUE THREAD

**Issue by waldyrious** [refined-github/refined-github#5247]
### Description

This is a bug with GitHub, not Refined Github; I was hoping RGH could address it. The icons at the left of some buttons' labels appear lower than they should, whereas the text is rendered higher than it should be. This is most visible on Firefox, but it's also noticeable, to a lesser degree, in Brave (Chromium-based).

### Screenshot

Screenshots from the example URL indicated below, in Firefox 95.0.1 on Ubuntu:
![Screenshot from 2021-12-26 20-27-29](https://user-images.githubusercontent.com/478237/147419702-0a1bc52a-97d0-4c4a-b6d2-e0d2bf39947b.png)
![Screenshot from 2021-12-26 20-37-48](https://user-images.githubusercontent.com/478237/147419703-a57cc985-f6b6-4134-8513-3ff12f8bb387.png)

...and in Brave (v1.33.106, Chromium 96.0.4664.110), also in Ubuntu:
![Screenshot from 2021-12-26 20-42-00](https://user-images.githubusercontent.com/478237/147419565-62facc7c-bf94-4d24-9dfe-592a41526216.png)

### Example URL

https://github.com/elementary/switchboard-plug-keyboard/pull/214/files?w=1

**Comment by fregante** [comment]
I don’t think we can fix your OS without breaking everyone else’s unfortunately. I'd ask to make sure your fonts are in good state because maybe their sizing is throwing the icons of.

**Comment by waldyrious** [comment]
Hmm, I did find it odd that nobody had reported this before. I'll wait a few more days, and if nobody else is seeing this, I will close the issue.

**Comment by fregante** [comment]
I suggest also contacting GitHub, they're pretty responsive. If you can reproduce the issue on a fresh Ubuntu install even better

**Comment by waldyrious** [comment]
Since after almost a month nobody else has manifested seeing the same issue, I'll close the thread. Thanks for the response!
