### ISSUE TITLE
Safari: Automate setting the current version in manifest.json

### ISSUE THREAD

**Issue by sindresorhus** [refined-github/refined-github#5250]
I currently have to manually set the version in

https://github.com/refined-github/refined-github/blob/dc0ca145e2fcfda83bc83a3396e9c27d00d4444b/distribution/manifest.json#L3

when I archive a build for Safari in Xcode.

It would be nice to have a Xcode run script that sets it automatically in the built app during archive.

Related to the discussion in https://github.com/refined-github/refined-github/pull/5203 about automating stuff.

**Comment by fregante** [comment]
Suggested solution: a `prepare:safari` script that:

1. reads the version from the latest git tag
2. rm -rf distribution
3. npm run build
4. sets the version in distribution/manifest.json and LocalOverrides.xcconfig file


This can be a macOS-only sh file in the build folder. 

Thoughts?

**Comment by sindresorhus** [comment]
Sounds good.

It would be slightly cleaner to do the version setting of `distribution/manifest.json` in the archived build (using Xcode run script) as it wouldn't cause a dirty Git tree (since the source file would not be modified).

**Comment by sindresorhus** [comment]
`3.` should also `npm install`.

**Comment by fregante** [comment]
I forget that that file isn't built. Hopefully I'll be able to use Parcel soon enough for that to stop being a problem. In the meanwhile we can restore CopyWebpackPlugin to move those files. I think it's more difficult to change the version in the archived extension

**Comment by sindresorhus** [comment]
The path would be something like this in a run script:

```
"${BUILT_PRODUCTS_DIR}/[FIND EXACT PATH]/manifest.json"
```
