### ISSUE TITLE
Personal token in Safari extension is sometimes deleted by itself

### ISSUE THREAD

**Issue by rakleed** [refined-github/refined-github#5251]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

Personal token in Safari extension is sometimes deleted on its own, even though I didn't even go into the extension's settings. Sometimes I clear the cache using Cmd+Opt+E, but at the moment I have not been able to reproduce the problem due to this. So I don't understand why this problem occurs. This issue has never appeared in a Chrome extension.

### Example URL

Refined GitHub settings

### Browser(s) used

Safari 15.2

**Comment by cheap-glitch** [comment]
May be caused by 👇
https://github.com/refined-github/refined-github/blob/de1287f62fd27d42a97d7d5615903510d4954755/source/options.tsx#L301-L304

**Comment by fregante** [comment]
Hopefully not, the cache clearer should only affect keys starting with `cache:`. My token hasn't been lost in a long while now

**Comment by fregante** [comment]
> One issue I know that when upgrading from Safari 5.1 to 5.2 you lose everything

I just updated to 5.2 and I have not lost anything (their release notes suggested that this would happen, but…)

Are you building the extension locally or installing it from the store? I see you develop some extensions, maybe data is being lost somewhere in the process.

**Comment by rakleed** [comment]
@fregante on the current device, I only use the version from the App Store and did not build the extension myself.

**Comment by fregante** [comment]
I just lost the token on iOS… I don’t think I've done anything here either (nothing was updated, I never open the options, I didn't clear anything)

I don’t think it's Refined GitHub's fault unfortunately though.

**Comment by fregante** [comment]
It hasn't happened since, it was likely a browser bug
