### ISSUE TITLE
`user-profile-follower-badge`: select_dom(...) is undefined

### ISSUE THREAD

**Issue by kerolloz** [refined-github/refined-github#5255]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Example URLs

Any profile page of a follower

### Browser(s) used

Firefox

### Description

![image](https://user-images.githubusercontent.com/36763164/147849139-0de9233b-0255-440b-b559-c83ae560c9a5.png)

```
init@moz-extension://77ae74f8-0cd3-4c5c-b531-a229e8f9195f/build/refined-github.js:6527:98
async*runFeature@moz-extension://77ae74f8-0cd3-4c5c-b531-a229e8f9195f/build/refined-github.js:2903:24
setupPageLoad@moz-extension://77ae74f8-0cd3-4c5c-b531-a229e8f9195f/build/refined-github.js:2916:40
add/<@moz-extension://77ae74f8-0cd3-4c5c-b531-a229e8f9195f/build/refined-github.js:2939:35
async*add@moz-extension://77ae74f8-0cd3-4c5c-b531-a229e8f9195f/build/refined-github.js:2940:11
async*@moz-extension://77ae74f8-0cd3-4c5c-b531-a229e8f9195f/build/refined-github.js:6523:21
@moz-extension://77ae74f8-0cd3-4c5c-b531-a229e8f9195f/build/refined-github.js:10067:5
@moz-extension://77ae74f8-0cd3-4c5c-b531-a229e8f9195f/build/refined-github.js:10068:3
```

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by cheap-glitch** [comment]
This should be fixed in `21.12.21`, but for some reason the release wasn't published on AMO. Maybe it's stuck in the review queue or something  ¯\\\_(ツ)\_/¯

**Comment by fregante** [comment]
Yeah gotta wait for the next release in a week or more. Firefox occasionally fails because they update their terms…

**Comment by fregante** [comment]
22.1.11 will be available on the stores today 

https://github.com/refined-github/refined-github/releases/tag/22.1.11
