### ISSUE TITLE
Repo Lines Counter

### ISSUE THREAD

**Issue by xuanweiace** [refined-github/refined-github#5256]
### Description

I think there was a plugin that did this, but I can't find it anymore.  
It can be displayed to the right of each project name, representing the total number of lines of code for the current project, or statistics for each type(eg: js:1000lines, python:278lines).  

I think this can help users quickly locate the difficulty of the project, learning cost, etc .

### Example URL

https://github.com/refined-github/refined-github

**Comment by cheap-glitch** [comment]
I think this is out of scope for RGH. At most we could add a link that would redirect to a particular web page or app, like we do with https://useful-forks.github.io.

**Comment by fregante** [comment]
Oh I thought the request was to find that plug-in and left it open without labels. If this is a feature request we can close it, it would be more pertinent in a "GitHub repo size" extension.

**Comment by xuanweiace** [comment]
> Oh I thought the request was to find that extension and I left the issue open without labels to see if anyone remembered.
> 
> If this is a feature request we can close it, it would be more pertinent in a "GitHub repo size" extension.

where to find "GitHub repo size"

**Comment by yakov116** [comment]
https://github.com/harshjv/github-repo-size

**Comment by xuanweiace** [comment]
> I think this is out of scope for RGH. At most we could add a link that would redirect to a particular web page or app, like we do with https://useful-forks.github.io.

what is the full name of RGH?

**Comment by xuanweiace** [comment]
> https://github.com/harshjv/github-repo-size

Get it.Thank you. But it is just the size of the repo, not the lines of code.

**Comment by yakov116** [comment]
> > I think this is out of scope for RGH. At most we could add a link that would redirect to a particular web page or app, like we do with [useful-forks.github.io](https://useful-forks.github.io).
> 
> what is the full name of RGH?

RGH is this repo (**R**efined **G**it**H**ub)

**Comment by fregante** [comment]
> > [harshjv/github-repo-size](https://github.com/harshjv/github-repo-size)
> 
> Get it.Thank you. But it is just the size of the repo, not the lines of code.

Weight and lines of code is basically the same metric, just counted differently. What I meant is that you can ask one of those extensions to add this feature because it's similar in scope.



> where to find "GitHub repo size".

https://chrome.google.com/webstore/category/extensions

**Comment by fregante** [comment]
The extension exists: https://github.com/kas-elvirov/gloc
