### ISSUE TITLE
Extend `hide-low-quality-comments`  with more keywords

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5257]
### Description

See the attached URL. Instead of matching exact comments [like we're doing](https://github.com/refined-github/refined-github/blob/6f300c941cfa7639a6b32333105f20cf1f0ba4e4/source/helpers/is-low-quality-comment.ts), we can drop every useless word and see what's left after it: _me, too, thank, thanks, you, issue, same, any, updates, solution, following, …_ and we should drop uncommon misspelling (like `followig`)

Also we should ensure we don't hide comments that have links because `[here](##)` could still be useful.

### Screenshot

<img width="470" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/147864788-b0eadcc6-9fd8-40f9-aab5-ca3c348c5aff.png">

### Example URL

https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/167#issuecomment-813856455

**Comment by fregante** [comment]
To clarify, many of the comments below these can't be filtered out because they have screenshots and code. Not much we can do about those

**Comment by fregante** [comment]
lol the feature is already doing god's work:

<img width="379" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/1402241/147864859-82128e94-f784-4d8c-9453-39104cd41779.png">

**Comment by kidonng** [comment]
How about a "strict mode" that enable more filters only when the thread has more than certain comments?
