### ISSUE TITLE
`dim-bots` only works on the first page

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5260]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Example URLs

https://github.com/renovatebot/renovate/commits/main

### Browser(s) used

Chrome

### Description

https://user-images.githubusercontent.com/44045911/147964542-d8474d4e-8fb1-476c-8f19-432c1d6b95e4.mov

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by cheap-glitch** [comment]
Could not reproduce on 21.12.12 with Firefox.

**Comment by fregante** [comment]
Could not reproduce on 21.12.12 with Safari.

**Comment by kidonng** [comment]
I'm on 21.12.21, forgot to mention that.
