### ISSUE TITLE
Add ability to hide/show unread notifications dot

### ISSUE THREAD

**Issue by jrieken** [refined-github/refined-github#5267]
### Description

Each and every page on GH shows the notifications bell. At times the bell is decorated with a blue dot for unread notifications. This little dot can be very disturbing because I cannot resist to click it, usually distracting me from my work. I would like to take back control and I want to decide when it's time for notifications. 

So the request is simple, add a way to turn off the button and turn it back on, basically run these two lines

```js
// off
document.querySelector('.notification-indicator .mail-status.unread').style.visibility = 'hidden'

// on 
document.querySelector('.notification-indicator .mail-status.unread').style.visibility = ''
```

<img width="186" alt="Screen Shot 2022-01-05 at 16 36 31" src="https://user-images.githubusercontent.com/1794099/148244937-2108bc5c-5284-4f88-a5ee-6fd2d6000f4d.png">

### Screenshot

Mockup of a possible UX, have a drop down menu for the bell icon with an entry to mute/unmute notifications

<img width="223" alt="Screen Shot 2022-01-05 at 16 44 13" src="https://user-images.githubusercontent.com/1794099/148246182-e1312127-e3e3-4e33-8fc9-4a948ead889a.png">

### Example URL

https://github.com/refined-github/refined-github

**Comment by cheap-glitch** [comment]
> I cannot resist to click it, usually distracting me from my work.

I know that pain… I ended up adding this CSS in the options page:

```css
notification-indicator .unread {
	display: none !important;
}
```

And I also use the "Notification Preview for GitHub" extension, which shows the unread notifications when hovering on the bell icon.

It's not perfect, but it alleviates the problem quite a bit.

**Comment by jrieken** [comment]
Thanks for that! This will already help me a ton - less distractions, more vscode features

**Comment by fregante** [comment]
Does it work for you? I also disabled the badges on some apps on my phone but unless I completely forget about them I still open them regularly to look for notifications.


Like @cheap-glitch did, I'd probably just stick the CSS in the options and be done with it, although I know this is not the 2-click operation you suggest.

**Comment by jrieken** [comment]
> Like @cheap-glitch did, I'd probably add the CSS to the options, although I know this is not the 2-click operation you suggest.

This works great for me (after a day of trying it). I am fine to close this issue as resolved, or trade the 2-click operation with a simple setting to hide/show the notification.

**Comment by kidonng** [comment]
The request is valid but unfortunately it will never become the default, hence not in Refined GitHub.

**Comment by yakov116** [comment]
> The request is valid but unfortunately it will never become the default, hence not in Refined GitHub.

☝️
