### ISSUE TITLE
Sort discussions by upvotes

### ISSUE THREAD

**Issue by szmarczak** [refined-github/refined-github#5269]
### Description

This would allow e.g. getting the most desired features.

### Example URL

https://github.com/sindresorhus/got/discussions

**Comment by kidonng** [comment]
Already brought up in #4993, but I guess worth a dedicated issue.

**Comment by cheap-glitch** [comment]
Is this really feasible for RGH?

Unless there's a native implementation that we can make easier to apply or access, doesn't this mean a lot of API calls + replacing a huge chunk of the DOM?

**Comment by fregante** [comment]
This was also kind of discussed for issues but we ended up implementing it as a link to the best comment instead: 

- https://github.com/refined-github/refined-github/issues/1898

I think the same reasons apply to discussions, with the addition that discussions are a relatively much rarely-used feature.

**Comment by kidonng** [comment]
`?sort=top`

**Comment by fregante** [comment]
🤔 is it not this?

https://github.com/sindresorhus/got/discussions?discussions_q=sort%3Atop

<img width="540" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/148636003-83bcdbf8-d1e4-4027-92a7-f14b8ab0637b.png">

**Comment by szmarczak** [comment]
I can't believe it was there the entire time 🙈
