### ISSUE TITLE
Github issues in columns

### ISSUE THREAD

**Issue by nicooprat** [refined-github/refined-github#5272]
### Description

Was thinking about presenting Github issues in columns, filtered by labels. Yeah just like any Kanban tool out there, without needing to use another SaaS, or projects in Github (because it would need to add every issue manually).

The idea would be to add a dropdown that lets user select which labels to use for splitting. A column is created for each label, filtering out the issues within.

From my quick test with browser devtools, it looks like we can just duplicate the main div containing issues, and remove any children div not containing the right label, without breaking any feature...

Potential issues:

* There could be duplicate issues among columns (maybe not really important?)
* How to deal with pagination? (maybe not important too)

What do you think?

(PS. In my case it would be even more useful for the Pull Requests page, but I think it's almost the same.)

### Screenshot

I just hacked in 5min this repo issues page to get this (chosen labels here would have been `discussion`, `bug` and `meta` for instance):

![image](https://user-images.githubusercontent.com/645641/148576734-94d5e19d-3532-4814-a969-04b0f7049921.png)

Edited code looks like this:

![image](https://user-images.githubusercontent.com/645641/148576352-a9a6c583-4d89-42d8-b838-5cf978bac193.png)

### Example URL

https://github.com/refined-github/refined-github/issues

**Comment by kidonng** [comment]
Looks neat! But unfortunately this seems to fall under the following rule, so it is unlikely to be added:

https://github.com/refined-github/refined-github/issues/2960#issuecomment-606767200

**Comment by fregante** [comment]
It does look neat, but I think it's too much for RG for a variety of reasons (not a good default, too big of a UI change, too open to opinions (top to bottom or masonry?), potentially a lot of code, …)

**Comment by nicooprat** [comment]
Thanks for your answer! Understood.
