### ISSUE TITLE
Option to add real names when the user is using a real name

### ISSUE THREAD

**Issue by jasonvarga** [refined-github/refined-github#5273]
### Description

I love the `Adds the real name of users by their usernames` feature where it puts the real name in parenthesis next to it.

However personally I don't like how it replaces the username inline if it's the same as the real name. (e.g. Sindre Sorhus in the screenshot below). This issue: #2165

Would it be possible to make _just_ the inline replacement an additional option? (Which could default to true for most people)

My use case is that I tend to copy/paste usernames from PRs into changelogs. Now I have to dig a little deeper to get their actual username. Not a big deal, I know, but thought it'd be worth asking.

If this sounds okay, I'd be happy to attempt the PR myself. Thanks!

### Screenshot

![](https://user-images.githubusercontent.com/1402241/62075835-5f82ce00-b270-11e9-91eb-4680b70cb3cb.png)

### Example URL

https://github.com/refined-github/refined-github/issues/5268

**Comment by kidonng** [comment]
> My use case is that I tend to copy/paste usernames from PRs into changelogs. Now I have to dig a little deeper to get their actual username. Not a big deal, I know, but thought it'd be worth asking.

GitHub already provides [such functionality](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes), you may want to try it instead.

**Comment by fregante** [comment]
> My use case is that I tend to copy/paste usernames from PRs into changelogs

You have two alternatives:

- right click -> copy address. Maybe you can use the address as is if  GitHub automatically shortens it to `@user`
- `quick-mention` takes the whole username comprehensive of `@` symbol and places it in the textarea. You might be able to click on multiple users this way and copy them all at once

<img width="304" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/148635683-de87467e-6ba9-4732-9630-361518448802.png">

**Comment by jasonvarga** [comment]
Thank you for the suggestions.

Like I mentioned, if you're okay with my suggestion, I'd be fine with doing the PR myself.
Otherwise, feel free to just close this.

**Comment by fregante** [comment]
> an additional option

Unfortunately that's not possible, [features don't have options](https://github.com/refined-github/refined-github/issues/2960#issuecomment-606765658)

**Comment by jasonvarga** [comment]
My idea was to split the existing feature into two.

First one would add all the real names in parenthesis, and the second one would merge them if the username matched the full name.

**Comment by fregante** [comment]
That's basically the same thing, effectively even worse for everyone because now one feature completely depends on the other, meaning more core, worse perf, bad UX.

I have an idea though: We can use fake spaces.

PR welcome to replace `Sindre Sorhus` with `Sindre<span></span>Sorhus` and `span {padding-left: 0.3em}

**Comment by fregante** [comment]
Ehhh, unfortunately that's not possible either since we drop dashes and add accents and punctuation:

https://github.com/refined-github/refined-github/blob/c9d133547f45321c28fb7ddb35ffc08189c9082e/test/helpers.ts#L100-L108

Any alternatives? I'm thinking about restoring the original text on hover, but I'm still unconvinced about the necessity of this. It'd be ok only if had a simple and lightweight solution.

**Comment by kidonng** [comment]
You can disable `show-names` or even Refined GitHub when you are going to make releases. Some extension manager makes it very convenient to do so.

@fregante Do you think we can add a extension popup that only includes option toggles?

**Comment by jasonvarga** [comment]
> You can disable show-names or even Refined GitHub when you are going to make releases.

This is honestly fine with me. I didn't mean to create so much fuss with this issue. Seems that there are more complicated moving parts than I first assumed.

**Comment by fregante** [comment]
No worries, your request makes sense, we just don't like to make things complicated since we only have hundreds of features. If there's a simple solution we can attempt to fix it.

**Comment by fregante** [comment]
https://github.com/refined-github/refined-github/issues/5273#issuecomment-1007901332
