### ISSUE TITLE
`reactions-avatars` is broken in reviews, releases and discussions

### ISSUE THREAD

**Issue by cheap-glitch** [refined-github/refined-github#5275]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Example URLs

https://togithub.com/refined-github/refined-github/pull/5113#discussion_r758597247

### Browser(s) used

Firefox

### Description

![image](https://user-images.githubusercontent.com/46634000/148637296-5b38900e-c546-432d-91cb-0719d39064a8.png)

![image](https://user-images.githubusercontent.com/46634000/148637351-0b143feb-95e4-4534-a393-c6fae56fe9b4.png)

~~Note: this happens on 21.12.12, couldn't test on latest release~~

Edit: confirmed to happen on latest main too.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by cheap-glitch** [comment]
This might be a GitHub bug, because the value of `aria-label` on the reaction button seems wrong:
```html
<button id="github--social_button_component-a7ad34" class="\n    btn-link\n    d-fl…render-button ml-0 mb-0" style="border-radius:100px;font-size:12px;" name="input[content]" type="submit" value="HEART react" aria-label="heart (1): kidonng, 04:30AM on December 31, 2021" aria-pressed="false" data-button-index-position="1" data-reaction-content="heart" aria-describedby="tooltip-1641641603007-9200">
```

**Comment by fregante** [comment]
It's possible that GitHub just changed the label and now it describes the single reaction

**Comment by cheap-glitch** [comment]
> It's possible that GitHub just changed the label and now it describes the single reaction

That's what I thought, but the tooltip stayed the same:

![image](https://user-images.githubusercontent.com/46634000/148649738-51905773-62f0-4d62-9421-1e54558118f7.png)

Plus it only happens for comments on review threads :thinking:

**Comment by kidonng** [comment]
> It's possible that GitHub just changed the label and now it describes the single reaction

True, see [this review comment](https://github.com/refined-github/refined-github/pull/5113#discussion_r758597247) with multiple reactions.

> That's what I thought, but the tooltip stayed the same

Did you notice the tooltips are back to custom ones instead of `title`?

Like [what I said](https://github.com/refined-github/refined-github/pull/5150#discussion_r762427109), it's strange they only changed one page. Now it turns out GitHub is preparing a new `<primer-tooltip>` element.

**Comment by cheap-glitch** [comment]
Guess we'll just have to grab the names from the tooltip then ᕕ( ᐛ )ᕗ

**Comment by kidonng** [comment]
@cheap-glitch Are you going to work on this? (asking because I'm planning to)
If so it might be worth fix the reactions padding on releases since that bug has been there for some time.

**Comment by cheap-glitch** [comment]
@kidonng go for it :+1:

**Comment by fregante** [comment]
Glad you managed to fit this into today’s release! The bug is pretty visible

**Comment by kidonng** [comment]
`<primer-tooltip>` is rolled out to entire PRs (not just reviews), example: https://togithub.com/refined-github/refined-github/pull/5298#pullrequestreview-853544750

So does the missing padding:

![image](https://user-images.githubusercontent.com/44045911/149636532-a303c579-66f1-4994-ae00-21288761d5d6.png)

Issues are not affected yet
