### ISSUE TITLE
Sidebar is missing spacing and separators

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5280]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Example URLs

This issue

### Browser(s) used

Chrome, Safari

### Description

<img width="360" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/148670687-b096c42f-e941-4024-bfe8-199ff5e3e00f.png">

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by cheap-glitch** [comment]
Actually, this is how the sidebar looks on native GitHub:

![image](https://user-images.githubusercontent.com/46634000/148673947-1d72e5ed-e00d-4b90-a33c-9ec56a293956.png)

I guess they dropped some separators? Feels weird, could be a bug.

**Comment by kidonng** [comment]
What spacing? Between "Milestone" and "Linked pull requests"? As @cheap-glitch said it seems like a GitHub bug, and IMO is acceptable.

**Comment by fregante** [comment]
Indeed not caused by US 🎉 I 'spose I should have followed the issue template 🥲 

Let's keep this issue open to track it

**Comment by fregante** [comment]
Time for a CSS hotfix? We need to cover 2 versions

**Comment by kidonng** [comment]
@fregante Would you like to have a "github" label? I feel we have had enough issues to say it's necessary.

**Comment by fregante** [comment]
> @fregante Would you like to have a "github" label? I feel we have had enough issues to say it's necessary.

Technically this issue should not have been created: 😅 

> * The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

I wouldn't be opposed to a `github bug` label just to mark them as such, including PRs and whatever is related to it.

**Comment by cheap-glitch** [comment]
Seems like the bug was squashed! ( ᐛ )و

**Comment by kidonng** [comment]
It appears again:

<img width="50%" src="https://user-images.githubusercontent.com/44045911/152205950-f906da7d-156a-4008-8de9-c55c3f081792.png">

...but only on some conditions:

- Only on PRs, not issues
- Appears on initial load only, doesn't appear if you navigate to a PR page via PJAX

The fix above still works, I will look into making it a hotfix.

**Comment by kidonng** [comment]
This flaky bug disappeared again.
