### ISSUE TITLE
The list of CI checks in the repo header is broken on Discussion page

### ISSUE THREAD

**Issue by cheap-glitch** [refined-github/refined-github#5283]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Example URLs

https://github.com/cli/cli/discussions

### Browser(s) used

Firefox

### Description

![image](https://user-images.githubusercontent.com/46634000/148682039-57453edb-9e6f-4607-bb38-75350db4a664.png)

Note that this doesn't happen when navigating using pjax, like when switching tabs in a repo.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by kidonng** [comment]
Seems like `https://github.githubassets.com/assets/github-<hash>.css` isn't loaded on Discussions page. It can be obtained with the icon together though.
