### ISSUE TITLE
Ability to unround repo star count

### ISSUE THREAD

**Issue by lewis6991** [refined-github/refined-github#5291]
### Description

Repositories that have over 1000 stars get rounded in the star count. E.g:

![image](https://user-images.githubusercontent.com/7904185/148959362-815966db-a484-404f-9785-371b129a208b.png)

However the html contains the exact count:

![image](https://user-images.githubusercontent.com/7904185/148959656-b0e6b0d1-d7eb-4835-bded-d0de6ef5502e.png)

so could we have an option to remove this rounding so we have: `16.6k` -> `16,554`?

### Example URL

https://github.com/refined-github/refined-github

**Comment by yakov116** [comment]
Just hover over the label

**Comment by fregante** [comment]
- https://github.com/refined-github/refined-github/issues/3382
