### ISSUE TITLE
Custom footer is dimmed

### ISSUE THREAD

**Issue by Gakk** [refined-github/refined-github#5292]
### Description

Hiding of GitHub's global footer seems to have been a base feature for ages, and that was fine since it seldom was used.

GitHub [in November introduced](https://github.blog/changelog/2021-11-23-custom-footers-on-github-enterprise-cloud/) a feature to [add custom footers for enterprises](https://docs.github.com/en/enterprise-cloud@latest/admin/configuration/configuring-your-enterprise/configuring-custom-footers):

> ![image](https://user-images.githubusercontent.com/5013909/149023140-096b1e0d-20e3-4015-a03d-77a3642676fd.png)

Using this with _Refined GitHub_ enabled results in our custom added links also being dimmed (including our logo at left being hidden):

> ![image](https://user-images.githubusercontent.com/5013909/149023505-aab15e42-31af-4a1e-9c1c-5325d8fb6fe6.png)

Without _Refined GitHub_ enabled both enterprise logo and links are normal:

> ![image](https://user-images.githubusercontent.com/5013909/149024015-e869b798-979d-433b-a6a5-044a475b8cd8.png)

When inspecting the page this line of custom links is in a `div` within the `footer` element:

> ![image](https://user-images.githubusercontent.com/5013909/149025207-87a9ae5a-063c-4aeb-840f-d9d2ab92617e.png)

I suggest adding the _dim GitHub footer_ feature as an option that can be enabled and disabled by users, so enterprises using this can suggest users with Refined GitHub disable that dimming feature.

_Or_ only dim the global GitHub line in the footer, and not the enterprise line.

### Example URL

https://github.com/refined-github/refined-github

**Comment by cheap-glitch** [comment]
> Or only dim the global GitHub line in the footer, and not the enterprise line.

+1

Could you post the full HTML snippet of the footer? Thank you

**Comment by fregante** [comment]
It's possible that we can just change the `.footer:not(:hover)` selector to `.footer> :last-child:not(:hover)`. That covers the public version and perhaps the GHE too.

**Comment by Gakk** [comment]
@cheap-glitch Thanks for your interest and +1 👍 

I have captured the full HTML snippet of the footer, it can be accessed here:
https://gist.github.com/Gakk/9c8f073643b6ffcae001670a66ffd4c2

**Comment by fregante** [comment]
Weird, they have an empty `div>span` at the end… so we can either adjust that selector with something like `:nth-child(-2n)` or use ` > div:not([data-test-selector])`

**Comment by Gakk** [comment]
@cheap-glitch I was very pleased that this was fixed so quickly, and were excited when the plugin were upgraded yesterday. But to my surprise it did not fix anything, but now both "GitHub Inc." and my organization name has disappeared, and no logos are visible. The space for name and logo is there, but without any visible content.

![image](https://user-images.githubusercontent.com/5013909/150122603-fb12d176-f1e9-47ac-8302-de5142765c31.png)

This is what I expected, and not what is shown in the _After_-images in PR #5294.

I have tried using "Find feature..." in the extensions settings, but the issue is there through all of the questions presented when cycling through different features.

**Comment by cheap-glitch** [comment]
@Gakk sorry that my PR didn't solve this.

Since I don't use Enterprise, I based the fix solely on the HTML you posted. Maybe GitHub changed it in the meantime?

**Comment by fregante** [comment]
If you could provide a snippet of CSS that hides the native footer and leaves the custom footer alone that'd be great, because otherwise we're just operating in the dark 😅

**Comment by Gakk** [comment]
I am very grateful for your time and effort! 😃👍

Here are a fresh dump of the HTML with Refined GitHub versjon 22.1.18 enabled.

Unfortunately I have not been able to find the CSS that is hiding the elements. I am not a web developer, and does not have a lot of experience using Chrome DevTools.

I have created a temporary organization that you can test this in, if that is of interest? If so, I have sent you both (@fregante & @cheap-glitch) an invite to join this empty organization, but with custom footers enabled. If this is not of interest just ignore the invite, and I can try to keep searching to understand why the footer is dimmed and images hidden.

<details>
  <summary>Click to expand HTML for footer-element...</summary>

	<footer class="footer width-full container-xl p-responsive" role="contentinfo">

		<span class="sr-only" id="business-name">My Organization Name Here</span>
		<ul aria-labelledby="business-name" class="sr-only">
			<li>
			  <a class="mr-3" rel="noopener noreferrer" href="https://example.com">Confluence / Wiki</a>
			</li>
			<li>
			  <a class="mr-3" rel="noopener noreferrer" href="https://example.com">Jira</a>
			</li>
			<li>
			  <a class="mr-3" rel="noopener noreferrer" href="https://example.com">Azure DevOps</a>
			</li>
			<li>
			  <a class="mr-3" rel="noopener noreferrer" href="https://example.com">Azure Portal</a>
			</li>
			<li>
			  <a class="mr-3" rel="noopener noreferrer" href="https://example.com">SomeURL</a>
			</li>
		</ul>

		<div class="position-relative d-flex flex-items-center pt-6 pb-2 mt-6 f6 color-fg-muted border-top color-border-muted flex-column-reverse flex-lg-row flex-wrap flex-lg-nowrap">
		  <ul class="list-style-none d-flex flex-wrap d-none d-lg-block col-0 col-lg-2 flex-justify-start flex-lg-justify-between mb-2 mb-lg-0">
			<li class="mt-2 mt-lg-0 d-flex flex-items-center">

				<a title="My Organization Name Here Home page" class="footer-octicon mr-2" href="https://example.com">
				  <img itemprop="image" class="" src="https://avatars.githubusercontent.com/u/5013909?s=48&amp;v=4" width="24" height="24" alt="My Organization Name Here">
	</a>          <span>
			  My Organization Name Here
			</span>
			</li>
		  </ul>

		  <ul class="Truncate list-style-none d-flex flex-wrap col-12 col-lg-8 flex-justify-center flex-lg-justify-start e mb-2 mb-lg-0">
				<li class="Truncate-text flex-1">
				  <a class="mr-3" rel="noopener noreferrer" href="https://example.com">Confluence / Wiki</a>
				</li>
				<li class="Truncate-text flex-1">
				  <a class="mr-3" rel="noopener noreferrer" href="https://example.com">Jira</a>
				</li>
				<li class="Truncate-text flex-1">
				  <a class="mr-3" rel="noopener noreferrer" href="https://example.com">Azure DevOps</a>
				</li>
				<li class="Truncate-text flex-1">
				  <a class="mr-3" rel="noopener noreferrer" href="https://example.com">Azure Portal</a>
				</li>
				<li class="Truncate-text flex-1">
				  <a class="mr-3" rel="noopener noreferrer" href="https://example.com">SomeURL</a>
				</li>
		  </ul>

		</div>

	  <div class="position-relative d-flex flex-items-center pb-2 f6 color-fg-muted border-top color-border-muted flex-column-reverse flex-lg-row flex-wrap flex-lg-nowrap mt-2 pt-2 border-top-0">
		<ul class="list-style-none d-flex flex-wrap col-0 col-lg-2 flex-justify-start flex-lg-justify-between mb-2 mb-lg-0">
		  <li class="mt-2 mt-lg-0 d-flex flex-items-center">
			<a aria-label="Homepage" title="GitHub" class="footer-octicon mr-2" href="https://github.com">
			  <svg aria-hidden="true" height="24" viewBox="0 0 16 16" version="1.1" width="24" data-view-component="true" class="octicon octicon-mark-github">
		<path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"></path>
	</svg>
	</a>        <span>
			© 2022 GitHub, Inc.
			</span>
		  </li>
		</ul>
		<ul class="list-style-none d-flex flex-wrap col-12 col-lg-8 flex-justify-center flex-lg-justify-between mb-2 mb-lg-0">
			<li class="mr-3 mr-lg-0"><a href="https://docs.github.com/en/github/site-policy/github-terms-of-service" data-hydro-click="{&quot;event_type&quot;:&quot;analytics.event&quot;,&quot;payload&quot;:{&quot;category&quot;:&quot;Footer&quot;,&quot;action&quot;:&quot;go to terms&quot;,&quot;label&quot;:&quot;text:terms&quot;,&quot;originating_url&quot;:&quot;https://github.com/LocusSolutions/Locus.Shared.Use.Lsp2&quot;,&quot;user_id&quot;:5013909}}" data-hydro-click-hmac="776aa9dab97322d5ab7363f485b6b7cb5b4ffa43318c5df247e8a0ab888239ee" data-analytics-event="{&quot;category&quot;:&quot;Footer&quot;,&quot;action&quot;:&quot;go to terms&quot;,&quot;label&quot;:&quot;text:terms&quot;}">Terms</a></li>
			<li class="mr-3 mr-lg-0"><a href="https://docs.github.com/en/github/site-policy/github-privacy-statement" data-hydro-click="{&quot;event_type&quot;:&quot;analytics.event&quot;,&quot;payload&quot;:{&quot;category&quot;:&quot;Footer&quot;,&quot;action&quot;:&quot;go to privacy&quot;,&quot;label&quot;:&quot;text:privacy&quot;,&quot;originating_url&quot;:&quot;https://github.com/LocusSolutions/Locus.Shared.Use.Lsp2&quot;,&quot;user_id&quot;:5013909}}" data-hydro-click-hmac="0167ed56108b70c1b8b325a5719e2a5a782927dfea3d194d749002960051b77d" data-analytics-event="{&quot;category&quot;:&quot;Footer&quot;,&quot;action&quot;:&quot;go to privacy&quot;,&quot;label&quot;:&quot;text:privacy&quot;}">Privacy</a></li>
			<li class="mr-3 mr-lg-0"><a data-hydro-click="{&quot;event_type&quot;:&quot;analytics.event&quot;,&quot;payload&quot;:{&quot;category&quot;:&quot;Footer&quot;,&quot;action&quot;:&quot;go to security&quot;,&quot;label&quot;:&quot;text:security&quot;,&quot;originating_url&quot;:&quot;https://github.com/LocusSolutions/Locus.Shared.Use.Lsp2&quot;,&quot;user_id&quot;:5013909}}" data-hydro-click-hmac="33632d2ac4dabe6679c5130b0db571a8400d898993fd1f83543e38b189ad7d96" data-analytics-event="{&quot;category&quot;:&quot;Footer&quot;,&quot;action&quot;:&quot;go to security&quot;,&quot;label&quot;:&quot;text:security&quot;}" href="https://github.com/security">Security</a></li>
			<li class="mr-3 mr-lg-0"><a href="https://www.githubstatus.com/" data-hydro-click="{&quot;event_type&quot;:&quot;analytics.event&quot;,&quot;payload&quot;:{&quot;category&quot;:&quot;Footer&quot;,&quot;action&quot;:&quot;go to status&quot;,&quot;label&quot;:&quot;text:status&quot;,&quot;originating_url&quot;:&quot;https://github.com/LocusSolutions/Locus.Shared.Use.Lsp2&quot;,&quot;user_id&quot;:5013909}}" data-hydro-click-hmac="e9457e1d9f876c67ca2d119ce6a9e3e8b3707802981a75562709fb1fe23159bc" data-analytics-event="{&quot;category&quot;:&quot;Footer&quot;,&quot;action&quot;:&quot;go to status&quot;,&quot;label&quot;:&quot;text:status&quot;}">Status</a></li>
			<li class="mr-3 mr-lg-0"><a data-ga-click="Footer, go to help, text:Docs" href="https://docs.github.com">Docs</a></li>
			<li class="mr-3 mr-lg-0"><a href="https://support.github.com?tags=dotcom-footer" data-hydro-click="{&quot;event_type&quot;:&quot;analytics.event&quot;,&quot;payload&quot;:{&quot;category&quot;:&quot;Footer&quot;,&quot;action&quot;:&quot;go to contact&quot;,&quot;label&quot;:&quot;text:contact&quot;,&quot;originating_url&quot;:&quot;https://github.com/LocusSolutions/Locus.Shared.Use.Lsp2&quot;,&quot;user_id&quot;:5013909}}" data-hydro-click-hmac="cbbce744f0520e0d3530566139fb1f63bf52d4e745408cefc372c05bd79d4f73" data-analytics-event="{&quot;category&quot;:&quot;Footer&quot;,&quot;action&quot;:&quot;go to contact&quot;,&quot;label&quot;:&quot;text:contact&quot;}">Contact GitHub</a></li>
			<li class="mr-3 mr-lg-0"><a href="https://github.com/pricing" data-hydro-click="{&quot;event_type&quot;:&quot;analytics.event&quot;,&quot;payload&quot;:{&quot;category&quot;:&quot;Footer&quot;,&quot;action&quot;:&quot;go to Pricing&quot;,&quot;label&quot;:&quot;text:Pricing&quot;,&quot;originating_url&quot;:&quot;https://github.com/LocusSolutions/Locus.Shared.Use.Lsp2&quot;,&quot;user_id&quot;:5013909}}" data-hydro-click-hmac="aabed0ad2bf0f9efe97e1046e4ba32cc198d21be220a7b060725102ed5bb62ba" data-analytics-event="{&quot;category&quot;:&quot;Footer&quot;,&quot;action&quot;:&quot;go to Pricing&quot;,&quot;label&quot;:&quot;text:Pricing&quot;}">Pricing</a></li>
		  <li class="mr-3 mr-lg-0"><a href="https://docs.github.com" data-hydro-click="{&quot;event_type&quot;:&quot;analytics.event&quot;,&quot;payload&quot;:{&quot;category&quot;:&quot;Footer&quot;,&quot;action&quot;:&quot;go to api&quot;,&quot;label&quot;:&quot;text:api&quot;,&quot;originating_url&quot;:&quot;https://github.com/LocusSolutions/Locus.Shared.Use.Lsp2&quot;,&quot;user_id&quot;:5013909}}" data-hydro-click-hmac="9e3aabdbe4447349cff0c91e809e94dec11ec0016f38cbac9c5413400259cd35" data-analytics-event="{&quot;category&quot;:&quot;Footer&quot;,&quot;action&quot;:&quot;go to api&quot;,&quot;label&quot;:&quot;text:api&quot;}">API</a></li>
		  <li class="mr-3 mr-lg-0"><a href="https://services.github.com" data-hydro-click="{&quot;event_type&quot;:&quot;analytics.event&quot;,&quot;payload&quot;:{&quot;category&quot;:&quot;Footer&quot;,&quot;action&quot;:&quot;go to training&quot;,&quot;label&quot;:&quot;text:training&quot;,&quot;originating_url&quot;:&quot;https://github.com/LocusSolutions/Locus.Shared.Use.Lsp2&quot;,&quot;user_id&quot;:5013909}}" data-hydro-click-hmac="5080baa1fec48edcd498c8a708b00a6780ab0f2f865f0a0b5700da670b6b8ee1" data-analytics-event="{&quot;category&quot;:&quot;Footer&quot;,&quot;action&quot;:&quot;go to training&quot;,&quot;label&quot;:&quot;text:training&quot;}">Training</a></li>
			<li class="mr-3 mr-lg-0"><a href="https://github.blog" data-hydro-click="{&quot;event_type&quot;:&quot;analytics.event&quot;,&quot;payload&quot;:{&quot;category&quot;:&quot;Footer&quot;,&quot;action&quot;:&quot;go to blog&quot;,&quot;label&quot;:&quot;text:blog&quot;,&quot;originating_url&quot;:&quot;https://github.com/LocusSolutions/Locus.Shared.Use.Lsp2&quot;,&quot;user_id&quot;:5013909}}" data-hydro-click-hmac="2ca8f0559290ea35c8c83040954459385dda9f84c6d188f4bb490bb6be49359e" data-analytics-event="{&quot;category&quot;:&quot;Footer&quot;,&quot;action&quot;:&quot;go to blog&quot;,&quot;label&quot;:&quot;text:blog&quot;}">Blog</a></li>
			<li><a data-ga-click="Footer, go to about, text:about" href="https://github.com/about">About</a></li>
		</ul>
	  </div>
	  <div class="d-flex flex-justify-center pb-6">
		<span class="f6 color-fg-muted"></span>
	  </div>
	</footer>

</details>

**Comment by fregante** [comment]
Wow, I thought this was a GitHub Enterprise feature.

**Comment by Gakk** [comment]
> Wow, I thought this was a GitHub Enterprise feature.

Yes, Enterprise Cloud, not Enterprise Server. Sorry, I could have specified that 😳

**Comment by cheap-glitch** [comment]
@Gakk thanks for creating a test org, that helped a lot!

I've hotfixed this for now, so the bug should disappear soon (you can clear the extension's cache to fix it immediately — "Clear cache" button at the bottom of the options page).

Please don't remove the org yet, we still need it to test and merge in a proper fix. Thanks again!

**Comment by Gakk** [comment]
@cheap-glitch Wow, thanks for yet another quick fix 😃👍

Now both our logo, name and links shows without dimming!

I will not be able to keep the organization forever (you are currently using two of our licenses), but I will do my best to keep it until your next release is deployed.

It is also worth mentioning that before the initial fix of this issue, the footer also showed "© 2022 GitHub, Inc." dimmed before the footer with terms etc., and this copyright notice is still missing with the hotfix. It does not bother me, but I guess GitHub might have an issue if their copyright is completely removed and not just dimmed.

Thanks again, both, for quick responses!

**Comment by Gakk** [comment]
A last note: I also first now noticed that the normal GitHub footer is no longer dimmed when viewing GitHub content that is _not_ in an enterprise organization (eg. the bottom of this issue page) 😳

**Comment by cheap-glitch** [comment]
@Gakk thank you very much for your sponsorship, I really appreciate it!

> A last note: I also first now noticed that the normal GitHub footer is no longer dimmed

This is what I get for rushing and not testing things properly :grimacing: Should be fixed for good now.

> I will not be able to keep the organization forever (you are currently using two of our licenses), but I will do my best to keep it until your next release is deployed

No worries, I'll open up a PR tomorrow and as long as I can test it and take screenshots it's all good

> It is also worth mentioning that before the initial fix of this issue, the footer also showed "© 2022 GitHub, Inc."

It was supposed to be hidden completely, the selector had just expired. I'm sure GitHub won't mind :)

**Comment by kidonng** [comment]
> It is also worth mentioning that before the initial fix of this issue, the footer also showed "© 2022 GitHub, Inc." dimmed before the footer with terms etc., and this copyright notice is still missing with the hotfix. It does not bother me, but I guess GitHub might have an issue if their copyright is completely removed and not just dimmed.

It is not removed, only hidden, on your browser with the extension only. It's like Intel won't sue anyone who get rid of the "Intel Inside" sticker on their laptop, because we already know that.

**Comment by fregante** [comment]
@Gakk thanks for the GHE invite! You can drop our accounts now. We'll release a new version on Feb 1st
