### ISSUE TITLE
"Years Old" is duplicated

### ISSUE THREAD

**Issue by Dentrax** [refined-github/refined-github#5293]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Example URLs

https://github.com/ahmetb/cloudrun-iamviz

### Browser(s) used

Firefox 95

### Description

Duplicate `years old`

![Screen Shot 2022-01-12 at 22 16 08](https://user-images.githubusercontent.com/16493751/149206817-80278e99-cd37-49f8-8960-ea5f53f99785.png)

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by yakov116** [comment]
Can you give exact steps?

**Comment by Dentrax** [comment]
> Can you give exact steps?

Just visited the URL. 🤷‍♂️

**Comment by yakov116** [comment]
RGH Version? Cannot replicate in chrome.
Any Console errors?

**Comment by yakov116** [comment]
Did this happen more than one time?

**Comment by cheap-glitch** [comment]
Can't reproduce on Firefox.

**Comment by Dentrax** [comment]
Couldn't reproduce it. RGH: `1.0.36`

**Comment by cheap-glitch** [comment]
> RGH: `1.0.36`

I don't think that's possible, latest release is 22.1.11 :laughing:

**Comment by Dentrax** [comment]
Oh! My bad. 🙈 It's `22.1.11`

**Comment by yakov116** [comment]
Sounds like a one time issue.

Open another issue if you see this persistently.

Thanks
