### ISSUE TITLE
`infinite-scroll`: Cannot read properties of undefined (reading 'append')

### ISSUE THREAD

**Issue by BlackOfWorld** [refined-github/refined-github#5300]
### Please ensure:

- [x] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Example URLs

https://github.com/

### Browser(s) used

Google Chrome 97.0.4692.71 (64-bit)

### Description

```
TypeError: Cannot read properties of undefined (reading 'append')
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:5223:45
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:1923:97
    at runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:2924:26)
    at setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:2934:40)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:2956:35
```

Console error:
```
refined-github.js:2886 ❌ infinite-scroll 22.1.11 → TypeError: Cannot read properties of undefined (reading 'append')
    at refined-github.js:5223:45
    at refined-github.js:1923:97
    at runFeature (refined-github.js:2924:26)
    at setupPageLoad (refined-github.js:2934:40)
    at refined-github.js:2956:35
```

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by kidonng** [comment]
> It seems that the "Explore" sidebar fails to load once in a while

`!` -> `?` then

**Comment by cheap-glitch** [comment]
> > It seems that the "Explore" sidebar fails to load once in a while
> 
> `!` -> `?` then

That would just silence the error. I think it'd be better to add a fallback to the selector, e.g. `[aria-label="Explore"], aside`

**Comment by kidonng** [comment]
It probably would look weird but OK

**Comment by BlackOfWorld** [comment]
> Weird, I was only able to reproduce this a single time. It seems that the "Explore" sidebar fails to load once in a while, which causes this line to throw an error:

Personally, the "Explorer" sidebar always worked, but yesterday, it didn't and that's how I encoutered this. Even in Incognito, no extensions, still didn't show.
