### ISSUE TITLE
`Switch branches or tags` string is used instead of the main branch

### ISSUE THREAD

**Issue by altrisi** [refined-github/refined-github#5302]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Example URLs

https://github.com/refined-github/refined-github/issues (with `repo-wide-file-finder`)
https://github.com/refined-github/refined-github/tree/main/source (with `default-branch-button`)

### Browser(s) used

Firefox 95.0.2

### Description

The branch name that is being used as the main repo branch is `Switch branches or tags` (that is the `title` of the branch switcher button, not sure if related) instead of the repo's main branch. This causes issues with the two features mentioned in the example urls, but it's likely to also cause them in other features I'm not aware of (just saw it also affects whatever that makes PRs mention the branch they target if not the main one, assuming it's considering it's different because of the same issue).

I couldn't find any console errors.

<details>

<summary>Screenshots</summary>

![imagen](https://user-images.githubusercontent.com/17107132/149507034-1aaf9593-d87c-48f2-8324-952c720390b1.png)
![imagen](https://user-images.githubusercontent.com/17107132/149507061-c76f641f-d98e-4659-8562-713725a90c51.png)

</details>

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by altrisi** [comment]
It seems like it now works properly...

It had been annoying me since yesterday (after the last update IINW), I'll close the issue for now, at least until I can reproduce it again.

**Comment by kidonng** [comment]
Hi, we are aware of the issue and there is a fix in #5297.
