### ISSUE TITLE
`collapsible-content-button` doesn't work in issue forms

### ISSUE THREAD

**Issue by altrisi** [refined-github/refined-github#5303]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Example URLs

https://github.com/refined-github/refined-github/issues/new?assignees=&labels=bug&template=1_bug_report.yml

### Browser(s) used

Firefox 95.0.2

### Description

If you click the `collapsible-content-button` in an issue form, nothing will happen until you reload the page, at which point all of the collapsible containers you requested will have been created if you didn't modify the textarea.

Couldn't find any console errors.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by cheap-glitch** [comment]
> nothing will happen until you reload the page

Actually you don't need to reload the page to see the injected content, just unfocus the text field so the editor disappears. But ofc that's not the intended behavior.

I think it's a similar bug to #4678 : the feature targets the wrong `textarea`, i.e. the "real" one used by the form, where instead it should target the "preview" created along the editor when a field is focused.
