### ISSUE TITLE
Show image sizes on containers page

### ISSUE THREAD

**Issue by fenollp** [refined-github/refined-github#5317]
### Description

The Container page of Packages lists a repo's docker images. It would help to show the size of each image in a compact manner.

The image manifest is shown on the [detailed image page](https://github.com/fenollp/grpc_bench/pkgs/container/grpc_bench/13101825?tag=rust_tonic_st_bench-complex_proto) which should be enough to sum the layer sizes and obtain the final image size. Not sure if that'd be the compressed or uncompressed size but that would still be an indication.

### Screenshot

![Untitled](https://user-images.githubusercontent.com/278727/149915796-e9eea9b8-084b-4eb1-8aaf-df5382999935.png)

### Example URL

https://github.com/fenollp/grpc_bench/pkgs/container/grpc_bench/versions

**Comment by cheap-glitch** [comment]
Would this benefit a good proportion of GitHub users? It seems like a pretty niche feature to me.

But then again I know nothing about this stuff, maybe everybody uses it :man_shrugging:

**Comment by kidonng** [comment]
```graphql
{
  organization(login: "github") {
    packages(first: 2, packageType: DOCKER) {
      nodes {
        versions(first: 2) {
          nodes {
            version
            files(first: 10) {
              nodes {
                size
              }
            }
          }
        }
        name
      }
    }
  }
}

```

**Comment by kidonng** [comment]
This is determined too niche as no other people has shown interest in this. You are suggested to implement it via a userscript, the GraphQL above is a good starting point.
