### ISSUE TITLE
Enabling/disabling `rgh-feature-descriptions` is unavailable in extension option menu

### ISSUE THREAD

**Issue by HariAcidReign** [refined-github/refined-github#5318]
### What I don't like

I wanted the feed design to go back to what it was. So, I found the feature changing the feed page using the 'Find feature' option, and on searching for the same in the menu to disable it, I was unable to find it. 

Do add toggling this option in the feat menu so that users can disable this style as required.

**Comment by yakov116** [comment]
Anything RGH- only applies to this repository. We do not give an option to disable.
Question: why exactly do you want to disable it?

**Comment by HariAcidReign** [comment]
as I had already mentioned, the "find the feature" functionality in the menu informed me that the feature modifying my initial feed page of Github is " rgh-feature-descriptions", and hence I want to bring back the style of my old feed while enjoying the rest of the features of Refined GitHub.

**Comment by busches** [comment]
@HariAcidReign I think there's been a mistake. Can you share a screenshot of what you're seeing and what you want to disable? The `rgh-feature-descriptions` adds feature descriptions on specific code pages only in the RGH repo.

e.g. https://github.com/refined-github/refined-github/blob/main/source/features/action-used-by-link.tsx
![image](https://user-images.githubusercontent.com/857700/149963867-b407bf5f-b98e-41c2-a749-02e4465ece11.png)

**Comment by cheap-glitch** [comment]
You're looking for `clean-dashboard`.

> as I had already mentioned, the "find the feature" functionality in the menu informed me that the feature modifying my initial feed page of Github is " rgh-feature-descriptions"

That should not be the result, so either you made a mistake (e.g. clicked on the wrong button) or the "Find feature" is buggy.

**Comment by fregante** [comment]
heh must have been confusing 😅 what browser are you using? @cheap-glitch is right though

It works for me in Safari:

https://user-images.githubusercontent.com/1402241/149966484-ff77057a-5a39-4223-9436-f5ab38de67c6.mov

**Comment by HariAcidReign** [comment]
y'all are amazing! `clean-dashboard` fixed it! Thank you so much :) @fregante @cheap-glitch @busches @yakov116
