### ISSUE TITLE
`clean-conversation-headers` displays incorrectly

### ISSUE THREAD

**Issue by ewjoachim** [refined-github/refined-github#5321]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button can be found at the bottom of the options page.

### Example URLs

https://github.com/peopledoc/septentrion/pull/136/files/346da19f7cd57956281751f33665c52d128de588

### Extension version

22.1.18

### Browser(s) used

Firefox

### Description

Steps:
- From the notifications page, click on a notification on a PR when the PR has been updated since the notification, leading you to a "We went looking everywhere, but couldn’t find those commits."
- From there, click on the Conversation PR tab
- The conversation header appears incorrectly

I have tried with and without a token configured.

Error in the console: 
```typescript
TypeError: select_dom(...) is undefined @ update-pr-from-base-branch.tsx:18:8
  function getBranches(): {base: string; head: string} {
	  return {
>   	  base: select('.base-ref')!.textContent!.trim(),
		  head: select('.head-ref')!.textContent!.trim(),
	  };
  }
```
Note: video also shows that even reloading the page doesn't fully fix the issue, the PR author still doesn't appear (though at the time of the video, I had not configured my token yet so maybe that part was just my token being over-used)

https://user-images.githubusercontent.com/1457576/150123039-fa1cca85-9351-4b25-b0a7-fe023b1fd688.mp4

![Screenshot from 2022-01-19 12-37-03](https://user-images.githubusercontent.com/1457576/150123062-cd1aafef-c27d-43bd-926b-d28d00c7d468.png)

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by yakov116** [comment]
Its because on https://github.com/peopledoc/septentrion/pull/136/files/346da19f7cd57956281751f33665c52d128de588 GitHub does not have the classes on the span. (The force commit page)

**Comment by javier808** [comment]
Leave me. Alone stop getting in my stuff @github jwlp

**Comment by ewjoachim** [comment]
As far as I can tell, I don't see the bug anymore. Maybe it was fixed by another change. I'll close the issue and if I (or some else) see it again, let's reopen it :)

**Comment by fregante** [comment]
Thank you for reporting
