### ISSUE TITLE
`prevent-link-loss` should be enabled on commit description textfields

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5326]
### Description

And possibly many other features that works with `hasRichTextField`.

### Example URL

https://github.com/refined-github/refined-github/edit/hotfix/README.md

Testing stuff: https://github.com./refined-github/refined-github/issues/5321

**Comment by fregante** [comment]
Hmmm I don't see how that can be true. The commit loss happens during the markdown conversion. The commit description is never rendered as such… is it?

**Comment by kidonng** [comment]
> Hmmm I don't see how that can be true. The commit loss happens during the markdown conversion. The commit description is never rendered as such… is it?

Hey, do you think this issues comes from nowhere? I opened it because I experienced it.

> Can you make a commit on a random branch that shows the loss?

https://togithub.com/refined-github/refined-github/pull/5324/commits/2c97f0bac0905079f668a945b51acb0d58380e2e (that `b5f752a` is a link to the PR when submitted).

**Comment by fregante** [comment]
Tones please

**Comment by kidonng** [comment]
> Tones please

I was mildly annoyed because I thought it's an obvious fact. Sorry if it hurts your feeling. I will be careful in the future.

Anyway here's a video demonstrating it for ya:

https://user-images.githubusercontent.com/44045911/150536301-8ce6dd43-dea4-47b3-9e39-2af778c588d4.mov

**Comment by fregante** [comment]
I see the issue, but how can we fix it? If markdown isn’t rendered in commit messages, then wrapping the link won’t fix it.

**Comment by kidonng** [comment]
[Assuming GitHub's parser isn't that RFC-compliant*.](https://github.com/kidonng/refined-github/commit/f4b4b03c6ca00c51a249cb26afa840fc37c165fa)

\* _The only problem is that most stuff aren't either. And hope people don't search for `github.com/` in commit messages 🤷_

**Comment by fregante** [comment]
Better to double-slash it:

```
https://github.com//refined-github/refined-github/pull/5327/commits/2e2dc93f2b6f626a7b02da243d66c9f7586ef0d8
```

Alternatives? Live example: https://github.com/refined-github/refined-github/commit/3474d4b2eded5ce034a93f768cd1ba593eed10dd

**Comment by kidonng** [comment]
> Better to double-slash it

Awesome, though it would still trip some third-party parsers we probably don't care.

We may want to do this to restore PJAX and stuff though:

```js
if (location.pathname.startsWith('//') {
	history.replaceState(null, document.title, location.pathname.replace('//', '/'))
}
```

**Comment by fregante** [comment]
I don't feel comfortable essentially breaking permanently-saved links just to fix a temporary GitHub bug, even if this "temporary bug" is several years old
