### ISSUE TITLE
user hovercard: show 'Person watches this repo'

### ISSUE THREAD

**Issue by jtagcat** [refined-github/refined-github#5331]
### Description

Sometimes it's nice to know whether a person is watching the repo. Manually navigating to /watchers (there is no button to do this? same with stargazers and forks).

I half-expected something like ':eye: watches this repo' to be on the hovercard.

### Example URL

https://github.com/refined-github/refined-github

**Comment by yakov116** [comment]
> Sometimes it's nice to know whether a person is watching the repo.

Because?

**Comment by jtagcat** [comment]
Whether to ping them or not

**Comment by fregante** [comment]
I think that if you need to ping someone you should just ping them. GitHub also specifically handles mentions and regular subscriptions differently. Even when I follow a repo, I sometimes ignore notifications that aren't review requests and mentions.
