### ISSUE TITLE
`git-checkout-pr`: removed fork results in `git remote add This repository has been deleted`

### ISSUE THREAD

**Issue by paper42** [refined-github/refined-github#5332]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button can be found at the bottom of the options page.

### Example URLs

https://github.com/void-linux/void-packages/pull/35150

### Extension version

22.1.18

### Browser(s) used

Firefox

### Description

GitHub doesn't close a PR when the fork was removed, then it's not possible to checkout the PR with git, but `Checkout with git`
`Code -> Checkout with Git` shows:
```
Run in your project repository, pick either one

HTTPS

git remote add This repository has been deleted https://github.com/This repository has been deleted.git
git fetch This repository has been deleted 
git switch --track This repository has been deleted/

SSH

git remote add This repository has been deleted git@github.com:This repository has been deleted.git
git fetch This repository has been deleted 
git switch --track This repository has been deleted/
```

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by fregante** [comment]
We have two options:

- avoid adding the content when the fork was deleted
- change the commands to fetch the commit from the current repo (I think that's how it works)

**Comment by kidonng** [comment]
I don't see `git-checkout-pr` on the example PR at all. Is this related to the Codespaces tab?

**Comment by yakov116** [comment]
Because the PR was closed. He made the issue before he closed it.

**Comment by kidonng** [comment]
Well, it's back to #4701

**Comment by fregante** [comment]
Closing in favor of #4701.
