### ISSUE TITLE
Folder download button no longer available on non-default branches

### ISSUE THREAD

**Issue by stamminator** [refined-github/refined-github#5335]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button can be found at the bottom of the options page.

### Example URLs

https://github.com/dotnet/runtime/tree/09ff1acdad2e7789908b5db9bb89896144c13042/src/libraries/Microsoft.VisualBasic.Core

### Extension version

22.1.18

### Browser(s) used

Chrome 97

### Description

The Download button for a directory is no longer available. There no longer appears to be any way to download an entire directory.

![image](https://user-images.githubusercontent.com/10633170/150903143-28f57c3d-6c04-445b-9706-147533bd2b7f.png)

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by cheap-glitch** [comment]
It's here if you go back to the default branch:
![image](https://user-images.githubusercontent.com/46634000/150929660-c134c8c3-f106-4c62-90de-f738204b4f03.png)
