### ISSUE TITLE
`wait-for-build` does not result in a usable checkbox

### ISSUE THREAD

**Issue by JasonGross** [refined-github/refined-github#5336]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button can be found at the bottom of the options page.

### Example URLs

https://github.com/mit-plv/fiat-crypto/pull/1110

### Extension version

22.1.18

### Browser(s) used

Chrome

### Description

There is no checkbox despite the console showing that `wait-for-build` is loaded:
![image](https://user-images.githubusercontent.com/396076/151265302-65918bb9-ae5b-4d53-b34a-c0df3e0596d3.png)

Console errors and demonstration that this PR has running checks:

![image](https://user-images.githubusercontent.com/396076/151265235-66972264-4fbc-4d28-babc-83db38785007.png)

Not sure if it's relevant, but there's no check icon next to the commit, only for the PR:
![image](https://user-images.githubusercontent.com/396076/151265643-7e0806ef-01d0-4156-983a-6e5449ff0462.png)

<details><summary>Complete console log</summary>

refined-github.js:2967 ↩️ Skipping clean-pinned-issues
refined-github.js:2967 ↩️ Skipping hide-navigation-hover-highlight
refined-github.js:2967 ↩️ Skipping close-out-of-view-modals
refined-github.js:2967 ↩️ Skipping hide-own-stars
refined-github.js:2967 ↩️ Skipping hide-inactive-deployments
refined-github.js:2967 ↩️ Skipping hide-issue-list-autocomplete
refined-github.js:2967 ↩️ Skipping bypass-checks
refined-github.js:2967 ↩️ Skipping clean-conversation-sidebar
refined-github.js:2967 ↩️ Skipping clean-conversation-filters
refined-github.js:2967 ↩️ Skipping clean-rich-text-editor
refined-github.js:2967 ↩️ Skipping dim-bots
refined-github.js:2967 ↩️ Skipping clear-pr-merge-commit-message
refined-github.js:2967 ↩️ Skipping clean-repo-filelist-actions
refined-github.js:2967 ↩️ Skipping clean-conversation-headers
refined-github.js:2967 ↩️ Skipping clean-repo-sidebar
refined-github.js:2967 ↩️ Skipping hide-repo-badges
refined-github.js:2931 ✅ minimize-upload-bar
refined-github.js:2931 ✅ hide-diff-signs
refined-github.js:2931 ✅ comment-fields-keyboard-shortcuts
refined-github.js:2931 ✅ one-key-formatting
refined-github.js:2931 ✅ tab-to-indent
refined-github.js:2931 ✅ selection-in-new-tab
refined-github.js:2931 ✅ profile-hotkey
refined-github.js:2931 ✅ improve-shortcut-help
refined-github.js:2931 ✅ esc-to-deselect-line
refined-github.js:2931 ✅ file-finder-buffer
refined-github.js:2931 ✅ esc-to-cancel
refined-github.js:2931 ✅ quick-review-comment-deletion
refined-github.js:2931 ✅ quick-review
refined-github.js:2931 ✅ conversation-activity-filter
refined-github.js:2931 ✅ clean-repo-tabs
refined-github.js:2931 ✅ quick-comment-hiding
refined-github.js:2931 ✅ quick-comment-edit
refined-github.js:2931 ✅ shorten-links
refined-github.js:2931 ✅ show-whitespace
2refined-github.js:2931 ✅ linkify-code
refined-github.js:2931 ✅ linkify-branch-references
refined-github.js:2931 ✅ sort-conversations-by-update-time
refined-github.js:2931 ✅ star-repo-hotkey
refined-github.js:2931 ✅ sync-pr-commit-title
refined-github.js:2931 ✅ open-ci-details-in-new-tab
refined-github.js:2931 ✅ wait-for-build
refined-github.js:2931 ✅ pull-request-hotkey
refined-github.js:2931 ✅ embed-gist-inline
refined-github.js:2931 ✅ comments-time-machine-links
refined-github.js:2931 ✅ parse-backticks
refined-github.js:2931 ✅ reactions-avatars
refined-github.js:2931 ✅ set-default-repositories-type-to-sources
refined-github.js:2931 ✅ warning-for-disallow-edits
refined-github.js:2931 ✅ preview-hidden-comments
2refined-github.js:2931 ✅ fit-textareas
refined-github.js:2931 ✅ collapsible-content-button
refined-github.js:2931 ✅ sticky-sidebar
refined-github.js:2931 ✅ toggle-everything-with-alt
refined-github.js:2931 ✅ suggest-commit-title-limit
refined-github.js:2931 ✅ pr-branch-auto-delete
refined-github.js:2931 ✅ reload-failed-proxied-images
refined-github.js:2931 ✅ linkify-user-location
refined-github.js:2931 ✅ user-local-time
refined-github.js:2931 ✅ quick-mention
refined-github.js:2931 ✅ expand-all-hidden-comments
refined-github.js:2931 ✅ prevent-link-loss
refined-github.js:2931 ✅ keyboard-navigation
refined-github.js:2931 ✅ linkify-user-edit-history-popup
refined-github.js:2931 ✅ stop-pjax-loading-with-esc
refined-github.js:2931 ✅ table-input
refined-github.js:2931 ✅ convert-pr-to-draft-improvements
refined-github.js:2931 ✅ git-checkout-pr
refined-github.js:2931 ✅ unfinished-comments
refined-github.js:2931 ✅ jump-to-change-requested-comment
refined-github.js:2931 ✅ wait-for-attachments
refined-github.js:2931 ✅ avoid-accidental-submissions
refined-github.js:2931 ✅ update-pr-from-base-branch
refined-github.js:2931 ✅ quick-label-removal
refined-github.js:2931 ✅ repo-wide-file-finder
refined-github.js:2931 ✅ more-dropdown-links
refined-github.js:2931 ✅ releases-tab
refined-github.js:2931 ✅ clean-repo-tabs
1110:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'takeRecords')
    at Function.e.closeListeners (chrome-extension://clmkdohmabikagpnhjmgacbclihgmdje/content-script.js:1:5858)
    at chrome-extension://clmkdohmabikagpnhjmgacbclihgmdje/content-script.js:1:3858
refined-github.js:2931 ✅ ci-link
refined-github.js:2931 ✅ bugs-tab
DevTools failed to load source map: Could not load content for chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
3refined-github.js:2931 ✅ suggest-commit-title-limit
</details>

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by fregante** [comment]
Yeah we depend on that check icon to detect whether it's running. Without it we'd have to poll GitHub every 10 seconds in every PR you open, I don’t think that'd be acceptable. So while it's a bug/limitation, I don’t think we have any practical solutions other than refreshing the page and trying again.

**Comment by cheap-glitch** [comment]
> So while it's a bug/limitation, I don’t think we have any practical solutions other than refreshing the page and trying again.

We could try again to use the API to get the commit's status, instead of depending on an unreliable DOM. That said, I don't know if it's worth working on this, since it might be made redundant by [GitHub's merge queue](https://github.blog/changelog/2021-10-27-pull-request-merge-queue-limited-beta).

**Comment by kidonng** [comment]
> That said, I don't know if it's worth working on this, since it might be made redundant by [GitHub's merge queue](https://github.blog/changelog/2021-10-27-pull-request-merge-queue-limited-beta).

The use case looks different (single PR v.s. multiple PRs).

**Comment by fregante** [comment]
> The use case looks different (single PR v.s. multiple PRs).

Kind of, but the end result is just that PRs are not merged (at least) until CI is green, which is what `wait-for-build` is about. Unfortunately GitHub decided to make it an optional feature instead of enabling it on every repo, so I think we'll still have to keep the feature (like we're keeping `pr-branch-auto-delete` 😕)



> We could try again to use the API to get the commit's status

In addition to the current DOM-based check maybe. Or maybe we can find a different logic to use mainly the API but only if the DOM is missing or "in progress". Anything to make the feature more reliable: https://github.com/refined-github/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+%22wait-for-build+%22

For example:

- when the user opens the merge box:
	1. check whether CI is expected:
		- repo has an action tab?
		- any commit has the CI icon
	2. does **the last commit** have a green icon?
		- if yellow or completely missing, add `wait-for-build` checkbox
	3. When user clicks "Merge", start polling server every 5s/10s, maybe with `p-retry`?
	4. Merge PR as soon as we get a "green CI" response

Advantages of this option:

- we don't rely on GitHub to update the DOM, which isn't reliable at all
- we save some HTTP calls because we don't start until the user has decided to merge
- if the PR is already green (but GitHub hasn't update the dom), this will only make one request and then merge almost immediately

**Comment by JasonGross** [comment]
> check whether CI is expected:

Could you intercept the down-click on the merge button before GH changes the page, check whether or not there's a checks box?  Or look at the "checks" tab above the PR and/or look at the number next to it?  Or even use the API for this and see if any checks come up as "in progress" or "queued" for the the PR?


Question that is not clear from the documentation: do I need to stay on the merge page for the merge to happen once CI is green?  (It seems like yes?)

**Comment by cheap-glitch** [comment]
> do I need to stay on the merge page for the merge to happen once CI is green?

You need to keep the tab with the PR conversation open, but it doesn't have to be focused, you can just keep in the background.

Maybe the little message that appears next to the checkbox could be more explicit, e.g.:
“This only works if you keep this tab open _in the background_ while waiting.”

**Comment by fregante** [comment]
> My primary use case is CI that can take a couple hours to complete.

I think you should enable GitHub's auto merge at this point because in two hours a lot can happen 😅

**Comment by JasonGross** [comment]
> > My primary use case is CI that can take a couple hours to complete.
> 
> I think you should enable GitHub's auto merge at this point because in two hours a lot can happen 😅

GitHub's automerge requires that I explicitly list out which checks need to be successful.  That's a bit more feasible now that we only have 10 checks (we used to have around 20), but the list of checks changes every so often and I'm concerned I'll forget to update the settings.  Also, it requires protecting the branch, which I'd sort-of like to avoid doing.
