### ISSUE TITLE
Fix native "sticky-scroll-into-view" when notification bar is shown

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5338]
### Description

`sticky-scroll-into-view` is a file from GitHub that does the following thing:

When you click the time (hash) of a comment, the comment will first scroll to the top (browser's default behavior), then `sticky-scroll-into-view` will scroll it down a bit to make sure it is not covered by the header.

This works well except for:

- ~~The initial load, since GitHub's code isn't ready at this time (**but ours is**)~~ Doesn't seem to be relevant anymore
- It only considers the sticky header. If you have the notification header around, the comment would still be covered.

The first scenario is particularly confusing when a link is linked to one (or two) particular line(s), as you may not even realize it is raising awareness of specific lines.

Regarding implementation: we can't (and shouldn't) use GitHub's code, mentions of `sticky-scroll-into-view` is just for reference.

### Example URL

https://github.com//refined-github/refined-github/pull/5238/files#diff-cb1dafea7a9c68c5c2ebb2d56f749b3506c13f7d26feeaf56c86521b25c60358R16

**Comment by fregante** [comment]
> ### Screenshot
> _No response_

Can you post a video of this issue? Your url works well whether I open it in this tab or in a new tab:

<img width="1248" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/151537686-203524ba-0d64-423b-9212-2e09d4c74c34.png">

**Comment by fregante** [comment]
Indeed this is quite annoying. Let's see if https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-top is useful here. We might be able to fix it with 2 lines of CSS. I definitely don't want to mess with JS because GitHub has their own (evidently-faulty) logic to do exactly this.

**Comment by fregante** [comment]
I think this is tricky for us to fix without causing further issues/conflicts with GH’s own behavior. 

Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it.
