### ISSUE TITLE
Extend `patch-diff-links` to PRs

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5340]
### Description

This was previously brought up in #1907 but I would like it to be reconsidered:

- [`hide-tips`](https://github.com/refined-github/refined-github/blob/8ed65a601abd4d21e729c5810481f97995d354c6/source/features/hide-tips.css) hides the relevant tip and the info is simply lost for power users.

  <img width="489" alt="Screen Shot 2022-01-20 at 19 50 38" src="https://user-images.githubusercontent.com/44045911/151447089-9e9d4883-8d25-4a92-b888-da7dd3688bf1.png">

- We already have this feature, extending it is trivial.
- People are actually using diff/patch links. Besides the aforementioned issue, https://github.com//dylanaraps/sowm/pull/57 is also a good inspiration.

Implementation-wise, where should we put it then? My two cents:

- Header: nope since we made `clean-conversation-headers` to hide stuff
- "Files changed": nope since `one-click-diff-options` is already adding stuff
- "Commits": a good but _relatively_ unnoticeable place

### Example URL

https://github.com//refined-github/refined-github/pull/5339

**Comment by fregante** [comment]
> where should we put it then?



<img width="106" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/151537168-55924607-13e5-440b-af45-4fa6198eb9c6.png">

**Comment by fregante** [comment]
Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it.
