### ISSUE TITLE
Configurable Refined-Github start page

### ISSUE THREAD

**Issue by casperklein** [refined-github/refined-github#5342]
### Description

Clicking the refined addon button opens `https://github.com/`. It would be nice, if that could be configurable to e.g. `https://github.com/notifications`.

### Example URL

https://github.com/notifications

**Comment by fregante** [comment]
Looks like an easy change, even though I'm not really a fan of adding a field in the options page.

**Comment by casperklein** [comment]
Or maybe a dropdown list with pre-configured github destinations?

- Notifications
- Issues
- Pull requests

**Comment by cheap-glitch** [comment]
> Or maybe a dropdown list with pre-configured github destinations?

If we add a field to the options page, we might as well add an input because it's the most flexible.

**Comment by kidonng** [comment]
> even though I'm not really a fan of adding a field in the options page.

The link was added back in https://github.com/refined-github/refined-github/pull/1777/files#diff-27ac5b833f3da1b2a72a5499a11bfe535f20d6744b8f4ad0f607054afa805b16.

Does anyone actually use it? Why not just use bookmarks? With browser predictions you don't even need bookmarks most of the time.

**Comment by fregante** [comment]
Consider it advertising: people are willing to keep the Refined GitHub button on the screen because it now serves a purpose. We benefit because people won't just forget they have it installed.

**Comment by casperklein** [comment]
@cheap-glitch Thank you, for implementing this! 🎉

**Comment by kidonng** [comment]
This is now my favorite Refined GitHub feature:

<img width="311" alt="image" src="https://user-images.githubusercontent.com/44045911/179343383-c52b6c55-92fc-481e-8e7d-ed68e9f14728.png">

**Comment by fregante** [comment]
![6mxxnd](https://user-images.githubusercontent.com/1402241/179343502-7960d696-8dd3-45aa-9308-a9d8286888f9.jpg)
