### ISSUE TITLE
Not able to add custom CSS

### ISSUE THREAD

**Issue by SakethKanchi** [refined-github/refined-github#5354]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button can be found at the bottom of the options page.

### Example URLs

https://raw.githubusercontent.com/catppuccin/github/main/catppuccin.css

### Extension version

22.1.18

### Browser(s) used

Brave

### Description

I've been using the Catppuccin CSS for a while, so I thought to change it out to another theme, but after changing it out I can't revert back to the previous one. Even after i reinstall the extension, the custom CSS is not being added into it. Here is the CSS I'm trying to add. 

https://raw.githubusercontent.com/catppuccin/github/main/catppuccin.css

Video:

https://user-images.githubusercontent.com/70198692/151800857-84c0cd6d-ff03-4591-98e7-4e7dc765a0ae.mp4

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by yakov116** [comment]
Can you try to leave the box before clicking the X?

**Comment by SakethKanchi** [comment]
> Can you try to leave the box before clicking the X?

Is this what you're talking about?
https://user-images.githubusercontent.com/70198692/151805733-eaf4c9d2-c555-4f24-94ac-935a54158641.mp4

**Comment by yakov116** [comment]
Did that help? If not can you try to click on another box within the popup?

**Comment by SakethKanchi** [comment]
> Did that help? If not can you try to click on another box within the popup?

I've tried both and as soon as i close the dialogue box. The Custom CSS box becomes empty.

**Comment by SakethKanchi** [comment]
It's the CSS problem. I think it was changed or updated. I found the old CSS on another browser and it works just fine.

**Comment by SakethKanchi** [comment]
> What CSS you input shouldn't matter. It would still be helpful if you can provide the problematic CSS so we can prevent situations like this.
This was the CSS i was trying to use:
https://raw.githubusercontent.com/catppuccin/github/main/catppuccin.css

**Comment by israelss** [comment]
Hi @SakethKanchi! I had the same problem, but removing the comments fixed it.

**Comment by fregante** [comment]
It works for me (Safari) but I suspect this is a space issue (e.g. you have too much cached content). 

However since our style injection is delayed I'd advise using Stylus instead for this kind of overarching style changes.
