### ISSUE TITLE
Ensure every feature has a compatible screenshot in the readme

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5361]
The first commit in https://github.com/refined-github/refined-github/pull/5360 passes CI even though some links in the readme are not compatible with the image detection function. We should use the same function in the verifier.

Follows:

- https://github.com/refined-github/refined-github/issues/4698
- https://github.com/refined-github/refined-github/pull/5360

cc @gamemaker1  if you're interested

**Comment by gamemaker1** [comment]
Sure, I'll try fixing this issue 👍
