### ISSUE TITLE
Working with command palette

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5366]
### Description

It has been some time since GitHub announced [Command palette](https://github.blog/changelog/2021-10-27-command-palette-beta/). While it is as standalone as it can get, maybe some features should work with it:

- `sort-conversations-by-update-time` doesn't apply to links within the command palette. I wonder if it's worth doing so though.
- `file-finder-buffer` is not going anywhere (since it's branch-aware), but `repo-wide-file-finder` may seem redundant now (though I still tend to press `t` these days).
- Just for record: https://github.com/refined-github/refined-github/issues/3802#issuecomment-966471452

More thoughts welcome.

### Example URL

N/A

**Comment by fregante** [comment]
> * [`sort-conversations-by-update-time`](https://github.com/refined-github/refined-github/blob/main/source/features/sort-conversations-by-update-time.tsx?rgh-link-date=2022-02-02T21%3A30%3A20Z) doesn't apply to links within the command palette. I wonder if it's worth doing so though.

Maybe, but probably via `delegate` since it's keyboard-based (so no need to support "Right click -> Open in new tab")



> * [`file-finder-buffer`](https://github.com/refined-github/refined-github/blob/main/source/features/file-finder-buffer.tsx?rgh-link-date=2022-02-02T21%3A30%3A20Z) is not going anywhere (since it's branch-aware), but [`repo-wide-file-finder`](https://github.com/refined-github/refined-github/blob/main/source/features/repo-wide-file-finder.tsx?rgh-link-date=2022-02-02T21%3A30%3A20Z) may seem redundant now (though I still tend to press `t` these days).

Let's keep it at least until it breaks. It's a micro feature that shouldn't give us trouble either way (I also use it more than the palette at this point)

> * Just for record: [Toggle for Github Theme #3802 (comment)](https://github.com/refined-github/refined-github/issues/3802#issuecomment-966471452)

?

**Comment by cheap-glitch** [comment]
> > * Just for record: [Toggle for Github Theme #3802 (comment)](https://github.com/refined-github/refined-github/issues/3802#issuecomment-966471452)
> 
> ?

It's possible to run "commands" with the `>` prefix, like changing the current theme.

**Comment by kidonng** [comment]
- [ ] Links in command palette is not PJAX enabled. We can enable that if you are e.g. in the same repository, just like regular GitHub navigation.

**Comment by fregante** [comment]
For operations on such links, let's use delegate and listen to keydown/mousedown to change links on the fly, not MutationObserver

**Comment by fregante** [comment]
Now that this was discussed, I'm closing it.

If there are still any bugs related to the palette, please open separate issues.

I opened this for a feature request followup:

- https://github.com/refined-github/refined-github/issues/6142
