### ISSUE TITLE
`rgh-linkify-features` should work on PR commits, but not on repo tree

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5367]
### Description

- Linkifying it on PR commits with be useful for lint PRs and PRs like https://github.com//refined-github/refined-github/pull/5355
- It's not very reliable nor helpful on repo tree (I changed my mind)

### Example URL

https://github.com/refined-github/refined-github/tree/main/source

**Comment by cheap-glitch** [comment]
@kidonng Probably unrelated, but the features aren't linkified for me in the body of the PR you linked to:

![image](https://user-images.githubusercontent.com/46634000/152309915-7d33978a-1235-4588-b325-d78fb275e44e.png)

But they are everywhere else, e.g. https://togithub.com/refined-github/refined-github/pull/4207. Did you do something special with the markup?

**Comment by fregante** [comment]
> Did you do something special with the markup?

It's the URL, look for the double slash
