### ISSUE TITLE
Autolink to issues/PRs when text matches "#1234" pattern

### ISSUE THREAD

**Issue by connorjclark** [refined-github/refined-github#5368]
### Description

Would be very useful for changelog files that aren't formatted to be links to PRs/issues

### Example URL

https://github.com/getsentry/sentry-javascript/blob/caba96ef557464283b983466e5e490f3545d8c41/CHANGELOG.md

**Comment by fregante** [comment]
I'm surprised it isn't and I'm hesitant to do it if GitHub decided against it. For us maybe it's not worth scanning every single markdown file for this when only a tiny minority has such links. I'd expect the release notes generator to take care of it since "`#22`" is meaningless on its own (especially when opening the file outside GitHub)

**Comment by connorjclark** [comment]
Do you think the value/cost might make sense if limited to just files named CHANGELOG/CHANGELOG.md?

**Comment by cheap-glitch** [comment]
> Do you think the value/cost might make sense if limited to just files named CHANGES/CHANGELOG/CHANGELOG.md?

That might work, but then someone will inevitably request that we support `CHANGES.rst`, `NEWS.txt` and so on…

Just look at the regex we have in `link-to-changelog-file` to match all the variants existing in the wild :smiley: 

https://github.com/refined-github/refined-github/blob/b0cc4dedfebf0c76019f9503f9bf23943122b017/source/features/link-to-changelog-file.tsx#L20

**Comment by kidonng** [comment]
What prevents you from using actually links? You don't even need to add them by hind, there should be available tools for this (or use regex).

**Comment by kidonng** [comment]
How about this: for changelogs, we add a link next to each heading (visible on hover, like the existing anchor link). When clicked, it will try to parse a version number from the heading and jump to the corresponding tag:

```jsx
// Example:
// Refined GitHub 22.2.1 - 2022 Lunar New Year Release
// ⬇️
// https://github.com/refined-github/refined-github/releases/tag/22.2.1

<a href={`https://github.com/refined-github/refined-github/releases/tag/${heading.match(/[\d.]+/)[0]}`}>
```

**Comment by connorjclark** [comment]
> What prevents you from using actual links? You don't even need to add them by hand, there should be available tools for this (or use regex).

Well, nothing... but the purpose is to improve CHANGELOGS of other projects, not the ones I'm writing.

> How about this: for changelogs*, we add a link next to each heading (visible on hover, like the existing anchor link). When clicked, it will try to parse a version number from the heading and jump to the corresponding tag:

This seems like quite a different and more complex feature, and not one I'd be interested in myself.

**Comment by kidonng** [comment]
> This seems like quite a different and more complex feature, and not one I'd be interested in myself.

The logic is simple: We don't need to parse the text, the release page also has it, but parsed by GitHub. We just need to add a link to there.

It can be archived in about 10 lines of vanilla JS:

```js
document.querySelectorAll('#readme h2 a').forEach(({ nextSibling: e }) => {
    const version = e.textContent.match(/^[\d.]+$/)
    if (!version) return

    const a = document.createElement('a')
    a.href = `${location.pathname.split('/').slice(0, 3).join('/')}/releases/tag/${version[0]}#repo-content-pjax-container`
    a.dataset.pjax = ''

    e.before(a)
    a.append(e)
})
```

Result:

https://user-images.githubusercontent.com/44045911/152431076-d0f2cc22-0064-4ace-a49a-22a8c965e57e.mov

**Comment by fregante** [comment]
> Do you think the value/cost might make sense if limited to just files named CHANGES/CHANGELOG/CHANGELOG.md?

PR welcome to limit this feature to changelogs.



> The logic is simple: We don't need to parse the text, the release page also has it, but parsed by GitHub. We just need to add a link to there.

That's different than what's being asked: linkifying the conversation links, not the tags. However it would be useful as part of the same feature: `linkify-changelogs`

**Comment by fregante** [comment]
Those files are Markdown files and can/should just be generated with the correct link inline instead. If they're generating .txt files, then the same applies, except the link would be shown in full (and is probably already natively linkified)

We should not endorse practices that are detrimental to non-RG users (I know we have a feature that does exactly this, but it's a super-old feature)
