### ISSUE TITLE
Add link to upstream repo in `quick-repo-deletion`

### ISSUE THREAD

**Issue by FloEdelmann** [refined-github/refined-github#5369]
After deleting a repo with `quick-repo-deletion`, only a header bar remains:
![grafik](https://user-images.githubusercontent.com/202916/152321091-675f1c3f-330c-4946-a590-8b962d7a5652.png)

If the deleted repo was a fork, I often want to go to the upstream repo afterwards. So I suggest to add a link to that in the header bar:
![grafik](https://user-images.githubusercontent.com/202916/152320916-f49564ea-0796-4b95-9ea8-e09fae5dbbc6.png)

### Example URL

https://github.com/FloEdelmann/streetcomplete-mapstyle (doesn't really make sense, since it is deleted now), forked from https://github.com/streetcomplete/streetcomplete-mapstyle

**Comment by kidonng** [comment]
Leaving a small note: both the deleted repository name and upstream name would look better in bold.
