### ISSUE TITLE
Interoperability with other extensions

### ISSUE THREAD

**Issue by mainrs** [refined-github/refined-github#5371]
Hello!

I need to write an extension that adds a new button to the top right of a repository, e.g., next to `sponser`. I was curious if there are generally certain things one needs to keep in mind when writing extensions that might clash with RG. Not only about this example, but maybe others might want to add certain stuff as well.

Cheers!

**Comment by fregante** [comment]
We have no general advice on how not to create conflicts because we touch hundreds of points. If you encounter issues and can’t solve them autonomously you can comment here and maybe someone can help, but conflicts are rare unless we’re touching the same exact element.

**Comment by kidonng** [comment]
We don't add a button there (currently, and unlikely in the foreseeable future), but I do remember a few other extensions do, like Sourcegraph.

Generally, if you only add and hide stuff (not removing them from the DOM), scope the style properly, you should be fine.
