### ISSUE TITLE
Maybe drop `update-pr-from-base-branch`

### ISSUE THREAD

**Issue by yakov116** [refined-github/refined-github#5372]
### Description

- https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/#always-have-the-option-to-update
- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-suggestions-to-update-pull-request-branches

### Example URL

https://github.com/refined-github/refined-github/pull/5362

**Comment by fregante** [comment]
Like for other features, they are repo settings but we offer a user setting, on every repo. They’re not equivalent unfortunately.
