### ISSUE TITLE
Make pin repo button redirect to the repo you pinned

### ISSUE THREAD

**Issue by Milo123459** [refined-github/refined-github#5374]
### Description

I was using the pin button today to pin my repo Milo123459/website. It would be nice that once it was pinned it redirected me back to Milo123459/website as opposed to my Github profile.

### Example URL

https://github.com/Milo123459/website

**Comment by fregante** [comment]
I think this makes sense but pinning is a rare operation, I don’t think we should spend time on this

**Comment by Milo123459** [comment]
Pardon me if I'm wrong but can't we just share some state, when done pinning just redirect to original page? I can try PR.

I could also rework the button to use the api as opposed to manually going to the page

**Comment by fregante** [comment]
> can't we just

No operation is bug-free and maintenance-free. I don’t think it makes sense to "fix" an operation that happens at most 4 times a year to save **one click** to go back.

[![automation_2x](https://user-images.githubusercontent.com/1402241/152635970-e04b9170-f8bb-46e7-bb6a-9ac2450982f7.png)](https://xkcd.com/1319/)
