### ISSUE TITLE
Provide a link to the repo from the notification page filtered for that repo

### ISSUE THREAD

**Issue by FichteFoll** [refined-github/refined-github#5377]
### Description

When viewing notifications for a specific repo, there appears to be no way to quickly navigate to the main entry point of that repo. 

All of the entries on the page link to specific issues and result in the respective issue being marked as read once clicked. It may also be that your current filter shows no issues at all for a repo.
The entry on the far left is just for the filter of the notifications page.

I could have used a link to go to the repo root quite a few times already, though I don't have a concrete proposal for where I would expect such a link to show up.

### Example URL

https://github.com/notifications?query=repo%3Arefined-github%2Frefined-github

**Comment by cheap-glitch** [comment]
> though I don't have a concrete proposal for where I would expect such a link to show up

How about in the space between the searchbar and the select tools:

![image](https://user-images.githubusercontent.com/46634000/152678467-dca492df-ad8f-42ad-8970-1c341cc9b949.png)

Or maybe just above the "Select all"?

**Comment by fregante** [comment]
If there's a space that doesn't push the content down it'd be better.

**Comment by yakov116** [comment]
Why don't we split the link `refined-github/refined-github` (SPLIT) `issue number`.

**Comment by kidonng** [comment]
> Maybe it can just be a "link external" icon next to the filter 

We can change the active filter link to point to the actual repo. That is, if you select a filter the second time, it leads you to the repo homepage.

**Comment by cheap-glitch** [comment]
> Maybe it can just be a "link external" icon next to the filter

+1

> Why don't we split the link `refined-github/refined-github` (SPLIT) `issue number`, in each notification.

Not a bad idea. That would mirror the way it works on the global issues/PR list (`[repo name] [issue name]`)

> We can change the active filter link to point to the actual repo. That is, if you select a filter the second time, it leads you to the repo homepage.

Imo this would be confusing and not very discoverable.

**Comment by kidonng** [comment]
> > We can change the active filter link to point to the actual repo. That is, if you select a filter the second time, it leads you to the repo homepage.
> 
> Imo this would be confusing and not very discoverable.

I didn't say there can't be any indicator like the external link icon aforementioned 😬

**Comment by fregante** [comment]
> Why don't we split the link `refined-github/refined-github` (SPLIT) `issue number`, in each notification.

Unlike regular issue lists, the whole notification line is clickable here. I don’t think it's worth changing the behavior here.

**Comment by yakov116** [comment]
FYI this issue is ONLY when group by date is used. If grouped by repository there is a link there.

![image](https://user-images.githubusercontent.com/16872793/152831470-af352206-3d4b-48cb-a279-73e1269f27e0.png)

**Comment by fregante** [comment]
Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it.
