### ISSUE TITLE
Add shortcuts into `conversation-activity-filter` options

### ISSUE THREAD

**Issue by 14113** [refined-github/refined-github#5379]
### Description

It's related to the https://github.com/refined-github/refined-github/pull/4029

It's a great feature! Thanks for that. 

Is it possible to keep this setting on for all issues and PRs after page reload? Right now, I have to click on the buttons every time I visit any issue.

### Screenshot

PR with `conversation-activity-filter` turned on:
<img width="954" alt="Screenshot 2022-02-07 at 11 11 14" src="https://user-images.githubusercontent.com/472927/152768038-e179b8a4-a92d-465d-bc51-4a4fd7794aa8.png">

The same PR after the page reload:
<img width="943" alt="Screenshot 2022-02-07 at 11 11 04" src="https://user-images.githubusercontent.com/472927/152768803-85c58958-782d-46c0-8138-c04f5d237895.png">

### Example URL

https://github.com/refined-github/refined-github/pull/4029

**Comment by fregante** [comment]
It was proposed but the risk is too high. The feature hides a lot of real content and forgetting it on can cause frustration. 

I wonder if there's a way to offer this as an option without offering an option 🤭 

What I've been suggesting in these cases is to add a keyboard shortcut so at least you can just press it on load, but nobody ever added it

**Comment by fregante** [comment]
Any single-letter key that is not already taken. Press <kbd>?</kbd> to see what's not available
