### ISSUE TITLE
Display "Lines Changed" in the Pull Request list items

### ISSUE THREAD

**Issue by DannyDelott** [refined-github/refined-github#5380]
### Description

The first thing I look at during a code review is the `Lines Changed` viz in the top right of a Pull Request:
<img width="142" alt="image" src="https://user-images.githubusercontent.com/4524175/152900054-2265c2fd-47db-4e30-aed6-61089f7fc104.png">

I think it would be really useful if this was displayed on the Pull Requests list page as well to make scanning the PR log a bit more informative (see screenshot below).

### Screenshot

![image](https://user-images.githubusercontent.com/4524175/152900319-33811316-b34c-4f46-9635-6002bf334500.png)

### Example URL

https://github.com/refined-github/refined-github/pulls

**Comment by cheap-glitch** [comment]
I wouldn't personally be against it, but I think something similar was proposed and rejected before.

If I remember correctly, the idea was that the issue/PR lists are already crowded and we don't want to make them unreadable.

**Comment by fregante** [comment]
Indeed. There's a *lot* of data we can display there. This could be nice or it could be noise.

**Comment by kidonng** [comment]
I don't think there's an API for this, which means you have to fetch and parse _every_ PR's HTML to list that info.

**Comment by fregante** [comment]
Let's not add more data to the list for now. Maybe you can suggest it to https://github.com/Mottie/GitHub-userscripts

**Comment by karthikeyann** [comment]
Since this is not getting implemented here, I created https://github.com/Mottie/GitHub-userscripts/pull/221 script to do this.  It needs no-scope classic token from Github.
I also added "Sort" by Most/Least lines changed.
