### ISSUE TITLE
`use-first-commit-message-for-new-prs` breaks when commit summary contains link

### ISSUE THREAD

**Issue by andreasabel** [refined-github/refined-github#5382]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button can be found at the bottom of the options page.

### Example URLs

https://github.com/BNFC/bnfc/pull/new/layout-error

(But this URL could soon not demonstrate the problem any more, as the state of the repo changes.)

### Extension version

22.2.1

### Browser(s) used

Google Chrome

### Description

If I open a new PR from a branch whose first commit starts with `Re #<issue>: text`, then the PR title is just `Re`.

I'd like to keep the full title.
Ideally, the PR text would be made from all of the commit titles.  (I dimly remember that this used to be the case once, but then disappeared as a feature.)

<img width="769" alt="Screenshot 2022-02-08 at 18 43 36" src="https://user-images.githubusercontent.com/1155218/153045133-24fceab7-fb62-44f1-a09d-006e17693179.png">

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by yakov116** [comment]
Its because the issue number is linkified so its split into 3 `<a>` tags

**Comment by andreasabel** [comment]
Excellent!  Eager to test it once it is release.
