### ISSUE TITLE
Auto populate list of approvals in merge commit description

### ISSUE THREAD

**Issue by ForrestH** [refined-github/refined-github#5383]
### Description

Similar to the clear-pr-merge-commit-message feature, this feature would modify the merge commit description text box on pull request pages by adding a line to list the users who have approved the PR. 

### Screenshot

![](https://user-images.githubusercontent.com/9374207/152912033-231286ea-96aa-4178-804e-04f9e5cbe154.png)

### Example URL

https://github.com/refined-github/refined-github/pull/5381

**Comment by fregante** [comment]
Interesting workflow but it's uncommon and thus it can't be the default in Refined GitHub.
