### ISSUE TITLE
Allow rebasing in `update-pr-from-base-branch`

### ISSUE THREAD

**Issue by FloEdelmann** [refined-github/refined-github#5384]
### Description

There is now a repository setting to always enable the "Update branch" button in PRs if the base branch changed: https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/#always-have-the-option-to-update

As previously discussed (#5372), this doesn't mean we can drop `update-pr-from-base-branch`. However, we could try to

1. match the native GitHub style
2. also allow rebasing like GitHub does

### Screenshot

https://user-images.githubusercontent.com/2503052/152357644-6484dc2b-4aae-4977-b76c-b284c5388d7b.mp4

### Example URL

any not up-to-date PR

**Comment by fregante** [comment]
We can probably append "or rebase it." if possible. I don't know if the API allows it though.

**Comment by fregante** [comment]
No can do: https://docs.github.com/en/rest/reference/pulls#update-a-pull-request-branch

**Comment by SunsetTechuila** [comment]
> fregante added "impossible" on Feb 9, 2022

<img width="200" height="200" alt="image" src="https://github.com/user-attachments/assets/8cc1361e-d119-48fb-a44e-41d22d68532f" />

https://docs.github.com/en/graphql/reference/mutations#updatepullrequestbranch

**Comment by SunsetTechuila** [comment]
This is actually a duplicate of #3563 (mostly)

**Comment by SunsetTechuila** [comment]
Should we copy descriptions too?

<img width="352" height="260" alt="Image" src="https://github.com/user-attachments/assets/013f2b62-5068-4fc9-a147-0801246840c5" />

<img width="254" height="142" alt="Image" src="https://github.com/user-attachments/assets/10ad0766-1878-46d9-96fd-ac1171d1b242" />

**Comment by fregante** [comment]
> Should we copy descriptions too?

Back in the day, Refined GitHub would hide those descriptions, so let's go without them 

My concern is that this change requires a buttload of code and that dropdown-like button is really not my favorite, in fact we have a few features that remove it in some situations.

**Comment by SunsetTechuila** [comment]
I've already coded everything

**Comment by SunsetTechuila** [comment]
> dropdown-like button is really not my favorite, in fact we have a few features that remove it in some situations.

You don't have to open the dropdown unless you want to rebase
