### ISSUE TITLE
Improve the contrast of strikethrough text in dark theme

### ISSUE THREAD

**Issue by huyenltnguyen** [refined-github/refined-github#5385]
### Description

Hey team, thank you for a great extension!

I'm wondering if the color of strikethrough text could be improved, as it is currently a bit hard to read in dark theme.

I believe the color is set here:

https://github.com/refined-github/refined-github/blob/3deadf54b50aebd250e61f7c237b209a50713662/source/refined-github.css#L64-L67

### Screenshot

Here is a comparison:

| Light default | Dark default |
| --- | --- |
| <img width="855" alt="Screen Shot 2022-02-09 at 01 54 37" src="https://user-images.githubusercontent.com/25715018/153056790-1dac6680-852f-4beb-9366-af21974b32c7.png"> | <img width="877" alt="Screen Shot 2022-02-09 at 01 54 16" src="https://user-images.githubusercontent.com/25715018/153056812-110e95fd-e8b5-4d12-8fcb-180927ea2766.png"> |

### Example URL

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
I think this is something we're doing, and I agree it can be fixed
