### ISSUE TITLE
`set-default-repositories-type-to-sources` error on oauth page

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5386]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button can be found at the bottom of the options page.

### Example URLs

https://github.com/login/oauth/authorize?you-get-the-idea

### Extension version

22.2.1

### Browser(s) used

Chrome

### Description

I don't even know why we run stuff there. The OAuth page probably belongs to #5356.

Note: there's also an auth page requiring you to input verification code, which can be triggered by login into the GitHub CLI (I don't remember it clearly).

```
TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:6469:13
    at new Promise (<anonymous>)
    at oneMutation (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:6465:14)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:6518:51
    at async chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:6516:9
    at async runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:2938:20)
    at async setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:2948:34)
    at async chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:2970:29
```

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by fregante** [comment]
I'm sure all "generic" features that aren't limited to isRepo suffer from the same issue on similar pages, like error pages. We can treat the login pages like the error pages and just exit early, there's not much we can do on them.

**Comment by seguri** [comment]
I'm here because of the `TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.`.

Video:

https://user-images.githubusercontent.com/2405157/169700795-092cdd3d-0f4c-475d-a881-84726cb7c2cb.mov
