### ISSUE TITLE
Be more verbose about our new releases

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5388]
### Description

A constant source of confusion is that "**Refined GitHub updates changed something I'm not expecting**":

> [I'm a long time user of the extension, and it gets auto-updated. As long as everything works as I've learned to expect - I have no need (nor time, to be honest) to go and randomly check if there are any new features or toggles that I need to tweak.](https://github.com/refined-github//refined-github/pull/5278#issuecomment-1029862107)

This is both boon and bane. It shows that we are doing a decent job integrating into GitHub, but more implicit than necessary.

Apparently asking users to subscribe to updates themselves (in https://github.com//refined-github/refined-github/issues/3543 or elsewhere) does not work well. To reduce friction, we need to be more verbose.

I suggest we adding a banner (could be anywhere, or only on the dashboard) pointing to the release note the first time users open GitHub after an update.

Or resort to opening the release note page after an update (albeit annoying, I know some extensions do this). 

---

Note this does not resolve the issue for new users. I remember that is discussed elsewhere, but couldn't find it.

### Example URL

https://github.com/

**Comment by fregante** [comment]
Anyone who wants to hear about the updates, they already can, it's literally on the welcome page. Can't blame us if you don't RTFM.

Generic update banners and new tabs only function to annoy everyone else who's not interested.

Something that would be nice in some cases is "this is a new button by RG" *glow* but that isn't always applicable (sometimes it's a new behavior, one less button, etc)
