### ISSUE TITLE
Explain the "conversation" jargon

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5389]
### Description

Implementation-wise, ["Conversation" means issues and PRs](https://github.com/fregante/github-url-detection/issues/14), but not discussions. I assume this is vague for most users:

> [Okay I found that but didn't think about that conversations are issue lists](https://github.com/refined-github/refined-github/issues/4326)

- We should explain it somewhere obvious, probably README. I'm not sure where to put it though.
- The search field on extension options page should be more considerate. When searching for "issue", "pull" and "pr"*, it should also list results for "conversation".

\* we probably also want to make sure "pull" and "pr" are interchangeable during searching, which could be achieved by revising feature descriptions.

Related: #4741

Also applies to repo -> repository

### Example URL

N/A

**Comment by fregante** [comment]
Great idea! Also we can add a "(issues and PRs)" wherever possible when mentioning conversations. Or just replacing conversations with "issues and PRs" in the descriptions (not in the feature names)
