### ISSUE TITLE
Exclude explicitly linked comments in `conversation-activity-filter`

### ISSUE THREAD

**Issue by FloEdelmann** [refined-github/refined-github#5390]
### Description

Like #5334, but for `conversation-activity-filter`. E.g. in https://github.com/refined-github/refined-github/issues/4008#issuecomment-996659891, I linked an [earlier comment](https://github.com/refined-github/refined-github/issues/4008#issuecomment-824729016) that is now hidden. While the filter is active, I have no idea what I linked :sweat_smile: 

With #5562, explicitly linked comments are excluded on page load, so clicking this link shows the comment: https://github.com/refined-github/refined-github/issues/4008#issuecomment-824729016
However, clicking an in-page link doesn't work.

### Reproduction

1. Go to https://github.com/refined-github/refined-github/issues/4008
2. Load hidden timeline items
  ![grafik](https://user-images.githubusercontent.com/202916/162746850-44db1b81-04c4-44b9-97d8-8f08884b685c.png)
3. Append this hash `#issuecomment-824729016` to the URL

… or …

1. Go to https://github.com/refined-github/refined-github/issues/4008#issuecomment-996659891
2. Load hidden timeline items
  ![grafik](https://user-images.githubusercontent.com/202916/162746850-44db1b81-04c4-44b9-97d8-8f08884b685c.png)
3. Scroll down to my comment and click this link there (it's currently hidden as well :slightly_frowning_face:):
  ![grafik](https://user-images.githubusercontent.com/202916/153233307-b6daca6e-306e-4550-ace4-d44e0fa37bf1.png)

**Comment by FloEdelmann** [comment]
@cheap-glitch @jopemachine The exact issue I described still persists after #5562. It's only mitigated for links from another page. I guess the feature needs some kind of listener to `location.hash` changes.

**Comment by FloEdelmann** [comment]
@cheap-glitch Can this issue be reopened please?

**Comment by cheap-glitch** [comment]
> It's only mitigated for links from another page. I guess the feature needs some kind of listener to `location.hash` changes.

If it can be done in a few lines then why not, otherwise I'm not sure it's worth the complexity.

cc @fregante

**Comment by fregante** [comment]
Repro:

0. On this page
1. Hide resolved comments
2. Click https://github.com/refined-github/refined-github/issues/5390#issuecomment-1099065613

Indeed this should work.

If we had `:has` we could add it to the CSS rule to automatically exclude the items when they become linked, like:

```css
.hide-comments .rgh-resolved:not(:has(:target)) {
	display: none;
}
```

However if we had `:has` the feature would barely need any javascript!

For now I think we can use `hashchange` to simply exclude the linked comments. We don't have to re-hide them if the hash changes again.
