### ISSUE TITLE
Copy source branch name without username

### ISSUE THREAD

**Issue by fisker** [refined-github/refined-github#5391]
### Description

I use this button when switching branches, but it copied `fisker:print-property` instead of just `print-property`.
I can't paste it after `git checkout ___`

### Screenshot

![image](https://user-images.githubusercontent.com/172584/153325989-3b6f2eef-86ed-4b61-be95-843716e29ed9.png)

### Example URL

https://github.com/refined-github/refined-github/pull/3

**Comment by fisker** [comment]
I didn't see #3522 at first, maybe reopen that?

**Comment by fregante** [comment]
There's a Code button to its right  that has exact copypastable commands, no need to type "git checkout" either

**Comment by fisker** [comment]
I know, but I only use that button to check out others PR with `gh pr checkout`.

> no need to type "git checkout" either

It's more like I typed `git checkout ` first, then I forgot the name, so I need copy that branch name, so I don't need delete `git checkout ` I already typed(or hit <kbd>ctrl + C</kbd>).

`Code` button:

- requires two clicks
- Far from the PR title
- git command  is not on top

Out of curiosity, what do you think GitHub adds that copy button for?

**Comment by cheap-glitch** [comment]
> I know, but I only use that button to check out others PR with `gh pr checkout`.

You can use `gh pr checkout` with your own PRs too.

> It's more like I typed `git checkout `first, then I forgot the name, so I need copy that branch name

You should be able to autocomplete branch names on the command line, which imo is infinitely more efficient than any copy/paste-based workflow.

**Comment by fisker** [comment]
> You can use gh pr checkout with your own PRs too.

I know, but I don't like...

> You should be able to autocomplete branch names on the command line

I use `cmd.exe`

**Comment by fregante** [comment]
> Out of curiosity, what do you think GitHub adds that copy button for?

No idea, never used it, it doesn't make any sense to include the username, and if it doesn't make sense to you I suggest contacting GitHub too. Maybe it does make sense and changing it breaks someone's workflow. 

> so I don't need [to] hit ctrl + C


You're asking for a feature to avoid pressing a single keystroke and changing the habit. Doesn't seem worth it to me. 

There are a million ways to check out PRs and they're available on the page. I don’t think we need to change the behavior of a button to add one more way to do things. Also selecting the branch name is still possible.

**Comment by fisker** [comment]
`Code` button also not clickable when I scroll to the bottom and found someone want me to do changes.

**Comment by fregante** [comment]
> You're asking for a feature to avoid pressing a single keystroke and changing the habit. 

> selecting the branch name is still possible

> Doesn't seem worth it to me.
