### ISSUE TITLE
The style of custom editor buttons is broken

### ISSUE THREAD

**Issue by cheap-glitch** [refined-github/refined-github#5392]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button can be found at the bottom of the options page.

### Example URLs

https://togithub.com/refined-github/sandbox/issues/3

### Extension version

22.2.1

### Browser(s) used

Firefox

### Description

![image](https://user-images.githubusercontent.com/46634000/153365797-0295fc2c-1149-4825-bbac-b5ddc9b3642c.png)

Affected features:
- `table-input`
- `collapsible-content-button`

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by cheap-glitch** [comment]
Adding the `.btn-octicon` class seems to fix things, for the most part:

![image](https://user-images.githubusercontent.com/46634000/153366639-ab35b814-0d1e-4446-9d93-01e5f55c3ad7.png)

The spacing before the table icon may need to be adjusted too.

Also, slightly unrelated but GitHub started to "externalize" the tooltips, using the `<primer-tooltip>` custom element:

![image](https://user-images.githubusercontent.com/46634000/153367035-e2838188-09c4-4fcd-8f31-10cf18913edb.png)

Should we switch to it too? (The old tooltips still work, at least for now).

**Comment by fregante** [comment]
I'm seeing it on iOS too

**Comment by kidonng** [comment]
> I'm seeing it on iOS too

@fregante kinda off-topic, but if you find any issues/possible improvements on mobile please let us know.

**Comment by fregante** [comment]
I've been using the official app most of the time. I only open GitHub.com when a feature is missing or I want to use a RG feature like updating branches 😁

**Comment by fregante** [comment]
Did this just break again? Safari 15.3, seeing this on every comment field, like https://github.com/refined-github/refined-github/pull/5428/files#submit-review

<img width="685" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/155007003-014f6328-452b-4d51-800e-dfda087b376d.png">

**Comment by cheap-glitch** [comment]
> Did this just break again?

Nope, looks fine in Firefox. It's likely RGH was updated to a newer version in the App Store and the hotfix needs to be moved to the correct CSS file.

**Comment by fregante** [comment]
But now all browsers are on the same version. If Safari needs a hotfix, then all of them do

**Comment by cheap-glitch** [comment]
> But now all browsers are on the same version. If Safari needs a hotfix, then all of them do

Weird. Could it be the update went wrong?

@refined-github/maintainers is anyone else seeing this bug? I'm not, on Firefox + RGH 2.2.13

**Comment by fregante** [comment]
Works again now
