### ISSUE TITLE
Release download counter does not show

### ISSUE THREAD

**Issue by andry81** [refined-github/refined-github#5403]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/andry81-builds/amule/releases

### Extension version

22.2.1

### Browser(s) used

Firefox

### Description

It does not work for me. The screens is the same as from here:

https://github.com/refined-github/refined-github/issues/5162

I've just installed the extension from here: https://addons.mozilla.org/firefox/addon/refined-github-

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by cheap-glitch** [comment]
The feature is working fine, it's just that the download count is 0, so nothing is shown :smiley: 

If you look at the artifacts of the previous release on the page that you linked to, you'll see that the feature is indeed working:

![image](https://user-images.githubusercontent.com/46634000/153721773-ab077c5b-f7f5-4676-8cd2-54c099023425.png)

**Comment by andry81** [comment]
> The feature is working fine, it's just that the download count is 0, so nothing is shown smiley

It is not, REST API shows not zero counters:

https://api.github.com/repos/andry81-builds/amule/releases

**Comment by cheap-glitch** [comment]
> It is not, REST API shows not zero counters

![image](https://user-images.githubusercontent.com/46634000/153730733-c12c1fda-6fd3-4fc1-9573-148869c77f12.png)

**Comment by andry81** [comment]
You didn't parse entire response.

```
        "state": "uploaded",
        "size": 58326086,
        "download_count": 3,
        "created_at": "2022-02-07T08:52:36Z",
        "updated_at": "2022-02-07T08:52:43Z",
        "browser_download_url": "https://github.com/andry81-builds/amule/releases/download/v2.3.3--2021-12-05/amule-dev--2-3-3--2021-12-05--e26d06a.7z"
```
```
        "state": "uploaded",
        "size": 14636936,
        "download_count": 10,
        "created_at": "2022-02-07T08:52:49Z",
        "updated_at": "2022-02-07T08:52:51Z",
        "browser_download_url": "https://github.com/andry81-builds/amule/releases/download/v2.3.3--2021-12-05/vcredist_x86.exe"
```

**Comment by andry81** [comment]
I've used another extension and it works as expected:

https://addons.mozilla.org/firefox/addon/github-downloads

**Comment by busches** [comment]
Your rest response shows zero downloads for all the assets on [v2.3.3--2021-12-05--wx28-xp](https://github.com/andry81-builds/amule/releases/tag/v2.3.3--2021-12-05--wx28-xp) and the extension shows nothing, as we don't show a zero.

Your rest response shows downloads for the assets on [v2.3.3--2021-12-05](https://github.com/andry81-builds/amule/releases/tag/v2.3.3--2021-12-05) and so does the extension, as seen in Florent's screenshot.

What are you expecting that's not happening? You said other extensions worked, can you share some screenshots?


We don't call the REST api, but the GraphQL one and we can see it matches the REST call you linked.

```json
{
  "data": {
    "repository": {
      "_v2_3_3__2021_12_05__wx28_xp": {
        "releaseAssets": {
          "nodes": [
            {
              "name": "amule-wx28-xp--2-3-3--2021-12-05--e26d06a.7z",
              "downloadCount": 0
            },
            {
              "name": "amule-dev-wx28-xp--2-3-3--2021-12-05--e26d06a.7z",
              "downloadCount": 0
            },
            {
              "name": "vcredist_x86.exe",
              "downloadCount": 0
            }
          ]
        }
      },
      "_v2_3_3__2021_12_05": {
        "releaseAssets": {
          "nodes": [
            {
              "name": "amule--2-3-3--2021-12-05--e26d06a.7z",
              "downloadCount": 2
            },
            {
              "name": "amule-dev--2-3-3--2021-12-05--e26d06a.7z",
              "downloadCount": 5
            },
            {
              "name": "vcredist_x86.exe",
              "downloadCount": 12
            }
          ]
        }
      }
    }
  }
}
```

**Comment by andry81** [comment]
> Your rest response shows downloads for the assets on [v2.3.3--2021-12-05](https://github.com/andry81-builds/amule/releases/tag/v2.3.3--2021-12-05) and so does the extension, as seen in Florent's screenshot.

It does not show. I don't know what to say anymore here.

**Comment by busches** [comment]
This is why I asked for a screenshot. Here's one more showing nothing for the first release, as it has no downloads, and counts for the second release as it does:

![image](https://user-images.githubusercontent.com/857700/153734744-49e8c3a1-f7a3-4b8f-b33a-a7bb07ea4f97.png)

**Comment by busches** [comment]
And what happens if you clear the extension's cache and refresh?

**Comment by andry81** [comment]
> your PAT is bad.

Ok, this is it. But you didn't ask for any PAT tokens. Other extensions basically asks on first use, your extension didn't ask of any. How the user suppose to know that?

**Comment by busches** [comment]
When you install the extension, we open a window to this issue: https://github.com/refined-github/refined-github/issues/3543

The first thing it mentions is the PAT.

**Comment by andry81** [comment]
You better to ask it programmatically on first use instead of force user to read spam letters.

**Comment by busches** [comment]
@andry81 Contributions welcome.

This issue also asked if there were any console errors at the start. Additionally, you opened the options menu to add custom CSS with #5406 and would have had to scroll past the PAT section in the options, so there's been quite a few chances to catch this.

**Comment by kidonng** [comment]
> You better to ask it programmatically on first use

That's exactly what the extension will do.

> instead of force user to read spam letters.

We do not _force_ you to read the issue and the "spam letters" as you described is a pretty common pattern among browser extensions.

> You may check other extension how it does use the permissions:

First, they work differently. If they don't ask for a PAT you may meet quota issues.

Second, it does not make sense to follow the "best patterns" of extensions used by only a few people.

Third, there's no such "best patterns" in reality. PAT is something you need to create manually and we can't just prompt aggressively as other people will hate it.

> there said it's optional

It is optional for the _whole extension_, but required for some (or let's say, many) features.

@refined-github/maintainers I think we do need to reword a bit (either in the welcome issue or the options page) and make it

# Extremely Clear

PAT is required.
