### ISSUE TITLE
Releases chat (collaborators only)

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5407]
Occasionally we have release-related discussion (failed submissions, schedules, etc). We can have them here and gradually delete our own old comments.

@refined-github/maintainers

**Comment by fregante** [comment]
@kidonng feel free to create a release today after you merge your approved PRs. 

Then let's aim for a 22.2.22 release

**Comment by fregante** [comment]
Thanks @kidonng! 🙏

**Comment by cheap-glitch** [comment]
I added a little blurb about the new hotkey for `conversation-activity-filters` in today's release. Feel free to reword it if it's not clear enough.

**Comment by fregante** [comment]
Let's release after:

- #5488 
- https://github.com/refined-github/refined-github/pull/5491

**Comment by fregante** [comment]
Bigass release successful!

<img width="351" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/1402241/169702960-25cb4618-b190-43a2-98a0-539a83de8eb9.png">

I tweeted about it at:

https://twitter.com/fregante/status/1528396221588463616

**Comment by fregante** [comment]
Last year we reduced the frequency of releases because Firefox was being annoying and requiring manual intervention every so often. 

I’m thinking we should return to a more frequent schedule, without actually having any schedule at all. Nothing should stop us from creating a release with 3 commits if there are some good features being broken. 

However Safari is still being released every 30/40 days so we need to keep hotfixes around for that. Let’s consider them LTS releases 😅

**Comment by cheap-glitch** [comment]
+1 for having no particular schedule, weekly would be nice but there might weeks with no changes merged (or at least no user-facing ones)

**Comment by fregante** [comment]
My preferred logic is described here:

- https://github.com/fregante/daily-version-action/issues/17

We can follow the same thing manually and release as we see fit.

**Comment by fregante** [comment]
I’m going to release 22.8.1 soon. Let’s try/discuss/finish/merge the open PRs 🚀

**Comment by fregante** [comment]
23.2.1 coming up within 12/24 hours. Please review some open PRs if you have time. I'll probably fix more bugs in a new release within 5/7 days later as well
