### ISSUE TITLE
Adapt more responsive design

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5408]
### Description

Safari and some 3rd-party Chromium browsers on Android are able to install Refined GitHub on mobile devices. There are also use cases for portrait mode or split screens, as mentioned in #4836.

This meta issue tracks responsive design issues encountered during the making. It won't be a first priority but let's tackle some obvious ones.

- #5398 (not sure if that counts)
- #5404
- #5405
- #4836

### Example URL

N/A

**Comment by fregante** [comment]
This isn't very actionable. It might be best to open specific issues when found. It could also be part of #5222 for anyone looking for small wins
