### ISSUE TITLE
Safari: The welcome page is opened on update

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5412]
### Extension version

22.2.13

### Browser(s) used

Safari 15.3

### Description

- Since https://github.com/refined-github/refined-github/issues/5228

This should not happen on update, but apparently Safari triggers the `install` event even on update…

Two choices, one of which _must be_ picked before the next release:

- exclude Safari from the current logic
- find another way to do this, maybe via the app? Or maybe better logic? Not sure if it exists.

**Comment by yakov116** [comment]
This was always an issue? Or they just broke this now?

**Comment by kidonng** [comment]
> This was always an issue? Or they just broke this now?

Both (#5228 is on Dec 20, 2021)

<img width="584" alt="image" src="https://user-images.githubusercontent.com/44045911/154204319-97cfa1c6-e88f-430d-9fe4-cc3d19533617.png">

**Comment by fregante** [comment]
> This was always an issue? Or they just broke this now?

The welcome page never worked before. We just added support for it but Safari sucks so here we are.



> The typical `first_installation` check probably works:

Sounds good, but it's complicate at this point because:

- we need to migrate the state from other browsers
- in Safari, on the next update we still won't know wether it's a new install or update, so we just need to disable the welcome screen until the next-next version

**Comment by kidonng** [comment]
> * in Chrome/Firefox: we need to migrate the state

They don't need this

> * in Safari: on the next update we still won't know wether it's a new install or update, so we just need to disable the welcome screen until the next-next version

Maybe we don't need a new variable, just check `featuresAlreadySeen`? People don't even need to have the token inputted™️, they just need to open the options page once. Only problem is that it is not synced. <sub>And false positives: people who just install the extension and chill out</sub>

**Comment by fregante** [comment]
> > * in Chrome/Firefox: we need to migrate the state
> 
> They don't need this

They do because we don't need to keep two separate ways to detect new installs: We need one that works for both.



> Maybe we don't need a new variable, just check `featuresAlreadySeen`?

ohhh almost good, except it only works if the user ever opened the options (which is not a guaranteed that they did or that they ever will)

If we have a key that is _always_ stored on load, then that would simplify things a lot and we could fix it for the next version already (no 2-version migration needed for Safari)

**Comment by fregante** [comment]
How about this, in the `install` handler:

```js
if (isSafari()) {
	if (!await detectFirstInstall()) {
		// Just an update #5412
		return;
	}

	// Then continue to open the first install page
}
```

In `detectFirstInstall` we check for `featuresAlreadySeen` and for a custom key like `firstInstall`. If neither is set, save `firstInstall` to ensure this keeps working as intended even if the user has never opened the options.

Two advantages of this solution:

- Chrome users are unaffected, they don't need `firstInstall` at all
- Most Safari users will be automatically migrated over, with a small minority seeing the message once
