### ISSUE TITLE
Resolve `/raw/` route redirection where possible

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5424]
### Description

This requests comes in three parts:

- Make the `Raw` button links to `raw.githubusercontent.com`

  <img width="281" alt="Screen Shot 2022-02-20 at 18 35 25" src="https://user-images.githubusercontent.com/44045911/154838560-ca086845-3e3f-47ff-9995-3713004a8966.png">

- Use `raw.githubusercontent.com` in our feature like `more-file-links`
- Change `/raw/` links to `raw.githubusercontent.com` in `shorten-links`

All these should only be applied to `github.com` links because of GHE.

**Motivation**: avoiding unnecessary redirection makes requests faster, and save the need to manually resolve redirection in some tools (e.g. pass `--location/-L` to `curl`), not to mention some programs simply doesn't consider redirection a thing.

**Cons**: `github.com` links are guaranteed to be usable, but `raw.githubusercontent.com` may change (however I don't think this is a concern in foreseeable future).

### Example URL

https://github.com/refined-github/refined-github/blob/main/.gitattributes

**Comment by fregante** [comment]
This would be good but I'm a little hesitant because it could break. I suppose these links haven't changed in forever so it should be pretty safe. 

GHE and private repos can't use this

**Comment by fregante** [comment]
While I like the idea, I'd rather not mess with links just for a micro optimization like this one
