### ISSUE TITLE
Inbox prev/next buttons at top of the page

### ISSUE THREAD

**Issue by jcommelin** [refined-github/refined-github#5427]
### Description

Would it be possible to have prev/next buttons at the top of the page for the inbox.
Currently, when I select 10 items on the page, and click on "done", the prev/next buttons jump up and down. By the time I want to click "prev", the page has loaded 10 new items, and the button has jumped down, causing a faulty click on my side.

### Example URL

https://github.com/notifications

**Comment by cheap-glitch** [comment]
Maybe this could be an extension of `previous-next-commit-buttons` :thinking:

**Comment by fregante** [comment]
The only difference is the Notifications page is dynamic so we'd have to listen to page changes. Not sure I wanna do that, also because we might not have space in the header here.

**Comment by fregante** [comment]
PR welcome to add a small `[ < ][ > ]` navigation at the top, hiding it as soon as it doesn't fit, probably with `class="d-none d-lg-block"`

**Comment by tghimanshu** [comment]
I want to work on it! This would be my first contribution so I would appreciate it if you could guide me to the right track.
<img width="749" alt="image" src="https://user-images.githubusercontent.com/34628529/227709822-4ce3bbb8-7d94-4a6c-9aa9-4bbbb6e86bf2.png">

This is what I have created in a local copy.

**Comment by fregante** [comment]
Great! Make sure to follow the instructions in my last comment and please send a PR

**Comment by fregante** [comment]
Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it.
