### ISSUE TITLE
Add option to swap the order of incoming and current changes in merge conflict resolver

### ISSUE THREAD

**Issue by fonix232** [refined-github/refined-github#5431]
### Description

In my current workflow, the most common merge conflict is additions to the changelog of the project - any incoming change is already merged, thus should be ordered above the current change, however in the current implementation, Refined Github sorts it below the current change.

An example:

1. Chanelog contains item A and B at the beginning:
```lang-markdown
# CHANGELOG

- A
- B
```
2. A PR is opened, adding item D to the changelog:
```lang-markdown
# CHANGELOG

- A
- B
- D
```
3. Another PR is opened, and merged before the first PR is merged, making the incoming changelog look like this:
```lang-markdown
# CHANGELOG

- A
- B
- C
```
4. This causes the following merge conflict:
```lang-markdown
# CHANGELOG

- A
- B
<<<<<<< Incoming change
- D
=======
- C
>>>>>>> Current change
```
5. With the current behaviour of Refined Github, if both changes are accepted, their order wouldn't be correct. This requires manual fixing. My recommendation is an extra button that swaps the order of the incoming and current changes, which results in the correctly ordered changelog list, with a single click:
```
# CHANGELOG

- A
- B
- C
- D
```

### Example URL

-

**Comment by fregante** [comment]
> Refined Github sorts it below the current change.

We don't touch the code until the user clicks our `resolve-conflicts` buttons, in which case we only delete lines, we never move anything.

Since this behavior is standard git we're not going to automatically change it. The alternative would be to add a fourth button to keep both of them **_and swap them_**, but I'd like to hear what others say. To me it sounds niche, but maybe I'm wrong.

**Comment by kidonng** [comment]
Refined GitHub is not Refined Git or a substitute to git tooling, period. 

Most conflicts are not going to be resolved by simply swapping the changes so it doesn't seem worth it to support such an uncommon action.

**Comment by fonix232** [comment]
@fregante I was thinking about adding a fourth button, which would execute exactly what you're saying - accept both changes, but swap the order they're being accepted in.

@kidonng I'm aware of this. I'm not asking for git tooling here, but an extra button that appears on GitHub's _own_ conflict resolution screen (which Refined Github already tinkers with!) that allows to accept both changes present, but in a reverse order. I also understand that most conflicts wouldn't be resolved this way - my use case is pretty specific, however I can see how others could also apply it to their own changelogs (just to further my own example), as well as other code pieces.

By having this function, a large majority of our conflict resolution could be sped up - clicking a button takes a second, whereas manually swapping the order of the two lines adds a few extra seconds of manual work. It doesn't sound much, but over dozens, or hundreds of PRs (our average number of PRs merged in a week fluctuates between 80 and 120), this can save a lot of time. And yes, just to confirm, a good chunk of the conflicts we face come from the changelog only, as every single PR will have at least one entry added.

**Comment by cheap-glitch** [comment]
Looking at the code in `resolve-conflicts.ts`, this seems like a relatively easy feature to implement, so, why not.

**Comment by fregante** [comment]
> why not.

Extra code and extra UI and extra bugs 😃 

Let's stick to what VSCode does, which is displaying the 3 buttons only.
