### ISSUE TITLE
Improve shortcuts help

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5439]
### Description

Quiz time: what feature added what shortcut and where does the shortcut apply?

<img width="299" alt="image" src="https://user-images.githubusercontent.com/44045911/155520963-00f6f16e-55fa-4044-92ab-6585bd097dec.png">

We should follow GitHub in the following ways:

- **Have concise, categorized shortcuts help.** Dumping all shortcuts into one section isn't going to help remember them and overtime many just get forgotten, and we never know (see: #5436).

- **Show context-related shortcuts.** GitHub does this via fetching them from something like: `https://github.com/site/keyboard_shortcuts?contexts=repository`. We should do the same.

  The "Create a new release" shortcut above is added by `create-release-shortcut` and only available on the releases page. If you try to activate it anywhere else, all you get is confusion.

### Example URL

N/A

**Comment by fregante** [comment]
> what feature added what shortcut

That's irrelevant, we don't do that with any button we add to GitHub 



> where does the shortcut apply

On the current page. We (should?) only add shortcuts to the list when the feature is active, so that means all of those are available on the current page. I don’t think it's particularly worth it to organize those shortcuts. I would sort them alphabetically though, so those "Go to" entries are grouped together.

**Comment by kidonng** [comment]
> > what feature added what shortcut
> 
> That's irrelevant, we don't do that with any button we add to GitHub

It's not meant to be shown directly 😅 sorry if I didn't make it clear

**Comment by fregante** [comment]
> I would sort them alphabetically though, so those "Go to" entries are grouped together.

PR welcome

**Comment by fregante** [comment]
Additional possible improvement desired by @cheap-glitch:

- [ ] use the new `addHotkey` to register an additional <kbd>?</kbd> handler that works with non-US keyboards
