### ISSUE TITLE
Option/menu toggle always visible to switch between commits/files when comparing changes

### ISSUE THREAD

**Issue by fmigneault** [refined-github/refined-github#5440]
### Description

When viewing compare changes between two branches/tags, the number of commits that are included between the two selected versions impacts how the pages is rendered. If the amount in "large enough", a shortcut appears to directly toggle between "tabs" view commits/file contents. This is nice because it avoids scrolling a lot of commits to reach the contents. 

On the other hand, when "few commits" are present between the two versions, the toggle option is replaced by some _stats banner_ with commits, changed files and contributor counts. However, the amount of commits can still be enough to require scrolling down through commits instead if simply clicking on the toggle.

It would be great to be able to view both the _stats banner_ and the _shortcut toggle_ simultaneously regardless of commit count in the compare changes, allowing convenient access to file contents. Since the page rendering changes conditionally, comparing multiple combinations of versions with differing amounts of commits is not intuitive (sometimes scroll, sometimes toggle). 

Because compares can sometime have very few commits (e.g: 2-3), the current view with _stats banner_ should probably still display the file contents directly under, since they are already visible. Maybe the added _shortcut toggle_ would only hide away commits in this case instead of actually toggling between commit/file tabs. 

### Screenshot

Compare change that has enough commits to make the shortcut appear:
Example: https://github.com/refined-github/refined-github/compare/22.2.1...22.2.22
![image](https://user-images.githubusercontent.com/19194484/155826121-e3cbbc2e-5a24-4eac-90cb-6289dd30a887.png)

Compare change that doesn't have enough commits (files much lower under the commit list).
Example: https://github.com/refined-github/refined-github/compare/22.2.13...22.2.22
![image](https://user-images.githubusercontent.com/19194484/155826123-bfbad86c-0f46-4047-93c0-37c71a035251.png)

Compare not worth having a full toggle since contents already visible
Example: https://github.com/refined-github/refined-github/compare/add95be2eb91268900b10903eb5d81b6e454dab0...33998e330a4b9fea1d6762f1cb9a153764116b25
![image](https://user-images.githubusercontent.com/19194484/155827004-4ff7ce48-2cb2-4d80-8844-7d48e3ec79bc.png)

### Example URL

https://github.com/refined-github/refined-github/compare

**Comment by cheap-glitch** [comment]
Thanks for the various links and screenshots!

> However, the amount of commits can still be enough to require scrolling down through commits instead if simply clicking on the toggle.

So if I understood right, you'd like to (almost) always have two tabs on the compare page, one for the commit list and one for the files? I don't think it'd be impossible, but it probably won't be trivial either. Seems to me like too much effort just to avoid a bit of scrolling.

What we _could_ do is turn the "x files changed" in the heading into a link that jumps to the file list:

![image](https://user-images.githubusercontent.com/46634000/155853959-fcd63d56-c394-47c4-b638-84388b2f9eec.png)

Not only is it very easy to implement, it's also less intrusive and more intuitive than a button to hide the commits — though it's also less discoverable.

It also won't help with that ↓

> Since the page rendering changes conditionally, comparing multiple combinations of versions with differing amounts of commits is not intuitive

**Comment by fmigneault** [comment]
You understood right.

I think the problem in the current page behavior is not particularly about the scrolling itself (its not *that much* scrolling), but rather the inconsistency between different page loads. Since it is very easy to change the compared versions with these menus: 

![image](https://user-images.githubusercontent.com/19194484/155854619-29b786b4-f7bf-4fe9-9a9a-33da7cb19f1b.png)

... what appears under them (commits/files in separate tabs, or one on top of the other) is always different.

But certainly, the link in the highlighted "files changed" is a good alternative if the tabs are too hard to implement or not worth the effort. Maybe a button "Goto files changes" that looks similar to the tab instead of the link would help making it more discoverable?

**Comment by fregante** [comment]
> One must scroll past commits to view files. A "goto" shortcut would allow at the very least to move directly to those files.

I like @cheap-glitch’s suggestion for that

**Comment by fregante** [comment]
> What we _could_ do is turn the "x files changed" in the heading into a link that jumps to the file list:
> 
> ![image](https://user-images.githubusercontent.com/46634000/155853959-fcd63d56-c394-47c4-b638-84388b2f9eec.png)

`linkify-jump-to-bottom-in-compare-pages` or something like that. Super simple feature

**Comment by fregante** [comment]
Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it. I may still accept a PR in the next 6 months.
