### ISSUE TITLE
Show `useful-forks` on archived repos

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5443]
We can bring our link out in situations where the desire to find a fork is likely.

Example:

- archived repos https://github.com/reactjs/react-autocomplete
- repos that have not been updated in a 6+ months (and have 200+ stars?)

For the archived repos we can just show a textual link in the yellow archived bar:

> This repository has been archived by the owner. It is now read-only. [Find forks]

Perhaps there should still be a minimum amount of stars or forks before this link shows up. Showing it on 10-star repos is useless, example:

- no button please: https://github.com/fregante/setup-git-token

**Comment by payne911** [comment]
I feel like maybe some kind of search icon

![image](https://user-images.githubusercontent.com/38117856/212502694-357c014f-d0de-400e-b1e5-35f89683460e.png)

could be squeezed somewhere in the "Fork" main button

![image](https://user-images.githubusercontent.com/38117856/212502712-e7fccc00-89b4-4ca7-a052-6d7cf428cdf4.png)

I feel like as long as there's at least 1 fork, it would make sense to display such quicklink.
