### ISSUE TITLE
`conversation-activity-filter` is clipped on small viewports

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5450]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github/issues/5449

### Extension version

22.2.13

### Browser(s) used

Safari 15.3

### Description

<img width="318" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/156516115-5152e337-de2b-4aa7-9bac-9752f76d6d22.png">

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by fregante** [comment]
Sometimes however this alignment is correct: https://github.com/refined-github/refined-github/pull/5432

<img width="856" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/156516563-8b9fac77-c6d8-4a39-9e83-8545b78dcd4e.png">

**Comment by cheap-glitch** [comment]
This should be fixed by #5415:

https://user-images.githubusercontent.com/46634000/157322723-05423c63-c57d-4203-a882-0cd47c003347.mp4

**Comment by kidonng** [comment]
> This should be fixed by #5415:
> 
>  capture-1646772553.mp4

Maybe not, it switches to popup only if the viewport is narrow enough.

**Comment by kidonng** [comment]
<img width="299" alt="image" src="https://user-images.githubusercontent.com/44045911/158425174-5e2a17fb-0cc3-446a-b298-6a27acf6d3de.png">

**Comment by cheap-glitch** [comment]
> But to be honest it's too rare to be worth fixing

If the fix is as simple as adding `.dropdown-se` or something, then I'd say it's worth it. Plus afaict it doesn't depend only on the window size, but also on the length of the metadata under the issue/PR title.

**Comment by kidonng** [comment]
> Plus afaict it doesn't depend only on the window size, but also on the length of the metadata under the issue/PR title.

That's what I'm concerned about, is there a pure-CSS fix?

**Comment by fregante** [comment]
> If the fix is as simple as adding `.dropdown-se` or something

Unfortunately not because on PRs it will be right-aligned and it will overflow the other way. However that overflow is better because technically the viewport will stretch and the content will be available. For this reason probably it's a better solution than this.

What if we use east on issues and west on PRs? PRs usually have a long description and viceversa
