### ISSUE TITLE
Branches in PR hovercard show [object Text]

### ISSUE THREAD

**Issue by j-f1** [refined-github/refined-github#5454]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github/releases/tag/22.3.3

### Extension version

22.3.3

### Browser(s) used

Safari TP Release 140 (Safari 15.4, WebKit 17614.1.1.5)

### Description

I’m running from the `main` branch by building the Safari extension manually. With Refined GitHub disabled, the branches do appear correctly but they aren’t linkified.

Also, I sometimes see the branch listed as `[object HTMLSpanElement][object Text][object HTMLSpanElement]`. This occurs reliably.

<img width="450" alt="Screenshot_2022-03-03 12 10 03" src="https://user-images.githubusercontent.com/25517624/156615379-d7533b22-ecdb-46b8-a0ee-3bd909f82b4d.png">

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [x] Console errors, if any

**Comment by kidonng** [comment]
Could you please test if it's `linkify-branch-references` misbehaving? If so we are going to disable this minor feature.

**Comment by j-f1** [comment]
Confirmed not to repro with `linkify-branch-references` disabled on Safari

**Comment by j-f1** [comment]
I figured out the issue: `dom-chef` checks `child instanceof Node` for child elements, but for some reason, the `Node` global has a different identity than the `Node` from which all nodes in the document inherit.

**Comment by cheap-glitch** [comment]
> but for some reason, the `Node` global has a different identity than the `Node` from which all nodes in the document inherit.

Is this a Safari bug? I couldn't reproduce the screenshot on Firefox.

**Comment by fregante** [comment]
Can't replicate in Safari 15.3 either. 

Welp, this piece of code is probably the issue:

https://github.com/vadimdemedes/dom-chef/blob/bbce2f9947e57ba0675e51fd5a141dcc516e43f6/index.ts#L102-L111

Maybe the extension sandboxing in 15.4 is broken and `x instanceof Node` fails because it comes from a different realm. 🤷‍♂️ 🤦‍♂️ let's hope they fix it

**Comment by fregante** [comment]
Can you try again today with the final 15.4 version?

**Comment by j-f1** [comment]
Safari 15.4 final seems to work fine on macOS 12.3, but I’m still seeing this issue in STP 141. Will try again when 142 comes out — that may be happening this Thursday.

**Comment by fregante** [comment]
This seems to be a browser bug. Ping us if you see it outside of a beta version

**Comment by j-f1** [comment]
Also seems to be fixed in the latest Safari + Safari Tech Preview.
