### ISSUE TITLE
Rebase by default / Disable Merge

### ISSUE THREAD

**Issue by tzaitsev-rl** [refined-github/refined-github#5467]
### Description

With the release of https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/

If there was a way to default to "Rebase Branch" -> "Update with Rebase"?

That would save a lot of accidental "Update Branch" -> "Update with merge commit".

This mode often puts a merge commit into the branch, which is not preferred. 

As a workaround, we've written a linter to check for merges but that still wastes time for developers.

If defaulting is less preferred than outright removing it (or giving more options), disabling/removing  "Update Branch" -> "Update with merge commit" would be fantastic.

### Screenshot

<img width="159" alt="image" src="https://user-images.githubusercontent.com/56273562/156903547-7233fa7a-ea9b-4a41-86a3-20dca35f8478.png">

<img width="285" alt="image" src="https://user-images.githubusercontent.com/56273562/156903540-2473e398-66f9-4e6f-96b6-76442f1ceb60.png">

### Proposal / Request

<img width="257" alt="Image 2022-03-05 at 3 54 27 PM" src="https://user-images.githubusercontent.com/56273562/156903580-b9d36a0e-7715-42af-a010-c558da77f31a.png">

### Example URL

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
> This mode often puts a merge commit into the branch, which is not preferred.

That's just a preference. We can't change this default because everyone has a different way of doing things. For me the merge commits in the PRs are easier and in the end every PR is squashed anyway, so the presence of merge commits in it isn't a problem. 

Again, it's a preference, so we can't change it as a default in Refined GitHub

**Comment by tzaitsev-rl** [comment]
I'll concede the preference, with some of the customization that refined-github offers, my intent was to see if it could be a flag that could enable this functionality. Feel free to close if it's not in scope!

**Comment by fregante** [comment]
That's understandable, but we only have enabled-by-default features

https://github.com/refined-github/refined-github/issues/2960#issuecomment-606765382
