### ISSUE TITLE
GitHub bug: "Go to file" leads to encoded URL

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5470]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github/find/main

### Extension version

22.3.3

### Browser(s) used

Chrome

### Description

Not actually RGH bug, but affects RGH.

The native "Go to file" feature now leads to URL encoded file paths, prevent some features like `rgh-feature-descriptions` to work.

```ts
// https://github.githubassets.com/assets/app/assets/modules/github/repositories/tree-finder.ts
virtualList.addEventListener('virtual-list-render-item', (event: Event) => {
    if (!(event instanceof CustomEvent)) return
    const frag = new TemplateInstance(template, {
      item: event.detail.item,
      id: `entry-${Math.random().toString().substr(2, 5)}`,
      urlEncodedItem: encodeURIComponent(event.detail.item)
    })
    const marker = frag.querySelector<MarkedTextElement>('marked-text')
    if (marker) marker.positions = positions
    event.detail.fragment.append(frag)
  })
```

Maybe we can add a feature to "normalize" these paths, could even bring https://github.com/refined-github/refined-github/issues/5326#issuecomment-1018560216 in.

Implementation I can think of: create a hidden PJAX link that links to the normalized path, then click it to trigger PJAX navigation (or probably just do a hard refresh?).

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by SuperSandro2000** [comment]
This would be really great to have. I often copy the paths from the GitHub URL and needing to HTML decode them first is a pain.

**Comment by kidonng** [comment]
You can use command palette for the moment.

**Comment by fregante** [comment]
Two fixes:

- immediately fix the URL on load, without any waiting/init logic. I'm sure the bug is temporary anyway. This should be early enough that fixes not only all of our features but other extensions too, as well as the user's URL bar
- add support for such URLs into our detection and parsers (probably troublesome)

**Comment by fregante** [comment]
Not a bug report, so we shouldn't use the bug template

**Comment by kidonng** [comment]
> But fixing I mean using history.replaceState to drop the encoding

That won't work since almost everything listens to `pjax:*` instead of `popstate`.

**Comment by kidonng** [comment]
Seems like GitHub resolved this by replacing `encodeURIComponent()` with this:

```ts
// Encode list item for URL accounting for '/' for items that are paths
function urlEncodeItem(itemName: string) {
  return encodeURIComponent(itemName).replaceAll('%2F', '/')
}
```

**Comment by fregante** [comment]
What are they even doing… why are they encoding URLs on the client? Why isn't the server sending correct URLs to begin with? 🤦‍♂️
