### ISSUE TITLE
Automatically make /pulls use `sort:updated-desc`

### ISSUE THREAD

**Issue by Milo123459** [refined-github/refined-github#5476]
### Description

Currently, if you go to https://github.com/rust-lang/rust/pulls it won't sort using `sort:updated-desc`. It would be cool if it automatically applied that, as I sometimes like to type out that URL.

### Example URL

https://github.com/rust-lang/rust/pulls

**Comment by yakov116** [comment]
Cannot reproduce.

Are you sure you have the extension on? Did you disable any options?

**Comment by Milo123459** [comment]
Go [here](https://github.com/rust-lang/rust/pulls) and it won't have the filter.

**Comment by yakov116** [comment]
> Go [here](https://github.com/rust-lang/rust/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) and it won't have the filter.

Cannot reproduce.

**Comment by Milo123459** [comment]
So when you go there, it automatically applies the filter?

**Comment by Milo123459** [comment]
This happens on a stock installation of refined-github, btw.

**Comment by yakov116** [comment]
Do you have any options disabled?

**Comment by Milo123459** [comment]
> Do you have any options disabled?

Like I said, stock installation - I haven't changed a thing,

**Comment by yakov116** [comment]
Browser?

**Comment by Milo123459** [comment]
Google Chrome.

**Comment by yakov116** [comment]
Please double check you have `sort-conversations-by-update-time` enabled.

Otherwise 🤷

**Comment by Milo123459** [comment]
<img width="364" alt="image" src="https://user-images.githubusercontent.com/50248166/157552632-7f4aaa56-fbdb-41f0-a3c0-87aa1aeb2661.png">

**Comment by fregante** [comment]
If you copy paste the URL or follow it from outside GitHub, we can't do anything about it. If you just click the link here it should work. 

That's because we only change links on the page, unfortunately we can't change the request while it's being made, and sorting results requires making a specific request.
