### ISSUE TITLE
It hides all files of repo and breaks code navigation 

### ISSUE THREAD

**Issue by Ashtonian** [refined-github/refined-github#5481]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github
![image](https://user-images.githubusercontent.com/4212452/157954473-dff69d62-d455-405b-9b2a-ac2bac0d8c2b.png)

### Extension version

22.3.3

### Browser(s) used

Brave

### Description

Can't see files listed on a github repo as seen in screen shot. It seems to be an issue loading fonts. 

![image](https://user-images.githubusercontent.com/4212452/157954953-39f5c1a2-04a6-4bcd-a4f4-ae37e603fe13.png)

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by cheap-glitch** [comment]
> Can't see files listed on a github repo as seen in screen shot

You can toggle the files list with this button:

![image](https://user-images.githubusercontent.com/46634000/157985692-f49eeda0-d9ce-44a1-956a-cfa7c60d34b6.png)

**Comment by fregante** [comment]
@Ashtonian It looks like you used `toggle-files-button` and the feature remembers the last state it was on. To fix it, click the button again.

- https://github.com/refined-github/refined-github/issues/3588
