### ISSUE TITLE
`reaction-avatars` doesn't work on Discussions

### ISSUE THREAD

**Issue by Milo123459** [refined-github/refined-github#5485]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/github/feedback/discussions/11202

### Extension version

22.3.3

### Browser(s) used

Chrome 99.0.4844.51

### Description

Reaction avatars isn't working on discussions.

<details>
<summary>Console error</summary>

```
Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': '[alt="@
  
          👎
          1

"]' is not a valid selector.
    at select_dom_select (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:1764:119)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:6529:77
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:6544:8
    at Array.map (<anonymous>)
    at showAvatarsOn (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:6525:90)
    at IntersectionObserver.rootMargin (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:6557:63)
```
</details>

Screenshot

<img width="391" alt="image" src="https://user-images.githubusercontent.com/50248166/158013755-d40c1de4-224a-403e-958b-cf57d2f0e3aa.png">

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by fregante** [comment]
It seems to work partially. No avatars on the top posts, but I see them on the comments

**Comment by Milo123459** [comment]
Yeah, same happening here.

**Comment by cheap-glitch** [comment]
Fixing the console error is easy enough, but for some reason the avatars added to the reactions on the first comment don't appear in the DOM, like they're immediately nuked by GitHub or something.

Also reactions are really buggy on Discussions (this is with RGH disabled):

https://user-images.githubusercontent.com/46634000/158058802-07172479-4f2a-4ca1-b3e0-f73b8b94068f.mp4

**Comment by fregante** [comment]
The new selector observer is probably a good candidate to fix this issue and drop `onNewComments` on this feature.

**Comment by fregante** [comment]
I think GitHub changed the selectors again because the feature is completely missing from discussions now, including on 22.9.9
