### ISSUE TITLE
`latest-tag-button` always shows "you're on the latest version"

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5504]
### Example URLs

https://github.com/refined-github/refined-github

### Extension version

latest on main today

### Browser(s) used

Chrome 99, Safari 15.4

### Description

@cheap-glitch @kidonng  definitely not working for me even in Chrome with a recent build and clean cache:

<img width="523" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/158322050-29e44959-af79-45a7-9192-f8a855a43c74.png">

Hopefully this is fixed before the next release or I'll have to revert:

- https://github.com/refined-github/refined-github/pull/5462
- https://github.com/refined-github/refined-github/pull/5365

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by cheap-glitch** [comment]
Found the bug, opening a PR now!
