### ISSUE TITLE
Comma between tags is inside inline code box, instead of between boxes

### ISSUE THREAD

**Issue by jakebailey** [refined-github/refined-github#5511]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/jakebailey/pyright-action/commits/v1.0.4

### Extension version

22.3.3

### Browser(s) used

Chrome

### Description

Have two tags on the same commit, like:

![image](https://user-images.githubusercontent.com/5341706/158429572-7e8fd1d2-b17d-479a-b366-5712e98f1bee.png)

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by fregante** [comment]
This already works correctly, you'll see the fix in the next release

Latest release

<img width="484" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/158529197-8f7b0f63-1d0e-4b43-99bd-2d62eb4407ad.png">

Unreleased version:

<img width="455" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/158529280-a73254e7-0897-46aa-9f18-2272b043b1f7.png">


Tested on https://github.com/fregante/daily-version-action/commits/master

**Comment by jakebailey** [comment]
Thanks; I can see that it was fixed in #5416.
