### ISSUE TITLE
`git-checkout-pr`: Add option to specify custom URLs

### ISSUE THREAD

**Issue by AlCalzone** [refined-github/refined-github#5513]
### Description

The feature currently adds a fixed description how to checkout a PR locally. I'm often working with Gitpod (a hosted dev environment) and while they have an option to comment on PRs with links to the checkout, this is very noisy for contributors.

I think the `git-checkout-pr` feature would be a great opportunity to add user-defined custom checkout links. This could be done in a generic way by specifying a label and an URL template, e.g.
```
label: Open in Gitpod
url: https://gitpod.io/#/<url>
```
where `<url>` would be replaced by the URL of the current PR. Other placeholders could be `owner`, `repo`, `pull_number`, ...

### Screenshot

Quick and dirty mockup:
![Unbenannt-1](https://user-images.githubusercontent.com/17641229/158612529-83f4e488-804c-4364-bf10-341ca1ccd0fe.png)

### Example URL

Any PR page on Github. The clone/download button on each repo's front page could be a good match too.

**Comment by yakov116** [comment]
This would go against https://github.com/refined-github/refined-github/issues/2960#issuecomment-606765658

**Comment by AlCalzone** [comment]
You're right :(
