### ISSUE TITLE
Release notes are a bit messy

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5516]
A while ago the release notes were good out of the box, but today we didn't even get a bugfixes section. Did we break it?

Here's the generated notes, I already fixed the [official notes](https://github.com/refined-github/refined-github/releases/tag/22.3.17) and you can see the difference.

---

### New
* Add `link-to-compare-diff` feature by @cheap-glitch in [#5458](https://github.com/refined-github/refined-github/pull/5458)
* Add `sticky-file-header` feature by @kidonng in [#5460](https://github.com/refined-github/refined-github/pull/5460)
* Improve progress UI for `deep-reblame` by @fregante in [#5490](https://github.com/refined-github/refined-github/pull/5490)
* Make Debugging section more prominent in the options by @fregante in [#5489](https://github.com/refined-github/refined-github/pull/5489)
* Restyle two tag-related features by @kidonng in [#5416](https://github.com/refined-github/refined-github/pull/5416)
* Exclude disabled features from "Find feature" wizard by @fregante in [#5497](https://github.com/refined-github/refined-github/pull/5497)
* Make Options page scrollbar dark in Chrome by @rakleed in [#5478](https://github.com/refined-github/refined-github/pull/5478)
* GitHub bug: Avoid overflow caused by the diff signs by @fregante in [#5506](https://github.com/refined-github/refined-github/pull/5506)
* Refactor `conversation-activity-filter` by @kidonng in [#5415](https://github.com/refined-github/refined-github/pull/5415)
* Fix alignment of "Allow edits by maintainers" checkbox by @cheap-glitch in [#5510](https://github.com/refined-github/refined-github/pull/5510)
* Dim more PRs opened by bots in `dim-bots` by @cheap-glitch in [#5512](https://github.com/refined-github/refined-github/pull/5512)
### Changes
* Drop reactions spacing fix by @cheap-glitch in [#5463](https://github.com/refined-github/refined-github/pull/5463)
* Fix `latest-tag-button` at repo home on tagged default branch by @cheap-glitch in [#5462](https://github.com/refined-github/refined-github/pull/5462)
* Fix top alignment of PR sidebar in `clean-conversation-sidebar` by @cheap-glitch in [#5469](https://github.com/refined-github/refined-github/pull/5469)
* Fix `pull-request-hotkey` feature by @cheap-glitch in [#5473](https://github.com/refined-github/refined-github/pull/5473)
* Don't override the PR title and body provided via URL parameters by @fregante in [#5495](https://github.com/refined-github/refined-github/pull/5495)
* Fix GitHub Safari bug: Horizontal scrollbars on Action logs by @fregante in [#5487](https://github.com/refined-github/refined-github/pull/5487)
* Ensure custom CSS is added *after* the extension CSS by @fregante in [#5493](https://github.com/refined-github/refined-github/pull/5493)
* Don't apply `shorten-links` to links in code blocks by @cheap-glitch in [#5472](https://github.com/refined-github/refined-github/pull/5472)
* Fix repo tab menu overflow due to `releases-tab` and `bugs-tab` by @fregante in [#5499](https://github.com/refined-github/refined-github/pull/5499)
* Avoid extra scrollbars in `scrollable-code-and-blockquote` by @fregante in [#5509](https://github.com/refined-github/refined-github/pull/5509)
* Fix `latest-tag-button` on branch ahead by more than 20 commits by @cheap-glitch in [#5505](https://github.com/refined-github/refined-github/pull/5505)
* Drop `fix-first-tab-length` feature by @fregante in [#5508](https://github.com/refined-github/refined-github/pull/5508)
* Include but skip inert URL segments in `useful-not-found-page` by @fregante in [#5496](https://github.com/refined-github/refined-github/pull/5496)
* Reliability fixes for `fork-source-link-same-view` by @fregante in [#5494](https://github.com/refined-github/refined-github/pull/5494)

## New Contributors
* @rakleed made their first contribution in [#5478](https://github.com/refined-github/refined-github/pull/5478)

**Full Changelog**: https://github.com/refined-github/refined-github/compare/22.3.3...22.3.17

**Comment by fregante** [comment]
> Did we break it?

Yes: `*` captures all

https://github.com/refined-github/refined-github/blob/c68a143504210033f8973d37a3d0021e3deadcba/.github/release.yml#L10-L15

**Comment by darkred** [comment]
@fregante Sorry about this issue, I didn't realize that `*` captures all. Thank you for fixing this!

**Comment by fregante** [comment]
No worries, me neither
