### ISSUE TITLE
`resolve-conflicts` is broken in latest release

### ISSUE THREAD

**Issue by cheap-glitch** [refined-github/refined-github#5520]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github/pull/5422/conflicts

### Extension version

22.3.17

### Browser(s) used

Firefox

### Description

The `resolve-conflicts` feature doesn't work in the latest RGH version. I get the following error in Firefox, as if the script was missing from the published bundle:

```
Loading failed for the <script> with source “moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/build/resolve-conflicts.js”. conflicts:1:1
```

It works perfectly fine in the dev version, so it's likely there was an issue with the latest release.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by fregante** [comment]
Argh we'll have to release a new one tomorrow. This is due to my Safari PR
