### ISSUE TITLE
Cancel button in `sync-pr-commit-title` sometimes not stopping sync after squash and merge

### ISSUE THREAD

**Issue by FloEdelmann** [refined-github/refined-github#5528]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://togithub.com/OpenLightingProject/open-fixture-library/pull/2488

### Extension version

22.3.18

### Browser(s) used

Firefox

### Description

1. Start squash and merge
2. Change the commit message
3. Click "cancel" to prevent syncing the PR title (the cancel link and text are hidden as expected)
4. Manually clear the commit description (maybe relevant)
5. Squash and merge
6. See that the PR title is updated anyway :frowning_face: 

I could not reproduce this when retrying in [another issue](https://togithub.com/OpenLightingProject/open-fixture-library/pull/2489) with reloading before step 1. Maybe it's also because I didn't clear the commit description there.

The browser doesn't show any errors.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by FloEdelmann** [comment]
I could not reproduce this in https://togithub.com/OpenLightingProject/open-fixture-library/pull/2490 without reloading, and with commit description clearing. So maybe clearing the extension cache may have fixed it?

**Comment by FloEdelmann** [comment]
It's not `updateCommitTitle` that's inappropriately being called, but `updatePRTitle`. I can try reproducing with the current `main` version, but it'll be difficult to conclude because it can't be reproduced reliably.

**Comment by cheap-glitch** [comment]
My bad, I read too quickly. But I don't think the cache has anything to do with it, since the feature never relies on it.

**Comment by yakov116** [comment]
https://github.blog/changelog/2022-05-11-default-to-pr-titles-for-squash-merge-commit-messages/

**Comment by FloEdelmann** [comment]
Since I didn't notice the problem mentioned in this issue anymore, I guess the issue can be closed.

@yakov116 That's interesting, but only tangentially related to this issue (since this issue is about the PR title being updated from a custom squash commit message, not the commit message defaulting to the PR title). Please open a new issue if anything should be done by RGH in response to GitHub's new feature.
