### ISSUE TITLE
`clean-dashboard` doesn't look right on new dashboard

### ISSUE THREAD

**Issue by mal-tee** [refined-github/refined-github#5530]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/

### Extension version

22.3.18

### Browser(s) used

Firefox 98.0.1

### Description

Seems like `clean-dashboard` breaks the new dashboard.

with `clean-dashboard`: 

![grafik](https://user-images.githubusercontent.com/45886910/159369066-7d43cbbd-272b-4a49-b93f-5ed23673e272.png)

without:

![grafik](https://user-images.githubusercontent.com/45886910/159369220-f2668ebe-4c83-4f53-a892-29e88e8284c5.png)

(I've used the devtools to change the user and repo name.)

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [x] Console errors, if any

**Comment by kidonng** [comment]
You know what, I have thought about hiding the duplicate repository name for a while...

But this is the other way around 😅

**Comment by fregante** [comment]
Oh, right, this is correct. The broken part is that we normally hide the cards themselves. Refer to the screenshot
