### ISSUE TITLE
`align-issue-labels` is broken

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5532]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github/issues

### Extension version

22.3.18

### Browser(s) used

Chrome

### Description

Does not do what it says on the tin.

<img width="507" alt="image" src="https://user-images.githubusercontent.com/44045911/159392219-3ebf2150-6033-407d-97de-811c6103de97.png">

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by kidonng** [comment]
I'm not sure, something is off, `clean-conversation-headers` is also misbehaving:

<img width="365" alt="image" src="https://user-images.githubusercontent.com/44045911/159392711-772e8b2d-d6dd-4a71-86dd-9b465fc153f5.png">

**Comment by fregante** [comment]
It doesn't misalign them, it's just broken. The feature move them from the current position to the left side, on a new line

**Comment by fregante** [comment]
Easy fix, will also hotfix
