### ISSUE TITLE
Duplicate `quick-comment-edit` button

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5536]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com//refined-github/refined-github/pull/5533#issuecomment-1074671507

### Extension version

22.3.18 (precisely, latest commit: 1a7af8e2)

### Browser(s) used

Chrome

### Description

✏️✏️✏️✏️✏️✏️✏️

No console error, may related to recently merged dedup PR.

<img width="833" alt="image" src="https://user-images.githubusercontent.com/44045911/159398689-79df32c9-f048-4db1-9e84-b08380082d22.png">

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by kidonng** [comment]
Just happened again, now in the automatically fetched comment:

https://github.com//refined-github/refined-github/pull/5535#issuecomment-1074677895

<img width="829" alt="image" src="https://user-images.githubusercontent.com/44045911/159400482-126ceec2-d88a-4c20-afa5-dd7ee52e8c06.png">

**Comment by kidonng** [comment]
Just noticed I have both the store version and dev version enabled. But shouldn't one of them bail out when they see `.refined-github`?

**Comment by fregante** [comment]
It already does, see the console message
