### ISSUE TITLE
Show repository avatars in header

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5546]
### Description

You probably have seen it in many places: dashboard, mobile apps, and the new hot "For you" feed:

<img width="689" alt="image" src="https://user-images.githubusercontent.com/44045911/159872688-ef18bd4e-ba33-4cae-a16a-c952633381f7.png">

It's not really _repository_ avatars like on e.g. GitLab, just the avatar of the user/organization the repo belongs to. But still, a nice thing to see more.

I propose we also put an avatar in the repository header (which is available now [via my userscript](https://github.com/kidonng/cherry/tree/cc877cce26eb469e132dab37ff6c5482b9387c21/scripts#github-repository-avatars)):

![](https://github.com/kidonng/cherry/raw/master/screenshots/github-repository-avatars.png)

Feeling familiar? Because you've probably seen similar design [elsewhere](https://gist.github.com/sindresorhus/a4706e81fbac24b5380a0d6d6bfb584e):

<img width="392" alt="image" src="https://user-images.githubusercontent.com/44045911/159873505-17a4b1ae-0366-473e-ad58-d8dc94882cdc.png">

### FAQ

- **Where would this take effect?**

  Public repositories, that is not template/fork/etc.

  In other words, we only replace the vanilla repo icon with a more awesome avatar, which should benefit most repos. We don't want to take away other unique icons that distinguish the status of the repository, especially since we already hide the label.

  Alternatively, we can _prepend_ the avatar to the icon, which will make it suitable for all repositories, though it would not look great.

- **Why not propose to GitHub?**

  _cough_ we are more flexible than their roadmap. _cough_ And seeing this only applied to some places (a.k.a. inconsistencies), I don't see how will GitHub implement this.

- **You know [the first rule](https://github.com/refined-github/refined-github/issues/2960#issuecomment-606764895) right?**

  Because I already _planned_ to to propose it to Refined GitHub. This applies to most of my other user scripts/styles posted here.

### Example URL

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
I like it, as long as keep the "public" label on the right since we've been using the repo icon as an excuse for that feature.

<img width="438" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/166138848-796239d6-cc87-4e40-a6ff-5a194d5b36e5.png">

**Comment by cheap-glitch** [comment]
> But… did we drop it already? I'm seeing the label again

Not, it hasn't been dropped. Maybe you disabled the `hide-repo-badges` feature?

**Comment by fregante** [comment]
Not that I recall. I'm on Safari though, buggy feature?

**Comment by cheap-glitch** [comment]
> I'm on Safari though

Then you're on `22.4.1`, which doesn't have https://togithub.com/refined-github/refined-github/pull/5583

**Comment by kidonng** [comment]
Released in [22.7.7](https://github.com/refined-github/refined-github/releases/tag/22.7.7) 🤞 hopefully well-received

**Comment by kidonng** [comment]
It's intentionally following the style of avatars in org profiles and hovercards:

https://github.com/refined-github/refined-github/blob/894f517a994602e17c84a99c15ea68dba48e7293/source/features/repo-avatars.tsx#L29-L31

**Comment by fregante** [comment]
By the way, `hide-repo-badges` is definitely broken for me in Safari 22.7.1 and Chrome 22.7.7

<img width="435" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/1402241/177793928-1b7798b4-22dc-4098-92c1-99d74c113585.png">

<img width="417" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/1402241/177793915-12f11b4e-e3d4-4a7b-b93e-14781cfe6c15.png">

But:



> I like it, as long as keep the "public" label on the right since we've been using the repo icon as an excuse for that feature.

So we should probably drop the feature

**Comment by cheap-glitch** [comment]
How about making the avatar a link to the corresponding profile? I know there's the user/org name right next to it, but I've caught myself clicking the avatar a few times, expecting to be redirected to the profile :sweat_smile: 

Plus it would match with others avatar on GitHub, most of which are links to the user profile.
