### ISSUE TITLE
Make `avoid-accidental-submissions` very cautious

### ISSUE THREAD

**Issue by PAI5REECHO** [refined-github/refined-github#5550]
### Description

Single <kbd>Enter</kbd> & double <kbd>Enter</kbd> for issue titles, <kbd>Ctrl</kbd> + <kbd>Enter</kbd>, or even just clicking the submit button normally are all too easy to do accidentally. I'd like `avoid-accidental-submissions` to remove the single <kbd>Enter</kbd> & double <kbd>Enter</kbd> shortcuts when you're editing the title altogether. Sure they're acceptable kinds of keyboard shortcuts for things like instant messaging apps, but when authoring a comment or issue on GitHub the experience should be closer to typing a formal E-Mail. I don't want to submit anything without deliberate confirmation.

Instead, I'd like <kbd>Enter</kbd> when your typing focus is in the issue title to just be the same as <kbd>Tab</kbd> so it changes typing focus to the body (remove all forms of submission with just the <kbd>Enter</kbd> alone). Then in addition to that completely block all forms of single action submission. That's kinda what I was hoping `avoid-accidental-submissions` would do in the first place. Ideally I'd like it to ask twice for any type of submission using a `confirm()` pop-up in the same way some websites ask you "are you sure you want to leave without saving?". This should apply even if I hit the `Submit ...` button with my mouse cursor.

### Example URL

https://github.com/refined-github/refined-github/issues

**Comment by cheap-glitch** [comment]
> but when authoring a comment or issue on GitHub the experience should be closer to typing a formal E-Mail

But unlike e-mails, you can very easily edit pretty much anything you post on GitHub. I don't really see the use of such a comprehensive safety net.

> Ideally I'd like it to ask twice for any type of submission using a `confirm()` pop-up

:scream:

**Comment by fregante** [comment]
> Enter when your typing focus is in the issue title to just be the same as Tab so it changes typing focus to the body

Ironically that's how the feature behaved until I [requested a change](https://github.com/refined-github/refined-github/issues/4462). You can read that to see why it's not a good idea.

I think the feature in its current state is relatively good, we have to strike a balance between being useful and being annoying.

**Comment by PAI5REECHO** [comment]
I guess I'll have to take the userscript route for this one then
