### ISSUE TITLE
Highlight PRs which require a review from you

### ISSUE THREAD

**Issue by AlexDaniel** [refined-github/refined-github#5551]
### Description

In our team, for some PRs, reviews can be requested from specific people. When looking at the list of PRs there is no easy way to tell if anybody is waiting for your review.

### Screenshot

![160559591-76fb33ab-e268-4a85-be6b-904955d7af48](https://user-images.githubusercontent.com/5507503/160559842-7a9bb1bd-d49e-429d-b378-edc89b963453.png)

Not sure what is the best wording, maybe it should say “Awaiting review from you” to match the similarly named filter:
![image](https://user-images.githubusercontent.com/5507503/160560487-f02c0a2b-9ba3-4324-a1e5-1bf9d5041a76.png)

And yes, that filter exists, but it requires two additional clicks each time for something that should be always visually indicated.

### Example URL

https://github.com/refined-github/refined-github/pulls

**Comment by cheap-glitch** [comment]
This might be useful info, but if a similar result can be achieved via a built-in filter, it doesn't seem worth adding to an already overcrowded list (see https://github.com/refined-github/refined-github/issues/5380).

That said I'm not against it on principle :man_shrugging:

**Comment by AlexDaniel** [comment]
I wouldn't call it a similar result. When looking at the list of pull requests, I'd like to know if there are any PRs where my action is required. For example, if there was my pull request where somebody requested changes, I need to do something about that PR. Same goes for PRs where my review was requested – I need to go to these PRs and do a review. That's not some kind of filter that is applied from time to time, it's a daily operation that currently requires two separate tabs to be open, or clicking two times to switch between the filters, all the time.

**Comment by fregante** [comment]
We'll keep it in mind but I think we're not going to add more information to the already-busy PR list

**Comment by AlexDaniel** [comment]
That's extremely disappointing because the feature doesn't even add any information to the already-busy list in the vast majority of cases. It only adds a label if somebody is actively waiting a review from you, which is essential information that of course needs to be visible without any extra steps. Meanwhile coworkers came up with some half-working greasemonkey contraption and are using it (even though it doesn't support team assignments and other more specific cases). Whatever. 😞
