### ISSUE TITLE
`sticky-sidebar`: `ResizeObserver.updateStickiness` ajax error in console

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5552]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github

### Extension version

Latest on main, almost 22.4.1

### Browser(s) used

Chrome 99

### Description

```
Uncaught TypeError: Cannot read properties of undefined (reading 'classList')
    at ResizeObserver.updateStickiness (refined-github.js:14560:11)
    at later (refined-github.js:23438:28)
```

Repro:

1. Go to https://github.com/refined-github/refined-github
2. Click on Compare link
3. 
<img width="431" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/160598741-e37d45b6-7033-4307-b7cf-a3ac06d509a1.png">

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [x] Console errors, if any

**Comment by cheap-glitch** [comment]
Probably due to #5422

**Comment by fregante** [comment]
I can reproduce consistently, it's likely in `sticky-repo-sidebar` because it happens when leaving the repo home
