### ISSUE TITLE
Labels on notifications if they exist

### ISSUE THREAD

**Issue by kylemh** [refined-github/refined-github#5554]
### Description

It'd be cool if a notification would render any attached labels if they exist (for PRs and issues)

### Example URL

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
> ### Example URL
> [refined-github/refined-github](https://github.com/refined-github/refined-github)

There are no notifications on this page

**Comment by kylemh** [comment]
I meant this as a feature request for the notifications page.
<img width="1426" alt="Screen Shot 2022-08-05 at 1 55 30 PM" src="https://user-images.githubusercontent.com/9523719/183081753-3ccdde4b-a357-40ae-88d4-0eab5eb6034d.png">

In other words, for this notification, I'd love to see: "enhancement" and "under discussion" in the actual notification.

**Comment by cheap-glitch** [comment]
I think this was requested and rejected before, but I couldn't find the issue. Either way, I don't think this is possible because it would necessitate too many API requests.

**Comment by kylemh** [comment]
Appreciate the insight!
