### ISSUE TITLE
Keyboard shortcuts for navigating between commits in a review don't work

### ISSUE THREAD

**Issue by ewjoachim** [refined-github/refined-github#5555]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github/pull/5549/commits/465ee726b5681abc6e0550b9b31c7ab7aa49feae (works on any repo)

### Extension version

22.3.18

### Browser(s) used

Firefox 98

### Description

Without Refined GitHub, when looking at an individual commit in a PR, hitting `n` and `p` on the keyboard goes to the next/previous commit.

With Refined GitHub enabled, it doesn't work.

I've tried using the feature identifier within Refined GitHub to pinpoint the culprit, but when in feature detection, the issue disappears completely (which points [`warning-for-disallow-edits`](https://github.com/refined-github/refined-github/blob/main/source/features/warning-for-disallow-edits.tsx) and I'm not really sure it's related as it seems it's mainly so because it's the last one in the list)

No error in the JS console.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by ewjoachim** [comment]
Woo, nice ticket number. Sharing [Daft Punk](https://en.wikipedia.org/wiki/Interstella_5555:_The_5tory_of_the_5ecret_5tar_5ystem) vibes :musical_note: :robot:

**Comment by cheap-glitch** [comment]
On my machine, <kbd>p</kbd> works wether RGH is enabled or not, and <kbd>n</kbd> never works.

Seems to me like another case of [GitHub's keyboard shortcuts being completely broken](https://github.com/github/feedback/discussions/13399).

**Comment by cheap-glitch** [comment]
> maybe the n/p data-hotkey elements are somehow either being dropped or overridden by something else

Actually, it seems there's no `data-hotkey` elements for p/n:

```
>> [...$$('[data-hotkey]')].map(el => { console.log(el.dataset.hotkey); })
g d
s,/
g p
g i
g d
g n
g c
g i
g p
g a
g s
g r
.
Shift+.,Shift+>,>
g 1,g ArrowLeft
g 2
g 3,g ArrowRight
g 4
t
c
d w
Control+b
Control+i
Control+Shift+.
Control+e
Control+k
Control+Shift+8
Control+Shift+7
Control+Shift+l
Control+b
Control+i
Control+Shift+8
Control+Shift+7
Control+Shift+l
ArrowLeft
ArrowRight
ArrowLeft
ArrowRight
i
a
g m
```

So it's either a specific feature or the deduplication mechanism that interferes with a native listener somewhere.

**Comment by fregante** [comment]
It's `pagination-hotkey` 🙂 (found via bisect 🎉)

**Comment by ewjoachim** [comment]
Thanks :) https://www.buymeacoffee.com/fregante/c/3335911

**Comment by fregante** [comment]
Merci beaucoup Mssr. Jablon 🍕
