### ISSUE TITLE
'End' Key should jump cursor to the end of the current comment line, not scroll to the bottom of the page

### ISSUE THREAD

**Issue by JLLeitschuh** [refined-github/refined-github#5556]
### Description

Currently, when working on a large PR leaving a comment, if you hit the 'End' key on the keyboard the browser window scrolls to the bottom of the page.

This is completely inconsistent with most modern IDEs (IJ, VScode, ect..) where the 'End' key moves your cursor to the end of the line you're currently typing.

You can reproduce this on any large PR. Attempt to leave an inline comment on a bit of code, then hit the 'End' key, your view will scroll to the bottom of page instead of moving your cursor.

### Example URL

https://github.com/refined-github/refined-github/pull/5322/files

**Comment by cheap-glitch** [comment]
> Attempt to leave an inline comment on a bit of code, then hit the 'End' key, your view will scroll to the bottom of page instead of moving your cursor.

By "inline comment", do you mean a review? Because the `End` key works fine for me on Firefox.

**Comment by JLLeitschuh** [comment]
> By "inline comment", do you mean a review?

Yes.

Huh, I'm using chrome, I wonder if this is chrome specific?!
