### ISSUE TITLE
Disable animations such as Actions in-progress spinners

### ISSUE THREAD

**Issue by altendky** [refined-github/refined-github#5557]
### Description

For whatever reason the yellow in-progress spinners for CI jobs end up seriously loading up my CPU.  While 'slick', they seem entirely unnecessary and I would expect it would be easy to disable the CSS animation.  I'm no expert but this seems to be the `anim-rotate` class that could be modified to have the rotation removed.

Note that the link below will not actually show the yellow spinners since they would be gone by the time you looked at the page due to the jobs being finished.

Thanks for your consideration.

### Screenshot

![image](https://user-images.githubusercontent.com/543719/161187065-7abe2bff-8aa9-429b-8b28-8830a541cc17.png)

### Example URL

https://github.com/altendky/qtrio/actions/runs/1856982092

**Comment by altendky** [comment]
Or maybe I just blamed this for some reason instead of really finding what to blame for the cpu usage.  I'll do a bit of work there first, sorry for the noise.

**Comment by busches** [comment]
You can add some custom css using the extension to disable this as well.
