### ISSUE TITLE
`stop-pjax-loading-with-esc` stopped working 

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5561]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

This issue

### Extension version

22.4.1

### Browser(s) used

Safari 15.4

### Description

This feature doesn't seem to be working.

1. On this issue
2. Click the Issues tab
3. Notice the blue loading bar appear at the very top of the window (without causing the browser’s "Refresh" button to change)
4. Press <kbd>esc</kbd> multiple times
5. Notice how your actions are ignored and the universe turns into a meaningless collection of matter

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by cheap-glitch** [comment]
The feature is working fine, it's just being deinited… #5422 strikes again :upside_down_face:
