### ISSUE TITLE
Automatically redirect pull requests search without "is:pr" to issues

### ISSUE THREAD

**Issue by asmeurer** [refined-github/refined-github#5563]
### Description

If you search on the pull requests page and delete the "is:pr" from the search, it doesn't include issues. But if you do the same on the issues page and remove "is:issue", it does include pull requests. For example:

- Includes issues and PRs: https://github.com/refined-github/refined-github/issues?q=search+
- Includes only PRs: https://github.com/refined-github/refined-github/pulls?q=search

I think this is probably some bug in GitHub, but it seems to be something that would be quite simple for refined GitHub to fix with a simple redirect. 

### Example URL

https://github.com/refined-github/refined-github/pulls?q=search

**Comment by fregante** [comment]
This is something I thought about too because I encounter it often enough. 

I suppose our solution would something like be:

- on submit, if there's no is:pr or if there is is:issue, change the action attribute to /issues

**Comment by 134130** [comment]
I found the `location.href` is changed to `/issues` when changing form's action's path.
<img width="800" alt="image" src="https://github.com/refined-github/refined-github/assets/50487467/4f66a6de-f89c-45e6-8228-ec511ad85e85">
