### ISSUE TITLE
Compare two files that git doesn't recognize as a rename

### ISSUE THREAD

**Issue by jaredmcateer** [refined-github/refined-github#5564]
### Description

The particular use-case I'm encountering is migrating a JavaScript codebase to TypeScript and when there have been too many changes in a file git will no longer treat it like a rename but as a delete and add. We try to limit the amount of changes in a file to avoid this but sometimes, especially if the file is smaller, it's unavoidable without having multiple PRs which adds a bunch of administrative overhead to getting the work done.

I would like to see an option to select two files or even using some simple heuristics like seeing a delete and add with the file path being the same except the extension and then a way to compare them (perhaps by linking to an external tool).

### Screenshot

![image](https://user-images.githubusercontent.com/781540/161621606-6b8fad75-7c3d-4ec9-a55b-d6b8576b9723.png)

### Example URL

https://github.com/refined-github/refined-github/pull/5562/files

**Comment by fregante** [comment]
Unfortunately there's no way to ask GitHub to compare two unrelated files nor it's possible for us to reimplement the whole diff view. This would have to load its own diffing tool and thus be its own extension.
