### ISSUE TITLE
"Cannot read properties of undefined (reading 'cloneNode')"

### ISSUE THREAD

**Issue by RussKie** [refined-github/refined-github#5565]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/dotnet/winforms/pull/6878/files

### Extension version

22.4.1

### Browser(s) used

MS Edge, 100.0.1185.29 (Official build) (64-bit)

### Description

This looks similar to https://github.com/refined-github/refined-github/issues/4827.

![image](https://user-images.githubusercontent.com/4403806/161652625-6c89c548-72de-4347-a80f-b2cea35adfc3.png)

```
Uncaught TypeError: Cannot read properties of undefined (reading 'cloneNode')
    at add (refined-github.js:9975:171)
    at runAdd (refined-github.js:5494:40)
    at applyChanges (refined-github.js:5464:48)
    at SelectorObserver.addRootNodes (refined-github.js:5616:75)
    at Array.processBatchQueue (refined-github.js:5436:21)
    at MutationObserver.handleMutations (refined-github.js:5453:21)
```

I tried cleaning the cache, "Empty cache and hard refresh" but nothing helps.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by fregante** [comment]
Probably related:

- https://github.com/refined-github/refined-github/pull/5422#issuecomment-1087543560

Are you using other extensions? Does the error happen even if you disable them?

**Comment by RussKie** [comment]
I disabled all extensions, the errors is still here 

![image](https://user-images.githubusercontent.com/4403806/162084419-fddb4c89-b3e7-4df4-a0ce-7f0b8ac301e6.png)
![image](https://user-images.githubusercontent.com/4403806/162084404-2946166c-e604-4db2-90b3-5f47cf913f25.png)
