### ISSUE TITLE
How can I get back to showing all the files when visiting someone repo?

### ISSUE THREAD

**Issue by Sylenss** [refined-github/refined-github#5566]
When I'm visiting someones repo it only shows me the readme file, and I don't know where to find the other files. How can I revert the changes back to the old style that would show the files along with the readme file?
![CleanShot 2022-04-04 at 20 18 35@2x](https://user-images.githubusercontent.com/45975952/161654407-d657ff4a-82c1-48f0-9fcc-665fc5c1319d.png)

**Comment by busches** [comment]
Click the expand/collapse button next to the words commit.

https://user-images.githubusercontent.com/1402241/35480123-68b9af1a-043a-11e8-8934-3ead3cff8328.gif

**Comment by Sylenss** [comment]
Wow, I wasn't aware that, Thank you!
