### ISSUE TITLE
Exclude `highest-rated-comment` in `hide-low-quality-comments`

### ISSUE THREAD

**Issue by FloEdelmann** [refined-github/refined-github#5567]
In [facebook/jest#5311](https://togithub.com/facebook/jest/issues/5311), the `highest-rated-comment` is at the same time a low quality comment. So clicking the  "Jump to comment" link there doesn't work, because that comment is hidden.

![image](https://user-images.githubusercontent.com/202916/161590885-2b231913-9203-4017-8958-9f3f5f3dd832.png)

Either the highest rated comment should be excluded right from the start in `hide-low-quality-comments`, or clicking the "Jump to comment" link should make it appear.

_Originally posted by @FloEdelmann in https://github.com/refined-github/refined-github/issues/5334#issuecomment-1087776139_

**Comment by fregante** [comment]
Thanks for the report! The solution should be the opposite though:

- bad comments are not worthy of highlight, so they should be excluded from the `highest-rated-comment`
