### ISSUE TITLE
GHE Support is busted

### ISSUE THREAD

**Issue by busches** [refined-github/refined-github#5568]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

My Github Enterprise URL

### Extension version

22.4.1

### Browser(s) used

Chrome Version 100.0.4896.60 (Official Build) (x86_64) Mac

### Description

RGH says it's enabled on my domain, my domain appears in the options, but nothing is running. Activating the debug logging, logs nothing. Opening as I don't have time at this moment to resolve, but I'll make time to get this resolved as it's extremely annoying 🤣 

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by cheap-glitch** [comment]
Does this happens only on the latest release?

**Comment by fregante** [comment]
> nothing is running

Can't replicate. Latest version of everything, it successfully injects the script on Twitter

<img width="1124" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/161808929-0853fadf-5e6f-40b0-8aea-4c0f038bfc6d.png">

**Comment by busches** [comment]
Unsure if permissions were reset or what happened. I recreated it on another machine, but re-enabling for the domain fixed it. I did do that on the other computer as well, but I'll double check to ensure it's checked for `on this domain` and not `when I click the extension`. I swapped to the local build I had and everything started working, I'll investigate more tomorrow, ugh.

**Comment by fregante** [comment]
> I'll double check to ensure it's checked for on this domain and not when I click the extension. 

Right. That dropdown should never be touched for our GHE support though, it's only useful for you to debug the problem just in case *it was* touched.
