### ISSUE TITLE
Extension slow down GitHub Notifications search

### ISSUE THREAD

**Issue by andry81** [refined-github/refined-github#5569]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/notifications/beta?query=is%3Adone&query=is%3Adone+blabla

### Extension version

22.4.1

### Browser(s) used

Firefox 98.0.2

### Description

I have hundreds subscriptions in the Done page.
If try to search and type in the filter field a random word and press enter, then it freezes with the Firefox popup:

```
"Refined GitHub" is slowing down Firefox. To speed up your browser, stop that extension. ...
```

If press stop, then it continues to search results,

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by haoadoresorange** [comment]
Second, I just had this issue too.

**Comment by fregante** [comment]
FYI the banner may occasionally be wrong about the culprit. We can look into it though

**Comment by Oren-Lindsey** [comment]
this is happening to me too

**Comment by fregante** [comment]
Confirmed, it's likely getting stuck in a loop here:

https://github.com/refined-github/refined-github/blob/2ff6708a489f550878867ef9879b3a14644f1bc6/source/features/select-all-notifications-shortcut.tsx#L8-L11

I disabled `select-all-notifications-shortcut` for now so you shouldn't see this happening anymore (once your extension downloads the hotfix)

For a solution:

- maybe we should just listen to the shortcut regularly _and then_ click the checkbox with a regular `$(checkbox).click()` or something

**Comment by fregante** [comment]
We should do the same for any similarly-convoluted pieces of code, if any

**Comment by andry81** [comment]
> I disabled [select-all-notifications-shortcut](https://github.com/refined-github/refined-github/blob/main/source/features/select-all-notifications-shortcut.tsx) for now so you shouldn't see this happening anymore (once your extension downloads the hotfix)

I don't know what is happened, but it started to work without update.

**Comment by fregante** [comment]
> I don't know what is happened, but it started to work without update.

We have a hotfix mechanism that lets us disable troublesome features remotely, that's what happened 😉

**Comment by mwz** [comment]
hello, can the select-all-notifications feature be re-enabled now?
