### ISSUE TITLE
Multiple edit buttons due to `quick-comment-edit`

### ISSUE THREAD

**Issue by 4310V343k** [refined-github/refined-github#5572]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/TauCetiStation/TauCetiClassic/pull/7772

### Extension version

22.4.1

### Browser(s) used

Yandex.Browser

### Description

Sometimes, this happens
![](https://i.imgur.com/rqvje7q.png)

This is mostly inconsistent, but try to reload the example url multiple times and press the "Load more" button

Console:
![](https://i.imgur.com/lIVIt8e.png)

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by cheap-glitch** [comment]
Related: https://github.com/refined-github/refined-github/pull/5422#discussion_r841821958

**Comment by fregante** [comment]
Once fixed we'll release a hotfix since this issue is quite visible
