### ISSUE TITLE
`clean-conversation-headers` is unreliable

### ISSUE THREAD

**Issue by 4310V343k** [refined-github/refined-github#5573]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/TauCetiStation/TauCetiClassic/pull/7772

### Extension version

22.4.1

### Browser(s) used

Yandex.Browser

### Description

~~The line under the PR title is sometimes (every second or third reload) not compressed, and the conversation filter button does not appear because of that~~

After every second or third reload the line under the PR title just becomes normal after the whole page loads (it disappears right after the "Bugs" button is added)

![](https://i.imgur.com/nIumfrk.gif)

Should be: https://i.imgur.com/eQosD7q.png

Is: https://i.imgur.com/SVpDCCm.png

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by cheap-glitch** [comment]
This is probably due to GitHub updating the header (for whatever reason) and `clean-conversation-headers` not reacting to it.
