### ISSUE TITLE
`highest-rated-comment` links to the first comment

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5577]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/vercel/next.js/issues/31054

### Extension version

22.4.1

### Browser(s) used

Safari 15.4

### Description

Already reported in https://github.com/refined-github/refined-github/pull/5357#discussion_r796514659 before it was merged, that change should be undone.

<img width="903" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/162121963-fe5733f6-5e7a-404f-b3a1-75529169e0aa.png">

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by kidonng** [comment]
Looking back it is indeed my fault, the feature shouldn't cater rare occasions I mentioned (and if it's really the case, `conversation-activity-filter` may be helpful).
