### ISSUE TITLE
Cleanup pull-request from clutter

### ISSUE THREAD

**Issue by Luzifer** [refined-github/refined-github#5581]
### Description

Sometimes pull-requests stay open longer than expected and pile up a lot of `X previously approved these changes N days ago` and `Y dismissed X's stale review via C N days ago`… Maybe in combination with `M hidden items` yielding more of previous examples after expanded…

This makes the pull-request view quite unusable because you need to scroll 4000px (just looked it up in one of my PRs) until you get to the important stuff.

An option to clean that up IMHO would be a great addition and would help the user to work more efficiently.

A simple "cleanup" which might be suitable to demonstrate the effect would be this one:
```javascript
[...document.querySelectorAll('.js-timeline-item')].filter(itm => {
    const html = itm.innerHTML
    return html.includes('previously approved') || (html.includes('stale review') && html.includes('dismissed'))
}).forEach(itm => itm.parentElement.removeChild(itm))
```

Sadly this needs to be re-applied every time a `M hidden items` section is expanded.

### Screenshot

Before / default state
![image](https://user-images.githubusercontent.com/20142/162428617-b95769d9-343d-4f05-81db-874987d24bad.png)

After / cleaned
![image](https://user-images.githubusercontent.com/20142/162428691-c7b646e9-8d4d-47da-8ca1-186756e65410.png)

### Example URL

Not providing an URL below as all example PRs are in private repos having a branch protection with "Dismiss stale pull request approvals when new commits are pushed" active.

**Comment by fregante** [comment]
I think we already do this as part of the `filter-conversation-activity` feature or whatever it's called

**Comment by cheap-glitch** [comment]
> I think we already do this as part of the `filter-conversation-activity` feature or whatever it's called

It's `conversation-activity-filter`, and there's even a hotkey for it (<kbd>h</kbd>)

**Comment by Luzifer** [comment]
Hm that doesn't do anything good for me… Level 1 already hides the commits and still shows the previous (stale) approvals… Level 2 hides everything… I need to see the commits and don't need to see stale approvals…

Maybe another level "hide stale stuff" keeping commits, non-collapsed comments and currently valid (non-dismissed) approvals? 🤔

**Comment by yakov116** [comment]
I know this is on GitHubs list to add in the future.

**Comment by fregante** [comment]
We can definitely include stale reviews in the "collapsed comments" filter, which are currently never hidden: https://github.com/refined-github/sandbox/pull/10#event-6400656397

<img width="709" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/162558537-716e67c4-a5cd-4d38-a795-e61ab115f1f5.png">




> Maybe another level "hide stale stuff" keeping commits

I wonder if we should always just keep commits visible instead. The feature was designed around issue conversations and then the PR followed. I think commits are an important part of PRs (uh, which seems obvious) so maybe we should never hide them.

Both of these changes would fix it for you.
