### ISSUE TITLE
Conversation sub-header is vertically misaligned

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5585]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

Any issue or PR
https://github.com/refined-github/refined-github/pull/5579
This issue

### Extension version

22.4.1

### Browser(s) used

Safari 15.4

### Description

Before and after in issues and PR. Likely due to the conversation filter icon

<img width="609" alt="Screen Shot 10" src="https://user-images.githubusercontent.com/1402241/162655957-e7800ac6-82b9-46c4-b16f-0b9d1d795b08.png">

<img width="411" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/1402241/162655951-c9a234a1-d397-42e2-800b-0524dbc19b0c.png">

<img width="688" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/1402241/162655949-4ba9e888-3479-4b1f-a540-5bb678ee5c44.png">

<img width="448" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/1402241/162655941-93d4657f-fb0f-47c1-bfed-fb1cc1d62f8c.png">

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by cheap-glitch** [comment]
Already fixed by https://github.com/refined-github/refined-github/pull/5322#discussion_r845282344 :wink:
