### ISSUE TITLE
'a' to select all notifications

### ISSUE THREAD

**Issue by gegoune** [refined-github/refined-github#5590]
Did GitHub just removed `a` mapping for selecting all notifications? It stopped working today and I am not sure whether this mapping was coming from GitHub or this extension. If it was removed by GitHub, could it be added to refined-github? It was very useful.

**Comment by cheap-glitch** [comment]
It is indeed from this extension (`select-all-notifications-shortcut`) and was temporarily disabled because of #5569. It will be restored by #5588, which will probably be released today.

**Comment by gegoune** [comment]
Thank you very much for such rapid response. Amazing extension!

**Comment by gegoune** [comment]
@cheap-glitch Is there anything that one can help with to get Safari extension built and uploaded?

**Comment by cheap-glitch** [comment]
@gegoune You can take a look at #3686, it sums up what needs to be done. I'm not a Mac user, so I can't be of much help on that.

**Comment by fregante** [comment]
> Is there anything that one can help with to get Safari extension built and uploaded?

- #3686 

Without it, releases will be once a month or so.
