### ISSUE TITLE
"Private" label was removed from repository page

### ISSUE THREAD

**Issue by qiwihui** [refined-github/refined-github#5595]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github

### Extension version

22.4.11

### Browser(s) used

100.0.4896.75 (Official Build) (x86_64)

### Description

The "Private" label was removed when in private repository page, it make it inconvenient. I thought my private repository was suddenly being changed to "Public". It confused me.

Refined github was enabled:

<img width="270" alt="Screen Shot 2022-04-14 at 10 26 02 AM" src="https://user-images.githubusercontent.com/3297411/163302865-ca018a99-4cb2-43c6-b9ee-a4c82fd78f8a.png">

Not enabled:

<img width="294" alt="Screen Shot 2022-04-14 at 10 31 28 AM" src="https://user-images.githubusercontent.com/3297411/163302868-07a6432c-43cd-42e9-a1ee-3f79d00c26ee.png">

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by cheap-glitch** [comment]
You can disable the `hide-repo-badges` feature in the options page if you don't want this behavior.

**Comment by fregante** [comment]
<img width="317" alt="Screen Shot 14" src="https://user-images.githubusercontent.com/1402241/163397445-d300b19e-0c16-4b7f-9295-61fca5f74341.png">
