### ISSUE TITLE
`forked-to` seems broken

### ISSUE THREAD

**Issue by yzqdev** [refined-github/refined-github#5596]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github

### Extension version

22.4.11

### Browser(s) used

google chrome  100.0.4896.88

### Description

link to your fork button disappears.
* I have cleared cache
* I have my personal token in refined-github
* I have forked refined-github https://github.com/yzqdev/refined-github

link to your fork button disappears.
I guess maybe it's github changed the fork procedure that causes this. Two days before, when I clicked fork button , a dialog jumped, while now when i click fork button, it'll turn to a new fork page.

### before
![](https://user-images.githubusercontent.com/44045911/155149526-4a9e0880-6268-47ee-9d59-d53cfc007150.png)
### after
![image](https://user-images.githubusercontent.com/20037151/163309726-06e06969-fbbd-4f09-8b5c-4a7c8359c776.png)

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by FloEdelmann** [comment]
I see this broken UI in https://github.com/streetcomplete/StreetComplete (of which I have [a fork](https://github.com/FloEdelmann/StreetComplete)):

![grafik](https://user-images.githubusercontent.com/202916/163358706-1514103d-9777-4d12-8913-26e3555964ba.png)

The button works fine though.

**Comment by cheap-glitch** [comment]
> I see this broken UI 

I don't see it, but this is probably because the feature has cached this repo as a fork for you and not me.

**Comment by cheap-glitch** [comment]
> I guess maybe it's github changed the fork procedure

Indeed, clicking the "Fork" button now redirects to a special page instead of showing a popup.

Though I don't know if it's for everyone or just people in organizations :thinking:

**Comment by Superskyyy** [comment]
I think the fork-to feature is still broken on the latest release, very rarely does it show the button. then sometimes it shows `fork-to Uncaught TypeError: Cannot read properties of undefined (reading 'classList')`. Then even the error message is gone now after clearing my cache and rebooting the browser etc. 

My version is  22.4.21 with Edge. I have tried many times clearing the cache and reinstalling the extension, and it stopped showing up completely.

![image](https://user-images.githubusercontent.com/26076517/164967139-fb8e7714-4fde-425a-b751-92b7f7e90a7c.png)

**Comment by cheap-glitch** [comment]
> I think the fork-to feature is still broken on the latest release

Can't reproduce on Firefox, it's working fine for me, even with heavy throttling:

![image](https://user-images.githubusercontent.com/46634000/164970356-39c46d8c-b445-47c4-a349-adced3397b7b.png)

> I have tried many times clearing the cache and reinstalling the extension

@Superskyyy The button will only be shown if you've visited your fork at least once. If you create a new fork, clear the cache, and then load the original repo, you won't see the button. Try visiting some of your forks before going to their parent repos, can you see anything?

Also, just to avoid any misunderstandings, the feature is not called "fork-to" but `forked-to`, meaning the button is a link that appears on the original repo, not on your fork.

**Comment by Superskyyy** [comment]
> > I think the fork-to feature is still broken on the latest release
> 
> Can't reproduce on Firefox, it's working fine for me, even with heavy throttling:
> 
> ![image](https://user-images.githubusercontent.com/46634000/164970356-39c46d8c-b445-47c4-a349-adced3397b7b.png)
> 
> > I have tried many times clearing the cache and reinstalling the extension
> 
> @Superskyyy The button will only be shown if you've visited your fork at least once. If you create a new fork, clear the cache, and then load the original repo, you won't see the button. Try visiting some of your forks before going to their parent repos, can you see anything?
> 
> Also, just to avoid any misunderstandings, the feature is not called "fork-to" but `forked-to`, meaning the button is a link that appears on the original repo, not on your fork.

@cheap-glitch Thanks for the reply! Indeed visiting the fork at least once made the error message appear again, but the button still does not show up for me. Well, I remember it showed up like once in the past hour in some other repos and disappears immediately after refreshing the page.

![image](https://user-images.githubusercontent.com/26076517/164970892-f42f87c5-6363-405e-9434-d266eec5854b.png)

**Comment by cheap-glitch** [comment]
@Superskyyy If by any chance you have other GitHub-related extensions, could see if the problem persists when you disable them? Also, if you have access to others browsers, is the error present there too?

If that's the case, can you open a new issue with:
- the console error
- your OS and exact browser version
- the HTML of the repo header with Refined GitHub disabled (or the whole page is fine too)

Thanks!

**Comment by Superskyyy** [comment]
> @Superskyyy If by any chance you have other GitHub-related extensions, could see if the problem persists when you disable them? Also, if you have access to others browsers, is the error present there too?
> 
> If that's the case, can you open a new issue with:
> 
> * the console error
> * your OS and exact browser version
> * the HTML of the repo header with Refined GitHub disabled (or the whole page is fine too)
> 
> Thanks!

Apparently it's a problem on my side, I rebooted my laptop few times and it started to work. 
Just to give an update, thank you!

**Comment by gengjiawen** [comment]
Sadly reboot not worked for me.
```
refined-github.js:3859 📕 22.4.21 → TypeError: Cannot read properties of undefined (reading 'classList')
    at refined-github.js:8567:24
    at init (refined-github.js:8601:12)
    at async runFeature (refined-github.js:3902:20)
    at async setupPageLoad (refined-github.js:3910:34)
refined-github.js:3860 🔍 Search issue https://github.com/refined-github/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+Cannot+read+properties+of+undefined+%28reading+%27classList%27%29
refined-github.js:3860 🚨 Report issue https://github.com/refined-github/refined-github/issues/new?labels=bug&template=1_bug_report.yml&title=%60forked-to%60%3A+Cannot+read+properties+of+undefined+%28reading+%27classList%27%29&example_urls=https%3A%2F%2Fgithub.com%2Fnodejs%2Fgyp-next&description=%60%60%60%0ATypeError%3A+Cannot+read+properties+of+undefined+%28reading+%27classList%27%29%0A++++at+chrome-extension%3A%2F%2Fhlepfoohegkhhmjieoechaddaejaokhf%2Frefined-github.js%3A8567%3A24%0A++++at+init+%28chrome-extension%3A%2F%2Fhlepfoohegkhhmjieoechaddaejaokhf%2Frefined-github.js%3A8601%3A12%29%0A++++at+async+runFeature+%28chrome-extension%3A%2F%2Fhlepfoohegkhhmjieoechaddaejaokhf%2Frefined-github.js%3A3902%3A20%29%0A++++at+async+setupPageLoad+%28chrome-extension%3A%2F%2Fhlepfoohegkhhmjieoechaddaejaokhf%2Frefined-github.js%3A3910%3A34%29%0A%60%60%60
```

**Comment by gengjiawen** [comment]
Maybe the loading time is not stable, I add a breakpoint and sees the forked button still not showing ?

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/3759816/167109299-27088fb3-881f-46e7-88bb-6cfc4cdad3c7.png">
