### ISSUE TITLE
GitPop instead of Useful Forks

### ISSUE THREAD

**Issue by azumukupoe** [refined-github/refined-github#5602]
### Description

https://github.com/AndreMiras/gitpop3 or https://github.com/AndreMiras/gitpop2 is much more lightweight than https://github.com/useful-forks/useful-forks.github.io

### Example URL

https://github.com/useful-forks/useful-forks.github.io

**Comment by fregante** [comment]
Refer to https://github.com/refined-github/refined-github/issues/3638#issuecomment-711492714
