### ISSUE TITLE
`restore-file` doesn't work after Ajax

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5606]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github/pull/5605/files

### Extension version

22.4.1

### Browser(s) used

Safari

### Description

I can never use `restore-file` until I refresh the page. I assume the repro is:

1. Open https://github.com/refined-github/refined-github/pull/5605
2. Go to Files tab
3. Look for "Restore file", it's missing
4. Refresh
5. It's there

https://user-images.githubusercontent.com/1402241/164187430-9d3af861-de74-43d8-9346-44444f92cc6b.mov

**Comment by cheap-glitch** [comment]
This is probably a de-duplication bug, as it affects every feature that acts on the "Files" tab, e.g. `linkify-code`:

1. Open https://togithub.com/refined-github/refined-github/pull/5541
2. Go to "Files" tab
3. Issue references are not linkified
4. Reload: they are
