### ISSUE TITLE
Ability to change default search sort order

### ISSUE THREAD

**Issue by PAI5REECHO** [refined-github/refined-github#5608]
### Description

It'd be nice to set what you want the default sort order for searches to be. I always prefer most recently updated rather than "best"

### Screenshot

![image](https://user-images.githubusercontent.com/96688573/164976234-d28e78ae-42ee-482e-a23f-58582a57f528.png)

### Example URL

https://github.com/search?q=asd

**Comment by fregante** [comment]
Unfortunate Refined GitHub is not about options: https://github.com/refined-github/refined-github/issues/2960#issuecomment-606765658
