### ISSUE TITLE
`forked-to`: select_dom(...) is undefined

### ISSUE THREAD

**Issue by cheap-glitch** [refined-github/refined-github#5609]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

Go to https://github.com/refined-github/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc and open an issue. Same with the PR list.

### Extension version

22.4.21

### Browser(s) used

Firefox

### Description

```
❌ forked-to refined-github.js:3859:17
	init@moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/refined-github.js:8563:146
	async*runFeature@moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/refined-github.js:3902:26
	setupPageLoad@moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/refined-github.js:3910:40
```

This only occurs when navigating from the Issue/PR lists to an Issue/PR page, which makes me suspect a de-duplication bug.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by gengjiawen** [comment]
Looks like need to make awaitDomReady to true https://github.com/refined-github/refined-github/issues/5596#issuecomment-1119447316

Is there an easy way to verify this on local ?

**Comment by gengjiawen** [comment]
Removing it works on my local.

**Comment by fregante** [comment]
That's right, `init` is called before DOM ready, so we must use `elementReady` somewhere, likely after the first line in `init`, before `select`

https://github.com/refined-github/refined-github/blob/b9df41b15f6fd54fad80f6651778b3d9f7107224/source/features/forked-to.tsx#L107

Something like this should work, without assigning it to anything: `await elementReady('.page-actions')`
