### ISSUE TITLE
Any way to always ignore spaces in diffs?

### ISSUE THREAD

**Issue by BoD** [refined-github/refined-github#5613]
Hi!

I never want to see white spaces when reviewing a PR (the equivalent of adding `?w=1`) to the URL. Is there a way to do this with this extension by any chance? Thanks a lot!

**Comment by cheap-glitch** [comment]
> Is there a way to do this with this extension by any chance?

No, and since that's a personal preference and we don't do feature settings, it's likely there never will be.

I suggest you make a request to GitHub about adding this. It could be a personal setting that would be applied everywhere, and/or a repo-specific setting too.

**Comment by BoD** [comment]
Oh ok 😢.  Thanks for replying.

Yeah [this issue](https://github.com/github/feedback/discussions/5486) already exists but it doesn't seem to have a high priority...

Just found [this extension](https://chrome.google.com/webstore/detail/github-whitespace/fnpkdafamnbjoldglihkjjdicofghccm), I'll try it.
