### ISSUE TITLE
How to disable repo info centering?

### ISSUE THREAD

**Issue by radstevee** [refined-github/refined-github#5617]
It looks like this for me:
![image](https://user-images.githubusercontent.com/96977790/166478104-169b69df-1b31-4d3f-8525-7b8444a0802c.png)
(i'm using [the catppuccin theme](https://github.com/catppuccin/github))

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/4519

**Comment by fregante** [comment]
This feature has now been dropped in https://github.com/refined-github/refined-github/pull/6247
