### ISSUE TITLE
Colored badges for private/public repositories

### ISSUE THREAD

**Issue by andry81** [refined-github/refined-github#5619]
### Description

Private and public repositories is poorly distinguishable in a repository list. Both has same color, font and form of a badge.

I suggest to improve that, for example, highlight a private repository by a purple (in case of dark mode and make it customizable) badge border color or something like that. This will be helpful in case of many repositories in a list.

In the html it does look like this:

```
<span data-view-component="true" class="Label Label--secondary v-align-middle ml-1 mb-1">Private</span>
<span data-view-component="true" class="Label Label--secondary v-align-middle ml-1 mb-1">Public</span>
```

### Example URL

-

**Comment by fregante** [comment]
I kind of agree that it could be better, but it's not worth adding JS for this and as you noticed they're indistinguishable with a CSS selector.
