### ISSUE TITLE
Show number of assigned and open pull requests for suggested reviewers

### ISSUE THREAD

**Issue by RyanMulready** [refined-github/refined-github#5624]
### Description

Our team is trying to find the right balance on who should review a PR. One of the things we would like to consider when requesting a review is how many other open PRs the person already has been asked to review. You can accomplish this by searching the PR list with a query like this 
`is:pr is:open review-requested:@GITHUB_USERNAME`

If possible including this count in the reviewer modal would be super beneficial. See screenshot below.

### Screenshot

![image](https://user-images.githubusercontent.com/1017057/167683475-023cb6ad-8cd5-45e9-90a5-05e6f9eb940d.png)

### Example URL

https://github.com/refined-github/refined-github/pull/5612

**Comment by cheap-glitch** [comment]
This seems to me like a rather niche feature, and one that would require a non-trivial amount of code too. Given that we're already struggling to maintain our current feature set, I don't think we can consider this.

Let's see what the other maintainers have to say though.

**Comment by AlexDaniel** [comment]
@RyanMulready Maybe a bit off topic, but I wonder, how do you guys know which PRs are assigned to you? #5551. To this day we're still struggling with that issue.

**Comment by RyanMulready** [comment]
> @RyanMulready Maybe a bit off topic, but I wonder, how do you guys know which PRs have a review requested from you? #5551. To this day we're still struggling with that issue.

In the list view we don't have a way. You can however see it in your filters:

![image](https://user-images.githubusercontent.com/1017057/180895287-c28cdd49-6712-4d82-bcc5-02d0f9dbfa84.png)

**Comment by AlexDaniel** [comment]
@RyanMulready yeah, well. These filters are only visible on https://github.com/pulls, not in pull requests of each repo.

**Comment by kidonng** [comment]
> In the list view we don't have a way.

That's not true, there are _multiple_ ways:

- In repository pull request list, use [`review-requested:USERNAME`](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-pull-request-review-status-and-reviewer) qualifier:

  <img width="449" alt="image" src="https://user-images.githubusercontent.com/44045911/181165510-b647a339-f378-4772-9d8b-03d68d6ae056.png">

- In [notifications](https://github.com/notifications), use `reason:review-requested` along with a `repo:USER/REPO` qualifier:

  <img width="620" alt="image" src="https://user-images.githubusercontent.com/44045911/181165639-ceb6725a-335a-40a3-be42-236b33a3c29c.png">

**Comment by RyanMulready** [comment]
> > In the list view we don't have a way.
> 
> That's not true, there are _multiple_ ways:
> 
>     * In repository pull request list, use [`review-requested:USERNAME`](https://docs.github.com/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-pull-request-review-status-and-reviewer) qualifier:
>       <img alt="image" width="449" src="https://user-images.githubusercontent.com/44045911/181165510-b647a339-f378-4772-9d8b-03d68d6ae056.png">
> 
>     * In [notifications](https://github.com/notifications), use `reason:review-requested` along with a `repo:USER/REPO` qualifier:
>       <img alt="image" width="620" src="https://user-images.githubusercontent.com/44045911/181165639-ceb6725a-335a-40a3-be42-236b33a3c29c.png">

I should have been more specific. There isn't a quick way to filter to that view. Maybe that's a good middle ground for this feature request. Could be get an additional filter link to that list?

`Every review requested of you`

![image](https://user-images.githubusercontent.com/1017057/181257885-b59cd893-bb7b-45ee-822c-5b3c905c0e8b.png)

**Comment by fregante** [comment]
> `Every review requested of you` 

Already exists natively, just a different dropdown:

<img width="326" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/181262404-96a2e96d-9cb3-42d6-9358-1ec7c63412e5.png">

> or even better a select list of contributors?

I think you're just talking about project management, which Refined GitHub [steers away from](https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#7-it-doesnt-enhance-projects).

GitHub already offers a better way to see all the issues assigned to each person in the team, so you don't have manually select each one sequentially:

https://github.com/features/issues

**Comment by fregante** [comment]
The request makes sense however it has several issues:

- kinda niche: having multiple review requests might not be that big of a deal
- difficult to explain: what's (2)? It's not a native GitHub feature and we can't even show a tooltip because the whole line is clickable
- not a simple feature, relative to it usefulness/impact

I'd suggest this to GitHub, but they'd probably have the same feeling.
