### ISSUE TITLE
Pages of long scripts become choppy

### ISSUE THREAD

**Issue by twio142** [refined-github/refined-github#5627]
I'm using an old MacBook and struggling with its pitiful performance. The extension works just fine on other GitHub pages. But when it comes to a long script with several hundred lines, the page becomes extremely slow and scrolls choppy. Which features could I switch off to help with this? 

Also: What would be the most efficient way to go through all the features, find out what each of them does and rule out the ones I don't need?

Many thanks in advance! ♥

**Comment by cheap-glitch** [comment]
> a long script with several hundred lines

Do you mean source files? Maybe disabling `show-whitespace` would help.

> What would be the most efficient way to go through all the features, find out what each of them does and rule out the ones I don't need?

Go to the options page, there's a list of toggable features with a short description and a screenshot for each one.

**Comment by fregante** [comment]
What browser? Does it happen without Refined Github?

With Safari, performance on long PRs is terrible even without RGH on my 2019 i9 MacBook too. It's a combination of bad browser and bad GitHub.



> Do you mean source files? Maybe disabling [`show-whitespace`](https://github.com/refined-github/refined-github/blob/main/source/features/show-whitespace.tsx) would help.

I sure hope not since we specifically do not touch lines outside the viewport (other than for watching them via IntersectionObserver) 😬

**Comment by fregante** [comment]
> Also: What would be the most efficient way to go through all the features, find out what each of them does and rule out the ones I don't need?

There's also a "Find feature…" button that lets you find out whether there's a specific feature slowing you down (unlikely, but…)

**Comment by twio142** [comment]
> What browser? Does it happen without Refined Github?

@fregante I'm using Chrome and yes, it performs properly without Refined GitHub.

> Do you mean source files? Maybe disabling [show-whitespace](https://github.com/refined-github/refined-github/blob/main/source/features/show-whitespace.tsx) would help.

This actually helps...😂  I tried back and forth, and this specific one does make differences. @cheap-glitch Thanks a lot! 

Thank you both for the advices :)
