### ISSUE TITLE
open all github actions of a pr

### ISSUE THREAD

**Issue by dvir-levy** [refined-github/refined-github#5628]
### Description

When creating a new PR I have a several GitHub Actions running on it. 
To see the results of them (not only the status) I need to open each one of them manually. 
It will be great to have the ability to open all GitHub Actions with a click of a button.
Thank you!

### Screenshot

<img width="927" alt="image" src="https://user-images.githubusercontent.com/79982395/168472517-5578e0f8-eaa2-44e7-8dba-da08c57c9d75.png">

### Example URL

https://github.com/hashicorp/terraform/pull/31049

**Comment by fregante** [comment]
This is rather niche as usually a green check means "it's all good" and it doesn't need to be checked. I might suggest using a generic "open multiple links" extension. I remember seeing one that lets you draw a line on the page and it opens all the links you cross at once.
