### ISSUE TITLE
`shorten-links` shortens a link in a pre incorrectly

### ISSUE THREAD

**Issue by NickBolles** [refined-github/refined-github#5630]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

The issue I'm making

### Extension version

22.4.21

### Browser(s) used

Edge

### Description

here's a very similar markdown segment as what I have in a PR comment. The github link in this case links to my user, instead of the full URL, which I want to show so that the command is copy/paste-able. I'm not 100% clear on if this is a bug or not, but if not I'd like to be able to disable shortening on this `<pre>` element as most of our team uses refined github and we'd like to be able to copy/paste this command

| | |
| --- | --- |
| table | <pre>ruby run.rb linky &#92;<br/>&emsp;&emsp;--host https://github.com/NickBolles &#92;<br/>&emsp;&emsp;--version 12345 &#92;<br/>&emsp;&emsp;-e stage</pre> |

Exact same code outside of a table:
<pre>ruby run.rb linky &#92;<br/>&emsp;&emsp;--host https://github.com/NickBolles &#92;<br/>&emsp;&emsp;--version 12345 &#92;<br/>&emsp;&emsp;-e stage</pre>

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by cheap-glitch** [comment]
This is indeed a bug, thanks for reporting! `shorten-links` should _not_ affect links inside code blocks.

I think the bug comes from the fact that the block is inside a table, which afaik was never tested for.

**Comment by NickBolles** [comment]
I'm glad I posted my repro then :) I just added an example with the same code outside of the table.

**Comment by fregante** [comment]
The interesting part is that GitHub is linkifying the URL in the table but not the other code block 🤷‍♂️ 

Fixing
