### ISSUE TITLE
`list-prs-for-file` is limited to 25 PRs

### ISSUE THREAD

**Issue by ncfavier** [refined-github/refined-github#5635]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/nix-community/home-manager/blob/master/modules/programs/ssh.nix

### Extension version

22.4.21

### Browser(s) used

Firefox

### Description

There is an open PR touching that file: https://github.com/nix-community/home-manager/pull/2370/files#diff-a58732e56068a41ed3b90c4069d4c4934a01dd8f1372633f8aae82995ee14495 but the PR is not displayed on the file.

I've seen the feature work on other repos.

Am I reading the source code wrong, or are we only looking at the 25 most recent PRs?

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by ncfavier** [comment]
As a first step we can probably increase 25 to 100, but ideally we should really be paginating the files and the PRs to get all of them. I don't know if there's a convenient way to do that.

**Comment by fregante** [comment]
The issue is that every time you visit a file in a new repo, we're fetching the list of PRs and the list of files they touch. Then we store this information in the cache. The cache is not unlimited, so you can see how we could too-quickly run of space if we store every file of every PR in every repo you visit.

**Comment by ncfavier** [comment]
I guess that's fair, even though for a huge repo like nixpkgs the total JSON for every open PR "only" weighs 687 KB.

I should probably make a shell script for this anyway instead of relying on a browser extension.

Thanks!

**Comment by fregante** [comment]
That's a substantial "only" considering we only have 5000kb available 🙂

**Comment by fregante** [comment]
I don't see this being solvable on our end. It'd be great to see GitHub steal this feature though.
