### ISSUE TITLE
Apply heatmap coloring (like in blame view) to `release-download-count`

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5637]
### Description

The blame view immediately tells you which lines are the most recent:

https://github.com/refined-github/refined-github/blame/main/package.json

We can use the same pattern/coloring in other areas of GitHub. There's already a feature request for this:

- https://github.com/refined-github/refined-github/issues/5081

But we can start laying down the foundation for a generic "pick heat based on min/max values of list" utility function in `release-download-count`

### Screenshot

<img width="164" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/1402241/169451882-d0e2d53e-4796-42d3-9028-3093c35d1966.png">

### Example URL

https://github.com/notepad-plus-plus/notepad-plus-plus/releases

**Comment by fregante** [comment]
Any other views that would benefit from this? (Other than conversations, 😬 already too noisy)

**Comment by foolmoron** [comment]
Took at a crack https://github.com/refined-github/refined-github/pull/6095
