### ISSUE TITLE
Display title changes events as diffs

### ISSUE THREAD

**Issue by FloEdelmann** [refined-github/refined-github#5657]
### Description

In GitLab, the title change event in an issue's or PR's timeline shows exactly what is changed as a diff. On GitHub, it's like "this is the old title, this is the new title, figure out what changed for yourself". For issues/PRs with longer titles, it can be difficult to spot subtle changes.

#### GitLab

![grafik](https://user-images.githubusercontent.com/202916/169703000-00262bac-f723-4971-af4c-889c2dbe3a28.png)
https://invent.kde.org/plasma/discover/-/merge_requests/214#note_349280

#### GitHub

![grafik](https://user-images.githubusercontent.com/202916/169703138-7efbdbed-8418-4ab6-b04f-db04a4f1a949.png)
https://togithub.com/refined-github/refined-github/pull/5626#event-6609835934

### Example URL

https://togithub.com/refined-github/refined-github/pull/5626#event-6609835934

**Comment by fregante** [comment]
Seems easy but producing a reliable diff might not be, plus add the DOM since GitHub renders the backticks. How would this diff this be rendered?

```diff
- Hello world
+ Hello `world`
```

It's impossible to render this way because the rendered text is the same, only the "style" changes

**Comment by FloEdelmann** [comment]
We could diff only "real" changes to `textContent`. "Style"-only changes are quite visible without the diff anyway.

**Comment by cheap-glitch** [comment]
This has been bothering me too for a while. Ideally the two titles should be collapsed if the changes are minimal, e.g.

<pre>Add type/bug and kind/bug to list of supported labels<ins color="green"> in bugs-tab</ins></pre>

> Seems easy but producing a reliable diff might not be

This is the tricky part. Pulling in a diffing lib just for this is clearly overkill.

That said, I wonder if a very crude word-diffing algorithm could do the job in just a few lines — and if there's too much differences between the two titles it's not worth having a diff anyway, so the feature could just give up in that case.

**Comment by fregante** [comment]
> We could diff only "real" changes to `textContent`.

i.e. avoid applying the diff if any `rendered` text is present? If not, this is a "real" change that also has a style change:

> ~~`code` is nothing~~ _code is not nothing_




> Pulling in a diffing lib just for this is clearly overkill

💯 



> a very crude word-diffing algorithm

Could be looked at if really crude and non-problematic, after we figure out what to do with `rendered` titles.

**Comment by fregante** [comment]
What if we just improve the wrapping with `del,ins{display:block}`?

## Before

<img width="538" alt="Screen Shot 15" src="https://user-images.githubusercontent.com/1402241/169727935-301b9046-9821-4852-98a9-7219f6a9ab51.png">


## After


<img width="551" alt="Screen Shot 14" src="https://user-images.githubusercontent.com/1402241/169727929-eb419e03-ccb3-4649-9965-925b7c7e5fd9.png">

**Comment by cheap-glitch** [comment]
> What if we just improve the wrapping

That's definitely an improvement, I like it!

That said, I still think a single-line diff would be ideal (especially in the example shown above), so I'd like this issue to remain open even if we make that change.

**Comment by fregante** [comment]
I think this only works if the changes are minimal. See the title change above:

```diff
- Highlight PR/issue title changes as diff 
+ Display title change events as diffs
```

It will be displayed as:

<img width="723" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/1402241/170859187-8b224a6f-b1fd-4103-9d70-3aca8d23a3eb.png">

Which I don’t think it's any more clearer than what https://github.com/refined-github/refined-github/pull/5658
