### ISSUE TITLE
Show a "View Branch in Editor" button for PRs

### ISSUE THREAD

**Issue by frankdilo** [refined-github/refined-github#5659]
### Description

Add a button to PRs that allow you to quickly open VS Code for the branch being reviewed on [github.dev](https://github.dev).

I find it useful when reviewing big PRs to take a look at a specific branch in the web editor, so I don't have to download the branch locally.

For any given branch in a repo, you can simply open the VS Code web editor provided by GitHub with this URL structure:

```
https://github.dev/{username}/{repo}/tree/{branch}
```

Example editor on Django: https://github.dev/django/django/tree/stable/4.1.x

### Screenshot

![CleanShot 2022-05-24 at 14 17 31@2x](https://user-images.githubusercontent.com/715405/170033585-84600285-4ae6-45b9-8143-a3585d02f7de.png)

### Example URL

https://github.com/django/django/pull/15730

**Comment by cheap-glitch** [comment]
If we add this, it should probably be in the "Code" dropdown. The PR header is already sufficiently crowded as it is.

**Comment by frankdilo** [comment]
> If we add this, it should probably be in the "Code" dropdown. The PR header is already sufficiently crowded as it is.

I think if we hide it too much nobody will use and discover it.

**Comment by cheap-glitch** [comment]
> I think if we hide it too much nobody will use and discover it.

Avoiding UI clutter comes first imo, especially for relatively niche features such as this one.

We can help a bit with discoverability by featuring it in the corresponding release. It's also up to users to read the docs.

**Comment by yakov116** [comment]
Its coming soon directly from GH, its called code spaces.

![image](https://user-images.githubusercontent.com/16872793/170044241-0126dc8b-cc7b-4243-848a-1e3694820ae0.png)
