### ISSUE TITLE
refined-github on brave

### ISSUE THREAD

**Issue by mmgxa** [refined-github/refined-github#5661]
I am using brave browser on Pop!_OS. I can't see the  features (e.g. download folder option etc.) - rather any feature -  while using the extension. I haven't added the personal token (I don't think it is needed for this feature).

Has anyone used this extension on brave and got it to work properly?

**Comment by mmgxa** [comment]
Do we need to login to our profile to make it work? I have now added the access token as well (without logging in). Still no signs of download option..

**Comment by fregante** [comment]
Some features work when you're logged out but we don't support that officially.  Can you post a screenshot of this repo after enabling the extension? Any errors in the console?

**Comment by fregante** [comment]
If you just need to download folders, you can use https://download-directory.github.io/ directly. RG only adds a link to it

**Comment by mmgxa** [comment]
Downloading folders was just one example - other features don't work. I guess I'll use it while logged in.
Thanks.
