### ISSUE TITLE
Automatically scroll to the next file in PR files view after marking as viewed

### ISSUE THREAD

**Issue by danieldiekmeier** [refined-github/refined-github#5664]
### Description

Every now and again, I have to review PRs with a lot of small files. When you view/collapse a file, you have to scroll a little bit to the next file to collapse it next.

I think it would be nice if, after collapsing, the page would automatically scroll the 60px to the next file.

The code I used to make my example video was:

```js
document.querySelectorAll(".js-reviewed-toggle").forEach((el) =>
  el.addEventListener("click", () => {
    window.scrollBy({ left: 0, top: 60, behavior: "smooth" });
  })
);
```

### Screenshot

https://user-images.githubusercontent.com/2098462/171027573-2ea9c420-ad85-4e81-a1c5-de35f28e9e7c.mov

### Example URL

[github.com/refined-github/refined-github/pull/5656/files](https://github.com/refined-github/refined-github/pull/5656/files)

**Comment by fregante** [comment]
This sounds good in theory but it risks being super annoying and maybe a little confusing too. Sliding the whole page under the cursor might be a little disorienting, this type of interaction is basically not seen anywhere. 

I don't know if it still works but I suggest pressing the J key to focus the next item after clicking Viewed, and then maybe continue marking as viewed with the keyboard (if such shortcut exists 🤔, I don't know, I'm on mobile right now 😅)

**Comment by cheap-glitch** [comment]
> if such shortcut exists

I haven't found one, but it could be a good feature to add (especially in combination with the <kbd>j</kbd>/<kbd>k</kbd> shortcuts)

**Comment by danieldiekmeier** [comment]
I agree: A shortcut that marks a file as viewed could, together with `j`/`/k`, also solve my original problem.

**Comment by forivall** [comment]
oh hey, i just suggested a keyboard shortcut here https://github.com/refined-github/refined-github/issues/5674 , I would propose <kbd>m</kbd>

**Comment by fregante** [comment]
Closing in favor of https://github.com/refined-github/refined-github/issues/5674
