### ISSUE TITLE
Unfocus PR comment field after submitting a comment

### ISSUE THREAD

**Issue by DaniFoldi** [refined-github/refined-github#5667]
### Description

The comment field in PRs remains in focus after submitting a comment. If I scroll up quickly (with the intention to navigate away or otherwise), but not quick enough, then after the PR is submitted the page jumps back down, scrolling the comment field into view.

### Example URL

https://github.com/refined-github/refined-github/pull/5654

**Comment by DaniFoldi** [comment]
Here's a video with me commenting on a PR. Apologies for the delay, I had exams.
https://user-images.githubusercontent.com/6977583/173543018-20d092ad-7589-4078-bb6c-e18f9b8906d8.mov

**Comment by yakov116** [comment]
It in the middle of sending the comment I think the behavior is expected
