### ISSUE TITLE
"Find feature" gives incorrect information for CSS features

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5668]
We can't disable CSS features so our flow will end up reporting the wrong information. 

Perhaps we can start the flow with a step without any features enabled. If the user can see the bug we'll say something like:

- Refined GitHub can't disable this. It may be a CSS-only feature or completely unrelated to Refined GitHub

**Comment by cheap-glitch** [comment]
+1 but:

```diff
-that can't be disabled
+that can (only) be disabled via the "Custom CSS" field on the options page
```

**Comment by fregante** [comment]
👌 We can add a link to https://github.com/refined-github/refined-github/issues/5501

**Comment by fregante** [comment]
Related information:

- https://github.com/refined-github/refined-github/issues/5828

We can add a link to the wiki for extended details that we can change and improve at any time.

> Unable to identify feature. It might be a CSS-only, a meta-feature or unrelated to Refined GitHub. More info on our [wiki](#page-to-be-defined)

PR welcome
