### ISSUE TITLE
surface "base" and "compare" branches (commit counts too?) for each pull request on Pull Requests pages

### ISSUE THREAD

**Issue by olets** [refined-github/refined-github#5672]
### Description

On the Pull Requests page, GitHub hides each pull request's branches behind a popup.

The only way to see them is with a mouse hover, which adds the content to the page with js. Surfacing the branches, for example next to the "#x opened y days ago by z", would make them accessible for users who currently aren't able to take advantage of GitHub's popup feature, and would be convenient for all users.

In the screenshot I've copied over the line from the top of a pull request page ("x commits into `a` from `b`"). The popup only has branches, but the commit count would keep nice parity between the Pull Requests list and pull requests.

### Screenshot

before|after
---|---
![image](https://user-images.githubusercontent.com/3282350/171692427-4fa0433c-7dd1-4f68-8148-840d47e9e4e4.png)|![image](https://user-images.githubusercontent.com/3282350/171692335-9dca9a81-ff1c-4b2a-b82b-968c50fea8ff.png)

### Example URL

https://github.com/refined-github/refined-github/pulls

**Comment by ngouy** [comment]
@fregante I see that a lot of request around this list are declined for the very valid reason that:
- this list is already crowded
- there is a lot of request

Overall I guess it really depends on how you manage your work flow, what you value/want to know on tour PRs

Would you consider adding those options/feature would be "not selected" by default so the options are here, but the basic view is still manageable for everyone, and customizable in the settings?

Or what about an "extension" system

Basicly where we could cherry-pick what we want and adapt to our workflows?

Sorry if redundant or else.
Should I open a new issue? (at least for traceability?) WDYT?
