### ISSUE TITLE
Preview resolved PR comments

### ISSUE THREAD

**Issue by Totktonada** [refined-github/refined-github#5673]
### Description

It would be nice to show several first words of a collapsed inline comment in a pull request. It would ease navigation over past comments.

Let's consider the first screenshot: I don't have an idea what is the key point of this review until I'll uncollapse comments. I can't spot the idea at glance.

Collapsed comments preview would also improve searching over comments. I often remember how a discussion was started and want to find and read the whole thread. (I don't know, whether HTML allows it, but the ideal would be allow to search over the whole comment, not only over the preview.)

I'm not sure whether this feature request fits good with the [It doesn't require too much HTTP traffic.](https://github.com/refined-github/refined-github/issues/2960#issuecomment-606769808) point. As I see, the comments are not loaded initially into the page. Hopefully we can fetch them all in an API request.

<details>
<summary>We can also consider a button to load all collapsed reviews</summary>

See the second screenshot.

It is a separate feature request, but together with one that is proposed here, it would allow a comfortable searching over PR discussions without annoying clicking `Load more...`.

I'll file a separate feature request if there will be an interest.
</details>

*(It is my first request to refined-github. I apologize if I doing something wrong. I'm trying to describe what would improve a developer productivity based on my personal experience.)*

### Screenshot

Collapsed inline comments:

![image](https://user-images.githubusercontent.com/92749/171767506-23e3ed0f-7b9d-4c37-a925-2335b0dcf002.png)

<details>
<summary>Screenshots for the 'button to load all collapsed reviews' proposal</summary>

Collapsed reviews:

![image](https://user-images.githubusercontent.com/92749/171769588-bc853278-f062-4580-9cbb-1746d9913a7d.png)

After the click I should do two more clicks in random places of the page.

Here:

![image](https://user-images.githubusercontent.com/92749/171769525-2aced2f0-50cb-40da-9fbb-55364d57be05.png)

And here:

![image](https://user-images.githubusercontent.com/92749/171769739-cd4e29ac-d317-46bb-a87c-c74e0300eba2.png)

And more to reveal everything.
</details>

### Example URL

https://github.com/tarantool/crud/pull/244/

**Comment by cheap-glitch** [comment]
We already have a feature called `preview-hidden-comments`, but as you pointed out GitHub started to defer the loading of collapsed comments (or at least some of them) a while ago, and there's not much we can do about that. We could triggered their loading by sending some mouse events to the `<detail>` elements but as you also pointed out, that would cause too many HTTP requests.

The other feature you suggested already exists too, it's called `expand-all-hidden-comments`. You just need to hold down <kbd>Alt</kbd> when clicking the "Load more" button and it'll load everything for you.

There are actually several RGH features in that vein that allow Alt-clicking stuff to batch multiple actions.
