### ISSUE TITLE
Add more hints about stars when change to private dialog

### ISSUE THREAD

**Issue by muescha** [refined-github/refined-github#5675]
### Description

Add more infos if someone try to change the visibilty of a repo to private.

add current stars
add current contributors

Full story see: https://httpie.io/blog/stardust

### Screenshot

current warning:

![image](https://user-images.githubusercontent.com/184316/171971141-e86fef17-8961-446d-b2e6-20eb49c055dc.png)

Add warning with counts (example of an warning):

![image](https://user-images.githubusercontent.com/184316/171971116-add09088-b97b-48de-989f-56238ff52e5f.png)

add ok when no harm:
![image](https://user-images.githubusercontent.com/184316/171971123-4e1f1a1f-15c4-44f6-aac9-73cf12580a1d.png)

### Example URL

https://github.com/httpie/httpie

**Comment by fregante** [comment]
I remember what happened there, but the dialog is already pretty clear. If people don't read them it's their fault. In this specific case one wishes GitHub would restore the stars but the UI already tries its best. 

If an extension attempts to make it safer, it risks making it worse by breaking it later. I don't see this being worth it for us. If GitHub doesn't change it after the public uproar I assume they also agree that the UI is good enough.
