### ISSUE TITLE
Add support for branches with a slash in `useful-not-found-page`

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5676]
### Description

I stumbled [a broken file](https://github.com/pages-themes/primer/blob/master/thumbnail.png) and it seems GitHub now shows a banner for missing files natively:

<img width="687" alt="image" src="https://user-images.githubusercontent.com/44045911/171989057-97c7887b-5cc1-426a-a092-fe936852405c.png">

It may be a little confusing to have the useful but not that clear `useful-not-found-page` feature _also_ shown at the bottom.

Proposal:

- Also show `useful-not-found-page` as a banner like the native message. The default style may not be as prominent as ours but we can spice it up if needed.
- Linkifying the names in the native banner if they show up, though `useful-not-found-page` works on more places.

### Example URL

https://github.com/pages-themes/primer/blob/master/thumbnail.png

**Comment by fregante** [comment]
I'd propose to:

- drop their useless banner
- use its information as part of our logic, especially if it correctly works on slashed branches (which completely break our feature, if I remember correctly)

**Comment by fregante** [comment]
> * use its information as part of our logic, especially if it correctly works on slashed branches

It does 🙂 

- 404 https://github.com/pages-themes/primer/tree/dependabot/npm_and_yarn/path-parse-1.0.7/thumbnail.png

<img width="864" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/1402241/171991401-741b77c0-74e1-4933-951b-ae3c0fd36b8f.png">


It doesn't appear on 410 branches though:

- 410 https://github.com/pages-themes/primer/tree/dependabot/npm_and_yarn/y18n-4.0.3/thumbnail.png

From https://github.com/pages-themes/primer/pull/48
