### ISSUE TITLE
Extract new "Close issue" dropdown buttons

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5678]
### Description

Like we do in `one-click-pr-or-gist`

![152473201-868ad7c1-e06f-4826-b808-d90bca7f08b3](https://user-images.githubusercontent.com/1402241/171990947-05ca9d01-03ec-478b-85b3-24ce98862031.png)

(not sure why this screenshot looks so bad, it should be updated)

### Screenshot

<img width="322" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/1402241/171990856-c39de578-ddf5-4bfd-b0af-ff6db6fb275b.png">

### Example URL

Any open issue you can close, like this one

**Comment by FloEdelmann** [comment]
Seems like nobody noticed that the following issue was a duplicate:

* #6883

Anyway, it's fixed in https://github.com/refined-github/refined-github/releases/tag/23.11.1:

* #6973
