### ISSUE TITLE
`open-all-conversations` doesn't appear when selecting conversations

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5679]
### Example URLs

https://github.com/refined-github/refined-github/issues
https://github.com/refined-github/refined-github/pulls

### Extension version

22.5.22

### Browser(s) used

Safari, Chrome

### Description

1. Click "Open all"
2. Nothing happens

Alternatively:

1. Check 1 or more files
2. No "Open selected" appears

https://user-images.githubusercontent.com/1402241/171992568-7b3e8b7f-d0b6-4e14-bd7a-22b018eb0243.mov

**Comment by fregante** [comment]
Broken again? Safari 22.8.1

![text](https://user-images.githubusercontent.com/1402241/183142769-0fd4505c-057f-4ef9-9f0d-5679fff34e8a.gif)

**Comment by cheap-glitch** [comment]
@fregante I think this was on purpose? (see https://github.com/refined-github/refined-github/pull/5687#discussion_r892430242)

**Comment by fregante** [comment]
Indeed the comment was right for "select all" but look at this native GitHub feature:

- 2 clicks, 5 issues selected

![text](https://user-images.githubusercontent.com/1402241/183241566-3b61a446-8aaf-48c6-9999-7e881bf31fec.gif)
