### ISSUE TITLE
Fixed sidebar doesn't work in long threads?

### ISSUE THREAD

**Issue by piranna** [refined-github/refined-github#5681]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/EpicGames/Signup/pull/24

### Extension version

22.5.22

### Browser(s) used

Chrome 102

### Description

Feature from https://github.com/refined-github/refined-github/issues/3349 works properly in all issues and PRs pages, but on https://github.com/EpicGames/Signup/pull/24 right panel don't get fixed when going beyond its limit. In the same repo, https://github.com/EpicGames/Signup/pull/26 works properly. Maybe is related to being a humongous big thread?

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by cheap-glitch** [comment]
This might be a Chrome bug as it's working fine for me in Firefox.

**Comment by piranna** [comment]
> This might be a Chrome

how can we be sure about it?

**Comment by cheap-glitch** [comment]
Actually this is probably working as intended: the feature will not apply if the sidebar is too tall to fit in your browser window. On my desktop it narrowly fits, does it in yours?

**Comment by piranna** [comment]
> On my desktop it narrowly fits, does it in yours?

No, it doesn't fits, it's a bit longer than my browser window. In any case, I think the actual behaviour in that case, should be to scroll just only down to the side bar bottom, or also in that case being able to scroll it independently once that the user has scrolled the page and the header appears. What do you think?

**Comment by fregante** [comment]
Unfortunately it's working as intended, it's the default `position: sticky` behavior. To do anything better than that, we'd either have to:

- use JavaScript (👎)
- use a scrollbar just for the sidebar, which I'm also not particularly a fan of 😰

**Comment by piranna** [comment]
> * use JavaScript to handle the scrolling/positioning (-1)

Agree in not being ok.


> * use a scrollbar just for the sidebar, which I'm also not particularly a fan of cold_sweat

Not too much of a fan, but in fact, I think it's the correct option here... :-/ Not all the time, by setting `overflow: auto`, but just only setting it when the scroll header is shown.
