### ISSUE TITLE
`restore-file` does not work in firefox

### ISSUE THREAD

**Issue by staabm** [refined-github/refined-github#5690]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/redaxo/redaxo/pull/5153

### Extension version

22.5.22

### Browser(s) used

firefox 103a

### Description

I am using refined github on a lot of machines successfully, with a personal token configured.

no matter on which workstation I try, the 'restore file' action from a Pull Request 'Files changed tab' runs into "unprocessible entity" error.

repro
- open a PR you own in Firefox
- open 'Files changed tab'
- click "..." from one of the PRs files
- select 'restore file'

expected
- toast message "restoring..."
- toast message "committing..."
- toast message "success"

actual:
- toast message "restoring..."
- toast message "committing..."
- toast message "unprocessible entity" ❌ 

the error happens on any file I pick of any PR I have submitted

I am using this feature successfully in chrome on the very same pull requests and the very same machine.
I can reproduce the error on macOS and windows11.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by staabm** [comment]
the feature did never work for me in Firefox (its not a recent regression)

**Comment by fregante** [comment]
It works for me

https://user-images.githubusercontent.com/1402241/173736634-1baf9276-0e0e-41be-9f39-bf927faf05dc.mov

Does `update-pr-from-base-branch` work for you? Just to exclude some API/token errors.

Also it'd be good to see:

- any console errors
- the full HTTP response from the Network tab in the developer tools

**Comment by fregante** [comment]
Also:

- open a PR on https://github.com/refined-github/sandbox and try there, to exclude repo-related issues
- are you using any HTTP-related blocker/extension?

It appears to be failing here:

https://github.com/refined-github/refined-github/blob/90edb0f8d458782c4cf0bd3d503a3db9e08b830a/source/features/restore-file.tsx#L73-L76

Also related:

https://github.com/refined-github/refined-github/blob/3733f38e5f597c988db12dd38c6d89c67afb5a9d/source/helpers/dom-utils.ts#L4-L8

**Comment by staabm** [comment]
thanks for your investigation.

> Does [`update-pr-from-base-branch`](https://github.com/refined-github/refined-github/blob/main/source/features/update-pr-from-base-branch.tsx) work for you? Just to exclude some API/token errors.

yep, works for me. using it several times a day.



> * any console errors

![grafik](https://user-images.githubusercontent.com/120441/174240397-0beb4363-a53b-4191-b69c-5a1b73c5f672.png)


> * the full HTTP response from the Network tab in the developer tools

I can't see any http requets after pushing 'restore'

> open a PR on [refined-github/sandbox](https://github.com/refined-github/sandbox) and try there, to exclude repo-related issues

I can reproduce the issue on this repo in https://github.com/refined-github/sandbox/pull/17

> are you using any HTTP-related blocker/extension?

I have a few brower extensions. I just disabled all but refined github.

the error still reproduces

**Comment by fregante** [comment]
I'd like to fix this or else it's likely that this issue will just stay open forever.

Can you try again and copy the "unprocessable entity" request from the developer tools "as cURL"? Just ensure to remove or break the token before pasting it here. I want to see how it compares to a request that is accepted.

Also include the file you're trying to restore (make sure you try this on a small file because it will be part of the cURL)

**Comment by staabm** [comment]
hmm I can no longer reproduce on the sandbox repo with https://github.com/refined-github/sandbox/pull/26

did another test on https://github.com/redaxo/redaxo/pull/5261 and it also works.

not sure why it started working and when!? 🤷
