### ISSUE TITLE
Emojis in commit title breaks `use-first-commit-message-for-new-prs`

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5694]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/sandbox/compare/😱?expand=1

### Extension version

22.5.22

### Browser(s) used

Safari

### Description

<img width="904" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/173626583-c0437cb9-fcc5-4411-a52f-05157eef7d6f.png">

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by yakov116** [comment]
https://github.com/refined-github/refined-github/blob/93e996910c661314f2672f97cbffd78a60a9d14c/source/features/use-first-commit-message-for-new-prs.tsx#L15

We have an issue that we are using the innerHTML to save the "``"code"`"

**Comment by fregante** [comment]
Due to https://github.com/refined-github/refined-github/pull/5402

We can probably replace the innerHTML with textContent

cc @cheap-glitch
