### ISSUE TITLE
`reactions-avatars` stopped working 

### ISSUE THREAD

**Issue by yakov116** [refined-github/refined-github#5698]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github/pull/4526

### Extension version

22.5.22

### Browser(s) used

Chrome

### Description

I see it working sometimes on the first post

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by cheap-glitch** [comment]
Seems like the usernames are now in a `<tool-tip>` element (weird name btw):
```html
<tool-tip for="reactions--reaction_button_component-2ef810" data-direction="n" data-type="description" data-view-component="true" id="tooltip-1655419124213-8135" role="tooltip" class="" style="left: -58.0333px; top: 612.3px;" hidden="">cheap-glitch and fregante reacted with thumbs up emoji</tool-tip>
```

Probably just a couple of selectors that need updating. On the bright side it seems to finally have been unified between regular & review comments :tada:

**Comment by fregante** [comment]
Hopefully they’ll stop messing with them now. 

> weird name btw

Custom elements need a dash in their name.
