### ISSUE TITLE
`user-local-time` not working

### ISSUE THREAD

**Issue by Glennmen** [refined-github/refined-github#5699]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github

### Extension version

22.5.22

### Browser(s) used

Brave Version 1.39.122 Chromium: 102.0.5005.115 (Official Build) (arm64)

### Description

The user local timezone isn't shown anymore in the hover card.
Not sure if it was broken before, I only noticed it now.

From what I could see the feature hasn't been removed.

<img width="474" alt="CleanShot 2022-06-17 at 13 30 19@2x" src="https://user-images.githubusercontent.com/11406433/174290180-8add30c6-99a6-43a0-94c5-e12b1e4f6f0f.png">

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by yakov116** [comment]
https://github.com/refined-github/refined-github/blob/04110bf6327322fb661ec41d268f00d6651a5b37/source/features/user-local-time.tsx#L146

Look like `div.d-flex.mt-3 > div.overflow-hidden.ml-3` changed a drop

**Comment by fregante** [comment]
Heh, selectors like that are always short-lived.

**Comment by Glennmen** [comment]
I guess so.

I did find this in the README but it doesn't look up to date anymore: https://user-images.githubusercontent.com/1402241/69863648-ef449180-12cf-11ea-8f36-7c92fc487f31.gif
