### ISSUE TITLE
How do I disable the header alignment?

### ISSUE THREAD

**Issue by LorenDB** [refined-github/refined-github#5700]
[This GIF from the README](https://user-images.githubusercontent.com/1402241/86574587-587f3800-bf76-11ea-9961-5c25cdb6e357.gif) shows off the header realignment. I'd like to disable this feature; however, the CSS rule (unsurprisingly) uses `!important`, so it seems to me that this can't be turned off easily.

Is there a way I can override this and leave the header at the left? I'm a C++ guy, not CSS, so I'm unsure of how to proceed.

**Comment by fregante** [comment]
There are many issues about it. 

!important can be overridden with a stronger selector.

**Comment by LorenDB** [comment]
Ah, I found #4519 which has the fix. Maybe if it is such a common request one of the issues about this should be pinned for CSS n00bs like me.

**Comment by fregante** [comment]
This feature has now been dropped in https://github.com/refined-github/refined-github/pull/6247
