### ISSUE TITLE
User hovercards in sticky issue sidebar aren't sticky

### ISSUE THREAD

**Issue by LorenDB** [refined-github/refined-github#5701]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github/issues/5690

### Extension version

22.5.22

### Browser(s) used

Opera 87.0.4390.45

### Description

1. Turn on sticky issue sidebars.
1. Browse to a long(ish) issue.
1. Scroll down to the point that the sidebar becomes sticky.
2. Hover over a user icon in the participants section.
3. Scroll down some more.
4. Note that the hovercard doesn't stick to the user avatar as it would in regular GitHub.

Screenshot:
![image](https://user-images.githubusercontent.com/55629213/174315267-0ff058f6-8c89-43b1-a8e2-5e852e31147b.png)

**Comment by yakov116** [comment]
Can you take a screenshot?

**Comment by LorenDB** [comment]
Done and edited in.

**Comment by fregante** [comment]
Thanks for the report. Unfortunately this isn’t something we can fix. The hovercard lives outside the sidebar so it can never be sticky when the sidebar is. There’s probably some JS hack via listeners to do this, but it’s totally not worth it.

**Comment by LorenDB** [comment]
Ah, I see. No problem! I would have never discovered it anyway if I hadn't accidentally hovered over an avatar before scrolling, so it's probably not a deal-breaker for anyone.
