### ISSUE TITLE
Add "mark all as read/unread" dropdown to `unwrap-unnecessary-dropdowns`

### ISSUE THREAD

**Issue by FloEdelmann** [refined-github/refined-github#5704]
### Description

Go to your notifications and select a few checkboxes. You can easily mark them all as done or unsubscribe, but marking as read or unread requires an additional click to open the dropdown (and it's less discoverable).

`unwrap-unnecessary-dropdowns` could unwrap the dropdown items, so they appear as regular buttons. There is enough space in that bar for two additional buttons.

### Screenshot

![grafik](https://user-images.githubusercontent.com/202916/174452389-49c9f793-8f23-46d9-bbc7-c37f9c92cad2.png)

### Example URLs

https://github.com/notifications

**Comment by fregante** [comment]
It makes sense, but there's only a problem (which already exists):

<img width="590" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/174467882-f2c8a38b-6161-4fe4-87de-444c1dbb8526.png">

Similar to:

- #5071

**Comment by FloEdelmann** [comment]
> We can unwrap it only above a certain resolution

Might not be needed if #5707 is accepted.

**Comment by fregante** [comment]
Still needed:

- unwrap
- enable horizontal scrolling instead of wrapping

The wrapping causes jumping on mobile. Also see:

- https://github.com/refined-github/refined-github/pull/6655

**Comment by fregante** [comment]
2 years, no PR, not worth it

**Comment by fregante** [comment]
Let's try again
