### ISSUE TITLE
`comments-time-machine-links`: Cannot read properties of null (reading 'querySelector')

### ISSUE THREAD

**Issue by DavidMichonneau** [refined-github/refined-github#5712]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/mkls/mock-amqplib/pull/25/files (doesn't happen for this url, but only can reproduce in private repo)

### Extension version

22.5.22

### Browser(s) used

Chrome 102.0.5005.115

### Description

Opening the fils changed tab of a PR, I cannot see the actions on the top: "Files Filters, Conversations, Jump to"
<img width="1779" alt="Screenshot 2022-06-20 at 15 14 36" src="https://user-images.githubusercontent.com/79507920/174609784-a1376411-2665-4da6-9289-c531f3cbf60e.png">

```
TypeError: Cannot read properties of null (reading 'querySelector')
    at init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:7229:107)
    at runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3913:26)
    at setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3921:40)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3946:35
```

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by ELLIOTTCABLE** [comment]
I'm experiencing this as well, but on GitHub Enterprise, not a private GitHub-hosted repository.

(FireFox 101.0.1 (64-bit), Refined GitHub 22.7.1)

```
init@moz-extension://773abd7e-7b7e-45cd-9c1c-3cec0deb32a9/refined-github.js:7194:34
runFeature@moz-extension://773abd7e-7b7e-45cd-9c1c-3cec0deb32a9/refined-github.js:3915:26
setupPageLoad@moz-extension://773abd7e-7b7e-45cd-9c1c-3cec0deb32a9/refined-github.js:3921:40
add/<@moz-extension://773abd7e-7b7e-45cd-9c1c-3cec0deb32a9/refined-github.js:3946:35
```

**Comment by fregante** [comment]
Thank you for the reports!

Closing because:

- the first error is most likely related to `quick-pr-diff-options` breaking that view, which has long been fixed
- the second error has also likely been fixed since the underlying code was changed and GHE likely updated as well.

Please open a new issue with updated info and screenshot if you encounter this issue or a similar issue.
