### ISSUE TITLE
Support “For you” in `infinite-scroll`

### ISSUE THREAD

**Issue by Yash-Singh1** [refined-github/refined-github#5716]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/

### Extension version

22.5.22

### Browser(s) used

Chrome

### Description

1. Go to the "Following" tab on your GitHub dashboard
2. Reload
3. Notice that the infinite scroll is working here
4. Go to the "For You" tab on your GitHub dashboard
5. Note that the infinite scroll isn't working here
6. Reload
7. Note that the infinite scroll is working now (sometimes it doesn't work for infinite scroll either)

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by kidonng** [comment]
Almost opened a new issue for this. Despite still marked as Beta, this is [announced almost 5 months ago](https://github.blog/2022-03-22-improving-your-github-feed/), I think it's fine to support it. Even if things break, it's just the feed won't load automatically.
