### ISSUE TITLE
`stop-pjax-loading-with-esc` is broken

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5723]
1. Click the **Code** tab above
2. Press ESC

- Due to #5719 

Events before: https://github.com/defunkt/jquery-pjax
Events now: https://turbo.hotwired.dev/reference/events

There's no pjax:error equivalent and probably the feature needs to be rethought

**Comment by cheap-glitch** [comment]
I'm still on `v22.5.22.` and it works for me

**Comment by fregante** [comment]
Related:

- https://github.com/hotwired/turbo/blob/700c921838d7e22b18c19200cfa6cc39cb4ad09d/src/util.ts#L86
- https://github.com/hotwired/turbo/issues/619  🤞
