### ISSUE TITLE
`show-whitespace` don't appear in code blocks after editing

### ISSUE THREAD

**Issue by ajmeese7** [refined-github/refined-github#5729]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/os-js/osjs-server/pull/58#issuecomment-1166689579

### Extension version

22.6.25

### Browser(s) used

Brave

### Description

When you post a block of code as part of a comment on a PR (and likely also on gists/issues), this extension shows the tabs and/or spaces that are included in the code block, indicated by either dots or arrows.

When you edit a block of code then save your edits, these dots and arrows are not shown until the user manually refreshes the page.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by fregante** [comment]
This has been discussed before but I can’t find it, it was probably for another feature. 

There are some situations where GitHub updates comments and our features are subsequently lost. It would be great to catch these instances but I worry that it’d become too heavy to track. 

We recently made some changes around that though:

- https://github.com/refined-github/refined-github/issues/2852
