### ISSUE TITLE
quick-review feature stopped working

### ISSUE THREAD

**Issue by jalopez** [refined-github/refined-github#5730]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/facebook/react/pull/24793/files

### Extension version

22.6.25

### Browser(s) used

Chrome 103.0.5060.53 MacOs arm64

### Description

The `quick-review` extension stopped working. All review boxes fallback to the original Github implementation and buttons are the original ones. It happens in all PRs. No errors in console. It used to work until couple of weeks ago

![image](https://user-images.githubusercontent.com/259623/175876975-3a216245-1930-4b71-bc5b-bc5ed5bb3bb7.png)

Thanks for this extension! It is super useful :) 

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by fregante** [comment]
Thanks for the report @jalopez. Could you be experiencing https://github.com/refined-github/refined-github/issues/5719?

Did you take the screenshot when “it’s not working”? Because I don’t see a problem in it

**Comment by fregante** [comment]
> reinstalling the the extension did the trick

It's possible that Chrome occasionally refuses to update the extension, it's frustrating really. My own Chrome was stuck on 22.4.1 and "Update extensions" did nothing to change that.
