### ISSUE TITLE
"Add an optional extended description..." doesn't auto-populate with PR title

### ISSUE THREAD

**Issue by sgbaird** [refined-github/refined-github#5731]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/sparks-baird/CrabNet/pull/31

### Extension version

22.6.25

### Browser(s) used

Google Chrome Version 103.0.5060.66 (Official Build) (64-bit)

### Description

Video of reproducing the error: https://www.screencast.com/t/tGqApBj4d

Open a PR and click "Merge Pull Request". It's not auto-populated like how it is with the extension disabled.

![image](https://user-images.githubusercontent.com/45469701/176042521-8c6f22dd-cd04-440a-aa4d-7d934473585f.png)

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [x] Console errors, if any

**Comment by fregante** [comment]
Are you referring to `clear-pr-merge-commit-message`?

**Comment by sgbaird** [comment]
@fregante didn't realize that was a feature! My bad. Disabling that restored the behavior I was looking for, which is to auto-populate the description with the PR title. Will try to be more thorough with searching through existing feats next time.

Thank you!

**Comment by fregante** [comment]
No worries, we have a lot of "invisible" features
