### ISSUE TITLE
`sticky-file-header` causes edit file header when scrolling to be hidden

### ISSUE THREAD

**Issue by sgbaird** [refined-github/refined-github#5732]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github/edit/main/readme.md

### Extension version

22.6.25

### Browser(s) used

Google Chrome Version 103.0.5060.66 (Official Build) (64-bit)

### Description

Place the cursor on the left of the page and scroll down.

Video demo: https://www.screencast.com/t/xtiZtmJ9A

![image](https://user-images.githubusercontent.com/45469701/176042349-2c94a31b-1b99-4eee-9e94-6a82b1acc0aa.png)

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by yakov116** [comment]
Assuming the selector changed ⬇️ (The .not).
https://github.com/refined-github/refined-github/blob/af9ba7b678209f6daa5f77a1b13db903c0eca007/source/features/sticky-file-header.css#L2

**Comment by kidonng** [comment]
Ouch, caused by #5717, my bad. I didn't notice this since it used to "just work" with old `0px` 🥲
