### ISSUE TITLE
`useful-not-found-page` appears twice

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5733]
### Example URLs

https://github.com/cheap-glitch/delegate-it/tree/support-signal

### Extension version

22.6.25

### Browser(s) used

Safari and Chrome

### Description

<img width="984" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/176104585-1d152d82-afa0-4ca8-9c89-ee1948c2ef57.png">

**Comment by iamziike** [comment]
@fregante would love to summit a pr for this issue

**Comment by fregante** [comment]
Thank you @iamziike but this is actually a broader problem introduced by #5720
