### ISSUE TITLE
Add annotations, artifacts and summary to specific job run page

### ISSUE THREAD

**Issue by ssbarnea** [refined-github/refined-github#5737]
### Description

While github is able to nicely display information about current CI with **[summary](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/), artifacts and annotations**, these are available only on Summary page (one per run) and that page is not even directly accessible from the pull-request page.

While browsing a specific job run there is no visual indication that this particular job produces any of the optional 3 outcomes. User must click left-side Summary links to visit these.

We need to give some visual indication that these exists and allow user to see them without having to leave that current job run page.

For start it should be enough to just display an icon that indicates that content exists on summary page. Later this could be a roll-over popup maybe?

### Screenshot

TBH based on what people suggest and what is easier to implement.

### Example URLs

https://github.com/ansible/vscode-ansible/runs/7089780746?check_suite_focus=true

**Comment by fregante** [comment]
Visually similar feature: `scheduled-and-manual-workflow-indicators`

**Comment by fregante** [comment]
Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it.
