### ISSUE TITLE
Some HTML elements get inserted twice

### ISSUE THREAD

**Issue by kytta** [refined-github/refined-github#5738]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/fltk/fltk  
https://github.com/refined-github/refined-github

### Extension version

22.6.25

### Browser(s) used

Firefox

### Description

On some repos, DOM elements that RG inserts (like the “Bugs” tab) get inserted twice:

<img width="1154" alt="Screenshot of fltk/fltk" src="https://user-images.githubusercontent.com/6566248/176194729-c0a29d61-41b8-4c2b-a0b4-102ef6be743e.png">

There are some console warnings, but all of them come from GitHub itself. The extensions doesn't report anything.

Perhaps this is related to #5733

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by yakov116** [comment]
Assumi9ng because of https://github.com/refined-github/refined-github/issues/5719

**Comment by fregante** [comment]
Found the reason for this and: `turbo:load` is fired on the first load too, not just on ajaxed loads 😖

**Comment by kidonng** [comment]
I still see this on main branch, though I triggered it via navigate back and forward (https://github.com/EnixCoda/Gitako/commits/develop)

<img width="442" alt="image" src="https://user-images.githubusercontent.com/44045911/176465690-88555cd9-92be-4f9b-ac01-7c24d99980f6.png">

**Comment by fregante** [comment]
Just now I saw this issue on load for the first time (Safari, store version), but I can't replicate that duplication issue anywhere
