### ISSUE TITLE
Render markdown inside of a commit message

### ISSUE THREAD

**Issue by devinrhode2** [refined-github/refined-github#5741]
### Description

Commit messages, while ideally are formatted with lines no longer than 80 characters, do not necessarily need to be rendered in monospace font, and I think developers generally like to use markdown syntax in extended commit messages.

Therefore, I think it would be nice to render commit messages as standard markdown, just like we see anywhere else in github.

### Screenshot

![CleanShot 2022-06-28 at 22 50 00](https://user-images.githubusercontent.com/539816/176347543-786b3e72-2565-4819-9ae8-e32bd6c1b5c7.png)

### Example URLs

[devinrhode2/sample-commit-msg-with-markdown@`3858ad9` (#1)](https://github.com/devinrhode2/sample-commit-msg-with-markdown/pull/1/commits/3858ad9b85739bfc510e96e319e9fe7f7d53b4b7)

**Comment by fregante** [comment]
There are too many reason to not do this in Refined GitHub, unfortunately:

- too big/heavy
- we can't possibly support syntax highlighting on those code blocks too
- Markdown can be interleaved with HTML, which we'd have to inject via `innerHTML`
- too easy for us to introduce XSS
- most people don't expect that area to be rendered, so either nobody uses it or it breaks expectations

Maybe you can ask GitHub to render it

**Comment by nedtwigg** [comment]
- gitcasso does markdown syntax highlighting on issues and comments, moving that into commit messages is a TODO: https://github.com/diffplug/gitcasso/issues/113
