### ISSUE TITLE
Buttons for bold, italics, etc should not be hidden on keyboard-less devices

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5743]
### Description

No way for me to set text as bold 🥲  

### Screenshot

 
![A5E6E952-5323-47C4-8574-4CE3EF3A4259](https://user-images.githubusercontent.com/1402241/176374379-06fbcc7a-2444-4e16-9718-8fdace859a3e.jpeg)

### Example URLs

https://github.com/refined-github/refined-github/issues/new?assignees=&labels=enhancement%2C+under+discussion&template=2_feature_request.yml

**Comment by cheap-glitch** [comment]
How do you enter text in the first place if there's no keyboard? Voice input?

**Comment by cheap-glitch** [comment]
> I mean no physical with ctrl/cmd keys

But then can't you just type Markdown directly? I agree it's a bit annoying on a phone keyboard, since you have to go back and forth between letters and special chars.

**Comment by fregante** [comment]
> I agree it's a bit annoying

That's the whole point of this request 😁
