### ISSUE TITLE
Drop `forked-to` feature

### ISSUE THREAD

**Issue by yakov116** [refined-github/refined-github#5745]
### What I don't like

https://github.blog/changelog/2022-06-29-the-repository-fork-button-now-displays-existing-forks/ !!

@fregante 🎉 The first time I have seen them mention a user in a blog bost!

**Comment by yakov116** [comment]
Anyone that takes want to do this pr. Its not just a drop the file. 
We use code from this file in other places and needs to be done slowly.

**Comment by fregante** [comment]
Neato!! 

> The first time I have seen them mention a user in a blog bost!

Second: https://github.blog/2018-08-28-announcing-paper-cuts/

<img width="565" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/1402241/176465970-e11af07f-208d-4380-b56b-345e7b30e3cd.png">

**Comment by yakov116** [comment]
Whats going on with you and closing issues today?

**Comment by fregante** [comment]
I press cmd+enter, it defaults to "Close with comment" 😅

**Comment by kidonng** [comment]
> I press cmd+enter, it defaults to "Close with comment" 😅

I can see this default make sense for _some_ maintainers with busy repos, otherwise it sounds like a potential feature for Refined GitHub (wink)

**Comment by fregante** [comment]
I think it's a momentary GitHub bug and I'm tempted to write a user script to prevent that 😰

**Comment by fregante** [comment]
<img width="115" alt="Screen Shot 16" src="https://user-images.githubusercontent.com/1402241/176484617-0416c7bc-a533-4b44-ad77-35c0319242ed.png" align=left> <img src="https://user-images.githubusercontent.com/1402241/176485083-f944aaf8-9b3c-46b2-abe1-18f153da7750.png" align=right>

**Comment by kidonng** [comment]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/44045911/178304635-bc3b9783-6bef-4af2-bed8-62af4a55ad01.png">
