### ISSUE TITLE
Possible to automatically merge a PR?

### ISSUE THREAD

**Issue by devinrhode2** [refined-github/refined-github#5747]
I don't know if I accidentally merged a PR, or if this extension automatically triggered a merge. I'm guessing I accidentally merged the wrong PR, but, I'm curious, does it seem even remotely possible that this extension incidentally merge a PR? Does this extension even contain code that can cause a PR to merge? (jquery selector for merge button, some api endpoint that triggers merge?)

**Comment by fregante** [comment]
We do have code to merge a PR, but only after the user clicks "Merge" in the first place: `wait-for-checks`

The only way for this to have happened, by mistake, due to Refined GitHub:

1. Click "Merge" while CI is running
2. Click "Cancel"
3. ❌  Refined GitHub forges to cancel the CI observer
