### ISSUE TITLE
How to turn off left padding for repo pages

### ISSUE THREAD

**Issue by PythonCoderAS** [refined-github/refined-github#5749]
The extension adds some padding to the left of the page to align the repo name with the file list. However, I think it looks terrible and I would like to turn it off, but I'm not sure which option controls the align. I tried searching "margin", "padding", and "left" but none of the options that showed up changed the padding.

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/4519

**Comment by fregante** [comment]
This feature has now been dropped in https://github.com/refined-github/refined-github/pull/6247
