### ISSUE TITLE
`#repo-content-pjax-container` is gone

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5751]
### Extension version

main

### Browser(s) used

Chrome

### Description

1. Open https://github.com/refined-github/refined-github/issues
2. `#repo-content-pjax-container` exists
3. Click on Issues tab
4. `#repo-content-pjax-container` is gone, see console error on this line

https://github.com/refined-github/refined-github/blob/5cda3447bf80cca0c64ae5eb79779ecd62fec18e/source/features/dim-bots.tsx#L44

Related code: https://github.com/refined-github/refined-github/search?q=repo-content-pjax-container

However GitHub’s own code is still using this selector too, so it might be a temporary issue. The specific console error could probably be avoided though

**Comment by fregante** [comment]
I was gonna open a new issue to warn against this new `turbo-frame` element I noticed, only to find that it's already causing issues:

<img width="457" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/176497788-29bc159e-f49a-4766-ab3d-835ca4ea564b.png">

**Comment by fregante** [comment]
I think we need to rethink our deduplication strategy.

We've been using `has-rgh` to determine whether RGH was run on the page after navigation, but we can already know this: if the navigation is caused by back/forward, we’ve already been on the page, right?

The issue has historically existed because we never distinguished between a new navigation and a history navigation: both of them triggered `pjax:end`. In practice though we always have `popstate` which can tells us whether a load is new or cached.

Can we replace all `deduplicate` checks with a single `isPopstateEvent` check? `deduplicate: false` should be preserved though. 

#### Related

- https://github.com/hotwired/turbo/issues/620

**Comment by levrik** [comment]
@fregante Hovering bot commits doesn't reveal the full details anymore since 2 weeks. Could this be related to this issue or should I open a new issue?

**Comment by fregante** [comment]
Related, but can you open a new issue?

**Comment by levrik** [comment]
@fregante Done: https://github.com/refined-github/refined-github/issues/5786

**Comment by kidonng** [comment]
We have a lot on our plate 😅

```shellsession
$ rg -l repo-content-pjax-container | xargs basename -s .tsx | sort
comments-time-machine-links
default-branch-button
dim-bots
index
latest-tag-button
linkify-branch-references
linkify-symbolic-links
quick-review
rgh-feature-descriptions
rgh-linkify-features
same-branch-author-commits
swap-branches-on-compare
useful-forks
```

**Comment by fregante** [comment]
ripgrep has the `-i` flag

```
❯ rg -l -i repo-content-pjax-container
source/features/linkify-branch-references.tsx
source/features/useful-forks.tsx
source/features/quick-review.tsx
source/features/comments-time-machine-links.tsx
source/features/same-branch-author-commits.tsx
source/features/rgh-feature-descriptions.tsx
source/features/latest-tag-button.tsx
source/features/default-branch-button.tsx
source/features/swap-branches-on-compare.tsx
source/features/dim-bots.tsx
source/features/linkify-symbolic-links.tsx
source/features/rgh-linkify-features.tsx
source/features/index.tsx
```

**Comment by kidonng** [comment]
Indeed, I have `--smart-case` aliased.

**Comment by fregante** [comment]
Same goes for the `.repository-content` selector, which targets the same element. It causes:

- https://github.com/refined-github/refined-github/issues/6077
