### ISSUE TITLE
Show the watch / fork count

### ISSUE THREAD

**Issue by Zenoo** [refined-github/refined-github#5753]
I didn't find any option to re-enable the watch and fork counts.  
Is there any way to show them?

**Comment by MarcusOtter** [comment]
It says it should be hidden "on smaller screens" but it occurs for me on my 2560×1440 screen. I'd also like to have them visible.

**Comment by Zenoo** [comment]
Yeah, mine is a 1440p too

**Comment by MarcusOtter** [comment]
https://github.com/refined-github/refined-github/issues/5406 has CSS to re-enable it

**Comment by yakov116** [comment]
> Undo the CSS:
> ```css
> .pagehead-actions :is(#repo-network-counter, #repo-notifications-counter) {
> 	display: inline-block !important;
> }
> ```

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/5406
