### ISSUE TITLE
In PR review: When a file is marked as "Viewed" scroll down a little so that the cursor is automaically on top of the next file

### ISSUE THREAD

**Issue by raed667** [refined-github/refined-github#5756]
### Description

This is a feature in Gitlab. 

When reviewing a PR, and marking multiple files as "viewed" quickly. It would be nice for the window to scroll down so that the cursor is aligned with the next file's checkbox. 

### Example URLs

https://ibb.co/G7zzHRQ

**Comment by kidonng** [comment]
> This is a feature in Gitlab.

Could you record a screencast?

This is probably to niche to be included in Refined GitHub, but I would like to write a user script for this.

**Comment by raed667** [comment]
@kidonng thanks for the reply here is a recording https://www.loom.com/share/f8ea26d6c9244f198cdfb487c3f6cf84
