### ISSUE TITLE
`clean-conversation-sidebar` wrongly hides projects

### ISSUE THREAD

**Issue by akien-mga** [refined-github/refined-github#5757]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/godotengine/godot/issues/62552

### Extension version

22.6.25

### Browser(s) used

Firefox Nightly 104

### Description

Refined GitHub is wrongly hiding projects assigned to issues which are using the older GitHub Project format (now renamed to "Projects (classic)" and I suspect that's what broke RG's logic for it).

Here's how it looks without RG:

![image](https://user-images.githubusercontent.com/4701338/176671472-d6734006-cf9f-42aa-9b49-068afb94f809.png)

And with RG, video of refreshing the page (don't mind the lock symbol, I made it public afterwards):

https://user-images.githubusercontent.com/4701338/176671593-abe3ecd4-4be1-44ec-a241-895a4edbd6c6.mp4

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by akien-mga** [comment]
Actually it's also failing with "Projects (beta)" links, e.g. here: https://github.com/godotengine/godot-proposals/issues/4548

Without RG:

![image](https://user-images.githubusercontent.com/4701338/176684074-e8cca662-ddd3-4fed-a2cf-135da8cc5bc7.png)

With RG:

![image](https://user-images.githubusercontent.com/4701338/176684144-e5bd27d7-d81d-4d47-b864-76c74087347d.png)

**Comment by Wenderson-P** [comment]
The Projects reappeared after I turned off the  `clean-conversation-sidebar` setting

**Comment by iamziike** [comment]
The problem lies here
https://github.com/refined-github/refined-github/blob/09466a8bd3e87e1f261ab463b0cf08514e581db7/source/features/clean-conversation-sidebar.tsx#L45-L47

The heading.nextElementSibling?.firstElementChild is null when passed a selector here 
https://github.com/refined-github/refined-github/blob/09466a8bd3e87e1f261ab463b0cf08514e581db7/source/features/clean-conversation-sidebar.tsx#L120

I thought about a solution where I pass the number of "steps" to take get the firstElementChild 
steps =1 ===> heading.nextElementSibling?.firstElementChild
steps =2 ===> heading.nextElementSibling?.nextElementSibling?.firstElementChild

```typescript 
function cleanSection(selector: string, step:number = 1): boolean {
	const container = select(selector)?.closest('form, .discussion-sidebar-item');
	if (!container) {
		return false;
	}

	const heading = select(':scope > details, :scope > .discussion-sidebar-heading', container)!;

	// Magic. Do not touch.
	// Section is empty if: no sibling element OR empty sibling element
	if (step === 1 &&  heading.nextElementSibling?.firstElementChild) {
		return false;
	}

	if (step === 2 &&  heading.nextElementSibling?.nextElementSibling?.firstElementChild) {
		return false;
	}

	const section = container.closest('.discussion-sidebar-item')!;
	if (canEditSidebar()) {
		getNodesAfter(heading).deleteContents();
		section.classList.add('rgh-clean-sidebar');
	} else {
		section.remove();
	}

	return true;
}
```

Ps. I was going for a solution where I did not have to change a bunch so WDYT?

**Comment by fregante** [comment]
how dare you touch it 😰 😜 

https://github.com/refined-github/refined-github/blob/09466a8bd3e87e1f261ab463b0cf08514e581db7/source/features/clean-conversation-sidebar.tsx#L43

The magic broke and now `heading.nextElementSibling` points to a new intermediate element:

<img width="396" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/176991917-f8e8d55c-bb8c-4139-925d-02c65ab7df43.png">

I think we should just replace the line with something more specific that covers every scenario (milestones, projects, linked issues):

```js
if (!heading.closest('form').querySelector('icon, progress, etc')) {
	return false
}
```

`'icon, progress, etc'` would be a selector for elements that appear only if these sections are full. It's probably `.Progress, .octicon-table, [data-hovercard-type]` but it needs testing to ensure it doesn't match elements inside the dropdown/selector

**Comment by iamziike** [comment]
@fregante ok, I'll like to work on it but to clarify we are ditching the "Magic" right

**Comment by fregante** [comment]
Correct. The piece of code I suggested replaces the magic condition

**Comment by fregante** [comment]
Oof, can’t wait to turn this feature into a CSS-based feature thanks to the `:has()` selector. So many possibilities!

**Comment by fregante** [comment]
Thank @iamziike 🎉

**Comment by matschaffer** [comment]
Indeed! Sorry @iamziike - I thought the issue "closed" timeline would have mentioned the PR author. Guess not 😊  

Great to have it fixed and back to using Refined Github!

**Comment by marcphilipp** [comment]
It seems this is still disabled (in Firefox) with 22.7.20, isn't it?

<img width="626" alt="image" src="https://user-images.githubusercontent.com/214207/180138670-fc267795-13ba-40e0-9b22-448f8dd4bf41.png">

**Comment by fregante** [comment]
It was disabled via [YOLO](https://github.com/refined-github/yolo/blob/main/broken-features.csv). Clear your cache (options page) to see it work again
