### ISSUE TITLE
Select/unselect all features

### ISSUE THREAD

**Issue by ibrahima** [refined-github/refined-github#5760]
### Description

Hi! Refined GitHub is pretty cool and has a lot of features. But it does have a performance impact, and I'd really like to limit the impact by selectively enabling features rather than having them all enabled and opting out of features I don't want. Would it be possible to add a "select all"/"unselect all" button so that we could do this more easily? Thanks!

### Example URLs

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/3535

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/2684

**Comment by amithm7** [comment]
Also, an option to disable new features by default would be nice.
