### ISSUE TITLE
Show notice of comments hidden in issues sidebar

### ISSUE THREAD

**Issue by jtagcat** [refined-github/refined-github#5764]
### Description

![image](https://user-images.githubusercontent.com/38327267/177013089-0ea0b4cb-3bf1-4a78-8237-44393603de18.png)

I don't always notice this in issues. I search in page (Ctrl-F) for the bit I'm about to add, for duplicates. Sometimes I don't notice that some comments are hidden.

### Screenshot

![image](https://user-images.githubusercontent.com/38327267/177013210-33785349-3d2a-4226-b396-d7626225ca0c.png)

(or/and in/near the comment box)

### Example URLs

https://github.com/prettier/prettier/issues/7475

**Comment by jtagcat** [comment]
![image](https://user-images.githubusercontent.com/38327267/177013443-3e8fa11f-371e-4a75-892c-b92f1b891472.png)

This would probably be better.

**Comment by fregante** [comment]
Not a bad idea. I’d probably make it less prominent by adding it in the header:

> (Open) 123 comments (23 collapsed)

Clicking on “collapsed” scrolls to the block you mentioned. We can’t actually “expand all”, this has been requested several times.

**Comment by jtagcat** [comment]
Could a notice of 'all not loaded' / scroll to the next block / show 'all loaded' be shown? Sometimes It's quite annoying to find the next block to load.

**Comment by fregante** [comment]
> > (Open) 123 comments (23 not loaded)

This would be the notice

**Comment by cheap-glitch** [comment]
> Sometimes It's quite annoying to find the next block to load.

FYI you can alt-click the "Load more" button to load everything automatically (it's a RGH feature).
