### ISSUE TITLE
Allow more bug labels

### ISSUE THREAD

**Issue by Xenfo** [refined-github/refined-github#5784]
### Description

I'd like more labels to be considered as bugs to show up on the `Bugs` tab. For example, I use `T - bug` which stands for `type: bug`.

### Example URLs

https://github.com/refined-github/refined-github

**Comment by Xenfo** [comment]
Then maybe an option to allow for custom regexes on top of predefined ones would be better?

**Comment by busches** [comment]
@Xenfo Please see https://github.com/refined-github/refined-github/issues/2960#issuecomment-606765658 We support a lot of options already, https://github.com/refined-github/refined-github/blob/main/source/features/bugs-tab.tsx#L15, including the unabbreviated version you're using.

**Comment by fregante** [comment]
Thoughts on matching `/[any separator]bug$/`. I don’t know how common “not a bug” actually is

**Comment by yakov116** [comment]
That would include `unconfirmed bug` or similar which are very common

**Comment by fregante** [comment]
What if we get all the labels containing the word “bug” and get the shortest one?

**Comment by yakov116** [comment]
I'm not very pro that. We have not had any requests in a while and don't think the logic is worth changing.

The only think is now we can improve is that multiple labels are supported now so it does not have to be limited to one

However changing the logic is pretty complicated , due to the way we currently have the tab detection.

**Comment by fregante** [comment]
> it does not have to be limited to one, 

In the linked comment I mentioned that we *do* prefer one label.  

> the logic is pretty complicated

My suggestion would basically only replace .find() with `.sort(byLength).at(0)`. If anything it’s easier because don’t have to maintain any regexes.

**Comment by fregante** [comment]
Good point, but I wonder if that’s like one in a million chance

**Comment by yakov116** [comment]
What I am trying to really say is that I think we covered everything, there are very few cases that we do not cover.
I don't see any point in changing anything if its not broken.

Like my mother used to say "If it aint broke don't fix it" - I live with "If it aint broke, fix it till it is". 😄
