### ISSUE TITLE
Revealing details on dimmed bot commits not working reliably

### ISSUE THREAD

**Issue by levrik** [refined-github/refined-github#5786]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/levrik/mdi-react/commits/master

### Extension version

22.7.1

### Browser(s) used

Edge (Chromium) 103.x

### Description

As you can see on the video, the reveal of full commit details for bot commits on hover doesn't work initially.
It starts to work when navigating back to the commits view without a full reload (JS navigation).

https://user-images.githubusercontent.com/9491603/177491375-9842b7de-7ecd-486b-b5b3-cf3d1a9ae7cb.mp4

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by kidonng** [comment]
GitHub no longer provides a `.navigation-focus` on hover, that's why it breaks.

**Comment by fregante** [comment]
I think it’s also due to the missing pjax container. I keep seeing that error in the console inside the timeout

**Comment by kidonng** [comment]
Ah, right. `.rgh-dim-bots--after-hover` is also missing.

**Comment by levrik** [comment]
@kidonng But as shown in the video, everything works when the commit history isn't opened directly via link. I'm wondering a bit why GitHub isn't offering this `.navigation-focus` class on hover on initial load but still after in-app navigation?
