### ISSUE TITLE
Bad `sticky-file-header` position on PRs coming from notifications

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5800]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github/pull/5735/files

but you need to come from a notification:

1. Open https://github.com/notifications
2. Visit any PRs that lands you on PR Files

### Extension version

22.7.1

### Browser(s) used

Safari 

### Description

The weird part is that if you refresh the page, then it works correctly:

![before](https://user-images.githubusercontent.com/1402241/177942576-1515b4ba-fc9a-4a75-a217-11beabee8659.gif)

Possible fix:

- Restore `:not(.sticky-file-header)` from [`c5ac0df` (#5735)](https://github.com/refined-github/refined-github/pull/5735/commits/c5ac0df7a14cdb66279caec01591d655d9fecff5)

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by kidonng** [comment]
We need to add this part back too:

https://github.com/refined-github/refined-github/blob/f11c40645726a5553f7ff49a05cc22550bbffc17/source/features/sticky-file-header.css#L9-L12

**Comment by fregante** [comment]
> for the dropdown

? Screenshot plz
