### ISSUE TITLE
Fix fixed header flicker on mobile

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5802]
### Description

GitHub has had this bug for the longest time. Super annoying. I wonder if it can be fixed by a plain `flex-wrap`

### Screenshot

https://user-images.githubusercontent.com/1402241/177983517-e22736fb-c071-4eef-bc02-c75da31f00ac.MOV

### Example URLs

 [`f1c7e3e` (#5845)](https://github.com/refined-github/refined-github/pull/5845/commits/f1c7e3e5fe25b86be9affc4f411917d7a2408c88) 

https://github.com/refined-github/refined-github/commit/f1c7e3e5fe25b86be9affc4f411917d7a2408c88

Even worse if there’s a notification bar.

**Comment by kidonng** [comment]
Interesting, I haven't seen similar stuff on Chrome mobile.

**Comment by cheap-glitch** [comment]
> Interesting, I haven't seen similar stuff on Chrome mobile.

It might be a browser bug. I remember Firefox mobile having a lot of trouble rendering `position: sticky` elements.

**Comment by fregante** [comment]
I see they fixed something that sounds like this. I’ll have to download and test it https://twitter.com/jensimmons/status/1549814445572083713

**Comment by fregante** [comment]
Nope


https://user-images.githubusercontent.com/1402241/180355231-61f4c867-2b00-485a-92af-c6c74747ed63.MOV

**Comment by fregante** [comment]
No one cares 🥲

**Comment by AlexSkrypnyk** [comment]
Still happening

**Comment by fregante** [comment]
Can't repro anymore 🙌

**Comment by dylanatsmith** [comment]
I’d never seen this before but FYI we have a PR up to fix this natively.

**Comment by fregante** [comment]
@dylanatsmith thank you for the update!
