### ISSUE TITLE
`first-published-tag-for-merged-pr` now nags you to make a release

### ISSUE THREAD

**Issue by jack1142** [refined-github/refined-github#5811]
### What I don't like

I don't like being nagged by this feature with the "Now you can release this change" and "This PR seems to be unreleased" notices. I do like the rest of it:
![image](https://user-images.githubusercontent.com/6032823/178162581-978d0537-f01e-48b1-adb8-4c06846e6ca0.png)

Would it be possible to split this feature into two so I could disable the nagging one while keeping the other?

**Comment by fregante** [comment]
See https://github.com/refined-github/refined-github/pull/5769#issuecomment-1179116739

**Comment by jack1142** [comment]
A bit unfortunate I guess but thanks so much for a user-style workaround for this, it works great :+1:
