### ISSUE TITLE
`open-issue-to-latest-comment` not working on AJAX navigation

### ISSUE THREAD

**Issue by yakov116** [refined-github/refined-github#5813]
### Description

Only working when I open in a new tab.

### How to replicate the issue

https://github.com/refined-github/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc click on the icon

### Extension version

22.7.7

### Browser(s) used

Chrome

**Comment by kidonng** [comment]
Error on `isPRCommit`: [`7e8bb26` (#2182)](https://github.com//refined-github/refined-github/pull/2182/commits/7e8bb264cda190a5ce2e09e51196cb8f4b230696)

```
refined-github.js:8642 Uncaught TypeError: Cannot read properties of undefined (reading 'closest')
    at addToConversation (refined-github.js:8642:200)
    at runAdd (refined-github.js:22353:20)
    at applyChanges (refined-github.js:22269:7)
    at SelectorObserver.addRootNodes (refined-github.js:22789:3)
    at Array.processBatchQueue (refined-github.js:22210:5)
    at MutationObserver.handleMutations (refined-github.js:22244:19)
```

**Comment by yakov116** [comment]
Delete comment I am deleting mine

**Comment by fregante** [comment]
I’m confused. The link is correctly modified but when the page loads via ajax the hash is just lost.

**Comment by kidonng** [comment]
Speaking of hash, there's this GitHub bug when you click a link pointing to the same hash of current page, it will do a ajax load, in rare cases it even scroll the page to the top (thus ignoring the hash).

Example: Open https://github.com/refined-github/refined-github#readme and click the "readme.md" header again

**Comment by fregante** [comment]
Testing a native link to the "latest comment":

- https://github.com/refined-github/refined-github/pull/2028#partial-timeline

And a non-ajaxed link:

- https://togithub.com/refined-github/refined-github/pull/2028#partial-timeline

**Comment by fregante** [comment]
GitHub seems to have fixed the issue 🎉 🙏
