### ISSUE TITLE
`one-click-diff-options` removes the built-in diff options

### ISSUE THREAD

**Issue by nicolasff** [refined-github/refined-github#5820]
### Description

I noticed today that the built-in GitHub diff options on the "Files" tab of a pull request were no longer visible when `one-click-diff-options` was enabled.

I opened a PR that looked like this (some info redacted):
![image](https://user-images.githubusercontent.com/7276/178568945-a58cfbd2-d788-4a56-8b98-5a5ca3b4698d.png)

Notice the "book" icon and the `[•]` icon, these are from the `one-click-diff-options` feature. But usually there are also a few more options from GitHub itself, such as "Changes from all commits…" (or a specific commit), "File filter…", and "Jump to…". These are now missing.

I used Refined GitHub's "Start process to identify a feature" to pinpoint which feature was causing this issue. I went through all the steps and a pop-up said it was due to `one-click-diff-options`. When I disabled this feature, the built-in diff options came back.

With the feature disabled, the same page now looks like this, with the expected diff options:
![image](https://user-images.githubusercontent.com/7276/178571689-833530c8-6720-4908-91d8-51dde0194668.png)

Regardless of whether the feature is enabled, I consistently see an error being logged (twice) in the console on the Files page where I noticed this issue. Both log messages are the same:

```
refined-github.js:5963 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'textContent')
    at isArchivedRepo (refined-github.js:5963:75)
    at refined-github.js:3941:95
    at Array.every (<anonymous>)
    at refined-github.js:3941:82
    at setupPageLoad (refined-github.js:3942:8)
    at refined-github.js:3987:35
```

This is preceded by two errors reported by _different_ features (`clean-repo-tabs` and `more-dropdown-links`), so I'm not sure it's relevant here but I'm including it just in case.

I tried the "Clear cache" suggestion, but it didn't help. This happened with GitHub Enterprise Server.

### How to replicate the issue

I am unable to provide a link, but I tried to reproduce the issue on GitHub.com and was unable to.

### Extension version

22.7.11

### Browser(s) used

Google Chrome version 104.0.5112.39 (Official Build) beta (x86_64)

**Comment by nicolasff** [comment]
@busches sorry, I should have mentioned it. It's 3.1.19.

**Comment by fregante** [comment]
https://github.com/refined-github/refined-github/blob/749b028ca9591155cdcfce5226fbb615796cc625/source/features/one-click-diff-options.tsx#L100-L101

This is likely the line. 

We need a helper to remove textNodes safely instead of just expecting to find them this way, e.g. 

``` JavaScript 
removeText(sibling, /^Changes from/);
``` 

This would act as a selector. Too bad we never got around to using XPath 🤭

**Comment by fregante** [comment]
@nicolasff would you be able to use the debugger in your browser to confirm that that line is hiding the elements?

Alternatively, a screenshot of the nearby DOM in the developer tools (without Refined GitHub) would be more useful.

**Comment by nicolasff** [comment]
Update: here's an annotated screenshot of what's in `originalToggle`, which explains why the entire set of built-in options disappears with the class change:

<img width="1629" alt="image" src="https://user-images.githubusercontent.com/7276/179088568-f53e2c8e-05cf-4742-8847-b36606988a89.png">

**Comment by fregante** [comment]
*Hello,* it’s me, I broke your GHE in https://github.com/refined-github/refined-github/pull/5518 👋 😅

**Comment by ELLIOTTCABLE** [comment]
Seeing this one over here on `GitHub Enterprise Server 3.3.8` as well!

**Comment by fregante** [comment]
Closing this issue because the bug was avoided by disabling the feature on every GitHub Enterprise. If anyone with access to GHE 3.3 wants the feature back, please send a PR. We can probably restore it in 3 months anyway.

**Comment by nicolasff** [comment]
Thanks for the fix @fregante!

**Comment by fregante** [comment]
Related, we had the same issue last December:

- https://github.com/refined-github/refined-github/issues/5039
