### ISSUE TITLE
Many features don't reset across different repositories

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5821]
### Description

With the recent deployment of Turbo on GitHub, more ajax navigation are enabled that used to be impossible. One of them is navigate from one repo to another repo (usually through notifications  or profiles), which used to require a full load of the page.

Whether you like it or not is another topic, but for many Refined GitHub features, it poses a serious issue: we used to implicitly rely on a full load to reset their states across different repos, but that is not the case anymore. This results in them still using old states on a new repository and malfunctioning.

### How to replicate the issue

Example: `latest-tag-button` appears on a different repo with no tag

https://user-images.githubusercontent.com/44045911/178644560-e1741b0c-3a5a-49a6-8fdd-f28d27966852.mov

Example: `highlight-non-default-base-branch` mistakenly use previous repo's default branch

https://user-images.githubusercontent.com/44045911/178644565-c2f9c002-929e-4353-9f73-83e8388c8833.mov

### Extension version

22.7.11

### Browser(s) used

Chrome

**Comment by kidonng** [comment]
Maybe we can `mem` them based on repo? Example for `latest-tag-button`:

```diff
+ import mem from 'mem';

- const getRepoPublishState = cache.function(async (): Promise<RepoPublishState> => {
+ const getRepoPublishState = mem(cache.function(async (repo: string): Promise<RepoPublishState> => {
...snip...
- cacheKey: () => 'tag-ahead-by:' + getRepo()!.nameWithOwner,
+ cacheKey: () => 'tag-ahead-by:' + repo,
...snip...
+ const repo = getRepo()!.nameWithOwner;
- const {latestTag, aheadBy} = await getRepoPublishState();
+ const {latestTag, aheadBy} = await getRepoPublishState(repo);
```

**Comment by fregante** [comment]
Oof, that explains why I saw the wrong “latest tag” a few times. 

This issue also affects API calls that use an empty `repository()` because they’re all locally memoized and I don’t think their key ever depends on the current repo. 

But I don’t think the code you mentioned is affected, right? If cacheKey dynamically calls `getRepo()` then it will always get the latest/correct key. The problem is where we *don’t* use such dynamic key

**Comment by fregante** [comment]
Repro:

1. Open https://github.com/refined-github/sandbox/pulls (it uses a non-standard default branch name)
2. Open the notifications
3. Open any other repo
4. Visit the Pull requests page on that repo
5. See `highlight-non-default-base-branch` showing `main` even if it's the default for the current repo

**Comment by fregante** [comment]
I'm leaving this issue open just in case you still find broken features. I only addressed 2 very common scenarios (`repository()` and `getDefaultBranch`)

This issue would probably cover most of the rest of the issues:

- https://github.com/fregante/webext-storage-cache/issues/34

And this could be nice, but I'm not sure I'll finish it:

- #5839

**Comment by methbkts** [comment]
Thanks for the fix 🥳
it was very annoying
