### ISSUE TITLE
`sticky-file-header` causes dropdown overlap

### ISSUE THREAD

**Issue by guillaumeboehm** [refined-github/refined-github#5823]
### Description

The file dropdown in the compare page is getting obstructed by file titles below.

![photo_2022-07-13_15-23-24](https://user-images.githubusercontent.com/12833794/178744056-67dd5f60-6fc9-473b-b5a1-47cf69759303.jpg)

### How to replicate the issue

I found the bug here https://github.com/x13a/Silence/compare/v1.11.1...master

- Go on a compare page
- Collapse files if the changes are long
- Click on the dropdown icon

The dropdown should be obstructed

### Extension version

22.7.11

### Browser(s) used

Brave

**Comment by fregante** [comment]
We’re going to need to hotfix-disable this CSS feature. I’m not sure if we can actually avoid this. The only way this would be possible is if the open dropdown adds a class so we can kick it up the z-index — or if we had the :has() selector 🥲

**Comment by kidonng** [comment]
This is https://github.com/refined-github/refined-github/issues/5800#issuecomment-1178779392 (kinda strange I missed the notification)

**Comment by cheap-glitch** [comment]
> The only way this would be possible is if the open dropdown adds a class so we can kick it up the z-index

Maybe we could add that class ourselves, using a simple delegated listener for clicks on the dropdown button :thinking:
