### ISSUE TITLE
"Snooze" notification

### ISSUE THREAD

**Issue by humitos** [refined-github/refined-github#5824]
### Description

Hi! I've been using this extension for years and I'm pretty happy with it. I'm not sure what's part of GitHub itself and what's part of this extension at this point. However, when I use a browser that doesn't have the extension enabled, I feel terribly bad and start complaining about all the features that are missing.

Thanks for doing my life easier! ❤️ 

----

One thing that I'd _love_ to have is a feature to "Snooze" a notification so it reminds me to take a look at this notification tomorrow, in 3 days, next week, or a custom date maybe.

As this feature does not exist yet, I've been using Slack for this:

- I just copy the notification link
- Paste it into my private conversation with myself (`Your Name (you)` tab)
- Click on the dots next to the message
- Select "Remind me later" in "Tomorrow"

Instead, if I could just emulate the same behavior on GitHub's notification it would be a killer feature to me.

### Screenshot

![Screenshot_2022-07-13_20-00-05](https://user-images.githubusercontent.com/244656/178800744-460e0c55-b0de-47e3-bfec-9120a2986af3.png)

### Example URLs

https://github.com/notifications

**Comment by fregante** [comment]
Refined GitHub is a collection of small improvements to the interface and this unfortunately is too complex for it. 

I’d suggest this to GitHub. In the meantime the closest since is Saved notifications.

**Comment by cheap-glitch** [comment]
> As this feature does not exist yet, I've been using Slack for this:

I know there's a GitHub app in Slack that can send you updates about the repos you subscribe to. I don't use it myself so I'm not sure, but maybe it could be used as a replacement for native GitHub notifications ­— at least to avoid copying the link to Slack every time.
