### ISSUE TITLE
Add ability to open extra Projects (Beta) fields by default

### ISSUE THREAD

**Issue by archon810** [refined-github/refined-github#5825]
### Description

We're starting to use the new Projects (Beta), and by default the UI loads the project-related fields collapsed like this:
![image](https://user-images.githubusercontent.com/469543/178861843-a209d01a-1f41-4315-b327-db53d980c2ae.png)

This is pretty user-hostile IMO and the "more" button should be opened automatically, like so:
![image](https://user-images.githubusercontent.com/469543/178861925-d9b6bac1-e3cb-4486-afc5-35f4239b6264.png)

Can we please get a feature to do this by default?

Thank you.

### Example URLs

We're using a private repo, but it should appear on the GH issue UI.

Interestingly, the in-project issue UI, which looks like this
![image](https://user-images.githubusercontent.com/469543/178862113-f65799dc-d88f-4ca4-a836-fdb66b3a5092.png)
already uncollapses these values by default, though it still leaves a "Show all fields" link which for me only hides the Repository name. I think the proposed feature could uncollapse this one by default as well.

**Comment by fregante** [comment]
Sorry but Refined GitHub won’t make any improvements to Projects. I suggest asking GitHub  https://github.com/refined-github/refined-github/issues/2960#issuecomment-619437895

**Comment by ssbarnea** [comment]
If anyone finds another extension or user-script that explains the "more" by default, please let me know, I do really need that. I only have one custom field to expand but because github enforces status to be always the first and does not allow you to delete it, my custom field is always hidden, making the use of the UI much harder.
