### ISSUE TITLE
"Bot" label isn't dropped by `clean-conversation-headers`

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5832]
### Description

<img width="447" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/179342719-69a668d0-5b86-4353-8127-e6e4a2973030.png">

### How to replicate the issue

1. Visit https://github.com/fregante/daily-version-action/issues/22

### Extension version

22.7.1

### Browser(s) used

Safari

**Comment by foolmoron** [comment]
Took a crack at this for hacktoberfest https://github.com/refined-github/refined-github/pull/6093
