### ISSUE TITLE
Sticky file header in PRs shown too low

### ISSUE THREAD

**Issue by rchl** [refined-github/refined-github#5834]
### Description

In Firefox (haven't tried Chrome) going from the notifications page to a PR and then clicking to see `Files changed` reproduces a bug where, after scrolling down, the file headers of every changed file will be positioned too low when it's supposed to be sticking to the top of the page (roughly speaking).

This shows the issue where the file header "detaches" from the diff box and is shown too low:

![Screenshot 2022-07-17 at 22 14 44](https://user-images.githubusercontent.com/153197/179423472-5be31e1c-4c33-401a-8a31-68c4ec621170.png)

### How to replicate the issue

1. Go to notifications page
2. Click notification that goes to (any) PR
3. Click the `Files changed` tab to see the diff of the changes
4. Scroll the page down until you see the bug.

Note that when testing using "Find feature", the issue reproduces for all steps so it appears to not be related to any specific "feature" but rather to some base extension code or just due to extension running (maybe that changes some timings). Disabling the extension fixes the issue.

### Extension version

22.7.11

### Browser(s) used

Firefox 102

**Comment by yakov116** [comment]
You mean https://github.com/refined-github/refined-github/issues/5800?

**Comment by rchl** [comment]
Yes, exactly.
Duplicate of #5800.
