### ISSUE TITLE
`toggle-files-button`: Cannot read properties of undefined (reading 'classList')

### ISSUE THREAD

**Issue by ngoitz** [refined-github/refined-github#5835]
### Description

```
TypeError: Cannot read properties of undefined (reading 'classList')
    at init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:6895:79)
    at async runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3956:20)
    at async setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3962:34)
```

### How to replicate the issue

1. Open any repo: [Code page](https://github.com/refined-github/refined-github)
2. Click `toggle-files-button` to collapse the file list
3. Go to other tabs, e.g. Issues
4. Go back to Code tab
5. `toggle-files-button` is lost and file list is not collapsed
6. Error is thrown in console

If I refresh the Code page, the `toggle-files-button` will return and the file list will be collapsed, but when I do the above steps the error occurs.

### Extension version

22.7.11

### Browser(s) used

Edge Chromium

**Comment by fregante** [comment]
Thanks for the report. This is being tracked in 

-  https://github.com/refined-github/refined-github/issues/5895
