### ISSUE TITLE
`open-all-notifications` does not work if you navigate to notifications from some repo

### ISSUE THREAD

**Issue by gwarser** [refined-github/refined-github#5837]
### Description

"Open unread" / "Open all unread" does not work if you click bell icon after visiting some repo, for example from here.

It works if you navigate from home page or reload the notifications page.

### How to replicate the issue

From here, click bell icon in top right if you see blue dot (unread notifications). Click one of the "Open unread" buttons - nothing happens.

Works correctly after reload.

### Extension version

22.7.11

### Browser(s) used

Firefox Nightly

**Comment by fregante** [comment]
Are the notifications marked as read (at least visually) at least? If that's the case, it's possible that Firefox Nightly has some problems with the background page. If absolutely nothing happens then the event listener is not being registered.

**Comment by gwarser** [comment]
Nothing happens after click.

**Comment by fregante** [comment]
Thanks for the report. This is being tracked in 

-  https://github.com/refined-github/refined-github/issues/5895

**Comment by gwarser** [comment]
This seems to be fixed in latest release.

**Comment by fregante** [comment]
Thanks for reporting back
