### ISSUE TITLE
Disable Turbolinks

### ISSUE THREAD

**Issue by jamiebuilds** [refined-github/refined-github#5840]
### Description

Adding a simple `data-turbo=false` attribute to `<body>` on GitHub will make navigations use normal page loading instead of client-side transitions powered by GitHub's "turbolinks"

For most users, the differences is likely negligible, that is until they are on a poor connection (airport/train/etc) where it will now be noticeably faster to open links in new tabs than let turbolinks do its thing.

Also see: https://jakearchibald.com/2016/fun-hacks-faster-content/

### Screenshot

https://user-images.githubusercontent.com/952783/179869111-c90a81c6-1f3e-4fb5-9fe9-28e16e32f2e9.mov

### Example URLs

https://github.com (every page)

**Comment by fregante** [comment]
Thank you for opening an issue, I would assume that that’s not the case for everyone and that there must be a reason to use ajaxed loads if GitHub invested so much on it over the years. 

While this change would be beneficial to Refined GitHub (ajax causes a myriad of issues) this can’t be part of Refined GitHub.

**Comment by jamiebuilds** [comment]
I wouldn’t assume that they’ve invested a lot in it over the years. In investigating how to disable it I discovered they are using a very old and out of date fork of a project that is now deprecated. I also found turbolinks attributes incorrectly configured. The article I linked above demonstrated techniques they could use to improve it six years ago and they have not implemented those changes. It’s also trivially easy to prove that it’s not faster on a number of connection types using a client script and devtools. Not to mention it appears to have some issues with ad blockers

**Comment by cheap-glitch** [comment]
> this can’t be part of Refined GitHub

Why not? The idea seems to be quite popular given its number of upvotes, and the implementation looks trivial (at least according to the OP).

How about having a special toggle in the options page, like an "Airport mode" or something? It would off by default, but there if people need it.

**Comment by kidonng** [comment]
Context: https://twitter.com/buildsghost/status/1549505382975881216

To make sure we are the same page, the library GitHub currently uses is [Turbo](https://github.com/hotwired/turbo), not Turbolinks.

**Comment by fregante** [comment]
> I wouldn’t assume that they’ve invested a lot in it over the years. 

I would because I’ve seen them work on it over the years. They just replaced the AJAX library instead of just dropping it, which tells me they still see the value in it. 

> The article I linked above demonstrated techniques

Yeah but tell them, it’s irrelevant here.


>  Not to mention it appears to have some issues with ad blockers

Again this is not our problem to fix.

> > this can’t be part of Refined GitHub
> Why not? 

Changing the core way of how a website handles page loading isn’t exactly kosher to me. It’s ripe for errors. Given that they will use multiple frames to load partial content, it’s also likely that the library will be used to display widget updates. Disabling turbo globally might mean that these widgets stop working. 

> The idea seems to be quite popular

Any idea is popular when you point your K followers to “please upvote”. 

> It would off by default

🙂

**Comment by fregante** [comment]
To reiterate, I'd probably like this change but it does not belong to Refined GitHub. If it's such a small change, then you can probably paste that line of code in a user script. I'll be doing that to test it out.

**Comment by fregante** [comment]
I tried it. Turbo feels faster and less janky. What you're experiencing in that tweet isn't normal, the request is failing.

# Native

https://user-images.githubusercontent.com/1402241/179943354-f1065a38-e1fb-4a0b-88d9-05a69c6277b0.mov

# Turbo


https://user-images.githubusercontent.com/1402241/179943378-84595870-06ac-48cf-aca6-93c3b75f592f.mov


My connection is above average and the native version still doesn't feel as fast as turbo’s

```
      Ping   17 ms
  Download   216 Mbps
    Upload   209 Mbps
```

**Comment by fregante** [comment]
You can add this line to your user scripts if Turbo doesn't work well in your situation


```js
document.body.dataset.turbo = 'false';
```

**Comment by joukevandermaas** [comment]
I consistently have the problem described in the original issue, on almost every github page. This would really help me.

**Comment by jamiebuilds** [comment]
Here is the above code as a userscript with install instructions: https://github.com/jamiebuilds/userscript-github-disable-turbolinks

I also tried adding https://github.com/GoogleChromeLabs/quicklink to the userscript to prefetch links in the viewport, but GitHub's CSP doesn't allow for _any_ prefetching which says everything you need to know about how much thought they've put into navigation performance in 2022 (read: none).
