### ISSUE TITLE
`toggle-files-button` notice is misplaced when not on main branch

### ISSUE THREAD

**Issue by cheap-glitch** [refined-github/refined-github#5842]
### Description

![image](https://user-images.githubusercontent.com/46634000/180034222-19320e97-c07f-41f2-8874-ec1f8fe4591a.png)

### How to replicate the issue

Go to https://github.com/refined-github/refined-github/tree/abort-delegates (this happen even with a full page load).

### Extension version

22.7.20

### Browser(s) used

Firefox

**Comment by fregante** [comment]
Love it. 😅 

We should probably also hotfix it (hide it via banner + notice” selector) on 22.7.1 and 22.7.20

**Comment by fregante** [comment]
0 Fixed by https://github.com/refined-github/refined-github/pull/5980
