### ISSUE TITLE
`clean-conversation-sidebar` is breaking the labels dropdown

### ISSUE THREAD

**Issue by CodingCanuck** [refined-github/refined-github#5843]
### Description

When Refined GitHub is enabled, clicking on Labels (or the corresponding gear icon) does nothing:

<img width="327" alt="Screen Shot 2022-07-21 at 1 22 38 PM" src="https://user-images.githubusercontent.com/19922103/180202306-6cd692a8-acf8-4b2c-86c7-89a9599f6692.png">

When I disable Refined GitHub, clicking on Labels shows the Labels dropdown:
<img width="329" alt="Screen Shot 2022-07-21 at 1 24 30 PM" src="https://user-images.githubusercontent.com/19922103/180202395-3c4317a0-a1a9-4d00-975c-76758a649bb5.png">

I've confirmed with my coworkers who also use Refined GitHub that labels were working yesterday.

I see that yesterday the 22.7.20 release was pushed: https://github.com/refined-github/refined-github/releases/tag/22.7.20 could this be a regression in the latest release?

### How to replicate the issue

Open a PR or issue which:
1) you have permission to add labels to
2) has no existing labels

For me https://github.com/3rdparty/eventuals/issues/483 reproduces this (since it has no labels and I have permission to add labels) but https://github.com/3rdparty/eventuals/issues/456 does not (I have permission, but when there are existing labels the labels modal works correctly) 

### Extension version

22.7.20

### Browser(s) used

Chrome

**Comment by cheap-glitch** [comment]
Feature bisector points to `clean-conversation-sidebar` being the culprit.

@CodingCanuck You can disable that specific feature until this is fixed :slightly_smiling_face:

**Comment by CodingCanuck** [comment]
> Feature bisector points to `clean-conversation-sidebar` being the culprit.
> 
> @CodingCanuck You can disable that specific feature until this is fixed 🙂

Confirmed: disabling that feature is a workaround for this issue.

That feature points to https://github.com/refined-github/refined-github/pull/5777/files as a potential culprit, could that be the regression?

I'm not familiar with this code, but I'm suspicious of the `>` being dropped from the line under ``// Hide heading in any case except `canEditSidebar\` ``

**Comment by fregante** [comment]
I disabled it via hotfix again, we had just fixed it
