### ISSUE TITLE
PR-branch-auto-delete should be configurable to not delete i.e. develop branch

### ISSUE THREAD

**Issue by Zeko369** [refined-github/refined-github#5847]
### Description

For free accounts that don't have protected branches [PR-branch-auto-delete](https://github.com/refined-github/refined-github/blob/main/source/features/pr-branch-auto-delete.tsx) can't control which branches get deleted after PR merge so this deletes i.e. develop all the time and it needs to be restored.

Possible solution: user editable whitelist where you can add regex exceptions for branches

### Example URLs

When merging a PR

**Comment by cheap-glitch** [comment]
We don't do feature-specific settings: https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options

GitHub has a native auto-delete branch feature now, you should ask them to make it configurable.

**Comment by fregante** [comment]
Protect the branch via GitHub settings so you won’t risk ever deleting.
