### ISSUE TITLE
Fix our GraphQL usage (use native variables)

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5848]
GraphQL offers its own variables system. I always avoided it because it was verbose (🤦‍♂️) but it would actually offer a good solution to improper memoization:

- https://github.com/refined-github/refined-github/issues/5821#issuecomment-1182822252

## Use variables

Before:

```js
api.v4(`
	repository () {
		name
	}
`)
```

Probably after:

```js
api.v4(`
	repository (owner: $owner, name: $name) {
		name
	}
`, {variables: getRepo()!})
```

## Extract queries to .gql

Separately, I wonder if we could extract these queries to proper GQL files and then `import` them using a webpack loader. 

The best advantage to this would be if there was a typescript transformer that actually parsed these files and provided types. 

Webpack would only need to import them as raw text while TypeScript would receive proper types from these files so that we don't need to deal with `any` 🙂 

Formatting and validation would also be nice side effects of this.

## Related

- 😬  https://github.com/refined-github/refined-github/pull/5839
- 😅  https://github.com/refined-github/refined-github/issues/4654

**Comment by fregante** [comment]
Maybe:

- https://github.com/ardatan/graphql-import-node

**Comment by zoey-on-github** [comment]
is anyone else going to do this or can i work on it?

**Comment by fregante** [comment]
You can
