### ISSUE TITLE
Push less towards creating releases after merged PRs

### ISSUE THREAD

**Issue by lode** [refined-github/refined-github#5851]
### Description

In [`first-published-tag-for-merged-pr`](https://github.com/refined-github/refined-github/blob/main/source/features/first-published-tag-for-merged-pr.tsx) a suggestion is shown to create a release on merged PRs. This suggestion:

- takes quite much attention (with page wide and background color) for something not every repository uses
- makes no sense for repositories which don't use releases

There's some discussion in https://github.com/refined-github/refined-github/pull/5769, to summarize:

> I found the latter [showing existing release, red.] very convenient, but the new suggestion to create a release is really going in the way for a repo where I merge dozens of PRs daily and make tagged releases very infrequently

> I also find the suggest to create a release quite annoying. Mostly on a private repo which doesn't have any releases and won't get any in the future either.

> I don’t get the point. There are a hundred buttons that you don’t use on the page, are they all tempting you? There’s a big “Close and comment” button in every conversation, but you rarely do that. Should it be hidden?

---

I can see how useful the feature is for repositories which make heavy use of releases. My proposal is to see if we can improve the feature for repositories where this makes less sense. E.g. imho most private repos, or bigger repo's with a slower pace of releasing.

Some ideas I can think of:

- Split the feature into showing an existing release and suggesting to create a release; this would make it easier for users to pick which part is useful to them.
- Hide the 'create a release' (or the whole check for existing release) when the repo doesn't use releases at all, something similar already happens with the releases tab.
- Use a less attention grabbing UX for suggestion to create a release, for example a white background and a link instead of a button. (See prototype below.)
- Combine some of these things, e.g. less attention grabbing if the repository doesn't have releases.

### Screenshot

![afbeelding](https://user-images.githubusercontent.com/511245/180747982-17d12405-7b89-40a8-999b-c002346a4594.png)

### Example URLs

Example repositories where the suggestion to create a new release makes less sense (imho):
- 90% of the repositories at the company where I work (except a few that do use releases)
- All the repositories I use for static github pages (don't use releases)
- https://github.com/torvalds/linux (don't create releases so often / based on merged PRs)
- https://github.com/php/php-src (don't create releases so often / based on merged PRs)

**Comment by fregante** [comment]
- https://github.com/refined-github/refined-github/pull/5850 

already addressed one point

**Comment by cheap-glitch** [comment]
This might be dangerously close to a feature setting, but how about adding a button to close the banner and remember that choice on a repo-by-repo basis? It might need a confirm dialog though, something like "Do you want to hide this banner on `<repo name>` forever"?

**Comment by yakov116** [comment]
I think that is too specific.

IMHO it should be a separate feature

**Comment by kidonng** [comment]
Kind of nit-picking, the Linux repo is not a good example, it's just a mirror and don't accept pull request.

**Comment by fregante** [comment]
These two are good enough:

> * Hide the 'create a release' (or the whole check for existing release) when the repo doesn't use releases at all, something similar already happens with the releases tab.
> * Use a less attention grabbing UX for suggestion to create a release, for example a white background and a link instead of a button. (See prototype below.)

**Comment by fregante** [comment]
> > [This is a banner ot sticks out](https://github.com/refined-github/refined-github/pull/5769#issuecomment-1193237530)
> 
> This is the main issue here, banners are not something people should just ignore

This is a good point. PR welcome to change the banner into this style:



> ![afbeelding](https://user-images.githubusercontent.com/511245/180747982-17d12405-7b89-40a8-999b-c002346a4594.png)

**Comment by fregante** [comment]
If you land on this issue, please open a PR as suggested in my last 2 comments. Closing for now
