### ISSUE TITLE
Ability to automatically join back wrap titles > 70 chars split by github

### ISSUE THREAD

**Issue by mfn** [refined-github/refined-github#5852]
### Description

When a git commit message exceeds > 70 characters, the PR title/description gets hard wrapped via `…` like this:

Original commit message:
> `Example of a way too long first line git commit message which gets hardwrapped by github upon creating a PR
`

Github creates:
- title: `Example of a way too long first line git commit message which gets ha…`
- description: `…rdwrapped by github upon creating a PR`

I would like to not have this split via an optional flag.

I do understand this goes against the best practice git conventions, but nevertheless in real life this happens often enough that I wish it was possible to have this be auto-joined.

Thanks

### Screenshot

# Before
![image](https://user-images.githubusercontent.com/87493/180763904-29ecde6f-d16a-46a8-8636-4cef165fc98c.png)

# After
![image](https://user-images.githubusercontent.com/87493/180764031-dbb2242b-1021-499a-b2d4-117251d127be.png)

### Example URLs

https://github.com/rebing/graphql-laravel/pull/933

**Comment by kidonng** [comment]
I remember GitHub used to wrap long commit titles if you commit through the web UI, but I just tried and it doesn't. And apparently [they doesn't wrap issue titles](https://github.com/redis/redis/issues/3909) so I think this behavior is somewhat too opinionated (if people want long titles, let them).

**Comment by fregante** [comment]
@kidonng the issue is unrelated to issues or PRs. It only appears in PRs because _commits_ are wrapped and PRs just use the commit _as is._

It'd make sense to un-wrap the title, but we need a limit, e.g. `description.split('\n')[0].length < 15`

Long PR titles are still not ideal and we already have a feature request that would suggest doing the opposite of this feature.

- https://github.com/refined-github/refined-github/issues/5375

**Comment by lobsterkatie** [comment]
I'd love to have this just as a display option, i.e., if GH has done the split that way, just change the DOM to show the full message (or at least as much as fits in whatever viewport is relevant).

BTW, Refined GH is an absolute lifesaver! Thank you so much for your work on it!

**Comment by fregante** [comment]
I don't think it's worth doing since we don't like long PR titles to begin with, as suggested in the previous comment

**Comment by nZeus** [comment]
> I don't think it's worth doing since we don't like long PR titles to begin with, as suggested in the previous comment

Oh that's such a pity this feature was rejected. 
It's super annoying to remove the dots every time and fix the title manually.

I find this opinionated that you don't like long PR titles. Our PRs often have title length of ~75-90 characters and none in the team ever complained on that...
