### ISSUE TITLE
Add the `Tracked in #x` on the project view

### ISSUE THREAD

**Issue by shiipou** [refined-github/refined-github#5859]
### Description

To allow us to create Epic issue, GitHub allow us to track any issue inside of an other issue.
That show the epic of an issue like that :
![image](https://user-images.githubusercontent.com/38187238/181277796-d3cedd59-0ae3-41e5-8758-805351e5171e.png)

It can be very useful to see it in the project view. GitHub didn't allow us for now to see it in this way. I hope this extension can allow it in near future.

### Screenshot

Add the `Tracked In` label on the card like on this screenshot : 
![image](https://user-images.githubusercontent.com/38187238/181279254-77bb84f4-fce4-444e-914c-09a7276fe8cf.png)

### Example URLs

https://github.com/orgs/lenra-io/projects/4/views/11

**Comment by yakov116** [comment]
Breaks the following rule https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#7-it-doesnt-enhance-projects

**Comment by shiipou** [comment]
Oh ok, sorry

**Comment by yakov116** [comment]
No worries, we hope you enjoy the extension.
