### ISSUE TITLE
Meta: linkify `github-url-detection` function names

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5860]
### Description

This could be useful for:

- Saving from manually linking them (and have stale links)
- Can be conveniently used as "Test URLs"

Potential issues:

- Seems too heavy, considering we already linkify feature names
- Need extra work to get the source link/line number of the corresponding function

Thoughts? Maybe make it a user script instead?

### Example URLs

Here

**Comment by fregante** [comment]
When you open such link, what do you want to see? Like, what information are you looking for that is useful coming from this repo? Can you give me some practical examples of which discussion such link would be useful?

In general what I miss is more of an autocomplete for the feature names and maybe the detections too, we do have an issue open for that (for file names if I remember correctly)

For the test URLs in PRs specifically we should move towards adding them to the bottom of the files. They’re really convenient when copy-pasting them from the file to the PR. Better yet if they are many and are described (see my recent PRs)

**Comment by fregante** [comment]
Here's a similar suggestion:

- inject the test URLs **in code** when a detection is found

## Example URLs

- https://github.com/refined-github/refined-github/blob/7dbc106e7884fd82e771bcfc253fd7c259c19b97/source/features/linkify-user-edit-history-popup.tsx#L24

## Demo

<img width="489" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/182831416-ecf65996-09af-421d-bc58-759bed918e53.png">

Pseudo-code for demo:

```jsx
isConversation.parentElement /* td */ .append(
	<br>
	<span>same leading whitespace as parentElement</span>
	<a class="pl-c for the comment style">http://etc</a>
)

**Comment by fregante** [comment]
See https://github.com/refined-github/github-url-detection/pull/164

What do you think about extending `rgh-linkify-features` to also handle this? I mention _extend_ because this can just piggyback the existing observer and `<code>` filter.

Possible feature:

```js
	if (code.textContent in pageDetect) {
		const url = `https://refined-github.github.io/github-url-detection/detections.html#${code.textContent}`
		wrap(code, <a href={url}>)
	}
```
