### ISSUE TITLE
The widget breaks the loading of new tabs in Ventura 13.0 Beta (22A5311f)

### ISSUE THREAD

**Issue by NewAlexandria** [refined-github/refined-github#5862]
### Description

if you are logged into Github, and you open a new tab, the cookie/session state from the first tab is not correctly accessed in the second/new one. The new tab crashes and says to reload.  This doesn't work.  Clearing cookies does so for all tabs, which leads to the same issue again of login -> ok -> new tab -> tab crash.

### How to replicate the issue

Clearing cookies for all tabs, which leads to the same issue again of login -> ok -> new tab -> tab crash.

### Extension version

22.7.1

### Browser(s) used

Version 16.0 (18614.1.22.1.2)

**Comment by busches** [comment]
Does this happen with RGH disabled? Seems like a straight GH issue.

**Comment by NewAlexandria** [comment]
Pardon that I did not mention.  Yes, the problem goes away when I disable the RGH plug-in. 

That's the only way that I'm able to use GitHub right now since I did the latest Ventura upgrade.

Encourage you to reopen the issue

**Comment by fregante** [comment]
This is not something we can do anything about, you're using beta software and have to deal with its consequences. I suggest reporting it to Apple rather than here. Refined Github isn't doing anything special.

**Comment by tgrapperon** [comment]
It seems that adding a personal token to RGH temporarily solves the problem.

**Comment by NewAlexandria** [comment]
I wonder why RGH was working fine through the first several Ventura beta versions, but not this one

**Comment by fregante** [comment]
Could you file this at http://feedbackassistant.apple.com?

If you're confident that Refined GitHub is causing it, open its background page developer tools from Safari's Develop menu and include any errors in the feedback. 

![image](https://user-images.githubusercontent.com/1402241/182053198-399a76d1-39ff-4c4b-b6d5-d4afb917ce41.jpeg)

**Comment by NewAlexandria** [comment]
The safari release with Venture `22A5321d` has fixed the issue
