### ISSUE TITLE
`action-used-by-link` doesn't work: `selectHas(...) is undefined`

### ISSUE THREAD

**Issue by altrisi** [refined-github/refined-github#5865]
### Description

The `action-used-by-link` feature isn't working. From a quick look it seems like the `selectHas` call isn't finding anything.
This is the stacktrace:
```
init@.../refined-github.js:9634:37
runFeature@.../refined-github.js:3955:26
setupPageLoad@.../refined-github.js:3961:40
add/<@.../refined-github.js:3986:35
async*add@.../refined-github.js:3987:11
async*@.../refined-github.js:9631:20
@.../refined-github.js:11575:5
@.../refined-github.js:11576:3
```

### How to replicate the issue

https://github.com/marketplace/actions/urlchecker-action

### Extension version

22.7.20

### Browser(s) used

Mozilla Firefox 102.0.1

**Comment by kidonng** [comment]
I get a different error:

```
❌ action-used-by-link
refined-github.js:3897 📕 22.7.20 → TypeError: Cannot read properties of undefined (reading 'pathname')
    at init (refined-github.js:9634:67)
    at runFeature (refined-github.js:3955:26)
    at setupPageLoad (refined-github.js:3961:40)
    at refined-github.js:3986:35
```

**Comment by fregante** [comment]
Same error, different browser

**Comment by altrisi** [comment]
Hmm, I get a different stacktrace depending on whether I normally load the page (like from clicking the link above) or if I refresh the page (where I get the one on the first comment), though the error message is still `TypeError: selectHas(...) is undefined`.

If I just load the page I get one quite similar to yours:
```
22.7.20 → TypeError: selectHas(...) is undefined
    init action-used-by-link.tsx:10
    runFeature index.tsx:207
    setupPageLoad index.tsx:223
    add index.tsx:302
```
I don't think it really matters though, the error seems to be the same, just worded differently.

**Comment by fregante** [comment]
Fixed https://github.com/refined-github/refined-github/pull/5867
