### ISSUE TITLE
Commented tab is invisible in review requests tab

### ISSUE THREAD

**Issue by KSH-code** [refined-github/refined-github#5866]
### Description

in **Review Reqeusts** tab, **Commented** and **Yours** is invisible
![image](https://user-images.githubusercontent.com/29705162/181671781-835b497c-bbe5-46f9-908a-7b1738cdacef.png)

### How to replicate the issue

visit https://github.com/pulls/review-requested

### Extension version

22.7.11

### Browser(s) used

Chrome 103.0.5060.114

**Comment by fregante** [comment]
- Tracked in https://github.com/refined-github/refined-github/issues/5895
