### ISSUE TITLE
`show-whitespace` not showing consistently, disappears after a GitHub rehydration 

### ISSUE THREAD

**Issue by winterqt** [refined-github/refined-github#5870]
### Description

The `show-whitespace` feature doesn't consistently show the whitespace on all files.

### How to replicate the issue

1. Go to https://github.com/NixOS/nixpkgs/pull/183772
2. Click on the changed files tab
3. Scroll down to the second modified file, `pkgs/top-level/all-packages.nix`
4. Notice that the whitespace does not show
5. Refresh the page
6. Notice that it does show

Sometimes they show on the file for a split second after I scroll down to it, then disappear.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/78392041/181834746-08db7e2c-a671-465f-bf6f-34a7efeaf640.png">

### Extension version

22.7.1

### Browser(s) used

Safari 15.6

**Comment by fregante** [comment]
I've seen this for years but I don't know why it's happening. I wonder if using the new observer can help here, even just for performance: 

- https://github.com/refined-github/refined-github/pull/5886

**Comment by refractionpcsx2** [comment]
I'm experiencing something similar but not sure it's the same thing, where you load the changes page and the whitespace shows, then they seem to disappear (without touching anything) after a couple of seconds, but only from the first like, 30 lines of the diff.

Here's a picture showing it "kicking in" again

![image](https://user-images.githubusercontent.com/6278726/183329127-5e05cb8d-30d6-4228-ba14-18a19c6ecbe0.png)

Link if required: https://github.com/PCSX2/pcsx2/pull/6801/files

I also removed/readded the extension and cleared my cache to see if either of those help, unfortunately, it didn't :(

**Comment by fregante** [comment]
I've seen whitespace marking disappear so I'm guessing that:

1. RG adds the marks
2. GitHub replaces/updates the code, dropping the marks
3. RG does not handle these new elements again because `rgh-observing-whitespace` is still present on the line

The way `show-whitespace` is implemented could also explain what's happening in the first screenshot

1. RG watches the lines
2. GitHub replaces them
3. RG no longer sees the lines so the whitespace isn't added

I'm not sure how GitHub is replacing each of the line’s content without touching the outer class on each line though, 😰  so annoying.

Some reverse-engineering is necessary by using `onNodeRemoval(span).then(() => {debugger})` after adding a whitespace `span`

**Comment by fregante** [comment]
Found the culprit in GitHub’s code and it's doing exactly what I imagined:

- The element remains, but its children (and our whitespace) is replaced

```js
class DiffRow {
get lineNumbers() {
	let a = this.tableRow.querySelectorAll("td.blob-num")
			, b = Array.from(a).map(a=>parseInt(a.getAttribute("data-line-number") || "") || null);
	return [b[0] || null, b[1] || null]
}
replaceChildren(a /* this is .blob-code-inner */, b) {
	let c = (0,
	h.r)(document, b);
	if (f.$.isFeatureEnabled("STRICT_DEFERRED_DIFF_LINES_CHECKS") && c.textContent?.trim() !== a.textContent?.trim()) {
		this.report && this.report(Error("DiffRow.replaceChildren(): textContent did not match"));
		return
	}
	a.replaceChildren(c)
}
constructor(a, b) {
	this.report = b,
	this.tableRow = a
}
```

The new data is loaded by querying this URL (which doesn't work when opened directly)

```
https://github.com/PCSX2/pcsx2/diffs/0e24d638c990affc52db9fcf5e3628557c0287f7..81f69cf3ee5410d0dbaeaea153b2addef75875b7?base_sha=0e24d638c990affc52db9fcf5e3628557c0287f7&whitespace_ignored=false
```

I'm not sure how we should go about this, our selector observer cannot target text nodes. I don't know using `onNodeRemoval` on every single node we add here is super efficient 🤔 but maybe we have no choice.
