### ISSUE TITLE
Wrap `selector-observer` to add `AbortSignal`, better types, etc

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5874]
I recently mentioned this in a comment but I can't find it anymore. @cheap-glitch also mentioned it in https://github.com/refined-github/refined-github/pull/5726#pullrequestreview-1019332862

Here's part of what I had in mind for a such a wrapper:

- accept `signal`
- use https://github.com/g-plane/typed-query-selector to automatically get types instead of using `constructor`
- better API (`observeElement('a', cb)` instead of `observe('a',{add: cb})`)
- more I can't remember 🥲

**Comment by kidonng** [comment]
> * better API (`observeElement('a', cb)` instead of `observe('a',{add: cb})`)

Actually, [this already exists in `selector-observer`](https://github.com/josh/selector-observer/blob/b811bb5d13cba9940026430f92a6760d5f9e365c/lib/index.d.ts#L19), same as:

```js
observe(selector, {
    initialize(el) {}
})
```

**Comment by fregante** [comment]
That’s not what I suggested, internally it would call `add` but externally we just pass a callback instead of an object. 

Also that reminded of another thing I wanted:

- automatic class generation and exclusion from the selector

Also in the future it’d be good to extend `attachElements` with an `observe: true` option that queries the selector via `selector-observer` instead of `select.all`, but that’s unrelated to this change.

**Comment by kidonng** [comment]
> not a behavior change

Sorry if I'm being misleading, "only run once" means for each element, so if we only use `add` there's no behavior difference with `initialize`.

**Comment by kidonng** [comment]
Found an example how GitHub uses `AbortController` with `selector-observer`:

```js
// https://github.githubassets.com/assets/app/assets/modules/github/issues/convert-to-issue-button.ts
const abortControllers = new WeakMap()

observe('.js-convert-task-to-issue-enabled .comment-body', {
  add(el) {
    const taskItems = getTaskListItems(el)
    decorateItems(el, taskItems)

    const abortController = new AbortController()
    abortControllers.set(el, abortController)
    addModifierKeyEventListener(el, abortController.signal)
  },
  remove(el) {
    const controller = abortControllers.get(el)
    if (controller) {
      controller.abort()
    }
  }
})
```

**Comment by fregante** [comment]
Honestly I wonder if we should just drop the library and look for alternatives. I feel that having to add the selector only to avoid a new call nullifies any speed improvements we get from using the library (if any at all)

Alternatives:

- different library?
- go full MutationObserver in the end (childTree: true 🥲)
- come up with an `animationend`-based solution (we add a 1ms animation the selector + listen to the event globally and catch its `target`)

**Comment by kidonng** [comment]
> Also the lib is dead.

GitHub is still happily using it unmodified 🤷‍♂️ I think the lib is fine, it's just different expectations (*everything* may throw in our case).

> * come up with an `animationend`-based solution (we add a 1ms animation the selector + listen to the event globally and catch its `target`)

That's neat but if there are hundreds of elements, does it impact speed?

**Comment by fregante** [comment]
> That's neat but if there are hundreds of elements, does it impact speed?

This is by far the most efficient, it has 3 parts:

1. Matching CSS selectors "live" (one of the most optimized paths in the browser)
2. `animationend` is triggered even with an empty `@keyframes lol {}`, which means it doesn't trigger layout/render operations
3. Event bubbling and listening is far more efficient than MutationObserver

The best part is that the animation name (`keyframes`) is part of the event itself, so all we need is something like:

```css
@keyframes collapsible-element-button {}
md-ref {animation: 1ms collapsible-element-button}
```
```js
const tracked = new WeakMap()
document.addEventListener('animationstart', {target, animationName} => {
	if (animationName !== 'collapsible-element-button' || tracked.has(target)) {
		return
	}
	tracked.add(target);
	attachElement({anchor: target, after: () => <CollapsibleButton/>)})
});
```

If it really is this simple and efficient, Refined GitHub (and other extensions) could become an order or magnitude easier to manage. Imagine making every feature "declarative" this way, no more wonky listeners.

We can start by adding the CSS to our CSS files for now and maybe later wrap it all in a helper that generates the CSS rules as well as the listener.

**Comment by kidonng** [comment]
I also made one:

```ts
import { css } from 'code-tag'
import type { ParseSelector } from 'typed-query-selector/parser'

export function observe<
    Selector extends string,
    TElement extends Element = ParseSelector<Selector, HTMLElement>
>(selector: Selector | Selector[], callback: (element: TElement) => void) {
    const name = `animation-observer-${Math.random().toString(36).slice(2)}`
    const style = document.createElement('style')
    style.innerHTML = css`
        @keyframes ${name} {
        }

        ${Array.isArray(selector) ? selector.join() : selector} {
            animation-name: ${name};
        }
    `
    document.head.append(style)
    document.addEventListener('animationstart', (e) => {
        if (e.animationName !== name) return
        callback(e.target as TElement)
    })
}
```

**Comment by fregante** [comment]
🔥 

Mind a PR? Would be great to see it working on a feature that already uses `observe`. The problem with the `style` tag is that it introduces some complexity to this code (they start to pile up in the head after multiple navigations, whereas the static CSS wouldn't), which could save for later, but that's up to you

**Comment by kidonng** [comment]
> 1. they start to pile up in the head after multiple navigations

*Return a cleanup function to remove the style element* 😂

I agree static CSS is better, but that needs to write a separator generator, while this works anywhere.

**Comment by fregante** [comment]
> write a separator generator

?

The only issue I see with it is that:

- it requires a CSS files
- the animation name needs to be specified in 2 places

**Comment by fregante** [comment]
> write a separate generator

Are you referring to the class name? It doesn’t need to be generated, as shown in my example.

**Comment by cheap-glitch** [comment]
Love the `animationend` hack!

> The only issue I see with static CSS

I wonder how hard it'd be to write a Webpack (or maybe PostCSS) plugin to generate the required CSS at build time :thinking:

**Comment by kidonng** [comment]
I put my code into a package 👉 https://github.com/kidonng/animation-observer

It's very simple but should do the work™️ you are welcome to try.

**Comment by fregante** [comment]
Uhm it’s a bit early to put code I imagined and wrote onto npm before knowing whether it works and what its limitations are (because I know it won’t work on every website)

**Comment by fregante** [comment]
See https://github.com/refined-github/refined-github/pull/5886#issuecomment-1204363045

Will have to revert to the original scope:

- wrap `selector-observer`

**Comment by kidonng** [comment]
> Uhm it’s a bit early to put code I imagined and wrote onto npm before knowing whether it works and what its limitations are (because I know it won’t work on every website)

I am sorry for this 😔 but I do want to clarify the first prototype I posted here is done separately (and slightly different).

I'm excited because I really love this idea and am gonna use it a lot. You nailed it here:

> If it really is this simple and efficient, Refined GitHub (and other extensions) could become an order or magnitude easier to manage. Imagine making every feature "declarative" this way, no more wonky listeners.

I've since incorporated the awesome improvements in #5886 into my library, credits to you ✨
