### ISSUE TITLE
Add an option to batch delete GitHub Codespaces instances

### ISSUE THREAD

**Issue by aslafy-z** [refined-github/refined-github#5875]
### Description

Codespaces are not automatically deleted. They stack until you reach the limit and have to delete them one by one on this page. Each delete requires 3 clicks and a page-refresh. I suggest adding a way to select codespaces using checkboxes and delete them all with one click to a single button at the top of the page.

### Screenshot

```javascript
const templateNode = document.createElement('div');

// Add checkboxes
templateNode.innerHTML = '<div class="d-flex flex-items-center"><div class="mr-3"><input type="checkbox"></div></div>';
Array.from(document.querySelectorAll("#js-pjax-container > div > div:nth-child(2) > div.codespaces-list-box > div.Box-row > div")).map(parentNode => {
  parentNode.prepend(templateNode.cloneNode(true).firstChild);
});


// Add delete button
templateNode.innerHTML = '<a href="#" target="_blank" data-view-component="true" class="btn-danger btn mr-2">  Delete selected codespace(s)</a>'
document.querySelector('#js-pjax-container > div > div.clearfix.mt-3.pb-3.border-bottom > div.col-md-4.col-sm-12.float-right.position-relative.d-inline-flex.flex-justify-end.mb-1').prepend(templateNode.cloneNode(true).firstChild);
```

![image](https://user-images.githubusercontent.com/8191198/182027119-48a3246a-57f3-4098-b7a7-568ec0e71569.png)

### Example URLs

[Codespaces settings: https://github.com/codespaces](https://github.com/codespaces)

**Comment by fregante** [comment]
You’re right about that, I have quite a few myself

**Comment by fregante** [comment]
This is best done via cli: `gh codespace delete --all`

https://cli.github.com/manual/gh_codespace_delete
