### ISSUE TITLE
Disable (most) notifications

### ISSUE THREAD

**Issue by devinrhode2** [refined-github/refined-github#5877]
### Description

I am trying out https://neat.run for github notifications, but would like to keep using refined github for everything except for desktop notifications.

I don't see an option to toggle here:
![CleanShot 2022-07-31 at 14 56 42](https://user-images.githubusercontent.com/539816/182043000-ae70433f-f7d7-40f9-95e7-be5f3176a08f.png)
 

### Example URLs

(https://www.google.com/)[https://www.google.com/]
(chrome://extensions/?options=hlepfoohegkhhmjieoechaddaejaokhf)[chrome://extensions/?options=hlepfoohegkhhmjieoechaddaejaokhf]

**Comment by busches** [comment]
Refined GitHub is not sending you the notifications, GitHub is.

**Comment by devinrhode2** [comment]
GH does not have desktop notifications enabled:
![CleanShot 2022-07-31 at 15 02 02](https://user-images.githubusercontent.com/539816/182043200-3e19839d-eedc-4c7a-8cc7-c7ef5861353b.png)


Gmail, for example, does:
![CleanShot 2022-07-31 at 15 02 12](https://user-images.githubusercontent.com/539816/182043217-f9d69deb-0c9e-4e73-a9b2-e519957787cb.png)

**Comment by devinrhode2** [comment]
I'll hide the icon and re-open if I'm getting double notifications.

**Comment by busches** [comment]
Then you have another extension providing them.

**Comment by devinrhode2** [comment]
ok, I think I totally confused this extension with https://github.com/sindresorhus/notifier-for-github

Sorry and thank you for correcting me!
