### ISSUE TITLE
Enable `mark-merge-commits-in-list` on comparison pages

### ISSUE THREAD

**Issue by ComiR** [refined-github/refined-github#5878]
### Description

adding `pageDetect.isCompare` to the `include` should suffice.

### Example URLs

https://github.com/refined-github/refined-github/compare/main...lint-2008

**Comment by shogohida** [comment]
@ComiR @fregante 
Hi guys! I created a [pull request](https://github.com/refined-github/refined-github/pull/6104) to solve this issue. I'm new to refined-github so I wasn't really sure how to test....

Please have a look at my pull request when you have time.
