### ISSUE TITLE
`batch-mark-files-as-viewed` partially broken

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5880]
### Description

It has off-by-one errors and other weird behaviors. I don't know if I broke it in my last PR 😔 

### How to replicate the issue

1. Visit https://github.com/refined-github/refined-github/pull/5845/files
2. Start clicking the Viewed checkbox while holding shift

The first selections might make sense, then no more

### Extension version

main

### Browser(s) used

Safari, Chrome

**Comment by yakov116** [comment]
Working perfectly for me on version 22.7.20, Chrome

**Comment by fregante** [comment]
Keep trying shift-cliking on 1, 3, 1, 4, 2, etc In this video I never left shift, you can see it starts missing pieces and just becoming useless:

https://user-images.githubusercontent.com/1402241/182196848-1d60b515-c41e-449f-b9b3-52c4df9c92c0.mov

**Comment by fregante** [comment]
Alt-clicks are completely broken too, at every try
