### ISSUE TITLE
`download-folder-button` doesn't seem to be working currently

### ISSUE THREAD

**Issue by LOuroboros** [refined-github/refined-github#5882]
### Description

The `download-folder-button` feature doesn't seem to be working. Or maybe I'm just blind. I can't see the "Download Directory" option anywhere, surely not where it's shown in the example screenshot linked in Refined Github's about:addons page.

I tested this on a clean Firefox profile with this very GitHub account logged in.

![firefox_20220802_081316979](https://user-images.githubusercontent.com/4485172/182361838-f965cdf7-5019-4bcb-a25a-31c67ae1d395.png)

### How to replicate the issue

1. https://github.com/refined-github/refined-github
2. Open a folder
2. Click the button with an ellipsis.

### Extension version

22.7.11

### Browser(s) used

Mozilla Firefox EME-free v103.0.1

**Comment by fregante** [comment]
It works when you refresh the page. One of the AJAX issues we're having

**Comment by fregante** [comment]
- Tracked in https://github.com/refined-github/refined-github/issues/5895
