### ISSUE TITLE
Minor issues with `tag-changes-link`

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5884]
### Description

<details>
<summary>Unrelated `create-release-shortcut` bug, fixed</summary>

- Open https://github.com/refined-github/refined-github/releases or https://github.com/refined-github/refined-github/tags, and see the following error (ajax related?):

	  TypeError: Cannot read properties of undefined (reading 'classList')
	      at addQuickSubmit (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:7255:99)
	      at runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3955:26)
	      at setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3961:40)
	      at HTMLDocument.<anonymous> (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3988:60)
	      at async https://github.githubassets.com/assets/vendors-node_modules_manuelpuyol_turbo_dist_turbo_es2017-esm_js-8af9baefab9e.js:15:7414
	      at async Visit.render (https://github.githubassets.com/assets/vendors-node_modules_manuelpuyol_turbo_dist_turbo_es2017-esm_js-8af9baefab9e.js:15:10698)

</details>

- On https://github.com/parcel-bundler/parcel/tags?after=v2.2.1, the feature cannot create shortcuts for some releases:
  
  <img width="467" alt="image" src="https://user-images.githubusercontent.com/44045911/182496975-eeb97617-e055-4a5c-aafa-c0f20f8744bd.png">
  
  And on https://github.com/parcel-bundler/parcel/tags:

  <img width="446" alt="image" src="https://user-images.githubusercontent.com/44045911/182496824-4c43172b-8a88-4da1-822f-decf23620873.png">

  The first case seems to be caused by different name style, but the second case is confusing as on the next page, the first tag shown is in the same fashion (v2.2.0) (I didn't read the code so this may be intentional.)

- On https://github.com/parcel-bundler/parcel/tags?after=%40parcel%2Fintegration-tests%401.12.5, tooltip doesn't decode the tag name:
 
  <img width="599" alt="image" src="https://user-images.githubusercontent.com/44045911/182497174-17d98a75-4d03-4b89-90eb-eab2c6a9e31c.png">

### How to replicate the issue

See above

### Extension version

22.7.20

### Browser(s) used

Chrome

**Comment by fregante** [comment]
Most of the issues are in `tag-changes-link`. The first one has been fixed by #6324

@amanmalh would you like to look into this after https://github.com/refined-github/refined-github/pull/6318?

I think the first 2 issues are in the code that loads the page 2 (because the "previous" tags exist only there). The last issue is just an encoding issue
