### ISSUE TITLE
Confirm before closing issues

### ISSUE THREAD

**Issue by DNin01** [refined-github/refined-github#5887]
### Description

Let's say you're writing a comment to discuss an issue, and everything's fine up until you click the Comment button. Turns out you were going fast and hit Close with comment by mistake. Kinda embarrassing. That's why I wanted to suggest a feature that asks before it gets closed if you are writing a comment and you click the Close with comment button. That should help prevent accidental closures!

<sub>I mean, you can just reopen it, but everyone still sees that it was closed for even a moment.</sub>

This hasn't ever happened to me, but I know it's got to have happened to someone, especially with that button being very accessible.

### Screenshot

![gh-closecommentbuttonconfirm](https://user-images.githubusercontent.com/106490990/182744993-03ab23de-e144-45db-b90f-693695655e93.png)

### Example URLs

https://github.com/refined-github/refined-github/issues/5887

**Comment by yakov116** [comment]
Well with RG that button is moved to the other side so that should not happen. Did disable the feature?

**Comment by DNin01** [comment]
> Well with RG that button is moved to the other side so that should not happen. Did disable the feature?

Actually, I haven't installed RG. I didn't know that you were already considering this scenario. Good alternative!

Then, we could either not add this new confirmation feature and leave users with the repositioned close button which is almost just as good, or we could add this so users would have two options: reposition the button and/or get a confirmation in case of accidents. Worth discussing, hm?

**Comment by yakov116** [comment]
First try out the extension and let us know if you have any feedback
