### ISSUE TITLE
Load all comments from an issue

### ISSUE THREAD

**Issue by janpio** [refined-github/refined-github#5888]
### Description

In long issues like https://github.com/prisma/prisma/issues/1122 the comment threads are automatically partially collapsed by GitHub:

<img width="790" alt="image" src="https://user-images.githubusercontent.com/183673/182887610-de9c8a6d-c8f0-49b9-9f91-25dd42ece7dc.png">

That is inconvenient when you want to Ctrl+F the page to search for certain terms, `MySQL` in my example.

"Load more..." unfortunately really only loads "some" more comment into the thread, and you are again left with a button to click:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/183673/182888233-3cbc4b7b-3671-4744-b809-e6cb256b0840.png">

That sometimes takes quite a while to click until all the comments are actually there, and is also easy to overlook as the new link is loaded at the end of the new list of comments.

It would be amazing if Refined GitHub could provide a "Load all" button here instead.

### Screenshot

<img width="790" alt="image" src="https://user-images.githubusercontent.com/183673/182887610-de9c8a6d-c8f0-49b9-9f91-25dd42ece7dc.png">

### Example URLs

https://github.com/prisma/prisma/issues/1122

**Comment by yakov116** [comment]
Exists already press alt and click https://github.com/refined-github/refined-github/blob/main/source/features/expand-all-hidden-comments.tsx

**Comment by janpio** [comment]
lol indeed. Thanks.

**Comment by cheap-glitch** [comment]
Maybe we should make this feature a bit more discoverable? I think it's not the first time someone requested it even though it's already there.

How about showing a little <kbd>Alt</kbd> badge when hovering on the "Load more…" link? It would only take a few lines of CSS. And actually this could apply to other <kbd>Alt</kbd> + click features
