### ISSUE TITLE
Use file name or dir name as page title

### ISSUE THREAD

**Issue by jd-solanki** [refined-github/refined-github#5894]
### Description

When we want to refer something from source code we open multiple files of that project and navigating between them becomes confusing as shown in below screenshot

### Screenshot

![Screenshot 2022-08-05 at 6 33 17 PM](https://user-images.githubusercontent.com/47495003/183086754-acecfc9f-2308-4ceb-a870-8708a7c0c80d.png)

### Example URLs

https://github.com/refined-github/refined-github/blob/main/source/options.tsx

**Comment by fregante** [comment]
> ### Example URLs
> N/A

👆

**Comment by jd-solanki** [comment]
I guess the issue is self-explanatory and I think Providing URL is not applicable here. Still, here's what I wanted to say with URL:

Assume we are on: https://github.com/refined-github/refined-github/blob/main/source/options.tsx

The title will be
![Screenshot 2022-08-05 at 7 04 22 PM](https://user-images.githubusercontent.com/47495003/183088364-07c378af-0bd7-489c-9d6a-12f32ae5891c.png)

_(Asuming we have multiple tabs open of the same project)_

Hence, we can't see the which file is currently open in respective tab just by looking at it. It will be really helpful to just use file name as tab names intead of using repo name as prefix for tab title:

Before: `refined-github | options.tsx`
After: `options.tsx`

Thanks

**Comment by fregante** [comment]
The feature request makes sense. The only issue I see is that we use the title for page detection, especially in files, so it's not safe to modify 🤭 

https://github.com/refined-github/github-url-detection/blob/4d996bb375806ed1cd4f87d2c00e7f6090f04e0a/index.ts#L435

**Comment by fregante** [comment]
I'm gonna have to decline unfortunately. Please send a request to GitHub
