### ISSUE TITLE
`tab-to-indent` conflicts with partial native support

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5903]
### Description

GitHub added native `tab-to-indent` support 🎉 but:

- only on selected text (no selection = <kbd>tab</kbd> moves focus)
- spaces 😩 

![text](https://user-images.githubusercontent.com/1402241/183241770-8062f1cc-2de3-4cde-a469-d15093845816.gif)

This also conflicts with `indent-textarea`:

- sometimes it just breaks
- sometimes it adds both a tab _and_ spaces

![text](https://user-images.githubusercontent.com/1402241/183241931-d49352d7-efa2-4907-9fa6-75725b57450b.gif)

### Possible solution

- block the native tab-to-indent behavior

### Browser

Safari

### Example URLs

This page

**Comment by chcamiloam** [comment]
Hi, I would like to work in this issue @fregante  do you know if we have something to block native GitHub functions to be called? Looks like first the refined-github is applied (with tab) and then the `updateIndentation` GitHub function is called, adding the spaces to the previous indentation.

**Comment by fregante** [comment]
I think we just need `event.stopImmediatePropagation()` inside my `indent-textarea` module. 

To find out whether that works:

1. Edit `node_modules/indent-textarea/index.js`
2. Restart the build (or else changes might not be picked up)
3. Try reproducing the issue

If that works, you can send a PR directly to `indent-text area`

**Comment by fregante** [comment]
You can now open a PR here to update just this dependency, so it will appear in the next release changelog
