### ISSUE TITLE
rgh enables overflow in code blocks, how can I disable this?

### ISSUE THREAD

**Issue by mfn** [refined-github/refined-github#5910]
A picture says more than 1000 words, from example isseue https://github.com/mfn/graphql-laravel/issues/5

# RGH enabled
😢 
![image](https://user-images.githubusercontent.com/87493/184479844-ad018548-f095-4b52-bb5f-861088aabf55.png)

# RGH disabled
😄 
![image](https://user-images.githubusercontent.com/87493/184479857-bd7fe7c9-341d-4c98-90b1-3d6d423e2dcc.png)

No matter what I tried, I can't figure out what part specifically enables this but I really would like to use RGH but not have this overflow enabled; it's a constant hassle not seeing the whole code reading comments, reviewing ad-hoc SQL queries (I already missed some things due to this because usually there's no overflow and my brain simply is not trained to expect one on github).

thanks!

**Comment by fregante** [comment]
It's `scrollable-code-and-blockquote`

See https://github.com/refined-github/refined-github/issues/3906#issuecomment-765031663

**Comment by mfn** [comment]
Thank you so much, [the workaround works like a charm](https://github.com/refined-github/refined-github/issues/3906#issuecomment-765031663)!

**Comment by fregante** [comment]
Since #6333 (version 23.2.11) you can disable the feature in the options page.
It's now called `scrollable-areas`
