### ISSUE TITLE
`linkify-code` doesn’t work in Discussions titles

### ISSUE THREAD

**Issue by Geeyun-JY3** [refined-github/refined-github#5915]
### Description

`linkify-code` doesn’t linkify issue/PR/discussion references in Discussions titles.

### How to replicate the issue

Enter issue/PR/discussion references in Discussions titles.

Example: https://github.com/File-New-Project/EarTrumpet/discussions/877

### Extension version

22.8.8

### Browser(s) used

Chrome

**Comment by kidonng** [comment]
It works, just not enabled there. 😅
