### ISSUE TITLE
Refined GitHub + Octotree freezes page after 10+ navigations via Octotree

### ISSUE THREAD

**Issue by GalvinGao** [refined-github/refined-github#5916]
### Description

Ref: https://github.com/ovity/octotree/issues/1139

Disabling Refined GitHub solves the problem. There's a huge user base for both extensions so I think it's reasonable to raise this up, despite it seems to be an incompatibility problem between two extensions.

This is quite reproducible on my side across all repositories that I've visited, no matter how big they are.
Some of the example ones: [MaaAssistantArknights/maa-website](https://github.com/MaaAssistantArknights/maa-website), [penguin-statistics/backend-next](https://github.com/penguin-statistics/backend-next)

I've attached a profile for reference. Here's the performance tab screenshot for overview purposes.
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/12567059/185253777-0fd13fcf-119b-4fa0-86da-52ddb4880b01.png">

If performance profile is needed, I'll attach it here once asked for ;)

### How to replicate the issue

1. Open a new tab
2. Enter a repository.
	- Here I have chose [penguin-statistics/backend-next](https://github.com/penguin-statistics/backend-next).
	- Expand some folders, and then navigate to some random files.
	- Here I have just chose to click all files under [https://github.com/penguin-statistics/backend-next/tree/main/internal/model](https://github.com/penguin-statistics/backend-next/tree/main/internal/model). Notice that you have to navigate the files via Octotree, not going backward/forward and navigate using the vanilla GitHub way.
4. After navigating 10 files, it is now very obviously, increasingly laggy: After you click a file, the content and the header of the file details page do change pretty instantly. However, the last commit oftenly can't load within about a second or so, and the main thread is completely busy (I can't click on dropdowns and moving my cursor around the page doesn't change the cursor style at all - until the main thread is finished with calculating stuff).
5. After navigating 15 files, it is now about ~10-15 seconds for a single page to load (or should i say, for the main thread to become idle again).

Reloading the page (via Cmd+R, or the Reload button) solves this issue, but it comes back after 10+ navigations.

### Extension version

22.8.8

### Browser(s) used

104.0.5112.79 (Official Build) (arm64)

**Comment by fregante** [comment]
Last time I looked at Octotree they were doing some weird/unnecessary stuff with navigation, like manually loading pages instead of letting GitHub do it. 

Can you verify if this issue happens when navigating via Octotree vs navigating the native GitHub interface?

**Comment by GalvinGao** [comment]
@fregante I see.

Sorry for the confusing language I've written, but this issue occurs *both* when:
- navigating via Octotree, OR
- navigating through the native GitHub interface. Reproduced by clicking those links:
<img width="683" alt="image" src="https://user-images.githubusercontent.com/12567059/185464288-a6f027bf-bb91-423e-8d48-ecd149aff2cc.png">

I also noticed that by random chance the page will perform a full page reload (like what `window.location.reload()` would do). Some delays after navigating around avoids this, and when quickly navigating by links it sometimes reloads the page. I would assume either Octotree or Refined GitHub (though I highly suspect that's Octotree) tried to avoid stale state when navigating through too quickly and just performs the reload to prevent it.

**Comment by fregante** [comment]
I can replicate the issue. 

As you can easily see from the Performance tab, all that code belongs to Octotree. We don't have any files called `content.js`

Sorry about that.

<img width="1114" alt="Screen Shot 13" src="https://user-images.githubusercontent.com/1402241/187086058-98376fc9-f72e-4b5b-b554-93c2fc7ac13f.png">

**Comment by fregante** [comment]
And it's easy to see that it's due to thousands of event handlers piling up here:

<img width="373" alt="Screen Shot 14" src="https://user-images.githubusercontent.com/1402241/187086154-9319a08b-d3b5-4487-823d-d080d32dc863.png">
