### ISSUE TITLE
Main menu disappears on Github Action Job Summaries 

### ISSUE THREAD

**Issue by jerone** [refined-github/refined-github#5921]
### Description

The main menu disappears on Github Action Job Summaries pages.

![image](https://user-images.githubusercontent.com/55841/185916718-1c6a9423-bc93-4532-be27-394f6046c69c.png)

### How to replicate the issue

1. Direct:
    1. Url: https://github.com/jerone/eslint-formatter-checklist/runs/7950750517?check_suite_focus=true
    2. Notice the absence of the main menu. 

3. Indirect:
	1. Go to repo: https://github.com/jerone/eslint-formatter-checklist
	2. Open Actions.
	4. Click on "CI" workflow.
	5. Click on latest run.
	6. Go to job summery "_JEST test 14_" or "_test report (node v14)_".
	7. Notice the main menu disappear.

### Extension version

22.8.8

### Browser(s) used

Firefox 103.0.2 (64-bit)

**Comment by fregante** [comment]
I think this is an issue somehow caused by our CSS because it appears at every bisect step. Something is interacting with GitHub’s overflow menu and making it hide every tab.

**Comment by fregante** [comment]
It seems to be the CSS of `clean-repo-tabs` and `more-dropdown-links`

**Comment by fregante** [comment]
This has been hotfixed
