### ISSUE TITLE
Small title field even if `suggest-commit-title-limit` is disabled 

### ISSUE THREAD

**Issue by rolfbjarne** [refined-github/refined-github#5922]
### Description

The textbox for the commit subject when merging a PR is smaller than the width of the textbox for the commit message:

<img width="931" alt="Screen Shot 2022-08-23 at 10 01 18" src="https://user-images.githubusercontent.com/249268/186112629-ed172156-2d7f-4ed8-88f6-5b65dafc38a2.png">

I believe this to be the `suggest-commit-title-limit` feature (*which I've disabled*, since I routinely create commits with longer titles). You can even see the same behavior in the screenshot for the feature: 

<img src="https://user-images.githubusercontent.com/37769974/60379478-106b3280-9a51-11e9-88b9-0e3607f214cd.gif" />

The smaller textbox size makes sense with the feature enabled, but if it's disabled it doesn't make sense anymore (and it just looks weird too).

### How to replicate the issue

I'm seeing this on all PRs I'm merging (on several repositories), so it's not specific to a particular PR.

This is the PR from the screenshot: https://github.com/xamarin/xamarin-macios/pull/15712

I'm not sure how I can create a public URL to repro, since you'd need write permissions to the repo in question in order to get be able to (try to) merge a PR.

### Extension version

22.8.8

### Browser(s) used

Safari, Chrome

**Comment by fregante** [comment]
It's a feature. As you can see, once you exceed it it turns red. Long commit titles get clipped in the UI, so it's best to keep it to 72 characters or less

**Comment by fregante** [comment]
I agree that the CSS should be disabled when the feature is disabled though

**Comment by fregante** [comment]
Mistakenly pushed straight to `main` 😅 a557cf89


## Feature enabled

<img width="848" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/1402241/190378687-af46827e-29f5-4f45-b9b2-87727668a697.png">


## Feature disabled

<img width="844" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/1402241/190378707-5a631cd8-5b82-4c4a-bf78-a9f489c970e4.png">
