### ISSUE TITLE
A problem about wait-for-checks

### ISSUE THREAD

**Issue by rootmelo92118** [refined-github/refined-github#5924]
I got a problem with wait-for-checks.
The reason is it should display an option "wait for successful checks" but it doesn't.
Is anyone know how can I solve it?
Normal page:
![photo_2022-08-23_17-31-48](https://user-images.githubusercontent.com/32770959/186125017-f7caaa8c-8396-4651-8b6e-fff50af216bf.jpg)
My page:
<img width="913" alt="截圖 2022-08-23 下午5 29 45" src="https://user-images.githubusercontent.com/32770959/186125071-937e4b93-cde2-4004-aeb4-079a7e7f64db.png">
My config of extension:
<img width="754" alt="截圖 2022-08-23 下午5 29 00" src="https://user-images.githubusercontent.com/32770959/186125209-1f0a4c50-85eb-47cb-aadf-e33a79f31e2a.png">

**Comment by fregante** [comment]
Are there any checks running? It only appears if there are.

Take a screenshot including the last commit on the PR page so we can make sure of that

**Comment by rootmelo92118** [comment]
> Are there any checks running? It only appears if there are.
> 
> Take a screenshot including the last commit on the PR page so we can make sure of that

Oh I see. My repository doesn't have workflow to check. Thanks
