### ISSUE TITLE
prevent accidental yolo merges

### ISSUE THREAD

**Issue by graingert** [refined-github/refined-github#5926]
### Description

There's now a github award called 'yolo' 'achieved' by merging an un-reviewed PR.

I often end up accidentally closing an issue and re-opening or other accidental actions that I can undo, however 'earning' this award will cause permanent damage to my account.

So I'd like for all of these possible merge buttons to be disabled, or put behind a "danger zone" box where I would need to type "earn yolo on ${username}"

### Example URLs

`https://github.com/[\w-]+/[\w-]+b/pull/\d+`

**Comment by fregante** [comment]
> however 'earning' this award will cause permanent damage to my account.

I don’t think this is an issue that most people are concerned with, so I don’t think it belongs to Refined GitHub.

As for a generic "confirm to close", it has already been asked and rejected:

- https://github.com/refined-github/refined-github/issues/5887
- https://github.com/refined-github/refined-github/issues/3884

**Comment by fregante** [comment]
Good news! Achievements can now be hidden from your profile:

https://github.blog/changelog/2022-10-07-visibility-settings-for-individual-achievements/
