### ISSUE TITLE
GitHub is freezing on some PRs

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5928]
### Description

I'm not sure if it's due to Refined Github or a GitHub issue, but I've seeing this happen in 22.8.1 Safari and 22.8.8 Chrome.

I'll try disabling RG to see if it still happens.

### How to replicate the issue

1.  https://github.com/refined-github/refined-github/pull/5925

After opening a PR, the page freezes while the checks are loading (not sure if it's related)

<img width="913" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/186146933-b29c7e4a-d1ea-4484-98c9-6e9783708caf.png">

### Extension version

22.8.1, 22.8.8

### Browser(s) used

Safari, Chrome

## Potentially related

- #5916

**Comment by fregante** [comment]
@jerone have you experienced this?

**Comment by jerone** [comment]
Yes, multiple times before. Keep forgetting to post the links with screenshot.

I'm experiencing it in Firefox. 
Usually on big PR's (not always). 
Firefox will show a banner telling that "Refined Github is slowing down the page".

**Comment by jerone** [comment]
Oh and when it happened it was on the files tab, never the conversation tab, which seems to be the problem you reported.

Haven't find any consistency if it happens after an redirect or opening a new browser tab.

**Comment by fregante** [comment]
I haven't seen it since, even after merging a dozen PRs

**Comment by fregante** [comment]
> I'm experiencing it in Firefox. Usually on big PR's (not always). Firefox will show a banner telling that "Refined Github is slowing down the page".

That's probably https://github.com/refined-github/refined-github/issues/5627
