### ISSUE TITLE
Add a `Hide all comments` option to `conversation-activity-filter`

### ISSUE THREAD

**Issue by Geeyun-JY3** [refined-github/refined-github#5929]
### Description

Add a `Hide all comments` option to `conversation-activity-filter`.

Sometimes I just need to skim the issue/PR references to find the related issue/PR I want.

### Screenshot

This option is provided by GitLab (equivalent to GitLab’s `Show history only` option in the `Sort or filter` menu)
![image](https://user-images.githubusercontent.com/49396421/186398404-0b65f478-b3c1-44f5-9175-52ec44b2dc18.png)

### Example URLs

https://github.com/refined-github/refined-github/issues/3764
https://github.com/refined-github/refined-github/pull/4029

**Comment by fregante** [comment]
> Sometimes I just need to skim the issue/PR references to find the related issue/PR I want.

While it sounds useful, it's rather niche. I don't want to add multiple choices to the feature
