### ISSUE TITLE
Discourage commenting on old, closed, or super-active threads

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5934]
### Description

Every so often someone leaves an incomplete bug report, a feature request, or a “me too” comment on closed issues and PRs. I do this too occasionally.

We should add a banner above the comment field to encourage people to open a new issue or do nothing instead. 

Messaging examples:

- This issue/PR is 3 years old. Consider opening a new issue instead
- This issue/PR is super active. Only leave a comment if you read the whole conversation
- Leaving a comment will notify about 30 people. Plz stop

### Example URLs

- https://github.com/refined-github/refined-github/issues/3076
- https://github.com/refined-github/refined-github/issues/3229

**Comment by cheap-glitch** [comment]
+100 for the first one, not sure about the other two

**Comment by fregante** [comment]
> * This issue/PR is super active. Only leave a comment if you read the whole conversation

StackOverflow [does it](https://stackoverflow.com/q/23667086/288906)

<img width="557" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/187418889-d9569845-24f4-4faf-ad04-8034c6f3b297.png">


> * Leaving a comment will notify about 30 people. Plz stop

Receiving random notifications from threads you commented on 3 years ago is annoying, it's why I've been locking more and more threads lately, especially the most commented ones. I'd rather not do that honestly, but people keep commenting there.

**Comment by fregante** [comment]
Related:

- https://github.com/refined-github/refined-github/issues/5815#issuecomment-1181290574

**Comment by fregante** [comment]
Heheh yeah it's more as a reminder. This also occasionally happens to me when I land on an issue from Google and comment only to realize it's 4 years old. 

Adding a banner as a reminder of etiquette is welcome to me too and I hope some GitHub developer notices it and makes it a default.

**Comment by fregante** [comment]
So, next step

- add banner to super-active threads like [this one](https://togithub.com/refined-github/refined-github/issues/3686)

What should the logic be?

<table>
<tr>
	<th>Participants
	<th><img width="316" alt="Screenshot 8" src="https://user-images.githubusercontent.com/1402241/230735414-95c99607-5ef4-4792-961a-a0f98756c3cc.png">
<tr>
	<td>Comments
	<td><img width="103" alt="Screenshot 9" src="https://user-images.githubusercontent.com/1402241/230735412-8cc93b1c-3d84-46d4-8e07-a190240da8e1.png">
</table>

My only concern is that this appears on lengthy discussions by the same team, so maybe:

- 10 participants
- don't show to collaboratora (best-effort to detect this)
- don't show on private repos (this might not be possible due to the "Global navigation update")


Also, what should the text be?

<img width="627" alt="Screenshot 10" src="https://user-images.githubusercontent.com/1402241/230735849-aa2e5746-b2ac-45b6-b39b-afb78f46a7d1.png">


Some more silly options from CGPT

> - "This ticket is quite active! Please review all comments before commenting."
> - "There's a lot of activity on this ticket! Take a moment to read all comments before adding your input."
> - "Due to high activity, we request that you read all comments before commenting on this ticket."
> - "With a lot of ongoing discussion, please review all comments before adding your comment on this ticket."
> - "This ticket is generating a lot of discussion. Kindly read all comments before contributing your thoughts."
