### ISSUE TITLE
Obfuscate/warn about sensitive content when posting a message

### ISSUE THREAD

**Issue by lppedd** [refined-github/refined-github#5936]
### Description

Happens pretty often I need to share logs extracted from production machines in GitHub issues.  
I know what I have to filter out (replace with dummy names, a bunch of `*`, and so on), but sometimes something slips in.

It would be cool if Refined GitHub could warn me about it, or automatically obfuscate with user-defined replacements on copy-paste in the message box.

Can this be considered in-scope for this plugin?

### Example URLs

See for example https://github.com/eclipse-tycho/tycho/discussions/1304

**Comment by fregante** [comment]
> sensitive content

How can it know what is sensitive?

**Comment by lppedd** [comment]
> 

@fregante the product(s) you're working on are the same for quite some time usually, so user-defined string matches could be enough imho.

**Comment by fregante** [comment]
As much as I'd like it, it would not be possible in Refined GitHub: https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options
