### ISSUE TITLE
`show-open-prs-of-forks`: Cannot read properties of undefined (reading 'after')

### ISSUE THREAD

**Issue by Trenly** [refined-github/refined-github#5937]
### Description

```
TypeError: Cannot read properties of undefined (reading 'after')
    at init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:9587:85)
    at async runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3851:20)
    at async setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3857:34)
```

![image](https://user-images.githubusercontent.com/12611259/187985388-3a56d5de-a247-423f-8789-788e31ebcc32.png)

### How to replicate the issue

I navigate to https://github.com/Trenly/winget-pkgs/branches/all and notice that only some branches show the PR status. 

### Extension version

22.8.23

### Browser(s) used

Google Chrome (Version 103.0.5060.134 64-bit)

**Comment by fregante** [comment]
The screenshot doesn't match the feature you're mentioning in the title. Can you make sure the bug report is consistent?

`show-open-prs-of-forks` works correctly for me on https://github.com/fregante/p-timeout/tree/patch-1

<img width="453" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/188281647-0ec7d5a1-0abf-4243-80bb-965754551dc3.png">
