### ISSUE TITLE
`sticky-sidebar` disappears when expanding fields of new Projects

### ISSUE THREAD

**Issue by janpio** [refined-github/refined-github#5939]
### Description

I am using Refined GitHub in a repository where issues get a lot of labels, and we use multiple GitHub projects (both old and new) - so our sidebars are pretty looooong. As the issues themselves are also long with many comments, `sticky-sidebar` is absolutely necessary to stay sane and be able to access labels and projects all the time. Thank you for that, as usual!

Unfortunately recently I noticed that when I expand one of the "new projects'" widgets (they can have multiple "fields" that all can have an input field or dropdown etc) the stickyness breaks and the whole sidebar disappears to the top, to its usual static location 😿 I have to scroll back up to edit the fields, and only a reload makes the sidebar sticky again - until the next edit.

After some experimentation I could figure out that a pretty specific situation needs to happen - but of course our repository consistently does that. So I created a reproduction issue: https://github.com/janpio/refined-github-sticky-sidebar-projects-bug/issues/1 

If I am understanding the problem correctly, the sidebar (via labels and projects and their fields) needs to be taller than the "viewport" where the sidebar could be displayed. I left instructions below that allow me to persistently reproduce this in an incognito window with only Refined GitHub enabled.

Here are also some screenshots:

Before, working as expected: 
<img width="971" alt="image" src="https://user-images.githubusercontent.com/183673/188207734-1cb68d8a-114a-4f3f-9bb0-0316ba5a7cd7.png">

After clicking `+ 7 more` on the sidebar - no more sticky sidebar:
<img width="950" alt="image" src="https://user-images.githubusercontent.com/183673/188207812-b2638864-224c-4bc1-81f8-a4a7977acdcc.png">

Ahhh, here it is, with the fields expanded:
<img width="964" alt="image" src="https://user-images.githubusercontent.com/183673/188207868-943aeac9-fbeb-4067-b0bc-08b10ad8f6e2.png">

### How to replicate the issue

Go to https://github.com/janpio/refined-github-sticky-sidebar-projects-bug/issues/1, scroll to the end of the page, make sure your browser window is just tall enough to display the current right hand sidebar (with the projects), click on `+ 7 more` in the Project "widget" on the right side - and then observe the "sticky" sidebar disappear to the top.

### Extension version

22.8.23

### Browser(s) used

Chrome Version 104.0.5112.81 (Official Build) (64-bit)

**Comment by fregante** [comment]
It's on purpose: the sidebar does not fit the viewport so we can keep it sticky. 

I kinda wonder if we could add a max-height and a scrollbar inside the sidebar, but I kinda dislike such nested scroll areas, especially since this is "sticky" rather than "fixed", making it even more weird

**Comment by janpio** [comment]
Oh, I understand - that makes sense. I can indeed prevent it by zooming out a bit before clicking the "7 more" link. Unfortunately I do not really know when I will hit the limit of course, so I would need to _always_ zoom out :trollface: 

It is hard to come up with a good alternative way to handle this indeed. But as I would assume this is more of an edge case (most sticky sidebars will not run into this situation), the scrollable container actually does not sound too bad for me. (Not 100% sure how the scroll behavior of the main page would change via the scrollable area in the sidebar - that could feel weird if that would disable the global page scroll for example)

A "workaround" could be some custom CSS to remove other unneeded stuff from the sidebar like "Development" to create a branch, or make the 4 links at the end of the sidebar use less vertical space (2 columns?). But that also all feels meh.

**Comment by janpio** [comment]
> [`clean-conversation-sidebar`](https://github.com/refined-github/refined-github/blob/main/source/features/clean-conversation-sidebar.tsx) was written with this in mind too, but GH keeps adding sections 😅

Also https://github.com/refined-github/refined-github/issues/5843 of course :( That sidebar is really trouble.

> It's a regular scroll area on a page. You can apply this CSS to have a demo:

I played with this a bit, the scroll behavior is definitely _weird_ - the last active scrollabale area gets "focus" of my scroll wheel. I would need to get used to move to the right or left of the scrollable sidebar to be able to scroll the actual page.

An alternative solution, but that is probably not as simple to implement, is to use the stickyness: 
By default the sidebar would expand beyond the viewport instead of snappting to the top, which of course would make its bottom inaccessible (but those are usually not that important anyway :trollface:). Only when you scroll to the end of the issue, after you are done with the actual comment thread, it scrolsl to the bottom on the sidebar. That would enable you to get to the links that might be outside the viewport. Could be the better tradeoff here.

**Comment by fregante** [comment]
> would make its bottom inaccessible

Indeed. 😅 That kills the suggestion.

The best sidebar implementation was by Facebook circa 2012, where the sidebar would be stuck "at the bottom" when scrolling down, and "at the top" when scrolling up: http://jsfiddle.net/gmolop/y3tdL9wd/

Also asked on https://stackoverflow.com/q/18358816/288906

But unfortunately that requires JavaScript

**Comment by fregante** [comment]
As an immediate solution to this issue, we can disable the ResizeObserver while the user is interacting with the sidebar, like `:has(:focus, :hover)`, so it won't disappear under the cursor.

**Comment by janpio** [comment]
> Indeed. 😅 That kills the suggestion.

To clarify: I meant that the bottom of the sidebar would be inaccessible _until you scroll to the bottom of the page_. That combined with getting into this situation being an edge case, sounds ok to me. I think that would be a variant (kind of the opposite sidebar behavior) of the jsfiddle you linked to. (I obviously have trouble to explain what exactly I mean and how it would behave.)

**Comment by janpio** [comment]
Here is a hopefully clarifying illustration on the suggestion:
<img width="1459" alt="image" src="https://user-images.githubusercontent.com/183673/188217079-a6d6ae3f-69e5-4b17-9ff4-f8eff891c931.png">

**Comment by fregante** [comment]
> until you scroll to the bottom of the page

I got, that's achieved by adding `position: sticky` unconditionally rather than depending on the sidebar height. But imagine you're on a long page and you have to scroll 3 seconds until you can click it. It's not a good experience, that's why we have the condition. 

The only issue that this causes is when the sidebar grows, as specified by your issue.

**Comment by janpio** [comment]
(I was thinking of my case, where "collapsing" the project fields would also lead to the bottom of the sidebar being visible again - but of course depending on the project and the viewport a sidebar could also _start_ in the state of being to high already. There my suggestion would indeed be a bit weird with loooong comment threads.)

**Comment by fregante** [comment]
Do you mean _only_ in your case? Then that's covered by:

> we can disable the ResizeObserver while the user is interacting with the sidebar

**Comment by janpio** [comment]
I honestly did not understand your message above before and pushed understanding it to later. 🙈 I think you are saying we can make it not trigger the "sidebar jumps to the top" behavior when it is triggered via me clicking "+7 more" in the new Project widget in the sidebar? Then that sounds great _for me_ (any my colleagues).

**Comment by fregante** [comment]
Yeah, `ResizeObserver` looks at the size of the element on the page and triggers the calculation to determine whether the sidebar should be stuck.

If we disable it, it won't suddenly become unstuck like in your demo screenshots.

**Comment by fregante** [comment]
Update: I tried adding a scrollbar as a fallback and it failed. The scrollbar effectively triggers "overflow: hidden" so the popups in the sidebar (in red) are cut off:

<img width="388" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/189523587-8cf885d3-9f3c-494d-b609-8fb841323612.png">
