### ISSUE TITLE
What happened to `sort-conversations-by-update-time` feature?

### ISSUE THREAD

**Issue by sanity** [refined-github/refined-github#5941]
Hi, I see a reference to this feature in a previous pull request but the feature doesn't seem to exist in the current version of the extension - was it removed?

https://github.com/refined-github/refined-github/pull/935/files

**Comment by fregante** [comment]
The feature exists under the same name I think and it works. But you need to click on a link on GitHub.com to work. If you open /user/repo/issues, we don't change the sorting on that page because it would require a reload.

**Comment by sanity** [comment]
Oh, hmm - are issues and conversations the same thing?

**Comment by fregante** [comment]
If you see "Conversation" we mean "issue or PR" since they're mostly the same thing for GitHub.
