### ISSUE TITLE
View earlier version of file

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5942]
### Description

You're looking at a file, how many clicks do you need to go to the previous version?

"The previous version" is at the core of how git works, yet this operation requires 2 full page loads.

We need to add a button to the previous version

### Screenshot

Example:

<img width="757" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/188318964-25e934f3-b6cf-42fd-b0d9-bffc6381307d.png">

### Example URLs

https://github.com/refined-github/refined-github/blob/main/.gitignore

**Comment by fregante** [comment]
I'm kinda tempted to add a button to githistory.xyz but it's not that fast and often you really need to stay on GitHub.xom

**Comment by fregante** [comment]
Would also be nice, loaded asynchronously:

<img width="402" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/188324506-50fcd397-3ff5-4eb2-b5c0-87ed2fbfea11.png">

**Comment by kidonng** [comment]
I remember it is mentioned in somewhere in this repo that you can do this

`abcd123` -> `abcd123~` (previous) / `abcd123~5~ (previous 5)

I do this manually all the time

**Comment by 134130** [comment]
@fregante @kidonng 
I'm currently working this feature. Let me know the feature's name.
Just working with temporary name: `file-history`

<img width="266" alt="image" src="https://user-images.githubusercontent.com/50487467/233801586-5273bd9f-1c0d-4640-97c6-5644de2fc29b.png">
Only view is available now.

**Comment by 134130** [comment]
The relative URL is based on commit; When I get HEAD~5, It means the File in HEAD commit's 5th previous.
I think we need to call API to get the File's history.
