### ISSUE TITLE
Milestones icon looks shifted to the side

### ISSUE THREAD

**Issue by AKorezin** [refined-github/refined-github#5943]
### Description

After #5891 if there are no milestones, then *Milestones* text will be shifted outside of the button.
I noticed that icon is not centered.
![1](https://user-images.githubusercontent.com/5399964/188342173-2e20a86e-43ca-4a32-b2ea-f87ffed67c38.png)

### How to replicate the issue

1. Go to https://github.com/refined-github/refined-github/issues
2. See the problem

### Extension version

22.8.23

### Browser(s) used

Chromium 105.0.5195.102

**Comment by fregante** [comment]
Indeed. The padding-left needs to be reduced. Thanks for the report

**Comment by Ayusj** [comment]
claim
