### ISSUE TITLE
`open-all-notifications` does not work after clicking the back button

### ISSUE THREAD

**Issue by janpio** [refined-github/refined-github#5947]
### Description

The "Open all unread" button from `open-notifications-button` looses functionality (but is still visible) when going to the previous search result page with the "Back" button of the browser, making it hard to open _all_ issues of a repo in chronological order in new tabs (which is unfortunately my usecase).

Reloading the page after going back to it let's you work around this - then the button works again.

### How to replicate the issue

1. Go to https://github.com/notifications, have _many_ (25+) notifications for a repository
2. Click to see all notifications from repository, e.g. https://github.com/notifications?query=repo%3Aprisma%2Fprisma
3. (Maybe, not sure if that plays a role: Also switch to the "Unread" view: https://github.com/notifications?query=repo%3Aprisma%2Fprisma+is%3Aunread)
4. Click "Next" at the bottom right until you get to the last new notifications
5. Use the amazing "Open all unread" button from Refined GitHub, from feature `open-notifications-button` to open all of them (after confirming the prompt if I really want to do that)
6. Use the browser "Back" button to get to the previous search result page.
7. Observe how clicking the button does nothing (no output in console either)

### Extension version

22.8.23

### Browser(s) used

Chrome, Version 104.0.5112.81 (Official Build) (64-bit)

**Comment by fregante** [comment]
Thanks for the report. It's likely this:

- https://github.com/refined-github/refined-github/issues/5871


We'll keep this issue open to know what's broken.

**Comment by janpio** [comment]
That sounds correct and relevant. The issue creation date also roughly matches to when I became aware of this not working any more as before - because this is definitely new and used to be fine in the past 👍 

I also subscribed to the other issue for updates, but thanks for keeping this one open as a concrete example.
