### ISSUE TITLE
Add banner for "May be fixed by" at the bottom of an Issue 

### ISSUE THREAD

**Issue by styfle** [refined-github/refined-github#5948]
### Description

I really like the existing large `first-published-tag-for-merged-pr` banner at the bottom of a PR (see https://github.com/refined-github/refined-github/pull/5643).

I would like a similar banner to make it obvious when an Issue has a linked PR. The current text is easy to miss because its at the top of the Issue, but my eye wants to go to the bottom to find recent activity in the timeline.

### Screenshot

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/229881/188893235-f4f36742-f820-4df7-987d-2d3f21b770ca.png">

### Example URLs

https://github.com/node-fetch/node-fetch/issues/1217

https://github.com/microsoft/TypeScript/issues/21732

**Comment by fregante** [comment]
Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it. If it was accepted before, I may still accept a PR in the next 6 months.

**Comment by styfle** [comment]
Based on the 3 emoji likes, this issue is in the top 12 most liked issues. 

Might be worth revisiting, especially if you are accepting PRs from the community.

**Comment by fregante** [comment]
It's a minor feature that just copied a link that is already always in the viewport. On the scale of utility this is super low. Hence the closure
