### ISSUE TITLE
Cannot open the milestone dropdown on issues

### ISSUE THREAD

**Issue by Nokel81** [refined-github/refined-github#5953]
### Description

https://user-images.githubusercontent.com/8225332/189156411-bc4be438-0881-4b77-8f9e-8b1ca803c36a.mov

### How to replicate the issue

Turn on Refined Github

### Extension version

22.8.23

### Browser(s) used

Firefox (macOS)

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/5952

**Comment by fregante** [comment]
Can you try disabling `clean-conversation-sidebar`?

**Comment by Nokel81** [comment]
Yes and that does resolve the issue.
