### ISSUE TITLE
Allow replacing quotes in `one-key-formatting`

### ISSUE THREAD

**Issue by FloEdelmann** [refined-github/refined-github#5960]
### What I don't like

When I want to change `"` to `'` or vice-versa in a comment, I need to first delete the character and then type the other one. When selecting it and typing the other one, `one-key-formatting` wraps it (e.g. `"` → `'"'`).

My suggestion: When a single quote character (`'` or `"`) is selected and a quote character is typed (`'` or `"`), skip `one-key-formatting`. This behavior matches VS Code (which also allows one-key formatting in Markdown).

**Comment by fregante** [comment]
> This behavior matches VS Code

Just tried. _Feels good, man._ Change more than welcome. Let's match VSC as much as possible here.

![a](https://user-images.githubusercontent.com/1402241/189526461-2afd8175-befd-4d1b-898a-c53b54bd2167.png)
