### ISSUE TITLE
`toggle-files-button` note position bug

### ISSUE THREAD

**Issue by ZaLiTHkA** [refined-github/refined-github#5978]
### Description

when viewing a project fork that is behind its upstream donor project, the note regarding Refined GitHub automatically collapsing the file list appears in the wrong place:

![image](https://user-images.githubusercontent.com/2149312/190093027-1d44f4b9-958d-4a13-9bad-83ca2608d33f.png)

### How to replicate the issue

1. fork a repo and collapse the file list
2. push commit to upstream repo
3. reload fork repo page

### Extension version

22.9.9

### Browser(s) used

105.0.5195.102

**Comment by fregante** [comment]
Thanks for the report! I think someone mentioned this in the past but there was no open ticket.

**Comment by fregante** [comment]
WIP
