### ISSUE TITLE
Sort commits from newest instead of from oldest

### ISSUE THREAD

**Issue by dkaszews** [refined-github/refined-github#5981]
### Description

GitHub orders commits in pull requests (and probably other places) starting from oldest at the top to newest on the bottom, which is exactly the opposite of what Git console and every UI does. This is also annoying as I usually want to check the newest changes, which requires me to slow down.

### Screenshot

Sorting in GitHub: from oldest to newest:
![image](https://user-images.githubusercontent.com/26599495/190234482-8e446fcd-ded3-4739-a783-a47d8d870913.png)

Sorting in Git: from newest to oldest:
![image](https://user-images.githubusercontent.com/26599495/190235134-8dd6aed4-cd41-451b-b3a5-d7e3115d9ce0.png)

### Example URLs

https://github.com/PowerShell/PowerShell/pull/18037/commits

**Comment by fregante** [comment]
I think this could make sense as the commits are also shown in reverse chronological order outside PRs. 

My only concern is pagination: if it exists, we can never do this. 

At what point does GitHub start paginating PR commit pages?

**Comment by dkaszews** [comment]
I found a [PR with 51 commits](https://github.com/PowerShell/PowerShell/pull/11452/commits), looks like no paginagion to me. Since gross majority of PRs have way fewer commits, it should not be an issue. If someone has a PR with so many commits it breaks on pagination, they can submit a bug and we can take a look at it. If it's really not easy to fix (may be possible by just swapping order of pages?), I would then propose to just disable reverse sorting when paging with a warning info.

**Comment by dkaszews** [comment]
I stumbled upon a PR broken due to rebase, according to GitHub it had 961 commits and displayed a message:

> This pull request is big! We’re only showing the most recent 250 commits.

So there is no pagination, just truncation, at a level way beyond what anyone can find reasonable for a PR, and it displays the _newest_ commits, so sorting them from newest to oldest is kinda a correct thing to do anyways.

**Comment by fregante** [comment]
Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it.

**Comment by pgeadas** [comment]
Can we re-open this? I have seen so many people asking for this and this should be the default anyway...
is it that hard to reverse the list before displaying it?
