### ISSUE TITLE
Acessibility: Disable "/" (slash) shortcut hijack.

### ISSUE THREAD

**Issue by gcbw** [refined-github/refined-github#5982]
### Description

Pressing "/" (forward slash) key on any github page will capture the keyboard input into the search input box on the site.

That same keystroke is used to start (and impossible to change) the typeahead search on firefox, which is an essential usability feature for mobility impaired people.

Suggested feature is to add checkbox that disable the search shortcut. Or change it to something else (e.g. `Ctrl+/`, which then would make it subject to the browsers "override keyboard shortcut" permission, which only govern shortcuts that use a modifier key)

### Example URLs

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
Already possible: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/managing-accessibility-settings#managing-keyboard-shortcuts

If not, contact GitHub for a better solution, we can't just break shortcuts in Refined GitHub.

**Comment by gcbw** [comment]
Thanks for the link! Their setting is excellent, but not very helpful if not logged in.

will probably still publish the code to a one-off extension for this. Might make more sense to prevent `/` hijack on more sites than just github actually.

Thanks you

**Comment by ernstki** [comment]
This userscript will work, too:

```javascript
// ==UserScript==
// @name           prevent GitHub from intercepting '/'
// @description    "/" slash should always bring up FF quickfind
// @run-at         document-start
// @match          https://github.com/.*
// @grant          none
// @version        0.0.1
// ==/UserScript==
/* source: https://superuser.com/a/1702003 */
document.addEventListener('keydown', function(e) {
  e.keyCode==191 && e.stopImmediatePropagation();
  return false;
}, true);
```

If you're not familiar with userscripts, see [this Super User answer](https://superuser.com/a/1702003/73744), which is a bit dated, but the advice still applies. If you don't use Firefox,  [Tampermonkey](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/) is another option, albeit under a proprietary license.

## References

1. <https://superuser.com/questions/399352/how-do-i-prevent-pages-i-visit-from-overriding-selected-firefox-shortcut-keys>
2. <https://superuser.com/questions/113806/firefox-dont-allow-websites-to-override-the-slash-key>
