### ISSUE TITLE
Some features are missing in Firefox

### ISSUE THREAD

**Issue by codezninja** [refined-github/refined-github#5988]
I've been using this feature for both GHE and github.com and recently I can't remember when it seems to have stopped working. I checked that I'm on the latest version of the extension `22.9.15` and the PATs for both instances are ✅ under extensions settings. 

Here's the screenshot for github.com. I've also restarted the browser and computer just in case.

![image](https://user-images.githubusercontent.com/4400773/190455651-043227e4-8527-4738-b26c-d284fa1501bb.png)

### Example URL

https://github.com/notifications

**Comment by yakov116** [comment]
Can you paste the URL?

**Comment by fregante** [comment]
It's possible that it has been broken for the view "grouped by repository"

**Comment by gravyboat** [comment]
I'm experiencing this as well since the 22.9.9 release last week. To answer @yakov116's questions:

* URL: https://github.com/notifications?query=is%3Aunread (redirects from https://github.com/notifications via the bell icon in the GitHub UI)
* Browser: Firefox 104.0.2
* OS: Windows 10 and MacOS Monterey 12.6

**Comment by fregante** [comment]
I think you just need to reload the page. It seems to be:

- #5895 

For the rare times when it doesn't appear, it does after a reload:

https://user-images.githubusercontent.com/1402241/190546639-abd61d96-aa5c-481f-a523-bc0a1f0cfdb2.mov

**Comment by codezninja** [comment]
> I think you just need to reload the page:

I've tried reloading and it still didn't show up

**Comment by goodevilgenius** [comment]
I'm having this issue on Firefox on macOS. Have not yet checked other browsers/OSs.

Reloading does not fix the issue.

**Comment by cheap-glitch** [comment]
This feature and several others (`toggle-files-button`, `reactions-avatars`, maybe more) are completely broken on Firefox (tested on both Linux & macOS). They don't appear even when reloading the page.
This is the case since the previous version btw.

**Comment by fregante** [comment]
Confirmed to be a bug visible at least in Firefox. It's due to `getSnapshotUUID` and probably a difference in stack trace format.

Possible solutions:

- fix `getSnapshotUUID` so that it points to the right line in the source
- replace `getSnapshotUUID` with just a WeakMap-based random ID, like:
	```js
	const ids = new WeakMap();
	function getFunctionId(fn) {
	    if (!ids.has(fn)) {
			ids.set(fn, crypto.randomUUID().slice(0, 6))
		}
		return ids.get(fn)
	}

	className = 'rgh-' + getFunctionId(listener)
	```
