### ISSUE TITLE
Diff viewed/remaining meter UI on PRs

### ISSUE THREAD

**Issue by ValentinH** [refined-github/refined-github#5989]
### Description

Currently, when reviewing a PR, Github displays a progress of how many files have been seen.
It would be much more helpful if it was showing the number of "lines" viewed instead.

There is a already a feature request on the main Github discussion board: https://github.com/community/community/discussions/11251

I've never contributed to `refined-github` so I'm not sure how feasible this is but I feel like there is already the required data on the page to compute such a progress bar. If it sounds like a good idea, I'd love to work on this.

### Screenshot

![image](https://user-images.githubusercontent.com/2678610/190604083-03dbb99f-efbd-4d58-a66d-5b0059b659e5.png)

### Example URLs

https://github.com/ValentinH/react-easy-crop/pull/404/files?w=1

**Comment by fregante** [comment]
> the required data on the page

Only sometimes. GitHub loads large PRs progressively, where "large" could just be 5 files. Given that this would require substantial work to keep the UI up to date, I don’t think this could work in Refined GitHub. In a dedicate extension/userscript it would be better.

**Comment by ValentinH** [comment]
I need to dig deeper but while inspecting the requests I saw one that was containing the diff count for each file. I think it's used for the sidebar which doesn't seen load progressively.

Also I need to have a look to the GitHub API to see if there is an endpoint regarding this data. In this topic, I have a probably naive question: is calling the API with authentication something that is already done in Refined GitHub?

**Comment by fregante** [comment]
Yes we already use the API, the token is provided in the options.

But then again this is probably too much for Refined GitHub
