### ISSUE TITLE
`table-input` details-menu is always open

### ISSUE THREAD

**Issue by aminomancer** [refined-github/refined-github#6003]
### Description

You probably already noticed this since it's hard to miss, but the table input button's grid popup is always open. I think it's just a CSS issue
```
:root .rgh-table-input {
  width: auto;
  padding: 3px;
  z-index: 99;
  display: grid !important;
  grid-template: repeat(5, 20px) / repeat(5, 20px);
}
```
has higher priority than
```
details:not([open]) > :not(summary) {
  display: none !important;
}
```

### How to replicate the issue

See the comment box input at the bottom of this page

### Extension version

22.9.21

### Browser(s) used

Firefox 107.0a1 (Nightly 2022-09-20)

**Comment by fregante** [comment]
Thanks for the report! I'll look into this soon. Can you include a screenshot?

**Comment by aminomancer** [comment]
![image](https://user-images.githubusercontent.com/33384265/191472427-e7e92ea9-3e82-4f9f-b7f2-617a23bd21f5.png)

Sure, here's a screenshot on Firefox. And yes, this is on github.com. I tried disabling other add-ons btw. The rule being overridden is [in here](https://github.githubassets.com/assets/primer-0e158a2f5ddd.css), which I guess is generated [from this](https://www.npmjs.com/package/@primer/css). Could be color scheme dependent, I have the "Dark default" theme enabled in https://github.com/settings/appearance

**Comment by fregante** [comment]
You're on a nightly version. It works correctly on Firefox 103 and Firefox 105 on Mac, even with the black default theme.

**Comment by fregante** [comment]
Even if the final `display` value is `grid`, the browser still hides the element because that's how `details` work. I think you should report it to Mozilla before it reaches the stable version.

<img width="726" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/191482871-caba52ae-8b3d-45d1-98f3-48e915a73c42.png">

**Comment by fregante** [comment]
For a quick fix, you might want to add something like this to the CSS field in the options:

```css
:root details:not([open]) > .rgh-table-input:not(summary) {
  display: none !important;
}
```

**Comment by aminomancer** [comment]
Ah, you're right. Thanks for your patience, it was actually my fault lol. The presence of the author sheet rule hiding the details content confused me, figured that it was intended to override the UA styles, but now (at least in Firefox) they're not overridable at all.
