### ISSUE TITLE
`bypass-checks` broken

### ISSUE THREAD

**Issue by SkySkimmer** [refined-github/refined-github#6004]
### Description

It used to work and now doesn't.

### How to replicate the issue

Go to https://github.com/coq/opam-coq-archive/pull/2317 
The check list has a link to https://github.com/coq/opam-coq-archive/runs/8449939508
It should be a link to https://gitlab.com/coq/opam-coq-archive/pipelines/645312543

### Extension version

22.9.21

### Browser(s) used

Firefox 104.0.2

**Comment by fregante** [comment]
Thanks for the report! The issue is likely the same as https://github.com/refined-github/refined-github/issues/5988
