### ISSUE TITLE
Button for `github.dev`

### ISSUE THREAD

**Issue by LePips** [refined-github/refined-github#6009]
### Description

On a repo, you can replace the url from `github.com` to `github.dev` and it will open up a browser instance of VSCode with the repo for that project.

It would be particularly handy if there was a button added to automatically redirect to this URL.

### Guidelines
> 1. It doesn't already exist as a [userscript](https://github.com/Mottie/GitHub-userscripts) or extension.

This is sort of like [GitHub in VSCode](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-in-VSCode), however differs in what URL is being used and how a project is opened.

> 2. It makes sense as a default for everyone.

This makes particular sense due to this being an official product from GitHub.

### Screenshot

Note: I propose using the SVG VSCode logo instead, I put "Dev" as a placeholder just as a mock for where the button can go.

<details>
<summary>Mock</summary>

<img width="928" alt="Screen Shot 2022-09-22 at 10 55 02 AM" src="https://user-images.githubusercontent.com/20747774/191807137-fcf3e049-4c43-4135-8f63-ef5bb3564f21.png">
</details>

### Example URLs

https://github.dev/refined-github/refined-github

**Comment by yakov116** [comment]
I good news for you! It exists! from GitHub it self!
Press the <kbd>.</kbd> on the repo main.
