### ISSUE TITLE
Ignore archived upstream repos in `show-open-prs-of-forks`

### ISSUE THREAD

**Issue by PeterDaveHello** [refined-github/refined-github#6010]
### Description

This alert is pretty sweat, but maybe ignore those PRs when the upstream already archived the repo will be even more awesome 😄 

`This repo has open issues/PRs, are you sure you want to delete everything?`

### Screenshot

![image](https://user-images.githubusercontent.com/3691490/191813618-66f24f36-2118-4df3-94d4-d42a48d5bd0c.png)

### Example URLs

https://github.com/PeterDaveHello/js-signals

**Comment by fregante** [comment]
> when the upstream already archived the repo

I don't see any archived repos in your example URL and in its fork source. Did you see the alert when trying to delete the linked repo?

**Comment by PeterDaveHello** [comment]
Oh, sorry, I must paste a wrong url, trying to find out the example needed here, I remember that I deleted already 😅

**Comment by PeterDaveHello** [comment]
Okay now I found another example:

- https://github.com/PeterDaveHelloKitchen/imagelayers-graph

![image](https://user-images.githubusercontent.com/3691490/193530583-25f8623f-bb79-49de-b4be-48a71f5f50fe.png)

![image](https://user-images.githubusercontent.com/3691490/193530659-3aac01e4-048b-4121-8905-d9924308b888.png)

![image](https://user-images.githubusercontent.com/3691490/193530705-34aea227-b920-4446-8e01-fe8a178ab378.png)

**Comment by fregante** [comment]
Indeed! #6042 should fix that and also hide `show-open-prs-of-forks`, which has the underlying issue.

**Comment by PeterDaveHello** [comment]
Is it possible to have a not that aggressive strategy that we can still know that there are PR opened, just with hints that the upstream was archived?

**Comment by fregante** [comment]
I don’t think you can do anything about PRs on archived repo. 

The issue here specifically is that the deletion feature just depends on the element being on the page, it doesn’t make its own query. It’s not worth here to double the query (archived or not archived) just to avoid a warning (which is still correct)
