### ISSUE TITLE
Duplicate on `global-conversation-list-filters`

### ISSUE THREAD

**Issue by Katsute** [refined-github/refined-github#6011]
### Description

Duplicate when backtracking from issues & pulls.

https://user-images.githubusercontent.com/58778985/191875609-19c812ec-d5c6-43df-a5ea-9fa165a7a59f.mp4

### How to replicate the issue

1. https://github.com/pulls
2. Press **Commented**
3. Go back

### Extension version

22.9.21

### Browser(s) used

Google Chrome 105.0.5195.127

**Comment by fregante** [comment]
Thanks for the report. We broke and fixed this feature so many times it's not even funny anymore. 🥲

**Comment by fregante** [comment]
Easy fix: replace the `select` with the element observer, like:

```js
function appendLinks(links) {
  // blah blah
  links.append(link)
}

function init(signal) {
  observe('.subnav-links', appendLinks, {signal})
}
