### ISSUE TITLE
Add `for Safari` to macOS app name

### ISSUE THREAD

**Issue by rakleed** [refined-github/refined-github#6012]
### Description

Can you add `for Safari` to the macOS app name? Since this is not a full-fledged macOS app, but just an extension for Safari, and many other extensions have done so.

### Screenshot

![Screenshot 2022-09-23 at 18 57 42](https://user-images.githubusercontent.com/19418601/192002956-af534833-91be-4c51-af83-2764c05529dc.png)

### Example URLs

N/A

**Comment by fregante** [comment]
Up to @sindresorhus

**Comment by sindresorhus** [comment]
Not sure I see the point. The two middle ones have that name because they also have separate main apps, so they have to differentiate them. I have 14 Safari extensions installed and none use this naming convention.
