### ISSUE TITLE
Duplicate on `user-local-time` (official feature now)

### ISSUE THREAD

**Issue by Katsute** [refined-github/refined-github#6013]
### Description

Local timezones were just added to GitHub; optional feature that users can set, only visible on profiles who actually set up a local timezone.

See https://github.blog/changelog/2022-09-23-local-timezones-available-on-profiles/

![image](https://user-images.githubusercontent.com/58778985/192012089-82639249-4649-48c5-82c8-d647bf5422e0.png)

### How to replicate the issue

https://github.com/Katsute

### Extension version

22.9.21

### Browser(s) used

Google Chrome 105.0.5195.127

**Comment by fregante** [comment]
Excellent! Ours was potentially very heavy. Happy to drop it. Please open a PR
