### ISSUE TITLE
`release-download-count` not visible sometimes

### ISSUE THREAD

**Issue by surfzoid** [refined-github/refined-github#6014]
### Description

Hi
Whit ff or chrome, after enable extension and put token, restart browser, under release page, the download counter isn't displayed.

### How to replicate the issue

1. Visit https://github.com/surfzoid/QtVsPlayer/releases/tag/1.0.19

### Extension version

22.9.21

### Browser(s) used

Firefox, chrome, chromium

**Comment by cheap-glitch** [comment]
I see them here: https://github.com/notepad-plus-plus/notepad-plus-plus/releases

<img width="284" alt="image" src="https://user-images.githubusercontent.com/46634000/192092486-361bd535-9007-4b69-ac51-9ef207917eaa.png">

Please provide an actual URL where the bug is visible.

**Comment by surfzoid** [comment]
The bug is for all my repository, I'm running Linux Magea 8

**Comment by fregante** [comment]
You must provide a screenshot and a real URL as required by the bug report form. The issue can be reopened after that

**Comment by surfzoid** [comment]
> You must provide a screenshot and a real URL as required by the bug report form. The issue can be reopened after that

Sorry, l'm not at home for the weekend, so I cannot provide screenshot, but I'm not so old yet and know we're i should see the counter.
Here it is the direct url of one of my repo
https://github.com/surfzoid/QtVsPlayer/releases/tag/1.0.19

I would prefer read do this or that to provide debug info and help you to solve the problem or find a workaround.
I thanks you

**Comment by fregante** [comment]
Indeed it works on https://github.com/notepad-plus-plus/notepad-plus-plus/releases

but not on https://github.com/surfzoid/QtVsPlayer/releases

**Comment by surfzoid** [comment]
Okay, so where the should be?

**Comment by surfzoid** [comment]
Hi,
the folowing api response show the download count
https://api.github.com/repos/surfzoid/QtVsPlayer/releases/latest
I'm not sure to understand the link with hiden coment.
Is there an maximise/minimise event to refresh the download count ?

**Comment by fregante** [comment]
This issue was accepted. No further comments are neded.

**Comment by fregante** [comment]
The assets list is loaded later on some pages, including:

- https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v8.4.6

### Solution

Replace the release selection:

https://github.com/refined-github/refined-github/blob/5e17c86770cc63a86e1dde6d5951d2d90a3ea013/source/features/release-download-count.tsx#L54

With an observer call, maybe with `batchedFunction`:

https://github.com/refined-github/refined-github/blob/da89c8ee20aa2d9ce8ac4fb5fc7225265539a8ab/source/features/show-names.tsx#L78

I think this whole block should be replaced with a single proper selector, like "get each _assets **list**_ on the page", then get/filter the remaining data from there.

**Comment by surfzoid** [comment]
Hi,
thank yu @fregante for your job.
Do i need to wait official update or there is an easy way to test the solution now?

**Comment by muescha** [comment]
> Do i need to wait official update or there is an easy way to test the solution now?

here you find a guideline to activate the extension with a local repo clone at your browser 
https://github.com/refined-github/refined-github/blob/main/contributing.md

**Comment by TigerBeanst** [comment]
@fregante 
Using 22.10.3(Edge but installed from chrome webstore)
![image](https://user-images.githubusercontent.com/3889846/194818540-05f996ca-be83-4708-a2d7-90e7cb320403.png)
but download count still didnot show in **special tag release**...

https://github.com/TigerBeanst/TigerInTheWall/releases , it shows.
![image](https://user-images.githubusercontent.com/3889846/194818027-fe42b7cd-285f-423f-a83a-489cf52a1307.png)

But not at https://github.com/TigerBeanst/TigerInTheWall/releases/tag/v1.0.6
![image](https://user-images.githubusercontent.com/3889846/194818112-5f9058be-11ac-4d5c-bbd0-9b493c6bc27e.png)

**Comment by surfzoid** [comment]
Hi,
problem is back, no more download counter with chrome or ff

**Comment by surfzoid** [comment]
i forgot to give my chrome extension version :+1: 22.12.15

**Comment by surfzoid** [comment]
Hi,
perhaps github itself bug, because if we look here https://qii404.me/github-release-statistics/?repo=/surfzoid/QtVsPlayer/ last release have 2 downloads but my badge in the README.md display 0 since yesterday : https://github.com/surfzoid/QtVsPlayer

**Comment by surfzoid** [comment]
Hi,
could you please build the chrome update?

**Comment by yakov116** [comment]
It has been already
[link-chrome]: https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf

**Comment by surfzoid** [comment]
> It has been already [link-chrome]: [chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf](https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf)

this is not the one with the bug fix mentioned here

**Comment by yakov116** [comment]
I see the fix

![image](https://user-images.githubusercontent.com/16872793/216137445-21d02a26-0a6f-4356-8bd5-165829a2ec66.png)

**Comment by surfzoid** [comment]
hum, strange me too now!

**Comment by surfzoid** [comment]
if i can make a suggestion and it's not too hard, a global download counter near the release name
