### ISSUE TITLE
Sort branch/tag dropdown by last modified

### ISSUE THREAD

**Issue by kerryj89** [refined-github/refined-github#6015]
### Description

I wonder if it's possible to add an option to sort the branch and tags list by last modified instead of alphabetical?

### Screenshot

![image](https://user-images.githubusercontent.com/1977804/192124082-a73dd7b2-1892-463d-8ae6-583cd0748e70.png)

### Example URLs

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
This annoys me too, I don't like the current order.

However I don't think we can actually do this here, we'd need to query the API and build the list ourselves, basically.

Can you send a request to GitHub?

**Comment by kerryj89** [comment]
I opened it up here, I couldn't find anyone else suggesting it surprisingly (but maybe I just suck at searching) https://github.com/orgs/community/discussions/34123
