### ISSUE TITLE
`quick-comment-edit` not longer available in discussions

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [refined-github/refined-github#6029]
### Description

I'm no longer seeing the quick-comment-edit button in discussions

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/8518288/193599829-9e1660ad-02b3-4da5-aa87-bed7b7fbc813.png">

Console log shows me
```
refined-github.js:5437 Uncaught TypeError: Cannot read properties of null (reading 'before')
    at addQuickEditButton (refined-github.js:5437:155)
    at refined-github.js:5082:7
addQuickEditButton @ refined-github.js:5437
```

As an example, see this [public discussion](https://github.com/ConstantinoSchillebeeckx/ghpm/discussions/13).

### How to replicate the issue

* create discussion
* try to edit it

### Extension version

22.9.25

### Browser(s) used

Chrome Version 105.0.5195.125

**Comment by fregante** [comment]
@ConstantinoSchillebeeckx URL to an example discussion needed, as requested by the issue template.
