### ISSUE TITLE
Find out the files you are CODEOWNER for in PR

### ISSUE THREAD

**Issue by piegamesde** [refined-github/refined-github#6031]
### Description

When there is a massive pull request that touches hundreds of files and I am CODEOWNER for a few of them, I'd like to be able to somehow filter for that.

### Screenshot

![image](https://user-images.githubusercontent.com/14054505/193331230-a7c7618a-ebc5-4c2f-ab8b-eeaad8500776.png)

### Example URLs

https://github.com/NixOS/nixpkgs/pull/193494

**Comment by fregante** [comment]
It makes sense, but building a dynamic dropdown and filter for a niche situation doesn't belong to Refined GitHub.

- Take the repos that use CODEOWNERS
	- Take the PRs that affect 10+ files
		- Take users of Refined GitHub
			- Take users that know this feature

It's not a lot of users compared to the complexity of the feature.

I suggest sending a message to GitHub

**Comment by piegamesde** [comment]
Thanks. I agree it is a fairly niche issue, as I only experience it with the `nixpkgs` repository. However, would there be any solutions that are easy enough to implement? Something like highlighting owned files or adding a "owned by you" so that I can easily find them while scrolling or with a text search would already help a lot.

**Comment by fregante** [comment]
That's far easier indeed, but I'm not sure it would help you filter the files out in this large PR.

Example CSS to add to your options:

```css
.js-file:has([aria-label~="CODEOWNERS"][aria-label*="@piegamesde"]){
	border-color: red;
}
```

<img width="351" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/193337739-374ef878-288e-44b2-ab34-e14553c21bca.png">
