### ISSUE TITLE
Expand/load all hidden items (comments) recursively

### ISSUE THREAD

**Issue by SUPERCILEX** [refined-github/refined-github#6044]
### Description

When comment chains get long enough, it's a massive pain to expand them all if you want to do a Ctrl + F on them. Add a button to continuously expand hidden items until they're all there.

### Example URLs

https://github.com/rust-lang/rust/issues/31844

**Comment by fregante** [comment]
We already have it: `expand-all-hidden-comments`

**Comment by SUPERCILEX** [comment]
Ohhh, alt click! Thanks! :)

**Comment by thulle** [comment]
In fluxbox alt+lmb is used to move windows and thus this doesn't work. Any way to rebind it to another modifier than alt?
