### ISSUE TITLE
Update the screenshot for one click review submission

### ISSUE THREAD

**Issue by grahamperrin** [refined-github/refined-github#6048]
### Description

The documented screenshot, in context: 

![image](https://user-images.githubusercontent.com/192271/194459231-7abacdb5-8483-477f-8a85-290e50276602.png)

### Screenshot

The dialogue that appeared for me: 

![2022-10-07](https://user-images.githubusercontent.com/192271/194459298-6a20f507-a903-42dc-8c3c-27ed5009cea3.png)

### Example URLs

moz-extension://0b6f89f1-fea7-482c-a1c4-6bda8fb3feb5/options.html

**Comment by fregante** [comment]
Thank you! Most screenshots are bound to be out of date. This is tracked in https://github.com/refined-github/refined-github/issues/5222#issuecomment-996620545

**Comment by cobrabr** [comment]
Sorry for the necro, but: instead of fixing the screenshot, would it be possible to change the button colours to match the screenshots again? It would make more sense, imo, to have the _Approve_ button be green and the _Comment_ button be in the more subdued colour.

**Comment by fregante** [comment]
<img width="594" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/236522023-9976c6df-c4dd-4d76-a853-ebf00c9c6264.png">
