### ISSUE TITLE
Link to draft release on repo home

### ISSUE THREAD

**Issue by ssbarnea** [refined-github/refined-github#6052]
### Description

As project maintainer, I find very inconvenient to go to last release draft. It requires at least 3 page loads, as clicking on the last release would open that last release page, after which you press releases to see list of releases, and after this you click on the first entry (like a draft).

We need to also display the last draft when that is available, so we can directly go to it.

### Screenshot

![](https://sbarnea.com/ss/Screen-Shot-2022-10-08-16-48-25.74.png)

### Example URLs

N/A

**Comment by fregante** [comment]
Refined GitHub already adds a tab that points to the releases page in every repo, as long as there is at least one release (token required for the tab to show, if I remember correctly). So that brings it down to a reasonable "2 clicks" from any page on the repo.  

I don’t think this needs to be reduced further as draft releases are not something the vast majority of users use.

**Comment by ssbarnea** [comment]
I would say that the github-refined users are more likely than others to be heavy-users, like maintainers for packages. The tricky bit is that the draft information requires token, as it is not public information.

I asked GH team some time in the past about an option to make drafts public, but apparently that is not on any roadmap for them. They still consider it "private information", and they were concerned that about potential release info leaks... :p

**Comment by fregante** [comment]
I suppose it could be part of `latest-tag-button` given that it already shows a Compare button when commits haven't been released yet. Example:

<img width="567" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/195277170-c6ccfda3-7ca1-404b-a20f-790b8369090b.png">

**Comment by fregante** [comment]
Linking to the draft requires making a request on every repo you visit, so I'm going to close this issue. I'll open a specific one for my suggestion above
