### ISSUE TITLE
`user-profile-follower-badge` keep duplicating when going back and forth

### ISSUE THREAD

**Issue by rluvaton** [refined-github/refined-github#6053]
### Description

The follows you is duplicating

### How to replicate the issue

Go to some users that follow you and go to your profile and back

https://user-images.githubusercontent.com/16746759/194730562-278c1fc3-2ab3-4647-801c-05711876a032.mov

### Extension version

22.10.3

### Browser(s) used

Chrome 105.0.5195.125

**Comment by rluvaton** [comment]
I was about to create a fix and then I saw this:
https://github.com/refined-github/refined-github/blob/c1f308405ae9ce5f712803265b93be537178863d/source/features/user-profile-follower-badge.tsx#L37

which looks like it relates to this issue

**Comment by fregante** [comment]
If you'd like to send a PR, you can use the `selector-observer.ts`, it has automatic deduplication. Check the other features to find out how to use it. 

That `decuplicate` line can then be dropped, it's obsolete.

**Comment by rluvaton** [comment]
> If you'd like to send a PR, you can use the `selector-observer.ts`, it has automatic deduplication. Check the other features to find out how to use it. 
> 
> That `deduplicate` line can then be dropped, it's deprecated. 

Oh sorry missed your comment, was on vacation
