### ISSUE TITLE
Allow changing date format in the milestone create page

### ISSUE THREAD

**Issue by diogotcorreia** [refined-github/refined-github#6054]
### Description

The "due date" field in the create milestone page is in American format.
It'd be great if we could change it either to `YYYY-MM-DD` (prefered) or to `DD-MM-YYYY`.

Not sure if there are other date inputs, but this is the one I use the most and it's very confusing as a non-American.

Related: https://github.com/orgs/community/discussions/16693

### Screenshot

![image](https://user-images.githubusercontent.com/7467891/194754532-c1e07e9d-9007-4fdd-8923-a8f7eb6d835c.png)

### Example URLs

https://github.com/refined-github/refined-github/milestones/new
`https://github.com/<user/org>/<repo>/milestones/new`

**Comment by fregante** [comment]
There is now a date picker:

<img width="482" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/205433469-d7786d28-b955-4799-ad9f-033393426548.png">
