### ISSUE TITLE
Automatically merge after REQUIRED checks are done

### ISSUE THREAD

**Issue by SIMULATAN** [refined-github/refined-github#6055]
### Description

So far, there's already the module `wait-for-checks` (which by the way is really nice!), but unfortunately, when checks are **enforced** by the policy defined on GitHub, the module doesn't work, because you can't click the merge button in the first place.
It would be great to have the feature work even when some checks are required.

### Screenshot

![merge window](https://user-images.githubusercontent.com/63104422/194808839-12777097-2318-4396-8fdc-f8268a4c60d0.png)

NOTE: ticking the checkbox also doesn't enable the `wait-for-checks` feature

### Example URLs

`https://github.com/<user>/<repo>/pull/<number>`
No concrete URL because you need write permissions to access the wanted feature.

**Comment by fregante** [comment]
GitHub already offers this feature natively: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request
