### ISSUE TITLE
`align-issue-labels` broken on milestones

### ISSUE THREAD

**Issue by tyrann0us** [refined-github/refined-github#6056]
### Description

In the issue overview of a milestone, the first label doesn't have any margin to the issue title.

### How to replicate the issue

1. Go to a repository that has milestones with issues with labels
2. Go to a milestone
3. Notice how the labels are too close to the issue title:
<img width="926" alt="Bildschirmfoto 2022-10-10 um 09 29 00" src="https://user-images.githubusercontent.com/8144115/194816756-a26bd081-daee-442c-858a-30995d87a786.png">

~Note that I don't know why the labels are not displayed below the meta information for this particular repository. Could this be caused by permission differences (we don't own it)?~
Edit: I updated the issue to make it clear that this happens on the milestone view.

### Extension version

22.10.3

### Browser(s) used

Chrome 106.0.5249.103

**Comment by fregante** [comment]
> * Go to a repository where the labels are displayed next to the title instead of below the "meta information"

URL required

**Comment by tyrann0us** [comment]
Hi @fregante, thanks for getting back to me.

I just realized that it's not happening on the issue overview, but on a _milestone_. Sorry for not noticing this earlier. Example URL: https://github.com/bmish/eslint-doc-generator/milestone/1

What do you think about moving the labels below the meta information for milestones, just like for the issue list?
