### ISSUE TITLE
PR diff layout broken

### ISSUE THREAD

**Issue by levrik** [refined-github/refined-github#6061]
### Description

All diff views are broken on GitHub since at least this morning.
I saw it working the last time on Friday before the weekend.

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/9491603/194866813-a1111748-26b3-48a0-bd34-45cf85a7ebe1.png">

I don't know if it's related but the following error is thrown in the console.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'cloneNode')
    at refined-github.js:9671:37
    at observe.signal.signal (refined-github.js:9680:12)
    at window.addEventListener.signal.signal (refined-github.js:5083:9)
```

The feature causing this issue seems to be `no-unnecessary-split-diff-view`.

### How to replicate the issue

Just open any page that shows a diff on GitHub, commit, PR etc
Here is an example https://github.com/levrik/mdi-react/commit/ea0580f795f027cb77a0bb8b45db95ed5191738a

### Extension version

22.10.10

### Browser(s) used

Microsoft Edge 106.0.1370.37

**Comment by gustavkj** [comment]
I was just gonna report this. Based on my local testing, it seems to originate from this PR: https://github.com/refined-github/refined-github/pull/6023

**Comment by ovflowd** [comment]
@fregante I still see this issue happening 😅 (Example on screenshot below)

![image](https://user-images.githubusercontent.com/12037269/194925592-315bf9b2-bc99-4916-ae04-bb4c55e22e00.png)

Is there any action needed from the user side? (Already using latest version of the extension)

**Comment by fregante** [comment]
@ovflowd the hotfix is working correctly:

<img width="545" alt="Screen Shot 14" src="https://user-images.githubusercontent.com/1402241/194927490-5ee13cec-7b68-470b-ad5c-70945e3569d4.png">

If you see the bug, refresh the page:

![gif](https://user-images.githubusercontent.com/1402241/194927745-72e68471-7cd4-4ecc-9f21-40c839a7638c.gif)

**Comment by ovflowd** [comment]
I can see that it says it was disabled, but even with force refresh, it doesn't work. Only works by disabling the extension :(

**Comment by fregante** [comment]
What browser are you using?

**Comment by ovflowd** [comment]
Chrome 106.0.5249.103 on macOS 12.6

**Comment by fregante** [comment]
I sent an actual CSS hotfix so the feature continues working and the bug is fixed. 

I suppose tomorrow I will release 20.10.11 with a proper fix in #6063

**Comment by ovflowd** [comment]
> @ovflowd are you using the version from the store? I'm using the same browser for testing and hotfixes work

You mean Chrome Web Store?

**Comment by lekoaf** [comment]
v22.10.10, issue "fixed" if I disable the `no-unnecessary-split-diff-view` rule.

**Comment by dwijnand** [comment]
Just wanted to shout out how great it is that the feature can be disabled without have to wait for another release or install a pre-release.  👍🏼 ❤️

**Comment by fregante** [comment]
I'm not sure why you're seeing the issue. The feature has been hotfixed already 🤔

**Comment by fregante** [comment]
22.10.11 out soon

**Comment by dwijnand** [comment]
No, clearing the cache didn't fix it.
