### ISSUE TITLE
Add discussions tab along top of main repo

### ISSUE THREAD

**Issue by sgbaird** [refined-github/refined-github#6062]
### Description

Right now, there is a search bar, pull requests, issues, marketplace, and explore.

If I manually go to https://github.com/discussions then I see all the discussions.

### Screenshot

![image](https://user-images.githubusercontent.com/45469701/194874171-2d28f71a-1411-42c0-bc4f-4b2335e7f3f6.png)

Maybe add "Discussions" after "Issues"?

### Example URLs

https://github.com

**Comment by fregante** [comment]
It's a relatively simple feature but I don't use Discussions that much. The issue comes with responsiveness. I suppose it can be shown in large windows.

**Comment by fregante** [comment]
I'm going to skip this as browsers already have bookmarks for this

**Comment by KaKi87** [comment]
> browsers already have bookmarks for this

Seriously ?

You could say that for anything else : bookmarks can replace global navigation, bookmarklets can replace local navigation and external redirections, editors can replace formatting buttons, etc.

Nevertheless, that feature would be as much as relevant as every other existing one.

And if we should necessarily use bookmarks then why not removing the menu altogether ?
