### ISSUE TITLE
PR code suggestions are hidden

### ISSUE THREAD

**Issue by stowball** [refined-github/refined-github#6064]
### Description

When suggesting a change in a PR, the suggestion is hidden because of this line of code:

```
.rgh-no-unnecessary-split-diff-view :is(.inline-comments, .js-inline-annotations) td:nth-child(2) {
    display: var(--rgh-only-additions, var(--rgh-only-deletions, table-cell)) !important;
}
```

Where

```
.rgh-no-unnecessary-split-diff-view .js-diff-table:not(:has([data-split-side="left"]:is(.blob-code-addition, .blob-code-deletion))) {
    --rgh-only-additions:  none;
    table-layout: auto !important;
}
```

See video https://youtu.be/D1LGMMw33IA

### How to replicate the issue

In a PR, add a code suggestion

### Extension version

22.10.10

### Browser(s) used

Chrome 106.0.5249.61

**Comment by fregante** [comment]
Thank you for the report!

If you clear the cache in the extension’s options and refresh the page twice, this should be fixed in 22.10.10.

I will add a proper fix in the next version:

- https://github.com/refined-github/refined-github/pull/6063
