### ISSUE TITLE
Add a new option to hide `x created y releases`

### ISSUE THREAD

**Issue by Dentrax** [refined-github/refined-github#6066]
### Description

It would be nice to have such a hiding option to _hide_ `x created y releases` spams in the feed. The current workaround is to unfollow the user.

### Screenshot

![Screen Shot 2022-10-11 at 11 24 39](https://user-images.githubusercontent.com/16493751/195038221-cd2b56df-c040-410c-8e87-d2b6f2d2cf8d.png)

### Example URLs

Feed - https://github.com

**Comment by fregante** [comment]
This is already part of `clean-dashboard`, but I think they pushed an updated that broke it.

**Comment by fregante** [comment]
I pushed a hotfix, you can clear the cache in the options page to see it

<img width="225" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/195043416-5dd499f9-1600-4b7d-870e-0a1f4f5ce97b.png">
