### ISSUE TITLE
Collapsed star events do not show repository link

### ISSUE THREAD

**Issue by jahirfiquitiva** [refined-github/refined-github#6069]
### Description

The collapsed star events do not show repository link

![Shot 2022-10-11 at 16 36 56@2x](https://user-images.githubusercontent.com/10360816/195203437-84394a0f-181d-4480-b531-76cd56ab4e71.png)

### How to replicate the issue + URL

The issue happens in the GitHub feed https://github.com/

### Extension version

22.10.11

### Browser(s) used

Edge

**Comment by kxxoling** [comment]
Same issue here, disabled `clean-dashboard` as a temporary solution. For someone using Chrome, you can configure it here: chrome://extensions/?id=hlepfoohegkhhmjieoechaddaejaokhf
