### ISSUE TITLE
Stacking Tabs in Pull requests

### ISSUE THREAD

**Issue by KSH-code** [refined-github/refined-github#6073]
### Description

1. Visit https://github.com/pulls
2. Click any pr.
3. go back history
4. then tabs are stacked.

### How to replicate the issue + URL

![image](https://user-images.githubusercontent.com/29705162/195278582-469e01e7-acd9-4769-8943-2321f93d296b.png)

### Extension version

22.9.15

### Browser(s) used

Chrome 105.0.5195.102

**Comment by fregante** [comment]
This was fixed in recent versions, your browser is using a month-old version
