### ISSUE TITLE
rgh-toggle-files is not re-added after navigation

### ISSUE THREAD

**Issue by panva** [refined-github/refined-github#6077]
### Description

The "Toggle files section" does not get re-added after github's turbo navigation.

### How to replicate the issue + URL

1. https://github.com/panva/oauth4webapi
2. Click the "Toggle files section" element
3. Navigate to Issues
4. Navigate back to Code
5. The toggle is gone, the only way to expand the files section is to do a full reload, then the toggle is present.

![Kapture 2022-10-12 at 11 23 49](https://user-images.githubusercontent.com/241506/195305666-2aa64cf4-6ca8-4598-bbf7-43ec9cf8874c.gif)

### Extension version

22.10.11

### Browser(s) used

Chrome latest

NB: I hid the "The file list was collapsed via Refined GitHub" notice with `.rgh-files-hidden-notice{display:none;}` because it has caused issues in the past (getting added multiple times), it also causes content to get pushed after it has rendered, everything's much more stable vertically when this notice is gone.

**Comment by fregante** [comment]
> it has caused issues in the past (getting added multiple times)

That was fixed

> it also causes content to get pushed after it has rendered

I'll fix that in my next PR




> 5\. The toggle is gone

- Due to https://github.com/refined-github/refined-github/issues/5751

**Comment by panva** [comment]
Cheers @fregante, I'll keep the notice hidden anyway, it's just clutter.
