### ISSUE TITLE
Quick action to remove self from as a requested reviewer from the "Review requested" tab

### ISSUE THREAD

**Issue by 100terres** [refined-github/refined-github#6086]
### Description

It would be really useful in my flow to be able to quickly remove myself as a requested reviewer on a pull request in the view: https://github.com/pulls/review-requested

Let me know what you think.

### Screenshot

Ww could add a call to action on each row of this table to perform this action?

![Screenshot from 2022-10-14 22-01-53](https://user-images.githubusercontent.com/4420524/195964155-eb82df41-0037-4cd1-b96b-25c55d79a171.png)

![Screenshot from 2022-10-14 22-05-23](https://user-images.githubusercontent.com/4420524/195964152-76966002-8720-4551-861a-6e96ed31f793.png)

### Example URLs

https://github.com/pulls/review-requested

**Comment by fregante** [comment]
Is this even possible? The only way I can find is to actually leave a review

**Comment by 100terres** [comment]
@fregante yes it. We can remove ourself from the request-reviewer dropdown (in the PR) I'll send more screenshots.

**Comment by fregante** [comment]
I think this is too niche and too involved for Refined GitHub at the same time. It would be nice a standalone userscrpt, or maybe you can already do it via gh-cli
