### ISSUE TITLE
Add scrollbar to the left-side section homepage

### ISSUE THREAD

**Issue by Ngoakor12** [refined-github/refined-github#6099]
### Description

Both refined and normal github hide content on the side bar by default. It's a pain because I have to zoom in an out to see more of my recent activity and teams.

A simple scroll css property on the sidebar seems like a good fix:
```css
...{
	overflow:auto
}
```

### Screenshot

Normal(100% zoom) screen
![image](https://user-images.githubusercontent.com/54069197/197379439-27331769-527a-4238-887f-845cb83c7909.png)

Zoomed(50%) out screen
![image](https://user-images.githubusercontent.com/54069197/197379659-5d3af401-c9cb-4d9e-b327-371094daeef9.png)

As you can see, there's other content that gets hidden

### Example URLs

https://github.com/

**Comment by fregante** [comment]
There's already a scrollbar:

/Users/rico/Desktop/197379439-27331769-527a-4238-887f-845cb83c7909.png

**Comment by Ngoakor12** [comment]
I'm talking about the left side section not on the site in general. My bad for not including a more focused screenshot.
![image](https://user-images.githubusercontent.com/54069197/197381093-e2ec578a-f6db-4cff-af34-edc080aa1ce3.png)

**Comment by fregante** [comment]
Wow that's kinda weird. We just need this in `github-bugs/dashboard.css`:

```css
.dashboard-sidebar {
	overflow: auto;
}
```

**Comment by Ngoakor12** [comment]
Can I work on it?

**Comment by fregante** [comment]
Yes please!

**Comment by fregante** [comment]
Actually it should just be added to https://github.com/refined-github/refined-github/blob/ebfb5f62b9f92a677402ffe9d61d9c1eee27824c/source/features/github-bugs.css
