### ISSUE TITLE
Remove duplicate "view organization" button in the organization dashboard

### ISSUE THREAD

**Issue by Ngoakor12** [refined-github/refined-github#6100]
### Description

The "view organization" added by refined-github in the organization dashboard view is no longer needed. 
Because:
- github has added another "view organization" button on the left side of the view.
- the hover effect of the github-refined makes it a bit hard to read the text

Screenshot

**Refined GitHub turned on.**
See right side section("member statuses") for the button added by refined github . See left side section for the button on the normal github
![image](https://user-images.githubusercontent.com/54069197/197380745-159273f4-64f4-48cd-a71b-9224cf264db3.png)

**Refined GitHub turned on turned off**
![image](https://user-images.githubusercontent.com/54069197/197380881-26e06676-7a6c-4fab-8838-97bb21a8602c.png)

### How to replicate the issue + URL

1. Go to https://github.com/orgs/refined-github/dashboard

	You can replace "refined-github" on the above url with an private orgs you're part of. I can't find a public url that works, you need to be part of certain orgs to see that view.

2. See right side section("member statuses") for the button added by refined github . See left side section for the button on the normal github

### Extension version

v.22.10.12

### Browser(s) used

Chrome v.105.0.5195.102 and Firefox v.105.0

**Comment by fregante** [comment]
I'm not sure about what the intention was. The link seems to be added by

https://github.com/refined-github/refined-github/blob/ebfb5f62b9f92a677402ffe9d61d9c1eee27824c/source/features/infinite-scroll.tsx#L39

**Comment by Ngoakor12** [comment]
Would also like to work on this one aswell

**Comment by fregante** [comment]
Great! Find out what it was meant to do in the first place by using the Blame view, maybe it's still needed in some situations.

**Comment by Ngoakor12** [comment]
I had a look, not gonna pretend I understand all of the code but here's what I've seen:

- It was a quick link to the org's repo before github added it's own "view organization" button
- It was added as part of [this PR](https://github.com/refined-github/refined-github/pull/5319) which is responsible for the footer being added to the bottom of the "member statuses" sidebar in desktop screens
- It was only being used at that one place so removing the variable and the one place where it was used should not affect anything imo

Should I go ahead? Might also have to add a some bottom-padding to the "load more" button above it
