### ISSUE TITLE
Make "outdated" comments visible in "files changed" tab

### ISSUE THREAD

**Issue by paulius-valiunas** [refined-github/refined-github#6105]
### Description

Github has the worst PR experience out of every Git service I've tried, which is mostly caused by one huge inconvenience: once you change something in a file, all previous comments on that file become "outdated" and it's impossible to view them in context of the updated file. The typical PR workflow is:
- Reviewer adds comments
- Requester makes changes and replies to those comments saying they fixed them
- Reviewer looks at the changes and resolves comments _if_ they're happy with the changes
In Github, the third step is unnecessarily complex because it doesn't allow you to read old comments in context of updated files. In Gitlab, Bitbucket or Azure Devops, you can just open the latest version of that file and the comment will show up with an "outdated" tag. On Github, you have to open the comment on one screen and the code on another screen, which is super inconvenient.

I suggest displaying "outdated" comments in every version of a file after the comment was written.

Example on this repo:
https://github.com/refined-github/refined-github/pull/6095#discussion_r1001393169
should appear on:
https://github.com/refined-github/refined-github/pull/6095/files#diff-6494bc745a7a5ab6cf6b6070ad49a1c4c92dae2ed8c702534d5f18211956c2b6 (latest version of the file)

### Example URLs

https://github.com/refined-github/refined-github/pull/6095/files

**Comment by paulius-valiunas** [comment]
There's a discussion about it [here](https://github.com/orgs/community/discussions/9956) but Microsoft refuses to acknowledge the issue.

**Comment by fregante** [comment]
This is out of scope for Refined GitHub. "Making them visible" means pulling the API and recreating the whole DOM for the comment. We can't do that

**Comment by paulius-valiunas** [comment]
was worth a try :)
