### ISSUE TITLE
Fork count not visible

### ISSUE THREAD

**Issue by fezjo** [refined-github/refined-github#6107]
### Description

Number on the side of fork button is hidden with Refined Github.
If I understand correctly, this was the intended behavior in the past, then the option `hide-watch-and-fork-count` was added, then the behavior changed so that fork count is hidden when viewport width is less then 1000px. I have 1080p screen, so with width of around 1900px, the count should be visible, but is not.
Additionally, I can't find the `hide-watch-and-fork-count`.

With Refined Github:
![image](https://user-images.githubusercontent.com/26350212/197735113-78f404d1-9ddb-4207-9fb2-1f2fcae1160e.png)
Without Refined Github:
![image](https://user-images.githubusercontent.com/26350212/197735183-9d01a4f4-5292-46ac-a6ad-cb9ca3712be3.png)

Tested on Firefox and Vivaldi.

### How to replicate the issue + URL

Visit https://github.com/refined-github/refined-github with Refined Github enabled.
![image](https://user-images.githubusercontent.com/26350212/197735486-baa94e16-7999-4304-b877-746e493f5185.png)

### Extension version

22.10.12

### Browser(s) used

Firefox 106.0.1 (64-bit)

**Comment by fregante** [comment]
It's a feature. You can search the repo

**Comment by fregante** [comment]
Since #6333 (version 23.2.11) you can disable the feature in the options page, it's called clean-repo-header`
