### ISSUE TITLE
`file-finder-buffer` does not work

### ISSUE THREAD

**Issue by lf-** [refined-github/refined-github#6108]
### Description

When I hit `t` on https://github.com/refined-github/refined-github, then type in "build" very quickly, the keystrokes are dropped. You can see me replicating it in the following gif. I finally type in the keys after waiting for the thing to load.

https://github.com/refined-github/refined-github/blob/main/source/features/file-finder-buffer.tsx

![refined-github file-finder-buffer broken](https://user-images.githubusercontent.com/6652840/197940724-702726a0-54ff-4cc7-aa74-a22bd91e2004.gif)

### How to replicate the issue + URL

Go to https://github.com/refined-github/refined-github

Type `t` then immediately start typing `build`.

The buffering will not work and the keystrokes will be dropped.

### Extension version

22.10.12

### Browser(s) used

Firefox 105.0 on Linux

**Comment by FloEdelmann** [comment]
The feature was dropped in #6296, so I guess we can close this issue now, right?

**Comment by fregante** [comment]
Thanks! I mentioned the issue but forgot to close it
