### ISSUE TITLE
`scheduled-and-manual-workflow-indicators` broken

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6111]
### Description

<img width="321" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/1402241/197970999-2d539463-0913-4fa7-afa3-401bf7bd94ac.png">

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/actions

### Extension version

22.10.12

### Browser(s) used

Chrome, Safari

**Comment by yakov116** [comment]
The entire layout changed its now a list

The selectors are now `.ActionList`
