### ISSUE TITLE
Add a button to clear all Github Action caches

### ISSUE THREAD

**Issue by 0rax** [refined-github/refined-github#6115]
### Description

With the addition of cache management to Github Actions, it became pretty simple to debug cache problems by being able to remove potentially corrupted one. With the use of `restore-keys` it is also sometimes required to clear all caches at once if the issue goes deeper.

Thus it might be interesting to add either a way to remove all caches at once or being able to select and delete specified ones.

### Screenshot

![image](https://user-images.githubusercontent.com/2822534/198272253-e3e03aac-f2af-43d1-a791-6c678f1c50cc.png)

### Example URLs

https://github.com/refined-github/refined-github/actions/caches

**Comment by fregante** [comment]
Unfortunately it's a rather niche and relatively complicated feature. It's probably best to do this via gh-cli or the API
