### ISSUE TITLE
`clean-conversation-sidebar` breaks dropdowns

### ISSUE THREAD

**Issue by FloEdelmann** [refined-github/refined-github#6116]
### Description

Go to any PR or issue you have write access to, try changing the labels. Clicking the header or gear icon doesn't do anything. The same happens for the Milestones, Projects and Development sections. The Assignees and Reviewers sections are unaffected.

Apparently, `clean-conversation-sidebar` removes the dropdown rather than the subsequent element:

![grafik](https://user-images.githubusercontent.com/202916/198331912-c59c75ec-4139-4b8a-a491-eea6c9dc3fb8.png)

![grafik](https://user-images.githubusercontent.com/202916/198331357-d64ea3a5-4200-473a-9e91-ec8b58f42b0c.png)

### How to replicate the issue + URL

* https://togithub.com/vuejs/eslint-plugin-vue/pull/2021 (for me)
* this issue (for you)

### Extension version

22.10.26.814

### Browser(s) used

Firefox 106.0.1

**Comment by fregante** [comment]
Ouch, again. Similar issue a while ago.

**Comment by fregante** [comment]
https://github.com/refined-github/refined-github/pull/6076 might avoid this issue in the future: assert the text content before removing it.
