### ISSUE TITLE
Add one-click PR approval on Conversation tab

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6118]
### Description

Re-proposing:

- https://github.com/refined-github/refined-github/issues/883

We had initially rejected this feature because "you shouldn't approve without looking at the diff" but there are many cases where that is fine:

- you already did and now you're back on the conversation tab
- dependabot PRs

Also related:

- https://github.com/refined-github/refined-github/issues/2702

### Screenshot

I wonder if we can just add it here:

<img width="324" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/198871439-f00a82c3-3ff5-4e4f-9fed-55266e2c702a.png">

### Example URLs

https://github.com/refined-github/sandbox/pull/4

**Comment by yakov116** [comment]
I am scared of random people just clicking the button. Maybe only if a review is requested?

**Comment by fregante** [comment]
I'd probably still ask for confirmation to avoid mistakes

**Comment by fregante** [comment]
> If we can detect it, only show it to maintainers

We do have a "canEditSidebar" that we can use for this purpose. I'm not sure if it necessarily produces a green check, but any moderator has been pre-approved by the repo-owner so they're unlikely to spam.

**Comment by jdeniau** [comment]
It would be great to have this. 

I understand the fact that "you shouldn't approve without looking at the diff", but a lot of time, I already did review the PR files, but comme back to the discussion to read the descriptions, or the discussions again.

We might either check that the `files` page is in history, if possible, or add a warning to tell the user that one should review the PR first ?

**Comment by sedghi** [comment]
This is highly desirable use case for PRs that have gone through many iterations. For instance, I review the code, but then I need to see if it actually works locally for our application. Then I checkout the PR and try it and everything is expected, go back to the PR and want to just approve! or add some comment that ok, you have changed this/that behaviour. But I need to navigate to the `files changed`, and for PRs with lots of files changed you can guess how slow would that page be to load!

**Comment by sedghi** [comment]
> I understand the fact that "you shouldn't approve without looking at the diff", but a lot of time, I already did review the PR files, but comme back to the discussion to read the descriptions, or the discussions again.

This exactly happen to me at least 5 times a day maintaining couple of repos

**Comment by fregante** [comment]
You're free to send a PR to add the feature. It has already been approved.
