### ISSUE TITLE
✨ Image preview on hover

### ISSUE THREAD

**Issue by jd-solanki** [refined-github/refined-github#6121]
### Description

If we have a list of images and want to take a look at it quickly we have to open each of them. We can improve UX if we provide a preview on hover of image

### Screenshot

![image](https://user-images.githubusercontent.com/47495003/199016001-c9aa86f0-96a6-49d1-9e31-ff04fdb3fb12.png)

### Example URLs

https://github.com/themeselection/materio-vuetify-vuejs-admin-template-free/tree/main/typescript-version/src/assets/images/avatars

**Comment by fregante** [comment]
This was already suggested and rejected. I'm sure a userscript or extension already exists
