### ISSUE TITLE
Add support for discarding a file in a pull request.

### ISSUE THREAD

**Issue by atishay** [refined-github/refined-github#6123]
### Description

Some files have trivial changes. There is edit and merge already provided by GitHub. Discard could take the old file and put it back as the edit.

Very useful for lightweight cleanup a PR (especially for files which have whitespace changes).

### Screenshot

<img width="253" alt="Screenshot 2022-10-31 at 1 54 54 PM" src="https://user-images.githubusercontent.com/2279039/199108751-67dfa452-7f85-4023-ab2f-fbdcb84b3fcd.png">

### Example URLs

`https://github.com/<org>/<repo>/pull/<id>/files`

**Comment by yakov116** [comment]
The feature exists already, its called `restore-file`

**Comment by yakov116** [comment]
@atishay do you have the extension installed?

**Comment by fregante** [comment]
The example URLs field specifies a REAL URL is required. 

The feature also already exists  👍

**Comment by atishay** [comment]
Thank you. Sorry was looking in the wrong browser.
