### ISSUE TITLE
Way to go to "Last page" for notifications

### ISSUE THREAD

**Issue by janpio** [refined-github/refined-github#6126]
### Description

When I have a lot of notifications for a repository, I often want to go to the _last_ page of the notification view, "Open all unread" there so I can go through them in the order they came in or were active (instead of starting with the _newest_ ones).

It would be amazing if Refined GitHub could add a `Last page` or `Last` next to "Prev | Next" below the list of notifications.

### Screenshot

<img width="313" alt="image" src="https://user-images.githubusercontent.com/183673/199468258-8a7b27ed-274e-4ec2-b52c-dd166c4ecf5f.png">

### Example URLs

For me e.g. https://github.com/notifications?query=repo%3Aprisma%2Fprisma+is%3Aunread

**Comment by fregante** [comment]
Just tried this for fun:


```js
a = $('[aria-label="Next"]');
s = new URLSearchParams(a.search)
max = looseParseInt($('.js-notifications-list-paginator-counts').lastChild);
lastCursor = Math.floor(max/50)* 50
s.set('after', btoa('cursor:' +lastCursor))
lastBtn = a.cloneNode()
lastBtn.search = s.toString()
lastBtn.textContent = 'Last'
a.after(lastBtn)
```

and the existing

```js
function looseParseInt(text) {
	if (!text) {
		return 0;
	}

	if (typeof text !== 'string') {
		text = text.textContent;
	}

	return Number(text.replace(/\D+/g, ''));
}
```

We could linkify the `201`, with an underline.

**Comment by janpio** [comment]
That would totally work and avoid having to add an additional button that might confuse some people (and their muscle memory of where to click to go to `Next` 👍

**Comment by janpio** [comment]
Oh this works so great for my use case. Thanks @fregante and @yakov116 again!

**Comment by janpio** [comment]
There seems to be a off by one problem going on somehow:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/183673/211084055-49ec60fc-2c61-4007-9813-a7ee653ffebd.png">
<img width="1570" alt="image" src="https://user-images.githubusercontent.com/183673/211084093-3cf2c978-81ab-4ea6-9e00-0362560b4187.png">
The "Prev" button on that page unfortunately also does not work (but that is a GH bug). That the link goes to this page is probably a problem of this feature.

(cc @yakov116)

**Comment by janpio** [comment]
Oh, even with 149 something fishy is going on:
<img width="209" alt="image" src="https://user-images.githubusercontent.com/183673/211084412-97d29ab6-7e29-400e-ac2b-92c7adfae5a0.png">
<img width="194" alt="image" src="https://user-images.githubusercontent.com/183673/211084460-e18892c6-4801-437e-b47c-0368eaebc4ac.png">
Here clicking "Next" brings me to the _actual_ last page then though.

**Comment by fregante** [comment]
It's best to open a new Bug issue 😅

**Comment by janpio** [comment]
https://github.com/refined-github/refined-github/issues/6218
