### ISSUE TITLE
Use native style for  `update-pr-from-base-branch`

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6127]
A couple of years ago we used to show this button in the mergeability box but gave up because the box varied too much and it was difficult to track due to its dynamic nature (frequent updates).

But now we don't have issues with dynamic elements (via `selector-observer`) and I thought of a less error-prone way to integrate it:

- inject a whole information bar just like GitHub does

I think we can do this with relative ease. The only issue is just the amount of JSX to maintain. We don't need 100% of the copy here.

# Native

<img width="771" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/1402241/199475406-e56e24f7-9eb1-4fa2-9957-856af46672b9.png">

# Ours (current)

<img width="777" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/199475444-a753eb39-f6c6-449e-8b83-f1ea2623087c.png">

**Comment by yakov116** [comment]
How do I trigger the native version?

**Comment by fregante** [comment]
It’s a per-repo setting that requires protected branches. https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-suggestions-to-update-pull-request-branches

**Comment by fregante** [comment]
I enabled it on this repo, together with CI requirements (native auto-merge, but `wait-for-checks`)

<img width="919" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/200106586-dfeaa3dc-c1f5-4fc7-bf55-44b89ff52793.png">
