### ISSUE TITLE
Tabs are still 8 space-wide instead of 4

### ISSUE THREAD

**Issue by X1nto** [refined-github/refined-github#6129]
### Description

The extension suggests that it replaces 8 space tabs with 4 space tabs. However, that doesn't seem to be the case:
![image](https://user-images.githubusercontent.com/48173186/199575039-1cf4cf01-6e37-47c3-a046-7d20a6c1855e.png)

### How to replicate the issue + URL

1. Install the extension
2. Open a file on any repo that uses tabs instead of spaces
3. Verify that tabs are still 8 space-wide

Reference material:
https://github.com/X1nto/Vencorded/blob/master/vencorded.cpp
https://github.com/Flo56958/MineTinker/blob/master/src/main/java/de/flo56958/minetinker/MineTinker.java

### Extension version

22.10.26.814

### Browser(s) used

Google Chrome 107.0.5304.88

**Comment by busches** [comment]
What do you have tab size set to on GH? https://github.com/settings/appearance

**Comment by fregante** [comment]
We should update the description. Refined GitHub now only sets the tab size where GitHub forgot to
