### ISSUE TITLE
Support `user#123` references in forks

### ISSUE THREAD

**Issue by lsloan** [refined-github/refined-github#6149]
### Description

References to issues are not linked if they are in another repo.  That applies to repo forks owned by another user or an entirely different repo.

For example, when I open a PR in a repo that addresses an issue in that **_same_** repo, I'll title it something like "#𝒏𝒏𝒏 - fix FUBAR bug".   When Refined GitHub displays that PR later, the "#𝒏𝒏𝒏" will be a link to the issue with that number.

However, I recently discovered that when I open a PR in a repo that addresses an issue in a **_fork_** of that repo, titling it "fork-owner#𝒏𝒏𝒏 - fix TARFU bug" did **_not_** cause Refined GitHub to link it.

Similarly, issue references like "repo-owner/repo-name#𝒏𝒏𝒏" aren't linked, either.

### How to replicate the issue + URL

Example of not working:  Issue (PRs are essentially issues) that Refined GitHub doesn't link the issue reference to a fork repo… https://github.com/lsloan/UDOIT/issues/5

Example of working: Issue that Refined GitHub does link the issue reference within the same repo… https://github.com/lsloan/UDOIT/issues/4

### Extension version

22.11.6

### Browser(s) used

Google Chrome Version 107.0.5304.87 (Official Build) (x86_64)

**Comment by fregante** [comment]
I haven't verified the bug but we're using this library to linkify the issue references, and it supports `user/repo#124`

- https://github.com/sindresorhus/linkify-issues
