### ISSUE TITLE
`release-download-count` missing after 100 results

### ISSUE THREAD

**Issue by andry81** [refined-github/refined-github#6150]
### Description

![Firefox_Screenshot_2022-11-09T17-44-59 229Z](https://user-images.githubusercontent.com/16258197/200900673-3c16c53e-6740-4f62-a9d9-44c44f106294.png)

### How to replicate the issue + URL

https://github.com/veracrypt/VeraCrypt/releases/tag/VeraCrypt_1.25.9

### Extension version

22.11.6

### Browser(s) used

FireFox 106.0.5 64-bit

**Comment by yakov116** [comment]
There is nothing we can do about this. The release has more than `100` assets and GitHub only allows 100 per request.

```gql
{
  repository(owner: "veracrypt", name: "VeraCrypt") {
    _VeraCrypt_1_25_9: release(tagName: "VeraCrypt_1.25.9") {
      releaseAssets(first: 100) {
        nodes {
          name
          downloadCount
        }
        totalCount
      }
    }
  }
}
```

totalCount = 104.

We can only load 100 of them.

**Comment by busches** [comment]
Can't we ask for the next 100, in another call, if we have 100 results back?

**Comment by yakov116** [comment]
Not worth complicating the entire code for the rare occasion.

Would require to check if the count is > 100 and make a new call with `endCursor` and combine the requests.

**Comment by busches** [comment]
Not worth it, is not the same as, nothing we can do about it.

We have this issue to track if it happens enough to reconsider.

**Comment by yakov116** [comment]
> Not worth it, is not the same as, nothing we can do about it.

Correct wrong choice of words 

> We have this issue to track if it happens enough to reconsider.

Very rare for a release to have over 100 assets.

**Comment by fregante** [comment]
What we can do is add an empty placeholder element so that the layout doesn't look broken

**Comment by fregante** [comment]
# 🎉
