### ISSUE TITLE
Repo info inside new Alpha search bar (z-index issue)

### ISSUE THREAD

**Issue by 01101sam** [refined-github/refined-github#6151]
### Description

![image](https://user-images.githubusercontent.com/100821827/201007247-70e4a5a1-b0bd-48fe-8b3b-f6aac2a5c0bf.png)

^ Enabled

![image](https://user-images.githubusercontent.com/100821827/201007323-bf9fa50d-0cce-4fc3-99e2-1432b2192ddc.png)

^ Disabled

### How to replicate the issue + URL

Repo with class `rgh-sticky-sidebar` as shown in screenshot

![image](https://user-images.githubusercontent.com/100821827/201007734-1a285d55-9c15-4791-9b14-090b52d20384.png)

with `rgh-sticky-sidebar`: <https://github.com/morethanwords/tweb>
without `rgh-sticky-sidebar`: <https://github.com/refined-github/refined-github>

### Extension version

22.11.6

### Browser(s) used

Chrome

**Comment by fregante** [comment]
We can probably push their drop-down's z-index higher
