### ISSUE TITLE
`download-folder-button` missing from new file view

### ISSUE THREAD

**Issue by HypedDomi** [refined-github/refined-github#6154]
### Description

When you go to your own Repo and open a Folder, the Download Folder Button doesnt appear. It only appears when you reload the page

Errors:
```
❌ repo-age
	📕 22.11.6 → TypeError: Cannot read properties of undefined (reading 'closest')
    	at init (refined-github.js:8705:66)
    	at async runFeature (refined-github.js:3709:20)
    	at async setupPageLoad (refined-github.js:3715:34)

	🔍 Search issue https://github.com/refined-github/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+Cannot+read+properties+of+undefined+%28reading+%27closest%27%29

	🚨 Report issue https://github.com/refined-github/refined-github/issues/new?labels=bug&template=1_bug_report.yml&title=%60repo-age%60%3A+Cannot+read+properties+of+undefined+%28reading+%27closest%27%29&example_urls=https%3A%2F%2Fgithub.com%2FHypedDomi%2FEnmity-Stuff%2Ftree%2Fmain%2FPluginTemplate&description=%60%60%60%0ATypeError%3A+Cannot+read+properties+of+undefined+%28reading+%27closest%27%29%0A++++at+init+%28chrome-extension%3A%2F%2Fhlepfoohegkhhmjieoechaddaejaokhf%2Frefined-github.js%3A8705%3A66%29%0A++++at+async+runFeature+%28chrome-extension%3A%2F%2Fhlepfoohegkhhmjieoechaddaejaokhf%2Frefined-github.js%3A3709%3A20%29%0A++++at+async+setupPageLoad+%28chrome-extension%3A%2F%2Fhlepfoohegkhhmjieoechaddaejaokhf%2Frefined-github.js%3A3715%3A34%29%0A%60%60%60
```

![issue.gif](https://img.bambus.me/r/8pS2oE.gif)

### How to replicate the issue + URL

Go to your own Repo and open a folder. Click the 3 dots. Only Delete Directory appears

URL: https://github.com/HypedDomi/Enmity-Stuff/tree/main/dist

### Extension version

22.11.6

### Browser(s) used

Brave

**Comment by fregante** [comment]
Either due to this summer AJAX refresh or yesterday's File view updates

**Comment by Ifeo-A** [comment]
The download folder button is still not visible, even after reloading the page. On the latest Chrome extension version 23.2.1

<img width="463" alt="image" src="https://user-images.githubusercontent.com/11969121/216800835-7eac1d62-3a3d-421e-8a42-171428d27428.png">

**Comment by fregante** [comment]
Link to that page please

**Comment by WegnerDan** [comment]
![grafik](https://user-images.githubusercontent.com/6908247/217676612-9c10d00d-39db-4210-97cd-2109472d6bca.png)

Just installed this extension in Firefox and Chrome and it's not working in either. 

These are the folders I was trying to download:

https://github.com/VoronDesign/VoronUsers/tree/master/orphaned_mods/printer_mods/edwardyeeks/Decontaminator_Purge_Bucket_%26_Nozzle_Scrubber

https://github.com/MotorDynamicsLab/LDOVoron2/tree/main/STLs/Purge%20Bucket

**Comment by fregante** [comment]
The feature works on the new Code View. You have to enable it in https://docs.github.com/en/repositories/working-with-files/managing-files/navigating-files-with-the-new-code-view

**Comment by WegnerDan** [comment]
> The feature works on the new Code View. You have to enable it in [docs.github.com/en/repositories/working-with-files/managing-files/navigating-files-with-the-new-code-view](https://docs.github.com/en/repositories/working-with-files/managing-files/navigating-files-with-the-new-code-view)

Ah, I didn't know that. I'm now on the waitlist.

**Comment by fregante** [comment]
I opened a PR to restore the feature on the old view as well

**Comment by dxcvvxd** [comment]
> I opened a PR to restore the feature on the old view as well
and it doesnt work on the newest version (23.2.5, Firefox 109.0.1-1 on Arch Linux)
