### ISSUE TITLE
`restore-file` no longer works

### ISSUE THREAD

**Issue by staabm** [refined-github/refined-github#6155]
### Description

I guess since GitHub shipped a lot of features while GitHub Universe the "restore file" feature from a pull requests file-context menu no longer works.

I get a

> can't access property "elements", form is undefined

error when using 

<img width="1192" alt="grafik" src="https://user-images.githubusercontent.com/120441/201464234-4228db1a-95a5-4710-8f42-33040d167e2e.png">

### How to replicate the issue + URL

https://github.com/FriendsOfREDAXO/rexstan/pull/225

### Extension version

22.11.6

### Browser(s) used

firefox 108 on latest macOS ventura

**Comment by fregante** [comment]
Related:

- https://github.com/refined-github/refined-github/issues/6152

**Comment by fregante** [comment]
This feature fetches the "Edit file" HTML page and then submits its form, making use of the authenticity token that GitHub generates.

I looked into a fix: they replaced the HTML form with raw data meant to be used by React to create a form on the fly. The raw data has all that we need including the token, but ideally we should restore this PR instead, which avoids the awkwardness:

- https://github.com/refined-github/refined-github/pull/4803

The reason why we had to revert it was that the API didn't work on forks. It's been a year now, has it been fixed? @gamemaker1 would you have time to try?

**Comment by gamemaker1** [comment]
Sure, I'll give it a shot!

**Comment by staabm** [comment]
in case its relevant. it seems to work in google chrome as expected but the error i see seems to be a firefox only problem for now

**Comment by staabm** [comment]
thx for working on it. I can confirm this issue is fixed in firefox <3.
