### ISSUE TITLE
Mobile reactions / emoji button in comments

### ISSUE THREAD

**Issue by jtagcat** [refined-github/refined-github#6161]
### Description

There is no way to add reactions on mobile. This has annoyed me constantly for over a year.

### Screenshot

On mobile, there is no way to add (first) reactions on comments without reloading page with desktop view: ![Screenshot_20221114-112240_Firefox Nightly](https://user-images.githubusercontent.com/38327267/201623214-39acfde3-bb55-482e-84d2-f53ea87e0fc0.png)

Where somebody else has already reacted, reactions are possible: ![Screenshot_20221114-112259_Firefox Nightly](https://user-images.githubusercontent.com/38327267/201623208-066b4eaa-7834-4caf-b025-dc8e26ae6aea.png)

### Example URLs

https://github.com/refined-github/refined-github/issues/6152

**Comment by fregante** [comment]
PR welcome to add `unhide-reactions-on-mobile`. The CSS required looks like:

```css
.timeline-comment-actions > .d-none:has(.js-comment-header-reaction-button) {
	display: none !important;
}
```



<img width="561" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/205435600-5d6107fe-f61f-43a6-a939-d008a8fc53aa.png">

**Comment by jtagcat** [comment]
Hm, so it's not just CSS. The element is completely removed:

![image](https://user-images.githubusercontent.com/38327267/205489409-13dbce92-a30e-47e0-89f8-0dc9fb1fb243.png)

**Comment by jtagcat** [comment]
That works, but FIrefox users need to enable `layout.css.has-selector.enabled`. I would prefer this to having a script running on the page at all times.

I added a `h4 { color red; }` as an initial test. With `isIssueOrPRList`, it should not affect the login page..?
![image](https://user-images.githubusercontent.com/38327267/205489683-760c0ccd-8903-456a-ba62-5ab7e926fc7e.png)


Here's the demo img, so I can get an URL (undocumented in contributing.md): 
![demo](https://user-images.githubusercontent.com/38327267/205493629-14563105-eaa1-4885-9f07-8b3ee9214c86.png)
