### ISSUE TITLE
`profile-gists-link` appears in status selection on profile

### ISSUE THREAD

**Issue by vintagesucks** [refined-github/refined-github#6162]
### Description

https://user-images.githubusercontent.com/13335308/202051672-29d1865c-3245-460f-88be-3da6526b3db1.mp4

### How to replicate the issue + URL

https://github.com/vintagesucks

1. Navigate to your own profile
2. Click on your status
3. Open the emoji selection
4. `profile-gists-link` is a tab in this selection

### Extension version

22.11.6

### Browser(s) used

Firefox 108.0b1 (64-Bit)

**Comment by fregante** [comment]
Does this classify as an Easter egg?
