### ISSUE TITLE
`edit-readme` -> add drop down selection like other edit button

### ISSUE THREAD

**Issue by muescha** [refined-github/refined-github#6163]
### Description

GitHub has the github.dev editor. 

if i look at a file i see a dropdown selection

this dropdown is missing at the `rgh-edit-readme` button

about github dev editor see also:
https://docs.github.com/en/codespaces/the-githubdev-web-based-editor

### Screenshot

go to a file and check out the drop down at the edit button:

https://github.com/refined-github/refined-github/blob/main/readme.md

![example](https://docs.github.com/assets/cb-118903/images/help/repository/edit-file-edit-dropdown.png)

### Example URLs

https://github.com/refined-github/refined-github/

https://github.com/refined-github/refined-github/blob/main/readme.md

**Comment by fregante** [comment]
Closing because:

- the two options are rather niche, especially compared to the amount of markup that this would need
- you can already do exactly this by pressing the `.` key on the repo root, it will open the readme
