### ISSUE TITLE
Option to share settings cross device

### ISSUE THREAD

**Issue by tommyliang-dev** [refined-github/refined-github#6172]
Is there a way to share my settings on device A to device B? 

I use GitHub on multiple devices (two laptops and a desktop) and was wondering if there's an easy way to persist the settings across all of them or generate a json file that I can paste in

**Comment by busches** [comment]
Chrome will sync your extension settings if enabled.

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/3981
