### ISSUE TITLE
Option to replace branch with tag for archival of out of support code

### ISSUE THREAD

**Issue by ssbarnea** [refined-github/refined-github#6173]
### Description

A very common practice is to replace stable branches with archived tags when the project no longer accepts any changes to these. This declutters the repository and browsing git branches for github and also for user git clients.

Example: replace `stable/2.x` branch with `archived/2.x` tag.

This feature is best implemented into `/branches` where there is already an option to rename a branch, we only need one to replace branch with tag.

### Example URLs

N/A

**Comment by fregante** [comment]
While it makes sense at first, it feels overly specific for Refined GitHub. I have never personally seen this exact workflow; generally tags/version are created  "as you go" and then the branch can be deleted at anytime.
