### ISSUE TITLE
Home and End sometimes do not work to scroll to the top and end of the page

### ISSUE THREAD

**Issue by txtsd** [refined-github/refined-github#6174]
### Description

Sometimes, pressing the Home and End keys do not work as intended to scroll to the top and the bottom of the page. Although Ctrl+Home and Ctrl+End do work when this happens.

Refreshing the page seems to fix the issue.

### How to replicate the issue + URL

I have not been able to reproduce it consistently.

There is no specific place where it happens. The page just has to be scrollable.

### Extension version

22.11.6

### Browser(s) used

Firefox 106.x-107.x

**Comment by fregante** [comment]
This isn't something related to Refined GitHub. Also a demo or screenshot of what you're experiencing is always useful, as suggested by the issue template.

**Comment by txtsd** [comment]
> This isn't something related to Refined GitHub. Also a demo or screenshot of what you're experiencing is always useful, as suggested by the issue template. 

It never happened before I installed Refined GitHub.

And a video of it happening will require me to be recording all the time since I can't know when it's going to happen, and can't reliably reproduce it.

**Comment by fregante** [comment]
If pressing a key doesn't work, you can start recording on that moment, not _all the time._ Mostly I'm interested to see how the page is scrollable with the mouse wheel when the home key doesn't work. 

In any case, we don't listen to that key specifically; if it works with ctrl, there's not even the chance we're involuntarily blocking the key.

At most, RG is causing additional scroll somehow, but without a demo it's impossible to determine.

**Comment by txtsd** [comment]
Thanks for the info. I'll record it the next time it happens.
