### ISSUE TITLE
Quick way to find files with comments in PR.

### ISSUE THREAD

**Issue by CraigSiemens** [refined-github/refined-github#6183]
### Description

No idea if it's possible, but it'd be nice if there was a way to simplify finding files that have a comment on them when the files are collapsed.

Some options I can think of. Have a button somewhere to expand files in a PR that have comments on them. Or add an indicator on a collaped file that it contains a comment.

My common case is I'm working through a PR leaving comments and collapsing comments as I go. Sometimes I'l be pulled away or just forget what comments I'd had left. Currently ti find the comments I need to expand all files and scroll through until I find them.

### Screenshot

For an indicator on a collapsed file, it could be an icon added on the right next to the "Viewed" button.

<img width="1280" alt="Padded Screenshot 2022-12-06 at 1 12 43 PM" src="https://user-images.githubusercontent.com/680442/206013194-7c520e13-5c41-4251-873b-19f5bd4e2809.png">

For adding a button to expand them, I'm not sure of a good place that could so since there aren't really any other buttons that control collapsing or expanding multiple files.

### Example URLs

https://github.com/refined-github/refined-github/pull/6182/files

Any PR that has unresolved comments on a file.

**Comment by fregante** [comment]
This already exists. No need to scroll the file list, just open the dropdown:


<img width="898" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/208230673-80341690-3155-4f4f-891d-3f8d8ad7fada.png">

**Comment by CraigSiemens** [comment]
That works when viewing comments from others, but while your in the process of reviewing a PR, your new comments down appear there until submitting the review.

**Comment by fregante** [comment]
I see, that's two different things unfortunately since GitHub treats drafts differently. 

If you're looking for your own reviews, then the icon shouldn't *also* indicate others' reviews. 

I think it's not a terribly difficult feature, it would be something like:

```js
// selector not real 
observe('.file:has(.draft-review) .header', header => {
  header.append(<SomeIcon/>)
})
```

**Comment by fregante** [comment]
Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it. If it was accepted before, I may still accept a PR in the next 6 months.
