### ISSUE TITLE
Freely pick date/time when setting a profile status clear date

### ISSUE THREAD

**Issue by davidstosik** [refined-github/refined-github#6184]
### Description

GitHub only provides a few options to automatically clear one’s status in the future:
- never
- in 30 minutes
- in 1 hour
- in 4 hours
- today
- this week

Sometimes, these values are not enough. Say for example I go on a 3-day weekend, and want to reduce review requests until my return on Tuesday morning, then none of the options offered would allow that.
Other examples could be:
- until I return back from lunch
- when I get back from a 2-week vacation

Being able to simply pick a date and date would provide all the flexibility anyone could need.

I have already implemented this feature as a bookmarklet, and I imagine it wouldn't be too difficult to port to Refined GitHub.
Please check it out here: [⏲️ Better GitHub status time picker](https://davidstosik.github.io/better_gh_status_clear/).

### Screenshot

Before | After
---|---
![before](https://davidstosik.github.io/better_gh_status_clear/static/gh-default-status-clear.png) | ![after](https://davidstosik.github.io/better_gh_status_clear/static/better-gh-status-clear.png)

### Example URLs

The feature would appear on any page, after opening the "Set status" modal.
Examples of pages:
- https://github.com/
- https://github.com/davidstosik

**Comment by fregante** [comment]
Thanks for the detailed request, but this is a bit much for Refined GitHub for a niche feature.
