### ISSUE TITLE
Change notification overview behavior

### ISSUE THREAD

**Issue by janpio** [refined-github/refined-github#6186]
### Description

I know this is a _long_ shot, but I thought I just ask anyway.

The screenshot below shows what my notifications view generally looks like every morning. By default GitHub shows a dozen of the issues for my most popular repositories (great!), and then for all the other ones where I just have a handful of issues each, it makes the decision to only show 1 or 2. To see all the issues, I have to click "view all notifications" - often to only see 1 more issue I do not really care about and you just have clicked "done".

I would rather see less repos in the initial view overall, but _all_ their issues so I can work through them from the notification page.

Is that possible somehow?

### Screenshot

<img width="1574" alt="image" src="https://user-images.githubusercontent.com/183673/206404923-d84fae04-3baf-4d64-a555-e103895fdae6.png">

### Example URLs

https://github.com/notifications?query=is%3Aunread

**Comment by fregante** [comment]
Yeah this sounds annoying, but I think that to do this we can either:

- fetch the data from each group from the API
- or fetch each "View all X notification" link separately

The first one requires building the DOM of the new notifications from scratch and that's something we want to absolutely avoid (the DOM is complex and has a lot of actions).

The second one requires one `fetch` per repo + it returns a slightly different DOM (we can likely get away with 2 DOM manipulations):

## Expected

<img width="591" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/208904978-2f84a3f4-59a1-46ad-8055-dd1e025f4496.png">

## Actual

<img width="561" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/1402241/208904964-7af5dbcc-a85b-48b8-9527-bd1e22d3647a.png">

---

Do you see lighter-weight alternatives?

**Comment by janpio** [comment]
Not really to be honest. 

I was hoping someone would pop up and say "Oh, we can just manipulate the request before it foes out" but that does not seem the case - and post-loading all this and crafting the HTML indeed seems weird.

The second one does sound kinda viable, but putting it back together to one view for multiple repositories is probably a similar frickle thing as option 1.

Shame.
