### ISSUE TITLE
`clean-dashboard` is a little broken

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6188]
### Description

<img width="957" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/206649882-16d57586-6c7f-4eb7-aa0a-8b7240c38a68.png">

### How to replicate the issue + URL

https://github.com/

### Extension version

22.11.21

### Browser(s) used

Safari

**Comment by cooljeanius** [comment]
I only just started using this and was wondering about the changes to the news feed; how is it *supposed* to look? i.e., which changes made to the news feed by this extension are intentional, vs. which are examples of this bug?

**Comment by fregante** [comment]
> how is it _supposed_ to look?

See https://github.com/refined-github/refined-github/pull/6136
