### ISSUE TITLE
Add quota details to codespaces page

### ISSUE THREAD

**Issue by Mosaab-Emam** [refined-github/refined-github#6189]
### Description

Shows quota information (consumption / remaining) for github codespaces on https://github.com/codespaces instead of it being buried in settings.

## Why?

It's not intuitive where this information can be accessed, the user might spend some time looking for a link in the codespaces page or even digging it up from settings. The user might need to eventually google it or check out the docs.

It does not need to be implemented exactly as in the screenshot, it can be a dropdown link, sidebar link, or button.

### Screenshot

![Screenshot from 2022-12-10 19-06-10](https://user-images.githubusercontent.com/26435307/206866950-9fc1b8e9-56b6-41bc-8126-461034f8507b.png)

### Example URLs

https://github.com/codespaces

**Comment by fregante** [comment]
It makes sense, but it's not worth the trouble in Refined GitHub. I suggest requesting it to GitHub themselves

**Comment by Mosaab-Emam** [comment]
If it's a time issue, can I work on it myself and open a PR?

**Comment by fregante** [comment]
> If it's a time issue

It's also a code/complexity issue. We don't want to add any more features that aren't _very simple_ and desirable by most people. GitHub keeps making large changes that break a lot of our extensions at once. 

Adding a new feature means maintaining it "forever", so it's not as easy as pushing some code and calling it a day unfortunately.

**Comment by Mosaab-Emam** [comment]
> > If it's a time issue
> 
> It's also a code/complexity issue. We don't want to add any more features that aren't _very simple_ and desirable by most people. GitHub keeps making large changes that break a lot of our extensions at once. 
> 
> Adding a new feature means maintaining it "forever", so it's not as easy as pushing some code and calling it a day unfortunately.

I see.

Not to bug you with this, but I can see a fair middle ground here.

A link on the sidebar just below All & Templates, which will redirect to billing page already scrolled down to codespaces section.

That's relatively low risk, it will not change behavior or layout, and a link is simple enough, yet useful in this case.

If this passes through your filters, I will be happy to implement it.
