### ISSUE TITLE
Show readme above code (special case)

### ISSUE THREAD

**Issue by Mosaab-Emam** [refined-github/refined-github#6190]
### Why

I often visit the [trending](https://github.com/trending) page to see what's hot right now in open source. Most of the time I'm clicking on projects I've never seen before, so the first thing I want to do is reading the README.

Some repos just have a root full of files and it's a bit of a scroll to reach the readme section.

My suggestion is that the readme and code sections are swapped, so the first thing on the repo page will be the readme, then scroll to see the code.

Of course, this is not a sane default for everyone, so I also suggest that this applies when the user is coming from [trending](https://github.com/trending) or [explore](https://github.com/explore) pages.

### Variations

Does not need to be exactly like in the screenshot / described, any of these implementations will be helpful:

1. A button to quickly swap readme and code sections.
2. Applies to all repos but the user can opt in / out as preferred.

### Screenshot

![Screenshot from 2022-12-10 19-29-03](https://user-images.githubusercontent.com/26435307/206867751-d6928cc7-def1-4f57-9683-6c3f24fb2e54.png)
![Screenshot from 2022-12-10 19-29-18](https://user-images.githubusercontent.com/26435307/206867752-24364719-07b1-4b6f-ac03-a878a4b04489.png)

### Example URLs

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
See `toggle-files-button`, it already allows you to collapse the file list and essentially achieve what you're suggesting:



> * A button to quickly swap readme and code sections.


And this one also sort of applies because the feature remembers its last state

> 2\. Applies to all repos but the user can opt in / out as preferred.


But keep in mind:

- https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options

**Comment by Mosaab-Emam** [comment]
Thanks @fregante, didn't realize.
