### ISSUE TITLE
Hotfixes don’t work?

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6195]
### Description

I disabled `clean-dashboard` but even if I see the notice in the settings page, I still see the feature being run in the console on the dashboard. 

Also some people mentioned that they didn’t see the hotfix the last time we had an urgent issue. 

### How to replicate the issue + URL

1. On 22.11.21 (not the dev install), open https://GitHub.com 
2. notice #6188 even if we have a hotfix

### Extension version

22.11.21

### Browser(s) used

Safari

**Comment by fregante** [comment]
I think this was due to https://github.com/refined-github/refined-github/pull/6595#discussion_r1181268745

**Comment by fregante** [comment]
@piotrekkr mentioned that the hotfix isn't working: https://github.com/refined-github/refined-github/issues/6963#issuecomment-1740671116

Can you tell me what browser you're using? Please visit one of your PRs and take a screenshot of the affected part. No need to clear the cache anymore

**Comment by piotrekkr** [comment]
@fregante It looks like this even after clearing cache twice. I think when it worked there were no radio buttons and just standard buttons to comment, approve and request changes.

![image](https://github.com/refined-github/refined-github/assets/503782/fdbdfc6d-2c72-4d59-951e-65a691b994b0)

I'm using Firefox 116.0.2 (64-bit) on Kubuntu Linux.

**Comment by piotrekkr** [comment]
@fregante I did not know there was a hotfix and I did not install anything manually. I thought the fix will be installed automatically when firefox updates extension. Should I somehow manually install this hotfix? Sorry for not understanding the process. Thanks

**Comment by busches** [comment]
@piotrekkr the hot fix was to disable the feature, not fix it. There is an open PR working on the fix now.

**Comment by fregante** [comment]
After you clear the cache, you have to wait for it to load, that's why I said you don't need to clear it anymore.

**Comment by fregante** [comment]
In the extension's options, there should be some features that are forcibly disable, mentioning the reason why they were disabled. You should see at least 3 at the top of the list, can you take a screenshot of those? Do you see `one-click-review-submission` there?

**Comment by fregante** [comment]
The hotfix is working correctly, judging by that screenshot 👍
