### ISSUE TITLE
Remember `hide whitespace` as in the native Github

### ISSUE THREAD

**Issue by Hiroshiba** [refined-github/refined-github#6200]
### Description

Native Github remembers `hide whitespace`.
https://github.blog/changelog/2021-10-14-hiding-whitespace-is-now-remembered-for-each-pull-request/

On the other hand, `refined-github` does not yet provide a way to remember.
This issue is a suggestion to adapt the feature to native Github.

(I personally feel `hide whitespace` is so useful that I want to turn it on every time...!)

ref:

- https://github.com/refined-github/refined-github/issues/2503
- https://github.com/refined-github/refined-github/issues/3655
- https://github.com/refined-github/refined-github/issues/4812

### Example URLs

https://github.com/refined-github/refined-github/pull/6251/files

**Comment by fregante** [comment]
I'm sure we had an issue about this open but I can't find it 😳
