### ISSUE TITLE
Add bors button

### ISSUE THREAD

**Issue by aviramha** [refined-github/refined-github#6201]
### Description

Add a button next to merge/squash called "Bors" that will comment `bors r+` on the thread to activate bors merging.

### Screenshot

![image](https://user-images.githubusercontent.com/41201924/207592738-d228e7b3-af82-46a3-8620-1cef94b66f47.png)
(Ugly example)

### Example URLs

https://github.com/metalbear-co/mirrord/pull/844

**Comment by fregante** [comment]
We don't add links to external tools unless they're generally useful. I never heard of bots
