### ISSUE TITLE
Show requested reviewer avatars a la bitbucket

### ISSUE THREAD

**Issue by ArchdukeTim** [refined-github/refined-github#6202]
### Description

When looking at a list of PRs, especially in a private org / repo, it is helpful from a project management standpoint to be able to see who is being waited on for PR reviews. In vanilla github, assignee avatars will show up on the list of PRs, but this doesn't correlate with requested reviewers.  

### Example URLs

https://github.com/refined-github/refined-github/pulls

**Comment by fregante** [comment]
Unfortunately GitHub already uses avatars to indicate who's assigned so it would be confusing. Also the PR list is already busy so we're generally not adding further information

**Comment by fregante** [comment]
There's so much information that _could_ be added so we're basically rejecting all requests to add more. Closing.

You can likely achieve this via Projects because it allows creating custom sorting/grouping/views

https://github.com/features/issues
