### ISSUE TITLE
When an action has spawned from a PR, provide a link back to the PR

### ISSUE THREAD

**Issue by culshaw** [refined-github/refined-github#6206]
### Description

On a github PR if you follow the pathway below:

<img width="797" alt="Screenshot 2022-12-21 at 10 22 13" src="https://user-images.githubusercontent.com/673948/208882545-0ce06f90-0d70-48ea-89fd-a532ba553262.png">

You end up on a screen with no breadcrumb back to the original PR.

Neither here:
<img width="1168" alt="Screenshot 2022-12-21 at 10 22 39" src="https://user-images.githubusercontent.com/673948/208882799-4dd1e28c-77f3-41b5-a7b1-d8f680bdeb3a.png">

Or here:
<img width="1173" alt="Screenshot 2022-12-21 at 10 24 32" src="https://user-images.githubusercontent.com/673948/208883160-2369e803-ee6c-47d2-8693-9513de49d6cf.png">

Only by clicking summary and then this tiny link can you get back to the original PR you've navigated from.
<img width="863" alt="Screenshot 2022-12-21 at 10 29 47" src="https://user-images.githubusercontent.com/673948/208883826-33780291-ddc7-40ce-9007-5c38a23d14e9.png">

What we want, is simply a link at the top of the page that links back to a PR, if it exists. e.g.

<img width="568" alt="Screenshot 2022-12-21 at 10 32 54" src="https://user-images.githubusercontent.com/673948/208884340-a56171ca-d6b9-4cd9-ac8d-fc1ee2b23fff.png">

### Screenshot

(Attached with context in description)

### Example URLs

https://github.com/refined-github/refined-github/actions/runs/3732055304/jobs/6331000824

**Comment by 134130** [comment]
When going to Workflow Job from PR with details button,
<img width="857" alt="image" src="https://github.com/refined-github/refined-github/assets/50487467/205db8ab-95e9-4932-8f86-60bb7d1f7456">

The link back button to assigned Pull Request is visible.
<img width="298" alt="image" src="https://github.com/refined-github/refined-github/assets/50487467/ebf7e566-a55d-4f0d-a236-9169637beaaa">

And the URL looks like this.
`/134130/134130/actions/runs/5103877883/jobs/9174418447?pr=1`

I think the best UI for this is next
<img width="328" alt="image" src="https://github.com/refined-github/refined-github/assets/50487467/aff2c6ac-372d-4358-8997-c69a081f367b">
