### ISSUE TITLE
Allow indenting a task `- [ ]` with the tab key

### ISSUE THREAD

**Issue by unvalley** [refined-github/refined-github#6207]
### Description

When I use a tasklist on GitHub, I often make a single task nested. I'd like to nest a task with pressing the tab key. GitHub doesn't allow that currently. 

For example: 
```
- [ ] task1
	- [ ] task2 
- [ ] ${Here, I hope indent the `- [ ]` with the tab key, but this is not implemented}
- ${not here} [ ] 
```

The [GitHub-indent-comments userscript](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-indent-comments) doesn't fit this requirement.

### Screenshot

https://user-images.githubusercontent.com/38400669/208927043-0fc46d9d-22b0-409c-811f-60b44fa20f45.mp4

### Example URLs

https://github.com/refined-github/refined-github/issues

If this is duplicated, please close this.

**Comment by fregante** [comment]
Refined GitHub already supports tabbing: either select the line or move the cursor to the beginning of the line, then press tab

**Comment by unvalley** [comment]
@fregante 

> either select the line or move the cursor to the beginning of the line, then press tab

Yes, that's true. but I kinda frustrated to move the cursor to the beginning or selecting the line to indent a task. 
When creating many tasks, I'd like to indent more smoothly without any actions.

**Comment by fregante** [comment]
That specific behavior is tracked and described here:

- https://github.com/fregante/indent-textarea/issues/3
