### ISSUE TITLE
Go straight to 2FA auth using authenticatior instead of Github mobile authentication

### ISSUE THREAD

**Issue by alber70g** [refined-github/refined-github#6208]
### Description

Github is recently pushing their app by adding the 2FA auth option to more secure areas of the app. E.g. when creating a new token, you are faced with a 2FA challenge.

I'd like it to automatically go to the Authenticator variant of the 2FA challenge instead of Mobile Phone.

### Example URLs

https://github.com/settings/tokens/new

**Comment by fregante** [comment]
This is not something Refined GitHub should enforce. I suggest creating a userscript, it's probably 1 line of code + headers

**Comment by alber70g** [comment]
Well, there seems to be an option to use "this method" as default

![image](https://user-images.githubusercontent.com/516972/209320820-58d37e49-789a-476e-aa87-c594bffd73d5.png)

**Comment by fregante** [comment]
You can also change it at any time in the user settings:

- https://github.com/settings/security

<img width="777" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/235321075-4645ae94-1846-4970-8fd5-d3f528f8163c.png">
