### ISSUE TITLE
`hide-newsfeed-noise` breaking release notifications

### ISSUE THREAD

**Issue by winterqt** [refined-github/refined-github#6214]
### Description

With `hide-newsfeed-noise` enabled, cards on the dashboard like the below one don't expand when the expand button is pressed.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/78392041/209758955-aff632dc-38e0-41b3-8c9f-c0d55535f44b.png">
<img width="692" alt="image" src="https://user-images.githubusercontent.com/78392041/209758979-bf060534-402c-46c2-a5af-17f6a0a0544b.png">

### How to replicate the issue + URL

Go to the dashboard, find a card that says "<user> created X releases", and try to expand it.

### Extension version

22.11.21

### Browser(s) used

Safari 16.2

**Comment by fregante** [comment]
That's been fixed in the next release, but it's not available in Safari yet

**Comment by winterqt** [comment]
Thank you as always, and apologies for not looking at recent commits! (I did search for issues mentioning this beforehand, though.)
