### ISSUE TITLE
Add a preference for filtering repositories by "last updated"

### ISSUE THREAD

**Issue by RheingoldRiver** [refined-github/refined-github#6215]
### Description

Refined Github seems to auto-add a filter of "sorting repos by last updated" when you view repos. The problem is, this hides all of my forks, and most of the repos I contribute to are forks of my OSS projects, and personally I often try to navigate back to the main repos via my forks of them, so it's pretty annoying to have to close out of that filter. So, I'd like to disable that filter.

I've read through the settings list for this addon several times and I'm pretty sure there's no preference for this particular thing but correct me if I'm wrong.

*Ideally* I'd love to have two different preferences: (1) Disable on *my profile* (when logged in) (2) Disable everywhere else; I don't know if this is possible though. If not, I would be happy to have only "disable everywhere."

Thank you!!

### Screenshot

Click here: 
![image](https://user-images.githubusercontent.com/18037011/210134767-c4e8e125-a9b3-410f-a713-5fc93d42c8f3.png)

I don't want this filter:

![image](https://user-images.githubusercontent.com/18037011/210134778-5c8bdd3b-43aa-460b-a8ac-b7a621a583d6.png)

### Example URLs

https://github.com/RheingoldRiver

**Comment by fregante** [comment]
Can you use the "Find feature" button in the options page? It's possible that you can already disable just that. I don't remember and I'm not at the computer

**Comment by RheingoldRiver** [comment]
This is the list of options with "filter," but I don't think any of them is about this particular issue:

![image](https://user-images.githubusercontent.com/18037011/210137143-f177ddfb-7c3a-4701-a768-f68dd40ba7b8.png)

I thought maybe the middle one that I have disabled might be, but looking at the screenshot it appears to be about something different:

![image](https://user-images.githubusercontent.com/18037011/210137155-448924f7-8880-4f17-9ffd-c5c7d3dff9a5.png)

**Comment by fregante** [comment]
Not the search, I meant this button

<img width="525" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/210150720-f430406e-cf8b-4d69-a6ad-eb90cac48bc5.png">

**Comment by fregante** [comment]
The feature is called `set-default-repositories-type-to-sources`

**Comment by RheingoldRiver** [comment]
oh wow, thank you so much! I was so focused on the "filter" aspect that I missed it. Would you mind if I sent a PR modifying the description of that setting to include the word "filter" in case other people think the same as I do?
