### ISSUE TITLE
`sort-conversations-by-update-time` doesn't work on Enterprise Github

### ISSUE THREAD

**Issue by KSH-code** [refined-github/refined-github#6216]
### Description

I have disabled `sort-conversations-by-update-time`.
but it does not work on Github Enterprise.

but normal github does work

## Normal
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/29705162/210310404-5ecad385-4337-403a-bb42-59aaa48e3bbd.png">

## Enterprise
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/29705162/210310438-d11b8faf-2648-4187-98b5-d4d7fa92eb78.png">

### Extension version

22.12.15

### Browser(s) used

Chrome 108.0.5359.124

**Comment by KSH-code** [comment]
I can fix it.

**Comment by fregante** [comment]
Refined GitHub has per-host options. You have to open the options and disable the feature on your GitHub enterprise domain too

**Comment by KSH-code** [comment]
Oh, I got it.
Thanks!
