### ISSUE TITLE
Where is the "Everything commented by you"?

### ISSUE THREAD

**Issue by GF-Huang** [refined-github/refined-github#6217]
![image](https://user-images.githubusercontent.com/4510984/211182719-41d993b7-baab-4fe4-960b-a3cf98b65e83.png)

**Comment by fregante** [comment]
It was replaced by "involved in"

**Comment by GF-Huang** [comment]
> It was replaced by "involved in"

Ha, thank you. For non-native English speakers, this is a new word, and at first glance I don't know what it is.

**Comment by fregante** [comment]
No worries. "Involved in" means that it's not where you left a comment, but also mentions, assignments, etc
