### ISSUE TITLE
`last-notification-page-button`: Link to last page is sometimes broken or wrong

### ISSUE THREAD

**Issue by janpio** [refined-github/refined-github#6218]
### Description

There seems to be a off by one problem going on somehow when the # of issues is 150 (and hits exactly when pagination would happen):
<img width="189" alt="image" src="https://user-images.githubusercontent.com/183673/211084055-49ec60fc-2c61-4007-9813-a7ee653ffebd.png">
=>
<img width="1570" alt="image" src="https://user-images.githubusercontent.com/183673/211084093-3cf2c978-81ab-4ea6-9e00-0362560b4187.png">
The "Prev" button on that page unfortunately also does not work (but that is a GH bug).

Oh, even with 149 something fishy is going on:
<img width="209" alt="image" src="https://user-images.githubusercontent.com/183673/211084412-97d29ab6-7e29-400e-ac2b-92c7adfae5a0.png">
=>
<img width="194" alt="image" src="https://user-images.githubusercontent.com/183673/211084460-e18892c6-4801-437e-b47c-0368eaebc4ac.png">
Here clicking "Next" brings me to the _actual_ last page then though.

(cc @yakov116)

### How to replicate the issue + URL

https://github.com/notifications?query=repo%3Aprisma%2Fprisma+is%3Aunread

### Extension version

22.12.15

### Browser(s) used

Chrome

**Comment by yakov116** [comment]
I have no way to debug this as I don't have a way to filter exactly 150 pages.

I just tried by me and everything is working, can you check now if you still have an issue. Maybe it was a GitHub bug.

**Comment by janpio** [comment]
This is def still happening in 22.12.15, I just got it on a result page with 97 results - after clicking the `97` it showed results `51-75` instead of the desired `76-97`.

Any way I can help debugging this? I often have this many issue notifications.

**Comment by yakov116** [comment]
An6 console errors? There must be something you are doing differently or this would happen every time

**Comment by janpio** [comment]
None that I noticed, and I just go to the notifications page and then click on one of the repos on the left or use "View all ..- notifications" in the main list that shows the truncated list. Will let it collect a few more issue and observe if anything happens in console or otherwise.

**Comment by janpio** [comment]
So right now I have it on https://github.com/notifications?query=repo%3Aprisma%2Fprisma+is%3Aunread with 47 issues:
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/183673/212959181-36d89d8d-07f1-4c0c-ae64-5d271eb9bc37.png">

Clicking on the # sends me to https://github.com/notifications?after=Y3Vyc29yOjA%3D&query=repo%3Aprisma%2Fprisma+is%3Aunread but the issues shown are the same:
<img width="1568" alt="image" src="https://user-images.githubusercontent.com/183673/212959343-40ead78c-d85c-42a9-976a-2372469a0b8f.png">
The correct URL I get when clicking the "Next" button is:
https://github.com/notifications?after=Y3Vyc29yOjI1&query=repo%3Aprisma%2Fprisma+is%3Aunread

**Comment by janpio** [comment]
Ok, bit the bullet and looked at the code - and I think I understand it!

https://github.com/refined-github/refined-github/blob/951f267db9441ae084ee660725d878bc1717bf5d/source/features/last-notification-page-button.tsx#L14
Is it possible that this should be using `25` considering that the notifications have 25 items per page instead of 50? That would explain that every 25 issues in the notifications it links to the wrong number - and then it works again for the next 25.

**Comment by fregante** [comment]
That's probably it! PR welcome if you can test it

**Comment by janpio** [comment]
I can try.
