### ISSUE TITLE
Display duration for in-progress workflow runs

### ISSUE THREAD

**Issue by 66Leo66** [refined-github/refined-github#6219]
### Description

Currently, actions are displayed as "Queued" or "In progress" if they're not yet completed.

It would be helpful to display a live duration like "Queueing for 10s" or "Running for 1m 5s". Or, the two fields (time started & duration) could be combined into one because they're the same for incomplete runs.

In this way, it would be easier to diagnose if a run is abnormal because of taking too much time.

The timer could be updated on client-side after fetching time info of a run.

### Screenshot

**Current**
![image](https://user-images.githubusercontent.com/33322229/211535510-3a352269-47df-4927-a0f5-f07d222ce7de.png)
![image](https://user-images.githubusercontent.com/33322229/211535518-022aadc9-1ee6-4ac9-b29e-e9aa560e1070.png)
![image](https://user-images.githubusercontent.com/33322229/211534887-2bc434e7-c307-48b9-a5c4-b99ed8826542.png)

**Improvement**
Type 1:
![image](https://user-images.githubusercontent.com/33322229/211537246-b7b2e0b5-d08d-4dcc-8680-5724b97cda76.png)

Type 2:
![image](https://user-images.githubusercontent.com/33322229/211537540-634673e8-e01d-42c9-b118-312cb17cd7dd.png)

### Example URLs

Action Pages, such as:
https://github.com/refined-github/refined-github/actions

**Comment by fregante** [comment]
Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it.
