### ISSUE TITLE
Option to disable "GitHub code search"

### ISSUE THREAD

**Issue by segeljakt** [refined-github/refined-github#6223]
### Description

Is it possible to add an option that disables GitHub code search? I like the feature, but oftentimes I just want to search using the regular Command-F on Mac.

### Screenshot

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/15143039/212300765-33241fe9-9376-439a-90be-9f5e32e358cc.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/15143039/212300845-6f681260-aa2e-42f5-88bd-fea94b815f7f.png">

### Example URLs

https://github.com/refined-github/refined-github/blob/main/webpack.config.ts

**Comment by j-f1** [comment]
Heads up that the new code viewer uses virtualization, so the browser find-in-page tool won’t work beyond about 200 lines.

**Comment by fregante** [comment]
I think for that reason alone we can't implement this
