### ISSUE TITLE
Add remaining changed lines in pull request files changed tab

### ISSUE THREAD

**Issue by Chicken** [refined-github/refined-github#6226]
### Description

Secondary counter under changed lines which shows the number of changed lines in files not marked as viewed. When a file is marked as viewed the counter should decrease.

### Screenshot

![mockup](https://user-images.githubusercontent.com/45627874/212474452-4584dfa1-5362-4822-b949-e002d19a66ac.png)

### Example URLs

https://github.com/Cowoding-Jams/Jambo/pull/53/files

**Comment by fregante** [comment]
Not a bad idea, but on long PRs (where files are loaded progressively) this is impractical to implement with little benefit. After adding hundreds of features, Refined GitHub is limiting new features to things that are easy to implement and maintain.
