### ISSUE TITLE
"Sticky" Pop-Ups

### ISSUE THREAD

**Issue by Sineos** [refined-github/refined-github#6227]
Since a while I have the issue that the GH pop-ups will stick. This means that they do not close when moving away from the link that is producing the popup. Affected are e.g. GH users, Issue / PR Popups etc. Moving to another pup-up-producing link will replace the old with the new, which then gets sticky. Even scrolling it out of sight will preserve it. Example

![image](https://user-images.githubusercontent.com/4459312/212559430-211bcbc8-a58a-46ca-b417-cfca310275b7.png)

When reloading the page, the issue often "heals" itself magically. FF versions is 108.0.2 (64-bit). In the browser's dev console, I did not see anything notable.

**Comment by fregante** [comment]
Not clear if this is supposed to be a GitHub bug report, a Refined GitHub report or a feature request. Please use the correct issue template.

**Comment by fregante** [comment]
If this is supposed to be a GitHub bug report, contact GitHub directly.
