### ISSUE TITLE
`profile-gists-link` appears in projects navigation on profile

### ISSUE THREAD

**Issue by vintagesucks** [refined-github/refined-github#6231]
### Description

https://user-images.githubusercontent.com/13335308/213022769-6f171e4e-9d2b-4b07-a749-ac7289ac4dee.mp4

Similar to #6162

### How to replicate the issue + URL

1. Navigate to your own profile
1. Click on Projects
1. `profile-gists-link` is a tab in the projects navigation

### Extension version

22.12.15

### Browser(s) used

Firefox 110.0b1 (64-Bit)

**Comment by fregante** [comment]
Can you post a screenshot of your DOM near that extra link? Right click on it and then pick "Inspect". I want to see its containers. For example:

<img width="668" alt="Screenshot 8" src="https://user-images.githubusercontent.com/1402241/215417392-075f1d93-3ec8-420c-ba5a-3720cbf20b7f.png">



I don't use projects so I don't have that second line

<img width="515" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/215417485-97977b9e-e8a2-4376-ab1e-8d36708b257a.png">

**Comment by vintagesucks** [comment]
Interesting! Maybe you get the second line if you also create a classic project (https://github.com/new/project)?

Anyhow, does this help?

![grafik](https://user-images.githubusercontent.com/13335308/215436741-fafd80e8-d9d2-454a-ab95-376c47fffae1.png)

**Comment by fregante** [comment]
I sent a PR but I'm not 100% sure it'll fix it. Are you able to build it and run it?

**Comment by vintagesucks** [comment]
Looking good! 

<img width="361" alt="grafik" src="https://user-images.githubusercontent.com/13335308/215468354-6edac114-243c-4545-9671-20a9825bb341.png">

By the way, it was very easy to follow your contributing guide to build the extension. Kudos!

**Comment by fregante** [comment]
Glad to hear that! 💚
