### ISSUE TITLE
`hide-newsfeed-noise` breaking follow notifications

### ISSUE THREAD

**Issue by noghartt** [refined-github/refined-github#6232]
### Description

On my feed, I would like to know what are the people that someone starts to follow.

But when I try to expand the section containing the people that has been followed, I can't see anything.

### How to replicate the issue + URL

Just open the [home feed](https://github.com/) when logged in and see what happens.

![image](https://user-images.githubusercontent.com/47952043/213156290-786f690a-3eed-40cf-9efe-90bb1063b588.png)

A friend report to me that he can see this section and can expand on it too. I don't know why this is happening here.

### Extension version

22.12.15

### Browser(s) used

Arc (chromium-based)

**Comment by fregante** [comment]
I think https://github.com/refined-github/refined-github/pull/6194 fixed this, but you're already using a version with that fix 🤔 

Related:

- https://github.com/refined-github/refined-github/issues/6214

**Comment by noghartt** [comment]
Disabling `hide-newsfeed-noise`, I could see the expandable following section again. Thank you so much!

**Comment by fregante** [comment]
This seems to be working correctly. It's possible that the hotfix was not updated

## Without RG

<img width="591" alt="Screenshot 6" src="https://user-images.githubusercontent.com/1402241/215416497-b3fd92db-4f31-4297-ab22-1078d3717962.png">

## With RG

<img width="582" alt="Screenshot 7" src="https://user-images.githubusercontent.com/1402241/215416536-dc8de1d0-5658-43b6-966f-13389a72bcfc.png">
