### ISSUE TITLE
User info boxes on mouse over username don't close

### ISSUE THREAD

**Issue by Ten0** [refined-github/refined-github#6234]
### Description

Note how the mouse is not on the username anymore:
![image](https://user-images.githubusercontent.com/9094255/213450635-76c6c204-3d88-4e94-b57d-520bdd0a32e0.png)

However the box stays open. This is a bug I've never had until I installed this extension yesterday.

This happens very regularly but not 100% consistently.

This prevents from clicking the buttons beneath which is a huge issue.

The issue also happens on other such boxes on the page when it starts happening for a page.

### How to replicate the issue + URL

PR 6230 in this repository (not putting a link to avoid mention). Sometimes this happens.

### Extension version

22.12.15

### Browser(s) used

Firefox

**Comment by fregante** [comment]
Does the page keep working or is it all stuck? If it gets stuck this is an urgent issue and it's probably going in a loop.

**Comment by Ten0** [comment]
It doesn't get stuck, if I put my mouse over another thing that would open a such box, the original box closes and the new one now stays open forever.

**Comment by Ten0** [comment]
> This is a bug I've never had until I installed this extension yesterday.

I have tested that and couldn't reproduce the issue without the extension (although as it's a bit flaky I can't be 100% sure but with the fact I've just installed this extension and it started happening right away, the fact I've never seen it before and the fact none of my colleagues have it I'm 98% sure let's say ^^)

**Comment by crystal-williams-brown** [comment]
I have this happen and it bothers me so much I don't have an Refined Github extension, this is just how Github is. It's very annoying

**Comment by fregante** [comment]
Thank you for the report. So this is not Refined GitHub. 

Y'all have to wait for GitHub to fix it.
