### ISSUE TITLE
Side by side Markdown editor

### ISSUE THREAD

**Issue by bokub** [refined-github/refined-github#6236]
### Description

Hello,

I have an idea for a feature, please tell me if it's suited or not for this extension

For all markdown editors in GitHub (comments, issues, discussions...), I'd love to be able to display the the "Write" tab and the "Preview" tab **side by side**, similar to side-by-side comparison when you visualize a commit

Do you thinks it's a good idea ? It this feasible ?

Thanks :+1: 

### Screenshot

Something like this

![image](https://user-images.githubusercontent.com/17952318/213655614-ff6223bb-b81a-46ee-9791-29a28d4a9a3b.png)

### Example URLs

- pull-request comments: `https://github.com/<owner>/<repo>/pull/<id>`
- issues: `https://github.com/<owner>/<repo>/issues/<id>`
- discussions: `https://github.com/<owner>/<repo>/discussions/<id>`

**Comment by fregante** [comment]
GitHub's markdown renderer is server-side and relatively slow in my experience. I think there are other extensions that add such preview already with a local markdown parser, so I suggest looking for them. It'd be too big of a feature for Refined GitHub
