### ISSUE TITLE
Looking for a way to prevent / disable the "jumpy ui" on the PR list

### ISSUE THREAD

**Issue by fluffynuts** [refined-github/refined-github#6240]
When dealing with a large backlog of PRs (eg from dependabot), I like to middle-click-to-open a bunch of PRs in new tabs so I can just accept them. The problem comes in with the UI changing positioning for things such that I have to wait for each accordion to open up & have to adjust mouse position. It's a little frustrating - see gif:

![jumpy-ui](https://user-images.githubusercontent.com/4669340/213994988-7b81dada-9bb0-448a-baa8-467c11374be3.gif)

I tried inspecting source & found the use of `relative-time` elements & then went looking through the source of refined-github to try to find the feature which implements this:
![image](https://user-images.githubusercontent.com/4669340/213995154-5e692fd7-391a-4322-8b7d-102ce997132f.png)

but either I'm doing something horribly wrong, or none of these are the feature I'm looking for ): I can disable RG to get what I want, but then I lose out on all the other great stuff. 

Any help appreciated.

**Comment by fregante** [comment]
The feature is called `dim-bots`

If you find yourself dealing with bots often, it makes sense to disable it. 

There's another issue regarding this issue, to improve the UX, but I don't remember which.

**Comment by fregante** [comment]
The feature is called `dim-bots`

If you find yourself dealing with bots often, it makes sense to disable it. 

There's another issue regarding this issue, to improve the UX, but I don't remember which.

**Comment by fregante** [comment]
The feature is called `dim-bots`

If you find yourself dealing with bots often, it makes sense to disable it. 

There's another issue regarding this issue, to improve the UX, but I don't remember which.

**Comment by fregante** [comment]
The feature is called `dim-bots`

If you find yourself dealing with bots often, it makes sense to disable it. 

There's another issue regarding this issue, to improve the UX, but I don't remember which.

**Comment by fregante** [comment]
The feature is called `dim-bots`

If you find yourself dealing with bots often, it makes sense to disable it. 

There's another issue regarding this issue, to improve the UX, but I don't remember which.

**Comment by fluffynuts** [comment]
Thanks for the heads-up! Appreciated.

**Comment by busches** [comment]
Additionally, we do add an `Open All` button at the top to make your flow easier.

**Comment by fregante** [comment]
This feature’s UX was greatly improved in 23.3.2, you can give it a try: https://github.com/refined-github/refined-github/pull/6374
