### ISSUE TITLE
Download Folder not available

### ISSUE THREAD

**Issue by Eversor** [refined-github/refined-github#6242]
### Description

The download folder option doesn't show up.

### How to replicate the issue + URL

Confirm not working anymore on chrome. The folder i'm trying to download seem to be the main branch afaik.
This is the folder in question: https://github.com/MonoGame/MonoGame.Dependencies/tree/master/MojoShader

### Extension version

v22.12.15

### Browser(s) used

Chrome for Windows

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/6154
