### ISSUE TITLE
Rethink `latest-tag-button`

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6250]
The new React-based views mentioned in https://github.com/refined-github/refined-github/issues/6152, no longer have enough space to show  `latest-tag-button`

<img width="471" alt="Screenshot 19" src="https://user-images.githubusercontent.com/1402241/215428933-29c77bbd-a143-47e2-95ef-01651541f6b6.png">

Essentially the old view is only show on isRepoRoot 

<img width="471" alt="Screenshot 18" src="https://user-images.githubusercontent.com/1402241/215428978-165aa162-8b0e-48c0-9783-952eb1d7463f.png">

What do we do with this feature? It was initially added to:

- inform the user that they're looking at a version of the readme that doesn't match the latest version
- see what commits haven't yet been released

Questions:

- does it really belong in that area of the screen?
- do we really need to show it in every folder and every file?
- is there a better way to communicate this information?

**Comment by fregante** [comment]
The feature also lets you:

- see the current view on the latest tag
- compare the latest tag to the latest version on main (which is a bit awkward on non-main branches)

I wonder if we can reduce it to:

- "see latest published version" link
- "see unreleased commits" link
- count unreleased commits

This would let us split and reposition the feature. We don't need to show the latest version on every page.

**Comment by fregante** [comment]
Here's my suggestion, I think it's a more direct solution to the original issue. The only missing part is that it requires 2 more clicks (without pageloads) to open "the same view, but in the latest tag." That's something I think is relatively rarely needed 🤔

## `unreleased-commits`

<img width="407" alt="Screenshot 22" src="https://user-images.githubusercontent.com/1402241/231438381-8160de57-5df7-4f78-894b-98881696898b.png">

- Shows: Whether there are unreleased commits
- Shows: How many commits are unreleased (if possible)
- Action: List unreleased commits (compare view)

Resolves:

- space issues: it's less than 60px wide
- sizing: we can finally drop `btn-sm`
- confusing state: it no longer confusingly shows the current tag in every single page

Missing:

- The exact tag: it can appear in the tooltip
- A link to the "tree" view of the tag: still available in +2 clicks in the dropdown

	<img width="300" alt="Screenshot 23" src="https://user-images.githubusercontent.com/1402241/231438976-b110d3a1-21cf-4f4f-8588-1d770fc78331.png">

**Comment by fregante** [comment]
Something to note: `unreleased-commits` would only appear on the default branch; not on tags, not on commits, not on other branches. The feature would exclusively say:

```
Hey you're looking at a newer version than what's published
```

This would also leave space for:

- https://github.com/refined-github/refined-github/issues/6499

**Comment by kidonng** [comment]
Maybe we should just merge it with the branch/tag picker:

## [On default branch](https://github.com/refined-github/refined-github)

TODO

## [On non-default branch](https://github.com/refined-github/refined-github/tree/demo)

Do nothing
  
<img width="392" alt="image" src="https://user-images.githubusercontent.com/44045911/232228769-a3c74c27-e935-4c8b-8c30-b2d54eea2689.png">

## [On latest tag](https://github.com/refined-github/refined-github/tree/23.4.10)

### Homepage

<img width="493" alt="image" src="https://user-images.githubusercontent.com/44045911/232228802-880db620-13a1-4c21-b4c4-ff17e03504da.png">

### File browser

TODO

## [On non-latest tag](https://github.com/refined-github/refined-github/tree/23.3.31)

### Homepage

<img width="416" alt="image" src="https://user-images.githubusercontent.com/44045911/232228828-d77362b0-a2e1-4c86-8872-4a3cd145df4d.png">

### File browser

<img width="289" alt="image" src="https://user-images.githubusercontent.com/44045911/232228839-687f6f14-4f43-4ff1-8bf9-d49105659090.png">

**Comment by fregante** [comment]
> How to go to latest tag

I think we need to de-emphasize the importance/frequency of this action and the necessity to know the latest tag on every single page.

I think `unreleased-commits` would bring the benefits we had initially wanted without filling the UI with unnecessary information.

This is why I suggest dropping `latest-tag-button` and adding a new, focused feature.

> How to go to latest tag
> 
> 1. Open picker
> 2. Select tag tab
> 3. Click the first item

This is good enough for me, requires no features/changes from us.

**Comment by kidonng** [comment]
> I think we need to de-emphasize the importance/frequency of this action and the necessity to know the latest tag on every single page.

My proposal is about not losing any current info, of course cutting down them is welcome
