### ISSUE TITLE
Linkify issues on yolo

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6258]
### Description

We have issues on this page, but they're not clickable. This would be a quick meta feature, probably named `rgh-linkify-yolo-issues`

### Screenshot

<img width="648" alt="Screenshot 31" src="https://user-images.githubusercontent.com/1402241/215490319-62049e09-d7e4-4f8c-b20b-97931f359687.png">

### Example URLs

https://github.com/refined-github/yolo/blob/main/broken-features.csv

**Comment by hemantsoni42** [comment]
@fregante can you please provide some more information about the issue.

**Comment by fregante** [comment]
In the "issue describing bug" column there are some numbers like "6109". Each of those is a reference to an issue, for example #6109.

The feature should look something like:


```js
for (const issueCell of select.all('td:nth-child(2)')) {
  wrap(cell.firstNode, <a href={getRghIssueUrl(cell.textContent)}>)
}

**Comment by hemantsoni42** [comment]
Ok can this implementation solve this issue ??
````
import React, { useEffect, useRef } from 'react';

const LinkifyIssues: React.FC = () => {
  const issueReferences = useRef<NodeListOf<HTMLTableDataCellElement>>(
    document.querySelectorAll('td:nth-child(2)')
  );

  useEffect(() => {
    issueReferences.current.forEach((issueCell) => {
      const issueNumber = issueCell.textContent;
      const issueLink = document.createElement('a');
      issueLink.href = `https://github.com/your-repo/issues/${issueNumber}`;
      issueLink.textContent = `#${issueNumber}`;
      issueCell.innerHTML = '';
      issueCell.appendChild(issueLink);
    });
  }, []);

  return null;
};

export default LinkifyIssues;
```

**Comment by hemantsoni42** [comment]
Ok can this implementation solve this issue ??

```
import React, { useEffect, useRef } from 'react';

const LinkifyIssues: React.FC = () => {
  const issueReferences = useRef<NodeListOf<HTMLTableDataCellElement>>(
    document.querySelectorAll('td:nth-child(2)')
  );

  useEffect(() => {
    issueReferences.current.forEach((issueCell) => {
      const issueNumber = issueCell.textContent;
      const issueLink = document.createElement('a');
      issueLink.href = `https://github.com/your-repo/issues/${issueNumber}`;
      issueLink.textContent = `#${issueNumber}`;
      issueCell.innerHTML = '';
      issueCell.appendChild(issueLink);
    });
  }, []);

  return null;
};

export default LinkifyIssues;
```

**Comment by fregante** [comment]
We don't have React here. The code I suggested is 90% of what you need

**Comment by hemantsoni42** [comment]
ok sir thank you
I already created a Pull request. There is some chance the code may be wrong if it is please let me know because this is my first contribution.
And thank you once again for explaining the issue
