### ISSUE TITLE
Enable arrow key navigation on the /notifications page

### ISSUE THREAD

**Issue by 0xdevalias** [refined-github/refined-github#6272]
### Description

Currently it's possible to navigate up/down in the list of notifications using `j` / `k`, and to mark them as selected with `x`.

It would be nice if it was also possible to use the `up` and `down` arrow keys, instead of the default `j` / `k` (as the arrow keys are more obvious feeling to a 'casual user'; whereas I always have to go back to the help to look up the default keys)

While this might be a nice feature to enable site-wide (as apparently the `j` / `k` shortcuts are sitewide), my explicit  use case/desire is only on the `/notifications` page; and i'm not sure if/what wider impacts changing the arrow keys across the whole site would have.

I hacked together a bit of a prototype for this to see if it would be possible/how it would feel to use; there are probably some issues with it, but here it is as written:

```js
document.addEventListener('keydown', (event) => {
  if (event.target.tagName !== 'BODY') return;

  if (event.key === 'ArrowUp') {
    event.preventDefault();
    event.stopPropagation();

    document.body.dispatchEvent(new KeyboardEvent('keydown', { key: 'k', code: 'KeyK', bubbles: true }));
  }
  else if (event.key === 'ArrowDown') {
    event.preventDefault();
    event.stopPropagation();

    document.body.dispatchEvent(new KeyboardEvent('keydown', { key: 'j', code: 'KeyJ', bubbles: true }));
  }
  else if (event.key === 'ArrowLeft') {
    event.preventDefault();
    event.stopPropagation();

    document.body.dispatchEvent(new KeyboardEvent('keydown', { key: 'h', code: 'KeyH', bubbles: true }));
  }
  else if (event.key === 'ArrowRight') {
    event.preventDefault();
    event.stopPropagation();

    document.body.dispatchEvent(new KeyboardEvent('keydown', { key: 'l', code: 'KeyL', bubbles: true }));
  }
}, { capture: true });

```

### Screenshot

N/A

### Example URLs

https://github.com/notifications

### See Also

My other `/notifications` feature requests:

- https://github.com/refined-github/refined-github/issues/6273
- https://github.com/refined-github/refined-github/issues/6274
- https://github.com/refined-github/refined-github/issues/6275
- https://github.com/refined-github/refined-github/issues/6276

**Comment by fregante** [comment]
Arrow keys have other purposes for accessibility, that's why J and K are used instead. Can't do it.

**Comment by 0xdevalias** [comment]
@fregante And yet you already override them for `left` and `right`, which seems at odds with what you just said..

![Screenshot 2023-02-02 at 9 56 16 am](https://user-images.githubusercontent.com/753891/216184765-2a63c168-9d49-4b0d-ab9e-2009bd5e1ce1.png)

**Comment by fregante** [comment]
Funny you'd mention that because it was implemented before I took over. Also:

- in 7 years, we can't expect every decision to be consistent
- just because we made bad decisions, it doesn't mean we should make more https://en.wikipedia.org/wiki/Broken_windows_theory

**Comment by 0xdevalias** [comment]
@fregante Perhaps the legacy 'bad decision' should be rectified to align with your current policy then? A consistently applied policy makes it far easier for others to understand, reason about, and follow it. Haphazardly applying it just undermines the impact/trust in the policy.
