### ISSUE TITLE
Allow 'Group by' Date/Repository to be used on any filter view in /notifications (not just the Inbox)

### ISSUE THREAD

**Issue by 0xdevalias** [refined-github/refined-github#6274]
### Description

Currently, when the 'Inbox' is selected on the `/notifications` page, we can use the 'Group by' selector to change the view between showing by date, or grouped by repository; yet this only works on the 'Inbox' filter view; so if we switch to any of the other default views (eg. Saved, Done), or any of our custom views (eg. Assigned, Participating, etc); we no longer have that 'Group by' option.

It would be awesome if we were able to use 'Group by' on any filter/view page.

### Screenshot

![image](https://user-images.githubusercontent.com/753891/215882575-259ed643-988a-464f-a712-0e0b0e0504dd.png)

![image](https://user-images.githubusercontent.com/753891/215883244-2719ee19-fde5-449b-93ea-dbeacd19a9a9.png)

![image](https://user-images.githubusercontent.com/753891/215883036-3994e7c6-91d3-4dcc-bb39-23cf21257139.png)

### Example URLs

https://github.com/notifications

### See Also

My other `/notifications` feature requests:

- https://github.com/refined-github/refined-github/issues/6272
- https://github.com/refined-github/refined-github/issues/6273
- https://github.com/refined-github/refined-github/issues/6275
- https://github.com/refined-github/refined-github/issues/6276

**Comment by fregante** [comment]
Unfortunately this is impossible in Refined GitHub for the same reasons outlined by https://github.com/refined-github/refined-github/issues/6186#issuecomment-1361254524

If you spent a lot of time on notifications, I suggest looking into apps that make it easier, like

https://getlotus.app/

**Comment by 0xdevalias** [comment]
> If you spend a lot of time on notifications, I suggest looking into apps that make it easier, like
> 
> [getlotus.app](https://getlotus.app/)

I've looked at it, and I like it in theory, yet in practice it has too many 'unknowns'/'doesn't seem to sync well with the native `/notifications` view. Hopefully it will get better over time, but my assessment so far was "looks cool, but insufficient".

**Comment by fregante** [comment]
That's just one example a friend of mine built, there are many other such apps

**Comment by fregante** [comment]
> after I triage the fact that I ignored `/notifications` so long

There lies the issue I think. These features seem to suggest you have a lot of notifications to go through and that's generally not something people have to do, and that's why I don't see the utility (compared to the complexity) of these features.

There's also an older product for notification management: https://octobox.io/
