### ISSUE TITLE
Review now button should not show for author of the PR or for closed PRs

### ISSUE THREAD

**Issue by hkdobrev** [refined-github/refined-github#6279]
### Description

The `quick-review` button in the PR sidebar is awesome!

But it shows in some cases where it's not that necessary:

- When the author of the PR is looking at the page, they don't need to have a quick way to review it. Technically, they can leave a review comment, but it's not that necessary or common.
- When the PR is already closed, the button is not that useful either.

P.S. If possible to detect, the quick review button is not useful on repositories you don't have review permissions as well.

### Example URLs

https://github.com/refined-github/refined-github/pulls/@me

Any PR which is either closed or you are the author.

**Comment by fregante** [comment]
Why not? GitHub shows it in both cases. See https://github.com/refined-github/refined-github/pull/159/files

<img width="580" alt="Screenshot 1" src="https://user-images.githubusercontent.com/1402241/215986267-8d412fa9-92ef-4681-888c-0af8375e052a.png">

**Comment by fregante** [comment]
Even GitHub’s own "assign yourself" is still there, we basically copied that:

<img width="316" alt="Screenshot 2" src="https://user-images.githubusercontent.com/1402241/215986445-77a40172-3365-451a-95fd-e929dcbd301e.png">

**Comment by fregante** [comment]
> * When the author of the PR is looking at the page,

I review my own PRs to add notes, see https://github.com/refined-github/refined-github/pull/6253

But I don't usually just leave a "review comment", I comment on the file itself, so you're right that the "Review now" link isn't particularly useful.

I'd still keep it though:

- for consistency, so I know that is'a always there at all times when the feature behind it is also there
- it's not particularly worth adding the logic for the 3 situations (even if they're all feasible) only to remove a feature
