### ISSUE TITLE
Single click on "Fork" to redirect to personal fork

### ISSUE THREAD

**Issue by casperklein** [refined-github/refined-github#6291]
Hi,

if I remember correctly, I could once in an upstream repository click on "fork" and would then be redirected to my personal fork.

This does not work anymore. I am not sure when this exactly "broke" for me. I looked through the issues and found "Drop forked-to feature #5745", which could be the feature I was using.

Is there still the possibility with a one-click action, to get to my personal fork? Now I've to click on "Fork" and then select the only listed fork (my fork).

Not a big deal, but I wanted to ask in case there is a solution to save me one click 😉

**Comment by fregante** [comment]
Indeed we used to have a one-click button when a fork was detected. I suppose I wouldn't be opposed to restoring that button if a single fork was detected:

https://github.com/refined-github/refined-github/blob/10d57548f67c34f26e4d44e83007ef9f24b673f9/source/features/forked-to.tsx#L55-L61

Possible feature:

1. on fork menu opening, store fork if there's only one, clear cache if there's more than one
2. if there's a stored fork, add button on load

**Comment by casperklein** [comment]
I can't provide a PR for that, as I am not familiar with typescript. If you or someone else implements this, that would be cool.

**Comment by fregante** [comment]
Not worth the complexity to save 1 second. Just open the dropdown:

<img width="322" alt="Screenshot" src="https://github.com/user-attachments/assets/d551a600-c562-4583-8933-ae7e324365c2">
