### ISSUE TITLE
`release-tab` is added too early, out of order, sometimes

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6293]
### Description

<img width="645" alt="Screenshot 1" src="https://user-images.githubusercontent.com/1402241/216769596-da0bb3ec-72d9-4f21-960e-fd2b3af58cc0.png">

### How to replicate the issue + URL

It happens occasionally, but often enough

https://github.com/refined-github/refined-github

### Extension version

23.2.1

### Browser(s) used

Chrome

**Comment by innocenzi** [comment]
It also sometimes doesn't appear at all and I can't figure out why. 

Sometimes it's because the repository owner unchecked "releases" to the "show on the home page" setting, but sometimes the tab is not there even though releases exist.

Maybe these issues could be fixed together

**Comment by fregante** [comment]
This is strange, we do have a specific waiter for the whole bar:

https://github.com/refined-github/refined-github/blob/60b7aa240d0902ed34904129a0b83631f88870f6/source/features/releases-tab.tsx#L62-L63
