### ISSUE TITLE
`fork-source-link-same-view` broke forked repo branch to `undefined`

### ISSUE THREAD

**Issue by 01101sam** [refined-github/refined-github#6302]
### Description

The `sameViewUrl.branch` is `undefined` when calling `await getDefaultBranch(forkedRepository)` @ function `getEquivalentURL`.

This only happened in sub-fork repo (For example, a fork of a fork)

> Please look at left bottom, the path of the branch is `undefined`

![image](https://user-images.githubusercontent.com/100821827/216920092-01fd316d-14ea-4215-8a9f-722fd47db908.png)

I've look through the code and found out that problem, but I'm still unsure if that's the right place that cause this `undefined`
![image](https://user-images.githubusercontent.com/100821827/216921506-b920f967-15f6-4095-b5c8-d04b2dfa3ff0.png)

### How to replicate the issue + URL

Example url:
```
https://github.com/01101sam/node-proxy-agent
|- https://github.com/bonald/node-https-proxy-agent
  |- https://github.com/orihamama/node-https-proxy-agent
```

Reproduce: Just hold your mouse at the same place that last screenshot shows, and click.
- Expected: You'll get redirected to parant repo.
- Got: 404 path (But the repo is still there as shown in the following screenshot)

![image](https://user-images.githubusercontent.com/100821827/216920704-c52761d8-0fae-4f5c-8c29-a1ad57d421d0.png)

### Extension version

23.2.5

### Browser(s) used

Chrome

**Comment by fregante** [comment]
I don't see the bug on the page https://github.com/01101sam/node-proxy-agent

**Comment by 01101sam** [comment]
> I don't see the bug on the page [01101sam/node-proxy-agent](https://github.com/01101sam/node-proxy-agent)
> 
> Even on this page: [01101sam/node-proxy-agent@`master`/src](https://github.com/01101sam/node-proxy-agent/tree/master/src?rgh-link-date=2023-02-06T08%3A32%3A31Z) The link points to [bonald/node-https-proxy-agent@`master`/src](https://github.com/bonald/node-https-proxy-agent/tree/master/src?rgh-link-date=2023-02-06T08%3A32%3A31Z). On which page it points to [orihamama/node-https-proxy-agent@`master`/src](https://github.com/orihamama/node-https-proxy-agent/tree/master/src?rgh-link-date=2023-02-06T08%3A32%3A31Z)

Extra info: You have ensure the page is first accessed, or just simply enter the url to the tab.
Or refresh the page.

**Comment by fregante** [comment]
Already done after clearing the cache. 

Can you clear the cache in the options page first? Either you have an outdated cache or the repro requires visiting another page first

**Comment by 01101sam** [comment]
> Already done after clearing the cache.
> 
> Can you clear the cache in the options page first? Either you have an outdated cache or the repro requires visiting another page first

This bug can still reproduce. And it also works at incognito mode without logging in.

**Comment by fregante** [comment]
You're right, I must have broken this in https://github.com/refined-github/refined-github/pull/6265, which isn't yet available in my browser (Safari). 

I can reproduce in Chrome
