### ISSUE TITLE
Repository Header is lacking padding-left 

### ISSUE THREAD

**Issue by cfstras** [refined-github/refined-github#6304]
### Description

Currently, when Refined Github is enabled, the header at the top of a repo is lacking padding on the left side.
This causes the title and Tab selector (code/issues/bugs/...) to be "glued" to the left side of the screen.

Expected / Actual:
<img width="272" alt="image" src="https://user-images.githubusercontent.com/1156864/216946792-90aa6a0f-d2ef-4169-a949-abeac1a03f36.png">   <img width="294" alt="image" src="https://user-images.githubusercontent.com/1156864/216946862-929719d6-8a4b-4ed0-bb10-3c5ae5c3d7d7.png">

This is probably caused by this snippet I found (on a flex div, direct child of `#repository-container-header`:
```
.refined-github > body:not(.wgh-disabled, .full-width, .enterprise) main > .hide-full-screen > * {
    padding-left: 0px !important;
}
```

A workaround is to add this custom CSS to refined github:
```
#repository-container-header {
padding-left: var(--base-size-24, 24px) !important;
}
```

### How to replicate the issue + URL

https://github.com/refined-github/refined-github

### Extension version

23.2.5

### Browser(s) used

Chrome 109.0.5414.119

**Comment by fregante** [comment]
That piece of code does not belong to us, we don't use `refined-github` class in our selectors.

It's more likely that some other extension is targeting Refined GitHub

**Comment by fregante** [comment]
Related: the feature that they're likely targeting has been dropped, which is why you're seeing that issue:

- https://github.com/refined-github/refined-github/pull/6247
