### ISSUE TITLE
`sticky-sidebar` doesn't work on the repo’s "Code" tab

### ISSUE THREAD

**Issue by noftaly** [refined-github/refined-github#6307]
### Description

I'm not really sure when it broke, but it looks like the `sticky-sidebar` feature doesn't work anymore, although the class "`rgh-sticky-sidebar`" is correctly added to the div...
There are no console errors

You can see at the beginning of the video that the sidebar does have the `rgh-sticky-sidebar` class, but when I scroll it isn't sticky. This video was made in Firefox.

https://user-images.githubusercontent.com/34779161/217345273-9fcc1fc7-b9ad-48f0-96ed-98195084748d.mov

### How to replicate the issue + URL

- Go to the page https://github.com/refined-github/refined-github/ with a screen big enough to fit the sidebar (check that the `rgh-sticky-sidebar` class is added to the div)
- Scroll
- The sidebar is not sticky

### Extension version

23.2.5

### Browser(s) used

Firefox & Safari

**Comment by fregante** [comment]
The feature depends on the viewport height. If the sidebar doesn't fit completely into the viewport (and the mouse isn't hovering it), it will not stick. 


On that page, try zooming out the page to 50% and it should stick.

**Comment by noftaly** [comment]
Yes I'm aware, but it still does not work. That's why I was insisting that there was the class `rgh-sticky-sidebar`, because it's only added when the sidebar fits; so it means that the extension detected that it sticks.

I zoomed out to 50% and here is the result:

https://user-images.githubusercontent.com/34779161/217364496-0dbb3e72-6cc9-4244-9bac-81bacbf7c110.mov

**Comment by amanmalh** [comment]
Hi @fregante, I'd like to work on this issue. I think I have a fix. Thanks.

**Comment by fregante** [comment]
You can send PRs unannounced.
