### ISSUE TITLE
`list-prs-for-branch` broken

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6309]
### Description

No error, not shown. https://github.com/refined-github/sandbox/pull/4 is open from that branch

<img width="447" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/217459736-919af5d7-7f7c-4231-b301-7bd9c59965ad.png">

Similar issue:

- #6299 

Related:

- https://github.com/refined-github/refined-github/issues/5234

### How to replicate the issue + URL

https://github.com/refined-github/sandbox/commits/sdfsdfds

### Extension version

23.2.1

### Browser(s) used

Safari

**Comment by amanmalh** [comment]
This seems to be working fine for me:
![prs for branch](https://user-images.githubusercontent.com/11196460/218370908-26c60169-3493-49e0-8ee0-2c8144198fd5.png)
Can we double check if the provided personal token is valid or not expired?

**Comment by fregante** [comment]
hmm you're right 🤷‍♂️ 

<img width="459" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/218377802-71027dca-86a7-4a95-9178-eafdbf4814bf.png">

Good thing I took a screenshot last time or I'd think I was crazy 😅
