### ISSUE TITLE
`clean-header-search-field`: Cannot read properties of undefined (reading 'classList')

### ISSUE THREAD

**Issue by kaste** [refined-github/refined-github#6310]
### Description

With the new Redefined version I get

![image](https://user-images.githubusercontent.com/8558/217484482-42e2be88-c606-46ce-9baa-cf439cbebbea.png)

If I follow the trace, it points to 

```
    }), feature_manager.add("file:///home/runner/work/refined-github/refined-github/source/features/clean-header-search-field.tsx", {
      include: [ isIssueOrPRList, isGlobalIssueOrPRList, isRepoSearch ],
      awaitDomReady: !1,
      init: async function() {
        const headerSearchButton = await elementReady("button.header-search-button");
        headerSearchButton.classList.add("placeholder"), select_dom('[data-target="search-input.inputButtonText"]', headerSearchButton).textContent = headerSearchButton.getAttribute("placeholder");
      }
    });
```

I do not have a `$("button.header-search-button")` on the page but I also don't have a "dirty" search field if I just disable this feature.  E.g. your test page https://github.com/fregante/GhostText/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc from https://github.com/refined-github/refined-github/pull/6266 looks like this before and after:

![image](https://user-images.githubusercontent.com/8558/217487300-0b816b31-725b-4532-938a-880a22ffe584.png)

### How to replicate the issue + URL

*I* get this this on every issues/pr page.

### Extension version

23.2.5

### Browser(s) used

brave

**Comment by fregante** [comment]
Do you have the new search feature? Can you send a screenshot of what it looks like when you focus the "search" field?

**Comment by kaste** [comment]
I have this

![image](https://user-images.githubusercontent.com/8558/217522551-1cb6ece0-217e-453a-abf1-6bf4ae797d75.png)

**Comment by fregante** [comment]
Indeed you still have the previous version. PR sent
