### ISSUE TITLE
Automatically sort stars by recently active

### ISSUE THREAD

**Issue by Yashirow** [refined-github/refined-github#6319]
### Description

Basically title, I searched if this already exist but found nothing so it would be great to have an option to automatically sort user's stars by recently active. Thanks.

### Example URLs

https://github.com/Yashirow?tab=stars to https://github.com/Yashirow?direction=desc&sort=updated&tab=stars

**Comment by fregante** [comment]
Makes sense but it's not objectively better than the default, I think changing it would not be welcome by most people

**Comment by Yashirow** [comment]
Yes I understand, but even if it's a toggleable option disabled by default in the extension settings it wouldn't be welcome ?

**Comment by fregante** [comment]
https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#2-it-makes-sense-as-a-default-for-everyone
