### ISSUE TITLE
Feature description overlaps first line of code on new file viewer

### ISSUE THREAD

**Issue by jerone** [refined-github/refined-github#6337]
### Description

![image](https://user-images.githubusercontent.com/55841/218269332-38ba106e-8f2e-4829-b290-9b60634f8540.png)

### How to replicate the issue + URL

Happens on any [feature source code](https://github.com/refined-github/refined-github/tree/main/source/features) file. For example: https://github.com/refined-github/refined-github/blob/main/source/features/action-used-by-link.tsx

This does **not** happen when source file is not an feature with an description. For example: https://github.com/refined-github/refined-github/blob/main/build/prepare-safari-release.sh

### Extension version

23.2.11

### Browser(s) used

Firefox

**Comment by fregante** [comment]
This is due to our `mb-3` class. We can replace it with an additional wrapper and `pb-3` instead, plus JS comment

`<div className="pb-3"><div className="Box">`

**Comment by jerone** [comment]
I also noticed in the new file viewer, that navigating to another [feature source code file](https://github.com/refined-github/refined-github/tree/main/source/features), the feature description is not updated. Similar issue with navigating away from a feature source code file, the previous description is still shown.

**Comment by fregante** [comment]
It seems that that affects other features as well 😩 like `download-folder-button`
