### ISSUE TITLE
Make network view scrollable on android

### ISSUE THREAD

**Issue by Efreak** [refined-github/refined-github#6339]
### Description

The [network view](https://github.com/refined-github/refined-github/network) is a visual representation of the list of forks, showing the ~100 most-recently pushed forks, and showing how far ahead/behind the current repo they are. On desktop, you can move and navigate this with a mouse. On mobile, you can't; all you can do is open it. It would be nice to be able to either drag the inside of the network *or* have buttons for navigating it.
As a fallback, simply extending the view height so everything shows with normal scrolling would be perfectly acceptable. It wouldn't be great UI, but it's far better than being entirely unavailable like it currently is.

It would also be nice on desktop to be able to zoom the view, since it's usually so large, but this is less important.

### Example URLs

https://github.com/refined-github/refined-github/network

**Comment by fregante** [comment]
Oof yeah that probably only works with the `mousewheel` event. If there's an easy way to map the two events we can do it, but I don’t think there is. I don’t think it's worth adding a lot of code for a rarely-used (on mobile) feature.

**Comment by fregante** [comment]
Mostly done, the only issue is that it's resetting the initial position every time:

```js
canvas.ontouchstart = e => {
	canvas.dispatchEvent(new MouseEvent('mousemove', {clientX: e.touches[0].clientX, clientY: e.touches[0].clientY}))
	canvas.dispatchEvent(new MouseEvent('mousedown'))
	
}
canvas.ontouchend = e => {
	canvas.dispatchEvent(new MouseEvent('mouseup'))
	
}
canvas.ontouchmove = e => {
	canvas.dispatchEvent(new MouseEvent('mousemove', {clientX: e.touches[0].clientX, clientY: e.touches[0].clientY}))
	e.preventDefault()
	
}
```

https://user-images.githubusercontent.com/1402241/218295409-0bfb05ef-7da0-40fb-a877-935db3ccfae2.mov



PR welcome after fixing that and cleaning up the code above

**Comment by fregante** [comment]
While it's an "easy" feature, it's rather obscure and it's likely to get outdated/forgotten. It's likely best to ask GitHub to fix this
