### ISSUE TITLE
Show list of `<branch>:<commits number>` in repositories page of an account

### ISSUE THREAD

**Issue by andry81** [refined-github/refined-github#6347]
### Description

Sometimes exploring a someone account repositories page finds out that an account actually does not much develop anything in a repository. Many accounts has used a repository as a source with stars, but actually it is a copy (not a fork) from someone's else repository with poor number of commits.

This become pretty annoying and time consuming as exploring more and more growing github repositories.

Could you add this?

### Example URLs

https://github.com/abdeenm

**Comment by fregante** [comment]
Sorry this doesn't belong to Refined GitHub

**Comment by fregante** [comment]
This repo is not owned by GitHub.
