### ISSUE TITLE
`clear-pr-merge-commit-message` fills in the commit title instead of commit body

### ISSUE THREAD

**Issue by ssbarnea** [refined-github/refined-github#6348]
### Description

Originally reported on https://github.com/refined-github/refined-github/pull/6346#issuecomment-1433054970

I mention that this event does randomly happens. We were not able to reproduce it consistently but we observed it happening on totally different systems, one Linux with Chrome and another one MacOS with Chrome.

About occurrences so far in the last couple of weeks. The sad part is that usually you spot it after you press the merge button, and you end-up with a commit message that is really ugly.

At least in our use-case we just want to keep the original PR title as the squash commit message. That works most of the time, still this bug seems to appear from time to time.

Is there something we can tune in extension settings to prevent this accident from happening?

### Extension version

23.2.11

### Browser(s) used

Chrome Version 110.0.5481.100 (Official Build) (arm64)

**Comment by fregante** [comment]
The feature is `clear-pr-merge-commit`, so you can disable it to prevent it

**Comment by fregante** [comment]
My guess is that there's a chance that multiple simultaneous edits can cause race conditions in https://github.com/fregante/text-field-edit since the insertion is a sequence of `focusField(); execCommand(); blurField()`

A way to test this would be:

```js
create100inputs()
for ([input, index] of inputs) {
  insert(input, index)
  assert(input.value === index)
}
