### ISSUE TITLE
`quick-comment-hiding`: invalid form control is not focusable

### ISSUE THREAD

**Issue by KaelWD** [refined-github/refined-github#6350]
### Description

Click hide -> spam, devtools shows
```
An invalid form control with name='classifier' is not focusable.
<select name=​"classifier" class=​"form-select mr-2" aria-label=​"Reason" required>​…​</select>​
```

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/issues/6350#issuecomment-1434102807

### Extension version

23.2.11

### Browser(s) used

Chrome 110.0.5481.96

**Comment by KaelWD** [comment]
Hide me

**Comment by 134130** [comment]
Cannot reproducing now because of brand new GitHub's bug is appearing firstly.
<img width="550" alt="image" src="https://github.com/refined-github/refined-github/assets/50487467/273233d3-b9ea-48c3-87bc-bb6e18d3b92a">
