### ISSUE TITLE
Add a UI for comparing two commits on the history UI

### ISSUE THREAD

**Issue by RheingoldRiver** [refined-github/refined-github#6351]
### Description

On the [Comparing commits](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/viewing-and-comparing-commits/comparing-commits) page, Github suggests that you manually edit the URL:

> To quickly compare two commits or Git Object IDs (OIDs) directly with each other in a two-dot diff comparison on GitHub, edit the URL of your repository's "Comparing changes" page.

However, the MediaWiki software has a great UI for comparing revision history, which I would love to see refined-github add, and which looks like this:

![image](https://user-images.githubusercontent.com/18037011/219565242-e60399db-a49c-4f5e-a137-e4ae976cd8c6.png)

[link to that example MediaWiki page](https://support.wiki.gg/wiki/Support_Wiki?action=history) and I think a similar UI could be implemented here. It's read-only and links to diffs so I think it's possible to do without any permissions.

A variant of this that could be less code, easier to maintain, and less intrusive, would be to show only a "diff to present" button on each line of the commit history.

### Example URLs

Here is where I want it to appear: https://github.com/TsubakiBotPad/teambuilder/commits/master

And I would like it to link to something like this: https://github.com/TsubakiBotPad/teambuilder/compare/47ab41d..bd18b98

**Comment by fregante** [comment]
Refined GitHub is about small refinements, not large UIs https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#4-it-doesnt-require-a-lot-of-viewui-code-and-effort-to-maintain

**Comment by jerone** [comment]
You are welcome to revive this userscript: https://github.com/jerone/UserScripts/tree/master/GitHub_Commit_Compare#readme
