### ISSUE TITLE
Why are PRs dimmed in the list like this? It's annoying and there's no clear logic behind it.

### ISSUE THREAD

**Issue by KaranErry** [refined-github/refined-github#6352]
In a list of PRs, refined-github (RGH) seemingly unpredictably greys out certain PRs in the list unless they are hovered over. At first I assumed there was some filtering logic going on (maybe the greyed-out PRs are not mergeable, or something similar). However, the dimming disappears upon hover, and remains even when the cursor is moved outside the hover area. 

Seems like a bug to me? I searched for "pull" and "PR" in the list of features to try to understand this 'feature' better, and disable it, but couldn't find any feature description that matched the behaviour. 

Screen recording below:

https://user-images.githubusercontent.com/7901923/219645598-6ca1d77a-4633-4079-91ef-6e39deb82e0c.mov

**Comment by fregante** [comment]
The feature is called `dim-bots`. The logic is that not PRs are less important that human PRs

**Comment by KaranErry** [comment]
@fregante Thanks for letting me know!
