### ISSUE TITLE
PRs for cherry picks should _say_ they're for cherry picks

### ISSUE THREAD

**Issue by david-bakin-sl** [refined-github/refined-github#6353]
### Description

PRs that consist _only_ of one or more cherry picks should have a nice banner at the top saying "this is a cherry pick" and point to both the original commit _and_ the original approved PR that merged that commit (into the default branch, or possibly some other branch you set somehow?)

[I may have missed this feature in Github - or in _refined Github!_  If so, sorry, and please inform me.]

### Example URLs

https://github.com/hashgraph/hedera-json-rpc-relay/pull/918

This ⬆ is a cherry pick (to a release branch) from an approved PR that was merged into the default branch `main` - that PR is here:

https://github.com/hashgraph/hedera-json-rpc-relay/pull/910

**Comment by fregante** [comment]
How is GitHub or Refined GitHub supposed to know it's a cherry pick? The commit hash is different

**Comment by fregante** [comment]
Specific flows can be enforced at the repository level, via bots and labels. Refined GitHub can't add this
