### ISSUE TITLE
Hide empty Environments in `clean-repo-sidebar`

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#6359]
### Description

This happens if there used to be environments but are all deleted now. Maybe too rare to care?

EDIT: If I remember correctly, the environments may not necessarily be deleted, they can just be inactive.

### Screenshot

<img width="306" alt="截屏2023-02-19 18 37 33" src="https://user-images.githubusercontent.com/44045911/219942874-502d0963-2c5c-476f-a70d-7d60b010c7a6.png">

### Example URLs

https://github.com/kidonng/sushi

**Comment by fregante** [comment]
Could be a caching issue? I think GitHub already hides it when empty

**Comment by fregante** [comment]
Welp. 10 days later and it's still there, empty. It's worth hiding it

**Comment by fregante** [comment]
Hmm it's true that the section is empty, but how can users reach the Deployments page? That page is not empty and this appears to the only link to it: https://github.com/kidonng/sushi/deployments

Did you delete the Enviroments? Or is just a consequence of the archival? 

<img width="714" alt="Screenshot 2" src="https://github.com/refined-github/refined-github/assets/1402241/a0b3aea4-8eba-4bca-ad6b-800644ebb634">

I don’t think I'm comfortable with removing this link at this point

**Comment by fregante** [comment]
I don’t think I'm comfortable with removing this link at this point. Closing due to nicheness
