### ISSUE TITLE
`swap-branches-on-compare` broken

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6361]
### Description

No link is added here

```
undefined is not an object (evaluating 'icon.parentElement.attributes["aria-label"].value')
```

<img width="354" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/219944793-5fe46d9b-34de-4620-9223-6660de0ba99d.png">

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/compare/main...23.2.1

### Extension version

23.2.1

### Browser(s) used

safari

**Comment by kidonng** [comment]
Get it working.

<img width="312" alt="image" src="https://user-images.githubusercontent.com/44045911/230346173-298bd657-e3ec-40f5-81d6-be1e318cd877.png">

But that three-dots GitHub docs link make it easy to misclick. And I always find it a little bit counter-intuitive clicking the arrow does a _swap_. I can't stop thinking that the compare icon on the left looks like a "swap" button as well.

**Comment by fregante** [comment]
> easy to misclick

Understatement 😅 it covers half arrow:

<img width="340" alt="Screenshot 6" src="https://user-images.githubusercontent.com/1402241/230350918-cda522b2-7080-4534-82a1-414ea13166fe.png">




> I can't stop thinking that the compare icon on the left looks like a "swap" button as well.

I think we used to have it that way 🤔 

What if we stop being clever and just add a damn button to the UI? 😅 So many of our features are "too integrated"

The only issue is with cross-fork comparisons and long branch names, which reduce the available space.

**Comment by kidonng** [comment]
Maybe here? Not very visible though 😅

<img width="621" alt="截屏2023-04-06 18 32 38" src="https://user-images.githubusercontent.com/44045911/230352341-2c4bb905-1603-4c6d-9a55-bd40d5016521.png">

**Comment by kidonng** [comment]
> I think we used to have it that way 🤔

I went back to before corona and [it is using the arrow anyway](https://github.com/refined-github/refined-github/blob/11b927189bab258a226e251c1bd87504feee51f4/source/features/swap-branches-on-compare.tsx#L18)

**Comment by fregante** [comment]
It was using the icon in its original PR, but I made changes before it was ever merged: https://github.com/refined-github/refined-github/pull/1360#pullrequestreview-125696748



> Maybe here? Not very visible though 😅

Looks nice but yeah, textual links kinda get lost. I think it could be as simple as a `<a class="btn btn-sm">Swap</a>` element on the right side of the dropdowns. Beats a link hidden in an icon every day 👍
