### ISSUE TITLE
Prevent jump on merge dialog

### ISSUE THREAD

**Issue by Stanzilla** [refined-github/refined-github#6365]
### Description

When there are some failed or pending checks, clicking the merge button will make the UI jump, sometimes resulting in your mouse being over the "close" button, often leading clicking that by mistake.

### Screenshot

https://user-images.githubusercontent.com/75278/220124300-fd6e4439-b883-442b-8eb2-28ef98f88944.mp4

### Example URLs

Any PR with mixed check status

**Comment by fregante** [comment]
I kinda like the idea, but also I don't want double-clicks to mistakenly _confirm_ a merge. Closing a PR is reversible, merging PRs isn't.
