### ISSUE TITLE
`file-age-color` also runs on issues and PR tab

### ISSUE THREAD

**Issue by Katsute** [refined-github/refined-github#6366]
### Description

The new file age color feature also changes colors on issue and PR tabs.

![files](https://user-images.githubusercontent.com/58778985/220163785-bbb63b87-c24e-4c0e-bb4b-3c8f16c0cba0.gif)

### How to replicate the issue + URL

1. This repo https://github.com/refined-github/refined-github/
2. Press issue or pr tab

Only happens if you go directly from a file page to a issue/pr tab, moving from issue to pr tab doesn't have this issue.

### Extension version

23.2.20

### Browser(s) used

Google Chrome 110.0.5481.104 x64

**Comment by Katsute** [comment]
Might be a timing issue caused by the SPA. Is it possible the feature is running after the DOM change but before the URL change? This might explain why going to another tab right after doesn't have this issue.

**Comment by fregante** [comment]
> timing issue caused by the SPA

Last related change in 23.2.1: 

- https://github.com/refined-github/refined-github/pull/6267

**Comment by Shinigami92** [comment]
Oh, I thought that was a feature :eyes: 
I just wanted to report the bug that it doesn't load when you directly go to issue or PRs e.g. by reloading the page
You first need to load the `Code` tab and then navigate to issue/PR

**Comment by 5HT2** [comment]
I also honestly thought this was an intentional feature. If there could be an option to also enable this for issues / pull requests I'd greatly appreciate that!
