### ISSUE TITLE
Not available on Firefox Android 

### ISSUE THREAD

**Issue by scrazzz** [refined-github/refined-github#6367]
The [README](https://github.com/refined-github/refined-github#install) states that this addon is available on Firefox mobile. But it isn't.

![Screenshot_2023-02-20-22](https://user-images.githubusercontent.com/70033559/220188390-43257d0f-ad8e-4694-aadd-d37fb76bac72.jpg)

Is it just me or can anyone else confirm?

**Comment by fregante** [comment]
It's already set up to be installed there. Where does that "click here" point to? I think it's still complicated to install extensions on Firefox for Android, you have to create a collection, right?

![image](https://user-images.githubusercontent.com/1402241/220237833-dd53a662-f37f-4778-9fb9-db049367b33e.jpeg)

**Comment by scrazzz** [comment]
"click here" directs to https://addons.mozilla.org/en-US/android/

> you have to create a collection, right?

There's nothing called "collection" in the stable version of Firefox Android. I think Firefox only allows a handful of extensions available to be downloadable on the stable version.

Anyways, I did some quick googling and found out the answer: https://blog.mozilla.org/addons/2020/02/11/faq-for-extension-support-in-new-firefox-for-android/

Quoting a sentence from the above link:
> Yes, there is an override in Firefox for Android Nightly that you can use to install extensions listed on addons.mozilla.org (AMO) via AMO’s Collections feature.

So I need to install the Nightly version of Firefox for this extension to work as there's no such feature know as Collections on the stable version.

**Comment by fregante** [comment]
Can you take a screenshot of one of the extensions listed in https://addons.mozilla.org/en-US/android/? Similar to your first screenshot above. Are they installable?

**Comment by scrazzz** [comment]
Yes, all plugins in that link are installable.
![Screenshot](https://user-images.githubusercontent.com/70033559/220531342-09ca0396-57f0-40bf-bcca-a8d9339f67bf.jpg)

**Comment by scrazzz** [comment]
You actually don't have to go to https://addons.mozilla.org/en-US/android to install the extension. There's a dedicated Add-ons section in the settings that lets you install it.

![Screenshot](https://user-images.githubusercontent.com/70033559/220531709-4cc49f5c-345a-4270-8578-e82f44c6dafa.jpg)

**Comment by fregante** [comment]
I don't know what to do, I already marked the extension as compatible. You'll probably have to ask on a Mozilla forum where they know why it's happening.

**Comment by scrazzz** [comment]
I've managed to install the extension on FF Nightly (Android), it was a bit hacky.

But it doesn't seem to work. All the [features](https://github.com/refined-github/refined-github#highlights-) the Add-on offers on the README isn't loading/available.

**Comment by fregante** [comment]
I don’t think anyone here uses Firefox for Android so unfortunately I can't help you there. If you do find out how to properly enable it, let us know.

The extension works on Firefox for desktop and is set to be installable on Android, I think that's all I can do. 

On Safari it must be enabled on specific websites after being installed, so it might be similar there. I suggest asking on a Firefox Android group or subreddit.

**Comment by bew** [comment]
Hello, searching `github refined` does yield any result:
https://addons.mozilla.org/en-US/android/search/?q=github%20refined

Could you re-open this issue or should I make a new one?

**Comment by bew** [comment]
Works now, I can install it and it works 👌

How do want to support the mobile version of the website?
For example I immediately noticed the UI of the notifications page isn't great on mobile, where the constrained available space isn't used very well, pushing the title to the right even though there's not much space..

<details>
<summary>See screenshots</summary>

With Refined Github:
![Screenshot_20240211-043210](https://github.com/refined-github/refined-github/assets/9730330/e5509022-dc05-46a7-832a-3d8d3d3b56e8)

Without Refined Github:
![Screenshot_20240211-043317](https://github.com/refined-github/refined-github/assets/9730330/ac235af6-0f73-4f2a-9232-8f097f68ccf9)
👉 Notice how the space is much better used here 👀

</details>

Do you want me to make separate issue for this and other things I notice on the mobile version?

**Comment by fregante** [comment]
Thank you for reporting that!

Yes you can open dedicated issues, but only if the issue also appears on Firefox when you make the window smaller. If not, it should be reported to Firefox

**Comment by niteshbalusu11** [comment]
Doesn't seem to show up on Android again. @fregante

**Comment by fregante** [comment]
I'll have to review the upload script, I suppose I have to mark the upload as compatible every time 🤦‍♂️

**Comment by fregante** [comment]
But I think it must be specified in the manifest: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings

PR welcome

**Comment by niteshbalusu11** [comment]
Works now. Thank you.
