### ISSUE TITLE
`useful-forks` Add button to "fork" dropdown

### ISSUE THREAD

**Issue by theS1LV3R** [refined-github/refined-github#6368]
### Description

Finding/navigating to the button for useful-forks is currently more complicated than it needs to be. I find myself commonly using this feature, having it somewhere easily accessible would be perfect. For example in the dropdown for listing your own forks.

### Screenshot

![image](https://user-images.githubusercontent.com/32072697/220197772-d1fb8fb3-d9fc-4116-ba2c-b00cdd9cbc17.png)

### Example URLs

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
The drop-down is for your own forks, I don’t think this belongs there. 

I'm not sure this feature needs to be that visible considering it's such a rare operation.

**Comment by theS1LV3R** [comment]
Alternatively if possible a configurable amount for it to be shown, I am unsure how possible that would be to do, but would be the ideal solution I think.

**Comment by fregante** [comment]
No options: https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options

**Comment by fregante** [comment]
- GitHub’s new forks page is [good enough now](https://github.com/refined-github/refined-github/issues/6397#issuecomment-1498857930)
- `useful-forks` itself is [being dropped](https://github.com/refined-github/refined-github/pull/6458)
- GitHub’s new global navigation is [hiding the star/forks button](https://github.com/refined-github/refined-github/issues/6456) everywhere except on the Code tab, which already includes a link to the forks
- plus my previous comments
