### ISSUE TITLE
🚀 Shortcut for naviagting to commits list

### ISSUE THREAD

**Issue by jd-solanki** [refined-github/refined-github#6372]
### Description

I have raised the [issue](https://github.com/refined-github/refined-github/issues/6371) regarding `g + 2` isn't working but later found that it was for PR review and not for the whole repo. I regularly use `g + r` and often I also go to the commits (list) of repos but unfortunately there isn't any shortcut to navigate to the commits list.

### Screenshot

N/A

---

Steps:
1. Go to any repo
2. Hit the shortcut we assign like `g + l`
3. It should navigate to commits list

### Example URLs

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
`more-dropdown` already adds a link in the repo navigation's dropdown. I don’t think we need to add further shortcuts
