### ISSUE TITLE
Git Notes support?

### ISSUE THREAD

**Issue by pastelmind** [refined-github/refined-github#6373]
### Description

Git has an underadvertised feature called [git-notes](https://git-scm.com/docs/git-notes). It's a pretty old feature that [GitHub used to support, but not anymore since 2014.](https://github.blog/2010-08-25-git-notes-display/)

Would it be possible to...

1. Show notes for each commit, by pulling them from GitHub via some API?
    - Since git notes are just blobs under special branches, they should be retrievable via Git checkout
2. ...or, if (1) turns out to be infeasible, perhaps a button that launches a "git notes browser" panel?

### Example URLs

https://github.com/refined-github/refined-github/commit/60ac04e85cdb0c597e90d3d314ad6fb4c1fe4d8d

Visiting a commit hash URL _could_ show the note under the regular commit comments, just before the code.

**Comment by fregante** [comment]
It doesn't seem to be practical, possible and/or common enough to be included in Refined GitHub unfortunately 

https://stackoverflow.com/a/71589325
