### ISSUE TITLE
Add a filter on notification screen to easily selected merged|closed|draft|opened Pull Requests

### ISSUE THREAD

**Issue by welcoMattic** [refined-github/refined-github#6377]
### Description

As maintainer of popular repository, it's quite common I need to select all merged|closed pull requests on my notification screen to mark those as "done".

I have to do it manually, which is pretty annoying.

What about adding a filter on pull request status, and even for issues?

### Screenshot

![image](https://user-images.githubusercontent.com/773875/220641559-a7a13ffb-3a1e-4236-ab2a-e87b8d92da2e.png)

### Example URLs

As notification screen is per user, I can't provide a link. The screenshot talk for itself

**Comment by fregante** [comment]
We already do, did you install Refined GitHub?


![](https://user-images.githubusercontent.com/1402241/152119039-4ea8333f-a744-4106-b56f-cf09f50678be.gif)

**Comment by welcoMattic** [comment]
Missed it sorry. Thanks for your answer :+1:
