### ISSUE TITLE
Hide diffs with less than x lines in PR files or commit view

### ISSUE THREAD

**Issue by janpio** [refined-github/refined-github#6388]
### Description

In massive PRs and commits, it would often be helpful to be able to "filter down" to relevant files even more than already possible by default on GitHub. Often one of those "relevance criteria" is the size of the diff per file, measured via the lines affected in the diff:

<img width="86" alt="image" src="https://user-images.githubusercontent.com/183673/221162862-effc3a3d-dfec-4794-a096-35bdc4075ec9.png">
<img width="113" alt="image" src="https://user-images.githubusercontent.com/183673/221162926-9160b0b7-0c19-4d4e-b2ff-94022933bee8.png">

The 2 line change is just some plumbing change affecting hundreds of files, while the bigger ones are outliers worth reviewing.

In my concrete case, only ~30 of the files actually have relevant changes, all the rest is "noise":

<img width="376" alt="image" src="https://user-images.githubusercontent.com/183673/221163292-bc8e85a1-4848-4394-8cb8-c7436c64783d.png">

It would be amazing if Refined GitHub would add some UI to automatically hide the files that only affect less than x lines.

### Example URLs

https://github.com/refined-github/refined-github/pull/6384/files
https://github.com/refined-github/refined-github/pull/6384/commits/d4e863a5b6cbc194ddbf7c3792ffd85cb74f0c28

**Comment by fregante** [comment]
Considering you should probably still review small changes, I'm not sure how much it helps in practice. Something you can do is scroll past them and then use shift-click to mark them all at once: `batch-mark-files-as-viewed`

We have a request open to "mark identical files as viewed", which may help in some cases (e.g. when you rename a file and all the imports are updated)

- https://github.com/refined-github/refined-github/issues/3045

**Comment by janpio** [comment]
Yes, ultimately all of them will be looked at - using for example `batch-mark-files-as-viewed`. I see this feature request similar to the `File filter` dropdown that lets me filter by file extension to only look at the relevant files first so I can work through them in a structured way.

**Comment by kidonng** [comment]
While this seems more actionable than #3045, how do we draw the lines? Config is not welcomed yet decide on some arbitrary number is just as bad.

Looking at the diff size and decide for oneself remains the best though unfortunate solution.

**Comment by janpio** [comment]
I would be happy to once take a look at the files of the PR, and then input a number myself. Similar to how I decide which files to hide.

**Comment by kidonng** [comment]
Made a simple bookmarklet:

```js
javascript:(() => { const n = Number(prompt('Hide files with diff size less than number:')); for (const diff of document.querySelectorAll('.diffstat')) { if (Number(diff.textContent) <= n) diff.closest('.file-info').querySelector('[aria-expanded="true"]')?.click() }})()
```

**Comment by kidonng** [comment]
Theoretically we can provide an input + button (possibly hidden in a dropdown) to do this, but it belongs to nowhere being so niche.

Until more people asked for this _and_ proposed a nice solution, use the bookmarklet.
