### ISSUE TITLE
Recently merged filter

### ISSUE THREAD

**Issue by jerone** [refined-github/refined-github#6389]
### Description

I would like an pull request list filter for most recently **merged**.

### Example URLs

https://github.com/vmware-clarity/ng-clarity/pulls?q=is%3Apr+is%3Amerged

The list is not sorted on recently merged. I don't know what the default sorting is (id I guess).

![image](https://user-images.githubusercontent.com/55841/221351817-e191e567-32bd-4699-adf0-ede9e6af45ad.png)

This list is sorted on most recently **changed** (which is not the same as **merged**):
https://github.com/vmware-clarity/ng-clarity/pulls?q=is%3Apr+is%3Amerged+sort%3Aupdated-desc

![image](https://user-images.githubusercontent.com/55841/221351898-8aea63a6-9240-41a8-8dde-b24723f0e3ec.png)

**Comment by fregante** [comment]
Does GitHub offer that sort unfortunately https://docs.github.com/en/enterprise-server@3.6/search-github/getting-started-with-searching-on-github/sorting-search-results

Hacking into GitHub's servers to add this feature is out of scope for Refined GitHub 😃

**Comment by jerone** [comment]
It is kinda possible, but very limited: https://github.com/refined-github/refined-github/pulse#merged-pull-requests

Don't know if that component can be reused...

**Comment by jerone** [comment]
Anyways, I've up-voted: https://github.com/orgs/community/discussions/30073

**Comment by fregante** [comment]
How would Refined GitHub go about reusing that? How would it differ from just opening that page? What kind of integration are you thinking of exactly? Because none of what in thinking is possible/practical within the context of Refined GitHub 😅
