### ISSUE TITLE
Edit button shows even if issue is locked

### ISSUE THREAD

**Issue by aaronliu0130** [refined-github/refined-github#6390]
### Description

The edit icon appears even if the issue is locked against you.

### How to replicate the issue + URL

![Animation](https://user-images.githubusercontent.com/11874211/221381766-8a307429-6552-446a-81d7-a96d88820f9a.gif)
I replicated this at https://github.com/Hex-Dragon/PCL2/issues/137 , but y'all didn't comment there before the issue was locked, so y'all won't be able to replicate this unless y'all find a locked issue y'all commented in. (why did I use `y'all`)
1. Comment
2. Get repo collaborator to lock issue
3. Use the "edit" icon

### Extension version

23.2.20

### Browser(s) used

Waterfox G5.1.2 (64-bit)

**Comment by fregante** [comment]
Thank you for the issue. I'll fix this in https://github.com/refined-github/refined-github/pull/6381
