### ISSUE TITLE
Support git blame on rendered markdown

### ISSUE THREAD

**Issue by devnoname120** [refined-github/refined-github#6393]
### Description

This would be helpful when I notice an unexpected line while reading the rendered markdown. If I click on the `Blame` button then I'm switched to the code mode. It breaks the flow as I need to find the position of the unexpected line again, which is made hard by the fact that it's hard to visually navigate in markdown code compared to rendered markdown.

### Example URLs

https://github.com/qwerty-fr/qwerty-fr/blame/master/README.md

**Comment by fregante** [comment]
There's no easy way to match the DOM to a line in Markdown, especially because one Markdown line could have several source lines, each of which could have its own commit. 

Unfortunately this isn't the kind of complexity Refined GitHub can tackle.
