### ISSUE TITLE
Drop `useful-forks`?

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6397]
So they rolled out a new forks page, finally: https://github.blog/changelog/2023-02-24-new-forks-page-view/

Unfortunately [it doesn't yet catch forks of forks](https://github.com/community/community/discussions/40968#discussioncomment-5166009).

<table>
<tr>
	<th><a href="https://github.com/EsotericSoftware/kryonet/forks">Native
	<th><code><a href="https://useful-forks.github.io/?repo=EsotericSoftware/kryonet">useful-forks
<tr>
	<td><img width="875" alt="Screenshot 4" src="https://user-images.githubusercontent.com/1402241/222134160-e410a7fd-0f91-47ed-aab9-69499aca2331.png">
	<td valign=top><img width="763" alt="Screenshot 3" src="https://user-images.githubusercontent.com/1402241/222134184-91657b26-0e92-423c-9e8c-102ded449a27.png">
</table>

**Comment by fregante** [comment]
At a minimum, the feature should be updated because it's missing from the new view. I think it should add a link or banner at the bottom

**Comment by zoey-on-github** [comment]
i think we should remove the useful-forks button because as time goes on an on the useful forks website will just become more and more outdated. github's native feature already has sorting by stars, which was one of the main things i looked at when finding useful forks

**Comment by KaKi87** [comment]
> the useful forks website will just become more and more outdated. github's native feature already has sorting by stars

I disagree, as the most imortant feature of *Useful Forks* is actually the *ahead* counter.

**Comment by fregante** [comment]
True. That's something you could ask to GitHub too since they're actively working on it: https://github.com/orgs/community/discussions/40968

**Comment by kidonng** [comment]
I don't see this immediately render the feature useless as an userspace solution tends to be more flexible, as pointed out.

But I'm curious, are there many well-maintained forks of forks that are less well-known (and thus benefits from `useful-forks`)? I feel if you are digging that deep you might as well search for third-party tools.

**Comment by KaKi87** [comment]
> are there many well-maintained forks of forks that are less well-known

Yes, Useful Forks allowed me to find some, several times.

> if you are digging that deep you might as well search for third-party tools

Of course, but using a fork is easier when you're already depending on the original one, especially if it has features that alternatives don't have.

**Comment by fregante** [comment]
I think the native feature has become _good enough_ now as it finds forks of forks and hides all the noise (note, "fork of forks" are not enabled by default):


https://github.com/EsotericSoftware/kryonet/forks?include=active%2Cnetwork&page=1&period=2y&sort_by=stargazer_counts

<img width="917" alt="Screenshot 7" src="https://user-images.githubusercontent.com/1402241/230353251-2f1e17dd-a2ae-45b2-9c28-4e9fc0b1365c.png">

**Comment by fregante** [comment]
The resolution for this feature:

- drop `useful-forks`
- add new `fork-notice` feature just for the "Check out the forks" banner

https://github.com/refined-github/refined-github/blob/c470d8103ebc9aa02735d4c0cb72d543333c5c06/source/features/useful-forks.tsx#L38-L52

Those who continue to prefer `useful-forks`, can install its extension: https://github.com/useful-forks/useful-forks.github.io#chrome-extension
