### ISSUE TITLE
Extra/Improved repository stats

### ISSUE THREAD

**Issue by couleurm** [refined-github/refined-github#6400]
### Description

Knowing what languages are used are nice, but it's also interesting to see file extensions based

let's say a repo has a shit ton of json files, or has a lot of docs and thus lots of .md files

![image](https://user-images.githubusercontent.com/82747632/222242980-b7cab5b1-d05d-40d3-90f0-383b9e4bfe0a.png)

### Example URLs

N/A, all repos

**Comment by fregante** [comment]
It's not something GitHub exposes, we'd have to query the entire list of files in the repo.
