### ISSUE TITLE
Use GitHub style in options

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6402]
- Follows #6384 

I think it makes sense to go full circle and just copy GitHub’s own boxed style for the sections:

<img width="566" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/222357910-73678267-4098-42d4-b38e-ab58a0d2ef45.png">

Notes:

- to simplify things, we should just use translucent colors instead of strictly matching GitHub’s palette, so that we don't have to mess with color-scheme media queries
- it would be interesting to also use octicons instead of emojis

**Comment by fregante** [comment]
Also we should use `scrollIntoView` on expansion, so that the user never has to scroll down:

https://user-images.githubusercontent.com/1402241/222359080-68d1c451-01c4-4812-9bdb-06042e879174.mov

**Comment by g-plane** [comment]
How about adopting [the official component library](https://primer.style/css/)?

**Comment by fregante** [comment]
No I want to keep this lightweight and easy to maintain. The changes described here would only add less than 10 lines of CSS + the icons

**Comment by fregante** [comment]
I changed my mind, it doesn't fit well. Also this is more important/urgent:

- https://github.com/fregante/webext-base-css/issues/14
