### ISSUE TITLE
Custom CSS in settings is too small

### ISSUE THREAD

**Issue by jerone** [refined-github/refined-github#6404]
### Description

Probably an Firefox issue.

### How to replicate the issue + URL

![image](https://user-images.githubusercontent.com/55841/222700559-d57f69ef-97ee-4bfe-a2f0-556b004310ba.png)

### Extension version

23.3.2

### Browser(s) used

Firefox

**Comment by fregante** [comment]
Due to https://github.com/fregante/fit-textarea/issues/8
