### ISSUE TITLE
`useful-forks` does not show on the new forks page

### ISSUE THREAD

**Issue by Aholicknight** [refined-github/refined-github#6405]
### Description

![msedge_20230315_zZ0evV1kkd](https://user-images.githubusercontent.com/7843719/222928848-1b399959-d42b-4ebe-a8e0-da06c897a78e.png)

Find useful forks button no longer appears on the new fork page.

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/forks

### Extension version

23.3.2

### Browser(s) used

Microsoft Edge

**Comment by fregante** [comment]
Mentioned in https://github.com/refined-github/refined-github/issues/6397

I'll leave this issue open so it can be fixed in the meanwhile

**Comment by KaKi87** [comment]
In the meantime, [here](https://git.kaki87.net/KaKi87/config/src/commit/2c72652c09764d29acf7f26cf86334ae63bd8f44/ocgpenflpmgnfapjedencafcfakcekcd/Redirector.json#L161)'s a [Redirector](https://github.com/einaregilsson/Redirector) configuration that redirects the new forks page to the old one.

**Comment by fregante** [comment]
You can just disable the beta, as far as I know.

**Comment by KaKi87** [comment]
I keep clicking *switch back to the tree view* but it still gets me to the new page.
