### ISSUE TITLE
`Use this template` shorter title button

### ISSUE THREAD

**Issue by tjx666** [refined-github/refined-github#6412]
### Description

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/224398341-87f14478-4335-4a36-8eff-5e8cb47bd7d0.png">

### Example URLs

https://github.com/tjx666/awesome-vscode-extension-boilerplate/tree/main

**Comment by fregante** [comment]
Related:

- https://github.com/refined-github/refined-github/issues/5071

I'm not sure it can actually be shortened to an icon and Refined GitHub doesn't have this issue. Shortening "Open in Web IDE" would be a better choice overall

**Comment by tjx666** [comment]
@fregante  I disable extension `Open in Web IDE` and this issue still exits

**Comment by fregante** [comment]
> Refined GitHub doesn't have this issue

I'm referring to the spacing issue. We add the `latest-tag-button` and save some space on that line, so there's enough space there as far as Refined GitHub is concerned.
