### ISSUE TITLE
`download-folder-button` duplicated

### ISSUE THREAD

**Issue by cuire** [refined-github/refined-github#6414]
### Steps to reproduce:

1. Open folder
2. Open file
3. Open folder again

![ezgif-1-c1e5a66abb](https://user-images.githubusercontent.com/81014305/224497287-c71f0f65-1cf5-4a75-9e08-ee4935f7f967.gif)

The bug happens after clearing extension cache. 

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/tree/main/source/features

### Extension version

23.3.2

### Browser(s) used

Firefox 110

**Comment by fregante** [comment]
`+` selectors are dangerous in `observeSelector`:

https://github.com/refined-github/refined-github/blob/598ece93f152b5fab1785fe7c98fbfbb5717609b/source/features/download-folder-button.tsx#L28


I think the fix here would be to change `+` to `~` but I'm not too sure.

**Comment by cuire** [comment]
I forgot to mention that the problem is only with the new code view. 

I dont feature's lifecycle well, but here are my guesses.

Using professional debuging tools 😅, I found that moving from repo's root to any folder makes the extension think that we are still in root. But when I go back to root and to folder again now extension can detect that we are not in the root.
```ts
const setupPageLoad = async (id: FeatureID, config: InternalRunConfig): Promise<void> => {
	const {asLongAs, include, exclude, init, additionalListeners, onlyAdditionalListeners} = config;

	if (id === 'download-folder-button') {
		console.log('👹', {
			isRepoRoot: pageDetect.isRepoRoot(),
			isSingleFile: pageDetect.isSingleFile(),
			},
			Date.now(),
		)
	}
	...
}
```


Next problem is that, navigation inside code view doesn't call `turbo:render` event since it all happens inside react. And I think this causes duplication.

I recorded a video about everything that is said, hope this helps
![ezgif-1-488d46249f](https://user-images.githubusercontent.com/81014305/224506935-32e78d92-150c-4609-b241-5b417aa958df.gif)

**Comment by 134130** [comment]
Thanks. The Issue reproducing route is this.

1. Enter a file tree of repository.
2. Enter some file of the tree.
3. Pop to back page (I don't know the correct word of this)
4. Enter some file of the tree.

As @cuire said, this situation doesn't call the `turbo:render` event but `soft-nav:render`

But this is derived new problem for debugging "duplicating `download-folder-button`"

**Comment by fregante** [comment]
@134130 Refer to my last comment, the fix is probably one line. The generic AJAX issue is tracked elsewhere.

**Comment by 134130** [comment]
@fregante I already fixed and writing PR description.
The `[title="More options"]` is only calling `[aria-label="Add file"] + details` what you mentioned is never calling.

I also agree the AJAX issue should be tracked elsewhere. But I wrote since There was report and I found a reason/solution.

**Comment by fregante** [comment]
I'll send a fix

**Comment by fregante** [comment]
Also newly affected:

- #6578

**Comment by Simon-He95** [comment]
<img width="736" alt="image" src="https://github.com/refined-github/refined-github/assets/57086651/6584e23b-6997-43de-84bd-d132d0c269fa">

Can we do this to resolve it?

**Comment by fregante** [comment]
A PR is already open. Posting screenshots of code isn’t really helpful because I don’t know what “this” refers to
