### ISSUE TITLE
About table input

### ISSUE THREAD

**Issue by KaKi87** [refined-github/refined-github#6417]
> No options allowed:
> - https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options

(https://github.com/refined-github/refined-github/pull/3598#issuecomment-1471398425)

@fregante How about having two table input features, including the existing HTML one enabled by default, and a new Markdown one disabled by default ?

> `table-input` will stay here however as it's vastly superior in every way

Exactly, which is why an identical button outputting Markdown would be amazing.

Thanks

**Comment by fregante** [comment]
This was already discussed, the answer remains no, especially now that there's a native button.

**Comment by fregante** [comment]
> and a new Markdown one disabled by default ?

Please read https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22 in its entirety

**Comment by KaKi87** [comment]
> no, especially now that there's a native button

The native button doesn't allow setting row/column count as easily as Refined's.

> Please read https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22 in its entirety

1. AFAIK, there is no extension/userscript providing this feature ;
2. Markdown makes more sense than HTML as default, as more people know Markdown than HTML, and Markdown requires a less amount of, easier to remember, and easier to write (especially on mobile) characters to add rows/columns to a table ;
3. It wouldn't require options ;
4. It wouldn't require more maintainance than the existing feature ;
5. It wouldn't require an external server ;
6. It wouldn't require any traffic ;
7. It doesn't enhance "Projects".
