### ISSUE TITLE
Bad Fedora COPR status badge

### ISSUE THREAD

**Issue by surfzoid** [refined-github/refined-github#6419]
### Description

My project is :
https://github.com/surfzoid/QtVsPlayer
Using COPR to build RPM
integrate badge staus in README.md, with refined enable, status badge is blocked on "in progress" since few days, without refined, status is ok.
The COPR URL https://copr.fedorainfracloud.org/coprs/surfzoid/QtVsPlayer/package/QtVsPlayer/

### How to replicate the issue + URL

open https://github.com/surfzoid/QtVsPlayer with and without refined enable.

### Extension version

23.3.2

### Browser(s) used

google chrome

**Comment by fregante** [comment]
Please include a screenshot, I don't know which badge you're referring to. 

Here I do see it in progress, but because it is. In red it's the native one and in green we just copy that one. 

![image](https://user-images.githubusercontent.com/1402241/226090379-15f20a74-ff64-4460-b7a0-1f7e89998fb2.jpeg)

Note that the icon next to the repo may not be refreshed on the fly so if you open a tab while it's in progress, it may stay that way until you close the tab. Reloading the page fixes it, we don't cache it

**Comment by surfzoid** [comment]
i spoken about COPR badge in the readme.md file, not the github badge,
![image](https://user-images.githubusercontent.com/20399920/226090583-c1f9122d-8302-4037-a5bf-26165070afe1.png)

**Comment by fregante** [comment]
This is not a Refined GitHub issue, I can reproduce it on a fresh browser without login and without extensions.

<img width="699" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/226092171-da590244-a3b4-4ddf-8cb0-660889b15a07.png">

**Comment by surfzoid** [comment]
yes :"at this time i m building on copr :" , it will finish soon, see status of build : https://copr.fedorainfracloud.org/coprs/surfzoid/QtVsPlayer/build/5676880/

**Comment by surfzoid** [comment]
well, openeuler build is abnormally very slow, perhaps we need to wait few hours in fact!

**Comment by surfzoid** [comment]
Anyway, there is something wrong, opening the image badge display the good status : https://copr.fedorainfracloud.org/coprs/surfzoid/QtVsPlayer/package/QtVsPlayer/status_image/last_build.png

But the one of the github page display "Failed", also after refresh and restart google chrome

**Comment by surfzoid** [comment]
Ok, we are now in a correct state to reopen the bug, with or without refined extension, the badge display "failed" : https://github.com/surfzoid/QtVsPlayer

on COPR	side, all builds finish with success : https://copr.fedorainfracloud.org/coprs/surfzoid/QtVsPlayer/build/5676880/

**Comment by surfzoid** [comment]
but, again, direct link to the png, is okay : https://copr.fedorainfracloud.org/coprs/surfzoid/QtVsPlayer/package/QtVsPlayer/status_image/last_build.png

**Comment by fregante** [comment]
> with or without refined extension, the badge display "failed"

Correct. So it's not Refined GitHub.
