### ISSUE TITLE
"Color-coded review counts" seems to be broken

### ISSUE THREAD

**Issue by krlmlr** [refined-github/refined-github#6422]
### Description

I had approved some of the PRs in a repo, now I'm missing the approvals in the PR list. This has worked before. Is it just on my system?

I notice a gap that appears between "by <username>" and "updated xx minutes ago" for less than one second, then the gap disappears.

### How to replicate the issue + URL

https://github.com/tidyverse/design/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

### Extension version

23.3.2

### Browser(s) used

Firefox 111.0, macOS aarch64

**Comment by fregante** [comment]
I think classes in the PR list changed recently. Related:

- #6421

**Comment by fregante** [comment]
I don't see any issues here: https://github.com/refined-github/sandbox/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+review

<img width="721" alt="Screenshot 4" src="https://user-images.githubusercontent.com/1402241/226278145-ffb97140-6cea-4cda-8ee5-00e52609e7f8.png">

It's up to GitHub to display that data, we just expose the label via CSS.

**Comment by krlmlr** [comment]
Thanks, confirmed. I see it in your repo, not in mine. 🤷

**Comment by fregante** [comment]
You're repo does not have any "review requested" nor approved PRs

**Comment by krlmlr** [comment]
https://github.com/tidyverse/design/pull/116 has a review, but no review request. There are three others.

**Comment by fregante** [comment]
Reviews don't appear in the list. They must be approvals or change requests. The feature is called `pr-approvals-count`

**Comment by krlmlr** [comment]
Correction: https://github.com/tidyverse/design/pull/116 doesn't have a review request. But I reviewed and approved, I pushed the green "Approve" button. There are three other PRs that I handled the same way.

I only find `pr-approvals-count.css` in this repo. I suspect this means that this feature only adds color to existing labels. I wonder if we could extend that to do our own querying, or if it's worth taking this to GitHub.

**Comment by fregante** [comment]
You're not a member/owner/contributor, your approvals don't count for GitHub:

<img width="511" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/226518627-5c67d6a2-afeb-460f-a21f-7bfc923fb648.png">

They must be green.

This is not something I intend to change and neither does GitHub
