### ISSUE TITLE
Extension marked as incompatible with Kiwi Browser

### ISSUE THREAD

**Issue by KaKi87** [refined-github/refined-github#6423]
### Description

The extension used to be installable on Kiwi Browser from the Chrome Web Store.

Now, the button says `/!\ Incompatible`.

Yet, if I download the extension using some "CRX downloader", it still works perfectly.

So, this is just a matter of marking it as compatible again.

Thanks

### How to replicate the issue + URL

https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf

### Extension version

23.3.2

### Browser(s) used

Kiwi Browser

**Comment by fregante** [comment]
Since I don't know what Kiwi browser is, you'll have to ask them why it says unsupported. 

It's likely because of the minimum chrome version specified here:

https://github.com/refined-github/refined-github/blob/main/source/manifest.json

**Comment by KaKi87** [comment]
[Kiwi Browser](https://github.com/kiwibrowser/src.next) is the only open source Chromium-based browser for Android that supports extensions.
It's current Chromium version is `107.0.5304.74`.
And as mentioned, Refined works fine on it, only the Chrome Web Store says it doesn't.
Thanks
