### ISSUE TITLE
`collapsible-content-button` is in "Slash commands" feature

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#6426]
### Description

Didn't see an issue about this, so I opened one.

Reference: https://docs.github.com/en/issues/tracking-your-work-with-issues/about-slash-commands#using-slash-commands

You can tell it's quite beta-y when it has obvious funky styles:

<img width="341" alt="截屏2023-03-20 22 41 14" src="https://user-images.githubusercontent.com/44045911/226374578-4912a496-c477-49b8-89f9-2ac881892877.png">

EDIT: noticed some differences, GitHub doesn't surround selected text like `collapsible-content-button` (would be surprising if they managed to do).

### Example URLs

Here

Gotcha: the feature doesn't seem to be enabled on issue templates yet (I'm not seeing it as I'm writing this issue)

**Comment by fregante** [comment]
I'm not a fan of their feature in the current state due to the ridiculous loaders, but it might be good enough in this case. 

The only advantage of ours would be that it works in one click around selected content (which could actually be a good-enough reason to keep it)

Their feature also has table-input but it's even worse UX. See https://github.com/refined-github/refined-github/pull/3598#issuecomment-1471398425

**Comment by fregante** [comment]
I also want to add that we've been burned by removing features while GitHub implemented theirs in beta, like https://github.com/refined-github/refined-github/pull/1611

**Comment by kidonng** [comment]
> The only advantage of ours would be that it works in one click around selected content (which could actually be a good-enough reason to keep it)

[Suggested that](https://github.com/orgs/community/discussions/40299#discussioncomment-5537258) to GitHub's public feedback.

> I also want to add that we've been burned by removing features while GitHub implemented theirs in beta, like #1611

I'm surprised I kinda remember that (Refined) GitHub feature. I also remember GitHub briefly added a `/sparkle` feature last year.

But I think this one is more practical, less problematic and isn't going away.

**Comment by fregante** [comment]
How can slash comments act on selected text? It would be a different feature than what they're implementing (typing commands in the current field vs typing commands in an overlay, for example). I don't see them making that change.

**Comment by kidonng** [comment]
I realized that right after I commented lol

But it won't hurt to mention it even if there's little chance they will accept. I feel saved replies and slash commands are doing very similar things in slightly different ways, maybe they will be merged someday, so it's not impossible.

**Comment by fregante** [comment]
I don’t like slash commands, too slow and it outputs extra `<p>`. We can reconsider when the feature is instant and clean
