### ISSUE TITLE
Is there any feature like Visual Studio Code inline blame?

### ISSUE THREAD

**Issue by iamandrewluca** [refined-github/refined-github#6429]
I would like to suggest, but I want to know first if there is something similar to the Visual Studio Code inline blame feature in Refined GitHub.

Is someone interested in such a feature, to show git blame on the current focused line?

<img width="907" alt="image" src="https://user-images.githubusercontent.com/1881266/226875523-ba90e497-0782-4370-9e17-497496b5b443.png">

**Comment by iamandrewluca** [comment]
Thanks!

**Comment by kidonng** [comment]
Sourcegraph have this: https://sourcegraph.com/github.com/refined-github/refined-github/-/blob/source/refined-github.ts

<img width="927" alt="image" src="https://user-images.githubusercontent.com/44045911/232184722-5f7e792f-9194-4a59-9f1d-65f77dc26656.png">

(For private repo you need to self-host obviosuly)
