### ISSUE TITLE
Add a button to expand all the files in PR (on the files view)

### ISSUE THREAD

**Issue by vvscode** [refined-github/refined-github#6430]
### Description

Example scenario:

Once the file is reviewed it's marked as `viewed` (and collapsed automatically). And if in some of the next files I do decide to make a search (by method name for example) browser doesn't do that in collapsed files. It's nice to have a way to expand them all together (not one by one)

### Example URLs

https://github.com/refined-github/refined-github/pull/6427/files

**Comment by fregante** [comment]
It already exists: `toggle-all-with-alt`

You can alt-click the file header or the "viewed" checkbox (if you want to mark all as viewed)
