### ISSUE TITLE
Quick view/edit stars lists

### ISSUE THREAD

**Issue by jerone** [refined-github/refined-github#6431]
### Description

Currently it requires multiple actions to find the page where you can view and edit your stars lists. 
I even had to Google where the list was. 
_Hint; they are under your personal account stars tab._

It would be useful to have a link/icon inside the stars modal, to directly go to your personal overview of lists. From there you can view and manage your lists.

Suggestions where to add link/icon (or maybe make the modal title linkable):
![image](https://user-images.githubusercontent.com/55841/227733642-be636cc2-8916-43e2-ac52-a0697c5db83f.png)

_I know lists are still in beta. But it is publicly available since [December 2021](https://github.blog/changelog/2021-12-09-lists-are-now-available-as-a-public-beta/). Plus, there's even [documentation](https://docs.github.com/en/get-started/exploring-projects-on-github/saving-repositories-with-stars#organizing-starred-repositories-with-lists) for it._

### Example URLs

Any repository.

https://github.com/refined-github/refined-github/

**Comment by fregante** [comment]
> to directly go to your personal overview of lists

Can you provide the exact URL you want this link to point to?

**Comment by jerone** [comment]
> Can you provide the exact URL you want this link to point to?

`https://github.com/USERNAME?tab=stars`

https://github.com/jerone?tab=stars

**Comment by fregante** [comment]
It exists 🎉 

![image](https://user-images.githubusercontent.com/1402241/227887945-297128dc-b1e2-4c8d-b086-67693f012de7.jpeg)
