### ISSUE TITLE
404 when loading the extension's CSS hotfix

### ISSUE THREAD

**Issue by igorskyflyer** [refined-github/refined-github#6433]
### Description

I have been getting a 404 error when the extension is trying to load its stylesheet, see below:

![css](https://user-images.githubusercontent.com/20957750/227966248-4d9beff0-f219-4da6-9c1a-5f0a6c010228.PNG)

It happens even after clearing the cache.

### How to replicate the issue + URL

It happens on any of my GitHub profile's pages, e.g. [igorskyflyer](https://github.com/igorskyflyer).

### Extension version

23.3.20

### Browser(s) used

Chrome 111.0.5563.111 (64-bit)

**Comment by fregante** [comment]
It's expected, can be ignored. It's for firefox only

**Comment by fregante** [comment]
We can move the fetch to the background page instead. The code can be copied from https://github.com/npmhub/npmhub/blob/e5fc850f5c91d6aad0adab14ec0cd46ce662c2c9/source/background.js#L32-L45

Replacing this call:

https://github.com/refined-github/refined-github/blob/3eb69778b29b87b02a4ab2ddda4d8a302307f759/source/helpers/hotfix.tsx#L25-L26

with 

```js
const {content} = await chromeP.runtime.sendMessage({fetchPackageInfo: 'the url'});
```
