### ISSUE TITLE
Ability to add a line length ruler

### ISSUE THREAD

**Issue by bsrz** [refined-github/refined-github#6434]
### Description

See title, also see image:
![](https://user-images.githubusercontent.com/1077441/228012551-c7764978-1cb6-4e33-ad47-8562f7296134.png)

### Example URLs

All code files view

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/1484

**Comment by bsrz** [comment]
Sadly, that solution doesn't work. Perhaps it's caused by the GitHub dark theme.
A nice clean line would be much better than an overly subtle gradient, that I have to manually add through custom CSS.
