### ISSUE TITLE
Show all packages for the repository

### ISSUE THREAD

**Issue by ksinghal** [refined-github/refined-github#6444]
### Description

In the right sidebar of a repository page, the packages linked to a repository are shown. However, that section is limited to only showing a maximum of 3 packages. You have to then click on "Packages" link in the right sidebar to see all the packages. It would be great if it would just show them all there directly

### Example URLs

https://github.com/Codertocat/hello-world-npm

The right section of the page has a "Packages" section, which shows the area I want to modify

**Comment by fregante** [comment]
This is rather niche so I'm going to pass on this

**Comment by ksinghal** [comment]
Any chance we could have the latest version of the package displayed? I would be happy to help get it implemented
