### ISSUE TITLE
Add a link to the release page of current tag

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#6451]
### Description

Maybe we do not need to restore `tags-dropdown`, since GitHub already has one, we just need a link to the release page:

<img width="308" alt="image" src="https://user-images.githubusercontent.com/44045911/230223311-ed9222b7-0aeb-49e3-9fc7-30103e929030.png">

I know this is more clicks, not on the release page either. But it has benefits too:

- Less code to maintain
- Leverage GitHub features you already know

I have no idea where to put the link though.

- Maybe reuse `releases-tab`? If you are on a tag, it goes to the corresponding release instead of showing all releases
- Next to the branch selector?

### Example URLs

https://github.com/refined-github/refined-github/tree/23.3.31

**Comment by fregante** [comment]
> Maybe reuse releases-tab? If you are on a tag, it goes to the corresponding release instead of showing all releases

That might be confusing or too hidden of a behavior. 

I think we can add a banner above the file list. It's a bit "lazy" but safer than other placements and it works on mobile out of the box:

- if you're on a /tree/ tag, add banner with link to release

As for tags-dropdown, I think it wouldn't be terribly hard to reimplement it as a datalist with an API call.

**Comment by fregante** [comment]
Adding the related PR:

- https://github.com/refined-github/refined-github/pull/6438

**Comment by kidonng** [comment]
#6499 is a more concrete proposal

**Comment by fregante** [comment]
You know what, actually this kind of made sense if you meant adding a link next to each line. I had only thought about a single link.

<img width="336" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/232130761-f407a4c5-2c47-45f8-b1bc-92d56e15db0d.png">

```js
$$('.SelectMenu-item').forEach(a => {
div = document.createElement('div')
a.replaceWith(div)
div.className = 'd-flex'
 tag = document.createElement('a')
tag.className = 'SelectMenu-item'
tag.style.width = '3em'
tag.style.paddingLeft = '1em'
 tag.textContent = '🏷️'
div.append(a, tag)
})
```

The only little **big** problem is that the list is regenerated/cleaned on every scroll, so it will get quite heavy 😰 

I'm posting this but not a good idea to pick this up due to the perf implications

**Comment by kidonng** [comment]
Why mess with DOM manually? You just need to modify the template:

```js
var a = document.createElement('a')
a.href = 'https://github.com/refined-github/refined-github/releases/tag/{{ urlEncodedRefName }}'
a.append(document.querySelector('.octicon-tag').cloneNode(true))
document.querySelector('#tags-menu [data-target="ref-selector.itemTemplate"]').content.firstElementChild.append(a)
```

Rather than potential technical issues, it is more about usability. Branch/tag picker does not focus the current reference automatically, so unless you are on the first page, you need to scroll down or search, which is a lot friction. Makes more sense to have a button/link outside.

**Comment by fregante** [comment]
????

That was demo/console code.

**Comment by kidonng** [comment]
> That was demo/console code

I'm referring to the "perf implications" part, which your demo suggests.

> What template? If you have a way to safely create the elements then this request could be reopened.

`[data-target="ref-selector.itemTemplate"]`, I thought you know it since you [mentioned looking into `ref-selector`](https://github.com//refined-github/refined-github/pull/6438#issue-1647269034) 😅

> * this: link to every tag, regardless of where you are

That's not I mean. The screenshot is to show that "GitHub already has a tag picker"

What I'm suggesting is:

1. You switch to the desired tag with the native picker
2. We add a button that goes from current tag to the corresponding release

That's why I said #6499 is more concrete.

**Comment by fregante** [comment]
> > this: link to every tag, regardless of where you are
> That's not I mean

That's what _I_ mean. It's a new proposal. A new idea. Related to yours only because rereading this issue and seeing your screenshot made me realize that there's another way. 

What we should debate is whether what I described is useful, practical, and efficient.
