### ISSUE TITLE
`repo-avatars` is in "Global navigation update" feature preview

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#6452]
Finally!

<img width="373" alt="image" src="https://user-images.githubusercontent.com/44045911/230225332-d362d773-4883-4e40-901a-1f174798cdbc.png">

To see this:

1. Enable "Global navigation update" feature preview
2. Go to any repository homepage e.g. https://github.com/refined-github/refined-github

**Comment by kidonng** [comment]
Oops, not really. It's only on the homepage. Ideally it should be something like this:

<img width="388" alt="image" src="https://user-images.githubusercontent.com/44045911/230228923-ce9f1a6e-93a7-4855-8fdb-fb9be729d6ba.png">

But then it leaves an awkward blank space below...

**Comment by fregante** [comment]
I don't see what you're talking about, I only see GitHub's own logo. 

Take a screenshot without Refined GitHub

**Comment by kidonng** [comment]
Did you turn on the "Global navigation update" feature preview?

(I probably should have mentioned it in the description as well)

**Comment by fregante** [comment]
Take a screenshot without RGH. I did and I don't see `repo-avatars`

**Comment by kidonng** [comment]
I have double-checked that when I posted this issue. This DOM is certainly not our code either:

<img width="575" alt="image" src="https://user-images.githubusercontent.com/44045911/230309653-db62da52-9473-430b-97e3-6bdb5d43de33.png">

**Comment by fregante** [comment]
In their screenshot I don't see Stripe's logo anywhere, which is what `repo-avatars` is about, right?

![](https://i0.wp.com/user-images.githubusercontent.com/1707375/228928493-1999411b-f215-42f2-bb89-1ba24ce399cd.png?w=960&ssl=1)

**Comment by kidonng** [comment]
That's why I said it is "not really" `repo-avatars`. My second screenshot is a hypothetical one.

**Comment by fregante** [comment]
Let's not make any changes yet because this is likely going to change. The current duplication of the repo name on the Code tab doesn't make much sense. 

My guess is that we're going to keep `repo-avatars` but apply it to the header, exactly as you suggested in their beta discussion. 👌

**Comment by kidonng** [comment]
I'm just proactively posting it here. Many things in the new design doesn't make sense, but the overall layout will likely remain the same, like this one.

**Comment by fregante** [comment]
I think they'll get a lot of pushback. This changes a lot more than it seems. For example all of this information now only appears on `isRepoRoot`:

<img width="851" alt="Screenshot 5" src="https://user-images.githubusercontent.com/1402241/230348792-b2fe9fd6-a491-4430-9f49-300be980cdd1.png">

Exists: https://github.com/fregante/refined-github/tree/avoid-accidental-submissions

Doesn't exist: (in subfolder) https://github.com/fregante/refined-github/tree/avoid-accidental-submissions/.github

**Comment by fregante** [comment]
Cleaned up and moved to https://github.com/refined-github/refined-github/issues/6784
