### ISSUE TITLE
`ci-link` broken on "Global navigation update"

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6454]
### Description

The `public` label is now only shown on the Code tab, consequently `ci-link` is only added there:

<img width="449" alt="Screenshot 1" src="https://user-images.githubusercontent.com/1402241/230338835-efcc16f8-11eb-42e8-af8d-a3ea60657f7c.png">

However the Code tab already has that exact indicator on the "latest commit" widget, so it's useless there.

## Fix suggested

It should be moved to the new header

<img width="301" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/230340535-ba916050-0020-4ba1-9f33-41def7c1d1b3.png">

### How to replicate the issue + URL

On this issue it's missing.

### Extension version

23.3.2

### Browser(s) used

Safari

**Comment by yakov116** [comment]
Should we make a new label called "Global Navigation"?
