### ISSUE TITLE
`quick-new-issue` broken on "Global navigation update"

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6455]
### Description

<img width="267" alt="Screenshot 2" src="https://user-images.githubusercontent.com/1402241/230341134-9cfecb7e-c6a8-4f00-b3aa-282dcfc220cc.png">

```
refined-github.js:3727 📕 0.0.0 → TypeError: Cannot read properties of null (reading 'textContent')
    at Module.isArchivedRepo (refined-github.js:26112:90)
    at isArchivedRepoAsync (refined-github.js:18131:60)
    at async init (refined-github.js:12525:7)
    at async runFeature (refined-github.js:3797:16)
    at async setupPageLoad (refined-github.js:3809:5)
```

### How to replicate the issue + URL

Every page, including this issue

### Extension version

23.3.2, 23.3.31

### Browser(s) used

Safari, Chrome

**Comment by kidonng** [comment]
Side note: this is available in command palette, albeit buried a little deep:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/44045911/230355059-3da0858b-9b68-4d5d-9c6b-78e4d500df56.png">

**Comment by fregante** [comment]
I think it only works if you're on Issues already, which is the same limitation as the native "New issue" button

<img width="866" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/230364373-c8a26a34-4d7e-44f6-b045-e3ef94385ca5.png">

**Comment by fregante** [comment]
Good tip!

I haven't been really using the palette because it varies by context (unlike in text editors) so it always feels awkward when trying to do global actions:

<img width="700" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/230364671-4b9a9856-72f9-45d3-a3f9-0aa76f564477.png">
