### ISSUE TITLE
Review `hasRepoHeader` usage on "Global navigation update"

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6456]
`hasRepoHeader` now no longer guarantees any of this content, which only appears on `isRepoRoot`:

<img width="851" alt="Screenshot 5" src="https://user-images.githubusercontent.com/1402241/230349123-70f45cfc-6389-4070-b5f8-afd971768410.png">

This probably also requires updates in https://github.com/refined-github/github-url-detection

However let's wait until their feature stabilizes.

### Related

- https://github.com/refined-github/refined-github/pull/6378
- https://github.com/refined-github/refined-github/issues/6452#issuecomment-1498834372

**Comment by FloEdelmann** [comment]
The redesign is now live by default for everyone: https://github.blog/changelog/2023-06-15-redesigned-navigation-enabled-for-all-users-beta/
