### ISSUE TITLE
Add separate Markdown file for "Welcome to Refined GitHub!"

### ISSUE THREAD

**Issue by WebSnke** [refined-github/refined-github#6459]
### Description

The ["Welcome to Refined GitHub!"](https://github.com/refined-github/refined-github/issues/3543) is currently just an issue thread. 
I suggest creating a separate Markdown file which would allow contributors to edit and improve it.

### Example URLs

https://github.com/refined-github/refined-github/issues/3543

**Comment by fregante** [comment]
We technically have a wiki for this, but eventually decided against using it. Given it's something that shouldn't really change much, it's best to open a new issue for that if you have any ideas.

**Comment by fregante** [comment]
You already did, if you have any suggestions, you can leave them here 😃
