### ISSUE TITLE
`hide-user-forks` missing from some links

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#6464]
### Description

Both missing in profile nav and profile menu with "Global navigation updates":

<img width="292" alt="image" src="https://user-images.githubusercontent.com/44045911/230560892-1d3d2f3c-6426-4612-b6dc-2fdd9c1a96a6.png">

---

<img width="306" alt="image" src="https://user-images.githubusercontent.com/44045911/230560922-00665a46-42fb-4d8d-b13b-1b2179b27673.png">

### How to replicate the issue + URL

https://github.com/kidonng?tab=repositories

### Extension version

23.3.31

### Browser(s) used

Chrome

**Comment by fregante** [comment]
This is actually not strictly related to the global navigation but your demo link itself right on this issue is broken 😅 because it doesn't have any selectable attributes.

It seems that we should just alter the feature to `observe('[href*="?tab=repositories"]', alterLink)` and then filter out any unrelated links via `!isProfile`

**Comment by fregante** [comment]
It seems that your UI is different from mine too 🤔 

URL: `https://github.com/fregante?tab=repositories`

<img width="349" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/230579106-b9506563-c912-4d20-8b5b-5efbedd1dd51.png">

**Comment by kidonng** [comment]
I.. will add a divider to make it clear

**Comment by kidonng** [comment]
> but your demo link itself right on this issue is broken

Hmm have it ever worked? Because the feature never targeted user content (comments etc.).

> It seems that we should just alter the feature to `observe('[href*="?tab=repositories"]', alterLink)` and then filter out any unrelated links via `!isProfile`

There's a slight issue with `isProfile` in that it solely relies on `github-reserved-names` to avoid false positives. But I'm probably worrying too much because:

- Adding `&type=source` is just noop in most pages
- If we do find any false positive we can report to `github-reserved-names`
