### ISSUE TITLE
Broken review list styles in pull requests

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#6467]
### Description

<img width="906" alt="image" src="https://user-images.githubusercontent.com/44045911/230596894-33d49b89-b051-43ec-a943-6ac760da760a.png">

### How to replicate the issue + URL

https://github.com//refined-github/refined-github/pull/6466

### Extension version

23.3.31

### Browser(s) used

Chrome

**Comment by kidonng** [comment]
Caused by `clean-checks-list`

Just need a narrower selector

**Comment by fregante** [comment]
Hotfixed in 23.3.2 and 23.3.31
