### ISSUE TITLE
Support jumping to a date (range) in commits page

### ISSUE THREAD

**Issue by xxchan** [refined-github/refined-github#6471]
### Description

Basically it's
```
https://github.com/refined-github/refined-github/commits/main?since=2022-12-01&until=2023-01-01
```

### Example URLs

```
https://github.com/refined-github/refined-github/commits/main
```

**Comment by fregante** [comment]
Technically GitHub supports this, it's what we use in `comments-time-machine-links`

This would be a single `input type=date` element that probably autosubmits on change, but:

- how many would find this useful?
- where would this belong in the UI?

**Comment by xxchan** [comment]
A little bit about my use cases: 
- Rust has nightly release everyday. Sometimes it has regression when we update the Rust version, and thus I want to check what happened during that time. (I can often bisect the Rust version to a very small range, then I need to look into the commit history)
- Sometimes I just want to browse the commits. Since there aren't any "Paging", date range can be a good alternative.

**Comment by fregante** [comment]
> Rust has nightly release everyday

Why don't they use tags? This would actually guarantee you're comparing the two correct commits, something that this feature would not make any easier (due to having to pick the exact time the release was made)




> * Sometimes I just want to browse the commits

I agree with this one. It would be nice to jump to a specific date. 🤔

**Comment by kidonng** [comment]
I think people wouldn't mind if we stuff two date input here:

<img width="1231" alt="Screenshot 2023-04-10 at 18 07 57" src="https://user-images.githubusercontent.com/44045911/230881459-4ce0eac4-3af5-4841-b929-aae8d0546b44.png">

They will just think GitHub added a new feature 😝

**Comment by fregante** [comment]
Probably a good place, but I'm not sure about the UI for this feature:

- just an input box with a placeholder text: might feel a bit out place
- input box with label: same but even worse
- a button with dropdown: this could work but I don't want to create a dropdown and stick just an input element in it

Maybe a mix:

```html
<input type="date" placeholder="Date" class="btn">
```

With this, it would look like a button until you click it (probably also needs some `::placeholder` classes to make the text thicker)

**Comment by kidonng** [comment]
I quite like this. I will use this myself even if it can't get into RGH:

https://user-images.githubusercontent.com/44045911/231226837-72509cce-b5ce-4be2-a363-9945475cfc70.mov

**Comment by fregante** [comment]
Looks great, but it also looks like a lot of JSX. I don't think this little feature would be worth it (see also the previous `tags-dropdown`)

**Comment by kidonng** [comment]
It's in the **New Branches and Commits Pages** feature preview :tada: 

![image](https://github.com/refined-github/refined-github/assets/44045911/cf001bd5-b631-45b8-a13e-1c746b274454)
