### ISSUE TITLE
Safari 16.4 transparent text bug in `pr-approvals-count`

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6473]
### Expected

<img width="591" alt="Screenshot 6" src="https://user-images.githubusercontent.com/1402241/230712520-0df1c13b-7d27-430d-a355-308e9fb6587c.png">

### Current

<img width="591" alt="Screenshot 4" src="https://user-images.githubusercontent.com/1402241/230712527-ba636a5e-8d7f-43f1-a8fa-34f3ed379870.png">

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/pulls?q=+review%3Aapproved+

### Extension version

23.3.2

### Browser(s) used

Safari 16.4

**Comment by fregante** [comment]
Hotfixed for now. If it survives one or more RGH Safari releases I'll merge the hotfix into `main`

**Comment by teor2345** [comment]
This is still happening in MobileSafari on iPadOS 16.4.1 (a) (20E772520a).

Manually applying the hotfix from https://github.com/refined-github/yolo/blob/main/style/23.4.15.css fixes it.

**Comment by fregante** [comment]
Thank you for the report, I forgot about it. I’ll re-apply the hotfix now
