### ISSUE TITLE
Style of "Confirm merge" button is broken

### ISSUE THREAD

**Issue by yanorei32** [refined-github/refined-github#6474]
### Description

`div.btn-group-merge > button:nth-child(1)` 's `border-top-left-radius` and `border-bottom-left-radius` is not accurate.

#### Actually Result
![image](https://user-images.githubusercontent.com/11992915/230727615-4a19ef2f-b25e-443f-ae98-5b830d470691.png)
![image](https://user-images.githubusercontent.com/11992915/230727768-e9975f17-9078-4b56-95d6-f2dbb47fad85.png)

#### Expected Result (disabled this addon)
![image](https://user-images.githubusercontent.com/11992915/230727941-2f8d75da-95f5-4208-8b8a-d9d89b5688b6.png)
![image](https://user-images.githubusercontent.com/11992915/230727918-69d5785c-7e1f-47d4-a6fb-c3e8bf88148c.png)

### How to replicate the issue + URL

https://github.com/yanorei32/obs-spotify-bridge/pull/77

### Extension version

23.3.31

### Browser(s) used

Firefox Nightly 113.0a1 (2023-04-06) (64-bit) Windows

**Comment by yanorei32** [comment]
It's too soon! What the hell is going on?!

**Comment by fregante** [comment]
It was an easy fix. Thanks for the report! It has also been hotfixed and it should appear in your browser within 4 hours
