### ISSUE TITLE
`closing-remarks` has wrong style

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#6482]
### Description

Icon has unnecessary margin

<img width="867" alt="image" src="https://user-images.githubusercontent.com/44045911/230782947-41819799-b900-458b-8d07-ad60fc37086c.png">

### How to replicate the issue + URL

https://github.com//refined-github/refined-github/pull/6427#ref-pullrequest-1640816674

### Extension version

23.3.31

### Browser(s) used

Chrome

**Comment by fregante** [comment]
Can you check what classes are used in GitHub's own banners? Where can we find a similar one?

**Comment by kidonng** [comment]
Probably this? https://primer.style/css/components/alerts#with-action-button

**Comment by kidonng** [comment]
This seems to fix better:

<img width="869" alt="image" src="https://user-images.githubusercontent.com/44045911/230886469-ba013415-296f-4d43-a161-ea1d58813e7d.png">

Tag icon should not be in the button because that button does not do tags

**Comment by fregante** [comment]
> that button does not do tags

?

What about  the one that creates a release? Screenshots in https://github.com/refined-github/refined-github/pull/5772

<img width="658" alt="Screenshot 29" src="https://user-images.githubusercontent.com/1402241/230887593-2bd4fb0a-91bf-482f-af6c-4643eb6e763b.png">

**Comment by fregante** [comment]
Also the last related discussion (it was specific to the "unreleased PR" banner though)

- https://github.com/refined-github/refined-github/issues/5851#issuecomment-1195289714

**Comment by kidonng** [comment]
> Flash messages, or alerts, inform users of successful or pending actions. Use them sparingly. Don't show more than one at a time.

It seems we are doing the opposite: https://github.com//refined-github/refined-github/pull/5643

<img width="925" alt="image" src="https://user-images.githubusercontent.com/44045911/230891370-2cf1330e-0952-439a-aaa4-611fdba13490.png">

**Comment by kidonng** [comment]
How do you feel about this? It does address the "too strong" problem:

<img width="860" alt="image" src="https://user-images.githubusercontent.com/44045911/230895530-7e1d75b8-0466-4352-88ca-14faa1a5b7b4.png">

---

However this is much less pronounced:

<img width="860" alt="image" src="https://user-images.githubusercontent.com/44045911/230895547-a0ccd8bb-6349-4718-8c23-7f43182f0e59.png">

**Comment by fregante** [comment]
Honestly I'm still not convinced it's particularly wrong. GitHub shows the "Delete branch" CTA in the same style and with a large solid icon on the right. Creating a release is arguably more important than deleting branches. 

In the same vein as https://github.com/refined-github/refined-github/pull/6487, I think that giving it a transparent background could be a good-enough compromise that could work for both the "draft release" and "this was released" banners. The only issue at that point would be differentiation.

**Comment by fregante** [comment]
See:

<img width="727" alt="Screenshot 28" src="https://user-images.githubusercontent.com/1402241/230882686-7419aad6-29e8-4307-98b9-44b324de82bb.png">


Their purple banner might work just as well if the text was "PR merged, you can create a release." It's the same exact tone and situation. The only difference is the weight of the action

**Comment by kidonng** [comment]
> GitHub shows the "Delete branch" CTA in the same style and with a large solid icon on the right.

That's not a (flash) alert (box with solid background), but our features are.

It does not really have a name I think. But it is the same one as mergeability status

**Comment by kidonng** [comment]
Not just the background, but everything else (avatar-style icon, dialog-style box, heading) is different.

Nomenclature is not important but our features _are_ what are documented as "Alerts with action button".

And honestly, I don't see why compare them in the first place. You only see it when

- You can delete branch
- The branch has not been deleted

Which are rare, especially given `pr-branch-auto-delete` is there.
