### ISSUE TITLE
Make `rgh-netiquette` less eye-catching

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6484]
I think this is a bit much:

<img width="1305" alt="Screenshot 18" src="https://user-images.githubusercontent.com/1402241/230867748-d1569d05-8317-4ed3-912c-a1dd33c5b8a0.png">

It should roughly match the visual weight of the comment box. Maybe it should be gray or just not a banner at all.

### Test URL

https://github.com/refined-github/sandbox/pull/17
https://github.com/refined-github/sandbox/pull/1

**Comment by zoey-on-github** [comment]
I personally don't know if it's a good idea to make this *less* eye-catching, as I feel like it's an somewhat important notice. I think that as-is, it's sort of helpful to have it stick out as when you(or me personally, at least) first load up the page you see that and you think "ah, maybe I should think about leaving a comment here"

**Comment by fregante** [comment]
This refers to the notice we have on the Refined GitHub organization. The user literally cannot miss it if they want to leave a message, because the comment field is hidden until they find the button to unhide it.

I want people to see this notice when they look for the comment box, whereas now they _see_ this notice without even trying to leave a comment.
