### ISSUE TITLE
Show author icon (profile pic) in PR list page

### ISSUE THREAD

**Issue by ChillarAnand** [refined-github/refined-github#6491]
### Description

Instead of showing name, showing profile pic will be much better to get the information at a glance.

### Example URLs

https://github.com/ChillarAnand/avilpage.com/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/4906
