### ISSUE TITLE
`latest-tag-button` overflow on small screen

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#6494]
### Description

<img width="472" alt="image" src="https://user-images.githubusercontent.com/44045911/231232477-2325b842-c3ce-48db-ab4c-4b752e88392e.png">

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/tree/automated-selector-testing

### Extension version

23.4.10

### Browser(s) used

Chrome

**Comment by fregante** [comment]
- See https://github.com/refined-github/refined-github/issues/6250


We should probably drop the feature and just add what's needed

**Comment by fregante** [comment]
> EDIT: could be a wrong update since many things are broken

It is a beta after all 😅
