### ISSUE TITLE
Reposition new "report repository" in `clean-repo-sidebar`

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6498]
### Description

Looks a bit off place. Can we move it lower via CSS? Or just re-align it? It doesn't fit in that icon-list

<img width="231" alt="Screenshot 12" src="https://user-images.githubusercontent.com/1402241/231424859-7725ba83-8542-4d03-8ad9-bcaec256a272.png">

### How to replicate the issue + URL

https://github.com/refined-github/refined-github

### Extension version

23.3.2

### Browser(s) used

Safari

**Comment by kidonng** [comment]
I would say just hide it. Life is too short to report all trivial spam, and if you do want to report a major issue you just spend one extra minute filling the field manually.

**Comment by fregante** [comment]
To be honest I never ever reported a repo, but I did report plenty of comments and users. However I don’t think it's fair to hide it especially considering I can't even find the report link anywhere else. If I click the "contact" button in the footer… I don't see anything related either.

**Comment by kidonng** [comment]
> However I don’t think it's fair to hide it especially considering I can't even find the report link anywhere else. If I click the "contact" button in the footer… I don't see anything related either.

I agree it's a very obscure process:

1. Click "Contact GitHub" in the footer
2. Click "Contact us" in the footer
3. Click "Report abuse or spam"
4. And good luck finding these links among all the docs

<img width="751" alt="Screenshot 2023-04-12 at 19 22 20" src="https://user-images.githubusercontent.com/44045911/231442796-252157cf-f236-47d7-9241-89fddb1d1512.png">

But adding the link to every repo sidebar is just going from one extreme to another.
