### ISSUE TITLE
Add way to switch between "tag view" and "browse view"

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6499]
### Description

This feature is two-part:

- on releases: add links to `/tree/<tagname>`
	- URL: https://github.com/refined-github/refined-github/releases
	- URL: https://github.com/refined-github/refined-github/releases/tag/23.4.10
- on file/folder: add link to `releases/<tagname>`, if the user is on a specific tag
	- URL: https://github.com/refined-github/refined-github/tree/23.4.10
	- URL: https://github.com/refined-github/refined-github/blob/23.4.10/.editorconfig

## Demo for part 1

<img width="450" alt="Screenshot 15" src="https://user-images.githubusercontent.com/1402241/231425658-29fead09-a226-48b5-a524-b49e4ee7204c.png">

## Related

This could be a new extension refactored out of:

- #6250 

## Context

Icon/verbiage taken from [commit lists](https://github.com/refined-github/refined-github/commits/main):

<img width="794" alt="Screenshot 16" src="https://user-images.githubusercontent.com/1402241/231425820-4fdd15ac-df5f-4f26-9060-b01b3070c675.png">

**Comment by fregante** [comment]
Indeed by [changing `latest-tag-button`](https://github.com/refined-github/refined-github/issues/6250) we make room for a different button when you're looking at tags


## Before: `latest-tag-button`

<img width="407" alt="Screenshot 24" src="https://user-images.githubusercontent.com/1402241/231441064-e99d8a2f-b2db-4a07-99a6-0c2197863a37.png">

## After: `visit-tag` (?)

<img width="407" alt="Screenshot 25" src="https://user-images.githubusercontent.com/1402241/231441042-f9c10bf2-e799-4199-b3a0-e88c05f4bd5c.png">

or

<img width="407" alt="Screenshot 26" src="https://user-images.githubusercontent.com/1402241/231443293-3be86dda-a9e0-4d58-935b-1596c360afb9.png">

It's kinda tricky because it needs to be different from both `unreleased-commits` and the "31 tags" link on its right

**Comment by kidonng** [comment]
Isn't this already pointing to `/tree/`?

<img width="179" alt="Screenshot 2023-04-12 at 21 12 22" src="https://user-images.githubusercontent.com/44045911/231468362-138a7336-be6d-4605-9538-751577e62d48.png">

**Comment by fregante** [comment]
> Isn't this already pointing to `/tree/`?

Indeed it is, I was just assuming it pointed to the "tag" page (which isn't _a thing_)

Worth adding a feature to replace the icon? I wish they added a clear icon to differentiate "THE tag" vs "browse repo at tag"

`clear-tag-reference`? 😅 

So yeah the remaining feature would be `visit-tag`, which takes you from:

```
https://github.com/refined-github/refined-github/tree/23.4.10
```

to:

```
https://github.com/refined-github/refined-github/releases/tag/23.4.10
```
