### ISSUE TITLE
`show-names` should not get the name for mannequin accounts 

### ISSUE THREAD

**Issue by Nightfirecat** [refined-github/refined-github#6504]
### Description

As shown in the screenshot below, this mannequin user (not a real user; the username was copied from one which existed on bugs.python.org; see https://bugs.python.org/issue23402) has the real name for the GitHub user Adam. This is likely not the same user, so shouldn't have the real name shown.

![Screenshot_20230412_135013](https://user-images.githubusercontent.com/2199511/231582198-b78f2770-1866-4f7f-a6f0-47d58c6f2e89.png)

Additional context: https://devguide.python.org/triage/github-bpo-faq/index.html#what-on-earth-is-a-mannequin

### How to replicate the issue + URL

https://github.com/python/cpython/issues/67591

### Extension version

23.4.10

### Browser(s) used

Firefox 112.0

**Comment by fregante** [comment]
This is funny. GitHub’s own DOM has a `show_full_name=false` attribute. The s̕i̼m͗u̪l̒a̐t̖ío̾n̆ ǐs̸ b̃r̛e͛a̎k̍i̢n͠ğ 😂
