### ISSUE TITLE
custom-css doesn't inject into viewscreen.githubusercontent subframe

### ISSUE THREAD

**Issue by paulirish** [refined-github/refined-github#6507]
### Description

custom css doesn't work in image-rich-diffs.

<img width="569" alt="image" src="https://user-images.githubusercontent.com/39191/231862023-47b0f01b-5bf3-46cf-aef0-e58cb670082b.png">

![image](https://user-images.githubusercontent.com/39191/231862709-960a6162-83b8-4a48-b9e4-ca1a2609a565.png)

### How to replicate the issue + URL

1. view https://github.com/GoogleChrome/lighthouse-ci/pull/883/files
2. theres a bunch of image diffs. switch to rich diff on the top one. 
3. scroll to the bottom of the first image.. change image diff mode to 'swipe'
4. scroll back up (sorry images are so long)
5. notice that the before/after images are not top-aligned
6. decide to FIX IT with refined-github (praise for rgh!)
7. add this to the 'custom css' in rgh options:

```css
.swipe-shell { padding-top: 0 !important; }
span.added-frame { margin: 0 !important; }
```

8. reload the page. notice it doesn't change anything.
9. notice that the custom-css is injected as a `<style>` in the main document however.. this image diff viewer is actually an IFRAME!!!!!!: 
   - `<iframe class="render-viewer " src="https://viewscreen.githubusercontent.com/diff/img?bypass_fastly=true&amp;color_mode=light&amp;commit=....." sandbox="allow-scripts allow-same-origin allow-top-navigation" title="File display" >...</iframe>`

### Extension version

23.4.10

### Browser(s) used

Google Chrome	111.0.5563.146

**Comment by fregante** [comment]
Thank you for the detailed report and the praises Paul! Unfortunately given the different domain it isn't possible to inject into it without asking for a new host permission, as well as refactoring the CSS injection part. 

Given that the field is provided as a simple utility, it's best to use more adequate extensions for advanced needs, like Stylus: https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne

**Comment by paulirish** [comment]
All good.  I actually solved it with a greasemonkey script earlier.

Agree that asking for a new host permission isn't worth this bug.

Thx!
