### ISSUE TITLE
CSS contains `:has()` which is not supported in Firefox

### ISSUE THREAD

**Issue by marvinhagemeister** [refined-github/refined-github#6508]
### Description

The CSS code for the extension contains the `:has()` pseudo class, which is not yet supported in Firefox. It's behind a feature flag in Firefox 103 at the time of this writing.

### How to replicate the issue + URL

1. Install extension in Firefox
2. Go to any link on GitHub like this one you're currently viewing
3. Open DevTools -> check console errors

<img width="841" alt="Screenshot 2023-04-13 at 22 36 01" src="https://user-images.githubusercontent.com/1062408/231877051-4046ee48-746e-4d18-9717-1e54fc87be8e.png">

### Extension version

23.4.10

### Browser(s) used

Firefox

**Comment by fregante** [comment]
We know, we'll just have to wait

**Comment by fregante** [comment]
Reopening to add an `asLongAs: hasSelectorSupported` so that it doesn't show console errors on every page.
