### ISSUE TITLE
`table-input` popup too large on small screen

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#6511]
### Description

<img width="408" alt="image" src="https://user-images.githubusercontent.com/44045911/231979090-30a40fab-04ca-4d2c-8bbd-630db116a9f6.png">

### How to replicate the issue + URL

Here

### Extension version

23.4.10

### Browser(s) used

Chrome

**Comment by fregante** [comment]
- Bigger squares (touch)
- Smaller box (via `width: fit-content` or something equally automatic)
