### ISSUE TITLE
`releases-tab`: Show "Tags" tab if releases are missing? 

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6517]
### Description

Some repos don't use releases so we don't show `releases-tab`. However I think we should still add a tags-specific tab in that case. Is it possible?  Maybe a single API request can fetch both totals and decide label and URL of the tab.

<img width="151" alt="Screenshot 7" src="https://user-images.githubusercontent.com/1402241/232029138-5c4f365a-1d4d-47a2-8451-ecf47aa48f1b.png">

### Related

- https://github.com/refined-github/refined-github/issues/6130
- https://github.com/refined-github/refined-github/pull/6131#issuecomment-1302295960

### Example URLs

https://github.com/python/cpython/releases

**Comment by kidonng** [comment]
If you are visiting the repo homepage then the tags count are already there:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/44045911/232092830-3aec8f76-85ea-4b52-b8b5-d59b81ec020d.png">

So it's at least partially doable.
