### ISSUE TITLE
Unsearchable feature names

### ISSUE THREAD

**Issue by liyishuai** [refined-github/refined-github#6520]
### Description

I wanted the "Go to file" label back, rather than the magnifier button, so I tried to search for that feature.
1. Let's try `go`. No result.
2. How about `button`? Too many results; don't read.
3. Maybe `label`? 8 results, none of them is what I want.
4. So `file`? Again, too many results.

I then gave up, and read through the console. Gotcha! `clean-repo-filelist-actions`
Wait, what? Clean? Actions? How come this name?
And when re-searching `button` and `file`, this option was actually within the results, but I didn't have that patience to read through all those results---because I didn't even know whether my target was included or not! (Unlike the console, which _must_ include my target.)

My abrupt suggestion is to rename this feature, to make it searchable.
If renaming is too heavy, consider adding "Go to file" to its description, as it matches my first attempt, i.e., `go`.

### Example URLs

https://github.com/refined-github/refined-github

**Comment by kidonng** [comment]
There's a dedicated function for identifying a feature:

<img width="533" alt="image" src="https://user-images.githubusercontent.com/44045911/232109180-53930ed6-1567-4fa2-9a90-055c797abde0.png">

Anyway, if you are unsure about something, feel free to open an issue. But we are unlikely to change the name solely to make it more searchable, as it's a very subjective standard.

**Comment by fregante** [comment]
I think that the filtering only includes feature names. We could also include the descriptions, but that could render filtering less accurate (i.e. more results that are bad matches, they're always sorted alphabetically)

As mentioned there's a dedicated "Find feature" section in the options that's definitely more accurate anyway.

**Comment by liyishuai** [comment]
> I think that the filtering only includes feature names.

And the descriptions. Adding more keywords to the descriptions might be helpful:
<img width="392" alt="image" src="https://user-images.githubusercontent.com/7020805/232115935-4a695513-75b4-40a9-a15d-1d2cb4ebc91d.png">

**Comment by kidonng** [comment]
The thing is, they are rather simplified descriptions used in many places and we can't write essays in it.

Because things can appear or disappear due to GitHub or us, we don't really get to write detailed documentation for every feature. But if it's something really worth noting, we are happy to add it to the wiki.

**Comment by liyishuai** [comment]
Here's my extended feature description:

    On the repository homepage, compress the labels of "Go to file", "Add file", and "<> Code" buttons into 🔍, ➕, and ⏬ symbols, respectively.

**Comment by fregante** [comment]
Super-detailed descriptions are only useful for this workflow and _will_ end up being out of sync and verbose. We have some descriptions that are a little "vague" (especially the very old ones) but most of them serve their purpose (together with the screenshots)

Your intent is to identify features and we have a whole "wizard" for that, so I'm closing it, but thanks for the discussion.
