### ISSUE TITLE
Don't export access token

### ISSUE THREAD

**Issue by mskelton** [refined-github/refined-github#6521]
### Description

I story my refined github config in source control. I noticed that the new export feature will export `personalToken` with the GitHub access token I have saved. I feel like exporting the access token is perhaps not the best practice even if you don't store the config in source control, but I'm curious your thoughts on if it should be ignored or not.

### Example URLs

-

**Comment by kidonng** [comment]
This was discussed in https://github.com/refined-github/refined-github/pull/6448#discussion_r1161313001

If we don't export it, it will become a inconvenience to some other people. I would suggest writing a pre-commit hook to remove the access token (with `jq` or something)

**Comment by mskelton** [comment]
Gotcha, thanks.  Didn't know this was already discussed.  It's not a big deal, just thought it should be brought up, which it already was 🙂
