### ISSUE TITLE
any appetite for optional persisted sort/filter?

### ISSUE THREAD

**Issue by wakamex** [refined-github/refined-github#6523]
### Description

I just recommended `refined-github` to my boss, but was surprised to find there's no way to enable filtering out Draft PRs by default. The idea is that we have a large number of draft PRs right now that make us look like we have a big backlog, but only a small number of non-draft PRs waiting to land. If he and other managers were to switch to filtering out draft PRs by default, the picture looks totally different!

Looking at the [previous conversation](https://github.com/refined-github/refined-github/issues/80) on the topic, persistance was mentioned a few times:
- @hkdobrev suggest it
- @mojavelinux said it's interesting
- @hkdobrev spent a few weeks trying to make it happen by default, but found it quite difficult
- @fregante says he'd "hate to find the issues in whatever weird order I checked the previous time" which begs the question why he sorts things in *weird orders* but points to a "make this persist" box being the way to go

I wonder if:
- the discussed difficulty has changed due to the passage of time (probably not)
- it's easier if the scope were "persist only if you click this box" instead of "persist everything everywhere all at once"

### Example URLs

wow so clean and manageable! 🚀 https://github.com/element-fi/elf-simulations/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+draft%3Afalse
so messy and I need to delete some PRs 🫣 https://github.com/element-fi/elf-simulations/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
if only there were a way to make the first view persist 🥴

**Comment by fregante** [comment]
Unfortunately can't do it:

- hiding real content isn't a good default
- Refined GitHub doesn't offer options or off-by-default features

**Comment by fregante** [comment]
I almost forgot that we actually have a feature that lets you easily filter out any draft PRs, but it's not persisted:

<img width="327" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/233558046-ae3873ba-fc77-436d-9f00-7fcd32f7e52a.png">
