### ISSUE TITLE
Make a local test and take contribution

### ISSUE THREAD

**Issue by codenamedpkt** [refined-github/refined-github#6524]
Hi there,
I forked ur project and ready to tested locally but I do not know how to make a pull request to you as scrnshot below:
[![Screenshot_20230415-075419_Chrome](https://user-images.githubusercontent.com/23336645/232171952-ba2d87da-ec5c-446a-a8a4-1864a78a499b.jpg)](#Issue-here)
As u can see, it needs test url and scrnshot. How can I test locally?
Mr. Alice,
Mr. Poon's Studio

**Comment by fregante** [comment]
Welcome to GitHub, please refer to the contributing.md file in the repo. When opening a PR there are also instructions in the text field. 

The "test URL" is just a regular GitHub URL where your PR is making changes.
