### ISSUE TITLE
`default-branch-button` tooltip is partly invisible

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#6526]
### Description

Happens on new file view

<img width="309" alt="image" src="https://user-images.githubusercontent.com/44045911/232230630-637a850a-9791-4ac8-941f-490162f33ee1.png">

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/tree/demo/source

### Extension version

23.4.10

### Browser(s) used

Chrome

**Comment by fregante** [comment]
I think it should be `tooltipped-ne`
