### ISSUE TITLE
`rgh-feature-descriptions` only works when opened in a new page

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#6528]
### Description

Navigate to the following file (e.g. via Go to file) vs opening it in a new tab, `rgh-feature-descriptions` only works for the latter

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/blob/main/source/features/linkify-code.tsx

### Extension version

23.4.10

### Browser(s) used

Chrome

**Comment by kidonng** [comment]
😅 Well this is probably the AJAX related one

`download-file-button` is also missing sometimes

**Comment by fregante** [comment]
I think you're using the sidebar to change files, which basically isn't supported by our `turbo:` event listener, for which we already have an issue open.

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/6554
