### ISSUE TITLE
`show-names` appears on repo owners on "For You" newsfeed

### ISSUE THREAD

**Issue by Lamparter** [refined-github/refined-github#6530]
### Description

User's preferred `name` (which for me would be 'Lucius Lamparter') value not displayed properly in the user's feed.

### How to replicate the issue + URL

This bug can be found on the GitHub homepage and 'For You' user feed. (https://github.com)

![image](https://user-images.githubusercontent.com/71598437/232239212-8a2fb368-61cc-4cdb-8dae-2a6add320159.png)

In this example, `@andypiper` has starred `@BenRoe`'s repository `awesome-mechanical-keyboard` however `@BenRoe`'s prefered name is not formatted properly. 

More concisely:
Instead of
```ml
BenRoe (Ben)
```
Refined GitHub displays
```ml
BenRoe(Ben)
```
which is looks bad and is formatted wrong

### Extension version

23.4.10

### Browser(s) used

Microsoft Edge Insider Dev

**Comment by fregante** [comment]
Thanks for the report. I see two issues:

- [ ] the event's author doesn't have the full name, but should 
- [ ] the repo owner has the full name, but shouldn't

**Comment by kidonng** [comment]
> Thanks for the report. I see two issues:
> 
> * [ ]  the event's author doesn't have the full name, but should
> * [ ]  the repo owner has the full name, but shouldn't

Isn't is just a spacing issue?

<img width="689" alt="image" src="https://user-images.githubusercontent.com/44045911/232245125-f8481380-e586-49af-be50-c8e512282c4a.png">

**Comment by fregante** [comment]
We never show the full name next to the repo owner. So where you see the space issue, that name should instead not appear there at all. 

Judging by your screenshot, the first part works correctly.

**Comment by Lamparter** [comment]
@fregante noticed another bug here.
In @kidonng's comment (see picture below), the event author (Takayuki Miyahara) has both their login and preferred name.
![image](https://user-images.githubusercontent.com/71598437/232291543-08d7a16f-df32-43f3-a035-5359983b0c6a.png)

However, in my original comment (see picture below), the event author (Andy Piper) has only his preferred name and not his login name.

![image](https://user-images.githubusercontent.com/71598437/232239212-8a2fb368-61cc-4cdb-8dae-2a6add320159.png)

To be honest, I would actually prefer if Refined GitHub only showed the event author's full preferred name and not their login name.

**Comment by fregante** [comment]
> another bug

It's a feature ;) 

`@andypiper`’s name is `Andy Piper`, so instead of showing `andypiper (Andy Piper)` we just format its username.



> only [show] the event author's full preferred name and not their login name.


Too controversial 😅

**Comment by kyoyacchi** [comment]
And this is how it looks on mobile version
![Screenshot_20230418-112603](https://user-images.githubusercontent.com/63583961/232718676-27a385f5-e2fe-44e6-952d-0025a74fac82.jpg)

**Comment by Lamparter** [comment]
@fregante any progress to fix this issue?

**Comment by fregante** [comment]
https://sindresorhus.com/blog/issue-bumping

**Comment by Lamparter** [comment]
@fregante 😕 The fix doesn't seem to be completely working..
![image](https://user-images.githubusercontent.com/71598437/235287885-67274326-7bb3-42e7-a2c9-d179bde3fa1f.png)

**Comment by fregante** [comment]
That's because it hasn't been published yet
