### ISSUE TITLE
navigation options missing, including releases

### ISSUE THREAD

**Issue by agris-codes** [refined-github/refined-github#6533]
### Description

Win10 x64, 1809
FF x64 112.0
RGH build 23.4.15

The Projects, Wiki, Security and Insights navigation tabs at the top of the page are filtered out by RGH when it is active. The Releases and Packages tabs on the RHS, under about, are also filtered out when RGH is active. Issue persists across browser restarts, RGH cache clearing.

Console log output when RGH is enabled shows filter matching / detection is choking while parsing elements. Console output is here: https://pastebin.com/xbBTxKP5

RGH enabled:
![RGH_enabled](https://user-images.githubusercontent.com/39627597/232327734-5befda83-61f1-4dec-9c3a-c583e3ab9862.png)

RGH disabled:
![RGH_disabled](https://user-images.githubusercontent.com/39627597/232327743-693f5c23-9368-46e1-881e-d16ca278ee7f.png)

### How to replicate the issue + URL

Enable RGH on FF as per the bug description. Browse to https://github.com/subtledoctor/IWD_EET_Integration

Note the missing navigation options along the top, and on the right-hand side. Disable RGH, note the options have returned.

### Extension version

23.4.15

### Browser(s) used

FF 112.0 (64), also occured on 111.1

**Comment by fregante** [comment]
They're separate features that can be disabled.

- projects and wikis are disabled when no projects or wikis are found
- the other tabs are moved into the overflow menu/dropdown on the right of the navigation bar

**Comment by agris-codes** [comment]
> They're separate features that can be disabled.
>     * the other tabs are moved into the overflow menu/dropdown on the right of the navigation bar
It's intended behavior to remove the only link to Releases from the code's landing page?

Also, there is no "Releases" options in the overflow. The default RGH configuration is stripping away visibility of releases for the way this particular repo. Other than disabling RGH, the only only way to get to releases is to filter via label.

![missing](https://user-images.githubusercontent.com/39627597/232334120-2ca1142a-9152-4126-9deb-71e1269ab7ef.png)

**Comment by fregante** [comment]
> The Projects, Wiki, Security and Insights navigation tabs at the top of the page are filtered out by RGH 

The feature is `clean-repo-tabs`




> The Releases and Packages tabs on the RHS, under about

No? Tags are shown, packages are missing and therefore are hidden (because there's nothing to show to begin with)

<table>
<tr>
	<th>Before
	<th>After
<tr>
	<td><img width="322" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/232334112-93a89233-1ba1-4c1c-b657-da8e81dd0d1f.png">
	<td><img width="276" alt="Screenshot 1" src="https://user-images.githubusercontent.com/1402241/232334141-6019d2d7-0308-4a35-bf59-ed5e324fd68c.png">

</table>

Refined GitHub only hides sections that are empty, such as:

- your empty projects: https://github.com/subtledoctor/IWD_EET_Integration/wiki
- your empty wiki: https://github.com/subtledoctor/IWD_EET_Integration/wiki
- your empty packages: https://github.com/subtledoctor?tab=packages&repo_name=IWD_EET_Integration

**Comment by fregante** [comment]
> Also, there is no "Releases" options in the overflow

Refined GitHub actually promotes the releases to the main navigation:

<img width="478" alt="Screenshot 2" src="https://user-images.githubusercontent.com/1402241/232334292-7169ddea-8289-48fa-bcfd-40295f1e832a.png">

But I think you're not seeing them because the token is missing in the options

**Comment by agris-codes** [comment]
> > Also, there is no "Releases" options in the overflow
> 
> Refined GitHub actually promotes the releases to the main navigation:

My point is that, for this particular repo, it does not. Token or not, the default behavior is not what your image shows.

> No? Tags are shown, packages are missing and therefore are hidden 

My point here is not about the empty packages page being hidden, but that default RGH behavior should not remove the Releases header above tags and collapse tags into the info panel showing the number of starts/watches/forks. 

Our definition of refined will surely be different as I'm a very casual user of GH, but the removal of the Releases header does nothing but obfuscate the actual releases, for this particular repo.

![refined](https://user-images.githubusercontent.com/39627597/232334524-9946616e-7c07-482d-bbc9-c28ca335d0ca.png)

**Comment by fregante** [comment]
> The default RGH configuration is stripping away visibility of releases for the way this particular repo



> > > Also, there is no "Releases" options in the overflow
> > 
> > 
> > Refined GitHub actually promotes the releases to the main navigation:
> 
> My point is that, for this particular repo, it does not. Token or not, the default behavior is not what your image shows.

What are you talking about? My image clearly shows a Releases tab for this particular repo _as long as the token is set_:


<img width="478" alt="Screenshot 2" src="https://user-images.githubusercontent.com/1402241/232334292-7169ddea-8289-48fa-bcfd-40295f1e832a.png">


> should not remove the Releases header above tags

It provides no extra _**information**_, it literally just says "Releases", so we hide it. We can debate whether its link is useful though, I opened a new ticket for a possible issue regarding this: https://github.com/refined-github/refined-github/issues/6535

It seems that you're suggesting that each comment should also be prefaced by: 

> ### Comment

and each comment box should have a

> ### New comment

header. My opinion (and GitHub’s) is that some of these labels are redundant. The "Releases" tab follows the same logic.

**Comment by fregante** [comment]
> Our definition of refined will surely be different as I'm a very casual user of GH,

True, but thanks for opening the discussion. Usage varies and some things may go missing. This is why most features can be disabled but I agree it's important to have good defaults. But yes, using RGH without a token is basically frowned upon because the best features require it 😅

**Comment by fregante** [comment]
I also wanted to ask: why do your screenshot look this way? The colors are off:

<img width="295" alt="Screenshot 5" src="https://user-images.githubusercontent.com/1402241/232336410-57e3944d-5552-4578-81aa-20c16800bf26.png">

👆 this is a screenshot of your screenshot.

---

And the text is super jagged/aliased 😱 

<img width="800" src="https://user-images.githubusercontent.com/1402241/232336231-2633cd58-83e6-4ee0-861a-354fa1c57b5a.png">

**Comment by agris-codes** [comment]
> I also wanted to ask: why do your screenshot look this way? The colors are off:

It's either: image compression, or that the native display the shots were captured from is a wide gamut and the calibration used to achieve reasonable windows colorspace as emitted by the panel looks off due to said calibration.

aliasing, no clue. cleartype is dialed in on my system, probably image compression. 

> It provides no extra information, it literally just says "Releases"

Your line of argumentation here is pedantry. Clearly it *does* provide information, as it informs visits to this improperly(?) configured repo that, despite there being no release packages, releases can be found via the labels. Characterizing keeping the header as analogous to prefacing all comments with a comment header is reductio ad absurdum.

Thanks for maintaining the plugin btw, it's a solid upgrade to the default experience! (usually)
