### ISSUE TITLE
Add more iOS screenshots to the store

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6541]
I'll see if I can take a few iPhone 14 pro screenshots in the simulator for the next release. There's only one now:

![image](https://user-images.githubusercontent.com/1402241/232654893-0ede3e61-2811-4560-9b6f-6042663a95f9.png)

There should be one for every highlighted feature

**Comment by fregante** [comment]
Here @sindresorhus for the next release
![Simulator Screenshot - iPhone 14 Pro - 2023-05-13 at 17 45 45](https://github.com/refined-github/refined-github/assets/1402241/0aa9380e-0558-47cf-9e80-d13975348c2f)
![Simulator Screenshot - iPhone 14 Pro - 2023-05-13 at 17 48 12](https://github.com/refined-github/refined-github/assets/1402241/8384c33d-ffc3-4892-b380-a00261572814)
![Simulator Screenshot - iPhone 14 Pro - 2023-05-13 at 17 48 58](https://github.com/refined-github/refined-github/assets/1402241/125d48b1-0d2b-431e-9122-4b99bcbae982)
![Simulator Screenshot - iPhone 14 Pro - 2023-05-13 at 17 40 04](https://github.com/refined-github/refined-github/assets/1402241/1e94a5c3-d6c7-4065-a3f4-cbd6cad3a8d0)
![Simulator Screenshot - iPhone 14 Pro - 2023-05-13 at 17 34 11](https://github.com/refined-github/refined-github/assets/1402241/0ac91980-c95e-4487-966e-4c4b4d0e34ea)


![Simulator Screenshot - iPhone 14 Pro - 2023-05-13 at 17 45 16](https://github.com/refined-github/refined-github/assets/1402241/5ff3205f-4b0a-4fac-9f02-c1d0eadb96b6)

**Comment by sindresorhus** [comment]
👍 It will be in the next update.
