### ISSUE TITLE
Option to hide tabs on repos (mobile)

### ISSUE THREAD

**Issue by Void48** [refined-github/refined-github#6544]
### Description

Can we have the option to hide some of the tabs on mobile? Like one of these for example: 
![image](https://user-images.githubusercontent.com/85196642/233262835-4c32db12-1997-4306-a9cc-418cb7dcca91.png)

### Example URLs

All repos (global setting?)

**Comment by fregante** [comment]
Refer to the wiki:

- https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options
