### ISSUE TITLE
Support downloading build artifacts with nightly.link or something similar

### ISSUE THREAD

**Issue by Void48** [refined-github/refined-github#6545]
### Description

Think it would be cool to be able to download the artifacts without having to go to nightly.link all the time to paste the link there. Or some other way if it's possible at all 🙏

### Example URLs

Any repo that has downloadable build artifacts

**Comment by fregante** [comment]
The example URL field requires a REAL url. I don't know what you're talking about specifically

**Comment by fregante** [comment]
That helps, thank you. Refined GitHub does not support that use case however so I'll close this issue. 

https://github.com/refined-github/refined-github/blob/316aa69f82714f5b2f77678406d5d275d87d38d5/source/feature-manager.tsx#L150
