### ISSUE TITLE
✨ Add 'create branch from `{branch}`' to add to repo button

### ISSUE THREAD

**Issue by Lamparter** [refined-github/refined-github#6549]
### Description

Add `create branch from {branch}` as an option in the 'add to repo' button on writable repos.

With a little mockup, I quickly created what I thought this feature should look like:
![image](https://user-images.githubusercontent.com/71598437/233824156-4f74bbe4-fd8a-4623-a688-1b4444a4cdd9.png)
After clicking 'create new branch', Refined GitHub should open this UI:
![image](https://user-images.githubusercontent.com/71598437/233824207-1a26e1f8-beff-4dc0-b9a3-1d373646a340.png) and if possible, the branch should automatically be based on the branch the user was on (difficult; unnecessary)

Perhaps also change the `aria-label` from `Add file` to `Add new..` or similar

### Example URLs

the feature should be here:
![image](https://user-images.githubusercontent.com/71598437/233824281-13cd3b7c-56ec-4f49-a953-50b70e87f2fe.png)
e.g. https://github.com/RiversideValley/Emerald for me, as I have write access and can see the `add files` button, but for you perhaps [this repo, ](https://github.com/refined-github/refined-github)https://github.com/refined-github/refined-github as you most likely have write access to the repo.

**Comment by fregante** [comment]
This is already possible with the native branch selector. Just open the selector and start typing the new name.
