### ISSUE TITLE
show "locked" status of issues

### ISSUE THREAD

**Issue by lsloan** [refined-github/refined-github#6551]
### Description

Refined GitHub should show an indicator when an issue is "locked".  I think it's most important when viewing an issue page, but it would also be helpful when showing a list of issues, if that's possible.

### Example URLs

https://github.com/PyCQA/pycodestyle/issues/703

**Comment by lsloan** [comment]
I thought of this after I read an issue and wanted to give a thumbs-up to some of the comments.  I couldn't figure out why others had done so already, but I could not.  Finally, when I got to the end of the issue comments, the last message I saw was that the repo maintainers had locked the issue.  Surprisingly, it's the only indicator of the "locked" status.  I expected the right column of issue info to include an indicator, but it does not.

I think Refined GitHub could probably solve this issue by putting an indicator either in the right column, with the issue header (title, etc.), or both.

**Comment by fregante** [comment]
Note that occasionally there are issues that are not "locked" but you still can't interact unless you did before:

- https://github.com/RupertBenWiser/Web-Environment-Integrity/issues/28

<img width="660" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/f0cae8ef-6f39-4f55-847b-d51abf6eb648">

An early hint of any type of lock is the lack of reaction buttons:

- regular: <img width="167" alt="Screenshot 2" src="https://github.com/refined-github/refined-github/assets/1402241/75aa01b4-abf8-4750-b905-62552b7fc8da">
- at-least-partially locked: <img width="292" alt="Screenshot 1" src="https://github.com/refined-github/refined-github/assets/1402241/ce65d2b5-3f64-47f2-95fa-4a3c08c672b8">

**Comment by fregante** [comment]
I've been using the reactions and https://github.com/refined-github/refined-github/pull/6795 to discern locked issues. I think this feature would be relatively simple:

```js
function addLock() {
	$('issue header').append(<div someLabelClass><LockIcon/> Locked</div>)
}

observe('the locked reaction avatars, some other "locked" indicator', onetime(addLock));
```

The hard part is just finding the right selector and right style/position.
