### ISSUE TITLE
`clean-rich-text-editor` no longer hides "please fill out this field" tooltips

### ISSUE THREAD

**Issue by Luke18033** [refined-github/refined-github#6589]
### Description

A while ago in #2349 I requested a feature that would hide "please fill out this field" tooltips on text boxes which are useless and do nothing but obscure what you're typing. This feature was implemented as part of `clean-rich-text-editor`, but at some point this stopped working and the tooltips now appear again.
![image](https://user-images.githubusercontent.com/19228201/235058983-9d5f936b-7d2a-451d-bf37-776195d60a88.png)

### How to replicate the issue + URL

Any page with required text inputs, such as [the create issue page](https://github.com/refined-github/refined-github/issues/new?template=1_bug_report.yml), [an issue](https://github.com/refined-github/refined-github/issues/6408), or [a discussion](https://github.com/StrataSource/Portal-2-Community-Edition/discussions/706).

### Extension version

23.4.26

### Browser(s) used

Firefox

**Comment by AmalChandru** [comment]
@fregante Can I pick this one?

**Comment by fregante** [comment]
You can just send a PR anytime 👌

**Comment by fregante** [comment]
I ended up deciding that this isn't worth the hassle
