### ISSUE TITLE
`open-all-notification` shows "n tabs opened" toast even if you cancel it

### ISSUE THREAD

**Issue by Vendicated** [refined-github/refined-github#6590]
### Description

Pressing the "Open all Notifications" button will show a confirm alert asking whether you want to open n tabs

If you cancel during this step, it won't actually open any tabs (as intended), but still show the "n tabs opened" toast in the bottom right

This seems to be because the `if (!openingTabs) return` comes after the toast, not before:
https://github.com/refined-github/refined-github/blob/3eb69778b29b87b02a4ab2ddda4d8a302307f759/source/features/open-all-notifications.tsx#L34-L41

Assuming showToast shows the "doneMessage" on promise resolve, the easiest fix would probably be to make openTabs reject if cancelled (instead of returning a boolean)

### How to replicate the issue + URL

- Go to https://github.com/notifications
- Have unread notification (just mark one as unread if you don't)
- Click "Open all Notifications"
- Cancel it
- Observe toast still showing

### Extension version

23.4.26

### Browser(s) used

Chromium Version 110.0.5481.177 (Official Build, ungoogled-chromium) (64-bit)

**Comment by fregante** [comment]
Thanks for the report! Indeed the API is a little awkward, given that opening tabs is nearly instant, it makes no sense to show a progress toast. I think it was only added to show an error, so it can be changed to:

```js
try {
	if (!await openTabs()) {
		return;
	}
} catch (error) {
	await showToast(error)
}
```

**Comment by Nanak360** [comment]
Hey I can take it up and start working on it
