### ISSUE TITLE
Using in Kiwi browser (mobile Chrome). Using settings.

### ISSUE THREAD

**Issue by goodevilgenius** [refined-github/refined-github#6591]
I recently started using Kiwi on my Android devices. I got it installed (although I had to sideload it, since the Chrome Web Store says it's not compatible).

This is probably a no-go, since it's not actually supported on mobile Chrome, but it does seem to work just fine. Only problem is that I can't get to the settings.

Tapping the sidebar button just opens up a new GitHub tab, and long pressing on the button does nothing.

I haven't checked yet what attaching a mouse and right-clicking does yet.

Is there a way to force the button to open the settings, instead of GitHub itself?

**Comment by fregante** [comment]
Can you ask them how that’s supposed to work? The browser should natively offer a button to access the options. 

If they say that’s not yet available, I could redirect the URL there. 

Are “actions popups” available? https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/action/setPopup

**Comment by fregante** [comment]
From what I see, you should already be able to access the options:

1. Open the installed extensions list
2. Find Refined GitHub 
3. Tap Details
4. Tap “Open extension options”

**Comment by goodevilgenius** [comment]
@fregante Thank you! Yes, that does it. Not sure how I missed that, but, thank you!

And now that I can get to the settings, I can change the default URL to open when I click the button to chrome://extensions/?options=aeeggjkpkmcmboppnlnkmnbcampgjfpa so that it does open the settings page for me.
