### ISSUE TITLE
Duplicate file icons with github-material-icons-extension

### ISSUE THREAD

**Issue by cj81499** [refined-github/refined-github#6598]
### Description

There seems to be a conflict when installed alongside https://github.com/Claudiohbsantos/github-material-icons-extension where duplicate icons are visible.

I used the "Find feature" button to discover that `quick-file-edit` is the culprit.

cc: @Claudiohbsantos (main developer of `github-material-icons-extension`)

### How to replicate the issue + URL

Install both `refined-github` and https://github.com/Claudiohbsantos/github-material-icons-extension. 

Navigate to: https://github.com/refined-github/refined-github

Observe duplicate file icons.

![Screenshot showing duplicate file icons bug](https://user-images.githubusercontent.com/9152032/235506029-c7ffdd79-2a42-4c42-a931-fc1f6a329428.png)

### Extension version

23.4.26 (Refined GitHub) 1.8.0 (Material Icons for GitHub)

### Browser(s) used

Chrome

**Comment by Claudiohbsantos** [comment]
Ops, I use both extensions as well and somehow missed this, thanks for tagging. I'm not super familiar with how this extension is operating so I'll have to take a look into that feature and see what is happening

**Comment by fregante** [comment]
This happened before:

- https://github.com/refined-github/refined-github/issues/1993

The solution might have changed since then, but you can look at https://github.com/lvarayut/github-file-icons/issues/5#issuecomment-493310349 for some hints.
