### ISSUE TITLE
"Identify Feature"

### ISSUE THREAD

**Issue by anzz1** [refined-github/refined-github#6599]
#### Identify Feature

Okay, I **absolutely** have to comment on this. This is just so good.

To whomever hasn't seen this marvel with your own eyes, check these steps out for yourself.
1. Open a GitHub tab where you see the change you did not like.
  In this case the compacted right side-bar (missing sub-headers for Releases and Languages, I prefer the original one more)
![step1](https://user-images.githubusercontent.com/13628128/235555936-b26470ce-e465-4dfa-91fa-fb858ab76081.png)

2. Open a new tab and type "about:addons" to address bar (or go through Firefox menu to Extensions) and find "Refined GitHub". 
  Click on the "Identify Feature" button.
![step2](https://user-images.githubusercontent.com/13628128/235555937-e68ea5d7-9278-4f31-b394-a1a99d52fd0f.png)

3. Go back to your first tab and press F5 to refresh, and this will appear.
  Only thing you need to do now is click "Yes" or "No" depending on whether you see the change/issue.
  
![step3](https://user-images.githubusercontent.com/13628128/235555940-312fbfc1-d48d-4772-92fc-ada5dcad2187.png)

![step4](https://user-images.githubusercontent.com/13628128/235555943-feb3fd82-2a0b-43d9-aed9-37f28763bdfe.png)
  
4. Finally this infobox will appear.
  It will not only tell you the name of the feature, but also directly link to the code at the extension's github repo (this one). If it's a feature you want to disable, you now know how; or if it's a bug, it is now very easy to contribute and fix it yourself if you can or to post an issue about it.
![step5](https://user-images.githubusercontent.com/13628128/235555944-5fdb2aad-7ec1-49d3-82d6-d2703708fd76.png)

5. Now you can go back to the addons tab, type the name of the feature in the box and uncheck the checkbox.
![step6](https://user-images.githubusercontent.com/13628128/235555945-91797337-5921-4d5a-bab3-7b347ee16495.png)

---

I hereby declare whoever thought of and implemented this a genius and the unquestionable god of UI/UX design.
We need to save this person's DNA so they can be cloned in the future and installed as the lead of UI/UX design to every software company in the known universe.

Never mind that I didn't have to RTFM at any point, which is always a sign of good design but also 

This is how everything should be designed. I can't even count the times I've been frustrated of some feature in a product while liking the product overall, and more often than not voicing such an opinion gets met with a hostile attitude of "if you don't like it, don't use it" aka. "my way or the highway" mentality, that your only option as an end-user is to dismiss the product entirely or to keep using it while grinding your teeth. Clearly that isn't the case when it comes to the Refined GitHub team.

Overall the design of this addon is exceptional, and the feature list has a fuzzy-search which works well and even has **screenshots!** and **direct links to the source!!**. With just that, the feature sure could be found too, but especially when the amount of configuration options grows it can get hard to find the right words to search for. Probably 100% of developers have had the problem of trying to find that single option in a sea of a million, especially when it comes to IDEs. While fuzzy-search is the "good enough" default, the "Identify Feature" feature is just *transcendental*.

Keep up the ~~good~~ fantastic work ! :+1:

**Comment by anzz1** [comment]
Sorry, I thought this was going to open a "discussion" and not a "issue", as this is not a issue. I just wanted to comment. Feel free to close whenever.

**Comment by fregante** [comment]
> more often than not voicing such an opinion gets met with a hostile attitude of "if you don't like it, don't use it" aka. "my way or the highway" mentality


<img src="https://user-images.githubusercontent.com/1402241/235581324-46666b51-bf8c-4659-bf66-ca361bfdc792.jpeg" width=200>

We definitely do this too sometimes 😅 

Anyway thanks for the review! I’ll keep this up there as a reminder it exists. It occasionally has helped myself finding a feature too, I don’t remember all of them anymore.
