### ISSUE TITLE
`rgh-feature-descriptions` Add “Report bug” on feature pages 

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6600]
### Description

On our feature, we should add a simple new button that opens the bug report with the feature name in the title. 

### Example URLs

https://github.com/refined-github/refined-github/blob/main/source/features/align-issue-labels.css

**Comment by Subham5401** [comment]
Hi @fregante , I'd like to take this further. Could you elaborate a bit on your requirements?
