### ISSUE TITLE
An option to choose the date format (everywhere)

### ISSUE THREAD

**Issue by MatteoGauthier** [refined-github/refined-github#6601]
### Description

Sometimes I need to know when a commit as been made, but "3 weeks ago" is not precise.
It might be useful to have the full date displayed.

### Example URLs

![image](https://user-images.githubusercontent.com/32040951/235653920-c6156df3-3df8-4476-a16c-fb44239a6988.png)

**Comment by iGabyTM** [comment]
You can hover over the text and it will show you the exact date and time
![image](https://user-images.githubusercontent.com/32105478/235671550-b2f6e96b-68e2-4c60-ac8e-fd815a77eb19.png)

**Comment by fregante** [comment]
Refer to:

https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options
