### ISSUE TITLE
Provide more prominent button to re-request review from some/all users if you were the user to open the PR

### ISSUE THREAD

**Issue by macintacos** [refined-github/refined-github#6602]
### Description

When I'm working on a PR, often I'll forget to re-request a review after fixing whatever I've been asked to fix. AFAIK, the only affordance for this button is the small arrows that are next to the reviewers' names at the top-right of the Conversation view.

It'd be awesome if there was a button above the tabs in a PR that was just "Re-request Reviews" if there were any pending. That way it would be visible regardless of which page you're on. If that can't be done, I'd settle for it just being a big ol' button in the sidebar on the Conversations view, just below the "Reviewers" section.

### Example URLs

Any PR should work as an example, so I'll just link to some PRs in this repo:

- https://github.com/refined-github/refined-github/pull/6445
- https://github.com/refined-github/refined-github/pull/6550

**Comment by fregante** [comment]
I disagree that this is an action that ever needs to be taken. 

Every comment and commit you push *already* notifies everyone who previously commented and reviewed. 

Refined GitHub won’t implement features that help spam users

**Comment by macintacos** [comment]
I disagree that this is “spamming” - the feature is meant to indicate that a review is ready to look at, while comments don’t necessarily do that. But I mean it’s your project, so more power to ya.
