### ISSUE TITLE
Make it so clicking the extension icon opens the options

### ISSUE THREAD

**Issue by asmeurer** [refined-github/refined-github#6603]
### Description

Right now, when you click the Refined GitHub extension icon, it opens github.com. This isn't particularly useful Generally, when I reach for the extension icon, it's because I want to open the options. It would be more useful if it opened the options. It would also be nice those options opened in a little popup (similar to how something like ublock origin works), but that's obviously more work.

I'm sorry if there's already an issue for this. It's not an easy thing to search for in the issues list.

### Example URLs

N/A

**Comment by busches** [comment]
Ironically, it's customizable and you can change it to open the extension options instead.

I agree it should be options instead by default though.

**Comment by asmeurer** [comment]
Oh I didn't notice that. I set it to open chrome://extensions/?options=hlepfoohegkhhmjieoechaddaejaokhf. Presumably that URL is different for everyone. Hopefully it doesn't change when the extension updates.

**Comment by fregante** [comment]
Yep, that’s what I do too
