### ISSUE TITLE
Please move all features that require a "Personal Token" to a separate section of the configuration UI

### ISSUE THREAD

**Issue by matthewhively** [refined-github/refined-github#6607]
### Description

When I go to configure `refined-github`, It would be nice to see at a glance all features that require a personal access token to function.
This way we can more easily decide whether its worth the hassle of generating and maintaining one based on the features it provides.

Currently it looks like the only way to find out what requires it is to use the search feature here on github
https://github.com/refined-github/refined-github/search?p=3&q=github-helpers+api

### Example URLs

From the configuration page:
chrome://extensions/

**Comment by yakov116** [comment]
The features are intended to be used with a personal token.
As Github changes the DOM to react we will have to rely on the api to determine things.

This is not something we plan to add.

**Comment by fregante** [comment]
Indeed that’s the correct way, we even have a link to that search next To the personal token field. 

Making this change requires too much work and that’s not needed. 

Related issues:

- https://github.com/refined-github/refined-github/issues/3217
