### ISSUE TITLE
"Expected node matching 'Code', found ''  "

### ISSUE THREAD

**Issue by matthewhively** [refined-github/refined-github#6608]
### Description

Misc console bugs that I found using the latest version of refined-github.
I tried clearing the cache as suggested. The error line reported changed, but didn't go away.

1st error:
<img width="1298" alt="Screen Shot 2023-05-03 at 5 01 53 PM" src="https://user-images.githubusercontent.com/25018092/236076296-809c1168-5c28-4106-8535-9bd3eb83952e.png">

2nd error:
<img width="1295" alt="Screen Shot 2023-05-03 at 4 57 53 PM" src="https://user-images.githubusercontent.com/25018092/236076402-06585dc2-248d-4bdb-a861-1eaba3165433.png">

This probably not a complete list of all the uncaught exceptions that exist.

Please let me know if you need me to export my plugin config, though I think every option is checked at the moment.

### How to replicate the issue + URL

1st error:
https://github.com/refined-github/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

2nd error:
https://github.com/refined-github/refined-github

### Extension version

23.4.26

### Browser(s) used

Chrome 112.0.5615.137

**Comment by yakov116** [comment]
Did you try to add a person token in the options?

**Comment by fregante** [comment]
Those are not errors.

I updated this issue title to only track the error related to the “repo file action cleaner” feature

**Comment by matthewhively** [comment]
> Did you try to add a person token in the options?

I did not try adding a personal access token.

**Comment by matthewhively** [comment]
> Those are not errors.

An uncaught error isn't an error?
To be clear, I attempted to turn off all of the features that generated the informational log message (the ones that say "XYZ -> Personal token is required for this feature")
And the uncaught error was again placed into the console when I refreshed the page.

**Comment by fregante** [comment]
> Those are not errors.

I’m referring to the black log messages which are black and not red because they’re messages and not errors. They also do not include the word “Error” for the same reason.

**Comment by fregante** [comment]
I was referring to the log list above regarding the token. I didn’t realize that the last one was actually an error about the token.

> This probably not a complete list of all the uncaught exceptions that exist.

Feel free open open separate issues for those errors but search for duplicates first. 

Some error messages include two links to search and create issues, you can use those to facilitate reporting.
