### ISSUE TITLE
`clear-pr-merge-commit-message` fails often

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6611]
### Description

This commit was sent (notice non-empty commit body)

https://github.com/refined-github/refined-github/commit/b3e7358daa453481574a796bd8b3c2238701a2bc

### How to replicate the issue + URL

1. Open https://github.com/refined-github/sandbox/pull/55
2. Click "Merge" to open the box
3. Notice that the box has been cleared
4. Submit a new comment
5. Notice box is closed when the comment is submitted
6. Reopen box
7. ❌ The commit message has returned and is empty

### Extension version

23.4.15

### Browser(s) used

Safari

**Comment by raiyni** [comment]
Not sure if this is the correct issue but this has been happening for a few months now where the extended description box for `Squash and merge` is filled with all of the commit message garbage.

![image](https://github.com/refined-github/refined-github/assets/22979513/15d8db7e-7e90-47d1-ae1a-df7c8edfc312)

**Comment by fregante** [comment]
My guess is that GitHub fills up the field a second time, but Refined GitHub does not catch that because it's the same field. 

Maybe GitHub fires some event we can listen to, or we have to go back to the "open merge box" event via delegate

**Comment by fregante** [comment]
I think the fix is simple:

- use `delegate('textarea selector', 'change', clear)` instead of `observe('textarea selector', clear)`

I saw that they always fire the event when it's opened:

```js
on('details:toggled', '.js-merge-pr', function (event) {
  const container = event.currentTarget
  const msgTextArea = container.querySelector('.js-merge-message')
  if (msgTextArea) {
    // Trigger size-to-fit for the merge message textarea
    fire(msgTextArea, 'change')
  }
})
```

**Comment by fregante** [comment]
Well well well. 

- https://github.com/refined-github/refined-github/pull/6330

This was an intentional change 🥲 

I think that rather than unloading the feature, it should just check whether the field "is dirty", like GitHub does. I think this can be checked via class for now.
