### ISSUE TITLE
Readme: wrong image for comment reaction avatars

### ISSUE THREAD

**Issue by suyanhanx** [refined-github/refined-github#6616]
### Description

It should be a screenshot of the reaction to the comments. The current screenshot is wrong.

https://github.com/refined-github/refined-github/blob/f9a7935adf36c139b9cf47953fd447a8ca28545f/readme.md?plain=1#LL216C22-L216C22

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/blob/f9a7935adf36c139b9cf47953fd447a8ca28545f/readme.md?plain=1#LL216C22-L216C22

### Extension version

23.4.26

### Browser(s) used

Chrome 112.0.5615.137 MacOS (arm64)

**Comment by fregante** [comment]
You’re right, I mistakenly broke it. It’s a good time to update the screenshot

**Comment by suyanhanx** [comment]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/24221472/236391895-21e952a9-f438-4c05-bb0a-744f8d7dcf22.png">

The image in the plugin configuration is also wrong. You can check it together.

**Comment by fregante** [comment]
It uses the readme for that
