### ISSUE TITLE
The `list-prs-for-branch` button is mispositioned/vertically-misaligned/wrapped

### ISSUE THREAD

**Issue by DanielMiao1** [refined-github/refined-github#6624]
### Description

In the commits tab of a branch where the `list-prs-for-branch` feature is enabled, the PRs-for-branch button is not displayed on the same line as the branch selector button (see figure 1 below).

This issue could be due to a change by GitHub in removing the `display: flex` property from `.file-navigation`, therefore disrupting the layout of the buttons.

### How to replicate the issue + URL

In a commits tab where the `list-prs-for-branch` feature is enabled, such as https://github.com/refined-github/sandbox/commits/6538-PR-BRANCH-2, the misalignment issue can be observed:

**Figure 1**
_The [issue](https://youtu.be/mCkl8i48Fh8) on Firefox 113.0b5_

![Screenshot 2023-05-06 at 9 46 23 AM](https://user-images.githubusercontent.com/83146190/236636741-535f0356-bda4-4245-a3cd-025ddd70d969.png)

**Figure 2**
_After applying `display: flex` to `.file-navigation`_

![Screenshot 2023-05-06 at 11 11 34 AM](https://user-images.githubusercontent.com/83146190/236640256-85134111-f9ac-4d7a-bf9f-718b0335b5ae.png)

### Extension version

23.4.26

### Browser(s) used

Firefox Developer Edition x86_64 113.0b5 on macOS 13.2, Chrome 113.0.5672.63 x86_64 on macOS 13.2

**Comment by fregante** [comment]
I encountered this issue while I restored the feature recently. It's possible that the DOM varies if you refresh the page vs if you change the branch selector (which is loaded via ajax)

Either way it should be an easy fix, assuming it maintains compatibility on non-`commits` pages

**Comment by DanielMiao1** [comment]
Is adding `display: flex` to `.file-nagivation` the correct method to fix this issue? From my investigations/testing, it looks like `.file-navigation`, which contains the PRs-for-branch button, should be `display: flex` as the button has `.flex-self-center`. Furthermore, it appears that all `.file-navigations` on other pages such as repo roots have `.d-flex` or another method of setting `display: flex`, so the fix should not create any issues for other pages.

Incidentally, have you found any specific scenario/sequence for loading the commits page that correctly aligns the button? I wasn't able to find such a scenario (even after accidentally discovering [this](https://user-images.githubusercontent.com/83146190/236696248-81975a7f-1a10-4c74-8d8d-514ae7e654a1.mp4), [this](https://user-images.githubusercontent.com/83146190/236696272-4cde1435-64aa-473b-bdaa-e136b30f2ac3.png), and [this](https://user-images.githubusercontent.com/83146190/236696288-d0435645-5526-44df-adf8-c358306c8837.mp4)), though I was able to verify that the DOM generated when the commits page is loaded from the "[history icon] x commits" button in the file/tree view is different from the DOM after refreshing the page, which (I believe) causes the PRs-for-branch and see-this-view-on-default-branch button to disappear when loading the page from the file/tree view.

**Comment by fregante** [comment]
I haven’t looked at the dom, but yeah probably you just need to add the `d-flex` class to its parent and go from there. GitHub has a lot of those utility classes so you rarely need custom CSS
