### ISSUE TITLE
`quick-file-edit` showing double icons in chrome

### ISSUE THREAD

**Issue by pMattheew** [refined-github/refined-github#6625]
### Description

![image](https://user-images.githubusercontent.com/99044724/236653111-08105169-6c3a-435b-9636-0a1035f30247.png)
[screen-capture.webm](https://user-images.githubusercontent.com/99044724/236653234-fb74bdde-4fa4-442c-965e-9e0b7112863f.webm)

---

for some reason this feature is causing the extension to show double icons when they're files inside of a github repo. I tested it only in chrome, and a video replicating it is linked above, below the image.

this issue started to happen after a few days, and today after being annoyed about it I searched what it was and using the **Identify feature** button of the extension, it reported it to me and showed that it was a [recent feature added two days ago](https://github.com/refined-github/refined-github/blob/main/source/features/quick-file-edit.tsx).

I hope this helps. ty!

### How to replicate the issue + URL

enabling `quick-file-edit` feature should replicate the problem.

### Extension version

23.5.6

### Browser(s) used

Chrome

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/6598
