### ISSUE TITLE
Convert TODO in code to issues

### ISSUE THREAD

**Issue by bradystroud** [refined-github/refined-github#6643]
### Description

GitHub can find warnings in code, I imagine it would be possible to find TODO comments, and have a little annotation that creates an issue based on the comment.

### Example URLs

https://github.com/SSWConsulting/SSW.Website-v3/blob/9e0d1b58223010b213f52e853fff2bdc27fd87df/next-sitemap.config.js#L17 

Anywhere code is viewed

**Comment by fregante** [comment]
Not a bad idea, but GitHub has recently made it difficult to add custom links in code. 

Related: 

- #6336 
- https://github.com/refined-github/refined-github/pull/6615

**Comment by fregante** [comment]
I suggest asking GitHub, we can't implement this currently

**Comment by bradystroud** [comment]
Done - #58695
