### ISSUE TITLE
`pr-base-commit` errors in attempting to remove a non-existent automerge message

### ISSUE THREAD

**Issue by DanielMiao1** [refined-github/refined-github#6650]
### Description

Currently, the `pr-base-commit` feature attempts to remove [(view source)](https://github.com/refined-github/refined-github/blob/77d3bbb7f5dbbe6bed7828675c1b5ddf7ef4f1fc/source/features/pr-base-commit.tsx#L46) the "Merging can be performed automatically" message (see figure 1) from the bottom of a pull request conversations page without verifying the existence of the message.

As the message is only shown to users with sufficient privileges to merge the pull request, the code fails with a warning-level `Error <span class="status-meta">` and an `Error: Expected node matching "Merging can be performed automatically.", found {actual_content}` (see figure 2) when a pull request is viewed by a user who does not have sufficient privileges.

### How to replicate the issue + URL

1. Visit an open, non-blocked, and non-draft pull request that you do not have sufficient privileges to merge and is behind the base branch, such as https://github.com/DanielMiao1/test/pull/8
2. The error is raised in the browser console (see figure 2).
&nbsp;

**Figure 1**
_The `Merging can be performed automatically` message shown to privileged users before its removal_

![Figure 1](https://github.com/refined-github/refined-github/assets/83146190/c15ed183-60f5-425d-8d9c-f45af71474c5)
&nbsp;

**Figure 2**
_The console error when viewing the page without sufficient privileges_

![Figure 2](https://github.com/refined-github/refined-github/assets/83146190/487bda9f-998a-4ffa-9b81-f6863346468b)

### Extension version

23.5.10

### Browser(s) used

all supported browsers

**Comment by fregante** [comment]
> without verifying the existence of the message.

The message you see is the exactly the verification: the text doesn’t match, so it throws an error 😉 

Solution:

- silence error
- have the text appear on two lines instead of that
