### ISSUE TITLE
`pr-base-commit` does not append a trailing whitespace to the injected message when needed

### ISSUE THREAD

**Issue by DanielMiao1** [refined-github/refined-github#6651]
### Description

The code for the `pr-base-commit` feature that injects the "x commits behind (base commit: 1234567)" message [in the `addInfo` function](https://github.com/refined-github/refined-github/blob/77d3bbb7f5dbbe6bed7828675c1b5ddf7ef4f1fc/source/features/pr-base-commit.tsx#L45) does not currently account for an `Only those with write access ... can merge pull requests` message, causing a missing whitespace character before the word "Only" (see figure 1).

### How to replicate the issue + URL

1. Navigate to an open, non-draft, and non-blocked pull request behind the base branch that you do not have permission to merge (in order to display the write-access message) such as https://github.com/DanielMiao1/test/pull/6
2. Observe the issue:
&nbsp;

**Figure 1**
![figure1](https://github.com/refined-github/refined-github/assets/83146190/e5f6cc69-efe8-49ef-976c-14c6a285b014)

### Extension version

23.5.10

### Browser(s) used

all supported browsers

**Comment by fregante** [comment]
Thank you, one issue is enough:  https://github.com/refined-github/refined-github/issues/6650
