### ISSUE TITLE
An option to align images in diff 

### ISSUE THREAD

**Issue by lwasyl** [refined-github/refined-github#6652]
### Description

Currently, when showing a diff between two images, Github will center them both vertically. It'd be useful for some use cases (like comparing screenshot tests) to align both images to top or to bottom

### Example URLs

https://github.com/mapbox/pixelmatch/pull/51/files#diff-af5ab23f506c169eda6e5e78d0b38b92825a0cade6267e76ba2e3019e4aef13e here the images are the same size, but if they were to differ, both would be centered.

**Comment by fregante** [comment]
I think this is too niche for Refined GitHub, sorry. The good news is that this can already be achieved with a couple lines of CSS.

**Comment by lwasyl** [comment]
Thanks for the response! It turns out this _can't_ be achieved with Refined Github's CSS box due to https://github.com/refined-github/refined-github/issues/6507 (it's the exact same use case btw), and I suppose the solution for me is the same as for the other poster — use a different tool :slightly_smiling_face:
