### ISSUE TITLE
Make the public/private repos more distinguishable

### ISSUE THREAD

**Issue by loikein** [refined-github/refined-github#6656]
### Description

In one's own repository tab, it is hard to decide at a glance which repos are private and which ones are public. These two labels look very similar. Example:

<img width="377" alt="image" src="https://github.com/refined-github/refined-github/assets/20618587/1ed87c83-bc99-4f83-983d-fce3a5816ee3">

In contrast, in repo pages, while still using the same labels, private repos have this little lock icon to clearly indicate that they are private. Example:

<img width="362" alt="image" src="https://github.com/refined-github/refined-github/assets/20618587/4ef611ed-b3d2-4bbd-8514-e2b958b566d8">
<img width="417" alt="image" src="https://github.com/refined-github/refined-github/assets/20618587/3c08d75f-6904-4d9c-85c4-9541d3d0e98d">

I wonder if some improvements can be done to the own repository tab.

Some suggestions on the top of my mind: add a lock icon somewhere around the label; make the Private label a different colour (maybe orange); make the Public label a different colour (maybe green).

Thank you very much!

### Example URLs

`https://github.com/<oneself>?tab=repositories&type=source`

**Comment by thehale** [comment]
Here's the custom CSS for turning the `Private` label orange in the repositories list:

```css
li.private .Label--secondary {
    border-color: var(--color-attention-muted);
    color: var(--color-attention-emphasis);
}
```

And here's a screenshot of how it looks:
![image](https://github.com/refined-github/refined-github/assets/47901316/9260abd3-54e7-427b-9dcf-70a0187fb217)

Changing the label color on the repository page looks like it would need JavaScript since there isn't a `private` CSS class on a parent element of the label.

**Comment by loikein** [comment]
@thehale Thank you so much! This is exactly what I wanted to achieve. I must have missed the class seeing so many level of `div`s…

**Comment by fregante** [comment]
This is now a global issue. The new header completely hides this information and we could restore it:

- private/public
- fork or not
- `repo-avatars`

The problem is that the new header is already crowded.

**Comment by fregante** [comment]
> Here's the custom CSS for turning the `Private` label orange in the repositories list:
> 
> ```css
> li.private .Label--secondary {
>     border-color: var(--color-attention-muted);
>     color: var(--color-attention-emphasis);
> }
> ```

PR welcome. It can be a CSS-only feature without `.tsx` counterpart.
