### ISSUE TITLE
[packages] Add version number next to package in package list

### ISSUE THREAD

**Issue by josh-burton** [refined-github/refined-github#6657]
### Description

When viewing a package, the version number is prominently displayed:

<img width="465" alt="Screenshot 2023-05-17 at 1 47 49 PM" src="https://github.com/refined-github/refined-github/assets/848767/cb3b821a-29d7-451e-968e-74ad43f1caf8">

But this version number isn't displayed in the list of packages:
<img width="1078" alt="Screenshot 2023-05-17 at 1 48 28 PM" src="https://github.com/refined-github/refined-github/assets/848767/dba617e3-52af-407d-b3a5-71cc9adcb7f8">

It would be great to be able to display the version next to each package in the list, to save a few extra clicks.

### Example URLs

https://github.com/orgs/github/packages

**Comment by busches** [comment]
That's not a real example url, since this repo has no packages.

**Comment by josh-burton** [comment]
> That's not a real example url, since this repo has no packages.

I've updated the URL with one that has packages.

**Comment by fregante** [comment]
Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it.
