### ISSUE TITLE
allow copying text confirming repository archive/deletion

### ISSUE THREAD

**Issue by SimonSiefke** [refined-github/refined-github#6661]
### Description

When archiving/deleting a repository, a confirmation prompt is shown where the name of the repository needs to be entered. 
Previously the name could just be copied from above but now the label has `user-select none` which sadly prevents copy/paste.

![confirm](https://github.com/refined-github/refined-github/assets/23744935/570dd9e4-f71c-42b8-a937-932ed9c03c50)

### Example URLs

https://github.com/SimonSiefke/ts-node-esm-bug/settings

**Comment by yakov116** [comment]
It is there for a reason, to prevent mistakes

**Comment by fregante** [comment]
Oof really? I selected and dragged the text all the time. 🤦‍♂️ I’d accept this. 

I think this would be an easy one-line of CSS in refined-github.css

> It is there for a reason, to prevent mistakes

We’re (probably) adults. That guy who lost a 100k-star repo got what he deserved but now we’re all paying for it with a multi-step form already.

If GitHub cared they would just allow undoing deletion within x days, but UI is easier I guess

**Comment by fregante** [comment]
I think they changed this already
