### ISSUE TITLE
Split clean-repo-tabs

### ISSUE THREAD

**Issue by God-damnit-all** [refined-github/refined-github#6662]
### Description

The description:
```text
Moves the "Security" and "Insights" to the repository navigation dropdown. Also moves the "Projects", "Actions" and "Wiki" tabs if they're empty/unused.
```
"Insight" is an extremely useful tab, particularly for a properly ordered list of recent PR merges by date that for some reason GitHub's sorting options in the Pull Requests section doesn't have yet.

If possible I would like to have Insight being hidden be a separate option, maybe a sub-option.

### Example URLs

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
Sorry we don’t split features:

- https://github.com/refined-github/refined-github/issues/5063#issuecomment-965130778

The link is still there, but tucked in the More dropdown
