### ISSUE TITLE
`conversation-activity-filter` causes multiple “Tracked in” overlap

### ISSUE THREAD

**Issue by Nyaasu66** [refined-github/refined-github#6663]
### Elements where the problem occurred
```javascript
// tracked-in-parent-pill-truncated label
document.querySelector("#partial-discussion-header > div.d-flex.flex-items-center.flex-wrap.mt-0.gh-header-meta > div:nth-child(3) > div > div")

// conversation-activity-filter button
document.querySelector("#rgh-conversation-activity-filter-select-menu")
```

### File that cause the problem
I found out that it was caused by this feature by `Identify feature` button:
https://github.com/refined-github/refined-github/blob/main/source/features/conversation-activity-filter.tsx
<img width="696" alt="image" src="https://github.com/refined-github/refined-github/assets/32192232/a8179e49-f3f6-4ed0-bfd5-ed50c60878b1">

### Temporary repair method
Maybe it can be fixed in such an inelegant way:
```css
#partial-discussion-header .tracked-in-parent-pill-truncated {
  z-index: 1
}
```

### How to replicate the issue + URL

<img width="949" alt="image" src="https://github.com/refined-github/refined-github/assets/32192232/1e9d9eb6-97ae-47de-b203-3fe308b6b945">

By accessing [https://github.com/electron/electron/issues/21457](https://github.com/electron/electron/issues/21457) and hovering the cursor over the tracked-in-parent-pill-truncated Label, the bug can be reproduced.

### Extension version

23.5.10

### Browser(s) used

Chrome 113.0.5672.92 (x86_64)

**Comment by fregante** [comment]
I think you picked the wrong button in the identification wizard because the right feature is `clean-conversation-headers`

**Comment by fregante** [comment]
This is the usual weird flexbox behavior that is triggered by overflowing elements. The solution is probably to drop the max-width on that wrapper or see how it looks like without `clean-conversation-headers`: how do native GitHub elements behave?

**Comment by Nyaasu66** [comment]
> This is the usual weird flexbox behavior that is triggered by overflowing elements. The solution is probably to drop the max-width on that wrapper or see how it looks like without [`clean-conversation-headers`](https://github.com/refined-github/refined-github/blob/main/source/features/clean-conversation-headers.tsx): how do native GitHub elements behave?

![Screenshot gif](https://github.com/refined-github/refined-github/assets/32192232/aeeb447b-f4ca-4623-920d-8390e34a95f2)

**Comment by fregante** [comment]
Ohhhh I get it. I’ve never seen that. So yes, the suggested CSS is probably the right solution, unless we can keep the eye itself on z-index:0
