### ISSUE TITLE
keyboard shortcut to navigate between annotations (for example: code coverage) on a pull request

### ISSUE THREAD

**Issue by glyph** [refined-github/refined-github#6664]
### Description

I think #3536 sort of gestured at this but it seemed to be more focused on conversations.  It also says that there are no anchors for these, when they definitely have ids.

My use-case here is that I want to be looking at a diff on a PR with incomplete coverage while I'm editing, hitting 'next annotation' (i.e. "next uncovered line") over and over as I write tests that cover those lines.

### Example URLs

https://github.com/twisted/klein/commit/913130d7996b2e38a7fbb0d4f6b9c7c2db40349c#annotation_11367359288

**Comment by fregante** [comment]
From your description, I don’t see the difference from #3536. https://twitter.com/GHchangelog/status/1397299450712821763 still applies
