### ISSUE TITLE
`infinite-scroll` references an element attribute name that has been changed

### ISSUE THREAD

**Issue by DanielMiao1** [refined-github/refined-github#6669]
### Description

On line 45 of `infinite-scroll.tsx` [(source)](https://github.com/refined-github/refined-github/blob/023b4d2f67255e36f234e24833ad4a13b4e81671/source/features/infinite-scroll.tsx#L45), the following code is used to select the "Explore" sidebar section in the GitHub dashboard (see figure 1 below) and append an element to it:

<code><b><i>select('[aria-label="Explore"]')!</i></b>.append(...</code>

Due to a rename of the `aria-label` attribute from `Explore` to `Explore repositories`, the `select` function now returns a null value, which is prohibited by the non-null assertion operator used in succession to the function call.

If this is the actual cause of the error, the issue can be fixed by changing line 45 of `infinite-scroll.tsx` [(source)](https://github.com/refined-github/refined-github/blob/023b4d2f67255e36f234e24833ad4a13b4e81671/source/features/infinite-scroll.tsx#L45) **AND line 1 of `infinite-scroll.css` [(source)](https://github.com/refined-github/refined-github/blob/023b4d2f67255e36f234e24833ad4a13b4e81671/source/features/infinite-scroll.css#L1)** from `[aria-label="Explore"]` to `[aria-label="Explore repositories"]`.

**Error generated in Chrome**

<pre>❌ <b>infinite-scroll</b>
	📕 23.5.10 → <b>TypeError: Cannot read properties of undefined (reading 'append')</b>
	   at init (refined-github.js:6535:45) <i>select_dom('[aria-label="Explore"]').<b>append</b>(dom_chef.createElement("div", {</i></pre>

**Error generated in Firefox**

<pre>❌ <b>infinite-scroll</b>
	📕 23.5.10 → <b>TypeError: can't access property "append", select_dom(...) is undefined</b>
	   init (refined-github.js:6535) <i>select_dom('[aria-label="Explore"]').append(dom_chef.createElement("div", {</i></pre>

### How to replicate the issue + URL

1. Navigate to the [GitHub dashboard](https://github.com/)
2. The error occurs
&nbsp;

**Figure 1**
_The "Explore" sidebar section in the dashboard and its new `aria-label` in devtools_

![Figure 1](https://github.com/refined-github/refined-github/assets/83146190/b742aa29-79b0-40ed-9077-8257da609dd2)
&nbsp;

**Demonstration**
_The error occurs in the dashboard_

https://github.com/refined-github/refined-github/assets/83146190/0ef355a6-d37d-4b41-b7ac-4ded5ba69ac6

### Extension version

23.5.10

### Browser(s) used

all supported browsers

**Comment by fregante** [comment]
Does this happen only on the "For you" view?

**Comment by jaymehta721** [comment]
No, this also happing in the "Following" view

**Comment by fregante** [comment]
It can be changed to `^="Explore”` so keep compatibility with the older version
