### ISSUE TITLE
`highlight-deleted-and-added-files-in-diffs` broken on single commits

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6678]
### Description

```
refined-github.js:8317 Uncaught TypeError: Cannot read properties of undefined (reading 'cloneNode')
    at highlightFilename (refined-github.js:8317:27)
    at signal.signal (refined-github.js:8343:5)
    at refined-github.js:20154:3
```

Also welcome changes:

- rename to `new-or-deleted-file`
- use API instead of relying on the UI

My guess is that the feature was never intended to run on commits, but just PR commits. I'm also open to just disabling the feature on commits.

### How to replicate the issue + URL

1. https://github.com/refined-github/sandbox/commit/1ed862e3abd13004009927b26355a51a109d6855

### Extension version

23.5.10

### Browser(s) used

Chrome

**Comment by yakov116** [comment]
Using the api would be huge on big prs. Would also be multiple calls sine we done have all the commits on the page. Plus a pr can have more than 100 files if you wanted to load on pr files tab.

Would require an uncashed call sone the files status could have changed by the tile you loaded the files tab again.

**Comment by fregante** [comment]
I think you're confusing this with some other feature, we don't on commits. 

Depending on what's available on the v4 API, this might be as easy as "query current PR, get list of files, check if they're new or deleted", in a single query.

If this isn't as easy as I described I agree it's best to not use the API though.



> Would require an uncached call

That's what happens with the current view we're triggering anyway. The only advantage is that it now comes preloaded when/if the user actually opens the dropdown… but we still have to wait for it anyway, every time.

**Comment by yakov116** [comment]
Sorry I ment to say files not commits.
