### ISSUE TITLE
`restore-file` requires two steps on renamed files

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6679]
### Description

Current situation:

1. Fetches info for the **current** filename in the base commit
2. **Current** filename doesn't exist on base branch
3. Deletes new filename, but does not restore the previous filename
4. UI is updated to show the previous file still being deleted

Expected:

1. We can extract the old filename from the PR UI
2. We have to both delete the new file and re-create the old one.

I think we used to have this code… maybe we removed it because it was too complex

### How to replicate the issue + URL

1. https://github.com/refined-github/sandbox/pull/16

### Extension version

23.5.10

### Browser(s) used

Chrome

**Comment by abotorabjabari** [comment]
#6715 https://github.com/refined-github/refined-github/issues?q=is%3Aissue%20state%3Aclosed%20archived%3Afalse%20reason%3Acompleted
