### ISSUE TITLE
ability to only show non-draft PRs in badge count

### ISSUE THREAD

**Issue by PeerRich** [refined-github/refined-github#6685]
### Description

it would be nice if I can configure refined github so this:
![image](https://github.com/refined-github/refined-github/assets/8019099/7e4f7d9d-0ea8-4a21-a24f-88601df4f745)

only shows non-draft

related: https://twitter.com/peer_rich/status/1660931828503519232

### Example URLs

https://github.com/refined-github/refined-github/pulls

**Comment by fregante** [comment]
https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#2-it-makes-sense-as-a-default-for-everyone

Good idea but not a good fit for Refined GitHub. We tried doing something similar for the `bugs-tab` feature but it was impractical as well.
