### ISSUE TITLE
“Clear filters” doesn’t work due to `hide-user-forks`

### ISSUE THREAD

**Issue by wakamex** [refined-github/refined-github#6687]
### Description

confirmed it doesn't happen if I disable the extension. clicking on Repos doesn't apply the filter. and if I apply it manually, I can also turn it off.
![ezgif com-optimize](https://github.com/refined-github/refined-github/assets/16990562/95140787-7c7f-4e40-b76c-4e27aca39f41)

with it on, the Repo link is hardcoded to include `&type=source` and I can't disable the filter.
![ezgif com-optimize(1)](https://github.com/refined-github/refined-github/assets/16990562/2800bd4f-45ee-49d7-bf58-09abc71dec9b)

I don't see any console errors.

meta questions/comments:
- why is this enabled by default? it hides "real content", my profile is 11/71 source repos. I like contributing to other people's repos. is that not considered "real"? it's those repos I'm most often looking for when I try to browse my profile.
- seems to go against "hiding real content isn't a good default" [here](https://github.com/refined-github/refined-github/issues/6523#issuecomment-1509452295)
- though I don't see that in the [Can you add this feature?](https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22) page. should it be added?
- doesn't a toggle count as an option?
- does it "make sense as a default for everyone"? I'd say a lot less than default activity sort on issues/PRs 😂

### How to replicate the issue + URL

1. https://github.com/wakamex?tab=repositories&type=source

### Extension version

23.5.20

### Browser(s) used

Firefox Nightly 112.0a1 (2023-03-07) (64-bit)

**Comment by fregante** [comment]
It works:

https://github.com/refined-github/refined-github/assets/1402241/8ca6914c-beb4-46f7-8d96-e4accb773773


What you're most likely seeing is a consequence of GitHub being a single-page application. In short, you just need to **reload the tab** for Refined GitHub to load the new options.

Also this feature alters the URL itself, so if you already _are_ on the "no-forks" page, nothing will change even if you disable the extension.

**Comment by wakamex** [comment]
Here's a replication of the issue I'm having. Maybe it's a thing only on more recent Firefox versions? this time on MacOS. previous gifs were on Ubuntu.
https://youtu.be/k56OmbQy7do

**Comment by fregante** [comment]
Ugh sorry once again I misunderstood the report. 😰 I’ll have to read them more carefully. 

Basically the feature is altering the “clear filters” button but shouldn’t. We have another feature (sort by updated time) that works in a similar way, but *does* exclude the “clear filters” button. 

PR welcome to implement the same filter here.
