### ISSUE TITLE
Custom issue link url in the PR title

### ISSUE THREAD

**Issue by max-prtsr** [refined-github/refined-github#6688]
### Description

We're using Linear and not GitHub for issue tracking.
It would be great if I would be able manually configure `PR-1234` replacement to a link `https://linear.app/team/issue/PR-1234`

### Example URLs

Not sure if I got the question, but as example this link could contain `PR-1234` in title
https://github.com/refined-github/refined-github/pull/6609

**Comment by fregante** [comment]
This is natively available to GitHub Pro users: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-autolinks-to-reference-external-resources

As for adding the feature to Refined GitHub, we don't have configurable features:

- https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options

**Comment by devnoname120** [comment]
> This is natively available to GitHub Pro users

@fregante Autolinks don’t apply to PR titles unfortunately, only their body.

Fortunately the list of autolink rules can be retrieved through the `/repos/${owner}/${name}/autolinks` endpoint though. These rules could be applied by Refined GitHub to the PR/issue titles, similar in spirit to the `parse-backticks` feature.
