### ISSUE TITLE
New `rgh-pr-template`: Move the PR template text out of the field

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6697]
### Description

Having to manually delete this text is a bit annoying:

<img width="920" alt="Screenshot 3" src="https://github.com/refined-github/refined-github/assets/1402241/0982e08a-31dc-4d98-b57f-6b372f919001">

It'd be great to extract it:

<img width="920" alt="Screenshot 4" src="https://github.com/refined-github/refined-github/assets/1402241/029ef022-8459-41c9-a82c-922427b0a3f6">

The code would be relatively simple, something like:

```js
observe('that textarea', textarea => {
	const content = /<!--.+-->/.exec(textarea.value)
	textarea.closest('tab-container').before(
		<div style="white-space: pre-wrap;" className="px-2">content</div>
	)
	textarea.value = textarea.value.replace(content, '');
});
```

### Example URLs

https://github.com/refined-github/refined-github/compare/main...commit-range-picker

**Comment by yakov116** [comment]
Definitely not the first time you opened an issue about this.

Have to find the old issue somewhere.

**Comment by fregante** [comment]
Oh yeah that was a long time ago, but the feature was to be applied on every repo and was much more complex. Then GitHub added native "issue templates" but not "pr templates"
