### ISSUE TITLE
Option to filter Github notifications by "is:issue" and "is:pull-request"

### ISSUE THREAD

**Issue by FearlessTobi** [refined-github/refined-github#6699]
### Description

Right now the notification page only seems to allow to filter by `is:issue-or-pull-request`.

There are cases however, where I don't want to filter by both, but just all the issues or all the pull requests in my notifications.
It would be great if this could be added. Thanks!

### Example URLs

https://github.com/notifications

**Comment by fregante** [comment]
This isn't possible in an extension, the filtering happens on GitHub’s servers.

The closest we can get is `select-notifications`
