### ISSUE TITLE
i18n of readme files

### ISSUE THREAD

**Issue by steve02081504** [refined-github/refined-github#6731]
### Description

see also: https://github.com/orgs/community/discussions/50719

You can see that many repo's have not only `README.md`, but also [`README_EN.md`](https://github.com/search?q=README_EN.md&type=code) [`README_CN.md`](https://github.com/search?q=README_CN.md&type=code) and [`README.jp.md`](https://github.com/search?q=README.jp.md&type=code), and [`/docs/README.zh-cn.md`](https://github.com/search?q=README.zh-cn.md&type=code) etc.
These files were created to make the repo easier to understand in different languages, but instead of automatically selecting the appropriate readme file to display based on the viewer's browser language setting, github only pickup `README.md` or `README.txt` which in my point of view is imcomplete and can be improved.
I think we can improve this aspect of performance.

### Example URLs

https://github.com/ukatech/ghost_terminal

**Comment by fregante** [comment]
Unfortunately I don’t think this is common enough to justify the feature in Refined GitHub 🥲

**Comment by steve02081504** [comment]
@fregante I think this need is still relatively common, considering that many star projects like https://github.com/alist-org/alist and https://github.com/tonsky/FiraCode could also provide a better experience with these features
Can you reconsider?
