### ISSUE TITLE
Fix `Prev` link after using `Open all unread` and reloading

### ISSUE THREAD

**Issue by janpio** [refined-github/refined-github#6732]
### Description

When I navigate to the last page of my notification of a repository, then use `Open all unread` to open all the issues from that page, and then reload the page I end up in a weird state where the `Prev` button does not work anymore. Instead, it seems to link to the same page over and over:
<img width="996" alt="image" src="https://github.com/refined-github/refined-github/assets/183673/f139cd7e-cb37-4a69-afee-097e74136be2">

It would be amazing, if Refined Github could fix that in a way that the button still works.

### Example URLs

https://github.com/notifications?after=Y3Vyc29yOjM3NQ%3D%3D&query=repo%3Aprisma%2Fprisma+is%3Aunread

**Comment by fregante** [comment]
> then reload the page

Sounds like it's a state that can easily be avoided and not something we should fix. I'd also just report it to GitHub
