### ISSUE TITLE
Hide "Compare and Pull Request" popup

### ISSUE THREAD

**Issue by port19x** [refined-github/refined-github#6738]
### Description

I'd like to have 2 unrelated branches in the same repo that share no history.
Git itself supports this well through orphan branches, but github get's confused and wants me to PR isntead.
Also see here: https://github.com/orgs/community/discussions/22526

### Example URLs

https://github.com/port19x/dotfiles

**Comment by fregante** [comment]
We can’t just hide the popup, but there’s a plan to make it less invasive.

- https://github.com/refined-github/refined-github/issues/6295
