### ISSUE TITLE
Handle lots of duplicate CI warnings in pull requests

### ISSUE THREAD

**Issue by piegamesde** [refined-github/refined-github#6739]
### Description

Basic problem as described in https://github.com/orgs/community/discussions/16661.

In that ticket I suggested deduplicating identical content, as this would be the best solution for GitHub to implement. However, there are other approaches which may help working around this issue and which may be easier to implement in refined-github:

- Add a button to globally hide all CI annotations for the PR (currently GitHub allows this but only on a per-file basis)
- Collapse large CI annotations, or truncate them with a "show more" button

### Example URLs

https://github.com/magic-wormhole/magic-wormhole.rs/pull/179/files#diff-4007187965c1fea4fd252a76f5f1007b2ea59f6d86e2f454edee547c5036be24L3 the entire file is extremely hard to read

**Comment by fregante** [comment]
I wouldn’t mind hiding them behind a “Show similar” button. GitHub does that for identical comments for example (although Refined GitHub actually hides that button)

**Comment by fregante** [comment]
While I sympathize with the issue:

- you can already toggle the annotations via menu or keyboard shortcut
- not worth (or it's dangerous to) integrating a deduplication logic here
- such a huge number of warnings to me looks like a misconfiguration of CI; the step causing those issues is likely not going to change based on the platform, so it's best to run it once. That's generally the issue with such a request, even if it's not strictly the same issue here 


https://github.com/refined-github/refined-github/assets/1402241/576afa48-e3ab-40b1-a407-75621f8e1812

**Comment by piegamesde** [comment]
> you can already toggle the annotations via menu or keyboard shortcut

AFAIK, this only works on a per file basis, which is really tedious to do on pull requests with many changed files, even with a keyboard shortcut.

> the step causing those issues is likely not going to change based on the platform

I am hitting this in a Rust project, and I need to test its compilation on different platforms with different feature flags. Most of the warnings are indeed identical, but there are differences across targets, for example due to `cfg![]`-gated code. I know of no way to get all the warnings within a single CI pass, and just having the warnings for one of the configurations might miss potential issues.

**Comment by fregante** [comment]
> this only works on a per file basis, 

The shortcut is global

> there are differences across targets

I see, but unfortunately the problem remains: determining what is a duplicate for you and what isn't. 

I'll keep this issue in mind if I figure out an easy solution to the issue, but unless a short PR materializes it's unlikely to be completed.

**Comment by piegamesde** [comment]
Okay, thank you. And what about cutting off long annotations with a "show more" button, how much effort would that be?

**Comment by fregante** [comment]
I’ll reopen this in case anyone wants to send a tentative PR or mockup for a feature that hides duplicates. I think the most complex part would be handling multiple sequences of annotations on the same line, e.g.:

- Ubuntu: expected tab
- Ubuntu: expected semicolon
- Windows: expected tab
- Windows: expected semicolon

I’d expect this to be detected with a single loop and to result into:
 
- Ubuntu: expected tab
- Ubuntu: expected semicolon
- duplicates hidden
