### ISSUE TITLE
Hide deployment success messages

### ISSUE THREAD

**Issue by mrhappyma** [refined-github/refined-github#6742]
### Description

Successful deploy preview messages clutter PR pages with nearly useless messages. This is especially bad when the PR is a draft and new commits are being added (and so a new deploy preview success per commit). Often the deployment service has already commented with a link to said preview, so you are already informed that this is happening. It gets in the way. It adds no value.
![image](https://github.com/refined-github/refined-github/assets/55963440/69cea90d-68c6-41df-b44b-de6deef2c887)
these
get rid of them

### Example URLs

https://github.com/AnswerOverflow/AnswerOverflow/pull/359
Just picked a random one with a lot.

**Comment by mrhappyma** [comment]
Maybe just getting rid of all of them is too broad. This is my first idea, just get rid of them all together. There's a good chance there's a better way to do this.

**Comment by 134130** [comment]
I think It would be nice to have smaller margins for similar jobs to make them look more grouped.

**Before**
<img width="787" alt="image" src="https://github.com/refined-github/refined-github/assets/50487467/a5c21353-90f7-4714-8372-801b3ea7715e">

**After**
<img width="797" alt="image" src="https://github.com/refined-github/refined-github/assets/50487467/4a4c62ab-e2c4-4748-a464-257b1f45dff1">

**Comment by 134130** [comment]
Or add an option at this?

<img width="294" alt="image" src="https://github.com/refined-github/refined-github/assets/50487467/9849f415-bab0-4098-ad38-5cc61306e1d9">

**Comment by mrhappyma** [comment]
> I think It would be nice to have smaller margins for similar jobs to make them look more grouped.

In my mind that's not enough. The important part is the commit messages, and even having the deployment success events grouped like that still draws away from them too much.

> Or add an option at this?

I hadn't seen that menu before. It currently clears for each PR, and on every load. Maybe making that option persist?

**Comment by fregante** [comment]
The request makes sense, but hiding content often means “how do I see it again?” 

The issue of repeating content has appeared frequently here and eventually we defaulted to `conversation-activity-filter`. See:

- https://github.com/refined-github/refined-github/issues/4186#issuecomment-811966004
- https://github.com/refined-github/refined-github/issues/5929#issuecomment-1225583955


Actually we also have `hide-inactive-deployments` which already affects the deployments, except that the repo owner needs to intentionally deactivate them. 

Overall, the two linked discussions still apply, so it’s not something I’m interested in adding. 

———

The “collapsed” style can be achieved with a little CSS, something like

``` css
event:has(deploy-icon) + event:has(deploy-icon) {
  margin-top: -2em
}
```
