### ISSUE TITLE
The extension icon keeps returning to the Safari toolbar

### ISSUE THREAD

**Issue by Finesse** [refined-github/refined-github#6744]
### Description

I don't need the extension icon in the browser toolbar, because it's useless and takes the limited space. So I remove it by customizing the toolbar (not by disabling the extension). But every time Safari or Refined GitHub update, the icon returns back to the toolbar. This is disturbing. Could you please address it?

This issue has been around for a while, with different versions of macOS, Safari and Refined GitHub.

### How to replicate the issue + URL

This is not related to any GitHub page. This is related to the extension in general. Steps to reproduce:

1. Install Refined GitHub for Safari from App Store.
2. Ctrl-click the Safari toolbar, choose «Customize Toolbar...».
3. Drag-n-drop the extension icon outside the toolbar, click «Done».
4. Update Refined GitHub from App Store.
5. Check the Safari toolbar. The icon has returned.

### Extension version

23.5.10

### Browser(s) used

Safari

**Comment by fregante** [comment]
I don’t think there’s anything we can do about this. Report it to Apple, it’s what they decided, it’s annoying and it happens with other extensions that also have that icon

**Comment by Finesse** [comment]
@fregante Thanks for the response. I didn't know it's a Safari bug.

One approach that I saw (AdGuard) is providing 2 extensions from a single application: one for the icon and one for the actual page manipulation. The icon extension can be disabled in the Safari settings, and it doesn't return on its own. Please consider this solution.

**Comment by fregante** [comment]
AdGuard is a native macOS application, we don’t have Xcode developers here who could implement that solution, plus it would probably not be possible to link it the same way (the real reason the icon is there is to support GitHub enterprise users)

The good news is that generally we release to Safari once a month instead of weekly and that you can just cmd-drag it off.

**Comment by Finesse** [comment]
Reported to Apple (feedback id FB12395669)

**Comment by fregante** [comment]
Thank you! I’m annoyed by that behavior too
