### ISSUE TITLE
Add a Preference to allow a user to set the default merge style on a PR

### ISSUE THREAD

**Issue by HeatherLemieux** [refined-github/refined-github#6746]
### Description

Would be nice to be able to globally define the preferred merge style to use by default on an open mergable PR e.g. 
"create a merge", "rebase and merge" "squash and merge".  Github does not have a way to define this it will default to whatever the last used merge style was on a PR, so one off changes mean you have to remember to revert back to your preferred method next time you merge. If configured, the refined github setting would override whatever github sets on the PR automatically. 
<img width="540" alt="image" src="https://github.com/refined-github/refined-github/assets/4631126/1b6b58a8-8a67-491f-937e-5bb566f712a5">

### Example URLs

https://github.com/refined-github/refined-github/pull/6740

**Comment by fregante** [comment]
No preferences allowed in Refined GitHub:

https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options


Related request:

- https://github.com/refined-github/refined-github/issues/5467
