### ISSUE TITLE
Colour favicons based on issue/pr status

### ISSUE THREAD

**Issue by zacps** [refined-github/refined-github#6747]
### Description

It would be nice to have the GitHub favicon colour by PR/Issue state to make it easier to distinguish tabs when you have a lot open.

### Example URLs

https://github.com/refined-github/refined-github/issues/6686

**Comment by fregante** [comment]
GitHub already changes the icon depending on CI status of PRs, as well as dark mode. It’s not practical here to fight GitHub’s logic and offer the many variants necessary for this feature. 

Related requests:

- https://github.com/refined-github/refined-github/issues/6134
