### ISSUE TITLE
Show mentions/references in conversation sidebar

### ISSUE THREAD

**Issue by forivall** [refined-github/refined-github#6750]
### Description

I find that it's quite easy for mentions to get lost in the events of a conversation/discussion (PRs, issues, etc), so when I need to reference to which PR mentions an issue, I often waste time trying to hunt down that mention in among all the commit mentions, other events, etc.

I think it should prioritize references and mentions from the current repo, and group based on kind of object that is mentioning this conversation.

My original idea was https://github.com/refined-github/refined-github/issues/6047, but I think this feature provides a more transformative feature, as it's not just adding new options, rather, it should be able to display mentions in a more useful manner.

### Example URLs

https://github.com/refined-github/refined-github/issues/6686

very rough / unpolished mockup done via web inspector editing:
<img width="644" alt="Screenshot 2023-06-26 at 3 49 36 PM" src="https://github.com/refined-github/refined-github/assets/760204/ec6c2aae-03d8-4c86-828f-939ba44f7220">

**Comment by forivall** [comment]
Sidebar semantic design update:

```
<header>Mentions</header>
<subheader>Issues (1):</subheader>
<ul><li>[issue title][issue number]    [status]</li>...</ul>
<subheader>PRs (2):</subheader>
<ul><li>[PR title][pr number]   [status]</li>...</ul>
<subheader>Commits (2):</subheader>
<ul><li>[Commit message][commit hash]</li>...</ul>
```

**Comment by fregante** [comment]
This sounds useful but also:

- relatively hard to implement
- "breaks" `sticky-sidebar` by potentially making it longer than the viewport

"Better" solutions in both respects would be:

- adding an option to `conversation-activity-filter`
	- but that feature is already "finished" in scope
- add a "collect references" button above the comment box, clicking it would simply move all the references to the bottom
	- but it sounds unusual and also I don't know where to place it. Maybe it can be a button in the sidebar, but still weird.

**Comment by fregante** [comment]
Best done as a separate userscript/extension
