### ISSUE TITLE
`toggle-files-button` is sometimes undone by GitHub

### ISSUE THREAD

**Issue by surfzoid** [refined-github/refined-github#6752]
### Description

code not stay folding with chrome, after a refresh, code reminded unfolded.
with firefox, i don't have anymore the folding button

### How to replicate the issue + URL

https://github.com/surfzoid/QtVsPlayer

### Extension version

23.6.17

### Browser(s) used

chrome

**Comment by fregante** [comment]
Refined GitHub does not do code folding, can you clarify? A screenshot is probably needed

**Comment by surfzoid** [comment]
Sorry, i forgot "files", mean code files folding
![notfold](https://github.com/refined-github/refined-github/assets/20399920/79eae247-0621-42c2-9154-267087d71364)
![folding](https://github.com/refined-github/refined-github/assets/20399920/19d46583-bbcb-406a-86f1-1d21e86e60d8)
.

**Comment by surfzoid** [comment]
in the past, if folding, after refresh or close and reopen browser, it stay folding, now it unfold

**Comment by fregante** [comment]
It seems that GitHub may be opening the list after we collapse it, but not all the time. Try this:

1. Close the list
2. Refresh the page (you might see it open, closed, then open again)
3. Refresh the page (probably open, then it stays closed)


Tested on Safari iOS (zoom 50%)

**Comment by surfzoid** [comment]
you are right, "not all the time"

**Comment by surfzoid** [comment]
Hi, perhaps a clue, i see in your code, line 13 :+1: const wereFilesHidden = new CachedValue<boolean>('files-hidden');

Is there a force cache refresh somewhere? is state memorized in a cookie?

**Comment by fregante** [comment]
No. As previously mentioned, we successfully close the list and GitHub reopens it afterwards.

**Comment by surfzoid** [comment]
> No. As previously mentioned, we successfully close the list and GitHub reopens it afterwards.

Is there workaround, something like, "wait github finish" then "close the list"?

**Comment by fregante** [comment]
There is a workaround, someone just needs to send a PR.

**Comment by fregante** [comment]
Closing because the feature is broken entirely 

-
