### ISSUE TITLE
Select organization when forking to do a web based fix

### ISSUE THREAD

**Issue by piranna** [refined-github/refined-github#6756]
### Description

When willing to do an in-place edit for a third party project by clicking the edit button, first a fork is being done. It ask to confirmo before doing It, but only allows to do the fork in the personal account. I would like a dropdown to be shown to select to do the editing fork in one of my organizations.

### Example URLs

https://github.com/refined-github/refined-github/edit/main/readme.md

**Comment by fregante** [comment]
This used to be easier I think. Unfortunately this is too complex for Refined GitHub and it’s for relatively niche need.
