### ISSUE TITLE
Create PR a directly from in-place edits

### ISSUE THREAD

**Issue by piranna** [refined-github/refined-github#6757]
### Description

Related to https://github.com/refined-github/refined-github/issues/6756, i would like to get a PR directly done when doing an in-place edit, instead of showing me the commit and needing to create the PR by hand.

### Example URLs

https://github.com/refined-github/refined-github/edit/main/readme.md

**Comment by fregante** [comment]
After editing a file o a new repo you’re immediately shown a form to create a PR, where you can confirm with one click. I don’t think it’s worth optimizing this step because most people should add more information to the PR body.

**Comment by piranna** [comment]
For single commit PRs, the PR body IS mostly equal to the commit body, that's why i think they can be done directly.
