### ISSUE TITLE
Showing the last update time in links?

### ISSUE THREAD

**Issue by jcelerier** [refined-github/refined-github#6758]
Heya,
I am wondering if there would be a way to use Refined Github to show the last update time when showing a link to a Github repo.

e.g. for instance: given some URLs listed in some random web pages:

    https://github.com/emilk/loguru
    https://github.com/mattiasflodin/reckless

I'd like to see something like: 

   [emilk/loguru (last update: 3 months ago)](https://github.com/mattiasflodin/reckless)
   [mattiasflodin/reckless (last update: 2 years ago)](https://github.com/mattiasflodin/reckless)
   
without having to click on the link to see if the project is active

**Comment by fregante** [comment]
It might make sense in a hovercard but I still don’t think it would be useful to justify a new feature that requires an API call.
