### ISSUE TITLE
Show automerge indicator in Notifications list

### ISSUE THREAD

**Issue by rarkins** [refined-github/refined-github#6760]
### Description

Display a visual indicator for PRs in Notifications which have GitHub's automerge enabled.

e.g.

![image](https://github.com/refined-github/refined-github/assets/6311784/d55c86f7-47df-43dd-b2a0-81ce97b8e96c)

### Example URLs

It would show on this page: https://github.com/notifications

**Comment by fregante** [comment]
I don’t think it's worth querying every PR list we ever visit for the offchance that _at pageload time_ auto-merge is active.

However there's good news: you can enable the native merge queue and you GitHub will add that indicator

<img width="530" alt="Screenshot 8" src="https://github.com/refined-github/refined-github/assets/1402241/6cf9821d-5730-4280-9e27-83e856773fda">

**Comment by rarkins** [comment]
@fregante thanks, although I believe you've screenshot a different page (repo pulls) not notifications. Hopefully GitHub add this indicator to Notifications then like they've done to the Pull Requests list

**Comment by fregante** [comment]
Oh you're right. Since that feature is in beta, you can find its Discussion somewhere and mention the need to show this in the notifications page
