### ISSUE TITLE
Show diff stats in PR's file tree

### ISSUE THREAD

**Issue by xxchan** [refined-github/refined-github#6762]
### Description

Like `git diff --stat`. It would be helpful to know what files are large, so that we can review them first (or last).

<img width="1137" alt="image" src="https://github.com/refined-github/refined-github/assets/37948597/6e8e6d1a-e595-4cfc-98ee-819d147a98bc">

[Gitako](https://github.com/EnixCoda/Gitako) support this:

<img width="281" alt="image" src="https://github.com/refined-github/refined-github/assets/37948597/548ec97c-5d35-4d4a-a992-44012df10169">

### Example URLs

`/pull/.../files`

`https://github.com/refined-github/refined-github/pull/6733/files`

**Comment by xxchan** [comment]
Another idea: maybe add a button to collapse all files in PR view

**Comment by fregante** [comment]
Alt-click a file header to collapse all files, you'll already see this:

<img width="412" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/1fe9c3eb-acde-42b2-8c43-7e8d8fc7b1d1">

It's not exact with lined removed/added, but it still counts the "lines changed"

**Comment by andybergon** [comment]
Would you reconsider this for GitHub’s current Files changed view?

The existing Alt-click workaround requires collapsing every diff and changes the current review state. It also does not help while actively reviewing with files expanded.

On a PR with 1,000 changed lines, I want to distinguish at a glance between ten roughly 100-line files and one large generated or configuration file plus many small source changes. Those shapes call for different review strategies, but the current tree makes them look identical.

A compact total or Gitako-style green/red bar beside each file would provide that overview without taking much width. Exact `+N/-N` values could appear in a tooltip or only when the tree is wide enough. The per-file numbers already appear in file headers, so this would primarily surface existing information.

Would a narrowly scoped implementation for the current UI be considered?
