### ISSUE TITLE
Enable `one-key-formatting` in Discussions

### ISSUE THREAD

**Issue by flatcap** [refined-github/refined-github#6768]
### Description

`one-key-formatting` doesn't work in the Title or Body of Discussions.

Steps:
- Highlight a word in the title, then hit <kbd>*</kbd>
- Highlight a word in the body, then hit <kbd>*</kbd>

Once a Discussion is created, it _does_ work in the comments. 

Thanks!

### Example URLs

https://github.com/neomutt/neomutt/discussions/new?category=development

**Comment by fregante** [comment]
Indeed. It's tracked in https://github.com/refined-github/github-url-detection/issues/175
