### ISSUE TITLE
Reverse chronological ordering of PR updates

### ISSUE THREAD

**Issue by armcknight** [refined-github/refined-github#6769]
### Description

With a sufficiently long PR (which happens easily the more bots/reviewers are involved) you always have to scroll to get to the newest information.

It would be nice to have the most recent comments/updates near the top, underneath the description, to avoid always having to scroll down to see them.

### Example URLs

https://github.com/refined-github/refined-github/pull/3007

I would like to be able to see its locked status, first release containing the changes, and most recent message without having to scroll to the bottom.

**Comment by fregante** [comment]
This is hard to get right due to the DOM and ajaxed-in updates. Not something worth for Refined GitHub to mess with
