### ISSUE TITLE
Link to repositories and members in account hover in navigation bar

### ISSUE THREAD

**Issue by DFelten** [refined-github/refined-github#6771]
### Description

In the hover of the GitHub account name in the navigation the number of repositories and members is shown. Both unfortunately without links. It would be useful if they link to the overview of repositories and members.

<img width="392" alt="CleanShot 2023-07-14 at 14 02 44@2x" src="https://github.com/refined-github/refined-github/assets/1169185/e868cf87-aa5f-49b8-99d7-e5b7866252f0">

### Example URLs

https://github.com/refined-github/refined-github

**Comment by DFelten** [comment]
As far as I see there is no way to go to the repository overview from an other repo. 

For example when you're here: https://github.com/refined-github/refined-github

First you need to select the name `refined-github` in the navigation bar and after this select the [repo overview](https://github.com/orgs/refined-github/repositories?type=source). This is an extra page that needs to be loaded whenever I want to get to the overview from a repo.

**Comment by fregante** [comment]
?

The page I took a screenshot of is the one that appears when you click on the refined GitHub organization name.

**Comment by DFelten** [comment]
Ok, you're right, sorry. The example was bad. We do not have an overview of the repos on the overview page for our organization account. Therefore, I always had to go two pages further there.

**Comment by fregante** [comment]
> We do not have an overview of the repos on the overview page for our organization account

I don't understand what you mean. The overview is the default, there's nothing to set and nothing to change. You cannot alter the two areas I highlighted in the screenshot. The only part you can change is the pinned repos and that's not what you're talking about.

The [Overview](https://github.com/refined-github) and the [Repositories](https://github.com/orgs/refined-github/repositories?type=source) tabs show **the exact same content in the same exact order**. It's literally the same view except that Overview has Pinned repos and a sidebar.

<table>
<tr>
 <th>Overview
 <th>Repositories
<tr>
 <td><img width="1023" alt="Screenshot 1" src="https://github.com/refined-github/refined-github/assets/1402241/abf90ffc-6c04-4683-ab7c-a89f6f00d44f">
 <td><img width="1023" alt="Screenshot 2" src="https://github.com/refined-github/refined-github/assets/1402241/bfced2c6-73f1-42ac-a041-082cefedde71">
</table>

**Comment by DFelten** [comment]
A new organization has not overview of repositories. Even with repositories there is a list of todos visible. 

![image](https://github.com/refined-github/refined-github/assets/1169185/386f2bfc-e5dc-44eb-b2de-72cac63fd29d)

Anyway, thanks for the feedback.

**Comment by fregante** [comment]
Well, yeah, it has no repos. 

![IMG_1442](https://github.com/refined-github/refined-github/assets/1402241/b29f87e0-7735-4575-9ec2-678af448d957)

**Comment by DFelten** [comment]
I have already shown the proposal. If you don't like it, then it doesn't have to be implemented. This is getting exhausting here.
