### ISSUE TITLE
Publish release confirmation

### ISSUE THREAD

**Issue by Elsie19** [refined-github/refined-github#6774]
### Description

When editing a draft release, the release button should really have an extra confirmation before it goes ahead and makes the release. It's way to easy to accidentally click it instead of the <kbd>Save draft</kbd> button.

### Example URLs

I can't send any URLs because github won't let people see release drafts for any repository unless they are owners of it, but I have an image.

![image](https://github.com/refined-github/refined-github/assets/58742515/5ab9a4f0-4f45-4771-a054-c329df788618)

**Comment by fregante** [comment]
We haven’t added any confirmations anywhere in Refined GitHub and this is a reversible action most of the time. 

If it’s important to you, I suggest writing a small userscript that looks like:

```JavaScript 
document
.querySelector('the release form')
.addEventListener('submit', event => {
  if (!confirm('Sure?')) 
    event.preventDefault()
})
