### ISSUE TITLE
"Wait for checks" checkbox still appears after I remove all workflow push triggers

### ISSUE THREAD

**Issue by samsalisbury** [refined-github/refined-github#6775]
### Description

**What happens:**
If I open a PR that introduces a push trigger, then things work as expected (I see the "wait for checks" checkbox). If later in that PR I remove the push trigger, then the "wait for checks" checkbox still appears, and is checked by default, even though there are no longer any checks expected to run on the branch. This makes it hand forever if I forget to uncheck the box.

**What I would expect:**
If I remove triggers on my PR branch so that no workflows run, I would expect the checkbox not to show up, or at least to be unchecked by default.

**Background**
This is a pattern I use to test GHA workflows as I develop them:

1. Open PR with schedule trigger (or some other trigger that doesn't run on push), work on the code.
2. When ready to test add a temporary commit adding a `push:` trigger.
3. Keep pushing code until I get a workflow run that looks right.
4. Revert the temporary commit as we don't want a push trigger on main.
5. Merge the PR to main <- This is where the problems arise, I don't see the checkbox and I'm waiting forever for the merge to complete.

The example PR is private so I can't provide a link sorry.

### How to replicate the issue + URL

This appears on PR URLs of the form: `https://github.com/[owner]/[repo]/pull/[pr_number]`

### Extension version

23.6.17

### Browser(s) used

Safari 16.5.2

**Comment by fregante** [comment]
It’s a Refined GitHub feature. We add it to all repos and it works differently (see the “info” icon)
