### ISSUE TITLE
Add keyboard shortcut to start a new code space

### ISSUE THREAD

**Issue by jonashaag** [refined-github/refined-github#6777]
### Description

`.` opens an editor. If you want to work on the repo using a code space, you'll need to press additional buttons in the `.` VS Code instance.

Would be nice to have a shortcut to go directly to a code space for the repo.

### Example URLs

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
I don’t think that's quite possible since there might be multiple code-spaces on a repo
