### ISSUE TITLE
Missing settings?

### ISSUE THREAD

**Issue by jsumners** [refined-github/refined-github#6785]
### Description

👋 I just installed this extension on a new system and the settings panel seems to be missing, uh, a lot of settings. 

<details>
<summary>Gif</summary>

![missing-settings](https://github.com/refined-github/refined-github/assets/321201/6ac93c04-8716-43df-99f5-9361f2bc54d6)

</details>

### How to replicate the issue + URL

`vivaldi://extensions/`

### Extension version

23.7.8

### Browser(s) used

Vivaldi 6.1.3035.100 (Stable channel) (arm64)

**Comment by fregante** [comment]
Scroll up 😃 

I’m not sure why Vivaldi scrolls down

**Comment by jsumners** [comment]
Thank you macOS for hiding the damn scroll bars. It's very helpful and not at all mysterious.

![image](https://user-images.githubusercontent.com/321201/98861539-6ddc0580-2433-11eb-910e-c05ae1fc129c.png)
