### ISSUE TITLE
Show file sizes for files and folders

### ISSUE THREAD

**Issue by fry9** [refined-github/refined-github#6786]
### Description

https://github.com/harshjv/github-repo-size
Maybe better format on the units with fewer numbers, like: 23.8 MB, 243 KB, 321 B.

![gitImg](https://github.com/refined-github/refined-github/assets/32324114/ebad6544-d819-4438-ac09-f2552d3fde6a)

### Example URLs

https://github.com/harshjv/github-repo-size

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/2431
