### ISSUE TITLE
Add a button to get random issue on Issues tab

### ISSUE THREAD

**Issue by ntindle** [refined-github/refined-github#6789]
### Description

Add a button to return a random issue on the Issues page

### Example URLs

https://github.com/refined-github/refined-github/issues

**Comment by fregante** [comment]
Funny but I don’t think that there’s a way to actually go to a random “issue”. The best I can think of would be to find the last issue/PR and find a number between that and 1. That would land you on a random issue or PR that might already be closed (or even deleted); it doesn’t sound very useful.

**Comment by ntindle** [comment]
Fair, yeah I was imagining it only be open issues. Here’s a bash script that accomplishes something similar if anyone else comes across this later: https://gist.github.com/ntindle/0e23168494b04659296a900111bc8409
