### ISSUE TITLE
Opening an actions run causes duplicate `repo-avatars`

### ISSUE THREAD

**Issue by uncenter** [refined-github/refined-github#6790]
### Description

After going to a specific actions run in a repository, like `user/repo/actions/runs/<run>`, clicking on any other repository tabs (and some links) causes the avatar to be duplicated. 

![image](https://github.com/refined-github/refined-github/assets/47499684/cde620e5-b452-4c9d-8c0e-7b2db044b6c6)

https://github.com/refined-github/refined-github/assets/47499684/360e36b4-72de-4750-801c-d561c6c853f1

### How to replicate the issue + URL

1. Go to https://github.com/fregante/GhostText/actions/runs/5538535691?pr=289 or any other Actions run.
2. Click the any other tab without reloading, like the Issues or Code tabs.
3. See duplicated avatars!

### Extension version

23.7.25

### Browser(s) used

Firefox

**Comment by fregante** [comment]
Thank you! I’ll disable the feature in a moment 🥲

**Comment by uncenter** [comment]
If/when it gets renabled, I think we should consider maybe redesigning it somehow... the redesigned GitHub layout makes the avatar look awkward next to the GitHub logo.

**Comment by fregante** [comment]
See https://github.com/refined-github/refined-github/pull/6788, it was just moved up there.

Redesigned how?

**Comment by uncenter** [comment]
> Redesigned how? I don't think we can do much about it; however you slice it, it's a _yet another blob_ on the header. In the last PR I made it smaller and closer to the repo owner name, but other than that I don’t think we can really "redesign" it. See [#6788 (comment)](https://github.com/refined-github/refined-github/pull/6788#discussion_r1271276536)

I'm not entirely sure either. I've been thinking about it and if I have any ideas for improvements I'll make a PR.

**Comment by fregante** [comment]
This could be an option but I think it's a bit much

<img width="384" alt="Screenshot 2" src="https://github.com/refined-github/refined-github/assets/1402241/438515e2-5668-41fb-94ec-a3f988b64df1">
