### ISSUE TITLE
Bring back repo stars on top

### ISSUE THREAD

**Issue by sedghi** [refined-github/refined-github#6798]
### Description

In the old github ui we were able to see the number of stars and number of forks on top and they were visible on code/issue/PR.

![image](https://github.com/refined-github/refined-github/assets/7490180/61b1e2f7-7006-4b0c-8a87-eda17efd4117)

Right now it is not possible and only visible in the repo home page. It is awful since when you search in github and click on a link and go to the code you basically can't understand if the code is from a repo with 1 star or a very well reputed repo. 

Can we please have stars back on the top again?

### Example URLs

(I always have issue understanding what you require here, a REAL URL). I'm just proposing a feature and I have screenshots above. But anyway for instance on your home page

https://github.com/refined-github/refined-github

It should look like

![image](https://github.com/refined-github/refined-github/assets/7490180/8f42b74e-b19c-400f-8043-bd73875a6591)

**Comment by fregante** [comment]
Definitely not forks since Refined GitHub has always hidden the fork count up there https://github.com/refined-github/refined-github/issues/1601

I’d consider restoring the star count (count only, no button) and fork status (link to source) next to the repository name, but I’m afraid of making the header too busy.

**Comment by slorber** [comment]
Hey

Just wondering, is there a way to keep showing the number of stars/forks in their original place?

Having the ability to show/hide in a new place is nice, but what about disabling this entirely and keep the original UI if we prefer it?

![CleanShot 2023-09-26 at 11 28 44@2x](https://github.com/refined-github/refined-github/assets/749374/e1914b0c-75ac-4e43-b242-acb321de7249)

**Comment by fregante** [comment]
The two features are unrelated. See the pinned post
