### ISSUE TITLE
`hide-low-quality-comments` hides comment by owner

### ISSUE THREAD

**Issue by tommy-mitchell** [refined-github/refined-github#6799]
### Description

Hidden comment:

<details>
<summary>Large image</summary>

![329F6369-7E49-4A22-AA77-215C41F45E7B](https://github.com/refined-github/refined-github/assets/1403701/5bc80a1e-98ef-46fa-a618-a7273f2e5b8c)

</details>

Revealing shows it’s by a maintainer:

<details>
<summary>Large image</summary>

![E03C341C-714E-4BB2-8818-27ADD7A706D4](https://github.com/refined-github/refined-github/assets/1403701/5c17166a-9907-4bed-84d2-d98ed7271114)

</details>

### How to replicate the issue + URL

https://github.com/sindresorhus/type-fest/issues/621

### Extension version

23.6.17

### Browser(s) used

Safari iOS 16.3

**Comment by fregante** [comment]
The check stopped working:

https://github.com/refined-github/refined-github/blob/0d219e911276786579550b6278b34b0be84396b5/source/features/hide-low-quality-comments.tsx#L62
