### ISSUE TITLE
In firefox failed gh jobs don't go to top like in chrome

### ISSUE THREAD

**Issue by nitzcard** [refined-github/refined-github#6800]
### Description

In firefox failed gh jobs don't go to top like in chrome:

firefox - 
![image](https://github.com/refined-github/refined-github/assets/123297447/71ddf539-9c86-4ce7-ab17-6c51b3dc650b)

chrome- 
![image](https://github.com/refined-github/refined-github/assets/123297447/ef7e1b10-3129-4459-b0e1-2a45af47e19c)

### How to replicate the issue + URL

I can't 	

### Extension version

23.7.25

### Browser(s) used

Firefox

**Comment by fregante** [comment]
Firefox doesn’t support this feature:

- https://github.com/refined-github/refined-github/pull/5858
- https://github.com/refined-github/refined-github/issues/5797

**Comment by nitzcard** [comment]
thanks ufffff
