### ISSUE TITLE
Select "closed as unplanned" issues in notifications page

### ISSUE THREAD

**Issue by melissawm** [refined-github/refined-github#6801]
### Description

Currently, when selecting notifications by status, one can choose "Open", "Closed", "Merged" or "Draft" - but this does not select issues marked "Closed as unplanned":

<img width="886" alt="Screenshot 2023-07-31 at 09 55 45" src="https://github.com/refined-github/refined-github/assets/3949932/cf4c7290-851c-410c-99eb-2061295f3834">

Ideally, this would be a new item in the Status to be selected, but these issues could also be selected in the "Closed" status.

### Example URLs

--

**Comment by fregante** [comment]
“Closed” should indeed also select “closed as unplanned”. PR welcome
