### ISSUE TITLE
Include required PAT scopes on the Welcome issue

### ISSUE THREAD

**Issue by luc122c** [refined-github/refined-github#6802]
### Description

It would be super helpful if the Welcome issue #3543 would list the required scopes for the PAT and perhaps even include the link to [generate one](https://github.com/settings/tokens/new?description=Refined%20GitHub&scopes=repo,delete_repo,read:project) that is in the options.

### Example URLs

https://github.com/refined-github/refined-github/issues/3543

**Comment by fregante** [comment]
Thank you for the suggestion, but that information is already present exactly where the token is requested, so there’s no need to duplicate it.
