### ISSUE TITLE
Enable `pr-commit-lines-changed` on non-PR commits

### ISSUE THREAD

**Issue by mausch** [refined-github/refined-github#6810]
Hi and thanks for this project!
I installed refined-github looking for this feature: https://github.com/refined-github/refined-github/issues/2326
Has this feature been removed? I can't seem to find where this is displayed.

Thanks

**Comment by fregante** [comment]
Did you set a token in the options? Any errors in the console? It works for me

**Comment by mausch** [comment]
Cheers, I was missing the token :+1:

**Comment by fregante** [comment]
Actually this information already appears on single commits, just not in the same format: https://github.com/refined-github/refined-github/commit/7e8bb264cda190a5ce2e09e51196cb8f4b230696

<img width="844" alt="Screenshot 2" src="https://github.com/refined-github/refined-github/assets/1402241/76474929-2edb-4367-b134-3dcd796c01dd">
