### ISSUE TITLE
refined github throws error on `New Repository Overview`

### ISSUE THREAD

**Issue by imranbarbhuiya** [refined-github/refined-github#6818]
### Description

When enabling `New Repository Overview` feature, refined github throws 
```console
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'title')
    at extractCurrentBranchFromBranchPicker (refined-github.js:3455:57)
    at refined-github.js:4646:81
    at async CachedFunction.updater (refined-github.js:4645:121)
    at async getSet (refined-github.js:2344:30)
```

### How to replicate the issue + URL

enable `New Repository Overview` and visit any repository 

### Extension version

23.8.3

### Browser(s) used

chrome

**Comment by fregante** [comment]
Nice, this view removes the last non-react file list. Hopefully it's the same component as the one they used in folders like https://github.com/refined-github/refined-github/tree/main/build
