### ISSUE TITLE
Strip '$ ' from start of code lines when copying

### ISSUE THREAD

**Issue by brzzdev** [refined-github/refined-github#6819]
### Description

It is quite common practice to use a $ at the start of each line in a code block to signal that it's a terminal command.
E.g:
`$ brew install example`
`$ docker pull example`
When using the built-in GitHub copy button, it includes the '$ ', then if you paste that into your terminal (in this example zsh) you will get the error
`zsh: command not found: $`
For single line commands, this can, of course, be worked around by just selecting the command text.
But when copying multiline strings this isn't possible.

An option to strip '$ ' from the start of lines when using the copy button would be really useful.

### Example URLs

https://github.com/samschott/maestral

Multiple examples of multiline commands in this repo. Undoubtedly, there's probably a better example with even more lines.

**Comment by fregante** [comment]
I'm not comfortable with silently altering user content. I'd advise adding a `$` alias to your cli. This might work:

```
alias "$"=""
```
