### ISSUE TITLE
Make it possible to show everyone who reacted to a comment 

### ISSUE THREAD

**Issue by Janik-Haag** [refined-github/refined-github#6820]
### Description

Currently github lists the names of people who reacted with a specific emoji if you hover over the icon and says something like `$name1, $name2 ... and 3 more reacted with thumbs up emoji` and it would be cool to see everyone that reacted. This is possible in the mobile app or with this api call: 

```bash
gh api \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  /repos/org/repoissues/comments/idreactions
```

### Example URLs

for example [here](https://github.com/RIPE-NCC/ripe-atlas-software-probe/issues/83#issuecomment-1673037798) the reactions get cut off.

**Comment by fregante** [comment]
Showing everyone isn't worth it? It would require too many API calls for every reacted comment
