### ISSUE TITLE
Cannot disable dimming passed CI checks.

### ISSUE THREAD

**Issue by LilithHafner** [refined-github/refined-github#6822]
### Description

<img width="982" alt="Screenshot 2023-08-13 at 7 03 54 PM" src="https://github.com/refined-github/refined-github/assets/60898866/6897d798-e7bc-41b5-8189-48c4f15fa7ba">

Passed CI checks are dimmed, I want to disable this feature, and it is not possible to detect this feature with the "identify feature" tool.

### How to replicate the issue + URL

Go to a PR with some passed and failed tests (e.g. https://github.com/JuliaLang/julia/pull/44869). Notice that the passed tests are dimmed. Revoke the refined-github extension's permissions at the browser level and notice that the passed tests are not dimmed. Use "identify feature" tool and notice that it fails to detect the feature.

### Extension version

23.8.3

### Browser(s) used

Chrome

**Comment by busches** [comment]
This is a CSS only feature and not able to be disabled. You can override the below CSS to disable it.

https://github.com/refined-github/refined-github/blob/main/source/features/clean-checks-list.css#L25-L29

**Comment by LilithHafner** [comment]
That solves my problem. I have successfully disabled the feature. However, my experience was not great with this, due to issues #5668 and #6827.

**Comment by fregante** [comment]
> I want to disable this feature

Can I ask why?
