### ISSUE TITLE
Make it easier to disable CSS-only features

### ISSUE THREAD

**Issue by LilithHafner** [refined-github/refined-github#6827]
### Description

I'd like to more easily disable CSS-only features like https://github.com/refined-github/refined-github/blob/main/source/features/clean-checks-list.css. Disabling these per-file would be great, as it is much easier to partially replace a disabled feature with custom CSS than to restore existing behavior by overwriting an unwanted feature.

Sndergizes with #5668

**Comment by fregante** [comment]
CSS-only features are by definition not disableable. Their injection is handled by the browser. 

Controversial features have been made disableable, but some CSS will never become optional

**Comment by LilithHafner** [comment]
It is often unclear to package authors which features users will like or dislike (#6822 being one such example). I encourage you to make it easy for users to opt out of any or all features.

One added benefit of making it easier to opt out of any or all features is fixing the underlying issue in #5668. 

Another added benefit is making it viable for folks to use refined-github exclusively for a single feature or two. Right now, if someone really likes a single feature of refined-github but doesn't want sweeping changes to their experience, that feature is not available to them at all because they can't use refined-github without lots of less documented and difficult-to-disable UI changes.
