### ISSUE TITLE
Add a 'Copy links' button next to 'Open all' button

### ISSUE THREAD

**Issue by lyqht** [refined-github/refined-github#6836]
### Description

I would like a feature where I can copy links easily to the GitHub PRs that I would like my reviewers to approve. 

An example mockup

![CleanShot 2023-08-16 at 18 20 26](https://github.com/refined-github/refined-github/assets/35736525/18d3fa29-b289-43d2-84db-8079a648174b)

Clicking it should result in a text with links like this copied to clipboard

### Expected result

[[PostDesigner] Update preview wallpaper](https://github.com/padlet/rn-mobile-app/pull/2301)
[Add color scheme prop to post view](https://github.com/padlet/rn-mobile-app/pull/2300)
[[PostView] Add color prop](https://github.com/padlet/rn-mobile-app/pull/2299)
[[PostView] Add scheduled at banner](https://github.com/padlet/rn-mobile-app/pull/2297)

### Example URLs

https://github.com/lyqht/repo/pulls/lyqht

**Comment by fregante** [comment]
While interesting, I don’t think the action is common enough to justify yet another button on that busy line 🥲
