### ISSUE TITLE
`linkify-code` should not run on truncated links

### ISSUE THREAD

**Issue by Katsute** [refined-github/refined-github#6841]
### Description

`linkify-code` linkifies incomplete (truncated) URLs.

The extension should probably avoid linkifying links that are followed by an ellipsis `…`

### How to replicate the issue + URL

Search for code where GitHub truncates a link

https://github.com/search?q=repo%3AKatsuteDev%2FBackground+marketplace&type=code

[![image](https://github.com/refined-github/refined-github/assets/58778985/744d7aef-2dd1-4fe1-a0da-6c45c56c76d2)](https://github.com/search?q=repo%3AKatsuteDev%2FBackground+marketplace&type=code)
↑

### Extension version

23.8.3

### Browser(s) used

Google Chrome 115.0.5790.173

**Comment by fregante** [comment]
It would be nice, but detecting a broken URL might be impractical. PR welcome

**Comment by Katsute** [comment]
I thought it would be a simple as modifying the selector with a `:has(+` or `:not(:last`, but yea, this feature runs through the `linkify-urls`.

Could be fixed if we append `(?!…)` to the regex, however I don't see any way to change the regexp in the lib.

I'll leave this issue open in case anyone finds another solution, or if linkify is implemented internally.

**Comment by fregante** [comment]
Can you open it on `linkify-URLs`? That library could skip links followed by `…` or `...`

**Comment by Katsute** [comment]
Implemented in #6844 by checking if the document fragment containing the linkified URL ended with `…`
