### ISSUE TITLE
`list-prs-for-file`: drop down covered by code

### ISSUE THREAD

**Issue by tonglil** [refined-github/refined-github#6845]
### Description

List of PRs is being covered by code.

<img width="283" alt="image" src="https://github.com/refined-github/refined-github/assets/3250776/52d9ba2f-73ca-4755-8fee-128bfcbd88db">

<img width="1367" alt="image" src="https://github.com/refined-github/refined-github/assets/3250776/6e61e632-0a4f-4456-97ef-e2b353d5936a">

### How to replicate the issue + URL

https://github.com/hashicorp/vault/blob/main/go.mod

Or any file page that has more than 2 open PRs against it.

### Extension version

23.8.3

### Browser(s) used

Firefox

**Comment by fregante** [comment]
Sure. I also see `previous-version` peeking through 😮 

<img width="271" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/5fb67a86-a8f8-4083-a178-f58fd1ec67ae">

Test on:

https://github.com/refined-github/sandbox/blob/default-a/README.md

**Comment by Askath** [comment]
Found the issue for previous-version already and fixed it.

**Comment by fregante** [comment]
Just open the PR when ready 🎉

**Comment by fregante** [comment]
<img width="711" alt="Screenshot 7" src="https://github.com/refined-github/refined-github/assets/1402241/84373fe2-d007-4a70-b37d-06cbcffc60eb">

<img width="289" alt="Screenshot 6" src="https://github.com/refined-github/refined-github/assets/1402241/f1e0bda5-3acc-4cbd-94f5-e94f7036a919">


```css
.container:has(> #StickyHeader.react-code-view-header--wide) {
	position: relative;
	z-index: 1;
}
```

I'm stumped as to why this works, but placing `z-index` on any of its ancestors will not. There's no `transform`, `position`, nor `opacity` on any of them.

I'm concerned about targeting such a big element, I'm sure it will cause further issues down the line (as every `z-index` fight does)

**Comment by Askath** [comment]
I have also playing around for a bit more but don't see a way how to fix it without throwing down a z-index.
But I am also clueless about why exactly that issue occurs too.
