### ISSUE TITLE
Textarea shortcut to add rich content

### ISSUE THREAD

**Issue by jd-solanki** [refined-github/refined-github#6846]
### Description

Hi 👋🏻 

Can we add shortcuts like below for textarea: note, imp, warning?
![image](https://github.com/refined-github/refined-github/assets/47495003/133ab7c2-578e-4e08-8ec5-42a80ec4f905)

https://github.com/orgs/community/discussions/16925

### Example URLs

Issue page, project: https://github.com/refined-github/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by fregante** [comment]
The shortcuts already exists in the form of Saved replies
