### ISSUE TITLE
Add a second "Viewed" checkbox after file diffs that are larger than screen height

### ISSUE THREAD

**Issue by ofirnk** [refined-github/refined-github#6848]
### Description

When reviewing a PR with large file diffs and wanting to mark the file as "viewed" - you'd need to:
1. Scroll all the way down (to view the file diff)
2. Scroll all the way up (to mark as viewed)

What I suggest is to add a second "viewed" button at the end of the file view.

[ I think it also makes sense to duplicate the whole raw where the filename, "viewed", and comment ] 

### Example URLs

https://github.com/refined-github/refined-github/pull/1750/files

**Comment by 134130** [comment]
The `file-header` is already sticky that you can click `viewed` button at the end of the file view.

<img width="800" alt="image" src="https://github.com/refined-github/refined-github/assets/50487467/4bddb7bc-d35c-487d-aff8-f5ed54001e1e">

**Comment by fregante** [comment]
As @134130 said

**Comment by ofirnk** [comment]
> The `file-header` is already sticky that you can click `viewed` button at the end of the file view.
> 

Right! Thanks for pointing that out, totally missed that
