### ISSUE TITLE
`convert-pr-to-draft-improvements` missing or misplaced with auto-merge and merge-queue

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6850]
### Description

Normal repos:

<img width="676" alt="Screenshot 4" src="https://github.com/refined-github/refined-github/assets/1402241/bdc3e65b-c073-4373-809e-8207816a5ed4">

Auto-merge repos:  (any open PR on https://github.com/refined-github/refined-github/pulls)

<img width="532" alt="Screenshot 2" src="https://github.com/refined-github/refined-github/assets/1402241/5ed72399-cbb5-40af-9ede-54134d702b67">

Merge-queue repos: https://github.com/refined-github/sandbox/pull/60

<img width="662" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/76863f9f-8c85-4464-8ab3-f94205b95da7">

### How to replicate the issue + URL

See above

### Extension version

23.8.3

### Browser(s) used

Safari

**Comment by cooljeanius** [comment]
yeah the merge-queue feature is one that I'm interested in using more, but it's kinda hard to when this extension doesn't really seem to know about it...

**Comment by fregante** [comment]
Closing in favor of this other issue since the feature needs to be rewritten for the new view

- https://github.com/refined-github/refined-github/issues/8123
