### ISSUE TITLE
Move merge icon in PR in `mark-merge-commits-in-list`?

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6852]
### Description

Instead of adding the icon next to the title, should we just replace the "commit" icon in the line?

<img width="140" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/133c9f7c-ba81-438b-a638-7482ef1ca2fe">

### Example URLs

https://github.com/refined-github/refined-github/pull/6830#commits-pushed-fffcbdb

**Comment by yakov116** [comment]
Like the idea the question is will it play nicely with the line going down

**Comment by fregante** [comment]
<table>
<tr>
 <th>Current
 <th>Replace icon
 <th><code>translate: 0.41em
 <th><a href="https://primer.style/design/foundations/icons/feed-merged-16">feed-merged</a> icon
  <th>None
<tr>
 <td><img width="101" alt="Screenshot 5" src="https://github.com/refined-github/refined-github/assets/1402241/441a0c6f-863f-42a4-818e-8dda1c4d7203">
 <td><img width="101" alt="Screenshot 4" src="https://github.com/refined-github/refined-github/assets/1402241/ce8be832-c9b7-4ec5-ac27-98a3e17fb165">
 <td><img width="101" alt="Screenshot 3" src="https://github.com/refined-github/refined-github/assets/1402241/77b114ba-b82d-4ee4-b473-75a3b0ce9e6c">
  <td><img width="101" alt="Screenshot 6" src="https://github.com/refined-github/refined-github/assets/1402241/5974a434-6063-4be0-8be5-42c5131e7937">
  <td><img width="101" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/97691073-1fb9-4b57-be59-906e8c4a96e7">
</table>

**Comment by yakov116** [comment]
Feed-merged or none
