### ISSUE TITLE
Fix junk layout on mobile review/edit forms

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6854]
### Description

Speaks for itself:

![after](https://github.com/refined-github/refined-github/assets/1402241/c837cd0d-3603-423f-9fd2-99c87b5f900a)

This happens on reviews shown in the "Conversation" tab, on the Files tab they a bit look better (spacing is still awful):
<img width="437" alt="Screenshot 4" src="https://github.com/refined-github/refined-github/assets/1402241/c596bc1c-7c84-49e5-b40a-dc9bb80720b5">

On the "New issue" forms it looks good:

<img width="394" alt="Screenshot 5" src="https://github.com/refined-github/refined-github/assets/1402241/e3dec71e-f537-4a60-84a4-cdfc77ad1996">

### Possible fixes

- never wrap tabs
- always place icons under the tabs
- drop spacing

The white background is probably because the buttons are expected to appear under the tabs. See the last screenshot above

### Implementation 

CSS-only feature, as little CSS as possible, e.g. 
- use `display: flex` to improve or avoid wrapping
- add `margin:0` to all
- maybe use `display: contents` to allow per-icon wrap, instead of grouping them

_Also reported by @kidonng, but I don't remember where_

### Example URLs

https://github.com/refined-github/sandbox/pull/10#pullrequestreview-832816238

**Comment by fregante** [comment]
This also happens when editing issues, right here

<img width="493" alt="Screenshot 6" src="https://github.com/refined-github/refined-github/assets/1402241/65d2d314-6634-44db-ba42-1453e028bb59">

**Comment by fregante** [comment]
Sample CSS:

```css
markdown-toolbar {
	margin-inline: -8px;
	padding-block: 8px;
}
.comment-form-head {
	flex-direction: column;
}
```

### Before

<img width="634" alt="Screenshot 1" src="https://github.com/refined-github/refined-github/assets/1402241/afa50297-8143-4f1d-80ca-8ecd85f81161">


### After

<img width="634" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/69c8b137-c810-4a00-949e-5e406f9fd109">

The problem is that it also breaks the forms that already work well, like the "New comment" form below:

<img width="284" alt="Screenshot 2" src="https://github.com/refined-github/refined-github/assets/1402241/9a7ec8ce-4877-4ee5-91aa-adecbe6510f7">

**Comment by Vichit1** [comment]
#6842

**Comment by fregante** [comment]
Was fixed by GitHub as part of https://github.com/refined-github/refined-github/issues/7011

<img width="562" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/65ab25d5-c155-4da9-a678-6bfb22af21f0">
