### ISSUE TITLE
Floating reply box?

### ISSUE THREAD

**Issue by jsumners** [refined-github/refined-github#6861]
### Description

I'm not sure this is even possible, but figured I'd ask the experts:

There are times when I need to reply to threads that have already received a lot of responses and I need to quote lines from those responses for context. Or maybe a response is particularly long and still results in pushing the reply box far off the bottom of the viewport. Would it be possible to "float" the reply box to the side such that it stays fixed in view while replying? It'd be amazing if it could be "popped out", e.g. like composing an email in Gmail, but I highly doubt that is feasible (at least not feasible while retaining the "quote in reply" feature).

### Example URLs

https://github.com/nodejs/TSC/issues/1430

**Comment by fregante** [comment]
I think this would conflict with `fit-textareas` because the field might extend beyond the viewport height. Not to mention the high chance of breakage.

I think a similarly-convenient feature would be to have a fixed "scroll to field" button that shows up when the field is not empty. This would complement `unfinished-comments`

**Comment by jsumners** [comment]
> I think a similarly-convenient feature would be to have a fixed "scroll to field" button that shows up when the field is not empty.

I don't understand what this is describing. Would be affixing the reply box to the bottom of the viewport such that prior comments scroll under it?

**Comment by fregante** [comment]
Are you familiar with the "Scroll to top" floating buttons? The same, but it scrolls to the text field instead.

**Comment by jsumners** [comment]
🤔 that might be an improvement. I'm really not sure. Having the text field always in the viewport would be optimal in my opinion.

**Comment by kidonng** [comment]
This works well enough for me:

```css
.CommentBox {
    position: fixed;
    right: 16px;
    bottom: 16px;
    z-index: 10;
    width: 320px;
    max-height: calc(100vh - 92px);
    overflow-y: scroll;
}
```

It makes the comment box fixed to the right side.

To have it as a toggle so you can "pop it out" on demand, use a user style manager like [Stylus](https://add0n.com/stylus.html).

**Comment by jsumners** [comment]
That's definitely doing the trick. Is there some CSS magic to make it arbitrarily resizable?

**Comment by fregante** [comment]
I'd love this, as a separate userscript.
