### ISSUE TITLE
`quick-label-removal`: Removing, then adding a label results in the removed label being added back

### ISSUE THREAD

**Issue by AlCalzone** [refined-github/refined-github#6862]
### Description

After getting issues transferred to my repo, I often have the need to replace one label with another. When I press the X button on the labels, then choose another one to add, this results in the removed label being added back. Not sure if this is related to the removed label being from a different repo.

Example:
![grafik](https://github.com/refined-github/refined-github/assets/17641229/b0dbea9d-733e-4da7-87b2-ba814f3e12e6)

### How to replicate the issue + URL

1. Open an issue with an existing label (possibly transferred from a different repo)
2. Remove the label with one click
3. Quickly add another label

https://github.com/zwave-js/node-zwave-js/issues/6195#event-10159785048

### Extension version

23.8.24

### Browser(s) used

Firefox 116.0.2 (64-Bit)

**Comment by fregante** [comment]
Thanks for the report. This bag was introduced by

- https://github.com/refined-github/refined-github/pull/4939
