### ISSUE TITLE
Create cherry pick branches for finished PR's

### ISSUE THREAD

**Issue by bramhoven** [refined-github/refined-github#6863]
### Description

Azure Dev Ops has a feature that when a PR is completed you can easily create a branch containing the cherry picked command.
For example you have the following branches:
          ____  hotfix/fix-bug
     __/____   release/v1
__ /_______   main

You want to fix the bug in the release branch and then cherry pick the commit to the main branch. Sadly the main branch is protected and needs a PR for code to be pushed. You would need to manually create a new branch, cherry pick the commit, push, create pr and get it approved and merged. Quite a lot of step. A few of those could be easily automated as they did in Azure Dev Ops.

Hopefully this makes sense and seems like a useful feature!

### Example URLs

Take for example https://github.com/refined-github/refined-github/pull/6857 at the end where the merge commit is located a button should be located. I don't know if that is the best place for it, but it seems logical to place it there.

**Comment by fregante** [comment]
Judging by this solution, it's too complex for Refined GitHub:

https://stackoverflow.com/q/53859199/288906

**Comment by 134130** [comment]
This feature might be better to create auto-cherrypick-bot or action workflow.
As @fregante said, I think it is too complex and it is devops's range. 
In my opinion, refined-github should be tunning GitHub, not being like Swiss army knife.
