### ISSUE TITLE
`vertical-front-matter`: only works on first load after cache clear

### ISSUE THREAD

**Issue by simon-abbott** [refined-github/refined-github#6865]
### Description

`vertical-front-matter` only works on the first load after the extension cache has been cleared. On all further loads it simply does nothing with no console errors.

https://github.com/refined-github/refined-github/assets/43803932/b3a11eeb-a8d9-44c7-810a-ae6f7147d254

### How to replicate the issue + URL

https://github.com/github/docs/blob/main/content/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github.md

### Extension version

23.8.24

### Browser(s) used

Firefox

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/6554

**Comment by fregante** [comment]
On second look, I don't know what's causing it
