### ISSUE TITLE
Plugin non-functional (Firefox Dev editon 118.0b3)

### ISSUE THREAD

**Issue by hgdagon** [refined-github/refined-github#6866]
### Description

I have recently noticed (though I can't remember the specific version when this started) that my github pages are back to their vanilla view, so today I decided to go through the setting one by one again. Since there's no save button button, I switched to the Details tab and back to Options tab. All checkboxes were missing again, and no changes on github pages (even after refresh). That's when I noticed a couple of more issues:
Import and Export buttons do nothing
The `Start process to identify feature...` and the `Clear cache` buttons as well as pressing enter in the `Find features` search box open the Options tab in a new browser tab. Repeating these actions on said tab opens another one.

### How to replicate the issue + URL

Go to Options and try to change any settings.

### Extension version

23.8.24

### Browser(s) used

Firefox Dev editon 118.0b3

**Comment by fregante** [comment]
If not even the options page works, I don’t think it's Refined GitHub's fault. Did you disable JavaScript? Anything in the console on GitHub.com?

Either way, it should be reported to Firefox instead.

**Comment by hgdagon** [comment]
The console shows  2 error (on this very page):

Error: An unexpected error occurred [refined-github.js:2180:52](moz-extension://cf50e561-dc70-47dc-802b-d3a06140c350/assets/refined-github.js)

```javascript
if (chrome.runtime.lastError) reject(new Error(chrome.runtime.lastError.message)); else resolve(result);
```

Error: Promised response from onMessage listener went out of scope [ExtensionMessagingService.js:89:34](moz-extension://2d3935a2-3913-49d0-ac0f-c3d09288e9c3/scripts/services/ExtensionMessagingService.js)

```javascript
chrome.runtime.onMessage.addListener
```

**Comment by fregante** [comment]
Related bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1643186

**Comment by fregante** [comment]
Happy to report that _it works for me._ 😅 I wonder if reinstalling the extension fixes it for you

<img width="1190" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/852f140a-569e-4d43-969e-ba2663c13e38">

**Comment by hgdagon** [comment]
> I wonder if reinstalling the extension fixes it for you

It did... I don't understand new Firefox
