### ISSUE TITLE
Add option to list all open pull requests in orgs I have commit access to

### ISSUE THREAD

**Issue by LilithHafner** [refined-github/refined-github#6877]
### Description

I sometimes look back over my open PRs to see if there is anything I should do about them. The ones in repos I have commit access to tend to be much more actionable so I would like an option to filter by "repos I have commit access to".

### Example URLs

https://github.com/pulls

**Comment by fregante** [comment]
This would be great, I would love it, but there's no way to search two users at once on GitHub:

https://github.com/issues?q=user%3Afregante+OR+org%3Arefined-github+

This means that the only way to display this information would be to create a page and all of its DOM, including pagination and all. This is out of Refined GitHub’s scope:

https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#4-it-doesnt-require-a-lot-of-viewui-code-and-effort-to-maintain

**Comment by LilithHafner** [comment]
https://github.com/issues?q=user%3Afregante+user%3Arefined-github+
