### ISSUE TITLE
Fewer clicks to close issue as "not planned"

### ISSUE THREAD

**Issue by simon-abbott** [refined-github/refined-github#6883]
### Description

Ever since GitHub added the ability to close issues as [not planned](https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/#%F0%9F%95%B5%F0%9F%8F%BD%E2%99%80%EF%B8%8F-issue-closed-reasons) I've been annoyed at needing to click an extra 2 times to actually use it. It would be awesome if there was a feature like `one-click-review-submission` and `unwrap-unnecessary-dropdowns` that applied the same ergonomic fix to the close reasons. Ideally it would also apply to the "re-open" button as well, to allow one-click switching of the close reason after the fact.

### Example URLs

Literally any open issue you have permission to close (even this one!)

**Comment by fregante** [comment]
I agree, I use it all the time, however I'm not sure we can dedicate that much space to the close button. 🥲

**Comment by janpio** [comment]
Maybe the button could be smaller and just has the `not planned` icon instead of the full test?

**Comment by fregante** [comment]
We have a few similar features indeed:

- `one-click-pr-or-gist`
- `one-click-review-submission`
- `unwrap-unnecessary-dropdowns`

This could be called:

- `one-click-issue-closure`
