### ISSUE TITLE
Any chance you can fix the new github feed?

### ISSUE THREAD

**Issue by port19x** [refined-github/refined-github#6884]
So github decided to remove the following feed as you probably noticed.
Is there anything that can be done about it within the scope of this project?

**Comment by fregante** [comment]
A good start would be by stating what's wrong with it. It's best to open dedicated issues around what changes you'd like. 

The good part is that there's a filter now"

<img width="390" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/6290e8f3-69ba-4a8f-af7f-4b17d53288cf">
