### ISSUE TITLE
"Edit on default branch" button on files on commits

### ISSUE THREAD

**Issue by janpio** [refined-github/refined-github#6885]
### Description

When one goes to a file on a commit (for example via GH search), you can not directly edit files. 

For example: https://github.com/AigarsPeda/wupzy/blob/d2ab7f1ffbc1c4c53e3cda02c89f65b49842f48c/prisma/schema.prisma
<img width="387" alt="image" src="https://github.com/refined-github/refined-github/assets/183673/4540a951-310a-4143-8f63-9709899605d8">

Instead one has to select a branch on the left dropdown:
<img width="312" alt="image" src="https://github.com/refined-github/refined-github/assets/183673/c7a712fa-7daf-498c-8d1f-40ff5ba98792">

Then you are directed to the file on the selected branch, and can edit the file:
https://github.com/AigarsPeda/wupzy/blob/main/prisma/schema.prisma
<img width="288" alt="image" src="https://github.com/refined-github/refined-github/assets/183673/bac709a2-e0fb-4331-92be-d26471262165">

This is a super common workflow for me (find files via search, edit them to propose a PR), so having a button "Edit on default branch" next to the existing one would be amazing and safe me _so many clicks_.

Would something like this be in scope of Refined GitHub?

### Example URLs

https://github.com/AigarsPeda/wupzy/blob/d2ab7f1ffbc1c4c53e3cda02c89f65b49842f48c/prisma/schema.prisma
https://github.com/AigarsPeda/wupzy/blob/main/prisma/schema.prisma

**Comment by fregante** [comment]
We actually have/had a feature to do this exactly, but it was removed. See the reasoning in the `edit-readme` removal (a feature that did this, but exclusively for the readme):

- https://github.com/refined-github/refined-github/issues/6859




> Instead one has to select a branch on the left dropdown:

No, you can click the `default-branch-button`. This operation only adds one click and makes it clear where the file is being edited in

**Comment by janpio** [comment]
:TIL: [default-branch-button](https://github.com/refined-github/refined-github/blob/main/source/features/default-branch-button.tsx)

> See the reasoning in the [edit-readme](https://github.com/refined-github/refined-github/blob/main/source/features/edit-readme.tsx) removal

Ok yeah, that was slightly different - for branches this should indeed not apply, but commits are different in that you can not edit there.

But I'm ok, adding new UI buttons is always a problem as they need to be explained - and that would be hard here.

**Comment by fregante** [comment]
> for branches this should indeed not apply,

No, branches are fine, `main` is just another branch. 

Editing on commits and tags is not possible, so one has to guess where the edit will happen. And then what happens when you try to edit a file that doesn't exist on the default branch (because the commit isn't on it yet or because the file has been deleted)?

Editing on permalinks was useful but the outcome isn't particularly clear. I figured it'd be easier to just visit the default branch instead
