### ISSUE TITLE
`sync-pr-commit-title` affects "merge commit"

### ISSUE THREAD

**Issue by woochanleee** [refined-github/refined-github#6889]
> Related https://github.com/refined-github/refined-github/issues/6888.

### Repdoruce issue video

https://github.com/refined-github/refined-github/assets/48552260/322feb4e-5707-493b-a80d-50737750b757

### When

- if GitHub repository settings > Pull Requests > Allow squash merging  > Default Message 
- if pull request contains a single commit
- if change pull request title differently than a single commit message.
- Select option squash merge to merge commit 

### Why

> Default message: commit title and commit message (if the pull request contains a single commit), or the pull request title and number and list of commits (if the pull request contains multiple commits),  [GitHub changelog](https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/#options)

As you can see in the video below, input not changed to merge commit message because it's value different from GitHub's default message.

https://github.com/refined-github/refined-github/assets/48552260/827f51a1-707c-4adf-a8f7-f9fb738a2c1a

### Workaround

Is the best solution to change the GitHub setting to one of `Default to pull request title...` instead of `Default message`?

<img width="528" alt="image" src="https://github.com/refined-github/refined-github/assets/48552260/496cfbf9-8b73-4728-a296-06f767368a33">

### How to replicate the issue + URL

https://github.com/woochanleee/refined-github-sync-pr-title-issue-reproduction/pull/1

### Extension version

23.9.7

### Browser(s) used

Chrome

**Comment by fregante** [comment]
Ok I gave this a further look: it works as expected.

Here are the two behaviors you're seeing:

- Refined GitHub will set the commit title to the PR title in `sync-pr-commit-title`
- GitHub preserves any changes to the PR title when switching between merge styles

You can either:

- disable `sync-pr-commit-title`, or
- _not_ open the "squash and merge" option before switching to "create merge commit"

Opening the default "Create merge commit" first is not affected by Refined GitHub:

<img width="601" alt="Screenshot 15" src="https://github.com/refined-github/refined-github/assets/1402241/84c65ce7-4ddb-427a-85d8-da02347ce280">
