### ISSUE TITLE
Please allow restoring the old news feed

### ISSUE THREAD

**Issue by dhirschfeld** [refined-github/refined-github#6890]
### Description

The changes to the news feed are awful:
https://github.com/orgs/community/discussions/65343

I'd like to get the old feed back as it did what I needed/wanted.

The content from the old feed is available at https://github.com/dashboard-feed but that's a bit awkward, not being integrated into your home page. 

### Example URLs

https://github.com/

**Comment by fregante** [comment]
Refined GitHub does not "bring back" features. 

If there's anything in particular that you'd like to see or fix on the dashboard you can open a specific issue.

**Comment by dhirschfeld** [comment]
I would like the data from the old feed, as displayed at [dashboard-feed](https://github.com/dashboard-feed), to replace the dashboard content on my home page.

**Comment by dhirschfeld** [comment]
There is already a script which does this for you:
https://github.com/Gerrit0/old-github-feed/blob/main/old-feed.user.js

I just thought, as a change which can make GitHub a more productive tool, that it would be a good fit for `refined-github`.

**Comment by fregante** [comment]
> There is already a script which does this for you:

Fantastic! See the first point:

https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/6884

**Comment by port19x** [comment]
> > There is already a script which does this for you:
> 
> Fantastic! See the first point:
> 
> [refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22](https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22)

That's a fair point for closing. You should probably point that out to the inevitable avalanche of issues that will be opened on this topic.

**Comment by fregante** [comment]
It's already pre-pointed out, and yet… 😃 

<img width="673" alt="Screenshot 1" src="https://github.com/refined-github/refined-github/assets/1402241/d9b9de8d-bd7e-4511-a6ec-98b4bf04c1e1">
