### ISSUE TITLE
`unfinished-comments` triggers on compare page

### ISSUE THREAD

**Issue by jerone** [refined-github/refined-github#6902]
### Description

![image](https://github.com/refined-github/refined-github/assets/55841/64ccf8d9-0346-48f0-a7db-0b71706c3893)

### How to replicate the issue + URL

https://github.com/yargs/cliui/compare/master...isaacs:cliui:main

Weirdly I was not able to reproduce it on this repo. E.g. https://github.com/refined-github/refined-github/compare/main%40%7B10day%7D...main

### Extension version

23.9.7

### Browser(s) used

Firefox

**Comment by fregante** [comment]
The compare page potentially has a field to create a PR, could that be it?

Either way it shouldn't be triggered when the field is empty/unaltered. There could be an issue if GitHub is setting the content dynamically via .value instead of .textContent. This is what we use to determine whether a field has been used.

**Comment by jerone** [comment]
> The compare page potentially has a field to create a PR, could that be it?

It does. But then I would expect the same issue to happen here (but it doesn't): https://github.com/refined-github/refined-github/compare/main...fregante-patch-1

**Comment by fregante** [comment]
This is very likely due to a 2-line commit description:

<img width="817" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/7c26c767-a662-4131-a019-830ced557297">

**Comment by fregante** [comment]
And indeed that's the issue:

<img width="477" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/71268a67-880d-466b-a69c-004373f32e75">

**Comment by fregante** [comment]
In some cases, presumably simple or recent comparisons, this issue doesn't happen because GitHub preloads the commit message in the HTML:

<img width="748" alt="Screenshot 4" src="https://github.com/refined-github/refined-github/assets/1402241/0c445b0b-ab4d-45ac-a866-5326ad78c036">

**Comment by jerone** [comment]
And detecting if the "create pull request" section is even expanded on the compare page?

**Comment by fregante** [comment]
A possible solution:

- only consider fields that actually received `input` or `session:resume` events

```js
const touched = new WeakSet()
delegate(document, 'textarea', 'input', field => {
  touched.add(field)
});
document.addEventListener('session:resume', () => {
// find which field was restored
})
```
