### ISSUE TITLE
Impossible to clear tags in organization repositories list

### ISSUE THREAD

**Issue by Nek-** [refined-github/refined-github#6906]
### Description

This bug occurs only with the extension enabled and after a clear cache.

If you go to https://github.com/orgs/{OrganizationName}/repositories and browse pagination, you cannot see the list without tags filters. (Clearing filters redirects to the page 1!)

### How to replicate the issue + URL

1. Go to https://github.com/orgs/Sylius/repositories (by clicking this link)
2. Clear filters
3. Go page 2
4. Clear filters
5. You're page 1

### Extension version

23.9.7

### Browser(s) used

Arc

**Comment by fregante** [comment]
I reproduced the issue without Refined GitHub, this is a GitHub issue.
