### ISSUE TITLE
How to modify content on PJAX pages like the repository settings

### ISSUE THREAD

**Issue by markphip** [refined-github/refined-github#6911]
I am trying to add a feature (in a fork) that would add some content in repository Settings pages.

These are all PJAX pages. I can do what I want if I refresh the page but not when I navigate between them. This is an example that shows some of the different things I have tried. Just to have something to do to show the problem, this removes the Add Users and Teams buttons from the Teams page.

All of these techniques work when the page is refreshed just not when navigating between them.

Wondering if there is a technique that will work for modifying these kinds of pages and recognizing when they have done the turbo rendering.

```typescript
import * as pageDetect from 'github-url-detection';
import features from '../feature-manager.js';
import select from 'select-dom';

// async function init(): Promise<false | void> {
//     if (window.location.pathname.endsWith("/branches")) {
// 	    console.log('✨ we are in the branches page!');
//     }
//     if (window.location.pathname.endsWith("/access")) {
//         console.log('✨ we are on the ACL page!');
//         const aclButtons = await elementReady('#repo-content-pjax-container > div > div > div.Layout-main > div > div > div.d-flex.flex-wrap.flex-justify-end.mt-6.mb-3 > div.js-add-access-form', {waitForChildren: false});
//         aclButtons!.remove();
//     }
// }

function init(): void {
    if (window.location.pathname.endsWith("/branches")) {
	    console.log('✨ we are in the branches page!');
    }
    if (window.location.pathname.endsWith("/access")) {
        console.log('✨ we are on the ACL page!');
        requestAnimationFrame(() => {
            const el = select(':is(#repo-content-pjax-container, turbo-frame) .js-add-access-form')
            console.log('✨ ACL element: ' + el);
            el!.remove();
        });
    }

}

void features.add(import.meta.url, {
	include: [
		pageDetect.isRepoSettings
	],
    deduplicate: 'has-rgh-inner',
	init,
});
```

**Comment by fregante** [comment]
`init` is already called on pjax navigations so if it's not working there maybe they're using React views. 

You can try using the selector observer inside `init`, look for `observe(` in other features

**Comment by markphip** [comment]
Just in case anyone else wants to customize the repository settings pages. Using observe did turn out to be the answer.

In my init function I use this and it works great: `observe('.js-add-access-form'`

thanks
