### ISSUE TITLE
New `unreleased-commits` causes Switch branches to be hidden in `<details>`

### ISSUE THREAD

**Issue by smowtenshi** [refined-github/refined-github#6922]
### Description

`unreleased-commits` enabled  ↓
![uosc with unreleased-commits enabled](https://github.com/refined-github/refined-github/assets/7839556/e768ea3c-ee48-456b-823b-ebdc735840a2)

`unreleased-commits` disabled ↓
![uosc with unreleased-commits disabled](https://github.com/refined-github/refined-github/assets/7839556/ae474161-eef8-4305-924d-5a923dd86699)

I haven't noticed any errors related to this feature in console.

### How to replicate the issue + URL

1. Enable `unreleased-commits` feature.
2. Navigate to any repository with unreleased commits.

Example URLs I noticed the issue at: 
- https://github.com/tomasklaen/uosc
- https://github.com/black7375/Firefox-UI-Fix

### Extension version

23.9.17

### Browser(s) used

Firefox 102.15.1esr

**Comment by jdreesen** [comment]
Same on Firefox 117.0.1 (64-Bit).

It also looks a bit broken when I click on it.

Closed: 
![image](https://github.com/refined-github/refined-github/assets/424602/ba892f40-d403-4870-b087-6eaedb39a48c)

Opened:
![image](https://github.com/refined-github/refined-github/assets/424602/09be008b-1a59-42e2-90f8-26fae88401b4)

**Comment by fregante** [comment]
Thank you for the report. I'll disable it via hotfix

**Comment by fregante** [comment]
https://github.com/refined-github/refined-github/blob/09a064501336b5b02355fe4bcd905cab771591d9/source/features/unreleased-commits.tsx#L99

We can just use `.ml-1` in this case

**Comment by 134130** [comment]
Sorry for making this issue.
The Old Repository Overview has the issue.
Reason is last view satisfies not only `legacy selector` but also `new selector`.

**Comment by fregante** [comment]
It happens
