### ISSUE TITLE
`repo-header-info` shows info for ci actions

### ISSUE THREAD

**Issue by UnderKoen** [refined-github/refined-github#6923]
### Description

Repo-header-info show the stars and lock on to many elements. On the CI actions popover I hav enoticed this.

![image](https://github.com/refined-github/refined-github/assets/15718297/3d3234ac-4874-4cd1-8a72-5266fd5724b3)

### How to replicate the issue + URL

1. Goto https://github.com/refined-github/refined-github
2. Click on the CI checkmark

### Extension version

23.9.17

### Browser(s) used

Chrome

**Comment by 134130** [comment]
🥲🥲🥲

**Comment by fregante** [comment]
I love it 😂
