### ISSUE TITLE
Link to stargazers in `repo-header-info`

### ISSUE THREAD

**Issue by FloEdelmann** [refined-github/refined-github#6926]
### Description

The star icon + text in `repo-header` info could be a link to the stargazers of that repo. That would make it a tad more useful.

### Example URLs

https://github.com/refined-github/refined-github
→ would link to https://github.com/refined-github/refined-github/stargazers

**Comment by fregante** [comment]
I thought about it but… what's the use? The list isn't searchable, so I don’t think anyone is looking at more than one page of random users. Maybe it's useful if there are a handful of users… but even then… 🤷‍♂️ 😅
