### ISSUE TITLE
Allow multiple PR reviews to be dismissed simultaneously with the same message

### ISSUE THREAD

**Issue by Oliver-Saer** [refined-github/refined-github#6929]
### Description

When changes are requested on a PR, you may wish to dismiss them after fulfilling each change request for clarity when viewing from the PR summary page.

However, if multiple users have requested changes, you must dismiss them individually, typing in the message each time.

It would be great if Refined GitHub could offer a facility to dismiss all/multiple reviews simultaneously with the same message.

### Example URLs

https://github.com/[organisation]/[repo]/pull/[pr_id]

**Comment by fregante** [comment]
> Include a REAL URL where the feature should appear. e.g. Do you want a feature to appear on the main page of a repo? Paste a link to a repo

**Comment by fregante** [comment]
> typing in the message each time

This doesn't seem necessary. GitHub already provides the "Resolve" button to target each review individually. If the closing message is the same for everyone, then it should just be added to the main conversation. 

Doing both probably already achieves what you're trying to do.

As for this specific feature, we had other requests for "batch action on comments" and figured it was too complex to integrate in Refined GitHub.

- #2988 

Also:

> Include a REAL URL where the feature should appear. e.g. Do you want a feature to appear on the main page of a repo? Paste a link to a repo
