### ISSUE TITLE
`TypeError: text is undefined` in `linkify-issues`

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6930]
### Description

There seems to be an issue in `linkify-issues`’s `getAsDocumentFragment` function, maybe just in Firefox

```
TypeError: text is undefinedrefined-github.js:26576:14
    getAsDocumentFragment moz-extension://abee8e9b-c4bd-4c86-88dd-a3e8be8650aa/assets/refined-github.js:26576
    linkifyIssues moz-extension://abee8e9b-c4bd-4c86-88dd-a3e8be8650aa/assets/refined-github.js:26601
    linkifyIssues moz-extension://abee8e9b-c4bd-4c86-88dd-a3e8be8650aa/assets/refined-github.js:17091
    linkifyContent moz-extension://abee8e9b-c4bd-4c86-88dd-a3e8be8650aa/assets/refined-github.js:8735
    getListener moz-extension://abee8e9b-c4bd-4c86-88dd-a3e8be8650aa/assets/refined-github.js:19532
```

### How to replicate the issue + URL

1. Open https://github.com/refined-github/refined-github/pull/6870/files
2. Open the console

### Extension version

23.8.3

### Browser(s) used

Firefox

**Comment by Katsute** [comment]
Chrome:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at linkify_issues_getAsDocumentFragment (refined-github.js:6648:192)
    at linkified.user (refined-github.js:6687:44)
    at dom_formatters_linkifyIssues (refined-github.js:6689:8)
    at linkifyContent (refined-github.js:6753:65)
    at refined-github.js:4608:9
```

in rgh ↓

```js
6648 |      for (const [index, text] of Object.entries(string.split(groupedIssueRegex))) if (index % 2) fragment.append(linkify_issues_domify(linkify_issues_linkify(text, options))); else if (text.length > 0) fragment.append(text);
```
in linkify-urls ↓

https://github.com/sindresorhus/linkify-urls/blob/4601c8b46dd401179be526e74523637da3d5dc2e/index.js#L39

```js
	for (const [index, text] of parts.entries()) {
		// URLs are always in odd positions
		if (index % 2 && !isTruncated(text, parts[index + 1])) {
			fragment.append(domify(linkify(text, options)));
// here ↓
		} else if (text.length > 0) {
			fragment.append(text);
		}
	}
```

text is somehow undefined

**Comment by fregante** [comment]
@Katsute the new logic is wrong actually, I hadn't noticed. 

The `else` should not be reached if `i % 2`, but due to the added isTruncated condition, it's reached. 

Changes required:

``` 
if i % 2
  if not truncated
    linkify
else if length
  add text

**Comment by Katsute** [comment]
I'll open a PR in linkify-urls to resolve this

**Comment by fregante** [comment]
Yea I'm not really sure of how the text could be undefined. It's worth a manual run through the loop to see how that happens, or via `console.log(...parts.entries())`

**Comment by fregante** [comment]
Yeah this is not due to your recent changes and I don't understand how this bug hasn't shown up earlier. Also note that the bug I saw was in the "linkify issues" package, which shares a similar logic. 

Can you add a failing test to the linkify-urls package first?

**Comment by Katsute** [comment]
Yea, seems to be an issue with the issues package (oops). Using the issue link causes no issue in the linkify-urls package

**Comment by Katsute** [comment]
Tests already fail on main...

https://github.com/Katsute/linkify-issues/actions/runs/6239327745/job/16937016509

Repo has a CI setup but it has never run on any of the commits

**Comment by Katsute** [comment]
@fregante bug was accidentally introduced in https://github.com/refined-github/refined-github/commit/8020f7af1bed72c9559a8ed33511bcbf4c74a3e6#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519R6152 when you updated a transient dependency `issue-regex` from `3.1.0` to `4.1.0` (see https://github.com/sindresorhus/linkify-issues/issues/12).

Using `issue-regex@4.0.0` will fix this issue.
