### ISSUE TITLE
Missing star/fork count bubbles

### ISSUE THREAD

**Issue by zhudotexe** [refined-github/refined-github#6933]
### Description

After updating to the most recent version of refined-github, I noticed that the bubbles counting the number of stars/forks on the star/fork button were missing:

With extension enabled:
![Screenshot 2023-09-19 at 11 09 33](https://github.com/refined-github/refined-github/assets/8866981/2f13728b-eceb-4fd9-8515-6d0c4bdcd3c5)

With extension disabled:
![Screenshot 2023-09-19 at 11 09 48](https://github.com/refined-github/refined-github/assets/8866981/e15cfc1e-e003-46bb-bffd-3fd28cb6ec98)

Disabling `repo-header-info` does not bring the bubbles back, nor does any step in the Identify Feature process.

### How to replicate the issue + URL

The count bubbles are missing on any repository page. To replicate the issue, visit any repository page and observe that the count bubbles are missing. Open the same page in incognito and observe that the count bubbles return.
Example repo: https://github.com/zhudotexe/kani

### Extension version

23.9.17

### Browser(s) used

Chrome 116.0.5845.187 on macOS

**Comment by 134130** [comment]
- `clean-repo-header` is css only feature and it cannot be disabled.
- Related #6908
- This feature creates many conversations and I think it needs to support toggleable.
