### ISSUE TITLE
Disabling `repo-header-info` does not restore star/fork count to original location

### ISSUE THREAD

**Issue by zhudotexe** [refined-github/refined-github#6934]
Why was #6933 closed and locked? The comment left by maintainers doesn't address the issue and I can't reply in the same issue so I have to make a new one.

I would expect the star/fork count to return to its normal place on the star/fork button if the `repo-header-info` feature was disabled in the plugin options, but it does not.

**Comment by tddschn** [comment]
Same problem here. Star count is no where to be seen.

**Comment by fregante** [comment]
Nobody said that disabling the feature would bring back the numbers. I already said that the numbers already exist on the page so we removed the redundant ones.

Stop spamming
