### ISSUE TITLE
Untruncate check descriptions in popup

### ISSUE THREAD

**Issue by nfi-hashicorp** [refined-github/refined-github#6945]
### Description

When you click the little checks button next to a commit, it shows this popup. As you can see, long items are truncated. For matrix jobs, this happens often, which means you can't distinguish them if the differentiating factor is at the end:

<img width="661" alt="image" src="https://github.com/refined-github/refined-github/assets/115657443/869507b0-b4f2-45fa-83a2-4b29cc74bb12">

I don't have great solution, but here's what it looks like if you hack the `css-truncate` class:

<img width="632" alt="image" src="https://github.com/refined-github/refined-github/assets/115657443/a5e95d29-25f8-4bd4-b9d2-331d7fcc4ee8">

Personally I feel like that `Detail` text is superfluous and the text for the check could be the link.

### Example URLs

https://github.com/hashicorp/consul for example, but anywhere those checks appear.

**Comment by fregante** [comment]
This is the kind of refinement I can get behind. However I guarantee that if we hide the Details button we'll immediately get a "bug report" that Refined GitHub hid that link.

**Comment by nfi-hashicorp** [comment]
Thanks. I may or may not get to it, we'll see!
