### ISSUE TITLE
GraphQL: Field 'viewerCanEditFiles' doesn't exist on type 'PullRequest'

### ISSUE THREAD

**Issue by nicolasff** [refined-github/refined-github#6946]
### Description

Hello,

Today I noticed this error being logged by Refined GitHub (version 23.9.21) while viewing the description tab of a pull request on a GHE instance (GitHub Enterprise Server 3.5):

```
VM900 refined-github.js:4433 Uncaught (in promise) Error: GraphQL:
Field 'viewerCanEditFiles' doesn't exist on type 'PullRequest'
Field 'compare' doesn't exist on type 'Ref'
    at v4uncached (VM900 refined-github.js:4433:60)
    at async getPrInfo (refined-github.js:8539:28)
    at async update_pr_from_base_branch_addButton (refined-github.js:8578:46)
```

In addition to `update_pr_from_base_branch_addButton`, I've also seen it from a different original call site, starting at `async addInfo (refined-github.js:12457:46)`, which calls `getPrInfo`.

In `v4uncached`, the exception is thrown if `errors` contains anything. I put a breakpoint on the `throw` to examine the `errors` variable, which contained:
```json
{
    "errors": [
        {
            "path": [
                "query",
                "repository",
                "pullRequest",
                "viewerCanEditFiles"
            ],
            "extensions": {
                "code": "undefinedField",
                "typeName": "PullRequest",
                "fieldName": "viewerCanEditFiles"
            },
            "locations": [
                {
                    "line": 7,
                    "column": 5
                }
            ],
            "message": "Field 'viewerCanEditFiles' doesn't exist on type 'PullRequest'"
        },
        {
            "path": [
                "query",
                "repository",
                "pullRequest",
                "headRef",
                "compare"
            ],
            "extensions": {
                "code": "undefinedField",
                "typeName": "Ref",
                "fieldName": "compare"
            },
            "locations": [
                {
                    "line": 9,
                    "column": 6
                }
            ],
            "message": "Field 'compare' doesn't exist on type 'Ref'"
        }
    ]
}
```

I also dumped `query`, which contained the following (anonymized):
```graphql
		repository(owner: $owner, name: $name) {
			pullRequest(number: 1234) {
				baseRefOid
				headRefOid
				mergeable
				viewerCanEditFiles
				headRef {
					compare(headRef: "REPO-NAME-WAS-HERE:main") {
						status
						aheadBy
					}
				}
			}
		}
```

## Cause

This is likely because `viewerCanEditFiles` is a (relatively) new field, mentioned as being added in a [GraphQL schema changelog](https://docs.github.com/en/graphql/overview/changelog#schema-changes-for-2022-06-23-1) dated June 23rd, 2022.

I dumped the schema for `PullRequest` on the GHE instance, and observed that `viewerCanEditFiles` was indeed not listed in this type's fields. I used this command, adapted from [GitHub's GraphQL docs](https://docs.github.com/en/enterprise-server@3.5/graphql/guides/introduction-to-graphql#discovering-the-graphql-api) for GHE 3.5:
```sh
gh api graphql -f query='query {
  __type(name: "PullRequest") {
    name
    kind
    description
    fields {
      name
    }
  }
}' | jq .
```

I also tried following the link to the GraphQL schema for GHE 3.5 (`schema.docs-enterprise.graphql`) in the [GitHub docs](https://docs.github.com/en/enterprise-server@3.5/graphql/overview/public-schema), but the link is broken and returns a 404. Fortunately [a copy](https://web.archive.org/web/20220819195009/https://docs.github.com/public/ghes-3.5/schema.docs-enterprise.graphql) is available on the Wayback Machine (link auto-downloads a file). I've extracted the definition for `PullRequest` in this gist, where you won't find any reference to `viewerCanEditFiles`: https://gist.github.com/nicolasff/58232f5c08c4529b2c019bdaae0be49e

I hope this helps! Thanks for making this great extension.

### How to replicate the issue + URL

I don't see this error on the public GitHub website, and obviously this GHE server is not public.

### Extension version

23.9.21

### Browser(s) used

Google Chrome Version 118.0.5993.21 (Official Build) beta (x86_64) on macOS Ventura 13.5.1 (22G90)

**Comment by fregante** [comment]
Hi, we generally don't support versions older than 6 months and 3.6.0 has been available for a year already (August 2022) so 3.5 is too old. 

This feature requires 3.7 (November 2022, 10 months ago), which appears to be the first version that exposes `viewerCanEditFiles`

https://docs.github.com/en/enterprise-server@3.7/graphql/reference/objects#pullrequest
