### ISSUE TITLE
How to show star count in star button?

### ISSUE THREAD

**Issue by GF-Huang** [refined-github/refined-github#6957]
### Expected
![image](https://github.com/refined-github/refined-github/assets/4510984/5230d427-0414-4678-ae1b-0e8df9c25e1a)

### Actual
![image](https://github.com/refined-github/refined-github/assets/4510984/76e07fad-6011-4afb-bb83-b3198addc06c)

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/6940
