### ISSUE TITLE
Link to Github Merge Queue

### ISSUE THREAD

**Issue by changusmc** [refined-github/refined-github#6958]
### Description

With Merge Queue in GA now, it would be great if there was a link to the Merge Queue. The href is usually $repo/queue

![image](https://github.com/refined-github/refined-github/assets/8715059/1941db31-7799-4481-b19e-e2e55213adc2)

### Example URLs

https://github.com/organization/repo/queue

**Comment by fregante** [comment]
A link to the queue appears on the PR list already, if there's any PR waiting to be merged. Maybe not as convenient, but Merge Queue isn't super commonly-used and it's empty most of the time even in repos that use it. I don’t think it makes sense for Refined GitHub to add it.
