### ISSUE TITLE
`toggle-files-button` missing on "New Repository Overview"

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6959]
### Description

<img width="742" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/173611f8-c591-4fad-bd15-bb02a04d7327">

### How to replicate the issue + URL

https://github.com/refined-github/refined-github

### Extension version

23.8.3

### Browser(s) used

Safari

**Comment by fregante** [comment]
Also it might be a good time to update the gif. I usually use licecap for this

**Comment by FloEdelmann** [comment]
FYI: This is now generally available: https://github.blog/changelog/2023-12-06-updates-to-repository-pages/

**Comment by Helmoes** [comment]
I'm also not seeing the button.

**Comment by fregante** [comment]
It's not just a missing button, the feature needs to be rewritten from scratch because they changed the way it looks on mobile:

<img width="426" alt="Screenshot 4" src="https://github.com/refined-github/refined-github/assets/1402241/3a5d1d40-47ea-4d0c-8eb5-e9217855f508">

They used to hide all files on mobile, so this feature just reused that logic. Since it's gone, probably none of the current code is usable (other than the chevron up/down CSS).

However the feature is relatively simple. PR welcome

**Comment by MAZ01001** [comment]
>
> They used to hide all files on mobile, so this feature just reused that logic. Since it's gone, probably none of the current code is usable (other than the chevron up/down CSS).
>

I don't know anything about how this extension is structured, but ...

I found that you could very simply get it to look like on mobile.

```javascript
(()=>{
    "use strict";
    document.querySelector("react-partial[partial-name=repos-overview] h2#folders-and-files+table>tbody>tr.show-for-mobile")?.style.setProperty("display","revert");
    document.querySelectorAll("react-partial[partial-name=repos-overview] h2#folders-and-files+table>tbody>tr.truncate-for-mobile").forEach(v=>v.style.display="none");
})();
```

Here again a little less compressed, with comments.

```javascript
(()=>{
    "use strict";
    //~ check if on repo overview
    const projectView = document.querySelector("react-partial[partial-name=repos-overview]");
    if(projectView == null) return;

    //~ get the body of the file list table
    const tableBody = projectView.querySelector("h2#folders-and-files+table>tbody");

    //~ display the "View all files" button
    tableBody.querySelector("tr.show-for-mobile")?.style.setProperty("display", "revert");

    //~ hide all marked rows
    tableBody.querySelectorAll("tr.truncate-for-mobile").forEach(row => row.style.display = "none");
})();
```

Which seems to collapse all but the first 10 rows and it's a one-time "View all files" expansion.

The [userscript](https://github.com/MAZ01001/CollapsibleGitHubProjectFiles "GitHub: MAZ01001/CollapsibleGitHubProjectFiles") I wrote permanently adds a toggle button (at the top) for all rows (which now also shows the number of rows).

**Comment by 134130** [comment]
@fregante How do you think about @MAZ01001 's solution that gives UX as same as mobile.

This will makes really simple job, and no makes conflict or side-effect with mobile extensions

**Comment by fregante** [comment]
I was looking into this at this exact time actually, specifically seeing if reverting https://github.com/refined-github/refined-github/pull/6706 was enough. 

Those two snippets don't work (anymore?). I'm not a fan of how the linked [userscript](https://github.com/MAZ01001/CollapsibleGitHubProjectFiles/blob/main/github_collapse.user.js) looks either

**Comment by 134130** [comment]
The @MAZ01001 's both scripts are working for me
![image](https://github.com/refined-github/refined-github/assets/50487467/2a770194-c261-4eb6-96e8-e3734f5b3ef7)

**Comment by fregante** [comment]
> are working for me

How? I don't see any change in the file list.

Anyway reverting #6706 mostly gets it to a working state. I'll open a PR

![Untitled](https://github.com/refined-github/refined-github/assets/1402241/42f8f933-1d9c-42f0-994f-37a27847b7d1)

**Comment by 134130** [comment]
Not Important anymore, but I just captured for your interesting.
![Untitled](https://github.com/refined-github/refined-github/assets/50487467/9c34c614-5822-42e9-b772-65d6941f2989)

**Comment by fregante** [comment]
Oh I didn't notice. I think that's not equivalent/enough for this toggle

**Comment by x9136** [comment]
I don't see the button.

Refined GitHub 24.6.21, Firefox 128.0 (64-bit).

**Comment by fregante** [comment]
You're not running the latest version
