### ISSUE TITLE
Allow resize in Actions run view

### ISSUE THREAD

**Issue by igorwojda** [refined-github/refined-github#6960]
### Description

There is a bunch of space on my screen so I would like to be able to see the full names of the jobs.
Can we add to resize this view or the ability to enter fixed width for the left sidebar and "diagram popup"

### Example URLs

<img width="1963" alt="image" src="https://github.com/refined-github/refined-github/assets/530122/c9ef0cfa-bfb4-474d-bb18-823714dec562">

**Comment by fregante** [comment]
Resizing no because it would introduce too many issues, but I’d totally allow wrapping like suggested in:

- https://github.com/refined-github/refined-github/issues/6945

PR welcome
