### ISSUE TITLE
cannot open extension options on v23.9.21

### ISSUE THREAD

**Issue by owocado** [refined-github/refined-github#6962]
Hello and greetings,

I have been using refined github extension for over 2 years now and it has been working very smoothly so far. However recently I had to factory reset my Android phone for personal reasons and had to setup everything again. After doing the setup, I installed kiwi browser (v116.0.5845.72) from Play Store and installed refined github extension from chrome extension store, then I tried to open extension options to set my personal access token for GitHub but nothing happens when I click on "Extension options" tab. On my old setup, before doing factory reset, refined github extension options used to open just fine as I remember setting my GitHub token few times. I toggled option to let refined github collect errors and it shows me this but I'm not sure if it's relevant:

![Screenshot_20230926-182015_Pixel Launcher](https://github.com/refined-github/refined-github/assets/24418520/e23209ae-ae10-43a9-838d-dba6e7cc9d6e)
![Screenshot_20230926-181950_Pixel Launcher](https://github.com/refined-github/refined-github/assets/24418520/984e5936-5897-4835-8cf8-cbf672fdc89d)

I searched in issues here but didn't find any relevant to this. There's #6807 but it's solved since quite a while ago. Apologies if I missed anything to include in this issue, please let me know. If anyone can guide me oh how to solve this, I would be immensely thankful for your help.

**Comment by fregante** [comment]
Unfortunately I can't be of help because Kiwi is not among the supported browsers. I suggest removing the extension and adding it again. If it still fails, try opening an issue on Kiwi's support to find out why. The extension works fine in Chrome.
