### ISSUE TITLE
`one-click-review-submission` seems broken

### ISSUE THREAD

**Issue by ewjoachim** [refined-github/refined-github#6963]
### Description

![Screenshot from 2023-09-27 14-14-57](https://github.com/refined-github/refined-github/assets/1457576/18e62492-feae-4ff2-b2c0-43774d031bf0)

`one-click-review-submission` is completly broken, as show in the screenshot.

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/pull/6954/files

### Extension version

23.9.21

### Browser(s) used

Firefox

**Comment by fregante** [comment]
Thank you for the report! I can confirm the issue and disabled the feature globally.

**Comment by RobHannay** [comment]
Thanks @fregante. I also had this issue (before clearing cache).

I <3 this extension and this feature. I can look at fixing if you've not picked it up yet?

**Comment by fregante** [comment]
Yes, no one has started working on it probably

**Comment by piotrekkr** [comment]
Clearing extension cache did not work for me so still issue. Or were you talking about clearing browser cache issue?

**Comment by fregante** [comment]
Note: the "hotfix" simply disables the feature so the website is no longer broken. For the actual fix you'll have to wait the PR above to be finished and then released (maybe in a week)
