### ISSUE TITLE
`no-unnecessary-split-diff-view`: 

### ISSUE THREAD

**Issue by tonglil** [refined-github/refined-github#6965]
### Description

This doesn't seems to be working on Firefox?
I can see this as activated in the console, and I've cleared the cache in the addon settings.

### How to replicate the issue + URL

https://github.com/hashicorp/vault/pull/23353/files

https://imgur.com/a/eEu6mEF

Same with https://github.com/refined-github/sandbox/compare/no-unnecessary-split-diff-view?expand=1&diff=split, everything is split.

<img width="1280" alt="image" src="https://github.com/refined-github/refined-github/assets/3250776/93f969db-5577-42bb-a4df-3aff93a0c911">

### Extension version

23.9.21

### Browser(s) used

Firefox 117.0.1 (64-bit)

**Comment by fregante** [comment]
Firefox doesn't support it yet. Next month it will

- https://github.com/refined-github/refined-github/issues/5797
