### ISSUE TITLE
Show your pending review status in the PRs list

### ISSUE THREAD

**Issue by TrianguloY** [refined-github/refined-github#6968]
### Description

In the PRs list (/pulls) if you hover on a pr, you can see at the bottom a small message saying if the pr needs your approval or not:
![image](https://github.com/refined-github/refined-github/assets/10616202/f8bb2bdb-2dbf-4df5-a2ae-58179d42ff84)
![image](https://github.com/refined-github/refined-github/assets/10616202/8cf98986-ed59-4029-a8ba-66456f3b5e1f)

This information is not available in the list itself, so you cannot see at-a-glance the prs that needs your approval.

I know you can filter the prs to only show those awaiting review from you, but having the icon/text in the list itself would be faster and more convenient.

## Suggestion
Include an extra icon/text in the list of prs with:
- If the PR requires your approval, and you haven't approved it yet, add an icon/text to indicate that the pr requires your approval.
- If the PR requires your approval, and you have already approved it, add an icon/text to indicate that you already approved the pr.
- If the PR requires your approval, and you have requested changes, add an icon/text to indicate that you requested changes.
- If the PR doesn't require your approval, there is no change (nothing extra)

Notes: GitHub also considers the 'You left a review' as a related status. I don't think this special status needs to be shown, but I wouldn't mind if it is.

## Sample mockups (possible implementations):
Extend the existing text:
![image](https://github.com/refined-github/refined-github/assets/10616202/2839bde1-0d46-4852-87c8-58c904904148)
![image](https://github.com/refined-github/refined-github/assets/10616202/411f2ff7-205f-4a42-8074-af425fc90a15)

Include your user icon with the state:
![image](https://github.com/refined-github/refined-github/assets/10616202/b2372a07-19a7-434f-a9b8-c84a5ef08a2c)
![image](https://github.com/refined-github/refined-github/assets/10616202/c9e5f70c-ac59-4810-8449-9cc663fc5d00)

### Example URLs

https://github.com/refined-github/refined-github/pulls

**Comment by fregante** [comment]
Like for https://github.com/refined-github/refined-github/issues/4730 and https://github.com/refined-github/refined-github/issues/6202, that list is already busy and we shouldn't add further information (there's _a lot_ we could add), especially when, as you said, you can reach that with filters.

I'd advise to just have a bookmark to see the PRs that are awaiting your review, because that's probably what you need to know anyway:

https://github.com/pulls?q=is%3Aopen+user-review-requested%3A%40me+
