### ISSUE TITLE
Releases tab not showing anymore

### ISSUE THREAD

**Issue by chaoscreater** [refined-github/refined-github#6974]
### Description

I'm on the latest build and the Releases tab doesn't show up anymore for some reason. Tried reinstalling and on 2 different Chromium based browsers (Edge and Vivaldi) and neither show the Releases tab.

### How to replicate the issue + URL

Browse to here:
https://github.com/refined-github

### Extension version

23.10.5

### Browser(s) used

Vivaldi, Edge

**Comment by chaoscreater** [comment]
Found this as a workaround:
https://github.com/gitmylo/github-releases-button/blob/main/script.js

**Comment by fregante** [comment]
> Browse to here:
> https://github.com/refined-github

There's no releases on organization pages.

Did you set the token in the options?

**Comment by fregante** [comment]
I assume you forgot to set the token because it works:

![image](https://github.com/refined-github/refined-github/assets/1402241/43092c46-e1cc-4304-98b2-fd58a6478104)

**Comment by chaoscreater** [comment]
Thanks for the fast response.

Yes you're right, I had not set the PAT token and I've got it working now. I wasn't aware of this requirement, as the previous versions didn't need this and the userscript I provided in my previous reply also didn't need it. But that's all good.

**Comment by fregante** [comment]
> previous versions didn't need this

`releases-tab` has required the token for a the past 4 years: https://github.com/refined-github/refined-github/commit/3891c5179fbc5dd3b2c03d2fcd55652129f0a034

but until recently it also tried to read it from the current page, if you visit that first, yeah.
