### ISSUE TITLE
Disable `clear-pr-merge-commit-message` for squash merges

### ISSUE THREAD

**Issue by IanVS** [refined-github/refined-github#6978]
### Description

Many of my projects use squash merges by default, and in those cases I want the PR description to be copied to the commit, which GitHub does but the `clear-pr-merge-commit-message` option removes.

I don't know if it's possible to determine the merge strategy of the repo and disable the feature based on that, but that would be ideal.  

If not, maybe it should be disabled by default, because the behavior is very unexpected and undesirable for those using squash merges.  I saw another [closed feature request](https://github.com/refined-github/refined-github/issues/6181) which would add an `undo` button to the cleared text, which would also solve this issue and give users a heads-up about how to disable the option if they wanted to, because right now it's not clear that refined github cleared the text unless you know about it.

### Example URLs

https://github.com/IanVS/prettier-plugin-sort-imports/pull/136

**Comment by fregante** [comment]
- Refined GitHub does tell you that it cleared the commit body, right next to the field
- the feature can already be disabled if you prefer the native behavior 
- there are no "disabled by default" features, as mentioned in the issue template you just used

https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22

This just shows that we can put as many notices and warnings but they do nothing if they're not read.

**Comment by IanVS** [comment]
I guess it's not so much about the merge strategy, as the repo setting for how the description is created.  And the docs already say it ignores those, so I assume it's not possible.  Too bad.

**Comment by fregante** [comment]
> not clear the message if it is being squash merged?

This feature is exclusively applied to squash merges. 

Yeah unfortunately due to how the native feature was implemented it's impossible to *not* override it.

**Comment by IanVS** [comment]
Yeah, I get it.  I use the option which copies the PR description into the commit, so clearing it out is counter-productive for me.  But that's not the default option so far, and I agree that copying the list of commit titles into the description is annoying.
