### ISSUE TITLE
Auto-merge warning when approving a PR

### ISSUE THREAD

**Issue by ngouy** [refined-github/refined-github#6979]
### Description

How many time I did approve a PR to not block someone, but with comments that still need to be addressed idealy before merging

But PR was in auto-merge mode (GH native auto-merge) and I didn't saw it

Could we have a visual hint or something on such PR on the approval box?

WDYT?

<img width="654" alt="image" src="https://github.com/refined-github/refined-github/assets/12391171/e994a291-4270-4de2-910f-bfb4eea58682">

### Example URLs

https://github.com/refined-github/refined-github/pull/6972/files#review-changes-modal

**Comment by fregante** [comment]
There are a couple of issues:

- this requires an API call
- this data can at any time become stale (e.g. someone enables auto-merge while you review)

I'm not entirely sure this can be done reliably. I think it's best to:

- avoid enabling auto-merge while waiting for reviews, as a policy on the repo
- not approve PRs if there's more to be done

**Comment by ngouy** [comment]
I don't have any idea on how to do that so all good. I wasn't even pretending it was doable

Also thanks for the advice. "you should change things on your side" never gets old 🤣
_There is always more to be done ^^
An approved PR is just a place where we agree we can move forward with curent, even if more can be done_

Anyway - Noted. I took my chance, happy to close the ticket, now there is a trace of it if ever someone is wondering
Thanks for the amazing work you do 💪
