### ISSUE TITLE
`repo-header-info`: Cache invalidation

### ISSUE THREAD

**Issue by ewjoachim** [refined-github/refined-github#6981]
### Description

If a repository is private, and then switched to public, the lock indicating it's private still appears for an indeterminate amount of time.

![Screenshot from 2023-10-13 09-30-59](https://github.com/refined-github/refined-github/assets/1457576/8a0efe1e-595b-483c-afad-91ef36514ee8)
![Screenshot from 2023-10-13 09-31-05](https://github.com/refined-github/refined-github/assets/1457576/64223fd8-28ef-45f1-a395-57adf133f444)

### How to replicate the issue + URL

I reproduced here: https://github.com/ewjoachim/refined-github-public-private-cache

Steps:
- Create a private repo
- Make it public
- Lock still appears

(to be clear the issue "disappears" if I clear the cache, but if I re-follow the steps, it reappears. Of course, that's expected as the issue here is the cache itself)

### Extension version

23.10.5

### Browser(s) used

Firefox

**Comment by fregante** [comment]
Thank you, but yes this is how cache works. The data is persisted for at least 1 day.

https://github.com/refined-github/refined-github/blob/ba686ec428909508e4b8191f0d011be3e9c354c8/source/features/repo-header-info.tsx#L25
