### ISSUE TITLE
in github action annotations identifiers like `@return` should not be rendered as a username

### ISSUE THREAD

**Issue by staabm** [refined-github/refined-github#6982]
### Description

in one of our private repos we get error messages regarding the `@return` type of a function (in a PHP codebase) linked with the github user `@return`.

I think the machnism which links text preceeding a `@` char and looks like a user name should not be used within github action annotations

### How to replicate the issue + URL

~~sorry I don't have a public url, hopefully the screenshot tells the whole story~~

just open the url https://github.com/redaxo/redaxo/pull/5842/files

![grafik](https://github.com/refined-github/refined-github/assets/120441/94b0973d-7129-40f2-91af-d4e42268e6ec)

### Extension version

23.10.5

### Browser(s) used

Google Chrome Version 117.0.5925.0

**Comment by staabm** [comment]
I was able to reproduce the issue in a public repo: https://github.com/redaxo/redaxo/pull/5842/files

(updated the above description)

**Comment by fregante** [comment]
Thank you for the report, but this isn't a bug in Refined GitHub. That mention is a bug, it links to the user https://github.com/return and it should be fixed/avoided. 

Refined GitHub only makes it more visible, but the link is there. 

We could add an exception for those common words but 🤷‍♂️ the bug is elsewhere

**Comment by staabm** [comment]
thanks for the fast feedback.

do you mean the extension which generates these error message should escape the `@return` somehow?
the message currently is rendered like

`PHPDoc tag @return with type bool is incompatible with native type rex_clang.`

what would be the right escaping for the message?
I can fix the message-creating component if I know how the message needs to be formatted :-)

**Comment by fregante** [comment]
The formatting is decided by GitHub. I'm not sure if there's a way to disable autolinking of usernames. The only way I know is to wrap the `@text` in a `code` tag exactly like I just did
