### ISSUE TITLE
`select-notifications` - Add filter for canceled actions

### ISSUE THREAD

**Issue by huehnerlady** [refined-github/refined-github#6984]
### Description

We have a cost effective action setting, where the old action is cancelled when eg. a new commit has been pushed. This appears in the notifications page like this:
![image](https://github.com/refined-github/refined-github/assets/12533979/e75c1113-cd70-4ad7-a029-564bb08286d3)

I would love if there could be a filter for cancelled commits

### Example URLs

https://github.com/notifications

**Comment by fregante** [comment]
Refer to https://github.com/refined-github/refined-github/issues/6980#issuecomment-1760057868

**Comment by huehnerlady** [comment]
@fregante ok, a shame, because everything else would not work for me.

But it was worth a try
