### ISSUE TITLE
Setting for disabling "Show more workflows..." in Actions tab

### ISSUE THREAD

**Issue by piotrekkr** [refined-github/refined-github#6985]
### Description

I have like 20+ workflows defined in GitHub repo and it always collapse workflows list and show this `Show more workflows...`. To see multiple workflows runs I have to click it multiple times just to see full list of workflow and choose workflows I want. It is pretty irritating tbh.

![image](https://github.com/refined-github/refined-github/assets/503782/6c181d85-6411-4f0e-b17f-0117672416a6)

I could not find any setting related to this in Refined GitHub settings so this is my feature request. Thank you for this great tool.

### Example URLs

https://github.com/piotrekkr/workflow-test/actions

**Comment by fregante** [comment]
> ### Example URLs
> [refined-github/refined-github/actions](https://github.com/refined-github/refined-github/actions)

Can you provide a URL where there's a "Show more workflows" button?

**Comment by piotrekkr** [comment]
Atm I can't because it is inside private repository, but I will prepare some dummy public repo with this and will link it here.

**Comment by piotrekkr** [comment]
@fregante here it is https://github.com/piotrekkr/workflow-test/actions

**Comment by fregante** [comment]
They added workflow pinning now, which means you might be able to just pick the important ones now.

If not enough, this feature can be implemented in one line in your userscript manager (`$('that link')?.click()`)

**Comment by piotrekkr** [comment]
Okay thanks. Will use userscript then.
