### ISSUE TITLE
Some features show information from the wrong/previous repository visited

### ISSUE THREAD

**Issue by 134130** [refined-github/refined-github#6988]
### Description

- `repo-header-info` show invalid repository's stargazer-count.
- <img width="793" alt="image" src="https://github.com/refined-github/refined-github/assets/50487467/6c9f449a-4d11-4ce9-85db-2e33060b0c75">

### How to replicate the issue + URL

1. Clear cache of refined-github
2. Go to https://github.com/refined-github/refined-github
3. Go to it's organization with Left top's breadcrumb 
    <img width="456" alt="image" src="https://github.com/refined-github/refined-github/assets/50487467/b4118598-76da-4134-9821-1dc67e9c743e">
4. Go to other repository
5. Check your `repo-header-info` stargazer-count

### Extension version

23.10.5

### Browser(s) used

Chrome

**Comment by 134130** [comment]
The reason is `CachedFunction`'s cacheKey is initialized with `refined-github/refined-github`, and visiting other repository with out script reloading (soft-rendering), CachedFunction still has cacheKey to `refined-github/refined-github`

https://github.com/refined-github/refined-github/blob/main/source/features/repo-header-info.tsx#L20-L28

There can be same cache issues which initializes `CachedFunction` like this case.

**Comment by fregante** [comment]
That `cacheKey` is dynamic, it depends on `location.href`

Maybe the issue is that it's fired at the wrong time due to:

- https://github.com/refined-github/refined-github/issues/6437

**Comment by 134130** [comment]
> That `cacheKey` is dynamic, it depends on `location.href`
> 
> Maybe the issue is that it's fired at the wrong time due to:
> 
> - https://github.com/refined-github/refined-github/issues/6437

Yes. I've checked `cacheKey` is correctlly updated on feature init callback.
But, the `cacheKey` is passed to `CachedFunction`'s constuctor as value, cannot apply `location.href` dynamically, when soft-rendering cases.

**Comment by fregante** [comment]
I have a repro for another feature, `default-branch-button`:

1. Clear cache
2. Open this in a new tab https://github.com/sindresorhus/p-retry/releases/tag/v6.1.0
3. Click "separate package"
4. Open a file or folder


https://github.com/refined-github/refined-github/assets/1402241/e28c4aa8-4540-4c66-af4d-4776a6bb14c4

**Comment by fregante** [comment]
Oof, it doesn't simply mess up the current view, but it also messes up the cache. I thought this was just a few issue, but for some reason it takes the previous value and stores it on the current URL.

My guess is that `getRepo` is called at different times, or that `webext-storage-cache` is memoizing the function call incorrectly.

**Comment by fregante** [comment]
> Is this really just a cache / memoization issue?

Did you clear the cache? I see 507

**Comment by jplatte** [comment]
I disable and re-enabled the extension, that didn't help. Now I also tried clearing cookies and other data from the URL header in Firefox (after which I had to login again). The count is still at 2.1k.

**Comment by fregante** [comment]
> I disable and re-enabled the extension, that didn't help

There's a "Clear cache" button in the extension's options page, not the browser's

**Comment by jplatte** [comment]
I didn't know about that. Now it just fails to show the header info entirely, even after navigating around a bit.

**Comment by 134130** [comment]
Not sure, but as you said, It appeares frequently and commonly on other features also.

**Comment by fregante** [comment]
The issue is:

- https://github.com/refined-github/refined-github/issues/6637
- Memoization
- specifically api.v4
