### ISSUE TITLE
`action-pr-link` not working on the PR Checks tab

### ISSUE THREAD

**Issue by brianjmurrell** [refined-github/refined-github#6989]
### Description

I cannot seem to get this:
https://github-production-user-asset-6210df.s3.amazonaws.com/50487467/241645264-076a0137-36a2-4fd0-a66e-735ef3b3a563.png

Instead I see this:
![image](https://github.com/refined-github/refined-github/assets/559317/bbd053e3-d6e6-48e5-887c-af15baa5dba8)

### How to replicate the issue + URL

Observe at https://github.com/refined-github/refined-github/actions/runs/6548411198

### Extension version

23.10.5

### Browser(s) used

Chromium

**Comment by brianjmurrell** [comment]
I see.  I was trying to do the latter, but navigating through the _Actions_ tab rather than through the _Commit Status_ links.

**Comment by fregante** [comment]
Do you mean the Actions tab in the PR? We can "fix" those links too if necessary. 

If you see any pages that:

- have a link to a workflow run, AND
- has information regarding the PR triggered, on the same page 

Please share them and we'll enable the feature on those pages.

**Comment by brianjmurrell** [comment]
> Do you mean the Actions tab in the PR? We can "fix" those links too if necessary.

Apologies.  I mean the Checks tab in the PR.

But now that I am playing with this refinement a bit more, I'm not sure I like it.  I miss being able to go back to list of runs for a particular test.  I.e. the:

![image](https://github.com/refined-github/refined-github/assets/559317/a167b8ea-bae7-487b-8de2-d20a05ec092a)
from my screenshot.  Is there any chance of having links to both?

**Comment by fregante** [comment]
That link is generated by GitHub, they already do that on some links but not others. Just just fill in the blanks
