### ISSUE TITLE
Quote reply with link to comment

### ISSUE THREAD

**Issue by Malix-off** [refined-github/refined-github#6990]
## Problem

Current "Quote Reply" feature only quote
It doesn't provide any link to the message nor mention to its author

## Possible Solution

Having a "Refined Reply" that has kind of this template:
```md
- [Comment Reply](SOURCE_COMMENT_URL) from @USER:
  > [⋯](SOURCE_COMMENT_URL) QUOTE [⋯](SOURCE_COMMENT_URL)

  REPLY 
```

## Example URLs

https://github.com/refined-github/refined-github/issues/6990#issue-1948138496

**Comment by fregante** [comment]
If I remember correctly @jerone or @yakov116 knows of a user script that creates detailed quote replies

**Comment by jerone** [comment]
[**@fregante**](https://github.com/fregante) commented on [Oct 18, 2023, 3:36 AM GMT+2](https://github.com/refined-github/refined-github/issues/6990#issuecomment-1767468238 "2023-10-18T01:36:31Z - Replied by Github Reply Comments"):
> If I remember correctly @jerone or @[yakov116](https://github.com/yakov116) knows of a user script that creates detailed quote replies

https://greasyfork.org/en/scripts/38372-github-reply-comments
