### ISSUE TITLE
Request Tab"Code" file sort by date modified

### ISSUE THREAD

**Issue by androidcn** [refined-github/refined-github#6994]
### Description

Request Tab"Code" file sort by date modified

![WX20231023-140701@2x](https://github.com/refined-github/refined-github/assets/271715/97cca988-db4b-4b36-9900-7f9aa35eb2f1)

### Example URLs

https://github.com/refined-github/refined-github/

**Comment by kidonng** [comment]
The issue is where to put yet another button/dropdown.

If you just want a quick run, this sorts from newest from oldest:

```javascript
files = document.querySelector('[aria-labelledby="folders-and-files"] tbody')
children = [...files.children]
files.replaceChildren(
    children[0],
    ...[...files.querySelectorAll('[aria-labelledby="folders-and-files"] .react-directory-row')].sort((a, b) =>
        new Date(a.querySelector('relative-time').datetime) < new Date(b.querySelector('relative-time').datetime) ? 1 : -1
    ),
    children.at(-1),
)
```

**Comment by androidcn** [comment]
> The issue is where to put yet another button/dropdown.
> 
> If you just want a quick run, this sorts from newest from oldest:
> 
> ```js
> files = document.querySelector('[aria-labelledby="folders-and-files"] tbody')
> children = [...files.children]
> files.replaceChildren(
>     children[0],
>     ...[...files.querySelectorAll('.react-directory-row')].sort((a, b) =>
>         new Date(a.querySelector('relative-time').datetime) < new Date(b.querySelector('relative-time').datetime) ? 1 : -1
>     ),
>     children.at(-1),
> )
> ```

Wow Thanks...
run it in Chrome(safari) console? how to do it ?

**Comment by kidonng** [comment]
Yep, paste the code in DevTools console and run.

**Comment by androidcn** [comment]
> Yep, paste the code in DevTools console and run.

<img width="845" alt="image" src="https://github.com/refined-github/refined-github/assets/271715/0f73d2da-5b8f-4078-b14a-503918e485d2">
not work

**Comment by kidonng** [comment]
You probably need to enable the "New Repository Overview" feature preview (in your profile menu), old DOM could be different (and I don't have interest in that).

Anyway this is going a little off-topic. Personally I would like some sort of sorting, it's just... too big of a feature.

**Comment by androidcn** [comment]
> You probably need to enable the "New Repository Overview" feature preview (in your profile menu), old DOM could be different (and I don't have interest in that).
> 
> 
> 
> Anyway this is going a little off-topic. Personally I would like some sort of sorting, it's just... too big of a feature.

Thanks，work！hope to add this feature to refined-github

**Comment by androidcn** [comment]
> The issue is where to put yet another button/dropdown in a already crowded space.
> 
> If you just want a quick run, this sorts from newest from oldest:
> 
> ```js
> files = document.querySelector('[aria-labelledby="folders-and-files"] tbody')
> children = [...files.children]
> files.replaceChildren(
>     children[0],
>     ...[...files.querySelectorAll('.react-directory-row')].sort((a, b) =>
>         new Date(a.querySelector('relative-time').datetime) < new Date(b.querySelector('relative-time').datetime) ? 1 : -1
>     ),
>     children.at(-1),
> )
> ```

please add the  feature to the project.thanks

**Comment by fregante** [comment]
This can be its own feature: sort by date, commit, name, etc. not in Refined GitHub. 

Refined GitHub does already highlight recent files so if you want to see recent changes you already can

**Comment by androidcn** [comment]
> This can be its own feature: sort by date, commit, name, etc. not in Refined GitHub.
> 
> Refined GitHub does already highlight recent files so if you want to see recent changes you already can

Thanks
