### ISSUE TITLE
`releases-tab` hidden in navigation dropdown

### ISSUE THREAD

**Issue by mjmatthiesen** [refined-github/refined-github#6995]
### Description

The main reason I have this extension is for the releases tab. Not sure if github broke something, or the extension.

![image](https://github.com/refined-github/refined-github/assets/16603906/202a24a8-11e6-4f39-8647-9bb1d08305db)

### How to replicate the issue + URL

https://github.com/rcmaehl/MSEdgeRedirect

### Extension version

23.10.5

### Browser(s) used

Firefox

**Comment by fregante** [comment]
When there are too many tabs, they're hidden in the dropdown. I think that  due to a race condition it's not being recalculated. Maybe in Firefox this line is broken:

https://github.com/refined-github/refined-github/blob/906da8c189127627f23fd3f0a706c2369a79c9b0/source/features/releases-tab.tsx#L69

**Comment by mjmatthiesen** [comment]
Do you mean this option in the extension?

![image](https://github.com/refined-github/refined-github/assets/16603906/c6ba4d16-5f77-4c55-866d-e6d543b5f533)

Then yes, it is enabled. If you are referring to the personal token, then no. I didn't need one for this in the past, so I never bothered. I know this extension has a lot of things happening, but I installed it only for the releases tab and have no clue on what else it may or may not do.

I downsized my view for the screenshot. I'm on an ultra wide, there's a lot of space for tabs. Can't comment on race condition or not.

![image](https://github.com/refined-github/refined-github/assets/16603906/66ccc4e4-c674-4b1b-995b-5f90f2d5af98)

I know when I refresh I see the security and insight links for a quick second. So my gut says this may be an error GH side, but maybe that's another feature extension.

**Comment by fregante** [comment]
I think the bug here is that we're adding the item in the dropdown even when it shouldn't be there. 

That feature has required a token probably for the past 3 months, so a bugfix would not *restore* the tab for you.  


I invite you to add a token if you want to use the feature, it's only needed to read data from the API

**Comment by fregante** [comment]
Confirmed: we're adding the tab regardless of releases:

 https://github.com/refined-github/refined-github/blob/906da8c189127627f23fd3f0a706c2369a79c9b0/source/features/releases-tab.tsx#L72

The code should be altered to query the API the same way we do it for the actual tab. That code can be copy-pasted into this function

**Comment by mjmatthiesen** [comment]
> I think the bug here is that we're adding the item in the dropdown even when it shouldn't be there.
> 
> That feature has required a token probably for the past 3 months, so a bugfix would not _restore_ the tab for you.
> 
> I invite you to add a token if you want to use the feature, it's only needed to read data from the API

While I use gh quite a bit, it's only to look at code, so that's probably why I didn't notice that the releases tab has been gone for so long.
Can I ask why it now requires a token when it previously didn't?

**Comment by fregante** [comment]
> Can I ask why it now requires a token when it previously didn't?

It has actually used a token for like 5 years because the GraphQL API requires it. 

Until recently we also attempted to read the release count in the repository home tab, but this only lead to complexity and more issues. For example this page-based detection had been failing for god-knows how long and it caused the information to never be cached, therefore hitting the API at every page load.

**Comment by mjmatthiesen** [comment]
Great, thanks for the answers! This issue is solved for me.
