### ISSUE TITLE
`linkify-code` breaks on search page

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#6996]
### Description

![image](https://github.com/refined-github/refined-github/assets/44045911/f92f240c-0b5c-4ed6-98cf-2cbe48205330)

Need to update this part to extract info from URL:

https://github.com/refined-github/refined-github/blob/906da8c189127627f23fd3f0a706c2369a79c9b0/source/github-helpers/dom-formatters.tsx#L31-L38

### How to replicate the issue + URL

https://github.com/search?q=repo%3Anotion-enhancer%2Fnotion-repackaged%20sqlite&type=code

### Extension version

23.10.5

### Browser(s) used

Chrome

**Comment by fregante** [comment]
Yeah it needs to extract the snippet's repo name. I thought we already did that but it probably broke
