### ISSUE TITLE
Show assigned users in Issue popover.

### ISSUE THREAD

**Issue by zoey-kaiser** [refined-github/refined-github#6997]
### Description

Github has a really nice feature, where you can embed links to issues inside of markdown text (such as #6997). When hovering over this reference you can see the title and a brief description of the issue (S1). 

I think it would be super helpful to also see who is assigned to this issue. This is something I have noticed in my day to day work, as we often make larger collection issues, where we write the priorities down quickly to coordinate our sprints (using boards often takes too much time, so we do it in a collection issue).
Developers can see if they were assigned (S2), but if you are not assigned, you miss out on this information.

I would also love to work on implementing this myself, however have never worked on a browser extension before, so I feel a bit lost. Maybe I could get some pointers?

Thanks in advance everyone!

S1:
![Screenshot 2023-10-24 at 16 32 51](https://github.com/refined-github/refined-github/assets/30908158/36cc8572-d862-4618-a90c-55fba2426e9a)

S2:
![Screenshot 2023-10-24 at 16 39 03](https://github.com/refined-github/refined-github/assets/30908158/e99d32ce-c153-492d-a936-508f5c6a1920)

S3: (Mockup of something I imagine, position would need to be determined, but this is the information I would love to see, maybe it could also be shown in text form like in S2)
![Untitled design(1)](https://github.com/refined-github/refined-github/assets/30908158/0a9464b3-be71-456d-9e35-9765bc01788d)

### Example URLs

https://github.com/refined-github/refined-github/issues/6997
(Any page where we have a markdown text edit field, see example above)

**Comment by yakov116** [comment]
This would require an API request for every single popup

**Comment by zoey-kaiser** [comment]
> This would require an API request for every single popup

Aww thats too bad, I was hoping the information for the assignees was already fetched when the popup shows the title and description.

**Comment by fregante** [comment]
There's a lot of information around issues and PRs that we could show, depending on everyone's needs, so I think it's best we don't start adding information that is rarely there in the first place.
