### ISSUE TITLE
Request: GIF integration (via Giphy, Imgur, etc.)

### ISSUE THREAD

**Issue by jamesbraza** [refined-github/refined-github#6998]
### Description

This request is https://github.com/refined-github/refined-github/issues/72, but 7-years later and not specific to Giphy.

Can Refined GitHub support GIF integration (via Giphy, Imgur, etc.)? 🤓 

This would make Refined GitHub a vehicle for better PR culture :)

### Example URLs

https://github.com/DrewML/GifHub#gifhub

Seems pretty close, just a button to paste in GIFs.

**Comment by fregante** [comment]
Indeed that feature already exists as a standalone extension, so we don't add it to Refined GitHub, as specified  in 
https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22
