### ISSUE TITLE
Linkify workflow `uses`

### ISSUE THREAD

**Issue by Katsute** [refined-github/refined-github#6999]
### Description

Linkify actions and reusable workflows inside workflow files.

**Actions:**

` - uses: actions/checkout@v4`
↓
<code> - uses: <a href="https://github.com/actions/checkout/tree/v4">actions/checkout@v4</a></code>

**Reusable workflows:**

`    uses: Katsute/Workflows/.github/workflows/npm.ci.yml@main`
↓
<code>    uses: <a href="https://github.com/Katsute/Workflows/blob/main/.github/workflows/npm.ci.yml">Katsute/Workflows/.github/workflows/npm.ci.yml@main</a></code>

### Example URLs

(action) https://github.com/refined-github/refined-github/blob/main/.github/workflows/release.yml

(reusable workflow) https://github.com/KatsuteDev/Background/blob/main/.github/workflows/npm_ci.yml

**Comment by busches** [comment]
This already exists in https://github.com/OctoLinker/OctoLinker
