### ISSUE TITLE
23.10.5 fails on Vivaldi

### ISSUE THREAD

**Issue by chunming08** [refined-github/refined-github#7006]
### Description

I recently upgraded my browser Vivaldi to 6.4
![image](https://github.com/refined-github/refined-github/assets/48174073/80868460-2806-464d-a980-a3a7b914011d)

And suddenly the refined-github doesn't work due to the javascript problem for the corporate-managed GitHub Enterprise
![image](https://github.com/refined-github/refined-github/assets/48174073/75363e39-bd88-41db-a538-eba6d3aa3635)

### How to replicate the issue + URL

I assume this can also be reproducible on the public GitHub by using the browser and extension

### Extension version

23.10.5

### Browser(s) used

Vivaldi 6.4.3160.34

**Comment by fregante** [comment]
It works for me:

<img width="972" alt="Screenshot 5" src="https://github.com/refined-github/refined-github/assets/1402241/a7afb32f-c34a-47f8-b03e-f5958fbfe874">

Maybe there are some errors in your case for some reason:

1. Open `chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/options.html`
2. Open the dev tools
3. Look for any errors in the console

**Comment by fregante** [comment]
My best guess is that this can be resolved by closing and reopening the browser, if it still happens
