### ISSUE TITLE
Auto delete of source branch when merge pull request

### ISSUE THREAD

**Issue by Hexi1997** [refined-github/refined-github#7008]
### Description

When merging code, the source branch will be automatically deleted. How can I close it? Or is this a bug? It's annoying
![1xO0d0MV5q](https://github.com/refined-github/refined-github/assets/66669483/cb8651e5-fea6-4a91-be35-a9dadd118f6f)
![ygOBcuoClo](https://github.com/refined-github/refined-github/assets/66669483/3f1fdb1b-e1a6-4961-94d1-8d24ceb55c07)

### How to replicate the issue + URL

https://github.com/Hexi1997/miui-interface-imitation

### Extension version

23.10.5

### Browser(s) used

chrome 114

**Comment by fregante** [comment]
Read the "event" it generates. It has all the information needed. 

You can disable it in the options

**Comment by Hexi1997** [comment]
> Read the "event" it generates. It has all the information needed.
> 
> You can disable it in the options

how to disable in the options? I can not find entry

**Comment by Hexi1997** [comment]
![image](https://github.com/refined-github/refined-github/assets/66669483/2ecad7ea-34ca-458d-afa7-af6dfc673dc9)
ok, I finally find it. But why this is default open? 

This is very confusing, if the user installs this plug-in and then merges the code, the source branch will be deleted by default. It's hard to find the way to turn this setting off

**Comment by fregante** [comment]
Nothing is ever deleted on GitHub. If your branch is not meant to be deleted, you can activate branch protections.
