### ISSUE TITLE
`one-click-review-submission` gone?

### ISSUE THREAD

**Issue by bartgol** [refined-github/refined-github#7010]
### Description

The buttons for the one-click-review-submission feature seem to be gone. Today I upgraded google-chrome on my RHEL8 machine, and the feature was gone after that. I verified under the refined github options that the feature _is_ enabled (I see the checkmark).

If it helps, the repo where I upgraded google-chrome from is https://dl.google.com/linux/chrome/rpm/stable/x86_64, and the old/new versions of the pkg are

- New: google-chrome-stable-118.0.5993.117-1.x86_64
- Old: google-chrome-stable-116.0.5845.179-1.x86_64

Not sure if something changed in chrome to cause this issue? Or maybe I'm doing something wrong?

### How to replicate the issue + URL

I see this on every PR. For instance: https://github.com/E3SM-Project/scream/pull/2587

### Extension version

23.10.5

### Browser(s) used

Chrome

**Comment by fregante** [comment]
It looks like they made a few changes around the input fields, see also:

- #7011
