### ISSUE TITLE
Form-related features missing

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7011]
### Description

The "new comment" form was updated and I see a few features missing

<img width="881" alt="Screenshot 8" src="https://github.com/refined-github/refined-github/assets/1402241/1beecd72-b75c-4a80-9c80-042e3e879796">

This is a generic issue to keep track of all these changes. Specific issues for each feature can be open an just point here.

- [x] https://github.com/refined-github/refined-github/issues/7012
- [x] https://github.com/refined-github/refined-github/issues/7010
- [x] https://github.com/refined-github/refined-github/issues/7013
- [x] https://github.com/refined-github/refined-github/issues/7020

### How to replicate the issue + URL

This issue

### Extension version

23.9.21

### Browser(s) used

Safari

**Comment by kidonng** [comment]
`table-input` and `collapsible-content-button` are back but doesn't use new tooltip style nor work with the responsive menu. That would need more work

Also, while we are at it, here's a little script that fixes the jumping issue of the menu button:

```js
document.querySelector('markdown-toolbar action-menu:not([hidden])').addEventListener('mousedown', () => {
    const {scrollY} = window
    window.addEventListener('scroll', () => {
        window.scrollTo(0, scrollY)
    }, { once: true })
})
```

**Comment by fregante** [comment]
Closing for now, I went through every "Writing comments" feature and dropped a couple. 

New issues can be opened for specific bugs
