### ISSUE TITLE
`table-input` and `collapsible-content-button` missing

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7012]
### Description

See https://github.com/refined-github/refined-github/issues/7011

### How to replicate the issue + URL

This issue

### Extension version

23.10.5

### Browser(s) used

Chrome

**Comment by auscompgeek** [comment]
These buttons seem to still be missing for me.

**Extension version**: 23.11.3
**Browser**: Firefox 119

**Comment by fregante** [comment]
Unfortunately the changes required broke it in Firefox. See #5797 for an `about:config` fix in the meanwhile
