### ISSUE TITLE
`clean-rich-text-editor` missing

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7013]
### Description

https://github.com/refined-github/refined-github/issues/7011

### How to replicate the issue + URL

This issue

### Extension version

23.10.5

### Browser(s) used

Chrome

**Comment by kidonng** [comment]
Maybe a good opportunity for #6512? But the new native menu on mobile is kinda broken (it scrolls the page to the top for no reason, and I can't see the menu at all sometimes)

**Comment by fregante** [comment]
Yeah totally. Whatever is PR'd first
