### ISSUE TITLE
Auto-format feature names in titles and comments

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7014]
Sometimes features are mentioned without using the proper formatting, so linkification fails:

- ✅ `linkify-code`
- ❌ linkify-code
- ❌ linkify code

We can fix this on a repo level via workflow that edits titles and comments like https://github.com/refined-github/refined-github/blob/main/.github/workflows/labeler.yml

Possible solution:

1. Listen to new comments and titles (no edits)
1. Get feature list using https://github.com/refined-github/refined-github/blob/main/build/readme-parser.ts
2. Run a search/replace with the feature list

Ideally this logic is in a standalone .ts file and has its own .test.ts file so that we can ensure we don't break it.

Example scenario where this workflow would have run: https://github.com/refined-github/refined-github/issues/7010#event-10828153656

**Comment by kidonng** [comment]
No offense but this gives https://xkcd.com/1319/ vibes.

I see a few issues. Some feature names are common enough word combinations that we can't just do search and replace automatically.

And I assume people either reference `feature-name` all the time, or don't know/care about them at all, which would need manual fixes from us anyway.  The actual value of such an automation is questionable.

**Comment by fregante** [comment]
> No offense but this gives [xkcd.com/1319](https://xkcd.com/1319/) vibes.

I know which one that is without opening it 😃 

Would you rather roll a boulder up the hill ["many times"](https://en.wikipedia.org/wiki/Sisyphus) or build a fence after the first roll up?

> tons of false positives

Doubt that there would be tons, maybe just `pr-filters`. In any case further edits would be excluded, so _if_ it's a false positive it can be undone. Worst case scenario we limit it to dashed-words, but still.


> which would need manual fixes from us anyway

The point of this script would be to reduce the load, especially because changing "One click review submission" to \`one-click-review-submission\` requires at a minimum 10 keystrokes and or mouse movements.

> The actual value of such an automation is questionable

_Watch how you talk to our [automation overlords](https://www.youtube.com/watch?v=7Pq-S557XQU&themeRefresh=1)_ :robot:

Like for https://github.com/fregante/title-to-labels-action, the value is minimal, but when I don't have it installed, I miss it.

The problem I see is actually more regarding markdown content, because one could [talk about pr filters](#some-link) or just

```js
// See pr-filters
```

and we can't safely apply replacements to that. So at most it should only run on titles. I think it's a simple script, it's worth a try.

**Comment by fregante** [comment]
🥹 

- https://github.com/refined-github/refined-github/issues/7137
