### ISSUE TITLE
Recursively Expand PR Conversation View

### ISSUE THREAD

**Issue by pdemro** [refined-github/refined-github#7018]
### Description

From time to time our project will have a very large PR (see screenshot).  The "Files Changed" view will load very slowly.  The best and most performant way to view a list of all feedback items at a glance is the conversation view.

As feedback items are addressed, the "conversation" starts to expand to the point of having to click "Load more..." a dozen or more times to get a full view of all the comments.

It would be nice to have something which will recursively call this expansion until everything is loaded.  Even better would be to roll this into the existing "filter" feature, where filtering the view would cause expansion.  In this case, this feature request would require the addition of a "comments only" filter which would trigger the expansion

![image](https://github.com/refined-github/refined-github/assets/5431128/89b59a17-492b-46d4-b9e0-4b1e2554d295)

### Example URLs

Private repo  unfortunately, but I've included a screenshot of the filter feature where this could possibly slot in

![image](https://github.com/refined-github/refined-github/assets/5431128/d440c86f-cca7-4875-99c5-e73003cc98a9)

**Comment by fregante** [comment]
We already have it, it's called `expand-all-hidden-comments` 🎉
