### ISSUE TITLE
`fit-textareas` broken

### ISSUE THREAD

**Issue by FloEdelmann** [refined-github/refined-github#7023]
### Description

#7011

### How to replicate the issue + URL

This issue

### Extension version

23.10.5

### Browser(s) used

Firefox 119.0

**Comment by FloEdelmann** [comment]
Hmm, actually it works here now...

**Comment by FloEdelmann** [comment]
Maybe it's rather caused by #6554.

**Comment by fregante** [comment]
> Maybe it's rather caused by #6554.

That is only related to files/folder at the moment, because the entire UI including navigation is a single app that spans across multiple pages/urls.

**Comment by FloEdelmann** [comment]
Ah, I see. Let's close this issue then until I can reproduce it reliably.
