### ISSUE TITLE
`close-as-planned` has weird behavior

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#7024]
### Description

[Kooha-2023-11-02-02-46-26.webm](https://github.com/refined-github/refined-github/assets/44045911/7cd59491-0815-43a6-b451-64d7f9255aaf)

### How to replicate the issue + URL

Here

### Extension version

199b54b33a864017b9276558f3ffd43292986ce6

### Browser(s) used

Chrome

**Comment by fregante** [comment]
fuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu I thought about it but never tested it. #6973 was open for 3 weeks…
