### ISSUE TITLE
Show author-date on list of commits

### ISSUE THREAD

**Issue by truthdoug** [refined-github/refined-github#7026]
### Description

When viewing a list of commits, either for a branch or in a PR, the dates of the commit are the committer-date instead of author-date. So if a branch has a dozen commits authored over a month but the branch was rebased one hour ago, all the commits show as "**My User** committed 1 hour ago".

If I run `git log --pretty=fuller` at the command line I see both dates. If I run just `git log`, I see the author-date.

It would be helpful for me to show `author-date` in addition to (or as an option to replace) `committer-date`

### Example URLs

https://github.com/refined-github/refined-github/commits/i-can-has-cheeseburger
https://github.com/refined-github/refined-github/pull/3955/commits

**Comment by fregante** [comment]
GitHub doesn't show that piece of information anywhere on the site I think, probably useful to most. There's a lot of metadata that _could_ be shown there.

Similar to the PR list situation: https://github.com/refined-github/refined-github/issues/6968#issuecomment-1739059321

**Comment by milindsmart** [comment]
Funnily, if one directly commits to a repo branch that they have access to, then the "commits" page of that branch shows the commit-date as "<user> committed <days ago>" or "<user> committed on <date>". 

However, if one makes a PR for it and then merges it, then it shows the author-date as "<user> authored <days ago>" or "<user> authored on <date>". For the next person who wonders about this and searches...
