### ISSUE TITLE
Allow bulk closing issues as not planned

### ISSUE THREAD

**Issue by KaelWD** [refined-github/refined-github#7028]
### Description

Related to #6883

This dropdown currently only closes issues as completed, if you want to mark them not planned you have to close each one individually:

![Screenshot_20231102_220956](https://github.com/refined-github/refined-github/assets/16421948/0a55eded-a122-4ae9-bae7-32a25d1d8f71)

### Example URLs

https://github.com/refined-github/refined-github/issues

**Comment by fregante** [comment]
This would be interesting, although given the rarity of the action I'd probably only accept it if it's as easy as `$(closedButton).clone().attr('value', 'not-planned').after(closedButton)`. 

I don’t think it's worth setting up the whole thing via API, as it's much more involved

**Comment by fregante** [comment]
It doesn't look like that's possible. I also tried adding another `input[name="state_reason"][value="not_planned"]` matching what's in the issue itself, but that didn't work. Closing for now
