### ISSUE TITLE
`close-as-unplanned` looks unexpected

### ISSUE THREAD

**Issue by janpio** [refined-github/refined-github#7029]
### Description

The idea behind [`close-as-unplanned`](https://github.com/refined-github/refined-github/blob/main/source/features/close-as-unplanned.tsx) is great, but I think something went wrong with the design in some cases: 

<img width="376" alt="image" src="https://github.com/refined-github/refined-github/assets/183673/1320d868-585e-4017-a168-a020e55ef078">

Does it potentially not cover the `with comment` case?

### How to replicate the issue + URL

Screenshot is from: https://github.com/prisma/prisma/issues/21744

### Extension version

23.11.1

### Browser(s) used

Chrome, Version 118.0.5993.117 (Official Build) (64-bit), Windows

**Comment by Jolg42** [comment]
I can reproduce as well on Firefox, on macOS

Before entering text
<img width="802" alt="Screenshot 2023-11-02 at 14 26 18" src="https://github.com/refined-github/refined-github/assets/1328733/3ddecdfc-5878-4bc3-a169-dc512146cf45">

With text in the comment textarea, it shows the same as what Jan mentioned. I find it confusing to have the text twice.
<img width="793" alt="Screenshot 2023-11-02 at 14 26 27" src="https://github.com/refined-github/refined-github/assets/1328733/009fc979-e551-4023-bc9a-80e24de339c0">

Now removing the text goes back to the first state, but the icon is actually missing
<img width="792" alt="Screenshot 2023-11-02 at 14 26 37" src="https://github.com/refined-github/refined-github/assets/1328733/5b1f0d28-8a16-495e-a3c2-5f7a109e9335">

**Comment by fregante** [comment]
This has been fixed by @kidonng and will be released probably tomorrow
