### ISSUE TITLE
 Display Project Board Associations in Issues Tab

### ISSUE THREAD

**Issue by 3ddyBoi** [refined-github/refined-github#7039]
### Description

This feature could be implemented like the display behaviour of milestones within the issues tab for project boards.

How milestone is displayed on a issue in the overview tab:
![image](https://github.com/refined-github/refined-github/assets/70267476/c93f860f-eaf0-45b8-a3b0-285aeb6a9ce7)

### Example URLs

All cards connected to a issue would get a label of the project, just like milestone is done.
https://github.com/refined-github/refined-github/issues?q=is:issue+is:open+sort:updated-desc

**Comment by fregante** [comment]
As this page mentioned in the issue template, we don't extend anything related to projects:

https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22

Also: https://github.com/refined-github/refined-github/issues/6968#issuecomment-1739059321
