### ISSUE TITLE
Make organization SSO login more convenient

### ISSUE THREAD

**Issue by jonashaag** [refined-github/refined-github#7040]
### Description

I have to confirm my organization's SSO every day on this page:

<img width="372" alt="Screenshot 2023-11-07 at 12 17 33" src="https://github.com/refined-github/refined-github/assets/175722/6365aad9-0389-4137-8240-607ceb4f6bf1">

Would be nice to make this more convenient by:

1. Having the Return key trigger the green Continue button so you don't have to use the mouse.
2. Maybe having the button automatically clicked?

### Example URLs

https://github.com/orgs/MyOrg/sso

**Comment by Julian-Dumitrascu** [comment]
This reminds of the fact that I would like many things (in GitHub and other programs) to be easier to do. About [another button in GitHub](https://github.com/orgs/community/discussions/63468#discussioncomment-7487566).

**Comment by jonashaag** [comment]
> super niche

I disagree here. Lots of organizations will use login coupled to SSO.

The other two points against adding this feature that you made I agree with though!
