### ISSUE TITLE
`one-click-review-submission` - Bad order of "Abandon review"

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7043]
### Description

The order is a bit messed up since the last update. The 3 buttons should be on the right. "Abandon" and "pending" should be on the left.

<img width="661" alt="Screenshot 3" src="https://github.com/refined-github/refined-github/assets/1402241/806e9399-e5c7-43bb-9cea-d00560b8332a">

### How to replicate the issue + URL

1. https://github.com/refined-github/sandbox/pull/55/files
2. "Start review"
3. Refresh page for "Abandon review" button to appear

See notes in https://github.com/refined-github/refined-github/pull/7015, it's not very easy to fix this feature unfortunately. We should have left the old GHE code as a standalone function instead of merging the logic 🥲 

### Extension version

23.11.3

### Browser(s) used

Safari

**Comment by blimmer** [comment]
Could we consider a revert? Putting the "abandon" button where the "submit" button used to be is pretty disruptive.
