### ISSUE TITLE
Add status:pending|success|failure dropdown filter for pull request. 

### ISSUE THREAD

**Issue by Carreau** [refined-github/refined-github#7046]
### Description

In github search fields for PRs it is possible to filter by [CI/Commit status](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-commit-status). 

I never remember the syntax, if it's `status:` or `ci:`, or `action:`, and wether the values are  `pass`, `passing`, `ok`. I'd love a dropdown like this:

<img width="327" alt="Screenshot 2023-11-08 at 11 16 55" src="https://github.com/refined-github/refined-github/assets/335567/f7ec97c0-58ca-464a-8d4d-aa94ae1fe51e">

### Example URLs

I guess it should appear on any pages where PRs can be filtered.

https://github.com/napari/napari/pulls or any ORG/REPO/pull
https://github.com/pulls (that list all your own PRs), that would make it easy to find all my PRs that need a a fix.

**Comment by FloEdelmann** [comment]
This feature already exists: https://github.com/refined-github/refined-github/blob/main/source/features/pr-filters.tsx

**Comment by Carreau** [comment]
Hum, Thankd,  that is weird. Any idea why id does not show up ? I do have the last version, and I don't see it being disabled in the options.

**Comment by Carreau** [comment]
Hum, it seem to have been an issue with my token, I regenerated it, and it works now. Sorry for the noise. Maybe it should be appended even when token is invalid/not working with a message on hover "Please check your token" ?

**Comment by fregante** [comment]
- Tracked in https://github.com/refined-github/refined-github/issues/5168
