### ISSUE TITLE
Enhancing Efficiency in Pull Request Review Process: Addressing Comment Visibility and Tracking Changes

### ISSUE THREAD

**Issue by stephenjason89** [refined-github/refined-github#7048]
### Description
I've encountered a significant challenge in the pull request (PR) review process that I wanted to share, which is also echoed in a discussion thread I've linked for further context.

When updates are made to a PR, particularly after addressing comments, the current system doesn't facilitate an easy way to resolve these comments. Ideally, the comment should update to show the recent changes, allowing for an immediate and efficient review right within the thread.

My experience mirrors that of many users, @sparmboy @Acorath @hazz0003 @dcumings @saleazer @flobacher @Kurt-von-Laven @jababda @paulius-valiunas @clemwo @robertodraGit @ben-polinsky @klinamen @carlospnav and many more, who expressed frustration with the lack of visibility into what exactly has been changed after a comment is addressed. When an author replies with something like "done" and pushes a new commit, as a reviewer, I'm left in the dark. The "view changes" link is not helpful for large PRs as it lists all the files, not just the one I commented on. This makes it a tedious task to locate the specific file and then the exact change.

Furthermore, when I'm trying to review the list of files that I've already looked at, there's no indication of which ones had comments that need a second look. This means I have to unmark each file as "viewed" to check for unresolved comments, which is incredibly inefficient.

It feels like the system isn't as intuitive as it could be. What I'm looking for is a way for the conversation history to stay visible within the file for all commits, so I can easily confirm that the author has made the necessary corrections they claim to have made. This would streamline the review process significantly and reduce the back-and-forth that currently plagues our workflow.
### Discussion thread
https://github.com/orgs/community/discussions/9956

**Comment by fregante** [comment]
This repo is not managed by GitHub. This is a browser extension for small enhancements. We can't rebuild the whole UI.
