### ISSUE TITLE
Filter out PR's in draft and with changes requested by default

### ISSUE THREAD

**Issue by gamestales** [refined-github/refined-github#7049]
### Description

Add draft:false to default PR filter
Add filter for changes requested PR's

### Example URLs

https://github.com/vcmi/vcmi/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+draft%3Afalse+

**Comment by fregante** [comment]
We can't just hide open PRs, sorry.

What I do though is have a browser bookmark that points me to a few that I use frequently. You might like this:

- https://github.com/pulls?q=is%3Apr+is%3Aopen+author%3A%40me+archived%3Afalse+sort%3Aupdated-desc++draft%3Afalse+review%3Achanges-requested+
