### ISSUE TITLE
Add "Difference" mode to image comparison widget

### ISSUE THREAD

**Issue by torokati44** [refined-github/refined-github#7050]
### Description

When a commit changes an image, GitHub shows a little widget to compare the old and the new images, with 3 different viewing modes: "2-up", "Swipe", and "Onion Skin".
I think that in many cases, a fourth one, "Difference", would be really useful. Example linked below.
It's sometimes just easier to tell this way what the nature of the visual changes are.

### Example URLs

https://github.com/ruffle-rs/ruffle/pull/11062/files#diff-8b768a758ee793bcacb0f927c4577c32d253b8b12170d79695804d8d4bb09133

I think it would be useful to be able to see the difference right there, like this:
![image](https://github.com/refined-github/refined-github/assets/288816/dca91adc-d5e3-4c94-9ebf-f8fc4e7557b5)

**Comment by fregante** [comment]
It looks like that iframe is served from a separate domain, which we don't have access to:

<img width="502" alt="Screenshot 1" src="https://github.com/refined-github/refined-github/assets/1402241/ac8df23d-8f5c-4162-988a-77538f18e012">

Extension permissions can't be changed without causing the extension to be disabled for all users, so it's not something we can do either.

**Comment by fregante** [comment]
Related issue:

- https://github.com/refined-github/refined-github/issues/6507

**Comment by torokati44** [comment]
Owh, that's too bad... :/
Thanks for the quick response though!

**Comment by torokati44** [comment]
(Although, _theoretically_, the extension could replace the entire `iframe`, reimplementing its functionality, right...?)

**Comment by fregante** [comment]
> reimplementing its functionality

_Refinements_, not war with GitHub 😅

**Comment by torokati44** [comment]
Ah, alright! 😅
