### ISSUE TITLE
`expand-all-hidden-comments` feature does not expand Gist `Load earlier comments...`

### ISSUE THREAD

**Issue by andry81** [refined-github/refined-github#7052]
### Description

Add the same feature as for the Issues.

### Example URLs

https://gist.github.com/probonopd/9feb7c20257af5dd915e3a9f2d1f2277

A very big conversation.

**Comment by fregante** [comment]
The logic in `expand-all-hidden-comments` is very strictly related to regular issues, I'm not sure it's worth enabling it on gists.

I'm open to a minimal PR that adds one more `init` specific to gists, without altering the existing one, but I will close this issue in the meanwhile.
