### ISSUE TITLE
Discussions: Modify default "Add your answer here..." input placeholder to make people use threads

### ISSUE THREAD

**Issue by janpio** [refined-github/refined-github#7064]
### Description

It is a common problem of GitHub discussions that users reply as a top level new response, instead of replying _in the thread_ that they are responsing to. In small 1:1 discussions that is not a big problem, but as soon as multiple users are involved this gets messy.

An example: https://github.com/prisma/prisma/discussions/21961#discussioncomment-7576315

Similar how Refined Github modifies the normal comment placeholder for issues, it would be nice if we could modify the default `Add your answer here...` of discussions to for example:

```
Add your answer here...
(Or in the thread if you are responding to a previous comment)
```

(I would expect Refined GitHub users generally to be aware of this, but maybe we still reach some that are not and change their behavior because of this nudge.)

### Example URLs

https://github.com/prisma/prisma/discussions/21961#discussioncomment-7576315

**Comment by fregante** [comment]
Sad how people don't know how to use threads. That user specifically however seems to be online much, so a change in RGH likely wouldn't affect those like them, as you suggested 

> I would expect Refined GitHub users generally to be aware of this

**Comment by janpio** [comment]
I think many really don't _see_ the "Reply" field under the comments and just by default go to the bottom of the page to type their words. I hope that will cover some RGH users.

**Comment by fregante** [comment]
PR welcome to extend `netiquette`

**Comment by fregante** [comment]
Unfortunately I don’t think this would actually make a difference. Also most newbies do not use Refined GitHub so it wouldn't affect them anyway.
