### ISSUE TITLE
Features broken on "New branches and commit pages"

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7067]
Tracking issue for this feature preview. Please open new issues and mention this one.

- https://github.com/refined-github/refined-github/issues/7045
- https://github.com/refined-github/refined-github/issues/7003
- https://github.com/refined-github/refined-github/issues/7068

### Related

- #7011 

### Context

<img width="500" alt="Screenshot 3" src="https://github.com/refined-github/refined-github/assets/1402241/2d353fae-eea4-4591-85e2-a9a84dcf26bd">

**Comment by FloEdelmann** [comment]
FYI: This is now generally available: https://github.blog/changelog/2023-12-06-updates-to-repository-pages/
