### ISSUE TITLE
`quick-mention`: causes first avatar to disappear when not logged in

### ISSUE THREAD

**Issue by vitoyucepi** [refined-github/refined-github#7070]
### Description

When not logged in to a GitHub account, using the `quick-mention` feature causes the avatar for the author of the pull request to disappear.
![Screenshot of the issue from #7069](https://github.com/refined-github/refined-github/assets/35035879/9bf067fb-4525-41be-a389-90ad9bcae237)

### How to replicate the issue + URL

1. Open an incognito/private browser window.
1. Navigate to any pull request on GitHub in the incognito/private window, for example #7069.
1. Observe that the avatar for the author of the pull request is missing.

### Extension version

23.11.15

### Browser(s) used

Chromium 119.0.6045.123

**Comment by fregante** [comment]
What do you mean by "using `quick-mention`? The repro steps do not mention `quick-mention`

**Comment by vitoyucepi** [comment]
Here's a refined reproduction script.

1. Start chrome/chromium with a clean profile.
   `chromium --user-data-dir=/tmp/test`
1. Open the [Chrome Web Store](https://chromewebstore.google.com/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf).
1. Press the *Add to Chrome* button.
1. Press the *Add Extension* button in the alert window.
1. Refined GitHub extension will be installed with default settings.
1. You will be redirected to a [Welcome page](https://github.com/refined-github/refined-github/issues/3543).
1. Go to a PR page, for example #7069.
1. Notice that the author avatar has disappeared.

How to identify the feature:
1. Open the Redefined GitHub Settings `chrome://extensions/?options=hlepfoohegkhhmjieoechaddaejaokhf` in the first tab.
1. Press the *Identify feature* button.
1. Press *Start process to identify feature...*.
1. Open a PR page, for example #7069, in the second tab.
1. Answer the questions.
   If you see the author's avatar, press the *No* button.
   If you don't see the avatar, press the *Yes* button.
1. After the last question you'll see
   > The change or question is caused by [quick-mention](https://github.com/refined-github/refined-github/blob/main/source/features/quick-mention.tsx).

**Comment by fregante** [comment]
Thanks Vito! I was actually looking in Safari and forgot that this feature was touched in the last version (#7054)

**Comment by a0m0rajab** [comment]
Test TExt
