### ISSUE TITLE
`quick-review`: It doesn't open the Review form

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7077]
### Description

I'm not sure if it's possible anymore, but maybe we just need to update the selector:

https://github.com/refined-github/refined-github/blob/e1c95bcd870e55c10d84bba90328cfa57147d31e/source/features/quick-review.tsx#L14

I think GitHub has a native link that points to this form, so we can find the new selector in it.

### How to replicate the issue + URL

1. On an open PR
	- https://github.com/refined-github/sandbox/pull/4
3. Click "Review now"
4. It should open the Review overlay

### Extension version

23.11.3

### Browser(s) used

Safari

**Comment by prplecake** [comment]
Seeing this in Firefox, too.

**Comment by fregante** [comment]
<kbd>v</kbd> is also broken on https://github.com/refined-github/refined-github/pull/7119/files

**Comment by fregante** [comment]
The fact that this is broken is a "big deal", because essentially now the button just duplicates the "Files" tab link 🥹 

If there's no native way to address this, we should add an `init` to detect `#review-changes-modal` and open the dropdown if it's not open.
