### ISSUE TITLE
Switching away from Issue comment in progress locks up tab in Arc browser

### ISSUE THREAD

**Issue by plasticrake** [refined-github/refined-github#7079]
### Description

When "unfinished-comments" is enabled, and I begin writing a comment reply in a github issue, switch to another tab, switch back. The tab with the comment is unresponsive and must be killed/refreshed.

I'm using Arc 1.17.2 which is based on Chromium 119. Arc has special tab handling and I'm guessing that is the issue. I did not see anything in the console.

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/issues/7078

### Extension version

23.11.15.1433

### Browser(s) used

Arc 1.17.2

**Comment by plasticrake** [comment]
Actually I'm seeing this happen even with `unfinished-comments` disabled. I've had to disable refined-github completely for now. I'm not sure which of the features may be causing this. I can troubleshoot more if someone can point me to the likely features that could be causing this.

**Comment by hoangmirs** [comment]
I also faced this when editing the PR's description, when clicking to other windows/tabs and coming back, the GitHub tab will not responding and need to refresh. The added content is also lost

**Comment by fregante** [comment]
Everyone here using Arc? If not, please specify your browser

**Comment by 134130** [comment]
@plasticrake Can you add a repro video?

I think the Arc browser's unique behavior of showing inner pages is related.

**Comment by plasticrake** [comment]
I renabled github-refined and I'm unable to reproduce the issue again. I'm still on the same version of the plugin and Arc. I'll leave it enabled and see if the issue comes back.

**Comment by wns3645** [comment]
> I renabled github-refined and I'm unable to reproduce the issue again. I'm still on the same version of the plugin and Arc. I'll leave it enabled and see if the issue comes back.

Same here. I had the same issue until yesterday; it disappeared for now. 🤷‍♂️

**Comment by fregante** [comment]
Closing as it seems that it was a temporary Arc issue rather than a Refined GitHub one
