### ISSUE TITLE
Add an option to create a copy of an existing issue

### ISSUE THREAD

**Issue by cdrini** [refined-github/refined-github#7080]
### Description

Often times I have an issue that I need to use as a temporary template ; I need to create the same issue for every quarter, or maybe for every team member, etc.

An option to take an existing issue and make a copy of it, would speed this up quite a bit! Then I would just make the copy, change anything I need to change, and hit save.

### Example URLs

https://github.com/internetarchive/openlibrary/issues/8544

**Comment by fregante** [comment]
I think this is too niche. If you need this often, either create a URL instead of an clonable issue, or use a bookmarklet.

**Comment by cdrini** [comment]
Here's 150 people who want it on GH: https://github.com/orgs/community/discussions/8485

For reference this is a very common task for project/issue management; here are some of the apps that support it:

- [Trello](https://support.atlassian.com/trello/docs/copying-cards-lists-or-boards/)
- [JIRA](https://support.atlassian.com/jira-software-cloud/docs/clone-an-issue/)
- [Asana](https://help.asana.com/hc/en-us/articles/14005479486235-Task-actions)
- [ClickUp](https://help.clickup.com/hc/en-us/articles/6309819303703-Duplicate-a-task)
