### ISSUE TITLE
Feature: wrap selection with backticks in editor

### ISSUE THREAD

**Issue by grafst** [refined-github/refined-github#7084]
### Description

Often I write something and afterwards want to format it as `code`.
It would be cool if backticks would behave the same as single and double quotes:
I select the text and hit the backtick key (and maybe space key) and it wraps the selected text into backticks.
![2023-11-22_08-52-20 (1)](https://github.com/refined-github/refined-github/assets/8471055/ed8064dd-739e-4632-95c4-f492d6ab437b)

### Example URLs

https://github.com/refined-github/refined-github/issues/new?assignees=&labels=bug&projects=&template=1_bug_report.yml

(in every markdown input)

**Comment by fregante** [comment]
This already exists. Are you using Refined GitHub?

`one-key-formatting`

![](https://github-production-user-asset-6210df.s3.amazonaws.com/83146190/261155564-e7aabd0e-b14b-4fe6-b379-62e7419c43f8.gif)

**Comment by grafst** [comment]
for me it doesn't work even tough the feature is enabled. 
<img width="585" alt="2023-11-22_18-58-28" src="https://github.com/refined-github/refined-github/assets/8471055/ed41d51b-becc-4ef6-bae8-adebf8d24a37">


But probably a client problem on my side.
sorry for the unnecessary feature request.
