### ISSUE TITLE
`conversation-activity-filter`: undefined is not an object (evaluating 'container.classList')

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7086]
### Description

The feature is broken 😰 

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/issues/6000

### Extension version

23.11.3

### Browser(s) used

Safari

**Comment by kidonng** [comment]
Apparently only broken on some pages, since it works here.

**Comment by fregante** [comment]
My guess is that the "hide as default" on that page causes a race condition:

https://github.com/refined-github/refined-github/blob/4d78a9f164479fddd82dc632f6af2bbaf3c416de/source/features/conversation-activity-filter.tsx#L224-L226

If so, this might just be fixed via `if in that array, await DOM ready`
