### ISSUE TITLE
`close-out-of-view-modals` - Link a branch for an issue requires two attempts

### ISSUE THREAD

**Issue by DFelten** [refined-github/refined-github#7093]
### Description

As soon as RefinedGitHub is activated, linking a branch or a pull request for an issue does not work on the first click. The list of branches should actually appear, but the dialog closes again. Only when I select `Development` again the corresponding branch can be selected.

When disabling Refined it's working directly. After tapping on a repository the branch list appears without closing the dialog.

### How to replicate the issue + URL

1. Click on `Development` or the icon on the right sidebar of an issue
2. Select repository
3. Dialog closes automatically
4. Tab again on `Development`

<details>
<summary>Images</summary>

Tap on development

![CleanShot 2023-11-22 at 15 40 15@2x](https://github.com/refined-github/refined-github/assets/1169185/3e9f1658-e5b0-47f1-b4c0-23f0a016d7c3)

Select repository

![CleanShot 2023-11-22 at 15 40 23@2x](https://github.com/refined-github/refined-github/assets/1169185/9317aaab-6ad1-4266-b0d0-f828629dc9f9)

Dialog closes

![CleanShot 2023-11-22 at 15 40 15@2x](https://github.com/refined-github/refined-github/assets/1169185/3e9f1658-e5b0-47f1-b4c0-23f0a016d7c3)

New tap on development the branch selection appears

![CleanShot 2023-11-22 at 15 43 45@2x](https://github.com/refined-github/refined-github/assets/1169185/76fdebb5-f7e5-41a3-b8e6-91e28300df7b)

</details>

### Extension version

23.11.3

### Browser(s) used

Safari 17.1

**Comment by fregante** [comment]
Thanks for the report! I think this is due to `clean-conversation-sidebar`

**Comment by DFelten** [comment]
> Thanks for the report! I think this is due to [`clean-conversation-sidebar`](https://github.com/refined-github/refined-github/blob/main/source/features/clean-conversation-sidebar.tsx)

The issue is still there when I have deactivated `clean-conversation-sidebar` in the settings of the extension.

**Comment by fregante** [comment]
Can you find the "Find feature" button to figure out which feature is causing this?

**Comment by fregante** [comment]
It's `close-out-of-view-modals`
