### ISSUE TITLE
`sync-pr-commit-title` - "Cancel" requires two clicks

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7096]
### Description

I don’t think this is caused by us, but probably there's an event listener that cancels propagation so our `delegate()` never receives the event:

https://github.com/refined-github/refined-github/assets/1402241/ff3c3394-5f3b-4c63-b33b-d58347d9d412

It seems to be related with the focus of the field, because if I blur it first, it works with one click. This is also true when blurring via `tab`

https://github.com/refined-github/refined-github/assets/1402241/823d11a3-626e-4810-b0a9-a269eb4a624f

### How to replicate the issue + URL

https://github.com/refined-github/sandbox/pull/12

### Extension version

23.11.3, 23.11.15

### Browser(s) used

Chrome, Safari

**Comment by fregante** [comment]
I tried `capture: true` here but that was not enough.

https://github.com/refined-github/refined-github/blob/927bca4ecfe486183df1c0d8a07cb336dcdf14b2/source/features/sync-pr-commit-title.tsx#L92-L93

**Comment by fregante** [comment]
Closing in favor of this other issue since the feature needs to be rewritten for the new view

- https://github.com/refined-github/refined-github/issues/8123

**Comment by SunsetTechuila** [comment]
> The bug probably/hopefully no longer applies there.

<img width="300" height="300" alt="Image" src="https://github.com/user-attachments/assets/dc43547d-5233-4ee4-a611-52b960d26ce5" />

**Comment by SunsetTechuila** [comment]
1. Mousedown is fired
2. Input field loses focus
3. Input change event is fired
4. `updateUI` is called by `onCommitTitleUpdate`
5. Initial node returned by `getUI` is re-appended
6. Mouseup event is fired on that re-appended node

https://github.com/refined-github/refined-github/blob/d63e2d97fc4d85f986a120fb49cd8e09f6785b93/source/features/sync-pr-commit-title.tsx

**Comment by SunsetTechuila** [comment]
https://github.com/w3c/pointerevents/issues/576
