### ISSUE TITLE
`more-dropdown-links`: dropdown opens to wrong direction

### ISSUE THREAD

**Issue by FloEdelmann** [refined-github/refined-github#7106]
### Description

When clicking the repo navigation dropdown, it opens to the top instead of to the bottom, making most links to be inaccessible:

![grafik](https://github.com/refined-github/refined-github/assets/202916/83380500-9ca9-4e81-8c90-aebcd3964723)

Note that:

1. The look and feel of this button was recently changed by GitHub.
2. The bug also appears with Refined GitHub disabled (on smaller screens), but
3. `more-dropdown-links` adds more links to the repo navigation dropdown, causing it to always be shown (also on large screens), making the bug much more obvious.

### How to replicate the issue + URL

1. Go to https://github.com/refined-github/refined-github
2. Click on the repo navigation overflow button → it opens to the top instead of to the bottom

Extra steps:

4. Disable Refined GitHub
5. Reload → the button is not shown anymore
6. Resize the screen to make the button re-appear
7. Click on the repo navigation overflow button → it opens to the top instead of to the bottom 

### Extension version

23.11.23

### Browser(s) used

Firefox 120

**Comment by fregante** [comment]
This is indeed a GitHub bug.

**Comment by fregante** [comment]
I'm gonna keep this open for discovery for now.

**Comment by fregante** [comment]
I think it has been fixed

<img width="296" alt="Screenshot" src="https://github.com/user-attachments/assets/cd60bd8e-28ce-4532-a226-c836b891400b">
