### ISSUE TITLE
Remove editor header in issues on archived repositories

### ISSUE THREAD

**Issue by tyrann0us** [refined-github/refined-github#7108]
### Description

On issues in archived repositories, GitHub displays the editor header ("Write" and "Preview"), which doesn't make sense.
<img width="983" alt="Bildschirmfoto 2023-11-24 um 08 46 12" src="https://github.com/refined-github/refined-github/assets/8144115/2817a3ac-1b7b-428b-bccf-f3f2d5ed9f6b">

What Refined GitHub does is remove the avatar in front of it. However, it would make more sense to remove the header completely.

### Example URLs

https://github.com/liip/bund_ds/issues/132#event-10996157695

**Comment by fregante** [comment]
PR welcome. This can be a 3-line CSS-only feature: `features/clean-archived-issue.css` I think

**Comment by a0m0rajab** [comment]
Hi @fregante I would like to work on this, but did not find the mentioned file, 
could it be a feature with the same logic as this one: https://github.com/refined-github/refined-github/blob/2fcbc2b28b6ca8c241c0411887e53a61b9e33e1e/source/features/archive-forks-link.tsx#L9 


To get this done we could remove the div with the next classes: `comment-form-head tabnav`

**Comment by a0m0rajab** [comment]
This is the first time for me to contribute here, how would the extension detect the CSS in the file and understand if the issue is archived?
