### ISSUE TITLE
Open all resolved threads

### ISSUE THREAD

**Issue by vanlooverenkoen** [refined-github/refined-github#7110]
### Description

I am working on a pull request for quite some time. There are a lot of discussions about the api & implementation. 

it would be nice to have 1 button to open all `resolved` discussions/comments with a single click. So it is easier to search for text in the page. Right now you have to manually open every `resolved` thread

![image](https://github.com/refined-github/refined-github/assets/21172855/d886ae83-696f-4355-ac6b-560c8c204336)

### Example URLs

https://github.com/flutter/plugins/pull/6284

**Comment by fregante** [comment]
We `toggle-all-with-alt-click` (or something like that)
