### ISSUE TITLE
`file-age-color` time range is extremely short

### ISSUE THREAD

**Issue by EcksDy** [refined-github/refined-github#7115]
### Description

I've just started using refined github and loving it so far! 🎉 

Issue:
I've expected the time range to be more gradual, as seen in [this comment](https://github.com/refined-github/refined-github/pull/6447#pullrequestreview-1370909117). 
But for some reason this is what I get:
![image](https://github.com/refined-github/refined-github/assets/994443/149e1286-8a05-40e3-9499-a2d7c13c53b3)

Info:
- My token is set
- No other github related extensions are active 
- Cleared cache
- I have a custom css, but it behaves the same without it:
```css
:root {
	--rgh-heat-color: #42dbab !important;
}
```
- No errors in console

The HTML for the `3 month ago` entry seems to be fine:
```html
<relative-time class="RelativeTime-sc-lqbqy3-0 rgh-seen-11477503587" datetime="2023-08-03T17:51:50.000+02:00" tense="past" title="Aug 3, 2023, 6:51 PM GMT+3" data-rgh-heat="10">
<% shadow root %>
3 months ago
</relative-time>
```
But it gets the maximum `data-rgh-heat`(10).
19 hours / 2 days ago get `data-rgh-heat=1`, last week gets `data-rgh-heat=3`.

### How to replicate the issue + URL

https://github.com/exelban/stats

### Extension version

23.11.23

### Browser(s) used

Firefox Developer Edition 120.0b9 (64-bit) on macos

**Comment by fregante** [comment]
Yes the feature is meant to highlight recently-changed files, not add a linear gradient between "1 second ago" and "40 years ago"

**Comment by fregante** [comment]
Glad you like Refined GitHub otherwise ☺️

**Comment by fregante** [comment]
> I've expected the time range to be more gradual, as seen in this comment.

Note that in that screenshot it's just a demo for the color, it doesn't follow the time

**Comment by EcksDy** [comment]
Ah... I see, is there any way to configure/override the current time range?
A range up to 1 year would make sense to me.
