### ISSUE TITLE
Button to go to latest run on "runs" page of a PR

### ISSUE THREAD

**Issue by IanButterworth** [refined-github/refined-github#7122]
### Description

Currently if you're on the page for viewing a CI run for a commit in a PR, and the PR gets a new commit, you have to go back to the PR page and then scroll down and click the CI link again.

It'd be nice to have a "go to latest" button on the "runs" page that appears if there's a newer commit.

### Example URLs

https://github.com/refined-github/refined-github/actions/runs/6967292040/job/18958925346

**Comment by fregante** [comment]
> ### Example URLs
> [refined-github/refined-github/actions/runs/123/job/123](https://github.com/refined-github/refined-github/actions/runs/123/job/123)

REAL URL please

**Comment by fregante** [comment]
> It'd be nice to have a "go to latest" button on the "runs" page that appears if there's a newer commit.

I agree. However it requires an API call so I'm not sure it's a common enough action to justify an uncached API call on each and every run page load.

**Comment by IanButterworth** [comment]
> REAL URL please

Updated OP.

Might there be a way to have a static url that goes to the latest run then and just show the button always?

**Comment by fregante** [comment]
Best it could do is load the list of runs for that specific workflow, and you'd have to click the first one

**Comment by fregante** [comment]
> list of runs for that specific workflow and branch

There's no search filter to see runs on an external branch (common for PRs) so this is impossible too.
