### ISSUE TITLE
Delete repo button does not appear

### ISSUE THREAD

**Issue by aidenscott2016** [refined-github/refined-github#7133]
I have installed this extension so that I can mass delete repositories. According to this [gif](https://user-images.githubusercontent.com/1402241/99716945-54a80a00-2a6e-11eb-9107-f3517a6ab1bc.gif) I should expect to see a delete button next to the watch button, but it is not there. To test that the repository I was trying to delete didn't somehow have issues, stars, or prs that I didn't know about, I  created a new repository. The button does not appear for that repository. I have generated a GitHub token, including the `delete_repo` scope, I see all green checks, and the `quick-repo-deletion source` setting is enabled. 

 Same issue in firefox and chrome

Am I missing something, or is this a bug?

**Comment by aidenscott2016** [comment]
I see from the source that this only works on forks

**Comment by aidenscott2016** [comment]
I think this would be a useful feature. If I made a PR would there be an appetite to merge it?

**Comment by fregante** [comment]
Unfortunately not, see:

- https://github.com/refined-github/refined-github/issues/3832
