### ISSUE TITLE
Reduce amount of clicks for "rerun failed jobs"

### ISSUE THREAD

**Issue by karfau** [refined-github/refined-github#7135]
### Description

I think GitHub recently changed the order inside the dropdown for rerunning jobs in case they failed. In the mobile app it's the first option listed, but in the browser the first option is now "rerun all jobs". Small change big difference in cost.

![image](https://github.com/refined-github/refined-github/assets/135657/837a8fa0-2cc7-4df1-ae97-4f2840497e1c)

I was thinking if it would be possible to avoid the dropdown (the same way that approvals only require one click instead of two) and directly offer one button for each option, ideally the one for rerunning failed builds should be the first one.

It would obviously only be visible if the viewer has the rights to rerun the workflow, not sure if that makes it harder to implement.

### Example URLs

https://github.com/refined-github/refined-github/actions/runs/7071099962?pr=7100

**Comment by fregante** [comment]
Not worth it here. Neither actions is more common than the other
