### ISSUE TITLE
`show-names` showing inverted text

### ISSUE THREAD

**Issue by jman-schief** [refined-github/refined-github#7136]
### Description

When the feature `show-names` is enabled it happened to me that some text looks horizontally inverted. I can reproduce consistently when visiting a specific Github repository (see next field for a repro). I could isolate the `show-names` as culprit thanks to the "Identify feature" of Refined Github.

![screenshot-20231203-231459](https://github.com/refined-github/refined-github/assets/82455740/66bc8de3-b01c-481b-b9d8-7afb228e9d9c)

### How to replicate the issue + URL

Please visit the following issue. I'm going to replace `github.com` with `hubgit.com` in the URL to avoid causing a mention in the other git repository.

https://togithub.com/ProfKelly/EASy68K/issues/2

### Extension version

23.12.1

### Browser(s) used

Firefox 121.0b6

**Comment by fregante** [comment]
Thank you for trying in a new profile ☺️

**Comment by fregante** [comment]
The repro link doesn't show the error. Have you seen it elsewhere?

Closing until we have a new repro
