### ISSUE TITLE
`small-user-avatars` showing wrong avatars on commit history/details

### ISSUE THREAD

**Issue by dgw** [refined-github/refined-github#7137]
### Description

GitHub appears to have added the `user-mention` class to `commit-author` links in places like the commit detail page and commit list. Refined GitHub now adds an incorrect, redundant small avatar if that feature is turned on:

![image](https://github.com/refined-github/refined-github/assets/164140/3b470257-afb2-4cfe-96d9-8e472f71cb75)

In the above example, the avatar for "gw" is shown instead of "dgw". RGH expects a `user-mention` to start with `@` and trims the first character, but the `commit-author` link type does not include `@`.

https://github.com/refined-github/refined-github/blob/a0381ca315606a53def92932ed7927dca84d8963/source/features/small-user-avatars.tsx#L25

```html
<a class="commit-author user-mention" title="View all commits by dgw" data-hovercard-type="user"
  data-hovercard-url="/users/dgw/hovercard" data-octo-click="hovercard-link-click"
  data-octo-dimensions="link_type:self" href="/sopel-irc/sopel/commits?author=dgw">dgw</a>
```

### How to replicate the issue + URL

I noticed it at https://github.com/sopel-irc/sopel/commit/120477fe28f470f9308163203c43688ff9121e12 but this happens anywhere a commit is shown (including `/:user/:repo/commits/:refname` and at the top of `/:user/:repo`)

### Extension version

23.12.1

### Browser(s) used

Chrome 119

**Comment by XDelta** [comment]
Can confirm I am seeing this as well.
XDelta is being adjusted to Delta and showing an additonal and incorrect user icon
![image](https://github.com/refined-github/refined-github/assets/7883807/8a896a3d-499f-4bac-b474-6ab2b2e064e9)

**Comment by fregante** [comment]
It looks like the added the `user-mention` class to an element that isn't a **mention** 😩 

I'll hot fix the feature to disable it.

**Comment by dgw** [comment]
> It looks like the added the `user-mention` class to an element that isn't a **mention** 😩

Yeah, this change makes no sense to me. If RGH has the ability to treat `.user-mention` and `.user-mention.commit-author` differently, that could be a way around this. (Does [something like](https://developer.mozilla.org/en-US/docs/Web/CSS/:not) `.user-mention:not(.commit-author)` work with the selector-observer helper?)

**Comment by dgw** [comment]
Bootstrapped Node locally so I could test the change locally, and opened #7139 with the results. Hope it's helpful!
