### ISSUE TITLE
Improve checks for Personal Token in extension settings

### ISSUE THREAD

**Issue by macintacos** [refined-github/refined-github#7138]
### Description

I was about to use what seems to be the "quick review" feature to approve a PR, and I was getting an error saying that my personal token needed updating so that it could make the appropriate calls. This was fine, however, I noticed that in the settings it doesn't seem to call this out:

<img width="533" alt="CleanShot 2023-12-04 at 17 55 28@2x" src="https://github.com/refined-github/refined-github/assets/8128941/d8646880-3e6b-4860-a689-69ee0ef1e5e0">

Can this list be updated to check for whether or not the key provided can access that feature?

### Example URLs

Unfortunately I do not have a URL, as this was for a private repo.

**Comment by fregante** [comment]
We don't have that sort of granularity. Like for the native GitHub token interface, we don't list all the things that each scope allows, it's up to you to interpret that "leaving a review" isn't "read access" but "edit"
