### ISSUE TITLE
Dropdown for PR/commit files

### ISSUE THREAD

**Issue by LePips** [refined-github/refined-github#7141]
### Description

Unsure if this goes against `4. It doesn't require a lot of view/UI, code and effort to maintain.`.

The dropdown menu that Github when selecting lines within a file isn't implemented for PR/commit files, which is annoying. The dropdown menu doesn't necessarily need all of the options that the file dropdown has, but at least copying the line(s), copying the permalink, and navigating to the blame is possible. I'm sure creating an issue/discussion from the permalink is possible as well but I don't see much utility in that, but I'm not against it either.

| File | PR |
| ---- | ---- |
| <img width="294" alt="Screenshot 2023-12-05 at 1 33 02 PM" src="https://github.com/refined-github/refined-github/assets/20747774/d2b679ce-91c4-4d05-b803-48c17ed4d679"> | <img width="166" alt="Screenshot 2023-12-05 at 1 33 23 PM" src="https://github.com/refined-github/refined-github/assets/20747774/27c2688c-0fc3-4415-aebf-238ad497f13f"> |

### Example URLs

All PRs

**Comment by fregante** [comment]
Unfortunately the underlying views use two completely different components, so we can't reuse the native one. 

Even then, generating a true permalink here probably requires an API call and that makes it a bit complicated. 

If you're ok with a non-truly-permanent link you can already select the lines and press Y, I think that already copies the URL on every page (`copy-on-y`)
