### ISSUE TITLE
Open links in a new tab option (default?)

### ISSUE THREAD

**Issue by rubengmurray** [refined-github/refined-github#7143]
### Description

When there are links in github PR descriptions, clicking the link does not open in a new tab. 

This can be frustrating if you are being directed to supporting documentation, graphs, or whatever else. Especially if there are multiple links.

Of course, holding ctrl / cmd allows for a common workaround, but I think the option for it to be embedded behaviour would be useful.

### Example URLs

https://github.com/refined-github/refined-github/issues/6000

For example, the link to #5222 the above PR description should open in a new tab.

**Comment by fregante** [comment]
It's bad practice to open links in a new tab by default, so if you want that you'd have to use a dedicated extension or write a simple user script, we can't do it here.

**Comment by fregante** [comment]
However fyi we do exactly that in a very specific situation: when it can cause data loss:

- https://github.com/refined-github/refined-github/pull/7055

**Comment by rubengmurray** [comment]
> It's bad practice to open links in a new tab by default, so if you want that you'd have to use a dedicated extension or write a simple user script, we can't do it here.
> 
> * [ux.stackexchange.com/q/5397/35104](https://ux.stackexchange.com/q/5397/35104)
> * [stackoverflow.com/q/946248/288906](https://stackoverflow.com/q/946248/288906)
> 
> However fyi we do exactly that in a very specific situation: when it can cause data loss:
> 
> * [`prevent-comment-loss` - New feature #7055](https://github.com/refined-github/refined-github/pull/7055)

It is slightly ironic that I'm clicking these links with cmd + click in order to read them and then revert back to this PR. 

I would suggest it is very common behaviour for PR review given the links in a PR often (always?) give context to the PR itself, so the user will want to keep the PR open to read the supporting links, with the ultimate goal of coming back to review. 

_However_, I don't have an example of a website off the top of my head that is doing it by default (that I've noticed) to help support this argument. For now I'll leave this task closed and look at a user script.

Cheers
