### ISSUE TITLE
Sticky `Edit` in issue/PR title bar that stays visible and usable on scroll

### ISSUE THREAD

**Issue by janpio** [refined-github/refined-github#7149]
### Description

#7147 reminded me that there is another functionality that scrolls away on long issues: The `Edit` button for the issue title. 

Often I want to update the issue title based on information that I see in comment 175 in a long thread, but then I have to scroll to the top instead of just being able to hit `Edit` right where I am.

<img width="1047" alt="image" src="https://github.com/refined-github/refined-github/assets/183673/1c981d46-c588-4890-94fc-859139f6bf3f">
vs.
<img width="989" alt="image" src="https://github.com/refined-github/refined-github/assets/183673/18cbbc26-2b5d-4c58-8662-7f73a448db70">

(Possibly hitting the button needs to scroll up the whole page so the title input is actually visible, that would be a fair tradeoff)

### Example URLs

https://github.com/refined-github/refined-github/issues/5939

**Comment by fregante** [comment]
It would be ok for me to add a small pencil icon next to the title and have it scroll to the top, with the title edit field open

**Comment by janpio** [comment]
True, that would more fit the style of the title sticky row 👍

**Comment by fregante** [comment]
> and have it scroll to the top

Since this is required, I don’t think it would save much time:

1. `Cmd-up` (or `Home` key on some keyboards)
2. Click `Edit` button

This would only save a keypress, not worth it
