### ISSUE TITLE
“Create draft” button misalignment on mobile

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7153]
### Description

![IMG_3284](https://github.com/refined-github/refined-github/assets/1402241/cf9966df-a5e0-43f3-9eef-d6b7f2f44b48)

### How to replicate the issue + URL

On a compare page, will add URL later

### Extension version

23.11.3

### Browser(s) used

Safari

**Comment by a0m0rajab** [comment]
Can we use chrome extensions on mobile phones? 😮

**Comment by fregante** [comment]
On the Safari iPhone yes, Refined GitHub is available on the App Store. 

On Firefox Mobile also yes. 

On Chrome mobile no, but there on Kiwi Browser yes.

**Comment by a0m0rajab** [comment]
Thank you for the information!

**Comment by fregante** [comment]
Solution to this issue:

1. Add `sm-d-none` class to the two buttons
2. Add `d-none md-d-block` classes to the the existing widget, instead of removing it altogether

(classes might not be exact)
