### ISSUE TITLE
Always expand the PR merge details to show all checks

### ISSUE THREAD

**Issue by fishpen0** [refined-github/refined-github#7154]
### Description

I would like the "View Details" button on the merged PR to be automatically expanded instead of collapsed by default.  I would also like the pane to be stretched to show all items sans-scrollbar.

Default:
![Screenshot 2023-12-11 at 12 42 36 PM](https://github.com/refined-github/refined-github/assets/2652774/a1f66aaa-f84f-470f-aa33-1439281854dc)

What I would like: 
![Screenshot 2023-12-11 at 12 41 45 PM](https://github.com/refined-github/refined-github/assets/2652774/51b5580c-2e5a-40ac-aa9e-b0779022c0fc)

### Example URLs

https://github.com/refined-github/refined-github/pull/7131 works to show this, including the scrollbar in the checks pane

**Comment by fregante** [comment]
I thought GitHub already did this by default on closed PRs?

**Comment by a0m0rajab** [comment]
They do this in on the open PRs but not closed one, I do feel like hiding them when the PR is closed would be better since it will show less data/noise.

**Comment by fregante** [comment]
To be honest I don’t think I've ever opened that list, or not more than a couple of times. If the PR was reviewed, merged and CI is green, what is there to see on CI? Feels like a rare operation
