### ISSUE TITLE
Close checks list when clicking outside of modal

### ISSUE THREAD

**Issue by Katsute** [refined-github/refined-github#7157]
### Description

Clicking anywhere outside the modal should just close it, every other modal that GH uses does close when you click outside the modal.

1. **Click on the check:**

   ![image](https://github.com/refined-github/refined-github/assets/58778985/ba5c1d9c-c964-4cb8-844f-771aa8ef6f40)

2. **Click anywhere outside the modal:**

   _(modal does not close)_

   ![image](https://github.com/refined-github/refined-github/assets/58778985/5332bad9-f881-4bab-b807-74f2f1180de1)

### Example URLs

(any page that shows a commit check)

* https://github.com/refined-github/refined-github
* https://github.com/refined-github/refined-github/tree/main/source
* https://github.com/refined-github/refined-github/blob/main/source/manifest.json

<br>

* https://github.com/refined-github/refined-github/branches
* https://github.com/refined-github/refined-github/commits/main/

**Comment by a0m0rajab** [comment]
This could be done by adding a `click` event listener to:  `div.Dialog__Backdrop-sc-uaxjsn-0.gmJJZ` and check if the target is that specific element then click on the X button. 

I could not get the dialog in the first link provided for examples though.

**Comment by fregante** [comment]
That's too bad, GitHub has always dealt with modals pretty well, especially because they never had a darkened background so people don't even know it's a modal. We used to have a feature for that https://github.com/refined-github/refined-github/pull/735


For what it's worth, that modal can be closed via ESC

**Comment by Katsute** [comment]
Implemented on https://github.com/Katsute/refined-github/blob/9715f1caecd100c2b8c456b247a94d349e87c076/source/features/checks-modal.tsx using `class^=` and `class*=`

Should I open a PR for this feature?

**Comment by a0m0rajab** [comment]
@Katsute thanks for taking this, I think you could open a PR. If @fregante does not want it, he will just close it. Otherwise, your PR will get a code review 😄 . This might save you and him some time due to the time zone differences. 

Note: I am just an external programmer for the project.
