### ISSUE TITLE
sort failed actions to the top

### ISSUE THREAD

**Issue by jepler** [refined-github/refined-github#7158]
### Description

In CircuitPython we have a few hundred jobs within our main CI workflow.

when something fails, It would be nice on the PR page to have the failed jobs at the top, instead of whatever sorting github is doing. otherwise, it's searching through 300 of something, 6 at a time, looking for the failed icon...

a related idea would be a way to filter by job status such as failed, not started, etc.

### Example URLs

https://github.com/adafruit/circuitpython/pull/8723

**Comment by fregante** [comment]
Are you using Firefox? 

We already do this, but Firefox doesn't support it (until the next Firefox release)

**Comment by fregante** [comment]
- https://github.com/refined-github/refined-github/pull/5858

**Comment by jepler** [comment]
thanks, & sorry for the noise. yes I'm using firefox 120.0.1 on linux.

**Comment by jepler** [comment]
An additional note: this seems to work for me in FF 120.0.1 if I set a user preference: layout.css.has-selector.enabled to true in about:config. Based on 'caniuse' it looks like it will become enabled by default in ff 121. https://caniuse.com/?search=%3Ahas

once again, thanks!
