### ISSUE TITLE
`releases-tab` - Missing from overflow menu

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7163]
### Description

I think this is broken for multiple features that add to or alter that dropdown.

![date](https://github.com/refined-github/refined-github/assets/1402241/d398efb0-eb43-4d6d-bea6-d9b7e920d7f7)

### How to replicate the issue + URL

Here 

### Extension version

23.12.1

### Browser(s) used

Safari, Chrome

**Comment by der-eismann** [comment]
Not sure if related, but is this the reason that the `+ x releases` link is not shown? Should the releases page be a tab instead? Or is it a different issue? 

**Without extension enabled:**
![screenshot-20240125-111724](https://github.com/refined-github/refined-github/assets/10406217/08480912-4a8e-4931-a73d-7722088231f3)

**With extension enabled:**
![screenshot-20240125-111524](https://github.com/refined-github/refined-github/assets/10406217/ae7dd790-636f-43ca-8849-d99bb9e113f8)

**Comment by fregante** [comment]
> is this the reason that the `+ x releases`

It's a feature: https://github.com/refined-github/refined-github/pull/3918

And yes the reason is that `releases-tab` already adds a link to the releases and tags on every page
