### ISSUE TITLE
`ci-link` - Dropdown style is outdated

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7170]
### Description

No really a bug but it can become one soon.

GitHub changed the style, do we need to update the widget we use?

### `ci-link`

<img width="464" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/f94fcf7d-534c-4f50-993b-ac13dffe21fb">

### New native

<img width="906" alt="Screenshot 1" src="https://github.com/refined-github/refined-github/assets/1402241/24cfa32c-a1ee-4829-9b80-8c4723dc1f11">

### How to replicate the issue + URL

Here.

Seen in:

- https://github.com/refined-github/refined-github/issues/7157

### Extension version

23.12.1

### Browser(s) used

All

**Comment by fregante** [comment]
Here we go, I think this is a React component we won't be able to use 🎊 

<img width="591" alt="Screenshot 2" src="https://github.com/refined-github/refined-github/assets/1402241/ad91f701-fbe2-43c2-a904-c6c2a53a9f59">

**Comment by fregante** [comment]
Source here. I don't see any link to web components that we can use, so we can't.

<img width="540" alt="Screenshot 4" src="https://github.com/refined-github/refined-github/assets/1402241/eae0ed0f-82f3-41d9-a069-8b62f9eabf7b">

**Comment by a0m0rajab** [comment]
Out of curiosity and for the sake of learning, how did you get the source image?

**Comment by fregante** [comment]
GitHub ships source maps, so I just enabled them in the Chrome Dev Tools. I usually keep sourcemaps disabled because they cause more trouble than they're worth
