### ISSUE TITLE
`quick-comment-hiding` reloads the page instead of using ajax

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7171]
### Description

As described. This change used to happen via AJAX, not it reloads the page

### How to replicate the issue + URL

Here, the comment below

### Extension version

23.12.1

### Browser(s) used

Safari

**Comment by fregante** [comment]
_Hide me if you can_

**Comment by sweetliquid** [comment]
Can I take it?

**Comment by fregante** [comment]
Yes please!
