### ISSUE TITLE
`pr-notification-link` - link to latest changes

### ISSUE THREAD

**Issue by FloEdelmann** [refined-github/refined-github#7172]
### Description

1. We can append `#partial-timeline` to the link, to automatically scroll down to the latest events (which most likely triggered the notification in the first place). See also `open-issue-to-latest-comment`.
2. We can append `?rgh-changes` to the link, catch that in the page and and scroll to the "New changes since you last viewed" timeline event. See also https://github.com/refined-github/refined-github/commit/2b38874f813423cd129f387a3dc3c7225578e43e where a partly implementation was reverted.

![grafik](https://github.com/refined-github/refined-github/assets/202916/01e21945-7586-4345-adbb-be77ac29389e)

<details>
<summary>HTML of the "New changes since you last viewed" timeline event</summary>

```html
<div
  class="js-timeline-item js-timeline-progressive-focus-container rgh-seen-6970248962 rgh-conversation-activity-filtered">
  <div class="TimelineItem">
    <span class="TimelineItem-badge color-bg-accent-emphasis color-fg-on-emphasis">
      <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true"
        class="octicon octicon-plus">
        <path
          d="M7.75 2a.75.75 0 0 1 .75.75V7h4.25a.75.75 0 0 1 0 1.5H8.5v4.25a.75.75 0 0 1-1.5 0V8.5H2.75a.75.75 0 0 1 0-1.5H7V2.75A.75.75 0 0 1 7.75 2Z">
        </path>
      </svg>
    </span>
    <div class="TimelineItem-body d-flex flex-items-center">
      <strong class="flex-auto">New changes since you last viewed</strong>
      <a href="/stylelint/stylelint/pull/7252/files/94eac4ec4b8914055b9e9d732fd8a92b17a3afdf..HEAD"
        data-ga-click="Pull Requests, view changes button, location:revision marker" data-view-component="true"
        class="btn-sm btn"> View changes
      </a>
    </div>
  </div>
</div>
```

</details>

*(extracted from https://github.com/refined-github/refined-github/pull/7104#issuecomment-1858728416)*

### Example URLs

Any force-pushed PR that you get a notification for

**Comment by fregante** [comment]
> 1. We can append `#partial-timeline` to the link

We already do, basically:

https://github.com/refined-github/refined-github/blob/3d227d441af6bc19c8ae149a2409af256d9c19fe/source/features/pr-notification-link.tsx#L11
