### ISSUE TITLE
Modifying labels with addon enabled causes browser to hang and pop up warning about a script

### ISSUE THREAD

**Issue by dakrone** [refined-github/refined-github#7176]
### Description

With Firefox, when I go to edit the labels for our repository, the dialog hangs (I cannot type anything to select a label) and eventually Firefox complains that a script is slowing down the page:

<img width="318" alt="Screenshot 2023-12-20 at 8 41 15 AM" src="https://github.com/refined-github/refined-github/assets/19060/33548f8f-171f-48c6-87ce-371e84543070">

Then eventually:

<img width="775" alt="Screenshot 2023-12-20 at 8 41 19 AM" src="https://github.com/refined-github/refined-github/assets/19060/7f884bc8-da92-4911-a8fd-6ee9d95143c7">

When I disable refined-github I'm able to change labels without any problems.

### How to replicate the issue + URL

Our repository (https://github.com/elastic/elasticsearch) has 612 total labels. If you attempt to modify the labels on an issue (for example: https://github.com/elastic/elasticsearch/issues/100371 ) then you should see the bug. You don't have to select any labels, just opening the dialog is enough to cause the problem.

If you're unable to see the performance issue, or if you can't change the labels on an issue since you're not a contributor, then you can follow these steps:
1. Create a new repository
2. Create a new issue in that repo
3. Create 600+ labels for the repository
4. Attempt to modify the labels for the issue created in step 2

I've performed the above steps for a repo, manually creating 300 labels, and the performance problem starts to show, but I'm still able to select a label. I suspect it gets worse the larger the number of labels.

### Extension version

23.12.17

### Browser(s) used

Firefox 122.0b1

**Comment by fregante** [comment]
Can you show what code appears when you click "Debug script"?

**Comment by dakrone** [comment]
@fregante I've added you as a collaborator on https://github.com/dakrone/label-test, where I've manually created 385 labels so far (I got that far before Github started hitting me with errors about rate-limits). In case it's helpful for debugging.

**Comment by zeertzjq** [comment]
This issue doesn't happen if the `quick-comment-edit` feature is disabled.

**Comment by joostlek** [comment]
Even with `quick-comment-edit` disabled it can happen, but that's just incidental.

**Comment by zeertzjq** [comment]
Oh, I checked again, it still happens with `quick-comment-edit` disabled.

**Comment by joostlek** [comment]
I now found out that you have to type slowly for it to work. So I'm guessing there's another reason why this happens. Any way we can deliver debug info of some sorts?

**Comment by fregante** [comment]
That's what I'm trying to figure out. I disabled those 4 features an I still have trouble opening long PRs in Safari.

**Comment by joostlek** [comment]
With `quick-comment-edit` enabled:
<img width="1512" alt="image" src="https://github.com/refined-github/refined-github/assets/7083755/0532ef62-2ea1-4be8-8031-481e18a9be2c">

With `quick-comment-edit`, `locked-issue` and `wait-for-checks` disabled (these 2 are disabled via a hotfix on my normal firefox instance but were enabled in the dev env):
<img width="1512" alt="image" src="https://github.com/refined-github/refined-github/assets/7083755/71679240-ae79-48ca-aff1-c84a73cd8189">

The code does say:
```ts
	// TODO: Replace with :has selector
	observe(preSelector + '.js-comment.unminimized-comment .js-comment-update', addQuickEditButton, {signal});
```

Is there maybe a performance reason why it should use `:has`?

**Comment by JelteF** [comment]
quick-comment-edit definitely causes perf problems in firefox indeed. One very simple way for me to trigger the slowness is resizing the browser window a few times in a row. Once in a while the page will completely freeze and not redraw for multiple seconds.

**Comment by fregante** [comment]
To those using Firefox, can you try using an older version of Refined GitHub? I have a suspicion that the "slow" code is in the CSS, because I can't think of a reason why `removeChild` would not be instant. I'd consider it a browser bug that affects RG users :(

**Comment by joostlek** [comment]
Are there any docs on how to revert to such version?

**Comment by fregante** [comment]
You can download them from https://addons.mozilla.org/en-US/firefox/addon/refined-github-/versions/

**Comment by MikeMoolenaar** [comment]
> To those using Firefox, can you try using an older version of Refined GitHub? Like from November

`quick-comment-edit`  also caused performance issues for me, disabling it in the newest version fixed it for me.  

Just tried version 23.11.3 released November 3th (with `quick-comment-edit` enabled) and the performance issues are still there, but much less. At least it doesn't lock up the tab completely...

**Comment by joostlek** [comment]
Would it maybe be possible to create a workaround that does not render the whole list and only works when you entered x amount of characters? I am slowly getting a bit tired of fetching my phone every time I want to add labels to something.

And if there is anything else we can do to help debug is, please let us know :)

**Comment by fregante** [comment]
Please try again with version 24.4.9. I think that the previous 24.4.1 made the problem worse (because it restored some previously-disabled features)

**Comment by joostlek** [comment]
Oeh oeh oeh, it looks very very promising

**Comment by joostlek** [comment]
It doesn't like if I start typing while it's loading, then the whole labels popup freezes, but the rest of the tab seems to still work (except for refresh), but if I am patient it works.

(Any chance we can use some localstorage cache for labels?)

**Comment by fregante** [comment]
Closing in favor of https://github.com/refined-github/refined-github/issues/7331
