### ISSUE TITLE
`hide-user-forks`: breaks browsing org repos

### ISSUE THREAD

**Issue by sersorrel** [refined-github/refined-github#7177]
### Description

When you click on the "Repositories" tab for an org, or hit "View all repositories" at the bottom of the page, you get taken to a page like https://github.com/orgs/NixOS/repositories?type=source (`hide-user-forks` adds the `?type=source`). There's a "Clear filter" button, and clicking it removes the filter (e.g. takes you to https://github.com/orgs/NixOS/repositories), but the pagination buttons at the bottom will reapply the filter (e.g. linking to https://github.com/orgs/NixOS/repositories?page=2&type=source), which makes it very annoying to page through all repos owned by an org.

### How to replicate the issue + URL

1. Visit https://github.com/NixOS
2. Click "View all repositories"
3. Click "Clear filter"
4. Click "Next" (to go to page 2)
5. Observe that the filter is silently reapplied

### Extension version

23.12.17

### Browser(s) used

Chrome 120.0.6099.109

**Comment by fregante** [comment]
You're right we should exclude the navigation. I think we have similar logic in the "sort issues by update time" feature

**Comment by metaqer** [comment]
hi

**Comment by fregante** [comment]
They added a new view in beta, there's no "clear filter" and the navigation works as expected:

![Untitled](https://github.com/refined-github/refined-github/assets/1402241/e66522bf-5cd0-4b82-b32b-908b672489f5)
