### ISSUE TITLE
`rgh-feature-descriptions` don't update on page change

### ISSUE THREAD

**Issue by Katsute** [refined-github/refined-github#7178]
### Description

Feature description doesn't update on page change

![rgh](https://github.com/refined-github/refined-github/assets/58778985/ebf8e5bb-da6a-4bc8-95d8-4519ef76c783)

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/blob/main/source/features/rgh-feature-descriptions.tsx

Occurs when doing any of these:

* Click on any other feature
* Moving forwards and backwards through page history
* Clicking feature through sidebar 'Go to file' search

### Extension version

23.12.17

### Browser(s) used

Google Chrome & Firefox

**Comment by fregante** [comment]
Thank you for the report, see

- https://github.com/refined-github/refined-github/issues/6528

**Comment by Katsute** [comment]
oopsies, forgot to check closed issues
