### ISSUE TITLE
Clear input when selecting status check on branch protection rules

### ISSUE THREAD

**Issue by Katsute** [refined-github/refined-github#7181]
### Description

Just a minor annoyance, clicking a status check from the dropdown should clear it from the input, rather than autocompleting. Doesn't really make sense to keep it in the input.

![branch](https://github.com/refined-github/refined-github/assets/58778985/019a69e0-e4a7-4907-aff7-92b89aa130f8)

### Example URLs

`https://github.com/USER/REPO/settings/branch_protection_rules/*`

**Comment by fregante** [comment]
This is too hidden and rare an action to be part of Refined GitHub 🥹
