### ISSUE TITLE
[Feature requests] Add an keyboard shortcut to switch accounts

### ISSUE THREAD

**Issue by danztran** [refined-github/refined-github#7182]
### Description

Hi, since Github support multiple accounts, I think an keyboard shortcut to switch accounts will reduce much effort.
Current behavior:
1. Click on avatar in top right corner.
2. Click to expand `Switch account` item.
3. Choose and click on the account we want to switch.

Potential shortcut:
- `g`+`a`+`a`: Switch to next account found in list, most suitable for users that have only 2 accounts.
- `g`+`a`+`number`: Switch to account at index `number` found in account lists.

### Example URLs

On every github.com sites if user has signed in with multiple accounts.

**Comment by fregante** [comment]
I don’t think this warrants a shortcut given it's probably a relatively rare situation.

Also Refined GitHub does not support multiple users so careful when using the ["Approve now" button](https://github.com/refined-github/refined-github/pull/7119) and similar features that use the API
