### ISSUE TITLE
"Select all" on the notifications page is slower than normal

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7183]
## Without RG

https://github.com/refined-github/refined-github/assets/1402241/d31b744d-1c07-4a74-8a06-e32d834126c6

## Using RG

https://github.com/refined-github/refined-github/assets/1402241/e42cc6af-2d5e-4996-b48b-39e3b749d7a9

### How to replicate the issue + URL

https://github.com/notifications

### Extension version

23.12.1

### Browser(s) used

Safari

**Comment by cheap-glitch** [comment]
I don't have that issue on Firefox, could it be a Safari bug?

![bug](https://github.com/refined-github/refined-github/assets/46634000/2cef7881-e98a-499b-bd57-778504a193c4)

**Comment by fregante** [comment]
Can repro without Refined GitHub now. It seems to be due to calls in `lazy-define` but my guess is that it's a CSS performance issue similar to what we had for 

- #5797
