### ISSUE TITLE
`one-click-diff-options`: Redundant button shown on commits

### ISSUE THREAD

**Issue by auscompgeek** [refined-github/refined-github#7184]
### Description

A redundant **No Whitespace** button is shown when viewing commits, next to the **Whitespace / Ignore whitespace** toggle.

Moreover, the button doesn't actually do anything – it only reloads the page when pressed. Its active state doesn't change with the state of the page either.

![screenshot: whitespace shown](https://github.com/refined-github/refined-github/assets/128854/33b8aaea-5ea9-485b-be8d-43c06eb88fcd)

![screenshot: whitespace ignored](https://github.com/refined-github/refined-github/assets/128854/fe0d86d1-4181-41cc-a7ad-ba0e4e8f65a3)

### How to replicate the issue + URL

https://github.com/refined-github/sandbox/commit/96451b68751d9807d5da0964868f418c5eeee148

### Extension version

23.12.17

### Browser(s) used

Firefox 121

**Comment by fregante** [comment]
It looks like GitHub added that button natively. PR welcome to disable the feature on those pages
