### ISSUE TITLE
Reduce markdown preview height to exact rendered size

### ISSUE THREAD

**Issue by pgimalac** [refined-github/refined-github#7187]
### Description

Github has a bug where when a markdown input's height is bigger than the rendered text, the preview tab will not be reduced to the exact size, resulting in a lot of empty space at the bottom.

This is a Github issue, but exacerbated when the `fit-textareas` feature is enabled, so I wasn't sure whether this would fit this project, and if so if it should be part of `fit-textareas` or be its own new feature (but considering it's not really about a `textarea` it might not really belong in `fit-textareas`).

Note that I locally implemented a fix for this issue, by removing the `size` style on the preview `div` when the `preview` button is clicked. Let me know if you think this can be part of this project.

### Example URLs

I don't have an URL, it applies to any markdown input field with preview tab, in order to reproduce you can just insert empty lines in your markdown input.

A less contrived example is when there are html comments (which are not rendered) in the input, it easily makes the input much bigger than the rendered format.

<table>
<tr>
 <td> Input
 <td> Original
 <td> With fix
<tr>
 <td> <img width="628" alt="image" src="https://github.com/refined-github/refined-github/assets/23154723/5d4c2781-46a9-4a77-b7aa-242494ee0010">
 <td> <img width="623" alt="image" src="https://github.com/refined-github/refined-github/assets/23154723/8e31b9f3-db8b-49bf-acb6-0de72e96be86">
 <td> <img width="743" alt="image" src="https://github.com/refined-github/refined-github/assets/23154723/e3a562de-9f86-4955-bb60-90ed87a6140c">
</table>

**Comment by fregante** [comment]
100% right about this one. It can go in `GitHub-bugs.css`

**Comment by pgimalac** [comment]
Nice, the fix is actually much cleaner directly from the CSS ! 
I'll open a PR tonight
