### ISSUE TITLE
Option for button-link to open the extension settings page

### ISSUE THREAD

**Issue by venkatasg** [refined-github/refined-github#7188]
### Description

Simple enough feature - right now there is an option for setting the page to open when the Extension icon is clicked on in the Safari toolbar. Would it be possible to have a setting for that to open the Settings for the extension? The address field is empty on Safari unfortunately so I believe this has to be done in the App itself somewhere?

### Example URLs

N/A

**Comment by fregante** [comment]
This URL should work in Safari:

```
safari-web-extension://421AC83C-3D45-450B-B2EE-AEE4EC26C049/assets/options.html
```

**Comment by venkatasg** [comment]
Interesting. I tried that URL but it just opens an empty page for me unfortunately :(

**Comment by fregante** [comment]
We might want to add support for opening the options page by just typing "options" in the field.

Alternative low-effort UIs/solutions?

**Comment by fregante** [comment]
> just typing "options" in the field

1. add information below field
2. detect `"options"` in the click handler and call `runtime.openOptionsPage()`
