### ISSUE TITLE
`use-first-commit-message-for-new-prs` overrides user set title when refreshing page

### ISSUE THREAD

**Issue by pgimalac** [refined-github/refined-github#7191]
### Description

When opening a PR and refreshing the page, Github will keep the previously entered title and body.
When `use-first-commit-message-for-new-prs` is enabled, refreshing the page will overwrite the title with the first commit.

<table>
<tr>
 <td> Without `use-first-commit-message-for-new-prs`
 <td> With `use-first-commit-message-for-new-prs`
<tr>
 <td> <video src="https://github.com/refined-github/refined-github/assets/23154723/21a7cec2-329a-40a3-b912-d9ca1813a1ce">
 <td> <video src="https://github.com/refined-github/refined-github/assets/23154723/2d5c99e1-97db-4891-ad2b-4f93c0ccb747">
</table>

### How to replicate the issue + URL

https://github.com/pgimalac/refined-github/compare/main...pgimalac:refined-github:pgimalac/fit-rendered-markdown?expand=1

I guess the above URL will only work if you have permissions on the source/target repo, you can use any URL for opening a PR.
Note that it doesn't seem to reproduce for cross-repo PRs.

### Extension version

23.12.17

### Browser(s) used

Chrome 120.0.6099.129

**Comment by fregante** [comment]
Possible solutions:

- detect `session:resume` event

I think that's what's refilling the screen here

**Comment by pgimalac** [comment]
@fregante what do you think of just not replacing the title if the page was reloaded, using the logic described in https://stackoverflow.com/questions/5004978/check-if-page-gets-reloaded-or-refreshed-in-javascript/53307588#53307588 ?

Let me know if that would work for you, I can open a PR.

**Comment by fregante** [comment]
I think we still need to cover reloads for the feature to work normally, right?

If you don't touch the field, what happens when you reload the page? Does first commit stay in the title?

**Comment by pgimalac** [comment]
I assumed the first time you open the page the feature replaces the title with the first commit, and then when you refresh GIthub restores whatever was in the field, whether it's the first commit or the user wrote something.

I'll give it a try and open a PR if it works properly.

**Comment by fregante** [comment]
That may be right, it should be tested:

1. Load the page
2. Have Refined GitHub set the title
3. Disable Refined GitHub 
4. Reload the page

**Comment by pgimalac** [comment]
I tested what you described and it works properly.
I implemented a fix and it also works as expected. I'll open a PR.
