### ISSUE TITLE
`table-input`: breaks all buttons in comment editor

### ISSUE THREAD

**Issue by zeertzjq** [refined-github/refined-github#7203]
### Description

`table-input` breaks all buttons in comment editor:

https://github.com/refined-github/refined-github/assets/35768171/7804638d-2b5a-4dc8-9dc5-35a987603d83

### How to replicate the issue + URL

It can be reproduced in any GitHub comment box, including the one at the bottom of this issue. It doesn't happen if the `table-input` feature is disabled.

### Extension version

23.12.17

### Browser(s) used

Firefox 121.0

**Comment by fregante** [comment]
Thank you for the report. I'll try disabling the feature via hotfix
