### ISSUE TITLE
Automatically pre-select merge type

### ISSUE THREAD

**Issue by Turbo87** [refined-github/refined-github#7204]
### Description

![Bildschirmfoto 2024-01-05 um 11 26 49](https://github.com/refined-github/refined-github/assets/141300/906aea0d-4e05-4341-94f1-fa7fb01c4dc9)

GitHub remembers the selection of the last merge and uses it as the pre-selection for the next PR. 

It would be nice if instead "Squash and merge" was the default for PRs with a single commit and "Create a merge commit" for multi-commit PRs.

### Example URLs

On any PR page where the user has merge permissions

**Comment by fregante** [comment]
This was requested and rejected because *your* merge type preference doesn't match everyone's, and we don't have options to let you pick the default merge type 🥹
