### ISSUE TITLE
`repo-wide-file-finder`: not working

### ISSUE THREAD

**Issue by ilike2burnthing** [refined-github/refined-github#7209]
### Description

Pressing `t` no longer redirects to file finder, unless you're on the Commits page (same as without the extension).

Update: 99% certain this used to work for me.

### How to replicate the issue + URL

- https://github.com/refined-github/refined-github/actions
- press `t`
- nothing

---

- https://github.com/refined-github/refined-github/commits/main/
- press `t`
- redirects to file finder

### Extension version

23.12.17

### Browser(s) used

Edge, Chrome, Firefox

**Comment by fregante** [comment]
It works everywhere for me. Is the feature enabled for you?


https://github.com/refined-github/refined-github/assets/1402241/d003594b-9718-4cc7-8d39-cf2ab46e614c

**Comment by ilike2burnthing** [comment]
Yep, definitely enabled. I even fired up Windows Sandbox before opening the issue to make sure there couldn't be anything else affecting it - default addon/extension settings, fresh browser installs, no old cache files.

In case it helps, I'm on Windows 10 22H2 and Edge v120 (and whatever the latest Firefox and Chrome installs were in Windows Sandbox).

In the extension settings site access is allowed for `https://api.github.com/*`, `https://gist.github.com/*` and `https://github.com/`, and I've allowed access to file URLs. I'm not running in Private mode.

I haven't added a personal token to the app, but from my understanding that shouldn't affect this feature.

While I do have some features disabled, this isn't one of them (although I have tested disabling and re-enabling it, didn't work), and none were disabled when testing in Windows Sandbox.

If there's any further information you need from me, or testing I can try, let me know.

**Comment by ilike2burnthing** [comment]
Just to take my system completely out of the mix, I tried it on any.run (an online sandbox) - https://app.any.run/tasks/8c0e9189-7cc4-4d63-9b00-6dfdc4817287

Last 3 screenshots are me pressing `t` and it working on the commit page, and the screenshots before that are me pressing `t` on various other pages and it not working.

**Comment by ilike2burnthing** [comment]
Personal token was required, but I'm not sure it is supposed to be. See also - https://github.com/refined-github/refined-github/issues/7218

**Comment by busches** [comment]
This uses `getDefaultBranch` conditionally, which conditionally calls the V4 API and requires a token. See the comments in #7218
