### ISSUE TITLE
Add use-last-commit-message-for-new-prs

### ISSUE THREAD

**Issue by shepmaster** [refined-github/refined-github#7213]
### Description

My usual PR starts with a bunch of refactoring and/or plumbing commits and ends with a singular featureful commit that is the point of the PR. A simple mockup:

- [refactor] Extract a function
- [fix] Unify behavior of features A and B

With the current behavior provided by `use-first-commit-message-for-new-prs`, my PR will get the title "[refactor] Extract a function", but "[fix] Unify behavior of features A and B" would be much better.

I think this makes sense to add for the same reasons that `use-first` exists, but there's obviously going to be a lot of duplication between it and `use-first`. 

Some ideas I see:
 - Add configuration to `use-first` that allows it to actually be `use-last`. I don't see any other features with configuration though, so that may be a non-starter.
 - Duplicate `use-first` to `use-last` (probably extracting out common code). This would be a bit weird as there'd be two features conflicting with each other, so one would want to be disabled by default, which I also don't see existing already. 

I'm happy to do the implementation work here, but would love guidance on what path would be best for the project.

### Example URLs

https://github.com/refined-github/sandbox/compare/linked-commit-title?expand=1
https://github.com/refined-github/sandbox/compare/rendered-commit-title?expand=1
https://github.com/refined-github/sandbox/compare/github-moji?expand=1

**Comment by fregante** [comment]
What you're suggesting is an option, which Refined GitHub doesn't do, see:

https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options

**Comment by shepmaster** [comment]
I understand that the first choice I suggested would be an option. Do you also think that the second case I said, of having two mutually exclusive features with one disabled by default, counts as an "option"? 

As you even suggested, the user already has the ability to disable features they don't like. The big change here would be a feature that starts disabled.

---

As a more contentious suggestion, what about **changing** from `first` to `last`? People who do single-commit PRs won't notice. This *is* based on my highly opinionated belief that my way of ordering commits in a PR is the correct and obvious thing to do, so I believe other people think the same thing.

**Comment by busches** [comment]
It wouldn't be an option, but it's covered by https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#2-it-makes-sense-as-a-default-for-everyone

**Comment by shepmaster** [comment]
Right, which I mentioned in my edit, correct? Or do you mean something else?

**Comment by shepmaster** [comment]
Well, [I created a userscript](https://github.com/shepmaster/github-userscripts/blob/main/last-commit-as-pr-content.js).
