### ISSUE TITLE
Clicking outside "All checks have passed" works on chrome but not on safari

### ISSUE THREAD

**Issue by darklight147** [refined-github/refined-github#7216]
### Description

Clicking outside the pop-up doesn't make the pop-up close on safari, works on chrome though

<img width="969" alt="image" src="https://github.com/refined-github/refined-github/assets/39389636/c2c81894-2510-4a63-8c3a-43c7d3677cf5">

### How to replicate the issue + URL

1. Go to https://github.com/refined-github/refined-github
<img width="112" alt="image" src="https://github.com/refined-github/refined-github/assets/39389636/d35c8a71-183d-4156-b181-9cd7473f8096">

2. Click on the checkmark of the "All checks have passed popup"
3. Then try clicking outside it to close it

### Extension version

24.1.10

### Browser(s) used

Safari

**Comment by fregante** [comment]
There is no 24.1.10 on Safari. The feature hasn't been released there yet
