### ISSUE TITLE
Weird yellow highlighting in diff view in PRs

### ISSUE THREAD

**Issue by dhruv-anand-aintech** [refined-github/refined-github#7217]
### Description

eg: See https://github.com/superlinked/VectorHub/pull/118/files

![Screenshot 2024-01-12 at 6 07 41 PM](https://github.com/refined-github/refined-github/assets/105786647/f22d5b55-f0d0-452d-9b89-c66aaa3ce189)

### How to replicate the issue + URL

Go to https://github.com/superlinked/VectorHub/pull/118/files

### Extension version

24.1.10

### Browser(s) used

Arc

**Comment by ilike2burnthing** [comment]
May be specific to Arc, or a conflict with another extension, as I'm unable to reproduce it with Edge, Chrome, Firefox, Opera, Vivaldi, or Brave on Windows 10 (no Arc for it yet).

**Comment by fregante** [comment]
Thank you for testing!
