### ISSUE TITLE
show-names - Show full name in the commit details header

### ISSUE THREAD

**Issue by yrtimiD** [refined-github/refined-github#7227]
### Description

![image](https://github.com/refined-github/refined-github/assets/816805/f4018d7a-2c79-4c78-aacb-758caa6c15ee)

### Example URLs

https://github.com/refined-github/refined-github/commit/0bff395e209f29841b89a1b12a8cb2ae213f5790

**Comment by fregante** [comment]
Please report them all in the same issue
