### ISSUE TITLE
Add ability to hide issues perpetually

### ISSUE THREAD

**Issue by deanm0000** [refined-github/refined-github#7228]
### Description

Equivalent of opening the inspect window and finding `<div id="issue_xxx">` then deleting it but we'd want to save the _hidden_ ids so that after a reload they remain hidden.

### Example URLs

https://github.com/refined-github/refined-github/issues

**Comment by fregante** [comment]
Sounds niche, sorry.

Also we generally don't accept features that require options/management (e.g. see a list of hidden issues).

Very related:

- https://github.com/refined-github/refined-github/issues/2672#issuecomment-1208916485

**Comment by deanm0000** [comment]
@fregante fair enough, thanks for the quick response.
