### ISSUE TITLE
`toggle-files-button`: button does not show up anymore

### ISSUE THREAD

**Issue by panva** [refined-github/refined-github#7230]
### Description

The button to collapse files does not show up anymore.

Expected (per the feature's preview)

![image](https://github.com/refined-github/refined-github/assets/241506/edc0ebf9-e800-47e0-8134-96e98c1d1712)

Actual
![image](https://github.com/refined-github/refined-github/assets/241506/974c0741-8a58-45fe-8a53-78b2fe1c3b1b)

No console errors, when enabling debugging there's still a ✅ for the feature.

### How to replicate the issue + URL

Navigate to any repository with files, e.g. https://github.com/refined-github/refined-github

### Extension version

24.1.10

### Browser(s) used

Chrome

**Comment by panva** [comment]
Duplicate of #6959

**Comment by fregante** [comment]
Also in 24.6.2

**Comment by fregante** [comment]
It's not broken, it was removed:

- https://github.com/refined-github/refined-github/pull/7741
