### ISSUE TITLE
Improve bulk applying multiple issue attributes

### ISSUE THREAD

**Issue by groenroos** [refined-github/refined-github#7233]
### Description

If I wish to bulk select multiple issues, and apply multiple issue attributes (e.g. the same label, and the same milestone) to each selected issue, the page will reload after applying the first attribute, and the selection will be lost. I then have to manually re-select the issues to apply the second bulk edit.

I'd either want the issue selection to be persisted across the page reload so that I can apply the second edit immediately afterwards; or alternatively, not apply the change immediately, and instead surface a `Confirm` button that allows applying multiple attributes to the selection, and submitting it all at once (although I do realise this goes against GitHub's established UX for issue attributes).

### Example URLs

https://github.com/refined-github/refined-github/issues

**Comment by fregante** [comment]
This is too much UI and state for Refined GitHub. If this sort of action happens regularly, you might want to look into Projects. I think you can drag issues into columns and they get labels and stuff assigned to them
