### ISSUE TITLE
`clean-conversation-sidebar` breaks "Create a branch from issue "

### ISSUE THREAD

**Issue by B1ack3ye** [refined-github/refined-github#7235]
### Description

When attempting to create a branch from an issue in my GitHub repository under the development section in the sidebar, I encounter an issue when the "clean-conversation-sidebar" feature is enabled, the "Create a branch" link is missing.

Without "clean-conversation-sidebar" I can click on the "Create a branch" link:
![image](https://github.com/refined-github/refined-github/assets/63259739/7d19a7e0-7de3-4062-9d1e-108bdff37ecf)

With "clean-conversation-sidebar" on:
![image](https://github.com/refined-github/refined-github/assets/63259739/433c39f3-c8e3-446b-a2af-68d0b566f137)

### How to replicate the issue + URL

Can't find any repo where this feature is enabled for me except in my own.

1. Open an issue in the GitHub repository, where you can create branches.
2. Try to create a branch from the issue.

### Extension version

24.1.10

### Browser(s) used

Google Chrome

**Comment by fregante** [comment]
This is still a bug. Thank you for reporting

**Comment by DenverCoder1** [comment]
This is also an issue for being able to open a Copilot Workspace from an issue (a feature currently in technical preview)

| Without `clean-conversation-sidebar` | With `clean-conversation-sidebar` |
| --- | --- |
| ![image](https://github.com/refined-github/refined-github/assets/20955511/fe0db098-5d0b-4d1c-a15e-4a35d5336ab2) | ![image](https://github.com/refined-github/refined-github/assets/20955511/a0f15e72-4b4b-4a14-a392-6153702b1e74) |
