### ISSUE TITLE
`table-input`: editor button overflows in small enough viewport

### ISSUE THREAD

**Issue by tranhl** [refined-github/refined-github#7236]
### Description

At small enough viewports, the `table-input` button overflows when adding a comment to a PR during review. Seems like the "Add collapsible content"  button also does the same thing.

Example of bug:

<img width="1357" alt="image" src="https://github.com/refined-github/refined-github/assets/24240419/22bcc724-15fd-4782-a1a5-fa8b8c148fcd">

When hiding the file list, the button is correctly positioned:

<img width="1342" alt="image" src="https://github.com/refined-github/refined-github/assets/24240419/bfbb838b-526e-4e07-956f-d56391892073">

### How to replicate the issue + URL

URL: https://github.com/microsoft/vscode/pull/203467/files

1. Open link above
2. Click on "Add comment" button
<img width="548" alt="image" src="https://github.com/refined-github/refined-github/assets/24240419/c3643f4b-bd00-4156-8ccb-c66ccec38859">

3. Observe table input button overflowing.

### Extension version

24.1.10

### Browser(s) used

Arc 1.27.3 (45706), Chromium Engine Version 121.0.6167.85

**Comment by ilike2burnthing** [comment]
https://github.com/refined-github/refined-github/pull/7214

**Comment by fregante** [comment]
Thank you! Indeed this was fixed but not released yet. I'll try to release soon

**Comment by fregante** [comment]
All good in 24.2.2?

**Comment by ilike2burnthing** [comment]
Unfortunately no. As long as `table-input` is enabled, the buttons overflow on a small textbox.

Edge v121.0.2277.98, Chrome 121.0.6167.140, Firefox 122.0
Windows 10 (confirmed with clean install in Sandbox)
Refined GitHub 24.2.2

**Comment by ForsakenHarmony** [comment]
@fregante the attribute was applied to the wrong element
https://github.com/refined-github/refined-github/pull/7214#discussion_r1484637202

**Comment by levrik** [comment]
This feature seems to be broken completely right now for at least ~2 weeks or so.
The button is there, also correctly placed but does nothing when clicked.
