### ISSUE TITLE
Is it possible that no Options > Export options button is not working?

### ISSUE THREAD

**Issue by stdedos** [refined-github/refined-github#7245]
I am expecting that the Export button would give some kind of popup with a JSON, and the Import would have some text input button to paste a previously Exported JSON.

But both of them appear decorative, and not functional

Version
24.2.2

**Comment by fregante** [comment]
Browser?

**Comment by stdedos** [comment]
Chrome. I have it set to "Ask each time", and nothing was asked. Also, `~/Downloads` has nothing 😕

**Comment by fregante** [comment]
Any errors in the console?

**Comment by stdedos** [comment]
Checked it too - empty

**Comment by ilike2burnthing** [comment]
Disable all other extensions, see if the issue continues.

Does the issue occur in another browser (preferably non-Chromium-based, e.g. Firefox)?

**Comment by fregante** [comment]
The most I can say is: Works For Me ™️ 🥹 

<img width="587" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/748705d5-9874-4613-88d0-2622595ba604">

**Comment by fregante** [comment]
1. Open `chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/options.html`
2. Click "Export"
3. Check the console now

**Comment by stdedos** [comment]
> Disable all other extensions, see if the issue continues.

Nothing changes by disabling every other extension :confused: 
 
> Does the issue occur in another browser (preferably non-Chromium-based, e.g. Firefox)?

I don't use the extension in another browser, sadly

> 1. Open `chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/options.html`

Following `chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/options.html`, I get:
```
options.js:3279 Uncaught (in promise) DOMException: The user aborted a request.
```
in
```js
      exportToFile=async () => {
        const extension = chrome.runtime.getManifest(), text = JSON.stringify({
          [this._jsonIdentityHelper]: extension.name,
          ...await this.getAll()
        }, null, "\t");
        await saveFile(text, extension.name + " options.json");
*     };
```
line.

I was able to extract the `text` to clipboard, and then manually to a text file from this page

**Comment by fregante** [comment]
It seems that `showSaveFilePicker` exists but is being auto-closed by the browser.

My guess is that you're running Chrome in some alternative way (e.g. via command line), there's some configuration breaking it (e.g. in `chrome://flags`) or your OS is broken.

Are you on Linux?

**Comment by fregante** [comment]
> your OS is broken

Related?

- https://github.com/telegramdesktop/tdesktop/issues/27440

**Comment by stdedos** [comment]
> My guess is that you're running Chrome in some alternative way (e.g. via command line), ...

No

> there's some configuration breaking it (e.g. in `chrome://flags`) ...

I can try that later, but _I don't think so_

> or your OS is broken.

"Not as far as I know"

> Are you on Linux?

Yes

> > your OS is broken
> 
> Related?
> 
> * [Copying text from Telegram Desktop doesn't work telegramdesktop/tdesktop#27440](https://github.com/telegramdesktop/tdesktop/issues/27440)

_Thank you for digging my recent issues_ 😅 
But no. Different system.

**Comment by fregante** [comment]
Do you have an antivirus? Is your computer locked down in other ways? Is it a company computer with enterprise provisioning?

**Comment by fregante** [comment]
> > Are you on Linux?
> 
> Yes

ur on ur own 🥹 ✌️

**Comment by ilike2burnthing** [comment]
>>Does the issue occur in another browser (preferably non-Chromium-based, e.g. Firefox)?
>
>I don't use the extension in another browser, sadly

Can you not do so for the sake of troubleshooting the issue?

Any policies set which might cause an issue? - `chrome://policy`

**Comment by fregante** [comment]
Just to give some context, `showSaveFilePicker()` asks the OS to show a "file save" dialog, giving complete control to the OS. The error suggests that the dialog was "cancelled" by the user, but since you didn't, then the OS is taking that action for you. 

If you'd like to further debug this issue, you can try running the API directly, for example in this demo:

- https://googlechromelabs.github.io/text-editor/

Then you can probably report the issue to the Chrome bug tracker. At the moment only Chromium browsers support this API:

- https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker#browser_compatibility

**Comment by stdedos** [comment]
> > > Does the issue occur in another browser (preferably non-Chromium-based, e.g. Firefox)?
> > 
> > 
> > I don't use the extension in another browser, sadly
> 
> Can you not do so for the sake of troubleshooting the issue?
> 
> Any policies set which might cause an issue? - `chrome://policy`

```json
{
   "chromeMetadata": {
      "OS": "Linux",
      "application": "Google Chrome",
      "revision": "5148e93c94b4990618801dd6918f26936be770f9-refs/branch-heads/5735_90@{#9}",
      "version": "114.0.5735.106 (Official Build) (64-bit)"
   },
   "policyValues": {
      "chrome": {
         "name": "Chrome Policies",
         "policies": {
         }
      },
      "extensions": {
         "cjpalhdlnbpafiamejdnhcphjbkeiagm": {
            "forSigninScreen": false,
            "id": "cjpalhdlnbpafiamejdnhcphjbkeiagm",
            "name": "uBlock Origin",
            "policies": {
            }
         },
         "djflhoibgkdhkhhcedjiklpkjnoahfmg": {
            "forSigninScreen": false,
            "id": "djflhoibgkdhkhhcedjiklpkjnoahfmg",
            "name": "User-Agent Switcher for Chrome",
            "policies": {
            }
         },
         "ghbmnnjooekpmoecnnnilnnbdlolhkhi": {
            "forSigninScreen": false,
            "id": "ghbmnnjooekpmoecnnnilnnbdlolhkhi",
            "name": "Google Docs Offline",
            "policies": {
            }
         },
      },
      "precedence": {
         "name": "Policy Precedence",
         "policies": {
         },
         "precedenceOrder": [ "Platform machine", "Cloud machine", "Platform user", "Cloud user" ]
      }
   },
   "status": {
      "user": {
      }
   }
}
```

**Comment by stdedos** [comment]
> Just to give some context, `showSaveFilePicker()` asks the OS to show a "file save" dialog, giving complete control to the OS. The error suggests that the dialog was "cancelled" by the user, but since you didn't, then the OS is taking that action for you.
> 
> If you'd like to further debug this issue, you can try running the API directly, for example in this demo:
> 
> * [googlechromelabs.github.io/text-editor](https://googlechromelabs.github.io/text-editor/)

It works 😅 

![image](https://github.com/refined-github/refined-github/assets/133706/93d7851a-6664-4630-b1e8-7aa73d37546b)

But anyhow - I understand your "Linux 🤷" attitude. The `chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/options.html` workaround was okay now for my purposes.

... Let's hope I don't need to Import something (which would definitely not be that easily hack-able)
