### ISSUE TITLE
notification page won't open new tabs (shift-o)

### ISSUE THREAD

**Issue by yeled** [refined-github/refined-github#7246]
### Description

I can't `Shift-O` (capital O) anymore on https://github.com/notifications.

I last noticed this in 2020: https://github.com/refined-github/refined-github/issues/3704 but I am not adept enough to understand what might have broken this time, there has been rewriting of the code since then.

### How to replicate the issue + URL

https://github.com/notifications

highlight with `j` or `k` and then press `O` and expect a new tab to open.

### Extension version

24.2.2

### Browser(s) used

Chrome/Safari/Firefox

**Comment by fregante** [comment]
Thank you for the report! It'll be fixed in the next release
