### ISSUE TITLE
Duplicate footer on org dashboard page

### ISSUE THREAD

**Issue by Ngoakor12** [refined-github/refined-github#7248]
### Description

Refined github introduces a footer that's no longer needed in the org dashboard page?

![image](https://github.com/refined-github/refined-github/assets/54069197/354ec5d3-49cb-4b72-8b3c-14291b12ad81)
GitHub

### How to replicate the issue + URL

1. Go to a dashboard page for an organization. E.g. https://github.com/orgs/Umuzi-org/dashboard
2. Scroll to the end of the page. You will see the same footer on both the middle and right section

### Extension version

24.2.2

### Browser(s) used

Google Chrome on Linux, Version 119.0.6045.105 (Official Build) (64-bit)

**Comment by fregante** [comment]
I think `infinite-scroll` moves the footer to the sidebar. Somehow it's adding it to the sidebar but not removing it from the footer.

**Comment by fregante** [comment]
Judging by the code, this was intentional. The footer was _copied_ to the sidebar.

**Comment by Ngoakor12** [comment]
Thanks for the update. I'm a big fan of the project :sweat_smile:  :ok_hand:
