### ISSUE TITLE
`conversation-activity-filter`: allow setting permanent default

### ISSUE THREAD

**Issue by Jacobfaib** [refined-github/refined-github#7254]
### Description

I would like to set a default value for `conversation-activity-filter`, such that I don't have to select the right filter every time. Currently it resets to "Show all" on each PR and even if you refresh the same PR page.

Gitlab natively supports filtering the comment log and allows setting a default for the filter:
1. globally
2. per repository
3. per merge request

Would be great if all three are supported, but if I only had to pick one it would be a global default.

Thanks!

### Example URLs

N/A?

**Comment by fregante** [comment]
We can't add further options to Refined GitHub, see:

https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options
