### ISSUE TITLE
review changes button

### ISSUE THREAD

**Issue by huehnerlady** [refined-github/refined-github#7256]
Hi,

I created it as a question as I am not sure if that feature might already exist. 

I have 2 ideas around the `review changes` button. I had a look in the features list, but couldn't find anything there.

1. idea: when clicking on `review changes`, move the cursor into the text area
![image](https://github.com/refined-github/refined-github/assets/12533979/9a9b8323-69ce-4dd3-a42b-f589c641d1db)

2. idea: add a shortcut to click the button `review changes` in the files tab of a pull request

this would make reviewing very small PRs, like dependabot upgrades, very quick and removes the need to click around with a mouse :)

**Comment by fregante** [comment]
Actually we have both:

1. It's there but it's broken if it doesn't already focus the field
2. The shortcut is `v` if I remember correctly

**Comment by huehnerlady** [comment]
> 1. It's there but it's broken if it doesn't already focus the field
Ah ok, I thought it did work before, but for me it is not focussing anymore. Do you know which feature this would be so I can enable it again? 


> 2. The shortcut is `v` if I remember correctly
ah super, maybe it would be helpful to add that to the list in `?` in github?
![image](https://github.com/refined-github/refined-github/assets/12533979/fecd8f88-62fa-46c7-902b-83a3cd658aae)

**Comment by huehnerlady** [comment]
@fregante I had another look but even with the "find-feature" logic I could not find a way to enable the focussing off the review comment window. Do you have any more information about that?

**Comment by fregante** [comment]
There's nothing to enable. If it doesn't work it's broken. I don't remember what feature did that

**Comment by huehnerlady** [comment]
> There's nothing to enable. If it doesn't work it's broken. I don't remember what feature did that

Oh I see. is there an issue for this or would you like me to create a separate issue for that?

**Comment by huehnerlady** [comment]
@fregante any update on this?

**Comment by fregante** [comment]
I opened a bug report
