### ISSUE TITLE
No longer possible to open releases page in one click from repo homepage

### ISSUE THREAD

**Issue by bew** [refined-github/refined-github#7257]
### Description

After a fresh install of the plugin, without doing any configuration I loose the ability to single click to open the releases page:
![image](https://github.com/refined-github/refined-github/assets/9730330/711e018b-bbc0-4d2c-b114-06d6b24d1799)
With the extension I only see:
![image](https://github.com/refined-github/refined-github/assets/9730330/3f28a9ee-f7f1-4804-b157-a67d24452141)

I see in the issue tracker a mention of `releases-tab` feature but I would expect it to be enabled by default but I don't see it anywhere :disappointed: 
![image](https://github.com/refined-github/refined-github/assets/9730330/c50a56c8-89a0-4837-96a2-76887259ffc5)

(related: #3942)

### How to replicate the issue + URL

https://github.com/refined-github/refined-github or any other repo

### Extension version

24.2.8

### Browser(s) used

Firefox on Linux (NixOS)

**Comment by bew** [comment]
Oh, then would it be possible to avoid hiding the releases ritle on repo homepage when the token isn't set?

**Comment by fregante** [comment]
See:

- #7231

**Comment by bew** [comment]
Thanks, indeed that worked (even without giving the repo_delete permission) 👌
