### ISSUE TITLE
Preview README before file tree

### ISSUE THREAD

**Issue by its-miroma** [refined-github/refined-github#7260]
### Description

When a project does not nest its files in subdirectories,
the file tree shown before the README file gets very big.

I'd like to propose an option to preview the README before
the file tree.

Before:
![Screenshot of https://github.com/git/git, showing an enormous file tree before the README](https://github.com/refined-github/refined-github/assets/136986257/30c4c9d1-3163-4c71-aa1b-bf134481c28a)

After:
![Concept based on https://github.com/git/git, showing the README before the long file tree](https://github.com/refined-github/refined-github/assets/136986257/a70ac1d7-ade8-49eb-aaee-facf7f478794)

### Example URLs

https://github.com/git/git

**Comment by its-miroma** [comment]
This code in the console seems to work:

```js
container = document.querySelector(".Box-sc-g0xbh4-0.yfPnm")

readme = container.querySelector(".Box-sc-g0xbh4-0.ehcSsh")
files = container.querySelector(".Box-sc-g0xbh4-0")

container.insertBefore(readme, files)
```

**Comment by fregante** [comment]
We have a `toggle-files-button` feature that's currently not working, it's enough for this purpose.
