### ISSUE TITLE
Token validator fails with no `read:project` permission even if full `project` permission is given.

### ISSUE THREAD

**Issue by 134130** [refined-github/refined-github#7261]
### Description

The below error is appearing..
<img width="766" alt="image" src="https://github.com/refined-github/refined-github/assets/50487467/8fbae5fc-9721-435d-90c1-d4bdd7b12534">

When below permission is given, validator fails. (if only `read:project`, validator works)
<img width="424" alt="image" src="https://github.com/refined-github/refined-github/assets/50487467/29f5fce0-a56e-4fac-b340-9248908301b7">

### How to replicate the issue + URL

NOTE: Only occurs on my private repositories (SAML required Organization)
- https://github.com/refined-github/refined-github/pulls

> Also, `pr-approvals-count`, the css only feature is not works on above pulls page, on my private repositories (SAML required also)
In this case; It seems not `refined-github`'s bug, just GitHub not supplies hint for this feature. Just FYI

### Extension version

24.2.8

### Browser(s) used

Chrome 120.0.6099.234 (arm64)

**Comment by fregante** [comment]
Sigh 🥹 

This check needs to be adjusted further:

- https://github.com/refined-github/refined-github/pull/6728
