### ISSUE TITLE
Unable to add enterprise Github domain

### ISSUE THREAD

**Issue by btmurrell** [refined-github/refined-github#7264]
I have Enhanced Gh v5.0.12 on Chrome 121.0.6167.162 on Windows. I've been a longtime lover of refined github.... i am on a new machine, and do not seem to be able to enable it for my EGh. In place of the "enable" option I see "Can't read or change site's data".  I suspect this is because my Chrome is "managed by my organization" -- but it always has been. Is this a new restriction in a recent version of Enhanced Github? or did my organization get better at detection?  My heart is heavy at the prospect of being denied your extension. 😞   Any community hacks out there to get around this, I'm all 👀 .

![image](https://github.com/refined-github/refined-github/assets/634487/ce42b960-a006-4ea8-8593-2206daf420eb)

**Comment by busches** [comment]
This is Refined GitHub, not Enhanced GitHub.
