### ISSUE TITLE
Convert to GitHub Apps

### ISSUE THREAD

**Issue by Malix-off** [refined-github/refined-github#7265]
### Description

Convert to GitHub Apps (from Personal Access Tokens)
I don't know if it would be possible technically.
[GitHub Docs - Choosing between a GitHub App or a personal access token](https://docs.github.com/en/apps/creating-github-apps/about-creating-github-apps/deciding-when-to-build-a-github-app#choosing-between-a-github-app-or-a-personal-access-token)

**Comment by fregante** [comment]
I wouldn't be against the idea if it makes support easier, but we'd have to keep supporting both.

**Comment by fregante** [comment]
On second thought, I think this requires an external server to make the requests from, which I don't want to have.
