### ISSUE TITLE
Native Notifications

### ISSUE THREAD

**Issue by Malix-off** [refined-github/refined-github#7267]
### Description

Feature Native Notifications (for exemple, desktop notifications)

### Alternative

Use https://github.com/sindresorhus/notifier-for-github

**Comment by fregante** [comment]
You can continue using that extension.

**Comment by Malix-off** [comment]
@fregante indeed, but it would be nice to use only refined github to fix all the caveats of GitHub, even it having no desktop notifications for some reason (see https://github.com/orgs/community/discussions/106727)

**Comment by fregante** [comment]
No it wouldn't be nice. Different extensions with different needs are best handled by different people. This is also mentioned in the document linked when you opened this issue. 


https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22
