### ISSUE TITLE
`unreleased-commits`: draft release button wraps below

### ISSUE THREAD

**Issue by sainak** [refined-github/refined-github#7268]
### Description

After the branch and tags count is loaded, the draft release button wraps down.

expected:
<img width="905" alt="image" src="https://github.com/refined-github/refined-github/assets/46787056/6a16cf23-8a8b-4825-8537-6bbcec212ba4">

actual:
<img width="906" alt="image" src="https://github.com/refined-github/refined-github/assets/46787056/12dc36db-5c9f-4f66-bf99-3025b25d1d1f">

### How to replicate the issue + URL

Happens on https://github.com/coronasafe/care_fe (with write access)

### Extension version

24.2.8

### Browser(s) used

firefox

**Comment by cooljeanius** [comment]
seen also on [https://github.com/cooljeanius/emacs](https://github.com/cooljeanius/emacs):
<img width="932" alt="Screen Shot 2024-04-01 at 21 22 53" src="https://github.com/refined-github/refined-github/assets/1388660/26b37348-e3bb-488c-b46f-51654ac3adc9">
