### ISSUE TITLE
Filter `everything you're involved` bring me back to issues.

### ISSUE THREAD

**Issue by jkroepke** [refined-github/refined-github#7273]
### Description

Each time, I clicked on the filter "everything you're involved" while i'm at pull requests brings me back to issues.
![image](https://github.com/refined-github/refined-github/assets/1560587/9460a9f1-4ef6-4653-a9f5-791765d31f4d)

It seems like `is:pr` is missing.

It would be also great, if I'm at closed issues/pr `is:closed`, it should be persist after clicking on the filter, instead just always going to `is:open`.

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/pulls

### Extension version

24.2.8

### Browser(s) used

Edge 121.0.2277.128

**Comment by fregante** [comment]
See https://github.com/refined-github/refined-github/pull/7325#issuecomment-2030018403
