### ISSUE TITLE
Releases tab not shown when releases-tab enabled

### ISSUE THREAD

**Issue by piotrekkr** [refined-github/refined-github#7274]
### Description

I cannot make "Releases" tab to show in repo tab list. I have this setting enabled
![image](https://github.com/refined-github/refined-github/assets/503782/53a6ce82-702a-4bfe-affb-9e85c6b11193)
But releases tab is still missing

![image](https://github.com/refined-github/refined-github/assets/503782/9acf5918-c6c5-4e75-a124-39c106dda7d0)

Tried to clear extension cache and also use this extension in private window but still no releases tab.

### How to replicate the issue + URL

Visit any github repo that has multiple releases e.g. https://github.com/refined-github/refined-github

### Extension version

24.2.8

### Browser(s) used

Firefox 123.0

**Comment by piotrekkr** [comment]
I've enabled "Show the features enabled on each page in the console" and I have this:
![image](https://github.com/refined-github/refined-github/assets/503782/8679bc32-e5a7-41b3-889b-18371bf18e25)

**Comment by fregante** [comment]
Yes. Follow the advice in the log
