### ISSUE TITLE
Remove `clear-pr-merge-commit-message`

### ISSUE THREAD

**Issue by aaronliu0130** [refined-github/refined-github#7277]
### Description

GitHub now allows you to configure whether the PR description is a bunch of junk. As such, this feature isn't really useful anymore, and should be removed. I understand that I can disable it, however I don't understand any further usecases.
![The GitHub settings for a repository, showing the dropdown setting for the commit message, which includes "Default message", "Pull request title", "Pull request title and commit details", and "Pull request title and description".](https://github.com/refined-github/refined-github/assets/11874211/94f703f4-2a36-4663-b370-35b4aec0b9a5)

### Example URLs

https://github.com/refined-github/refined-github/pull/1418

**Comment by fregante** [comment]
GitHub allows the config per-repo, only if you're an admin. This feature works on every repo, without config
