### ISSUE TITLE
RFE: dim draft PRs in the PR list

### ISSUE THREAD

**Issue by BoD** [refined-github/refined-github#7279]
### Description

I usually go to the PR list to see what needs to be reviewed (or what's already reviewed and needs to be merged). In that context, Draft PRs are a bit of a 'noise'.

It would be nice if they could appear as dimmed, to remove some visual clutter, similarly to what [dim-bot](https://github.com/refined-github/refined-github/blob/main/source/features/dim-bots.tsx) does.

I realize this could probably be a UserScript instead (didn't find one that does this already) - but I _think_ most people would like this feature?

### Example URLs

https://github.com/refined-github/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc  (or any PR list of any repo that has draft PRs).

**Comment by fregante** [comment]
We tried this and it was too much because draft PRs are not "noise" like bot PRs are. We ended up going for a dimmer icon instead: `emphasize-draft-pr-label`
