### ISSUE TITLE
`prevent-pr-merge-panel-opening` doesn't work properly

### ISSUE THREAD

**Issue by jackbentley** [refined-github/refined-github#7280]
### Description

The feature doesn't do what it says: it doesn't keep the PR merge panel closed after page reload

It also adds a bug where some PRs will have the merge panel opened even though it's never been opened before. Clicking `cancel` should but doesn't stop it from being opened on page reload.

### How to replicate the issue + URL

Obviously this is going to be dependant on if you have maintainer access or not. So, I can't give any URLs. This should be present on any PR. I can't work out what causes the panel to open when it's never been opened before, though.

### Extension version

24.2.8

### Browser(s) used

Chrome

**Comment by fregante** [comment]
> The feature doesn't do what it says

Read the name: PREVENT opening.



> some PRs will have the merge panel opened even though it's never been opened before

This is the GitHub bug that this feature tries to fix

**Comment by jackbentley** [comment]
> Read the name: PREVENT opening.

Absolutely no need to be snarky. I appreciate I made a typo in the description but you could've been polite at least. I reported that it doesn't do what it says: It doesn't prevent it opening. I said it also actively opens it unnecessarily. 

<pre>
The feature doesn't do what it says: it doesn't keep the PR merge panel <s>open</s> <b>closed</b> after page reload
</pre>

> This is the GitHub bug that this feature tries to fix

No, what this apparently fixes (according to the description) is "after it’s been opened once". I was reporting a case where it's never been opened before which this will actively open it unnecessarily.

---

Regardless, I've tried again with this feature both enabled and disabled. It seems I can no longer reproduce this. It also seems the feature no longer does anything for me. The panel seems to always remains closed after a page reload regardless. Either it's related to me updating chrome, something has changed in GitHub, or this is an intermittent issue.

**Comment by fregante** [comment]
Sorry I wasn't trying to be snarky, I was just terse. The feature shouldn't _cause_ the issue, it's a GitHub bug/behavior that is amplified by the other features that touch the PR title/description if I remember correctly. 

GitHub's logic is:

1. save any user input in `sessionStorage`
2. if the page is reloaded and no new commits are in, restore the previous user input

Separately, there's another feature like:

999. on user input, open the panel 

Since _the other features_ alter the contents of the panel, it's sometimes treated as user input, which triggers _GitHub's own_ bug/behavior

**Comment by jackbentley** [comment]
> Sorry I wasn't trying to be snarky, I was just terse.

Not to worry.

When I opened the issue I was very certain it was this which was causing the panel to open on every PR page. Even ones which I had never visited prior.

I used the "Identify Feature" feature to find and disable it. I tested with it enabled and disabled and it seemed very definite it was causing the panel to open unnecessarily. However, as mentioned, I can't seem to replicate it any longer. 

Thanks for the info on how the feature gets activated. I can confirm it's working as expected currently. Editing the textbox causes the mentioned behaviour and the feature does indeed fix it. I'll re-enable and keep my eye on it to see if the bug I reported of it opening unnecessarily happens again. Feel free to close this for now.

**Comment by fregante** [comment]
I can't repro the issue and the feature seems to work correctly in my case. 

### Demo

0. **Without Refined GitHub** 
1. Leave field open
2. Reload page
3. See field open (native GitHub feature ✅)
4. **Enable Refined GitHub** 
5. Reload page
6. See field closed (`prevent-pr-merge-panel-opening` working properly ✅)


https://github.com/refined-github/refined-github/assets/1402241/b43ebafc-e2f8-4303-b280-d7b83d801d92
