### ISSUE TITLE
Show full committer and author details

### ISSUE THREAD

**Issue by MattSturgeon** [refined-github/refined-github#7281]
#### Summary

As per `git show` and `git log`, it is sometimes useful to see the "full" or "raw" commit header.

For example, if I want to mark another user as the `--author` or [`Co-Authored-By`](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) on a commit, I need to know the name & email they typically use in their commits.

#### Examples

<details><summary><strong><code>git show</code> output</strong></summary>
<p>

```markdown
$ git show 0a8910415d --no-patch
commit 0a8910415d07384e076bbc197ed1d1f1eb2500b2
Author: Matt Sturgeon <matt@sturgeon.me.uk>
Date:   Wed Mar 6 12:55:27 2024 +0000

    fix(nvim): Workaround which-key.nvim limitation

    Until [#583] is resolved, we need to call `:WhichKey` manually.

    Luckily the `<C-w>` mapping is delegated to which-key so it's not a big
    deal...

    [#583]: https://github.com/folke/which-key.nvim/issues/583

    Co-authored-by: Adrian Chong <adrianchong@seekasia.com>
```

</p>
</details> 

<details><summary><strong>Mockup</strong></summary>
<p>

A quick mockup I threw together in GIMP. The actual implementation could look significantly different if preferred.

![Mockup](https://github.com/refined-github/refined-github/assets/5046562/1f68385d-9e76-465b-8283-15dfb2881187)

</p>
</details> 

#### Alternative

Alternatively, a link to the plain text commit header would also achieve the same underlying goal and may prove more useful for other purposes?

### Example URLs

https://github.com/MattSturgeon/nix_config/commit/0a8910415d07384e076bbc197ed1d1f1eb2500b2

**Comment by fregante** [comment]
This already exists: `patch-diff-links` adds links to the entire commit patch
