### ISSUE TITLE
`clean-conversation-sidebar` breaks the labels picker

### ISSUE THREAD

**Issue by FliegendeWurst** [refined-github/refined-github#7283]
### Description

The labels/projects/milestone sections in issues and PRs are hidden when the extension is enabled. This makes it impossible to apply labels to issues or PRs, configure which project they belong to, or set their milestone.

![image](https://github.com/refined-github/refined-github/assets/12560461/64d82565-34d3-45fa-818b-37e496ceab8a)

### How to replicate the issue + URL

Open any issue or PR, e.g. #1

### Extension version

24.2.8

### Browser(s) used

Firefox

**Comment by fregante** [comment]
I think this is somewhat of an ajax issue. I saw it rarely since January and it seems to happen when going back and forth maybe.

**Comment by FliegendeWurst** [comment]
> That's a feature. They're only hidden when they're empty and not selectable (e.g. if you're just a viewer)

In my case, I have permission to apply labels and configure the project association etc.

> That's the bug, it's mistakenly removing the Labels header, but I think you can click the "Details" label?

I can, but that only works if there is already some label applied.

> Are you using a custom stylesheet? Why are all the rounded borders missing?

Yes, I'm using a custom stylesheet that removes the rounded borders.

**Comment by fregante** [comment]
> A page reload should fix it.

How about this?

**Comment by FliegendeWurst** [comment]
> > A page reload should fix it.
> 
> How about this?

It doesn't help.

**Comment by archon810** [comment]
I think the issue I found is similar enough to be merged into this one. If an issue is added to a project and then archived in the project, the Restore link is hidden by Refined Github.

Here's what it looks like with clean-conversation-sidebar disabled:
![image](https://github.com/refined-github/refined-github/assets/469543/cf1d3c74-6beb-4a5f-ab71-6afeed810b9e)

And with clean-conversation-sidebar enabled:
![image](https://github.com/refined-github/refined-github/assets/469543/06426884-dcdb-4d5c-a4b9-567b0695f25d)

**Comment by fregante** [comment]
I'm seeing this consistently now, even on this issue. The picker works but it's visually broken. The `summary` element is being removed

<img width="159" alt="Screenshot" src="https://github.com/user-attachments/assets/33e25745-21e5-475d-865a-bab68bea5825">
