### ISSUE TITLE
Button to list all commits in PR

### ISSUE THREAD

**Issue by jerone** [refined-github/refined-github#7285]
### Description

In Azure DevOps there is a feature that I use almost daily and that I'm missing here in GitHub.

When creating a PR in Azure DevOps, there's a button that will list all your PR commits into the description field at your cursors location.

This is handy when you want to list all the changes in your PR after you've carefully written all your commit messages. 
This will safe time writing the same PR description.

![image](https://github.com/refined-github/refined-github/assets/55841/3d610c57-bff8-4310-96cc-09ea967b240b)

### Example URLs

https://github.com/refined-github/refined-github/compare

**Comment by fregante** [comment]
GitHub does that by default, but `clear-pr-merge-commit-message` clears the field and leaves a message


<img width="922" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/192137126-2960d952-427c-44f2-9e0c-61d7b40ac98b.png">

**Comment by jerone** [comment]
Thanks for pointing to that feature. That feature is indeed about _merging a PR_, while my FR is about _creating a PR_.

Your screenshot is a good example where this FR is not useful (one-person-repo) :)

It is useful for when commits are written very descriptive. At least it's a good starting point to create a PR description.

I might create an userscript.
