### ISSUE TITLE
Did I do the pull request correctly?

### ISSUE THREAD

**Issue by win7guru** [refined-github/refined-github#7292]
I recently found a site called Snyk and it lets me find vulnerabilities in forked repos, yours for example.  My goal was to create a pull request from the fork and request it be committed to your public repo.  Is that okay?

**Comment by fregante** [comment]
Please don't. You can update them all at once if they work

**Comment by fregante** [comment]
See https://github.com/refined-github/refined-github/pulls?q=is%3Apr+update+dependencies+is%3Aclosed

**Comment by win7guru** [comment]
> Please don't. You can update them all at once if they work

I am not sure what you mean.  It keeps saying there are merge conflicts and they will not resolve.  Sorry for the confusion.
