### ISSUE TITLE
Support for setting file permissions (chmod) via Web UI

### ISSUE THREAD

**Issue by kvanzuijlen** [refined-github/refined-github#7296]
### Description

It would be quite nice if there was a way to change file permissions (chmod) via the Web UI. This of course would in turn trigger a commit and allow you to open a PR (normal file edit flow).

### Example URLs

https://github.com/refined-github/refined-github/blob/main/build/new-feature.sh

or

https://github.com/refined-github/refined-github/edit/main/build/new-feature.sh

**Comment by fregante** [comment]
It would be nice but this is such a rare operation I can't add it to Refined GitHub
