### ISSUE TITLE
Allow expanding force-pushed file diffs in pull requests

### ISSUE THREAD

**Issue by Minion3665** [refined-github/refined-github#7301]
### Description

This is very similar to #3097, however that feature proposed expanding the full forcepush history all the time, whereas this one doesn't: instead it could start collapsed.

Currently, GitHub only shows you the last 2 commit hashes for a forcepush, which means that if you do multiple forcepushes in a row [you lose access to previous forcepush commits](https://github.com/orgs/community/discussions/3478#discussioncomment-2676885). GitHub gives you a message like "*name forcepushed the __my-branch__ branch __X__ times, most recently from __penultimate-commit-hash__ to __last-commit-hash__*" but this stops you from seeing any commit hash before the penultimate one. As an example, you can't tell from the pull request page what the first commit hast was.

This causes particular trouble if you forcepush then realize you made some small mistake (perhaps you forgot to format) and you forcepush again to correct it. Suddenly your important changes are buried under a trivial formatting diff.

You can still get all the forcepush events via the API, for example by using this query in [the graphql explorer](https://docs.github.com/en/graphql/overview/explorer), which I constructed by modifying the query [in this comment](https://github.com/isaacs/github/issues/361#issuecomment-745692579)
<details>
<summary>A graphql query to show you a list of forcepush events, including hidden ones</summary>

```gql
{
  repository(name: "online", owner: "CollaboraOnline") {
    pullRequest(number: 8412) {
      timelineItems(last: 6, itemTypes: HEAD_REF_FORCE_PUSHED_EVENT) {
        nodes {
          ... on HeadRefForcePushedEvent {
            beforeCommit {
              commitUrl
            }
            afterCommit {
              commitUrl
            }
            createdAt
          }
        }
      }
    }
  }
}
```

</details>

Here's a comment on #3097 that further explains the ideal:
> I agree that collapsed is by far the best default as most of the time force push details are just noise. But still having access to the full force push history somewhere would be very useful in some situations.
> 
> Say you created a branch off another branch, and that branch under yours was force pushed. Such a problem is solvable with git rebase --onto, but you need to know the full force push history to get the correct git hashes.
> 
> Let me know if the full force push history is just hidden somewhere, or I am simply just overlooking where to expand it.

### Example URLs

https://github.com/CollaboraOnline/online/pull/8412
https://github.com/CollaboraOnline/online/pull/7857
https://github.com/CollaboraOnline/online/pull/8311

**Comment by fregante** [comment]
> GitHub only shows you the last 2 commit hashes for a forcepush

The solution is to stop force-pushing. If you want to keep the history, then use git un-forcefully.

I can't add this here because it's a non-trivial feature that goes against reason why git exists
