### ISSUE TITLE
`unwrap-unnecessary-dropdowns` errors on notifications page

### ISSUE THREAD

**Issue by connorjclark** [refined-github/refined-github#7304]
### Description

https://github.com/refined-github/refined-github/assets/4071474/d740ef96-e003-4d8d-b0cf-8633c25b3f90

```
 unwrap-unnecessary-dropdowns
refined-github.js:4009 📕 24.2.8 → TypeError: Cannot read properties of undefined (reading 'textContent')
    at init (refined-github.js:9507:139)
    at async refined-github.js:4060:22
    at async Promise.all (index 0)
    at async refined-github.js:4056:11
    at async runFeature (refined-github.js:4055:9)
    at async setupPageLoad (refined-github.js:4072:37)
```

### How to replicate the issue + URL

just go to https://github.com/notifications . You'll need at least one notification to see the Select All header.

### Extension version

24.2.8

### Browser(s) used

123.0.6312.46 (Official Build) (arm64)

**Comment by blakegearin** [comment]
Even with `unwrap-unnecessary-dropdowns` disabled I'm still seeing the large `box-shadow` that wasn't there yesterday. 

Looks like it's coming from [`sticky-notifications-actions`](https://github.com/refined-github/refined-github/blame/main/source/features/sticky-notifications-actions.css). `--rgh-background` is white when it used to be a [dark color](https://github.com/refined-github/refined-github/pull/6465#issuecomment-1835492446).

**Comment by jdreesen** [comment]
Yes, it seems like GitHub made some bigger changes which breaks many addons :/

**Comment by fregante** [comment]
I left the shadow issue in https://github.com/refined-github/refined-github/issues/7305

The console error for `unwrap-unnecessary-dropdowns` is unrelated

**Comment by fregante** [comment]
Can't repro, I assume the likes are related to the shadow issue, which was resolved and is unrelated
