### ISSUE TITLE
`file-age` not working anymore?

### ISSUE THREAD

**Issue by melMass** [refined-github/refined-github#7308]
### Description

The file-age feature (#6340) seems to have broken very recently:
![image](https://github.com/refined-github/refined-github/assets/7041726/846b4674-0884-4894-8d8d-0e8eda222c70)

### How to replicate the issue + URL

https://github.com/refined-github/refined-github

### Extension version

24.3.20

### Browser(s) used

Firefox

**Comment by fregante** [comment]
Likely related to:

- https://github.com/refined-github/refined-github/pull/7306

GitHub changed the variable color names so we should replace all of them at once as part of this issue. 

PR welcome 🙏

**Comment by melMass** [comment]
I'm going to try to setup a dev env for it, I couldn't quickly find how to test it locally but I might next week if no one did by then.
It seems like `js-navigation-item` doesn't exist anymore yet the `react-directory-commit-age` does have the proper style if I look from chrome tools but what is targeting `title` is now in a shadow-root:

![image](https://github.com/refined-github/refined-github/assets/7041726/d58bc24b-1204-421d-8755-223b9e5f62da)

**Comment by fregante** [comment]
They probably changed the DOM too

**Comment by ilike2burnthing** [comment]
Oddly it works when not signed in to GitHub (personal token or not, dark mode or light), and I can't see any difference in the HTML that would explain it.

**Comment by offensive-vk** [comment]
Same issue with Brave, Chrome in windows too.
