### ISSUE TITLE
Add commits list as a repo tab

### ISSUE THREAD

**Issue by yushiyangk** [refined-github/refined-github#7310]
### Description

It would be great if the [commits page](https://github.com/refined-github/refined-github/commits/main/) of a repo can be added as one of the repo tabs (alongside Issues, Pull Requests, etc.).

Commits are one of the core entities that we interact with when working with Git, but right now the page that lists them has to be accessed by going to the home page of a repo and clicking on an easy-to-miss link at the top right of the files list.

### Example URLs

https://github.com/refined-github/refined-github
https://github.com/refined-github/refined-github/issues
https://github.com/refined-github/refined-github/issues/1
etc.

**Comment by ilike2burnthing** [comment]
https://github.com/refined-github/refined-github/blob/main/source/features/more-dropdown-links.tsx
