### ISSUE TITLE
Performance issue on PRs with lots of changes

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7316]
Follows

- https://github.com/refined-github/refined-github/issues/7116
- https://github.com/refined-github/refined-github/pull/7315

If after v24.3.25 you still see performance issues, please "like" this issue.

**Please do not leave "me too" comments**

**Comment by Pajn** [comment]
I see performance issues in Firefox with 24.4.1 if I reload on the conversation page and then go to "files changed" but not if I reload directly on the "files changed" page. Manually disabling the features in #7315 solves it even if I start on the conversation page. The identify feature function only identified `locked-issue` and only disabling that one seems to solve it as well but I haven't tested on a PR with many comments, only many files.

**Comment by fregante** [comment]
> Manually disabling the features in #7315 solves it

I think this is because of:

- https://github.com/refined-github/refined-github/issues/6437

In short, the slowdown still exists because the _previous load_ still affects the new one on PR Files, where the feature is disabled.

PR welcome to change the solution in https://github.com/refined-github/refined-github/pull/7315 to use `asLongAs: [isChrome]` instead of `exclude: [isBadBrowserOnPrFiles]`

**Comment by Seregy** [comment]
I do see an improvement after completely disabling the features in the https://github.com/refined-github/refined-github/pull/7315.

But there seems to be another issue with some large PRs that causes the changes page to take forever to load completely. The top changes are visible, but on trying to scroll the page down I experience a ~15 seconds delay before seeing the next chunk. Continuing scrolling after that seems to work fine for some(not that big) PRs, but for some larger ones the loading just hangs for me. I've tracked the problem down to the `quick-mention` feature, it's noticeable when moving from the `Conversation` page to the `Files changed` one. Opening the `Files changed` page directly seems to work fine(I guess that makes sense, `quick-mention` shouldn't be enabled for that page)

**Comment by fregante** [comment]
24.4.9 was just released with @Seregy's fix 💙

I'll close this issue and open a new one in order to track the amount of people still affected. 

Sorry about this 🥹 🙏
