### ISSUE TITLE
`highest-rated-comment` - Missing border 

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7317]
### Description

<img width="409" alt="Screenshot 4" src="https://github.com/refined-github/refined-github/assets/1402241/bdb3563b-dd17-4cf9-96a9-9a8871e5fd0e">

Just for tracking purposes, it will be fixed by:

- https://github.com/refined-github/refined-github/pull/7313

### How to replicate the issue + URL

https://github.com/webpack-contrib/mini-css-extract-plugin/issues/216#issuecomment-407729606

### Extension version

24.2.8

### Browser(s) used

Safari

**Comment by Spurlos** [comment]
`--color-success-emphasis`, which should set the border color is missing from styles
![image](https://github.com/refined-github/refined-github/assets/667533/2c86b058-9518-4741-aeab-786181911968)
![image](https://github.com/refined-github/refined-github/assets/667533/af18ed88-67bd-41d1-9e1f-ebab0f3fcc57)
