### ISSUE TITLE
"Access your data on all sites" permission corrupts Google search result subtitles.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [refined-github/refined-github#7319]
1.	### **Description**
	
	When granted https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions?as=u&utm_source=inproduct#w_access-your-data-for-all-websites on https://koji.fedoraproject.org/koji/rpminfo?rpmID=38118194, https://www.google.com/search?client=firefox-b-d&q=wexextension.org+github causes:
	
	> ![image](https://github.com/refined-github/refined-github/assets/42837531/6dc0eb50-acd7-4862-a0f7-f4c433c0162f)
	
	Disabling and enabling that preference causes the problem to occur immediately (*sometimes* without page refresh) and reproducibly.
	
1.	### How to replicate the issue + URL
	
	1.	Install `cpe:/o:fedoraproject:fedora:40`.
		1.	Write https://download.fedoraproject.org/pub/fedora/linux/releases/test/40_Beta/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40_Beta-1.10.iso using `flatpak install https://dl.flathub.org/repo/appstream/org.fedoraproject.MediaWriter.flatpakref && flatpak update app/org.fedoraproject.MediaWriter/x86_64/stable --commit=08f95f0584ba56e427555192146ebe9f4e558521bff8588d7fa83998ad184b86`.
	1.	Enable https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions?as=u&utm_source=inproduct#w_access-your-data-for-all-websites for https://addons.mozilla.org/firefox/downloads/file/4252355/refined_github-24.3.20.xpi via `about:addons`.
		1.	Install https://addons.mozilla.org/firefox/downloads/file/4252355/refined_github-24.3.20.xpi.
			1.	Install https://koji.fedoraproject.org/koji/rpminfo?rpmID=38118194.
	1.	Visit https://www.google.com/search?client=firefox-b-d&q=wexextension.org+github.
	
1.	### **Extension version**
	
	https://addons.mozilla.org/firefox/downloads/file/4252355/refined_github-24.3.20.xpi
	
1.	### **Browser(s) used**
	
	https://koji.fedoraproject.org/koji/rpminfo?rpmID=38118194

**Comment by fregante** [comment]
> When granted

Yeah, don't grant it. This is not a bug. You're asking the extension to run on the wrong sites.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/refined-github/refined-github/issues/7319#issuecomment-2021743410

@fregante, because https://addons.mozilla.org/firefox/downloads/file/4253367/augmented_steam-3.1.0.xpi doesn't expose the *ability* to enable this permission via `about:addons`, per https://discourse.mozilla.org/t/how-to-ask-user-to-grant-permissions-for-access-your-data-for-all-websites-through-a-prompt-during-the-installation-process/110637/6, removing

```JS
permissions: ["activeTab"],
origins: ["<all_urls>"]
```

from your extension manifest should remediate this.

**Comment by fregante** [comment]
It's an optional permission. You enable it so you deal with the consequences. The permission must exist to support GitHub Enterprise users that enable the extension on each specific domain. It's not meant to run on all URLs
