### ISSUE TITLE
emphasize-draft-pr-label not working

### ISSUE THREAD

**Issue by asmeurer** [refined-github/refined-github#7320]
### Description

With emphasize-draft-pr-label enabled, the icon for draft PRs is not showing. For example

<img width="410" alt="image" src="https://github.com/refined-github/refined-github/assets/71486/426d712b-c079-4530-a6a1-991633540a79">

I've confirmed that disabling the feature fixes the problem. 

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/pulls (or any PR list with a draft PR)

### Extension version

24.3.20

### Browser(s) used

Chrome on macOS

**Comment by asmeurer** [comment]
Actually, highlighting the PR shows that the icon is there, but it is pure white. 
<img width="433" alt="image" src="https://github.com/refined-github/refined-github/assets/71486/5ff135b8-7ad4-417b-95ad-9076e31512f4">

**Comment by fregante** [comment]
This will likely be fixed by https://github.com/refined-github/refined-github/pull/7313

**Comment by fregante** [comment]
Not fixed :(

**Comment by fregante** [comment]
Fixed by https://github.com/refined-github/refined-github/pull/7313
