### ISSUE TITLE
Sort Pull Requests by Label Size (e.g., size/xxs to size/xxl) or Diff Line Count

### ISSUE THREAD

**Issue by cprayer** [refined-github/refined-github#7321]
## What is it? 
A sorting feature that allows users to organize the files in a pull request either by the number of lines changed (in ascending order) or by size labels assigned to each file. This feature aims to prioritize files for review based on their complexity or size, making the review process more structured and efficient.

## Why is it needed? 
Large pull requests can be overwhelming, with varying file sizes and changes making it difficult to know where to start. A sorting feature based on either diff line count or size labels will enable reviewers to tackle changes systematically, starting with the smallest or least complex files. This approach could reduce the initial review barrier and ensure more thorough and efficient code reviews.

### Example URLs

![image](https://github.com/refined-github/refined-github/assets/24709996/09db81dd-64ca-4877-bf7e-d4720af0b69b)

**Comment by fregante** [comment]
Sorting isn't possible in an extension, it can only show what the server returns. There's no such sorting available in GitHub.

**Comment by cprayer** [comment]
@fregante That's sad. 😢 I hope GitHub supports it someday.

**Comment by fregante** [comment]
Yeah, you'd have to contact GitHub and ask
