### ISSUE TITLE
`repo-avatars` - Wrong organization icon

### ISSUE THREAD

**Issue by LitoMore** [refined-github/refined-github#7322]
### Description

It shows a bot avatar when the bot has the same display name.

### How to replicate the issue + URL

See this link below:

- https://github.com/simple-icons/simple-icons/pull/10728.

### Extension version

24.3.20

### Browser(s) used

Safari, Chrome

**Comment by fregante** [comment]
Due to

https://github.com/refined-github/refined-github/blob/3c2d8947a6fe96098db6aae63168fdec5e9f91dd/source/github-helpers/get-user-avatar.ts#L7-L11
