### ISSUE TITLE
Pull requests/ Issue sidebar

### ISSUE THREAD

**Issue by oSumAtrIX** [refined-github/refined-github#7323]
### Description

Sometimes, you open a PR or issue and want to switch to another. This requires you to switch to the PR or issue tab and then back to another PR or issue. This can be simplified by including a sidebar of PRs and problems next to an open PR or issue, reducing the need to return to the PR or issue tab.

### Why this feature does not make sense

- When you work on an issue or PR, you may unlikely be interested in other PRs or topics.
- The sidebar is a significant addition to the PR or issue page, which can be offputting
- On small screens, the sidebar may not fit
- One may open multiple browser tabs

### Why this feature makes sense

- If you are assigned to multiple PRs or issues and need to leave a review or comment on them, switching between them is trivial
- Sometimes, you open a PR or issue without visiting the issues or PR page, which means you never get to switch tabs or open multiple PR or issue at once (such as via mail)

While I just came up with one reason it makes sense, I believe it weighs more than the other three.

### Example location of the sidebar (on a 27" screen)

![image](https://github.com/refined-github/refined-github/assets/13122796/9fbd56a7-e592-43f3-bb03-6c9fbd65b56d)

### Example URLs

In issues: https://github.com/refined-github/refined-github/issues/1
In PRs: https://github.com/refined-github/refined-github/pull/7318

**Comment by fregante** [comment]
This would be a whole new extension, it can't be part of Refined GitHub, see:

https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22

**Comment by oSumAtrIX** [comment]
I can see where you are coming from, and as depicted, that may be the case. Technically, a list of HREFs would be sufficient as well to jump from issue to issue or PR to PR, but it would miss useful features such as filtering as seen by the issues and PR page, but if this still is too much to be part of Refined GitHub I understand.
