### ISSUE TITLE
Add the ability to jump to the most recent release as of a comment or issue

### ISSUE THREAD

**Issue by Zealot-311** [refined-github/refined-github#7327]
### Description

The ability to jump to the most recent release as of a given date would be very helpful. As it is now, if I want to find this, I need to go to the releases tab and search through manually until I find it. This would be in the same place as the link to browse the repository at a certain date given by a comment or issue.

### Example URLs

https://github.com/SimonHalvdansson/Harmonic-HN/issues/34

**Comment by fregante** [comment]
You can reach a comment's release:

1. Click "View repo at this time" (added by `comments-time-machine-links`)
2. Click "History" to see the commits
3. Scan the list for any releases appearing in the list (added by `tags-on-commits-list`)

Not great but it gets you there.


---

I'd love to see what you're asking but it requires querying 100 tags at a time from the API until the desired date. You can see that `comments-time-machine-links` is already complex as it is.

If anyone finds an API to get the exact release available on a specific date, please leave a comment.
