### ISSUE TITLE
Ghost Notification Fix

### ISSUE THREAD

**Issue by ShayBox** [refined-github/refined-github#7332]
### Description

If a repo/gist was deleted before you could mark a notification as read/done it'll be stuck forever.  
GitHub doesn't seem interested in fixing this issue, [see here](https://github.com/orgs/community/discussions/6874#discussioncomment-8879321)

Could a tweak with refined github be made to add a mark all read button which fixes this?  
This can be done with a network request, examples in the linked community discussion.

### Example URLs

https://github.com/notifications

**Comment by fregante** [comment]
This is a tiny and rare bug and it's not in the UI. You should use the API call provided in that discussion

**Comment by ShayBox** [comment]
It's not rare, people mass ping users which end up in the repo/gist being deleted and the notification icon on the top right of the page being stuck for a lot of people, and fairly often once you're in the mass ping bot list.

**Comment by fregante** [comment]
It's rare as far as Refined GitHub is concerned. Extensions don't fix one-time bugs, but only bugs that appear every day to most people. This isn't it.
