### ISSUE TITLE
More customizations for notifications?

### ISSUE THREAD

**Issue by standardAI** [refined-github/refined-github#7333]
Great tool!
Is it possible to see notifications only when an Issue, PR, or Discussion is *opened*?
@fregante

**Comment by yakov116** [comment]
I believe this is out of the scope refined-github, these customizations would need to be done on GitHub's end.

**Comment by fregante** [comment]
I don’t think this piece of information is available via API and definitely not on the page. The reason for a "New issue" notification is always "repo subscription", just like all others.

**Comment by standardAI** [comment]
I couldn't understand well, could you please elaborate?

**Comment by standardAI** [comment]
I couldn't understand well, could you please elaborate?
@fregante @yakov116
