### ISSUE TITLE
`link-to-changelog-file` : add link to changelog on tag and release UI cards

### ISSUE THREAD

**Issue by RupertBarrow** [refined-github/refined-github#7339]
### Description

The `link-to-changelog-file` currently adds a link at the top of the pages which list all releases and all tags. It currently links to the changelog file on the main/master branch.

When one manages multiple release branches, one needs a link to the changelog file of each release.
I suggest you add a changelog link to each UI car for an individual release of a tag, at the top of the card next to the release or tag number.
This link would point to the changelog file in the branch of the release or tag.

Nice to have : display a disabled and crossed out changelog button if the branch has been deleted.

### Example URLs

https://github.com/d3/d3/releases

**Comment by fregante** [comment]
Raga/releases are global on GitHub, so we follow that
