### ISSUE TITLE
Add option to distinguish review required statuses when I've already reviewed the PR.

### ISSUE THREAD

**Issue by Swiddis** [refined-github/refined-github#7340]
### Description

When working on repositories that have a high PR throughput and require 2+ reviews per PR, it's hard to tell at a glance where my reviews are needed. Currently all PRs that need more reviews have a "Review required" label, regardless of if I've reviewed them or not.

![Current view](https://github.com/refined-github/refined-github/assets/31739405/a917a55f-b4d4-450d-9af6-46756a855dc2)

I'd like to propose introducing another label along the lines of "Pending reviews", to distinguish cases where I've already reviewed a PR and we're waiting for someone else to review it. The new label would be applicable when I've reviewed a PR but it's still waiting for someone else to review it, and for PRs I've authored. The "Review required" label would be reserved for PRs I still need to review.

![Proposed view](https://github.com/refined-github/refined-github/assets/31739405/428e1178-1d88-4797-95dd-1e0ed6d64752)

The information is already available when hovering over the PR, e.g. when I've approved a PR it says "You approved this pull request" at the bottom of the pop-up while when I haven't it says "You have a pending review request". This feature request is to have the information visible in the PR list directly.

![grafik](https://github.com/refined-github/refined-github/assets/31739405/07c0f1ba-6d91-4e48-b5b5-905fb5bbd4dc)

### Example URLs

https://github.com/opensearch-project/dashboards-observability/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc or any other repository that has a 2 person rule for PR reviews.

**Comment by fregante** [comment]
The list is very crowded and very often we get requests to add more information to it. We can't. 

You can already request the PRs that are awaiting review from you with GitHub's own filters

![image](https://github.com/refined-github/refined-github/assets/1402241/97755ed6-4b5b-47b3-81d1-c6fcc895cf4f)
