### ISSUE TITLE
Duplicated `show/hide whitespace` and `Switch to unified view` overflow on the view.

### ISSUE THREAD

**Issue by shiipou** [refined-github/refined-github#7341]
### Description

The drop down menu with the split view or unified view didn't display well in the latest version of the extension and GitHub.

With the extension enabled : 

![image](https://github.com/refined-github/refined-github/assets/38187238/da97c141-774e-4e00-8761-631222a635da)

![image](https://github.com/refined-github/refined-github/assets/38187238/8fc00a83-6e16-40ca-981d-68a60fad2006)

With the extension disabled : 

![image](https://github.com/refined-github/refined-github/assets/38187238/1bbb4b79-4e7b-4d4f-9625-55a377f1b72b)

![image](https://github.com/refined-github/refined-github/assets/38187238/b11dc525-48e0-4121-b3c3-a00e70522e6a)

### How to replicate the issue + URL

[dofigen#175-bug-fail-on-unknown-fields](https://github.com/lenra-io/dofigen/pull/176/files?diff=unified&w=1)

### Extension version

24.4.9

### Browser(s) used

Firefox 125.0.2 (64-bit)

**Comment by fregante** [comment]
Can't repro in any browsers. The extension should turn that dropdown into two, when the window is wide enough:

<img width="460" alt="Screenshot 3" src="https://github.com/refined-github/refined-github/assets/1402241/4fef15b5-1424-4d20-88cb-44c305145d5e">


Do you have any other extensions enabled?
