### ISSUE TITLE
Ability to copy the source diff (raw file)

### ISSUE THREAD

**Issue by x9136** [refined-github/refined-github#7342]
### Description

During reviews, I copy svgs and paste them into Figma to check. It is often impossible to select the source diff with two clicks, because it is on different lines. It is not convenient to select with the mouse, because you need to aim accurately and move it down the code for a long time.

The 1-click option will be best, so I suggest simply duplicating the copy button from the "View file" page.
![1 click option](https://github.com/refined-github/refined-github/assets/60105060/8f4a25f6-130d-424a-96bf-b0b6d1c6b5b8)

### Example URLs

https://github.com/LawnchairLauncher/lawnicons/pull/1927/files#diff-11c628f0ca4825f61a3b8b2ee690e57352ce4c4dd3cccc204b74eb599f684e32

**Comment by fregante** [comment]
> During reviews, I copy svgs

I think that's a rare action for Refined GitHub. Perhaps I suggest:

1. alt-click "View raw" in the dropdown
2. drag the downloaded file to Sigma

<img width="510" alt="Screenshot 2" src="https://github.com/refined-github/refined-github/assets/1402241/53ece0ba-8f80-4b8a-81e2-0e8c9a6da0af">

**Comment by x9136** [comment]
> that's a rare action

Not quite. There are several PRs per month with dozens of icons. For each one, you have to do 4 actions (Open the menu -> View raw-> Copy -> Close the tab) instead of 1, that is, 40-80 instead of 10-20. Sometimes there are requests for 50+ icons.

Then I'll wait to see what GitHub does about it.

**Comment by fregante** [comment]
> > that's a rare action
> 
> Not

We have 100k users and copy-pasting code from PRs is likely not how most people deal with code. I'm sure it's a daily occurrence for you but not for the remaining 99,999 users, so it's "a rare action **for Refined GitHub**"
