### ISSUE TITLE
Default to own fork on "Create pull request" if it exists and not a maintainer

### ISSUE THREAD

**Issue by altrisi** [refined-github/refined-github#7343]
### Description

Currently, when you click the `Create pull request` button in the pulls tab, it'll default to comparing across branches on the same repository. If you want to use a branch from your fork, you have to make multiple clicks, search the fork list, wait for a reload and then choose the branch.

If you don't work on the repository, you most likely want to create a pull request with a branch from your fork instead of between branches on the same repository. Refined GitHub could default to the fork in that case.

### Example URLs

https://github.com/refined-github/refined-github/pulls

**Comment by fregante** [comment]
We can't change the current behavior. I think if you're already working on your own repo, you should create the PR from there, as the GitHub flow suggests. They already show the one-click button when you're on your repo:

<img width="409" alt="Screenshot 3" src="https://github.com/refined-github/refined-github/assets/1402241/235e3130-77e4-41fd-8a16-ad88ae9a1271">
