### ISSUE TITLE
Keyboard shortcut to edit Pull Request description in Conversation tab

### ISSUE THREAD

**Issue by martinssipenko** [refined-github/refined-github#7344]
### Description

Add an `e` keyboard shortcut in the Pull Request Conversation tab to enter into PR description edit more.

Many other tools (for example Atlassian products) use this hotkey which removed a few mouse clicks.

### Example URLs

https://github.com/refined-github/refined-github/pull/7335

**Comment by fregante** [comment]
We try to avoid adding too many shortcuts because there's always a chance of conflict.

There's a trick though:

1. Press `j` (it should focus the first comment / PR description)
2. Click `quick-comment-edit`
