### ISSUE TITLE
No response while opening large file or PR

### ISSUE THREAD

**Issue by AurevoirXavier** [refined-github/refined-github#7345]
### Description

No response while opening large file or PR

### How to replicate the issue + URL

Open and scroll or click blame: https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/balances/src/lib.rs

### Extension version

24.4.9

### Browser(s) used

Chromium Engine Version 124.0.6367.92

**Comment by fregante** [comment]
Tracked in https://github.com/refined-github/refined-github/issues/7331
