### ISSUE TITLE
Option to toggle &type=source when clicking on Repositories 

### ISSUE THREAD

**Issue by sorpdev** [refined-github/refined-github#7346]
If you click on the Repositories tab on either an user or organization there's always the &type=source added.

This also happens if you use the side bar (if you click on your profile picture in the upper right corner) and click on "Your repositories"

Is there at the moment an option to disable this feature?

**Comment by fregante** [comment]
Yes, it's called `hide-user-forks`

**Comment by sorpdev** [comment]
Thanks for the quick help @fregante.

But wouldn't it be better to mention the word "source" or "type, source" in the description of the feature? 
So it would show up in the features menu if you're searching for the words.

Would've helped me at least 😅
