### ISSUE TITLE
`hide-user-forks` description improvement

### ISSUE THREAD

**Issue by sorpdev** [refined-github/refined-github#7348]
### Improvement of `hide-user-forks` description

Wouldn't it be better to mention words like "source",  "type" or similar in the description of the [`hide-user-forks`](https://github.com/refined-github/refined-github/blob/main/source/features/hide-user-forks.tsx) feature?
So it would be easier to find the corresponding feature if someone wants to disable it and doesn't know which feature it is.

I disliked the feature and wanted to disable it but wasn't able to find it in the features menu (https://github.com/refined-github/refined-github/issues/7346). I think including some of the words I named would be a good improvement

### Example URLs

https://github.com/refined-github/refined-github

**Comment by qyurila** [comment]
+1, including 'source', 'type', 'filter' or 'repo tab' in the description would help a lot IMO.

**Comment by fregante** [comment]
We have a “Identify feature” for this purpose. When I read the current description I find that it explains exactly what it does and I don’t see how to naturally fit those keywords in there. If you have suggestions for the description I’ll welcome a PR to edit the readme file though.
