### ISSUE TITLE
Option to hide repositories and notifications of some organizations I belong to

### ISSUE THREAD

**Issue by FezVrasta** [refined-github/refined-github#7352]
### Description

I think most people nowadays use multiple browser profiles to separate work and personal browsing sessions.

One problem I have is that when I open GitHub, no matter what browser profile I use, I see all the organizations I belong to, included their notifications, repositories, etc...

It would be very useful if Refined GitHub could allow to hide some organizations so that I can only show notifications and repositories from a given org when I browse with my work profile, and don't see the orgs' stuff when I use the personal profile.

### Example URLs

https://github.com/notifications

**Comment by fregante** [comment]
1. If you want to separate your work and other profiles, I think it's best you create two profiles
2. Refined GitHub does not implement large features that require UI. Here for example the repo/org picker would be comparatively large enough on its own, let alone the actual logic to filter the noise out.
