### ISSUE TITLE
`table-input` causes overflow

### ISSUE THREAD

**Issue by sebastiaanspeck** [refined-github/refined-github#7353]
### Description

Buttons that do not fit the line on mobile are placed on a newline in the Editor which makes them non-clickable
![IMG_2351](https://github.com/refined-github/refined-github/assets/12570668/284175ee-8c03-4d68-8b65-f938b13ddf12)

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/issues/new?assignees=&labels=bug&projects=&template=1_bug_report.yml

### Extension version

24.2.8

### Browser(s) used

Safari iOS

**Comment by fregante** [comment]
I think this has been fixed in Chrome but we haven't released for Safari in a while. I'll try to work on Refined GitHub a bit this month and release a new version everywhere

**Comment by fregante** [comment]
I fixed this bug on `collapsible-content-button` but the same fix didn't work on `table-input`. Maybe I left something out.

PR welcome because this is a useful feature, but I disabled it via hotfix for now because this bug is very visible and annoying.

**Comment by fregante** [comment]
Fixed by https://github.com/refined-github/refined-github/pull/7931, but only on the new input fields. We'll just have to wait for GitHub to enable them everywhere
