### ISSUE TITLE
The draft icon for PR’s is invisible when using dark mode

### ISSUE THREAD

**Issue by sebastiaanspeck** [refined-github/refined-github#7354]
### Description

The draft icon for PR’s is invisible when using dark mode

![IMG_2353](https://github.com/refined-github/refined-github/assets/12570668/258388f2-71f8-4beb-9447-3c2fbdbaa29f)

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

### Extension version

24.2.8

### Browser(s) used

Safari iOS, Safari macOS

**Comment by fregante** [comment]
This was fixed. It's just that Safari hasn't seen updates in a while. We'll do it this month
