### ISSUE TITLE
Filter for forks that are ahead

### ISSUE THREAD

**Issue by moritz-t-w** [refined-github/refined-github#7359]
### Description

Currently, looking for forks that differ from upstream is very annoying. You end up having to go through each fork. Filtering by `Active` doesn't help in the case of a fork having had pushes in the past, the contents of which, have however since been merged into upstream.
I would love to get an additional client side filter option to only show forks that have differences to the upstream.
![Mockup](https://github.com/refined-github/refined-github/assets/90388353/a6228ba8-d6f5-4d4b-85d5-6d11b6a1c116)

### Example URLs

https://github.com/refined-github/refined-github/forks

**Comment by fregante** [comment]
You might like https://useful-forks.github.io/
