### ISSUE TITLE
Editable upload path

### ISSUE THREAD

**Issue by aaronliu0130** [refined-github/refined-github#7361]
### Description

When uploading files, I wish we could customize the folder we're uploading to. The screenshot shown below would upload to the "winget-pkgs/manifests/w/Waterfox/Waterfox/G6.0.13" folder.

### Example URLs

![image](https://github.com/refined-github/refined-github/assets/11874211/299c0557-dc1d-41a4-a3a4-38498dbe64b1)
<https://github.com/aaronliu0130/winget-pkgs/upload/waterfox'14/manifests/w/Waterfox/Waterfox/G6.0.13>

**Comment by fregante** [comment]
This would be nice but we can't reliably reimplement the whole widget in Refined GitHub. I don't immediately see a way to reuse GitHub's own widget, but if you do, please open a PR
