### ISSUE TITLE
Tags in commit list

### ISSUE THREAD

**Issue by SMillerDev** [refined-github/refined-github#7362]
### Description

When viewing the commit list I often want to know when in that list the last tag happened. Unfortunately, that’s not possible in native GitHub. So it would be great if you could add it.

### Example URLs

https://github.com/refined-github/refined-github/commits/main/

**Comment by fregante** [comment]
We already have a feature named exactly that: https://github.com/refined-github/refined-github/blob/main/source/features/tags-on-commits-list.tsx

Did you set the token in the options?

**Comment by SMillerDev** [comment]
Oh sorry, I only looked through the readme and didn't find it. That's great, thanks!
