### ISSUE TITLE
`clean-conversation-sidebar`: incorrectly hides "open in workspace"

### ISSUE THREAD

**Issue by pengx17** [refined-github/refined-github#7363]
### Description

`clean-conversation-sidebar`: incorrectly hides "open in workspace" on github issue page

<img width="1079" alt="image" src="https://github.com/refined-github/refined-github/assets/584378/dec97570-91a7-4e3b-b699-095ab476bb4a">

### How to replicate the issue + URL

Opening a github issue with Copilot Workspace enabled, there is no "open in workspace" shown in the sidebar

### Extension version

24.4.9

### Browser(s) used

Arc

**Comment by pengx17** [comment]
should be fixed by #7350

**Comment by fregante** [comment]
Yes
