### ISSUE TITLE
Customize default issue filters to exclude specific labels

### ISSUE THREAD

**Issue by sedghi** [refined-github/refined-github#7368]
Is there a way to customize the default filters I see whenever I click on the issues tab? 

For example, I would like to always filter out a specific label from the issues.

![CleanShot 2024-05-22 at 14 13 38@2x](https://github.com/refined-github/refined-github/assets/7490180/0e734585-1f10-4209-ae1b-eb2b245fa412)

**Comment by fregante** [comment]
Not in Refined GitHub, maybe that can be a browser bookmark
