### ISSUE TITLE
`pull-request-hotkeys` works intermittently

### ISSUE THREAD

**Issue by ElijahLynn** [refined-github/refined-github#7369]
### Description

I would like to press a keyboard shortcut to quickly go to the conversation tab from e.g. the /files tab. Sumtim + Sumtim + C (for Conversation) would make the most sense to me. 

### Example URLs

* https://togithub.com/refined-github/refined-github/pull/8130

**Comment by ElijahLynn** [comment]
I'm noticing intermittent behavior on some PRs vs other PRs. Something is off, as I just tested this on https://github.com/refined-github/refined-github/pull/3500/files and I'm seeing it work now. 

From Conversation tab (1):
* g + 2 takes me to "commits"
* g + 3 takes me to "checks"
*** g + 4 does not take me to "files**

From Commits tab (2):
* g + 1 takes me to "conversation"
* g + 3 takes me to "checks"
* g + 4 takes me to "files

From Checks tab (3):
* g + 1 does not take me to "conversation"
*** g + 2 does not take me to "commits"**
*** g + 4 does not take me to "files**

From Files tab (4):
* g + 1 takes me to "conversation"
* g + 2 takes me to "commits"
* g + 3 takes me to "checks"

**Comment by ElijahLynn** [comment]
I'm already seeing a bunch of errors:

![image](https://github.com/refined-github/refined-github/assets/1504756/1c5c581a-28ad-47b6-ad05-cec1be31b19e)

**Comment by fregante** [comment]
> I'm already seeing a bunch of errors:

The errors are all about your missing token.

> I'm noticing intermittent behavior on some PRs vs other PRs

Same here, even on the same PR across reloads. I turned this into a bug report. This is most likely a race condition (or GitHub A/B testing some classes)

**Comment by louis-jaris** [comment]
Is it possible to also add the `g 1`, `g 2` etc. shortcuts in the help (`shift ?`) so that folks knows about it? 🙏

I spent 30 mins trying to find that shortcut 😅

**Comment by ElijahLynn** [comment]
> Same here, even on the same PR across reloads. I turned this into a bug report. This is most likely a race condition (or GitHub A/B testing some classes)

Thank you for the sanity check!!!


> The errors are all about your missing token.

Thanks, didn't even realize I needed one, I just added a token.

**Comment by gabrielguimaraes** [comment]
It's not working for me.
I am trying using:

* g + {number}

and nothing happens.
Are these hotkeys still working for pull request page?
