### ISSUE TITLE
Meta: Switch from Prettier to dprint for formatting

### ISSUE THREAD

**Issue by g-plane** [refined-github/refined-github#7372]
Are there any considerations about switching the formatter from Prettier to [dprint](https://dprint.dev/)? dprint is a plugins-based formatter, and it's written in Rust so it's fast.

But speed and performance isn't the most important factor, dprint is highly configurable while Prettier is opinionated. So, code styles can be easily customized to get satisfication.

The reason why I recommend dprint is that I've noticed you opened an issue about the bug of  formatting CSS selectors with comments in Prettier: https://github.com/prettier/prettier/issues/15356 . dprint doesn't have official plugins for formatting CSS at this moment, but here is a third-party one: [Malva](https://github.com/g-plane/malva).

Malva is also highly configurable and customizable, and it provides more options than Prettier. Also, it works with comments better than Prettier. For the bug you caught in Prettier, Malva works well: [Malva playground](https://malva-play.vercel.app/?code=H4sIAAAAAAAAA2WOQQ6CMBRE1%2FxT%2FDUR2NetLo1naOkUflJpUwvaGO%2BuC4wGZznz8jKtJt6kaq0412Tcc9PD%2B3%2BAvwSta1f%2FEkcrmaMesOOYgtHGF55jHy4yDXw4nxgLUrmNSGCqu9WhlIEL7%2BpB1ce0yFWMeMlF8ebIKNZi2tOTXlJi5W7FAAAA&config=H4sIAAAAAAAAA6vmUlBQykzPyy9Kdc7PzU3NK3HJLEpNLsksS1WyUlDKTcwpS9SFyCtx1QIAA%2FFtiS4AAAA%3D&syntax=css). Malva also fixes some other bugs in Prettier, such as https://github.com/prettier/prettier/issues/16232#issuecomment-2118609637 .

Feedback is welcomed.

**Comment by Jayllyz** [comment]
[Biome](https://biomejs.dev/) could replace both prettier and eslint :eyes:

**Comment by fregante** [comment]
Thank you but prettier is good enough for now. 

Biome doesn't have compatibility with eslint plugins, which we have a lot of.

**Comment by fregante** [comment]
I gave it a try in https://github.com/refined-github/refined-github/commit/6210d1ee10a3a98344a0e00c779501a1e1567674 but I think it's a downgrade in a few spots, especially with comments being wrapped to the next line, or moved before the selector.

This was done for https://github.com/refined-github/refined-github/pull/7553

**Comment by g-plane** [comment]
Quotes can be configured.

**Comment by fregante** [comment]
Would you be open to send a PR? Last week I had two issues:

- :has(), :is() wrapping
- comments position

If the first one can be fixed to maintain what we expect, we can probably figure something out with the comments positioning. Biome actually moved some comments _before_ the comma and that made sense, for example.

```diff
- a, /* comment */
+ a /* comment */,
b {

}
```

But in the last dprint PR, the formatting in this case was changed to this instead, which isn't what we expect:

```css
a,
/* comment */ b {

}
```

**Comment by fregante** [comment]
We're only using Prettier for CSS and GQL for now. I think GQL would still need Prettier because I don't see it (via dprint plugin)

https://dprint.dev/plugins/

**Comment by g-plane** [comment]
- Can you give me some examples about `:has()` and `:is()`? (expected results)
- Recently I'm fixing comments problems.
- dprint has a Biome plugin and Biome supports GraphQL, so we can format GraphQL indirectly.
- dprint also has a Prettier plugin. If you don't like Biome, you can still use Prettier to format GraphQL. Compared to using Prettier directly, running Prettier in dprint will be faster because files will be formatted in parallel.

**Comment by fregante** [comment]
- the expected result is what we have now, more or less. The wrong result is when multiple long selectors are on a single line inside is(), as shown in my last comment
- yes GQL would need to use biome or prettier, I had also set biome for GQL without issues in my PR. Prettier would be preferred since it's part of our dependencies anyway (via XO)

**Comment by g-plane** [comment]
Just enable `"linebreakInPseudoParens"` option, and the result of `:is()` and `:where()` can be better. [playground](https://malva-play.vercel.app/?code=H4sIAAAAAAAAA7PKLNaITkksSdTNTdFNKi0pyc%2BzVcpNzSvJzM9TitVRwJArSk3DKp6RmpiSWqRrjFUyKT8nBatEZkliTmayUqymVV5%2BiYZVWn5yabGmQnUtAKfcXIuXAAAA&config=H4sIAAAAAAAAA6vmUlBQysnMS00qSk3M9swLKE4tTckPSCxKzStWslIoKSpN5aoFAFs%2BU4clAAAA&syntax=css)

**Comment by g-plane** [comment]
Malva [v0.6.0](https://github.com/g-plane/malva/releases/tag/v0.6.0) has been published with many comments improvements. Would you like to try it again? Don't forget to configure Malva as the `dprint.json` example below:

```json
{
  "malva": {
    "quotes": "preferSingle",
    "blockSelectorLinebreak": "always",
    "linebreakInPseudoParens": true
  }
}
```

**Comment by Eveeifyeve** [comment]
> * Can you give me some examples about `:has()` and `:is()`? (expected results)
> * Recently I'm fixing comments problems.
> * dprint has a Biome plugin and Biome supports GraphQL, so we can format GraphQL indirectly.
> * dprint also has a Prettier plugin. If you don't like Biome, you can still use Prettier to format GraphQL. Compared to using Prettier directly, running Prettier in dprint will be faster because files will be formatted in parallel.

I had a look at this comment unfortunatly it seems like graph ql formatter is unreleased for biome so dprint can't support as it's not released.
