### ISSUE TITLE
`github-actions-indications` - CSS is broken

### ISSUE THREAD

**Issue by 134130** [refined-github/refined-github#7389]
### Description

- `github-actions-indications`'s CSS is broken

### How to replicate the issue + URL

- See disabled workflow
  - <img width="326" alt="image" src="https://github.com/refined-github/refined-github/assets/50487467/25ec65d0-0491-4c29-85f8-2ada9956f6c1">
  - https://github.com/134130/134130/actions/workflows/blank2.yml
- See manual triggerable workflow
  - <img width="332" alt="image" src="https://github.com/refined-github/refined-github/assets/50487467/b7db6f7c-1d5a-41f9-b72f-afe20c59b86d">
  - https://github.com/refined-github/refined-github/actions/workflows/release.yml

### Extension version

24.4.9

### Browser(s) used

Chrome

**Comment by fregante** [comment]
So they added a native "Disabled" text

<img width="332" alt="Screenshot 1" src="https://github.com/refined-github/refined-github/assets/1402241/6b9c5a8b-6060-4ecb-93af-3b18b21f45eb">

I'll:

- drop our "disabled" icon
- check if we can preserve the "play" icon on disabled workflows
