### ISSUE TITLE
Breaks the new github workspaces on Issues

### ISSUE THREAD

**Issue by krschacht** [refined-github/refined-github#7390]
### Description

I have given Copilot Workspace access to my organization. Now, when I got to an open pull request I have a "Open in Workspace" button in the right column, and I'm also able to go the Copilot Workspace Dashboard and create a New Session for my repo from there. However, I do not have this button on any Issues that I open. This is the primary starting point for me so I'd love to get the button working there.

The docs here show it as the first example: https://github.com/githubnext/copilot-workspace-user-manual/blob/main/getting-started.md

@terkel Multiple users have this issue ^
rahulpandita — 05/28/2024 11:01 AM

Are you using a any chrome extension that alter the GitHub UI like [ https://github.com/refined-github/refined-github] , that may interfere with rendering the button on issues page? 

Ahhh, refined github! I disabled it and now the button appears.

### How to replicate the issue + URL

Activate Github Workspaces, apply it to a project, and then visit any issue within that project. This project has Workspaces already activated so here is a random Issue.
https://github.com/AllYourBot/hostedgpt/issues/236

### Extension version

Not sure, I just uninstalled

### Browser(s) used

Chrome

**Comment by fregante** [comment]
This was just fixed in v24.6.2, make sure you're using that version
