### ISSUE TITLE
`align-issue-labels` - CI check icon is too close to the title

### ISSUE THREAD

**Issue by InSyncWithFoo** [refined-github/refined-github#7398]
### Description

The following screenshots and the red rectangle markers have exactly the same size. The latter are placed at the exact same position relative to the top left corner of their screenshots.

Enabled:

![Extension enabled](https://github.com/refined-github/refined-github/assets/122007197/82e1151c-aeb8-464c-8518-1d9a58f1e427)

Disabled:

![Extension disabled](https://github.com/refined-github/refined-github/assets/122007197/4e7f9a61-b390-4c33-bf9e-15c220a5a766)

### How to replicate the issue + URL

This bug can be found on PR pages (e.g. [this one](https://github.com/refined-github/refined-github/pulls)).

### Extension version

24.6.2

### Browser(s) used

Chrome 125.0.6422.142

**Comment by fregante** [comment]
I don't see any "GitHub Action button" in that screenshot, also there are no labels for `align-issue-labels` to align

**Comment by fregante** [comment]
Great, thank you for clarifying!
