### ISSUE TITLE
Personal token validation in options page doesn't work for GHE

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#7405]
### Description

A minor issue, validation of personal token in options page doesn't work for GitHub Enterprise, even if a valid token is inputed and features do actually work, it still shows as "Bad credentials":

<img width="424" alt="Screenshot 2024-06-05 at 18 50 24" src="https://github.com/refined-github/refined-github/assets/44045911/983fbd8c-4d80-4366-be1e-57cc82531c9d">

The cause seems to be the validation still (mistakenly) being done via `api.github.com` on GHE:

<img width="534" alt="Screenshot 2024-06-05 at 18 51 38" src="https://github.com/refined-github/refined-github/assets/44045911/a5abb4be-e3b6-417a-bfc9-2349b6099482">

### How to replicate the issue + URL

`chrome://extensions/?options=hlepfoohegkhhmjieoechaddaejaokhf` 🤷

### Extension version

24.6.2

### Browser(s) used

Chrome

**Comment by fregante** [comment]
Should be fixed by https://github.com/refined-github/refined-github/pull/7388 in the next release

**Comment by fregante** [comment]
Should be fixed by https://github.com/refined-github/refined-github/pull/7388 in the next release

**Comment by kidonng** [comment]
Ah yes, was just looking at related code and wondering how could this bug exist. Guess I was absent from developing RGH for too long and forgot to test on `main` first 😂

I will close this and link the PR.
