### ISSUE TITLE
`restore-file`: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

### ISSUE THREAD

**Issue by garyhtou** [refined-github/refined-github#7410]
### Description

<img width="481" alt="image" src="https://github.com/refined-github/refined-github/assets/20099646/ebe8b822-7e48-41e4-a1bb-8826fd4f6b85">

```
Error: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4079:43
    at base64ToString (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4080:8)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:8662:32
    at async showToast (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:5593:40)
    at async HTMLHtmlElement.handleClick (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:8652:9)
```

### How to replicate the issue + URL

1. Go to any Pull Request (e.g. https://github.com/garyhtou/garyhtou/pull/1/files)
2. Open the meatball menu (three dots) for any file
    <img width="538" alt="image" src="https://github.com/refined-github/refined-github/assets/20099646/e25abc0c-7120-47c4-b326-55c0cf1001ab">
3. Click the `Discard Changes` button
    <img width="263" alt="image" src="https://github.com/refined-github/refined-github/assets/20099646/fa4bc5b9-618b-4e4a-881d-96d3f639d6bc">

### Extension version

24.6.2

### Browser(s) used

Arc. Version 1.46.0 (50665). Chromium Engine Version 125.0.6422.142

**Comment by fregante** [comment]
Did the file that failed have any UTF-8 characters?

**Comment by fregante** [comment]
I can confirm that it's broken due to 

- UTF-8. I can't restore https://github.com/refined-github/sandbox/pull/16/files#diff-4030f0c0b99ba5e189b6fe295448a8ca31ca589a55930175de18032545c11501 because the previous version contains an emoji
- that PR. If I check out the commit before it, it works
