### ISSUE TITLE
`comment-on-draft-pr-indicator`: Main body comment button not modified

### ISSUE THREAD

**Issue by Jiralite** [refined-github/refined-github#7438]
### Description

The comment button's label is unaltered in the main body of a pull request. The screenshot example in the feature shows it works, so either it got removed or the example needs to be updated.

Not entirely sure how it worked before, but the class is not present here:

https://github.com/refined-github/refined-github/blob/6302d1e0c78ee4126187008c42bbf068c819dd8a/source/features/comment-on-draft-pr-indicator.tsx#L11-L17

Adding `'.btn-primary'` modifies the button's label, but I am not sure if this is the proper resolution.

### How to replicate the issue + URL

1. Open a draft pull request (https://github.com/refined-github/sandbox/pull/7)
2. See the comment button

### Extension version

24.6.9

### Browser(s) used

Arc, Firefox

**Comment by fregante** [comment]
Yea the feature is supposed to alter the buttons. 

I've been wanting to change this feature and add a banner like `netiquette` does.

**Comment by fregante** [comment]
Oh you meant this one, right?

<img width="348" alt="Screenshot 2" src="https://github.com/refined-github/refined-github/assets/1402241/577b5644-8b30-4759-ad25-7938c46b6e45">

Yeah we did not implement that. PR welcome to turn the feature into a banner exactly like `netiquette`

**Comment by Jiralite** [comment]
Yeah, that's what I mean. I only opened a bug report about it because the associated image showed it working:

<img alt="image" src="https://user-images.githubusercontent.com/34235681/152473140-22b6eb86-3ef4-4104-af10-4a659d878f91.png">
