### ISSUE TITLE
I forgot to set the token

### ISSUE THREAD

**Issue by c02y** [refined-github/refined-github#7439]
When the refined-github is disabled:
https://imgur.com/UcGa51P

When the refined-github is enabled:
https://imgur.com/oL1oE0o

How can I restore that section to the original one?

**Comment by fregante** [comment]
Why do you need to restore it? What exact information is needed from there that isn't available on the page?

**Comment by c02y** [comment]
I need to goto the Release page instead of the latest release page

The Release page contains all the releases including the latest one, now the latest button only contains the latest release.

This change is unnecessary to me.

**Comment by fregante** [comment]
The change is made so that the sidebar has fewer items. Refined GitHub adds a Releases tab to the repository navigation, which is always visible on every page, so the link in the sidebar is duplicate. That feature is called `releases-tab`

**Comment by c02y** [comment]
`release-tab` option is already enabled, but I've never seen such tab
https://i.imgur.com/1DrudVP.png

**Comment by fregante** [comment]
Did you set the token?
