### ISSUE TITLE
Blank page when opening options on button click in Firefox

### ISSUE THREAD

**Issue by FloEdelmann** [refined-github/refined-github#7448]
### Description

After 

* https://github.com/refined-github/refined-github/issues/7188
* https://github.com/refined-github/refined-github/pull/7437

leaving the URL field empty should make the toolbar button open the extension options when clicked:

![grafik](https://github.com/refined-github/refined-github/assets/202916/5f940bc8-b7ae-41ac-aa42-f879bacd9d5f)

In Firefox, it opens an empty page with the URL `moz-extension://e5ca0577-0efe-46b9-9c5a-2c6dd4a225bc/_generated_background_page.html`:

![grafik](https://github.com/refined-github/refined-github/assets/202916/b38021d9-fb2a-440d-9615-c663e54757e0)

### How to replicate the issue + URL

1. Go to extension options
2. Clear "Button link" field
3. Click toolbar button

Expected: The extension options open.
Actual: A blank page opens.

### Extension version

24.6.13.1731

### Browser(s) used

Firefox 126.0.2

**Comment by fregante** [comment]
I mistakenly broke it in the last commit in that PR:  [`5ef4b64` (#7437)](https://github.com/refined-github/refined-github/pull/7437/commits/5ef4b64af1b87be9b4efec11858f62cbbf1a5418)

The check should be restored with `=== ''` instead of `=== 'options'`
