### ISSUE TITLE
Shift+Click no longer works to bulk mark files as viewed

### ISSUE THREAD

**Issue by bsrz** [refined-github/refined-github#7455]
### Description

Title says it say.
You used to be able click on "viewed" for 1 file, and click on the any other file while holding SHIFT to mark all files in between as viewed.

This no longer work.

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/pull/7451/files

1. Click on "viewed" on the first file
2. scroll down to the last file
3. Click on "viewed" on the last file

Expected behaviour: all files marked as viewed 
Actual behaviour: text is selected

### Extension version

24.6.13.1731

### Browser(s) used

Brave

**Comment by bsrz** [comment]
It works as expected in 24.2.8 on Safari

**Comment by fregante** [comment]
Can't repro, is it related to #7447? I'll release a new version anyway, let me know if you still see the issue there

Thank you for reporting
