### ISSUE TITLE
Major Issue in 24.6.13

### ISSUE THREAD

**Issue by offensive-vk** [refined-github/refined-github#7461]
## Bugs:

- User and Organisation Icons from the Repo path are missing, just names are being shown.
- File History color is gone by most recent update.
- No profile icons/pictures of other users are shown.

## See the image :
![extension not working](https://github.com/refined-github/refined-github/assets/121493131/b179bf23-8b8e-4103-9e8a-c114feacc21c)

### How to replicate the issue + URL

* https://github.com/refined-github/refined-github
* https://github.com/offensive-vk/UntilEverything/

### Extension version

24.6.13.1731

### Browser(s) used

Brave Official Build

**Comment by fregante** [comment]
Thank you for the report. This was resolved in 24.6.14, we just need to wait for it to become available on Chrome

**Comment by offensive-vk** [comment]
So it hasn't published on chrome web store yet?

**Comment by Samk13** [comment]
`File History color` is indeed missing on `24.6.13.1731`
Will this feature be restored in V24.6.14 @fregante?

**Comment by fregante** [comment]
24.6.14 is out on Chrome and Firefox. Safari will follow soon.

**Comment by offensive-vk** [comment]
Everything is restored back to normal with new latest update.
Thanks @fregante 🙌
