### ISSUE TITLE
Chrome Web Store - Item currently unavailable

### ISSUE THREAD

**Issue by MrChocolatine** [refined-github/refined-github#7463]
### Description

The [extension's page](https://chromewebstore.google.com/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf) on Chrome Web Store shows the error:
> Item currently unavailable. Please check the troubleshooting guide.

![cwb error refined github](https://github.com/refined-github/refined-github/assets/47531779/dbbf2f87-3682-433c-ad9a-3f55a924cd24)

The button `View guide` redirects to:
https://support.google.com/chrome_webstore/answer/1698338

Am I the only one? First time I am seeing this error and my setup, or browser, has not changed for a while.

Because of that I cannot update the extension.

I also cannot manually download + install the extension as its CRX file is not available on any release:
https://github.com/refined-github/refined-github/releases

### How to replicate the issue + URL

- Go to https://chromewebstore.google.com/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf

### Extension version

24.4.9

### Browser(s) used

Ungoogled-Chromium (https://github.com/ungoogled-software/ungoogled-chromium)

**Comment by fregante** [comment]
Every release has a zip file you can install as a developer, in any browser. You might have to unzip it first.

**Comment by fregante** [comment]
This is not an issue with Refined GitHub. You have a two-month old version installed, you should report the issue to the authors of your browser

**Comment by MrChocolatine** [comment]
Understood, I was not sure the issue was coming from the extension, but thought it would be faster to ask here first.
Thank you @fregante .

**Comment by fregante** [comment]
My guess is that it has something to do with https://github.com/ungoogled-software/ungoogled-chromium/issues/662, but it shouldn't.

**Comment by MrChocolatine** [comment]
That may finally force me to use a different browser.
I have been too lazy...
