### ISSUE TITLE
mark unavailable features in settings

### ISSUE THREAD

**Issue by doc-sheet** [refined-github/refined-github#7464]
### Description

Hi!
https://github.com/refined-github/refined-github/pull/7330 silently removed `show-whitespace` feature from firefox
On settings page I can enable/disable feature with no effect and it is hard to get the real issue, identify feature isn't helping too.

is it possible to disable/mark blocked features in settings? And maybe force some of them to run. I don't mind if show-whitespace is somewhat slow.

### Example URLs

https://github.com/refined-github/sandbox/pull/18/files

**Comment by fregante** [comment]
You're right, unfortunately we don't extract that information into the options. That specific item was supposed to be disabled temporarily. This month I'll slowly re-enable some of those features after some fixes.
