### ISSUE TITLE
Open the options page in a new tab

### ISSUE THREAD

**Issue by HanabishiRecca** [refined-github/refined-github#7465]
### Description

Firefox `about:addons` page is inconvinient. The options page could also be accessed by opening `moz-extension://b519e627-49b9-423e-9860-cbd5ac4819fc/assets/options.html` directly instead. It works very nice as a button link too.

But for users it is fairly tricky to get that url in the first place. Would be good to have a toggle for opening the options page if the button link is empty. Or at least have that url in the description below for user to copy.

### Example URLs

Internal

**Comment by fregante** [comment]
I've been thinking about this for a while. Showing the options in the native window makes it feel more "native", especially thanks to https://github.com/fregante/webext-base-css, but our options have grown quite a bit so it might make sense to just pull them out. 

PR welcome to:

- have the options open in a tab
- remove webext-base-css
