### ISSUE TITLE
Watch releases without pre-releases

### ISSUE THREAD

**Issue by Saafo** [refined-github/refined-github#7466]
### Description

See https://github.com/orgs/community/discussions/4993

### Example URLs

Something like this
![image](https://github.com/refined-github/refined-github/assets/46736350/5aaacc1c-5b2d-4d2f-ab76-8085aae9b5eb)

**Comment by fregante** [comment]
This is not something extensions can do. Once GitHub generates a notification, it's already too late.

**Comment by Saafo** [comment]
Got it. I'm just wondering how we can receive open/close notifications from issue, aren't they similar?

**Comment by fregante** [comment]
That's also managed by GitHub. Refined GitHub only makes that subscription "one click"

**Comment by Saafo** [comment]
Got it. Thanks!
