### ISSUE TITLE
Hide the column with the modified files in PR review page

### ISSUE THREAD

**Issue by bartgol** [refined-github/refined-github#7467]
### Description

Allow to hide (or at maybe resize?) the column on the left in a PR rewiew, where the folders/files modified are listed/grouped (the one circled in red in the attached figure below).

When I work on a small screen, I need to increase the browser's font size a lot (my eyes are no longer as they were 20yy ago). This makes the left column very large too, eating pointless space. I like that column, but rarely use it. I'd like to use the space for the main diff window.

I would be ok with either option:
- allow to reset width: manually via click/drag, or via settings
- remove the column altogether: probably only possible via settings.
- allow to temporarily hide the column down to a single button that you can click to bring it back (like collapsing a panel).

### Example URLs

https://github.com/E3SM-Project/scream/pull/2869/files
![Screenshot at 2024-06-17 15-02-56](https://github.com/refined-github/refined-github/assets/3226046/a584685a-adb8-4d34-9f34-d62a81728c50)

**Comment by fregante** [comment]
The button already exists natively, it's right next to the green "Open" bubble under the PR title.

**Comment by bartgol** [comment]
> The button already exists natively, it's right next to the green "Open" bubble under the PR title.

HOW? How did I miss that? I swear I went around and looked cause I thought "this must be something someone else already thought about", and did not find it. I feel like when my wife tells me "get that thing in the fridge", I tell her "honey, I'm telling you, it's not there!", and then she goes and it's magically there....

Thanks!

**Comment by fregante** [comment]
https://github.com/refined-github/refined-github/assets/1402241/eb98ddeb-9fa7-48f3-9764-9ce375b8fefa

**Comment by bartgol** [comment]
I swear that happened exactly like that!
