### ISSUE TITLE
`list-prs-for-file` dropdown gets hidden behind Symbols panel

### ISSUE THREAD

**Issue by miketheman** [refined-github/refined-github#7468]
### Description

The dropdown to list PRs for the current file is obscured behind the opened Symbols panel.

It's easy enough to close the panel to see the content, but it should try to come up to the top of whatever Z index is there.

I found these related bits, might be helpful:

* https://github.com/refined-github/refined-github/blob/main/source/features/list-prs-for-file.tsx
* https://github.com/refined-github/refined-github/pull/7417
* https://github.com/refined-github/refined-github/blob/ce7d7e71c32c11a68e7fa54ce5e46a7227132ceb/source/features/list-prs-for-file.tsx#L40-L53

### How to replicate the issue + URL

* Visit https://github.com/pypi/warehouse/blob/main/warehouse/packaging/models.py
* Open the Symbols panel
* Click on the List Pull Requests dropdown
* Observe that the behavior is hidden behind the Symbols list

<img width="557" alt="Screenshot 2024-06-18 at 12 32 51" src="https://github.com/refined-github/refined-github/assets/529516/f5726278-c8ef-476f-a80f-d949c81df88d">

### Extension version

24.6.14

### Browser(s) used

Chrome Version 126.0.6478.62 (Official Build) (arm64)

**Comment by fregante** [comment]
I wonder if https://github.com/refined-github/refined-github/pull/7417 was the cause or if it's just a coincidence. cc @Kocal

**Comment by fregante** [comment]
This is caused by

https://github.com/refined-github/refined-github/blob/037a1d013945d2746e2614aceb359621ab463e18/source/refined-github.css#L177-L180

If we bump that number to 5 we resolve the issue. Follows:

- https://github.com/refined-github/refined-github/issues/7408

**Comment by miketheman** [comment]
Thanks!!
