### ISSUE TITLE
I want to disable everything on the /pulls tab

### ISSUE THREAD

**Issue by sharunkumar** [refined-github/refined-github#7474]
I want to disable all the features on https://github.com/pulls (and similar tabs) since it makes the list less dense and I have to scroll a lot more to view all the items on the page.

I tried using the feature identifier option on the extension settings but couldn't the exact feature to disable.
I don't see a feature to blacklist a url either, to prevent everything from running on a certain url.

I would need help in identifying all the features that are acting on this page

**Comment by fregante** [comment]
There's no way to exclude a specific page. You can:

1. Enable "Show the features enabled on each page in the console" in the Options > Debugging
2. Open the browser console on /pulls
3. Disable all the features running there


However you're most likely interested in `align-conversation-labels` and nothing else.
