### ISSUE TITLE
Add Code Folding

### ISSUE THREAD

**Issue by aidan-gibson** [refined-github/refined-github#7475]
### Description

Like the 2019 issue #2195, I am again requesting code folding. The existing [Mottie userscript](https://github.com/Mottie/GitHub-userscripts) has been broken a while.

### Example URLs

https://github.com/Mottie/GitHub-userscripts/blob/575e466080dfcdff3c06aac2fd49c284552d11c9/github-code-colors.user.js#L23

**Comment by fregante** [comment]
My response then is still valid today: too complex for Refined GitHub
