### ISSUE TITLE
Remove clean-commit-form mention in wiki

### ISSUE THREAD

**Issue by aidan-gibson** [refined-github/refined-github#7476]
### Description

Remove the following line from [this wiki page](https://github.com/refined-github/refined-github/wiki/Undo-unwanted-styles):
* Avatar left to the commit form: [clean-commit-form](https://github.com/refined-github/refined-github/pull/5350#issuecomment-1033719565)

It is no longer relevant, `clean-commit-form.css` no longer exists.

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/wiki/Undo-unwanted-styles

### Extension version

24.6.14

### Browser(s) used

Firefox

**Comment by aidan-gibson** [comment]
There is also a minor typo on that page
> They can be find via the addCssFeature keyword.
Should be "They can be found..."

An example for clarity would also be great, I'm not sure how to use it.

**Comment by fregante** [comment]
Thank you! Most of it was outdated and I added a mention to CSS customization into our Customization page https://github.com/refined-github/refined-github/wiki/Customization
