### ISSUE TITLE
Extension demands access on all websites (Firefox)

### ISSUE THREAD

**Issue by HanabishiRecca** [refined-github/refined-github#7477]
### Description

Using Firefox, after 24.6.21 update the extension demands access on all websites. I guess it's the Manifest V3 thing?

![image](https://github.com/refined-github/refined-github/assets/13597663/07e080a3-bbd2-4234-b312-2671c29c883f)
![image](https://github.com/refined-github/refined-github/assets/13597663/605a82e6-6180-40ac-a831-e8ab88a83653)

### How to replicate the issue + URL

1. Open any unrelated website.
2. Observe the extension icon.

### Extension version

24.6.21

### Browser(s) used

Firefox 127.0.1

**Comment by fregante** [comment]
Thank you for the report! Unfortunately this is a Firefox bug so there's nothing we can do here.

I'll keep this issue open just for reference.

Bug described at:

- https://discourse.mozilla.org/t/permission-needed-indicator-on-browser-action/123183


Bug tracked at: (10 months old)

- https://bugzilla.mozilla.org/show_bug.cgi?id=1851083

**Comment by fregante** [comment]
# 24.6.14 (manifest version 2)

<img width="386" alt="Screenshot 3" src="https://github.com/refined-github/refined-github/assets/1402241/1f87f5f0-0b14-4059-be64-70136caefa49">

# 24.6.21 (manifest version 3)

<img width="386" alt="Screenshot 4" src="https://github.com/refined-github/refined-github/assets/1402241/3841b793-64cd-410f-8167-2d5e8bf14711">

**Comment by fregante** [comment]
Until that Firefox bug is resolved, I think we could just ship MV2 to Firefox.

We can add a small Node script to reverse the manifest.json changes from https://github.com/refined-github/refined-github/pull/7473. The rest of the code already works regardless of the manifest version.

That indicator is complete nonsense and I don't want to bother Refined GitHub users unnecessarily.

**Comment by HanabishiRecca** [comment]
Yeah, if it is not too cumbersome to maintain. Unlike Chrome, Firefox is not planning on dropping V2.

**Comment by INSANEMODE** [comment]
> Until that Firefox bug is resolved, I think we could just ship MV2 to Firefox.
> 
> We can add a small Node script to reverse the manifest.json changes from #7473. The rest of the code already works regardless of the manifest version.
> 
> That indicator is complete nonsense and I don't want to bother Refined GitHub users unnecessarily.

One thing to point out is that Firefox for Android support would be impacted by this change, as it only supports MV3.

That is probably a fairly small number of users compared to desktop Firefox, though.

**Comment by fregante** [comment]
> as it only supports MV3

I don’t think that's the case? We've been shipping Refined GitHub for Firefox for a while now:

- https://github.com/refined-github/refined-github/pull/7307

**Comment by INSANEMODE** [comment]
My bad, I misremembered. I double checked, and I am wrong.


 I thought it got dropped when extension support opened back up for Android, but that isn't the case. Most have gotten it mixed up with something else.

**Comment by fregante** [comment]
We're having some unrelated issues on that though, on all recent versions:

- https://github.com/refined-github/refined-github/issues/7486

**Comment by fregante** [comment]
I uploaded a Firefox-only version 24.6.25 with these changes. Hopefully it will be published today. Please report back when you see it and let me know if it fixes the issue.

[link-firefox]: https://addons.mozilla.org/firefox/addon/refined-github-/ 'Version published on Mozilla Add-ons'

This is a live badge for the current version on Mozilla Addons: [<img valign="middle" src="https://img.shields.io/amo/v/refined-github-.svg">][link-firefox]

Full changelog: https://github.com/refined-github/refined-github/compare/24.6.21...24.6.25

**Comment by fregante** [comment]
It's already out!

<img width="386" alt="Screenshot 9" src="https://github.com/refined-github/refined-github/assets/1402241/2b21e560-3d3b-4b0c-a05e-50afd4e60c0a">


However you'll encounter a Firefox bug prompting you to accept the new permissions. This is false, the permissions have always been the same.

<img width="456" alt="Screenshot 8" src="https://github.com/refined-github/refined-github/assets/1402241/1159f6c9-c0a3-428d-9ff8-3d5adae4b1c9">

**Comment by DrWhoFan13** [comment]
It's fixed for me, I no longer see a blue dot below my extensions menu button.

**Comment by willdurand** [comment]
@fregante [Bug 1851083](https://bugzilla.mozilla.org/show_bug.cgi?id=1851083) has just been fixed (in Nightly).

**Comment by fregante** [comment]
Quick! Thank you

So it will appear in v129 already?

**Comment by willdurand** [comment]
Yes, 129 as per our [release schedule](https://whattrainisitnow.com/).

**Comment by HanabishiRecca** [comment]
I'd say stick with V2 until the ESR release will also catch up.

**Comment by fregante** [comment]
ESR is already out as of July 9th, so you can already use the latest version and the latest features without any issues. 

The extension will likely be switched back to MV3 within the next month to avoid issues with the manifest version switching script.

**Comment by fregante** [comment]
The next ESR will be like in end of 2025, we're definitely not keeping MV2 around until then. It's more likely that I'll republish the MV3 version to AMO at some point this summer.

**Comment by willdurand** [comment]
The patch was uplifted to ESR128.

**Comment by fregante** [comment]
That's great to hear! Thank you 🙏

**Comment by fregante** [comment]
@willdurand it doesn't look like anything changed. Both my MV3 extensions with `activeTab` permission have a blue dot in Firefox 129:

<img width="1084" alt="Screenshot" src="https://github.com/user-attachments/assets/29751b39-5164-49e1-b232-d6940d84dd52">

**Comment by willdurand** [comment]
@fregante are these extensions only requiring `activeTab` or other host permissions?

**Comment by fregante** [comment]
Thanks for your answer. Both of them have a static one-host permission, a one-host content script and optional host permissions for “all URLs”: https://github.com/npmhub/npmhub/blob/main/manifest.json#L49

In both cases, the bubble appears on all websites exactly like in the first screenshot on this page.

**Comment by fregante** [comment]
@willdurand it appears that Firefox 130 finally fixed this. The wording is there but the badge is dot:

<img width="1196" alt="Screenshot 4" src="https://github.com/user-attachments/assets/6726090c-a8a6-4fdb-92c4-ea637eb9d181">
