### ISSUE TITLE
`update-pr-from-base-branch` - Enable on non-own repos

### ISSUE THREAD

**Issue by jkroepke** [refined-github/refined-github#7478]
### Description

I'm working for some OSS project which may not enabled the feature to offer "update branch" inside a PR.

![image](https://github.com/refined-github/refined-github/assets/1560587/5d280c80-104b-40f2-b14c-de7b2ff501ff)

To update the branch anyway, I have always go to my fork, choice the branch and click sync fork there.

![image](https://github.com/refined-github/refined-github/assets/1560587/03e399cb-1971-4396-a71a-40e37a9860a5)

Would be great, if Refined Github could offer a one-click button for this scenario:

### Example URLs

any PR

**Comment by fregante** [comment]
Did you set the token in your options?

**Comment by jkroepke** [comment]
![image](https://github.com/refined-github/refined-github/assets/1560587/ecaa87ae-17d3-4098-938a-0d0250a1a224)

Yes. Does it work cross repositories? I did not see the button on upstream repositories.

**Comment by jkroepke** [comment]
@fregante yes

![image](https://github.com/refined-github/refined-github/assets/1560587/ecaa87ae-17d3-4098-938a-0d0250a1a224)

Does it work cross repositories? I did not see the button on upstream repositories.

**Comment by fregante** [comment]
Yes if I remember correctly. There's a chance that they have a slightly different DOM and the button is not being appended. I'll reopen as a bug report

**Comment by jkroepke** [comment]
I can confirm, that there is no node with .merge-message 

https://github.com/refined-github/refined-github/blob/d9ea19838067ede2893c25935cb19ff19edd85e9/source/features/update-pr-from-base-branch.tsx#L98

cross-repo PRs (at least, if I do not have the merge permission on upstream)


<details>
<summary>Own Repo</summary>

![2024-06-22 18_50_26-Suppression by jkroepke · Pull Request #1 · jkroepke_terraform-provider-azurerm](https://github.com/refined-github/refined-github/assets/1560587/2bdae805-90ef-493c-af50-847cee5b5cc3)

</details>

<details>
<summary>Upstream Repo</summary>

![2024-06-22 18_49_28-New Resource_ `azurerm_advisor_suppression` by jkroepke · Pull Request #26177 · ](https://github.com/refined-github/refined-github/assets/1560587/22e02d29-e62c-4823-ae71-31a812d794c3)

</details>

**Comment by fregante** [comment]
I see it on cross-repo PRs: https://github.com/refined-github/sandbox/pull/13

<img width="927" alt="Screenshot 1" src="https://github.com/refined-github/refined-github/assets/1402241/4589fa2c-6d00-4af9-b491-fcfca30b7701">

But I don't see it if I don't have access to the repo where the PR is opened: https://github.com/cletusw/eslint-plugin-local-rules/pull/23
<img width="926" alt="Screenshot 2" src="https://github.com/refined-github/refined-github/assets/1402241/f37e20bb-80a3-4184-8211-5aad84ae5a80">

That's because the selector is targeting the Merge button itself 🤔 I don't remember why

<img width="946" alt="Screenshot 3" src="https://github.com/refined-github/refined-github/assets/1402241/598c92b9-383a-46d5-b4ca-cf0b9d348bf9">

**Comment by fregante** [comment]
https://github.com/refined-github/refined-github/blob/d9ea19838067ede2893c25935cb19ff19edd85e9/source/features/update-pr-from-base-branch.tsx#L59

> I don't remember why

I probably used that condition as a way to determine whether the user can merge the PR. This is not necessary, the condition should be "can the current user **update** the PR?"

I turned this back into a feature request.

**Comment by jkroepke** [comment]
> "can the current user **update** the PR?"

I guess, if the current is the author would be a sufficient condition?

**Comment by fregante** [comment]
If there's no other indicator, "can merge PR or is author" should be good enough. However there are cases where a repo collaborator can update PRs, but not merge them. Also the author can open a PR across repos that they don't own.

**Comment by jkroepke** [comment]
Maybe this indicator (checkbox -> Allow edits) on right side could be treat as indicator

![image](https://github.com/refined-github/refined-github/assets/1560587/269f4586-d233-4f8d-8de2-c8aa1ef05f0d)

It may not hits

> However there are cases where a repo collaborator can update PRs

but, it present cases like that

> Also the author can open a PR across repos that they don't own.

**Comment by fregante** [comment]
I think the solution is to just look for the "Close pull request" button 🤯

Users who can close it:

- PR author
- Maintainer

Seems obvious in retrospect. PR welcome

**Comment by fregante** [comment]
Would you be able to test https://github.com/refined-github/refined-github/pull/7642?

**Comment by jkroepke** [comment]
How I can test PRs?

**Comment by fregante** [comment]
You'd have to check out the PR locally, build the extension and load it into your browser. If you're not familiar with npm and extensions it might be difficult. See: https://github.com/refined-github/refined-github/wiki/Contributing#workflow

Anyway I think I covered your case in my tests already

**Comment by jkroepke** [comment]
> You'd have to check out the PR locally, build the extension

Is there an reason, why one of the PR actions not building and upload the crx as artifact? Then, I could just download the crx from [GHA](https://github.com/refined-github/refined-github/actions/runs/10216447965?pr=7642).

On my projects, I'm doing this, for example: https://github.com/prometheus-community/windows_exporter/issues/1543#issuecomment-2259304033

**Comment by fregante** [comment]
We just haven't set that up for PRs, we only do in releases. PR welcome to add that 😅
