### ISSUE TITLE
Increase size of profile picture to user hovercard

### ISSUE THREAD

**Issue by Andrew6rant** [refined-github/refined-github#7481]
### Description

I think it would be cool if there was an option to slightly increase the size of the picture in the profile hovercard. It's currently nearly the same size as the hover target.

Here's a quick CSS solution I threw together:

**Before:**

![Refined Github profile hover view](https://github.com/refined-github/refined-github/assets/57331134/054c7572-14c2-47a9-8080-6fc6f184fd41)

**After:**

![Modified Refined Github profile hover view](https://github.com/refined-github/refined-github/assets/57331134/50cf4c92-d786-4463-a8ac-608420a1799a)

### Example URLs

https://github.com

**Comment by fregante** [comment]
Changing the layout can introduce bugs down the line, but, simply increasing the size of the avatar should be easy and worthwhile.

PR welcome to add those 3/4 lines to `refined-github.css`

**Comment by fregante** [comment]
Please just send a PR when you have time 👍

**Comment by Andrew6rant** [comment]
Apologies for the delay, I just sent in a PR.

It's not perfect - I'm not sure if there's a nice way to avoid top-level comments' profiles from getting cut off without moving or changing the layout of the hovercard.
