### ISSUE TITLE
`visit-tag` adds useless link when switching branch picker tabs

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#7491]
### Description

When you change from "Branches" to "Tags" tab, the icon also changes thus matching our selector and triggers the addition of `visit-tag` link:

https://github.com/refined-github/refined-github/assets/44045911/d65d69a8-4b06-4bbf-89ee-0386f3fae4b0

We could probably just check if the branch picker is open and do nothing,

### How to replicate the issue + URL

https://github.com/refined-github/refined-github

### Extension version

24.6.21

### Browser(s) used

Chrome

**Comment by fregante** [comment]
This is caused by their own bug, showing `main` as a tag: 

![Untitled](https://github.com/refined-github/refined-github/assets/1402241/afcdd9a0-3196-4f85-ad5d-186d0c8d46a7)
