### ISSUE TITLE
`expand-all-hidden-comments` not available on mobile

### ISSUE THREAD

**Issue by BlazeFTL** [refined-github/refined-github#7506]
Sorry I Couldn't find any info on how to use it on a phone
All i saw was alt click..is there anyway to use this feature in phone ?

**Comment by fregante** [comment]
No way at the moment. I think that we should add a "Load all…" button and be done with it, no alt-click.

**Comment by fregante** [comment]
Their new issues view loads up to 150 comments at a time, making this feature obsolete. We'll eventually drop it once the old issue view is removed.

https://github.blog/changelog/2024-10-01-evolving-github-issues-public-beta/

**Comment by BlazeFTL** [comment]
hello i am on pc...but alt+mouse click still loads only 20 post for me
i am trying on this page 'https://github.com/uBlockOrigin/uAssets/discussions/17361'

**Comment by fregante** [comment]
`expand-all-hidden-comments` only works on issues and PRs. Not many Refined GitHub features support Discussions

**Comment by BlazeFTL** [comment]
Could this be added ?..if it's too time consuming for you then its ok
