### ISSUE TITLE
`fit-textareas`: Expansion of unfocused fields on the page

### ISSUE THREAD

**Issue by karlhorky** [refined-github/refined-github#7522]
### Description

When writing a longer issue with longer text in multiple `<textarea>` elements, it is a bad UX for:

- the unfocused `<textarea>` elements to collapse upon focus of a new field, hiding information that is being referred to during writing in other fields (see video below)
- the newly focused `<textarea>` element to change its size, causing a jump in the UI and leading to a feeling that the UI is janky or broken

https://github.com/refined-github/refined-github/assets/1935696/29eefb7c-544f-4f5d-9081-233d193b8a3b

I understand that it probably does not fit the `refined-github` philosophy to have configuration of the `fit-textareas` feature, so maybe it would make sense to either:

1. Change the default to always fit the text for all `<textarea>` elements
2. Or to introduce a new feature `fit-all-textareas` (default disabled)

These would lead to a stable UI size when focusing new fields, while not obscuring text content important to filling out all fields.

### Example URLs

- https://github.com/mdx-js/mdx/issues/new?assignees=&labels=&projects=&template=1-bug.yml

**Comment by fregante** [comment]
Can you make a screencast showing the problematic behavior? There's a chance that a recent update broke it

**Comment by karlhorky** [comment]
Sure, added a screencast video in the issue description above.

**Comment by fregante** [comment]
I don’t think that's a problem introduced by Refined GitHub. All fields already autofit the content; Refined GitHub just removes the height limits.

**Comment by karlhorky** [comment]
Hmm... maybe this should have been a feature request then. What are your thoughts on changing it to a feature request? Either with the `fit-textareas` feature or a new one?

**Comment by fregante** [comment]
I suppose the feature could also expand the "unfocused" field. This can be done via CSS, there's already a CSS rule

**Comment by karlhorky** [comment]
Ok, PR open here:

- https://github.com/refined-github/refined-github/pull/7530

I wonder if this is actually new behavior (a regression) since [the native `field-sizing` feature was enabled on new browsers](https://github.com/refined-github/refined-github/pull/7421)...

Reading the code it appears that nothing in the non-`field-sizing` code path was preventing it  from being applied to all `textarea`s on the page (the way I understand it, all `textareas` be sized by [`fit-textarea`](https://github.com/fregante/fit-textarea) as the user entered content, and would stay at that size when unfocused - this is also how [the `fit-textarea` demo](https://fregante.github.io/fit-textarea/) appears to work):

https://github.com/refined-github/refined-github/blob/8397b28f0eb32986d48e680cfaef114ab6a92f67/source/features/fit-textareas.tsx#L21-L33

**Comment by karlhorky** [comment]
Thanks for the review and merge of #7530 and publish in [`refined-github@24.7.10`](https://github.com/refined-github/refined-github/releases/tag/24.7.10)

I tested the new version just now in Chrome, and it is no longer obscuring the text in the unfocused fields 🎉


https://github.com/user-attachments/assets/7082fd07-be92-4716-a7b7-8bf2c3eb8265
