### ISSUE TITLE
`highlight-collaborators-and-own-conversations` - broken CSS

### ISSUE THREAD

**Issue by 134130** [refined-github/refined-github#7523]
### The feature looks pressed
![image](https://github.com/refined-github/refined-github/assets/50487467/efcf297f-b4b4-415b-afa1-0bda40b0d75a)

### Expect slim and nice
![image](https://github.com/refined-github/refined-github/assets/50487467/defc6d3a-220d-47e8-9c95-50566a35c503)

### How to replicate the issue + URL

- https://github.com/refined-github/refined-github/pulls

### Extension version

24.7.1

### Browser(s) used

Chrome

**Comment by fregante** [comment]
Fixed
