### ISSUE TITLE
Reactions' tooltip box doesn't appear for locked conversations

### ISSUE THREAD

**Issue by zzJinux** [refined-github/refined-github#7527]
### Description

Hovering the cursor over a reaction box for locked conversations doesn't show a tooltip box that lists usernames unlike when the extension is disabled.

### How to replicate the issue + URL

Example of a locked conversation: https://github.com/golang/go/issues/45729
<img width="529" alt="Screenshot 2024-07-05 at 20 14 14" src="https://github.com/refined-github/refined-github/assets/6695226/72f10b73-0303-4e08-beef-0a8f1c13cb3c">

Example of a non-locked conversation: https://github.com/golang/go/issues/52188
<img width="517" alt="Screenshot 2024-07-05 at 20 13 55" src="https://github.com/refined-github/refined-github/assets/6695226/928d6918-1772-4485-8319-85bc684468bf">

### Extension version

24.7.1

### Browser(s) used

Google Chrome 126.0.6478.127 macOS arm64

**Comment by fregante** [comment]
Indeed, it's because we disable the hover state by just using `pointer-events: none`

PR welcome to override the hover state instead.

**Comment by fregante** [comment]
Source:

https://github.com/refined-github/refined-github/blob/e33a312b6bbbd52536e7a64860a4e82fd984d100/source/features/github-bugs.css#L51-L56

**Comment by zzJinux** [comment]
@fregante I read #6795. I think it is natural that a disabled reaction button changes its visual state when hovered since hovering has its functional outcome (tooltip). What do you think? I'll follow your direction on visuals.

**Comment by fregante** [comment]
> a disabled reaction button changes its visual state when hovered

Hover states generally point to an item being clickable. I see one such example right next to this field:


![4545](https://github.com/user-attachments/assets/2df078d3-2e7a-494e-ba71-3dcbb848c291)



The icon is hoverable and has a tooltip, but it doesn't have a hover state because it's not clickable.

**Comment by zzJinux** [comment]
That's a good counterexample. However, to my taste, the icon (circled `i`) naturally indicates it will show a tooltip when interacted with, so it doesn't need a dynamic visual change, whereas a reaction button does not. A tooltip of a reaction button is not expected.

If you disagree with my argument, that's OK and I'll go with yours. It's a matter of taste and I also get your reason about consistency.

**Comment by fregante** [comment]
> consistency

Yes we try to match GitHub's behavior. A nearly-exact example is also shown here:

<img width="249" alt="Screenshot 19" src="https://github.com/user-attachments/assets/ca638a6f-3c53-4952-a7f3-4bb7f2d03235">

Same style, no icons, no images, no hover state… but tooltip.

**Comment by zzJinux** [comment]
That's a definitive example. I'm sold. Now I'm thinking about how to neutralize the hovering effect after returning `pointer-events` back...
