### ISSUE TITLE
Github issue reactions

### ISSUE THREAD

**Issue by Hacksore** [refined-github/refined-github#7531]
### Description

Is there any appetite to allow merging of this into Refined Github?

I'd be willing to contribute but I'm putting this issue together to hear from the refined github folks as well as @Norfeldt who makes the following extension.

https://github.com/Norfeldt/github-issue-reactions-browser-extension

tl;dr it puts these on the side bar that lets you jump to really useful comments.
![image](https://github.com/refined-github/refined-github/assets/996134/28e2e3d6-cfa8-41d1-984b-e94ee8f17ac0)

### Example URLs

any issue/pr url

**Comment by fregante** [comment]
See the first point on:

https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22

**Comment by Hacksore** [comment]
@fregante the main driver is the [intention to move to react](https://github.com/Norfeldt/github-issue-reactions-browser-extension/issues/21#issuecomment-1532724449) within the original extension.

> Use it, support it, extend it. Not everything needs to be part of Refined GitHub.

Sure but there is a bustling community here with a lot more folks who'd be willing to maintain the feature. There also is not a doubt in my my mind this rule has be overruled on features before.

This feature would be a very sane default for many developers who are looking to save time instead of traversing Github issues/pull requests.

Is this a final decision with no possibility on changing the stance?

Still curious to hear @Norfeldt's input to see if they are interested in this at all.

**Comment by fregante** [comment]
There are many reasons for which it won't be part of Refined GitHub (number 3 on that list also applies), one of which is that I don't like it. I suggest improving or forking that extension because there's still no reason to merge it here in any case.
