### ISSUE TITLE
`comment-on-draft-pr-indicator` appears on own comments + when editing

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7541]
### Description

- Following https://github.com/refined-github/refined-github/pull/7514

The banner appears in two places where it shouldn't:

- when editing comments
- to the PR author

<img width="691" alt="Screenshot 3" src="https://github.com/refined-github/refined-github/assets/1402241/9f2553e4-a4b1-40b1-825f-3582c0a885f6">

### Example URLs

https://github.com/refined-github/sandbox/pull/7

**Comment by kidonng** [comment]
> * when editing comments

I made a fix in https://github.com/refined-github/refined-github/commit/ac16c7b9923b1fb1a14c40b83d964a2277d5b943

As for

> * to the PR author

I will get to it some time later
