### ISSUE TITLE
Pull request sticky header misalignment

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#7542]
### Description

Without RGH:

<img width="558" alt="Screenshot 2024-07-10 at 10 14 22 PM" src="https://github.com/refined-github/refined-github/assets/44045911/e26e4871-aa5b-428c-8c4f-67385262e6f2">

With:

<img width="518" alt="Screenshot 2024-07-10 at 10 14 29 PM" src="https://github.com/refined-github/refined-github/assets/44045911/978fd78b-89d6-46d0-8ac2-0ef834a65900">

### How to replicate the issue + URL

https://github.com//refined-github/refined-github/pull/7472/files

1. Open any PR
2. Go to Files tab
3. Scroll down to see the sticky header
4. Notice the misalignment

### Extension version

24.7.1

### Browser(s) used

Chrome

**Comment by fregante** [comment]
I think this was done intentionally at some point to give some space between the title and the text below, but I might be wrong.

**Comment by kidonng** [comment]
Hmm but it _looks_ wrong and inconsistent if intentional (why only works on Files tab?)

<img width="675" alt="Screenshot 2024-07-10 at 10 39 41 PM" src="https://github.com/refined-github/refined-github/assets/44045911/c98e4a8c-39da-4c54-a323-181f299952af">
