### ISSUE TITLE
clean-repo-sidebar: Hides non-empty packages on repo page

### ISSUE THREAD

**Issue by rcdailey** [refined-github/refined-github#7544]
### Description

My project has 1 package (a docker image). The main repo page is [here](https://github.com/recyclarr/recyclarr) and the image is [here](https://github.com/orgs/recyclarr/packages).

If you look on the main repo page, the "Packages" section on the right side bar is missing. Screenshot:

![image](https://github.com/user-attachments/assets/7352e57d-87ad-4126-9981-e5836d378aca)

When I did "find feature", it identified `clean-repo-sidebar` as the issue. Here is a screenshot with that feature disabled:

![image](https://github.com/user-attachments/assets/0fc41e21-ff57-4139-9144-1d8c7c3cca5a)

This must have been a recent change because I never had this issue before. I sadly do not recall when it started; maybe a month or two ago?

### How to replicate the issue + URL

https://github.com/recyclarr/recyclarr

### Extension version

24.7.10

### Browser(s) used

Microsoft Edge

**Comment by fregante** [comment]
Is this related?

- https://github.com/refined-github/refined-github/issues/7532
