### ISSUE TITLE
Always show the commit title when reviewing commits in a PR

### ISSUE THREAD

**Issue by valkum** [refined-github/refined-github#7548]
### Description

Currently, the commit title is only shown at the very top of the page and scrolls out if the commit contains lots of changes.
The PR title is sticky and stays visible.
It makes sense to move the commit title next to the PR title e.g. in the format `PR title > Commit title`

### Example URLs

https://github.com/refined-github/refined-github/pull/7546/commits

**Comment by fregante** [comment]
That area is already quite busy and buggy at times. I don’t think this particular piece of information on that particular view is useful enough to justify the complexity unfortunately
