### ISSUE TITLE
`default-branch-button` doesn't appear on `isSingleFile` pages

### ISSUE THREAD

**Issue by injust** [refined-github/refined-github#7549]
### Description

```
refined-github.js:3281 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'classList')
    at fixFileHeaderOverlap (refined-github.js:3281:34)
    at default_branch_button_add (refined-github.js:5480:27)
    at refined-github.js:3561:9
```

The button doesn't appear:
<img width="319" alt="Screenshot 2024-07-15 at 7 07 16 PM" src="https://github.com/user-attachments/assets/edf442f6-200c-47e9-966d-06bd67179c0a">

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/blob/07ecc75/extension/content.js

### Extension version

24.7.10

### Browser(s) used

Chrome 126.0.6478.127 on macOS Sonoma 14.5

**Comment by fregante** [comment]
Indeed, it doesn't work when the window is very wide and the sidebar is pinned open.
