### ISSUE TITLE
Cannot set properties of null (setting 'value')

### ISSUE THREAD

**Issue by MrMonster123** [refined-github/refined-github#7551]
### Description

Hi All,

I'm getting the following bug when trying to download a directory via download-directory.github.io

Cannot set properties of null (setting 'value')

Tested in Chrome, Edge, Firefox - not sure if I'm missing anything

Machine is Windows

### How to replicate the issue + URL

go to download-directory.github.io

you will see the error right on the screen

![image](https://github.com/user-attachments/assets/cd85fbe9-6b7a-4bc8-b48c-beb4e3e4a11d)

In Firefox it is a different error

![image](https://github.com/user-attachments/assets/7b4a5365-16b7-48ab-a5a9-e9d26e4b1e15)

### Extension version

24.7.10

### Browser(s) used

Chrome, Edge, Firefox

**Comment by fregante** [comment]
It was fixed. Thank you for the report
