### ISSUE TITLE
`shorten-links` should not strip anchors from external URLs

### ISSUE THREAD

**Issue by asmeurer** [refined-github/refined-github#7556]
### Description

I don't know if it's intentional, but shorten-links is affecting links to external sites. The description seems to imply it only applies to GitHub links. 

This in particular causes it to strip anchors from links, which can be confusing. The fact that a URL has an anchor is often important context to know that a link is pointing to a specific part of a page. 

TBH, I would personally prefer it if shorten links didn't shorten external URLs at all, as a full URL is more noticeable as such if it isn't shortened. 

### How to replicate the issue + URL

First noticed it [here](https://github.com/data-apis/array-api-compat/issues/160#issuecomment-2231533605) but it seems to apply everywhere. 

### Extension version

24.7.10

### Browser(s) used

Chrome

**Comment by fregante** [comment]
Can you paste here the exact link being mangled? I'm not seeing it on 24.7.1 (Safari)

`shorten-link` is not supposed to alter the actual `href` nor to drop the `#hash` part from any links. External links only get `https://www.` dropped

**Comment by kidonng** [comment]
Without RGH:

<img width="928" alt="Screenshot 2024-07-17 at 11 49 14 AM" src="https://github.com/user-attachments/assets/b106f408-3179-466c-977d-000de73ffe6c">

With RGH 24.7.10 on Chrome:

<img width="922" alt="Screenshot 2024-07-17 at 11 49 18 AM" src="https://github.com/user-attachments/assets/cf1fcbad-751f-48db-a018-e4d3a617011e">

I agree the result are sub-optimal

**Comment by fregante** [comment]
I recently updated the underlying package so a bug might have been introduced. V24.6.14 does not have that update

**Comment by kidonng** [comment]
Indeed:

```js
import shortenV4 from 'https://esm.sh/shorten-repo-url@4'
import shortenV5 from 'https://esm.sh/shorten-repo-url@5'

const url = 'https://data-apis.org/array-api-compat/#difference-between-array-api-compat-and-array-api-strict'

console.log('V4', shortenV4(url))
console.log('V5', shortenV5(url))
```

<img width="1028" alt="Screenshot 2024-07-17 at 5 11 14 PM" src="https://github.com/user-attachments/assets/7c34dc38-5a90-4718-82fd-723b2e5bd17e">

**Comment by fregante** [comment]
Due to https://github.com/refined-github/shorten-repo-url/pull/50

The code was meant to affect non-repo URLs, but affected all URLs instead. I'll send a PR
