### ISSUE TITLE
Add current/previous shortcuts to wiki history pages

### ISSUE THREAD

**Issue by vrad-exe** [refined-github/refined-github#7557]
### Description

Comparing consecutive revisions of GitHub wiki pages is currently a bit of an annoying process, requiring you to manually check the boxes for 2 revsisions then press the compare button. Of course there needs to be a way to compare any two points in the revision history, but most commonly you're either comparing to the immediate previous revision or the current revision, and it's a little annoying to have to do this every time.
![image](https://github.com/user-attachments/assets/a33d2df2-f2e0-4ec6-8223-ca5f59c4030c)

MediaWiki's solution for this is to have `cur` and `prev` buttons next to every revision, which act as shortcuts to do those specific comparisons without having to select the revisions manually. It'd be neat to have this feature added to GitHub wiki history pages too.
![image](https://github.com/user-attachments/assets/6cf0641e-6615-4c83-8ccc-8e2973fa8c81)

### Example URLs

https://github.com/TeamSpen210/HammerAddons/wiki/Installation/_history
https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22/_history

**Comment by fregante** [comment]
Wikis are not a very commonly-used feature on GitHub, such a feature would get forgotten and lost quickly.

**Comment by vrad-exe** [comment]
What do you mean uncommonly used feature, I see repos use them all the time including literally this one

**Comment by fregante** [comment]
Yes but this repo has 100000 users, most repos don't. And even if it does, I never had to compare two revisions. Wikis are used *relatively* very little and you can tell by how old its UI is, it's probably been there unchanged since 2014

**Comment by kidonng** [comment]
I sorta feel your pain so I just built this: https://github.com/kidonng/userscript/tree/main/source/github-quick-wiki-diff

It's my personal project and unaffiliated with Refined Github so ask there if you have further thoughts.
