### ISSUE TITLE
`clean-repo-tabs` doesn't show actions when they're only on one branch

### ISSUE THREAD

**Issue by quatquatt** [refined-github/refined-github#7563]
### Description

When viewing a repo without actions enabled on the main branch, but with actions enabled on a secondary branch, the actions button in the top bar doesn't appear. 

In a perfect world, the actions button would only appear when viewing on the branch that adds them. However, this isn't really intuitive with how github works, because pages like Issues aren't per-branch. Because of this, I think it should just check all branches before deciding not to display Actions, instead of just the main branch. 

Actions not appearing on the top: 
<img width="1017" alt="Screenshot 2024-07-17 at 3 08 13 PM" src="https://github.com/user-attachments/assets/d93e128f-b4fc-4cc2-a901-00a822287dfc">

When visiting the actions menu from Additional Navigation Options, they suddenly appear. There are existing Actions, so it should have appeared before. 
<img width="1420" alt="Screenshot 2024-07-17 at 3 09 01 PM" src="https://github.com/user-attachments/assets/29dc81b6-964c-4e5f-bdb8-08473a518800">

After it realizes that Actions do exist, they'll now persist for a short time, but the menu will disappear upon reloading. 
<img width="1015" alt="Screenshot 2024-07-17 at 3 18 11 PM" src="https://github.com/user-attachments/assets/dba36af5-5cca-460e-b2a1-520207e30bd7">

### How to replicate the issue + URL

https://github.com/quatquatt/no-actions-menu
Visit this repo with Clean Repo Tabs enabled, and observe that the Actions menu doesn't appear, which would make you assume that it was empty. Then, go to the Additional Navigation Options, and select Actions. You'll see that Actions do exist, which the extension has suddenly realized, since it now appears in the top bar. This doesn't occur for something that isn't set up, like Projects. Now when you go back to Code, Actions will persist on the tabs menu. However, it'll disappear upon reloading the page. 

### Extension version

24.7.10

### Browser(s) used

Firefox, Chrome

**Comment by kidonng** [comment]
I assume it's very rare the workflow files are located in non-default branches only. I don't think it's worth it to query every branch just for this.

> Then, go to the Additional Navigation Options, and select Actions. You'll see that Actions do exist, which the extension has suddenly realized, since it now appears in the top bar.

This works as expected, we don't hide the tab if you are looking at it.

**Comment by fregante** [comment]
Indeed this is a bug and we can't fix it unless we find a different way to ask for workflows.

https://github.com/refined-github/refined-github/blob/4d54cf5ec5a29c017b7f1c9a1e3b344923696a2c/source/features/clean-repo-tabs.gql#L3-L9

And… good news! There's actually a way:

https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-repository

Let's use this new REST endpoint `/repos/quatquatt/no-actions-menu/actions/runs` instead

**Comment by fregante** [comment]
The `page`/`Link` trick explained [here](https://github.com/refined-github/refined-github/issues/7547#issuecomment-2241698376) also applies. This lets us do HEAD requests and avoid fetching _any_ data from the API.
