### ISSUE TITLE
`quick-mention` breaks Polar.sh badge positioning

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7575]
### Description

First time I see this badge:

<img width="190" alt="Screenshot 20" src="https://github.com/user-attachments/assets/ad99f404-5f90-4cc3-a1a1-282a706ae758">

Broken with Refined GitHub

<img width="152" alt="Screenshot" src="https://github.com/user-attachments/assets/e4ada45e-13f2-4b1b-bcb8-a8bbd686cc21">

<img width="415" alt="Screenshot 21" src="https://github.com/user-attachments/assets/f756d6a3-f54b-4cd8-9346-c0ae82524ad1">

### How to replicate the issue + URL

https://github.com/biomejs/biome/issues/1927#issuecomment-2227203261

### Extension version

24.7.10

### Browser(s) used

Chrome

**Comment by kidonng** [comment]
Looks like there used to be #2630:

https://github.com/refined-github/refined-github/blob/45f6900bc6417df7cddc8ae951419adac8642404/source/features/quick-mention.css#L12

**Comment by fregante** [comment]
We needed these two examples in the Test URLs as well.



> No idea why

Could be any reason, worth a try.

Also `quick-mention` itself is misaligned so a PR might want to address both:

- #7561
