### ISSUE TITLE
Pull Requests: Shortcut to navigate to changes when files are expanded.

### ISSUE THREAD

**Issue by sudhirkhanger** [refined-github/refined-github#7576]
Is there a shortcut for me to navigate to a subsequent change in a pull request when I have expanded the file fully?

GitHub by default shows files in collapsed form with changes highlighted. This make reviewing PRs difficult for me as I don't have enough context about the code around the change. If I expand the file and the file is very big then there is no way for me to directly navigate to the changes. Azure Git interface has this feature.

How can I setup such a shortcut?

**Comment by fregante** [comment]
I think we set up J for this already. The same shortcut works everywhere in GitHub, in some places it's native in others we add it (in issues for example it navigates comments)

**Comment by sudhirkhanger** [comment]
@fregante thanks for the reply.

Pardon my ignorance but I didn't understand what you meant but we setup J for this.

**Comment by fregante** [comment]
You asked for a shortcut, the shortcut is <kbd>J</kbd>

**Comment by sudhirkhanger** [comment]
@fregante I don't think it takes me to changes location when files are expanded mode.

**Comment by kidonng** [comment]
If I understand correctly:

1. You expand the file
2. The changes are pushed down to somewhere
3. You want a shortcut to jump to the changes

Indeed we don't have this feature. But you can preserve you location while expanding the file, the trick is to click the expand button when the file header becomes sticky:


https://github.com/user-attachments/assets/ef7ea821-398d-4b10-970c-5f65df32b21d
