### ISSUE TITLE
`linkify-code` trailing dot/point/`.` picked up as part of URL/link 

### ISSUE THREAD

**Issue by Avasam** [refined-github/refined-github#7577]
### Description

When an URL appears at the end of a sentence, it is often followed by a `.` without space. GitHub correctly highlights the URL w/o the `.` in the code view and makes the correct link clickable in Preveiw/View mode. Even my IDE (VSCode) excludes the `.` from the URL.

But the `linkify-code` feature incorrectly includes `.` as part of the clickable URL in the code view

### How to replicate the issue + URL

Modify any file to include an URL with path params (`/`) that ends with `.` and check the PR/commit in GitHub. For example:

```md
This repo is https://github.com/refined-github/refined-github.
```

Edit, even just this code block shows the issue. ☝️ 

Here's an example https://github.com/python/typeshed/commit/2fb9c35ff93db0e8e7297cbb5860a7bb6aa5dfa6#diff-9c749476405e46c668093de1fa173e3569a04cbd97331800ac4dc2a67059168eR105

### Extension version

24.7.10

### Browser(s) used

Opera, FireFox

**Comment by fregante** [comment]
Thanks for the detailed issue!

This is a long standing bug. Tracked in:

- https://github.com/sindresorhus/linkify-urls/issues/26
