### ISSUE TITLE
Move PR and issue ID/number to beginning of window title

### ISSUE THREAD

**Issue by greglockwood** [refined-github/refined-github#7578]
### Description

**The problem:** The ID for PRs, issues, etc. comes after the title in the tab/window, so it often gets hidden behind the truncation ellipsis on hover or is not visible in the text shown in the tab. But that ID is quite useful, so I would like to see it first in the tab title instead.

### Example

From a private company repo
**PR title:** ``Replace usage of `.at()` with equivalent index access``
**PR ID:** `#12937`
**Full window title:** ``Replace usage of `.at()` with equivalent index access by greglockwood · Pull Request #12937 · [org]/[repo]`` (placeholders used instead of real org and repo names)
**Suggested amended title:** ``#12937: Replace usage of `.at()` with equivalent index access by greglockwood · Pull Request · [org]/[repo]``
**Screenshot of Chrome hovercard:**
<img width="243" alt="Screenshot of hover card shown for GitHub PR with title of 'Replace usage of `.at()` with equivalent index access by...'" src="https://github.com/user-attachments/assets/184c4b0c-4efc-414d-aa9f-afeb13dd9d22">

### Use Case Examples
1. You are trying to mention another issue that you have open in a different tab. This enables you to see the ID in the visible tab text or at least the hovercard.
2. You are trying to use the GitHub CLI to checkout a PR that you have open in a different tab or where you have scrolled down past the header, etc etc. You need the ID to do so (`gh pr checkout <id>`), so having it visible would be useful.

### Suggested state
I can see this one being polarising, so perhaps it would be best to have it disabled by default but able to be opted into. I am happy to discuss to see how others feel about this first before deciding, though.

### Implementation Complexity

This one should be pretty easy to do as it should just be a regex replace of the current `window.title` value.

### Example URLs

https://github.com/refined-github/refined-github/pull/7570
https://github.com/refined-github/refined-github/issues/7577

**Comment by kidonng** [comment]
It makes sense to see how other issue trackers do things:

- GitLab: ID after title ([example](https://gitlab.com/gnachman/iterm2/-/issues/11737))
- Jira: ID before title ([example](https://unicode-org.atlassian.net/jira/software/c/projects/ICU/issues/ICU-22834))
- YouTrack: ID after title ([example](https://youtrack.jetbrains.com/issue/IJPL-158666/Rider-new-solution-Display-non-English))

So opinions can indeed vary.

> I can see this one being polarising, so perhaps it would be best to have it disabled by default but able to be opted into.

[We don't do that here](https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#2-it-makes-sense-as-a-default-for-everyone).

**Comment by fregante** [comment]
I can see how this can be useful, but for many others the number might be *less* useful than the "title for humans" at a glance
