### ISSUE TITLE
Add reviewers' status to the PR page

### ISSUE THREAD

**Issue by QuentinC974** [refined-github/refined-github#7581]
### Description

It would be great to be able to see reviewers' status on the PR page so we can easily know what we have reviewed and what we haven't yet, and the same thing for our teammates' reviews.

So now we have :
![image](https://github.com/user-attachments/assets/1ae1ff3e-1488-4f27-8391-56ddfe31c39e)

I suggest :
![image](https://github.com/user-attachments/assets/752ecb64-179a-43a7-b360-47f5c6d196c1)

or a simplified version : 
![image](https://github.com/user-attachments/assets/e5b7a1a6-9cdf-4e05-a22c-2ee53931608d)

- **It doesn't already exist as a [userscript](https://github.com/Mottie/GitHub-userscripts) or extension.**
   I haven't found it, but if it does, I'd love to have the link!
- **It makes sense as a default for everyone.**
   I think so
- **It doesn't require options.**
   No : just enable or disable, as it is already the case.
- **It doesn't require a lot of view/UI, code and effort to maintain.**
   It doesn't seem to be much more from what we already have
- **It doesn't require an external server.**
   I do not think so
-  **It doesn't require too much HTTP traffic**
   not really, maybe few calls to get the status and PP
- **It doesn't enhance "Projects"**
   It would make the PR review process easier

### Example URLs

https://github.com/afkl-airspace/prognos-ihm-front/pull/

**Comment by fregante** [comment]
Unfortunately I have to close this for the same reason we closed the dozen other similar requests: that list is already busy and there's plenty of information that _could_ be shown. In this case _who_ reviewed it isn't particularly useful to the vast majority of users.

**Comment by QuentinC974** [comment]
I understand, but if you say that there are dozens of requests like mine, maybe it would be a great feature to add.
If by any chances you know an extension to do it, I'd love to have it.
Have a great day.

**Comment by fregante** [comment]
The requests I meant were about pieces of information to add to the PR list, not this specific request

**Comment by QuentinC974** [comment]
Alright, thanks for your time and answers.

**Comment by sarah-gelt** [comment]
It's a shame this won't be considered. It's standard UI in Bitbucket which I used with a previous team and I loved it. Have missed it for years since moving to Github. If it's not useful to all users, couldn't it be optional for those who do want it? It seems to be have been requested often enough...

**Comment by Papooch** [comment]
@fregante Would you consider re-opening the issue? I counted at least 3 other closed issues that asked for the same feature.

There's also multiple feature-requests for GitHub itself to add this feature ([1](https://github.com/orgs/community/discussions/52631), [2](https://github.com/orgs/community/discussions/37961), [3](https://github.com/orgs/community/discussions/17683)).

Having migrated off Bitbucket, this is the feature that is missing the most.

---

I'd like to challenge the argument that "that list is already busy" :

If the list of avatars was shown _instead of_ the long phrase "X review approvals" or "changes requested", space would be actually _saved_, while providing _more_ information.

![Image](https://github.com/user-attachments/assets/9b73cb34-988a-4e04-add6-e0f48136cbab)
vs
![Image](https://github.com/user-attachments/assets/44862750-7f74-4a45-a7ae-1787205e4ed5)

**Comment by EliteMasterEric** [comment]
This feature would be great. Maybe make it optional or toggleable.

**Comment by Papooch** [comment]
Every feature is already togglesble, that's why I don't see the reason for such strong opposition.
