### ISSUE TITLE
 Auto-merge warning when approving a PR

### ISSUE THREAD

**Issue by quodlibetor** [refined-github/refined-github#7596]
### Description

I want to reopen the discussion on #6979 -- it would be great (for me) if the review changes modal had a warning or something that said that auto merge is enabled.

https://github.com/refined-github/refined-github/pull/6972/files#review-changes-modal

the rationale for closing was:

> * this requires an API call

I think it's fine if this is blocked behind having a github token enabled.

> * this data can at any time become stale (e.g. someone enables auto-merge while you review)

I already make decisions based on stale data -- I check if auto merge is enabled, and then decide whether to approve with comments or not.

Additionally, if it's possible to do the api call when the "Review Changes" button is clicked then you could have up-to-the second info. It could still become stale, but that's a known risk if we allow auto-merges on our repos.

---

One possible ui allowing for a spinner so that the api call can be done late would be:

![image](https://github.com/user-attachments/assets/4ad74475-dbf1-4cd9-a6a6-8911ed44ee73)

then one of these:

| is enabled | is disabled |
|---|---|
| ![image](https://github.com/user-attachments/assets/4fea999a-855b-4d77-a6c4-c277bb032154) | ![image](https://github.com/user-attachments/assets/82d92f24-52bc-443f-8968-3476dd60efed) |

Or any other UI.

An alternative would be to modify the Approve button to have a spinner and then have the text be "Approve (auto-merge)" if it is enabled:

loading:

![image](https://github.com/user-attachments/assets/caef3225-3cdf-4d13-9930-28895455b4e6)

turning into:

![image](https://github.com/user-attachments/assets/989c76da-e857-4bdb-a2f9-7da0371b601b)

### Example URLs

https://github.com/refined-github/refined-github/pull/7580/files#review-changes-modal

**Comment by fregante** [comment]
The point still stands: someone already clicked that button, so they already decided it's fine to be merged after an approving review. 

If you need changes together with the review, then don't approve it. 

It seems that you want this feature because both you and the premature automerger are using GitHub *the wrong way* and then complaining that it's doing exactly what you're telling it to do. 

Again the advice here is to inform the team to not click "auto-merge" unless it has been reviewed by enough people.

**Comment by fregante** [comment]
As for why Refined GitHub can't implement it: you can't show this piece of information without continuously polling the API. For you that's ok, for most Refined GitHub users it's not worth it. 

This, coupled with the misuse described above means we can never add it here.

**Comment by quodlibetor** [comment]
> both you and the premature automerger are using GitHub *the wrong way*

I work on a high trust team -- we have norms around when we enable auto-merge, and when we approve with comments. If we approve with comments it means we are fine with things as they are but want to point out something non-blocking and let the author decide whether or not accept the suggestion and merge. I trust them to do the right thing, they shouldn't need to wait for me to approve again, and honestly I don't want to be interrupted again.

Although, thinking about it, we can just turn on "cannot merge until all comments are resolved", which will also solve this problem.

Anyway, thanks for a great extension, I use and love it every day.
