### ISSUE TITLE
Docs: Broken link in #3543 

### ISSUE THREAD

**Issue by injust** [refined-github/refined-github#7609]
### Description

> Check out [contributing.md](https://github.com/refined-github/refined-github/blob/main/contributing.md?rgh-link-date=2020-09-11T17%3A57%3A41Z) for more info!

This should point to https://github.com/refined-github/refined-github/wiki/Contributing

### How to replicate the issue + URL

N/A

### Extension version

N/A

### Browser(s) used

N/A

**Comment by fregante** [comment]
Thank you 🙏
