### ISSUE TITLE
`netiquette` appears in preview tab

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7612]
### Description

![c](https://github.com/user-attachments/assets/a837f5ea-7b1a-4526-9552-79f5c338d9f6)

### How to replicate the issue + URL

https://github.com/facebook/react/pull/19377

### Extension version

24.7.29

### Browser(s) used

Chrome

**Comment by fregante** [comment]
cc @kidonng

**Comment by kidonng** [comment]
That's `draft-pr-notice` but yeah `netiquette` is also affected. I think GitHub changed DOM recently or else this should have always been the case.
