### ISSUE TITLE
Show all issues/prs by default, i.e. ability to remove default `is:open` filter

### ISSUE THREAD

**Issue by HanabishiRecca** [refined-github/refined-github#7615]
### Description

`Issues` and `Pull requests` button links carry default `is:open` filter with them.
It would be good to have an ability to remove the default filter.

### Example URLs

https://github.com/refined-github/refined-github/issues?q=sort%3Aupdated-desc+is%3Aissue

**Comment by fregante** [comment]
I don’t think most users would appreciate the change because open issues are clearly more important than closed issue.

We have a `sort-conversations-by-update-date` feature that contains code that you can reuse in your own userscript though.

**Comment by HanabishiRecca** [comment]
I don't see why the feature can't be disabled by default, but ok.

**Comment by fregante** [comment]
When opening this issue there was a link explaining why:

- https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#2-it-makes-sense-as-a-default-for-everyone

**Comment by HanabishiRecca** [comment]
Ok, fair take.
