### ISSUE TITLE
Extend `fix-no-pr-search` to work on global lists

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7616]
### Description

Removing `is:pr` from here won't work: https://github.com/pulls

### Example URLs

https://github.com/pulls

**Comment by fregante** [comment]
@kovsu

**Comment by kovsu** [comment]
I can't reproduce it. Can you provide me a gif or a video?

**Comment by fregante** [comment]
1. Open https://github.com/pulls
2. Delete `is:pr` from search field
3. Press enter
4. You should end up on a list that contains all your ISSUES and PRs https://github.com/issues?q=sort%3Aupdated-desc+is%3Aopen+author%3A%40me+archived%3Afalse

**Comment by kovsu** [comment]
@fregante Got it!
