### ISSUE TITLE
`comments-time-machine-links`: URL hash is removed

### ISSUE THREAD

**Issue by injust** [refined-github/refined-github#7620]
### Description

Links sometimes have a line number/range in the URL hash, e.g. `#L104`. Clicking the "view this object as it appeared at the time of the comment" link removes this hash during navigation, even though it exists in the URL.

### How to replicate the issue + URL

Visit https://github.com/acomagu/fish-async-prompt/issues/51 and click on this link: https://github.com/acomagu/fish-async-prompt/blob/master/conf.d/__async_prompt.fish?rgh-link-date=2021-04-01T17%3A21%3A00Z#L104

Then click "view this object as it appeared at the time of the comment", which goes to `https://github.com/acomagu/fish-async-prompt/blob/316aa03c875b58e7c7f7d3bc9a78175aa47dbaa8/conf.d/__async_prompt.fish#L104`. But when you click it, the `#L104` hash is lost during navigation.

### Extension version

24.7.23

### Browser(s) used

Chrome on macOS Sonoma 14.5

**Comment by fregante** [comment]
Thanks for the detailed report! I think I found the reason, due to GitHub's https://turbo.hotwired.dev/ library.
