### ISSUE TITLE
`toggle-everything-with-alt` support search page

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#7628]
### Description

We have it in `easy-toggle-files`:

https://github.com/refined-github/refined-github/blob/0aa661be9eb59620576eb4f41759863afe9c2a12/source/features/easy-toggle-files.tsx#L19-L28

### Example URLs

https://github.com/search?q=repo%3Arefined-github%2Frefined-github%20features&type=code

**Comment by fregante** [comment]
Why would you toggle them? Seems like an unnecessary feature
