### ISSUE TITLE
Features with "Open issue/notification" buttons broken on iOS

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7629]
### Description

It visually works but no tabs are open and no notifications are actually marked as unread on the server

### How to replicate the issue + URL

1. https://github.com/notifications
2. Click "open all unread"

### Extension version

24.7.10

### Browser(s) used

Safari

**Comment by fregante** [comment]
I don't know what's up with Safari, but there are two possible easy fixes:

- Ship MV2
- Ship MV3 but with a background script instead of the worker

There's background issue in Safari but that shouldn't be the cause. It seems that the worker isn't starting or is unable to stay awake

- https://github.com/fregante/webext-tools/issues/10

I'll have to use the simulator maybe

**Comment by fregante** [comment]
Reported:

- https://bugs.webkit.org/show_bug.cgi?id=277588

I'll fix this by using `background.scripts` instead.

**Comment by Nixinova** [comment]
I'm just going to say, your passive aggressive response and title change at #7659 is frankly insulting and degrading. At least give me the opportunity to readd the token and try again to see if the issue still occurs. Your attitude is incredibly offputting for your users and has turned me off wanting to use this extension altogether.

**Comment by fregante** [comment]
You insulted me by not reading the instructions that appear when you install the page, but ignoring the big red banner that appears on top of the "New bug report" template, and all the instructions on that page. You do not care about my words, why are you asking for more?
