### ISSUE TITLE
`hide-inactive-deployments`: Inactive deployments not hidden

### ISSUE THREAD

**Issue by MarcusCaspeco** [refined-github/refined-github#7630]
### Description

This feature seems broken, everything so far is working except for this one. The inactive deployments are not being hidden.

![image](https://github.com/user-attachments/assets/dc9d8001-d331-4d7b-98a1-4cbb98eaefa0)

I have one error in console but it doesn't seem related to this feature. When I disabled `show-names` the error disappears, but the problem with inactive deployments persist.
![image](https://github.com/user-attachments/assets/6e588e2c-220a-4ad2-8051-da1ff5c81cef)

### How to replicate the issue + URL

- Completely fresh install
- Add access token
- Go to https://github.com/btkostner/btkostner.io/pull/10
- See all deployments

### Extension version

24.7.30

### Browser(s) used

Chrome

**Comment by fregante** [comment]
Strange, I just tested it last week for https://github.com/refined-github/refined-github/pull/7554/files#diff-442650bcb70bc49a833891f1261993e0a871c103943b5cf152236466aa92bdaf

**Comment by fregante** [comment]
If you see that console error after a refresh, please open another bug report and include a URL for that issue, it’s unrelated to this.

**Comment by shayaantx** [comment]
I think github changed their client side code, cause I'm also noticing this
```
	const deployments = $$('.js-socket-channel[data-url*="/partials/deployed_event/"]');
```
is not working against their latest HTML, now it seems to have switched from "data-url" attribute to "data-gid" at least in my PRs

I've been using this css to completely hide all deployment stuff cause its so noisy

```
div.js-socket-channel div.js-updatable-content[data-gid^="PR_"] {
	display: none !important;
}
```
