### ISSUE TITLE
`update-pr-from-base-branch` missing when reviews are required

### ISSUE THREAD

**Issue by baado** [refined-github/refined-github#7631]
### Description

It happens even in secret mode.
`pr-base-commit` also not working for me.

![スクリーンショット 2024-08-02 7 40 10](https://github.com/user-attachments/assets/e6261aaa-cc75-4edc-93c1-124337afd30d)

Is this error related?

<img width="757" alt="スクリーンショット 2024-08-02 7 33 48" src="https://github.com/user-attachments/assets/d1a95559-68a6-42bb-b42f-c74560262636">

```
Uncaught (in promise) Error: Expected node matching /commented|left a comment/, found ""
    at assertNodeContent (refined-github.js:3891:13)
    at removeTextNodeContaining (refined-github.js:3893:7)
    at refined-github.js:6213:77
    at show_names_updateLink (refined-github.js:6215:8)
```

### How to replicate the issue + URL

URL sample:
https://github.com/(org)/(repo)/pull/1234
this is a private repository.

How to replicate the issue:
show this page and scroll down.

### Extension version

24.7.30

### Browser(s) used

Google Chrome 127.0.6533.88（Official Build） （arm64）

**Comment by fregante** [comment]
Would you be able to test https://github.com/refined-github/refined-github/pull/7642?

**Comment by baado** [comment]
it seems to be working fine! thank you so much!
