### ISSUE TITLE
Re-add `global-search-filters`

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#7658]
### Description

The feature was dropped in #6248 as it was broken and needed a rewrite due to the new search. It was stated

> the 4 filters are now more easily achievable via GitHub's interface

But the interface does not become any more helpful. You _have to remember_ to use e.g. all uppercase `NOT` and `is:fork` not `is:forked` just to exclude forks (all these are not provided as completions).

Just now I missed the feature to exclude forks in one click. I think it would be useful even if we merely add this:

<img width="216" alt="Screenshot 2024-08-04 at 3 07 18 PM" src="https://github.com/user-attachments/assets/3bab98e0-2564-4763-95bf-c982abcbc7c9">

I did a quick prototype in-place and the implementation is straightforward, just copy existing link element and change the `href` target then good to go.

### Example URLs

https://github.com/search?q=refined-github&type=code

**Comment by fregante** [comment]
Search supports a large number of filters: https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests

I don’t think it's worth adding one of the many, unless they're non-trivial. `is:fork` on its own is rather trivial

**Comment by kidonng** [comment]
> Search supports a large number of filters

Most of them are already there:

<img width="241" alt="Screenshot 2024-08-04 at 3 47 02 PM" src="https://github.com/user-attachments/assets/2a12251e-34b6-4d65-af1b-0f7ae1c663bc">

> I don’t think it's worth adding one of the many, unless they're non-trivial

I thought Refined GitHub is about the opposite? 😂 

> `is:fork` on its own is rather trivial

Can't say for other people, but I occasionally need to search through some code pattern across all my repositories to update/make sure/etc. And forks get in the way. I know the ultimate solution (for this case) is to prune forks no longer in need but it takes time and sometimes you just can't so that's it.

**Comment by kidonng** [comment]
If just one extra filter seems overkill for an entire feature then another candidate could be `owner:<my username>` because `owner:@me` doesn't work and the autocomplete orders suggestion in ways beyond my comprehension:

<img width="249" alt="Screenshot 2024-08-04 at 4 00 52 PM" src="https://github.com/user-attachments/assets/f71ef1c2-30ef-4e41-b29b-acb924814b57">
