### ISSUE TITLE
No releases tab

### ISSUE THREAD

**Issue by Nixinova** [refined-github/refined-github#7659]
### Description

The extension does not add a Releases tab even when it says it should and hides the "Releases" button on the sidebar, making it annoying to try get to the releases page.

![image](https://github.com/user-attachments/assets/d57c4d31-6cf6-4c68-872a-e1239ae230fd)
![image](https://github.com/user-attachments/assets/a2ec7967-5791-40b1-a24a-1b41731b24b4)
![image](https://github.com/user-attachments/assets/86d4b667-2d03-4060-a13f-e6228af49699)
<hr>

When extension is disabled:
![image](https://github.com/user-attachments/assets/0d5d2925-5871-4ebc-9de9-f884af4b38cb)

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/tree/24.8.3

### Extension version

24.7.30

### Browser(s) used

Chrome

**Comment by fregante** [comment]
The bug report page is clear. You did not set the token. 

![image](https://github.com/user-attachments/assets/a8b818b6-ee0c-4842-8a40-6d6bb89582c7)

**Comment by fregante** [comment]
<img width="731" alt="Screenshot 1" src="https://github.com/user-attachments/assets/0b49c988-1a96-473e-b5e7-58de4c8469ae">
