### ISSUE TITLE
`fit-textareas` cuts off the description area for new pull requests

### ISSUE THREAD

**Issue by Seregy** [refined-github/refined-github#7664]
### Description

The description area on the "Open a pull request" page may not fit all the text when the `fit-textareas` is enabled. The text area looks fine after switching between the `Write` and `Preview` tabs. The issue is particularly noticeable when the repository defines a rather lengthy PR template.
Affects Firefox, Chrome seems to be fine

With the `fit-textareas` enabled:
![refined-github-feature-enabled](https://github.com/user-attachments/assets/662563b8-2eaf-444b-b845-d088d08548f4)

With the feature disabled:
![refined-github-feature-disabled](https://github.com/user-attachments/assets/8f69734e-06e7-48b9-a65f-088600eb5bc4)

### How to replicate the issue + URL

Try to open a new pull request in a repository that has a PR template.
Example with the current repository -  https://github.com/refined-github/refined-github/compare/main...test/bun?expand=1
Example with the test repository with a long template - https://github.com/Seregy/pr-template-test/compare/test-branch?expand=1

### Extension version

24.8.3

### Browser(s) used

Firefox 129.0

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
The field is expanded correctly when you start typing into it, right?

**Comment by FirelightFlagboy** [comment]
Hello, I'm having the same issue with the PR template used in the repo https://github.com/Scille/parsec-cloud.

The text area don't resize if I start writing in it.

I would also note that the "button" to resize the text area is not visible (cf the first screenshot in the issue description)

**Comment by fregante** [comment]
Just Firefox right?

**Comment by Seregy** [comment]
The issue seems to be caused by the way the `fitTextarea` function resizes the text area elements on the page(although I have no idea what exactly changed since yesterday). In my environment the text area with the id `pull_request_body` effectively keeps its original height(`541px`), but the element with the id `pull_request_body_ghost` becomes smaller after the resize(`541px` -> `58px`).
When I open the compare page without the `expand=1` query parameter and  click the "Create pull request" button, the text area actually looks fine. It seems that in this case the height of the ghost element gets fixed by the GitHub's `handleResize` function from the `copilot-text-completion-element.ts`, which gets executed after the `fitTextarea`. When the compare page is opened with the  `?expand=1`, the execution order is different and the `pull_request_body_ghost` keeps the height set by the extension.
Additionally, the change of the `pull_request_body_ghost_ruler` height(`0px` -> `30px`) seems to create a gap between the resize handle and the end of the text area.

<details>
<summary>Resize handle gap</summary>

![refined-github-resize-handle-description](https://github.com/user-attachments/assets/7e98b077-a13d-40bd-8771-c8553bb59606)

</details>

Chrome is not affected by this issue, as it supports `field-sizing: content` and the `fit-textareas` doesn't use the `fitTextarea` for resizing the elements in this case(see the [condition with the `nativeFit`](https://github.com/refined-github/refined-github/blob/main/source/features/fit-textareas.tsx#L27)).

I've tried upgrading the `fit-textarea` to `3.0.0` to see whether it works better. With the updated version the description is displayed in full, which is nice, but the `pull_request_body_ghost` gets placed below the `pull_request_body`, which leaves an even bigger empty area.

<details>
<summary>Description area after upgrade</summary>

![refined-github-dependency-upgrade](https://github.com/user-attachments/assets/4065d59d-57fc-431d-a3e6-c02184659676)

</details>

**Comment by fregante** [comment]
So this is related to copilot, like:

- https://github.com/refined-github/refined-github/issues/7648

I don't have access to it. Do you use GitHub Enterprise?

I guess the question is how does GitHub handle this natively? And I'm confused as to why `field-sizing` works but the JS version doesn't 🤔

**Comment by fregante** [comment]
It seems that:

1. there are two _ghost_ `textarea`s that GitHub resizes to match the main textareas
2. `fit-textareas` will handle these independently, which breaks them since they're empty
3. `field-sizing` works because our scripts don't override the _ghost_ `textarea`s

**Comment by Seregy** [comment]
> Do you use GitHub Enterprise?

Nope, I don't have access to Enterprise or Copilot
