### ISSUE TITLE
`toggle-everything-with-alt` no longer works for the commit messages in the commit list

### ISSUE THREAD

**Issue by Seregy** [refined-github/refined-github#7671]
### Description

The `toggle-everything-with-alt` no longer toggles commit messages on the commits page.

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/2eb42b72-84d0-4241-bd9b-93bf0e870edd

</details>

The commit message selector defined in the feature is `.TimelineItem .ellipsis-expander`, but at the moment the commits list uses a different button:
```html
<button class="Button Button--iconOnly Button--invisible Button--small" data-testid="commit-row-show-description-button" aria-labelledby="show-description-d74da84" aria-pressed="false" aria-expanded="false" tabindex="0">
   <svg aria-hidden="true" focusable="false" role="img" class="octicon octicon-ellipsis" viewBox="0 0 16 16" width="16" height="16" fill="currentColor" style="display:inline-block;user-select:none;vertical-align:text-bottom;overflow:visible">
      <path d="M0 5.75C0 4.784.784 4 1.75 4h12.5c.966 0 1.75.784 1.75 1.75v4.5A1.75 1.75 0 0 1 14.25 12H1.75A1.75 1.75 0 0 1 0 10.25ZM12 7a1 1 0 1 0 0 2 1 1 0 0 0 0-2ZM7 8a1 1 0 1 0 2 0 1 1 0 0 0-2 0ZM4 7a1 1 0 1 0 0 2 1 1 0 0 0 0-2Z"></path>
   </svg>
</button>
```

### How to replicate the issue + URL

Try to toggle commit messages with alt on the commits page

https://github.com/torvalds/linux/commits/master

### Extension version

24.8.3

### Browser(s) used

Firefox, Chrome

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by kovsu** [comment]
the `.list-view-item` selector all be affected.
 
https://github.com/search?q=repo%3Arefined-github%2Frefined-github%20.list-view-item&type=code
