### ISSUE TITLE
`default-branch-button`: Branch name or commit hash is truncated

### ISSUE THREAD

**Issue by injust** [refined-github/refined-github#7681]
### Description

When the button for this feature is added, the branch name or commit hash is truncated, even though visually there is enough room for the full branch name/commit hash to be displayed.

![image](https://github.com/user-attachments/assets/75f8994c-8480-4352-8c9f-26606d454dc4)

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/blob/74d86d37d7301719e0d9bd6536c52e32379e78e8/source/features/default-branch-button.tsx

### Extension version

24.8.13

### Browser(s) used

Chrome

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Indeed this issue can even be seen in my own gif: https://github.com/refined-github/refined-github/pull/7403

Cause: https://github.com/refined-github/refined-github/pull/6249

https://github.com/refined-github/refined-github/blob/51b867bf47a95569a4d13ddaaaff161c288a5910/source/features/default-branch-button.css#L1-L4
