### ISSUE TITLE
`tags-on-commits-list`: Cannot read properties of undefined (reading 'pathname')

### ISSUE THREAD

**Issue by eranb-di** [refined-github/refined-github#7682]
### Description

```
TypeError: Cannot read properties of undefined (reading 'pathname')
    at getCommitHash (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:6125:35)
    at init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:7411:134)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:3119:28
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:3115:64
    at Array.map (<anonymous>)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:3115:45
    at runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:3116:10)
    at setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:3131:43)
    at async chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:3156:11
```

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/commits/main/

### Extension version

24.8.13

### Browser(s) used

Google Chrome 127.0.6533.100 (Official Build) (64-bit)

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by eranb-di** [comment]
Updated the browser type
Thanks :)

**Comment by kovsu** [comment]
<img width="500" alt="image" src="https://github.com/user-attachments/assets/4ec7b4b3-8601-47ec-b95a-8a03c886f80c">


the `.list-view-item` selector all be affected.
 
https://github.com/search?q=repo%3Arefined-github%2Frefined-github%20.list-view-item&type=code

**Comment by fregante** [comment]
I think we can use `[role="listitem"]`, but a bit more specific to the commit list

**Comment by kovsu** [comment]
Will it be dropped one day if use `[data-testid="commit-row-item"]` ?

**Comment by fregante** [comment]
Nothing is guaranteed. We can try though
