### ISSUE TITLE
Wrong `highest-rated-comment` if there's >1 reactions

### ISSUE THREAD

**Issue by TonyRL** [refined-github/refined-github#7687]
### Description

The highest rated comment should be the one from [Tennyleaz](https://github.com/Tennyleaz) (42 upvotes) instead of the one from [xromansx](https://github.com/xromansx) (12 upvotes).
<details>
<summary>Screenshot</summary>

![Screenshot](https://github.com/user-attachments/assets/5007c283-f2eb-4df5-855b-3d71c801291d)
</details>

<details>
<summary>Screenshot 2</summary>

![Screenshot 2](https://github.com/user-attachments/assets/c56b05dd-e545-46b2-afae-b656326c200b)
</details>

### How to replicate the issue + URL

Visit: https://github.com/netbirdio/netbird/issues/363

### Extension version

24.8.13

### Browser(s) used

FireFox v129.0.1

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
It is the 42 upvotes for me

![image](https://github.com/user-attachments/assets/fe8255a3-5f34-434a-a305-505eb7a94403)

**Comment by TonyRL** [comment]
This works fine on Chromium-based browsers (v118 and v127).

**Comment by fregante** [comment]
Does it happen consistently? Or just sometimes?

**Comment by fregante** [comment]
I can't repro in Firefox either, Refined GitHub v24.8.13 and the previous v24.8.3

<img width="634" alt="Screenshot 8" src="https://github.com/user-attachments/assets/183fe1d5-6a45-4b21-9bca-44dc497731a3">

The feature waits for the whole page to be loaded too, so this shouldn't be a race condition either. Do you have other extensions?

Does it happen at every load of https://github.com/netbirdio/netbird/issues/363 or just sometimes?

**Comment by fregante** [comment]
Could something like this have been the problem? Are you logged into GitHub when the issue occurs?

GitHub sometimes trims the reactions and I don’t think we support this DOM

![IMG_4703](https://github.com/user-attachments/assets/5d40373b-f4d7-4fe2-a151-63bf34e95a63)

**Comment by TonyRL** [comment]
> Do you have other extensions?

...I've tried disabling all extensions except Refined GitHub and it's still picking up the 12 upvotes one...

_Originally posted by TonyRL in https://github.com/refined-github/refined-github/issues/7687#issuecomment-2290473447_

> Are you logged into GitHub when the issue occurs?

Yes. It's logged in on Firefox. If I log out (or in incognito mode) when visiting that issue, it does pick up the 42 upvotes one.

> Does it happen at every load of https://github.com/netbirdio/netbird/issues/363 or just sometimes?

It happens on every load.

**Comment by fregante** [comment]
Thanks for the repro, but seems to be too niche to work on. Likely the new view will fix it or require a rework of the feature anyway.

- #7856
