### ISSUE TITLE
Unable to export Options… to JSON for Enterprise servers

### ISSUE THREAD

**Issue by mobilemind** [refined-github/refined-github#7688]
### Description

The Export option always exports the json for GitHub.com, even if you change the drop-down menu at the top to an enterprise server before clicking Export. Valid personal access tokens exist for both the GitHub domain and the Enterprise server domain. The GitHub Enterprise server is GitHub Enterprise Server 3.9.

No console errors are indicated in the console for the  original (settings) tab or the console with the replacement content and the `data:application/json` URL.

 In the attached example, I've redacted the Enterprise server, user account, the personal access token (except for the last few characters), and modified the action URL Hoeever you can see it is not exporting 

Notice that the token and action URL from the Refined options (settings) are not what appears in the JSON export.

![Refined-options](https://github.com/user-attachments/assets/f6f08011-f63c-42ff-a8e2-85177a2c3f9f)

![Refined-export](https://github.com/user-attachments/assets/e3cb92f3-c861-4731-83d9-05352bd89375)

### How to replicate the issue + URL

https://ENTERPRISE-SERVER.github.ENTERPRISE-DOMAIN.com

### Extension version

24.7.10

### Browser(s) used

Safari  17.6 (Mac)

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Thanks for the report! I think this is the bug:

- https://github.com/fregante/webext-options-sync/issues/75

**Comment by mobilemind** [comment]
This fix seems to have broken the ability to add and use separate tokens for GitHub.com and an enterprise GitHub domain. If you switch domains and paste in a new token, it replaces the token for both domains with the new one.
