### ISSUE TITLE
Review parts of files, or `git add -p` on a Pull Request's `/files` page

### ISSUE THREAD

**Issue by fenollp** [refined-github/refined-github#7697]
### Description

Large diffs can be exhausting and showing fewer [unrelated] lines of code helps. On the provided `/files` Pull Request URL, GitHub allows checking whole files as `Viewed`. And, while it helps, I feel it could be improved with finer grain `Viewed` possibilities.

* I'd like to reuse the `add-line-comment` / `line-comments` UI elements to allow for marking the selected lines as `Viewed`.
* I have no idea if GitHub's API allows marking parts of files as `Viewed`! Maybe the call takes a range of lines? :crossed_fingers: 

For example when reviewing file `integration-tests/passing/only-noop.strom` in https://github.com/quickstrom/quickstrom/pull/130/files#diff-f00b139e04a3d95de858133a72b87784fda3bf50b6f4a371f9645def7196faab

![image](https://github.com/user-attachments/assets/ae4eb963-906d-43d1-89b0-820ea629865c)

One may want to leave out parts of this file un-reviewed just so they'd continue to appear in the succeeding review rounds, after a number of new commit pushes.

Here I'm showing the multiline selection when adding a review comment and the `Viewed` checkbox I apposed. 
I'm not a fan of this idea UX-wise (checkbox and commenting aren't exclusive (as in xor) actions) but it conveys my point.

![Untitled](https://github.com/user-attachments/assets/9928ad0f-3e91-4e76-837a-3d6b8bb0d1d5)

Here I felt like the top comment should be re-checked later on so I hid the other changes in the file. I don't expect these parts of the file to change in the future of the PR. I do want that, on the next pushes that touch this file, none of the `Viewed` parts show up, unless of course newer changes are entangled with `Viewed` ones.

![image](https://github.com/user-attachments/assets/9e460d98-2c61-42a9-8cbe-97aa7bc3b20e)

### Example URLs

https://github.com/quickstrom/quickstrom/pull/130/files

**Comment by fregante** [comment]
I wish, but that's not possible in Refined GitHub, it would be a whole dedicated extension to recreate and store which chunks you already reviewed.

https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#4-it-doesnt-require-a-lot-of-viewui-code-and-effort-to-maintain
