### ISSUE TITLE
`show-names` is broken on github enterprise 3.11.13

### ISSUE THREAD

**Issue by SuperSandro2000** [refined-github/refined-github#7699]
### Description

I am on a private GitHub Enterprise version 3.11.13 and the show-names features is replacing the names with undefined.

I get the following trace in console:

```
refined-github.js:3397 Uncaught (in promise) Error: GraphQL:
Could not resolve to a User with the login of 'undefined'.
    at Object.v4uncached (refined-github.js:3397:60)
    at async show_names_updateLink (refined-github.js:6239:21)
```

![image](https://github.com/user-attachments/assets/828d2dec-ae78-4e4b-a21e-318d2faf11c5)

I couldn't find the graphql query for this feature in the network tab, only the defaultBranchRef and total count of releases appeared there.

### How to replicate the issue + URL

An equivalent URL on public github where the bug does not appear https://github.com/NuschtOS/nixos-modules/pull/76

### Extension version

24.8.13

### Browser(s) used

Google Chrome 127.0.6533.120

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
I'd accept a quick PR that detects `undefined` and throws an error instead so I can merge it in the next release this week.

**Comment by fregante** [comment]
@SuperSandro2000 can you investigate further? How can this be happening? We have a couple of places where `undefined` would fail before DOM replacement happens.

1. We're exclusively selecting `a` elements, so `textContent` _cannot_ be `undefined` there, it has to be a string, even if empty.
	https://github.com/refined-github/refined-github/blob/6e167b9d881bd05db8cb92a5e140144cda7fd873/source/features/show-names.tsx#L80
3. Right before this replacement happens, we call a function that exclusively works on strings:
	https://github.com/refined-github/refined-github/blob/6e167b9d881bd05db8cb92a5e140144cda7fd873/source/features/show-names.tsx#L47


So it seems to me that this is somehow getting an `'undefined'` string. Given the timing, this is very likely a consequence of:

- https://github.com/refined-github/refined-github/pull/7666

**Comment by SuperSandro2000** [comment]
Derp 🤦🏼 I totally forgot that I have a similar addon installed for our internal GitHub which provides a similar feature but translates our internal IDs to readable github names. When I disabled that addon the bug goes away. The feature in Refined GitHub works as expected but only shows the internal user IDs which is not that helpful 😅 

Big Sorry!

**Comment by fregante** [comment]
Thanks for updating us 😅 🙏
