### ISSUE TITLE
`select-notifications`: dropdown hotkey (`S`)  appears nonfunctional

### ISSUE THREAD

**Issue by ian-h-chamberlain** [refined-github/refined-github#7713]
### Description

Tested on a clean Firefox profile with no other extensions, but I can't seem to get the hotkey working. This console error appeared which seems like it could maybe be related? Disabling `unwrap-unnecessary-dropdowns` doesn't make the hotkey work either though.

```
❌ unwrap-unnecessary-dropdowns
📕 24.8.13 → TypeError: select_dom_$(...) is undefined
    init moz-extension://e218913b-16f4-4b96-a33c-bdf672583ec8/assets/refined-github.js:8674
    runFeature moz-extension://e218913b-16f4-4b96-a33c-bdf672583ec8/assets/refined-github.js:3119
    runFeature moz-extension://e218913b-16f4-4b96-a33c-bdf672583ec8/assets/refined-github.js:3115
    runFeature moz-extension://e218913b-16f4-4b96-a33c-bdf672583ec8/assets/refined-github.js:3115
    runFeature moz-extension://e218913b-16f4-4b96-a33c-bdf672583ec8/assets/refined-github.js:3116
    setupPageLoad moz-extension://e218913b-16f4-4b96-a33c-bdf672583ec8/assets/refined-github.js:3131
    add moz-extension://e218913b-16f4-4b96-a33c-bdf672583ec8/assets/refined-github.js:3157
    async* moz-extension://e218913b-16f4-4b96-a33c-bdf672583ec8/assets/refined-github.js:8666
    <anonymous> moz-extension://e218913b-16f4-4b96-a33c-bdf672583ec8/assets/refined-github.js:11762
    <anonymous> moz-extension://e218913b-16f4-4b96-a33c-bdf672583ec8/assets/refined-github.js:11763
````

### How to replicate the issue + URL

1. Navigate to notifications page: https://github.com/notifications
2. a. Press `s` 

**Expected:** "select by" dropdown to expand
**Actual:** sitewide github search focused (this is a global shortcut AFAIK)

2. b. Alternatively, press `shift+S` (this was what I assumed was meant by the capitalization of the hotkey)

**Expected:** "select by" dropdown to expand
**Actual:** nothing happens

### Extension version

24.8.13

### Browser(s) used

Firefox 129.0.1 (64-bit)

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Interesting. It seems that `Shift+S` is just not working. My guess is that they're reserving it for something else, but I don't see any `data-hotkey` elements on the page.

Either we change it to something else (`b` for "by") or we have to use a dedicated `keypress` listener.

Also I think we need to add a `tooltipped` class to show this new shortcut there.
