### ISSUE TITLE
Show user pronouns alongside their name

### ISSUE THREAD

**Issue by WaffleLapkin** [refined-github/refined-github#7717]
### Description

The [`show-names`](https://github.com/refined-github/refined-github/blob/13510c32340b53fc0532e00f6b90a687bf1279bb/source/features/show-names.tsx) feature shows a name alongside the username of a user. It would be nice to have another feature that would add user pronouns alongside their name, so it's easy to know how to refer to a person when writing your own comment.

Here is a mock up:
![image](https://github.com/user-attachments/assets/1d3f50d7-295a-4f7b-b846-92c8105bb46a)
Or maybe pronouns should be separate from the name: 
![image](https://github.com/user-attachments/assets/fb8fb99b-043b-480d-a9e8-c71e458b5a46)

---

Another thing that would be even better, but might also be a lot harder, is to show user pronouns when editing a comment which contains a mention of them. Something like that:
![image](https://github.com/user-attachments/assets/a023c71b-4e83-4dd8-b807-2e472995ec47)

Ideally it would show while _writing_ the comment, but I couldn't come up with a way to sketch it.

---

I think the first part is in scope of refined github, but I'm not sure about the second one.

### Example URLs

https://github.com/rust-lang/rust/issues/129352

**Comment by fregante** [comment]
That would become too long. The pronouns are available in the hovercard already

**Comment by WaffleLapkin** [comment]
@fregante would it? I just scrolled through some issues in my notifications and whatnot, and all users I could find had plenty of empty space in the comment header. I.e. adding pronouns (which are usually short!) would in no way be a problem.

While it's true that the pronouns are present in the hovercard, it's pretty inconvenient to hover over the username. Especially since a lot of the users don't specify their pronouns and as such you'd hover for nothing.
