### ISSUE TITLE
Can't open options in firefox

### ISSUE THREAD

**Issue by vaqxai** [refined-github/refined-github#7732]
### Description

Browser: **Firefox**
OS: **Ubuntu 24.04**
Issue:
Can't open settings. The extension's toolbar button opens github's mainpage, and **clicking on a "options" link anywhere (like the create an issue site) doesn't do anything.**
![image](https://github.com/user-attachments/assets/67c76f17-207f-4fab-b58a-d854b9532020)

P.S. I lied when i checked the box at the bottom of the create-an-issue page, because I can't add a token, because I can't open the options/settings.

### How to replicate the issue + URL

1. Install ubuntu 24.04
2. Install firefox browser
3. Add refined github (from https://addons.mozilla.org/en-US/firefox/addon/refined-github-/)
4. Try to open settings

Not including an URL because this happens... in the browser? Not on a page? If any, it's gonna be https://github.com/

### Extension version

24.8.20

### Browser(s) used

Firefox

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
It works in all three ways for me. Can you check if these work? 

https://github.com/user-attachments/assets/0a9c72ab-9f89-47ee-b651-10dae261a4eb

**Comment by fregante** [comment]
> P.S. I lied when i checked the box at the bottom of the create-an-issue page, because I can't add a token, because I can't open the options/settings.

Believe it or now, [straight to jail](https://www.youtube.com/watch?v=eiyfwZVAzGw)

**Comment by fregante** [comment]
> P.S. I lied when i checked the box at the bottom of the create-an-issue page, because I can't add a token, because I can't open the options/settings.

Believe it or not, [straight to jail](https://www.youtube.com/watch?v=eiyfwZVAzGw)

**Comment by vaqxai** [comment]
Just checked, none of them work. Nothing happens, like if the button wasn't hooked up to anything

**Comment by fregante** [comment]
1. Open https://github.com/refined-github/refined-github/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+open+options
2. Click on this button 

<img width="1026" alt="Screenshot 12" src="https://github.com/user-attachments/assets/2f51d4ad-afdb-4eed-9895-22a4a6352473">


If nothing happens, the background page is not being loaded and I don't know why. You can then open `about:debugging#/runtime/this-firefox` and look for Refined GitHub. You might be able to see more info there, like by inspecting the extension and checking for errors.

Either way, does it work if you close and reopen Firefox?

**Comment by fregante** [comment]
Specifically, if clicking “Preferences” doesn’t open the options, this is a Firefox bug or you’re using an old Firefox version. What’s your current version? Is it exactly Firefox or a fork?

Closing the issue for now because it’s unlikely to be a bug in the extension. The browser should be able to open the options page even without JavaScript because it’s defined in the manifest.
