### ISSUE TITLE
View line-counts of source files in the GitHub file tree

### ISSUE THREAD

**Issue by gabriel-vanca** [refined-github/refined-github#7734]
### Description

An option to view line-counts of source files in the GitHub file tree]

![image](https://github.com/user-attachments/assets/df123c9b-d9c8-4477-abb8-0d5763b9cfa9)

### Example URLs

See this other extension that does this https://github.com/amkhrjee/ghlines

**Comment by fregante** [comment]
The first point of the ["Can you add this feature"](https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22) page linked in the "New issue" template is:


> ## 1. It doesn't already exist as a userscript or extension.
> 
> Use it, support it, extend it. Not everything needs to be part of Refined GitHub.


That extension was updated just 2 months ago

**Comment by fregante** [comment]
You can open an issue on that repo
