### ISSUE TITLE
`toggle-files-button` More and more toggle buttons

### ISSUE THREAD

**Issue by akku1139** [refined-github/refined-github#7737]
## Folder

1. Open GitHub repository
2. Open folder
![image](https://github.com/user-attachments/assets/e0a7407c-85ac-4294-99f5-f4b78b17fa00)
3. Move to another folder (other than repository root)
4. Two toggle buttons is displayed
![image](https://github.com/user-attachments/assets/169b9dbd-5d91-492e-808b-08ad9bc23262)
5. Move to another folder (other than repository root)
6. Three toggle buttons!
![image](https://github.com/user-attachments/assets/2d033b88-383f-41d1-8648-ce4661816bd6)
7. Open another folder and more buttons will be added

## File

1. Open GitHub repository
2. Open file
![image](https://github.com/user-attachments/assets/ceb6296c-4c59-4040-a739-93651bff5c22)
3. Move to another file
4. Two toggle buttons is displayed
![image](https://github.com/user-attachments/assets/8b31faf6-ef3e-4734-80de-4761b5401770)
5. Move to another file
6. Three toggle buttons!
![image](https://github.com/user-attachments/assets/9056cfc4-496f-4e43-bd80-960b537e4f34)
7. Open another file and more buttons will be added
![image](https://github.com/user-attachments/assets/4fc2d593-7e1c-40e5-998f-ccbd718029a9)

Also, the file toggle button is not visible when opening the file directly
even if you move to another file.
(e.g. paste URL. middle mouse button. open link in new tab.)

### How to replicate the issue + URL

https://github.com/zen-browser/desktop

(Probably all repositories)

### Extension version

24.8.20

### Browser(s) used

Firefox Developer Edition

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Probably going to have to revert https://github.com/refined-github/refined-github/pull/7700

cc @kovsu

**Comment by kovsu** [comment]
```ts
const existingButton = elementExists(`.${toggleButtonClass}`, commitsLink.closest('[class^="Box"]')!);
if (existingButton) {
	return;
}
```
How about this way? I run it in my browser, it works fine.

**Comment by fregante** [comment]
I suppose so, but:

- no need to use the second argument of `elementExists`, there can only be one element on the whole page
- this doesn't solve the fact that it also appear on files

As for the second part, due to #6554 it's ok if it _remains_ there, but it shouldn't appear if you open https://github.com/refined-github/refined-github/blob/main/source/manifest.json and refresh the page.

**Comment by kovsu** [comment]
So you mean if we are in a file page, the button shouldn't appear right?

**Comment by fregante** [comment]
There's no file list to toggle there

**Comment by fregante** [comment]
I disabled the feature via hotfix on previous versions to avoid multiple bug reports
