### ISSUE TITLE
Hide unnecessary files

### ISSUE THREAD

**Issue by Richienb** [refined-github/refined-github#7754]
### Description

Migration of this https://github.com/sindresorhus/hide-files-on-github
That project is facing problems with manifest v2 removal

Even if it doesn't fit requirements for inclusion here, could we maybe fork/move it into the refined-github org for continued development by the community?

### Example URLs

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
The repo was archived because there was no interest to maintain it on either side. Feel free to fork it and publish it. You can ask Sindre for the store names too
