### ISSUE TITLE
`pr-branch-auto-delete` - exclude gitflow branches

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7755]
### Description

Until now we’ve been suggesting to enable branch protection so that this feature doesn’t kick in. This advice is still very much valid, but I think we can at least skip auto-deletion when it detects certain branch names:

- develop
- production
- prod
- main (could still be set as secondary to develop or prod)
- master
- release/*

What other names should we exclude?

### Example URLs

https://github.com/refined-github/sandbox/pull/12

**Comment by fregante** [comment]
@Blackman99 any name suggestions? The feature will stay as a default, so don’t suggest changing that.

**Comment by Blackman99** [comment]
From my personal experience, these names might be common:
* v*
* dev
* development
* pre
* next
* stage

**Comment by BasSchoutenTribe** [comment]
- production*
- staging*
- master*
