### ISSUE TITLE
`resolve-conflicts` broken due to import statement

### ISSUE THREAD

**Issue by ndom91** [refined-github/refined-github#7767]
### Description

`resolve-conflicts` is complaining about 

```
SyntaxError: Cannot use import statement outside a module
```

Relating to the `regexJoin` import at the top of the file

### How to replicate the issue + URL

Any merge conflict page on GitHub, i.e.

![image](https://github.com/user-attachments/assets/82966e90-5234-4677-bd02-c04f756cbb43)

### Extension version

24.8.26

### Browser(s) used

Vivaldi (Chrome 126)

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
This is probably easy to fix:

- add `type=module` to the script tag generated in that file
- add node_modules to the `web_accessible_resources`

**Comment by ndom91** [comment]
Awesome thanks a lot for the quick turnaround! I relied on this a lot :blush:

**Comment by fregante** [comment]
Yeah this is a useful feature, I’ll try to release a new version tomorrow
