### ISSUE TITLE
`tags-on-commits-list` only works once per repo

### ISSUE THREAD

**Issue by davidzhuu** [refined-github/refined-github#7774]
### Description

The commit list will only show tags once. Revisiting the commit list for that repo will no longer show tags. You can briefly see the tags show up (likely cached) before it disappears. Clearing the cache will show tags on commit list again (but only one time, per repo).

I am on Safari 18.0 (macOS Sequoia beta), but this issue also occurs in Safari on Sonoma.

### How to replicate the issue + URL

1. Visit any commit list of a repo (e.g. https://github.com/lwouis/alt-tab-macos/commits/master/). Note that the tags show up correctly, where applicable.
<img width="669" alt="tags-on-commit-list-working" src="https://github.com/user-attachments/assets/d44cd7d6-96e2-4580-b489-876c3483e32f">

2. Refresh the page. Tags are no longer shown.
<img width="710" alt="tags-on-commit-list-broken" src="https://github.com/user-attachments/assets/8e9613d5-b3bc-4df6-8ef8-60efab035669">

### Extension version

24.8.20

### Browser(s) used

Safari 18.0 (20619.1.26.31.6)

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
It looks like the tag is added but then React updates the DOM and removes it. Our selector needs to be updated

**Comment by fregante** [comment]
Can no longer repro
