### ISSUE TITLE
Hide SSO banners

### ISSUE THREAD

**Issue by groenroos** [refined-github/refined-github#7779]
### Description

When you belong to an organisation that uses SSO, but aren't currently logged in to SSO, many GitHub UIs will include a very visible banner in the content area "nagging" you to log in to SSO.

This can be a useful reminder when you're on your work laptop, but can become annoying visual noise if you use the same GitHub account for personal projects as well. The call-to-action here is also typically a no-op, in that I can't/won't/shouldn't SSO to a work organisation on a personal device.

I'd like an option in Refined GitHub to hide these SSO banners. Perhaps it can be disabled by default to avoid any confusion.

An alternative approach could be to remove the banners, and instead show a more demure SSO indicator in a more predictable location, e.g. in the navbar.

### Example URLs

URL | Example
-|-
https://github.com/ | <img width="490" alt="Screenshot 2024-09-03 at 18 43 53" src="https://github.com/user-attachments/assets/82d52227-8209-40f5-8672-66d8b02caf77">
https://github.com/notifications | <img width="490" alt="Screenshot 2024-09-03 at 18 35 44" src="https://github.com/user-attachments/assets/e3bbb374-5a01-433e-bc70-276543e81532">
https://github.com/search?o=desc&q=github&s=created&type=issues | <img width="490" alt="Screenshot 2024-09-03 at 18 35 28" src="https://github.com/user-attachments/assets/b17e9dec-ee9a-4423-a677-c53d5fb7ae7b">
https://github.com/groenroos | <img width="490" alt="Screenshot 2024-09-03 at 18 45 51" src="https://github.com/user-attachments/assets/9ff73107-d620-4015-9918-0e31b46d9daf">

**Comment by fregante** [comment]
I think it's a piece of information that is important for the user to know. If it gets annoying after you already know it you can apply some CSS to manually hide all of them, we try not to hide "important information" in Refined GitHub.
