### ISSUE TITLE
Table View Broken

### ISSUE THREAD

**Issue by gabriel-vanca** [refined-github/refined-github#7780]
### Description

This extension breaks the table alignment when used together with https://github.com/softvar/enhanced-github

![image](https://github.com/user-attachments/assets/b6f0def6-7329-42bd-91cc-74998dddd65a)

### How to replicate the issue + URL

use with https://github.com/softvar/enhanced-github

### Extension version

24.8.30

### Browser(s) used

Edge

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by gabriel-vanca** [comment]
Created matching issue in that repo too: https://github.com/softvar/enhanced-github/issues/146

**Comment by fregante** [comment]
Given we only change the color of the text and not the layout I’m going to close this
