### ISSUE TITLE
`embed-gist-via-iframe`: Cannot read properties of undefined (reading 'cloneNode')

### ISSUE THREAD

**Issue by Pouya-moh** [refined-github/refined-github#7781]
### Description

```
TypeError: Cannot read properties of undefined (reading 'cloneNode')
    at init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/features/embed-gist-via-iframe.js:9:40)
    at async chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/feature-manager.js:186:14
```

### How to replicate the issue + URL

https://gist.github.com/fregante/5b239118cd2aaf001b0d33d54166cd95

### Extension version

24.8.30

### Browser(s) used

Version 127.0.6533.72 (Official Build) (64-bit) on Ubuntu 22.04

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

---
**EDIT** -- Further information:
- In Chorme Version 128.0.6613.84 (Official Build) (64-bit) on Ubuntu 20.04 also doesn't work and throws console error.
- In Firefox 129.0.2 on Ubuntu 20.04 also doesn't work with console error `24.8.30 → TypeError: embedViaScript is undefined`

**Comment by fregante** [comment]
Works for me in Safari, v24.8.20, but not in Chrome, v24.8.30 (no console errors though)

<img width="909" alt="Screenshot 3" src="https://github.com/user-attachments/assets/c298ec40-d40a-411e-a617-5f03d28ff2fe">
