### ISSUE TITLE
Show/keep "Add single comment" button on existing comments during review

### ISSUE THREAD

**Issue by ST-DDT** [refined-github/refined-github#7783]
### Description

Currently, you can only answer to a comment, either before a reviews starts or after it was submitted (or have a random comment floating in the review that cannot be resolved.

Before review:

![grafik](https://github.com/user-attachments/assets/d8382b02-448b-449d-9c36-cdeda0c0a07b)

During review:

![grafik](https://github.com/user-attachments/assets/23725842-9da0-4f68-8782-a6ca5d330552)

After review:

![grafik](https://github.com/user-attachments/assets/0582797b-4ede-44c3-8d53-d037c6d15bbe)

So I would like to retain the ability to just comment on an existing comment, without it being part of the new review.

### Example URLs

https://github.com/ST-DDT/faker/pull/21

**Comment by fregante** [comment]
As far as I know, this is a GitHub limitation and not a UI limitation. The server knows that a review is in progress so any "single comments" will always be appended to it.

A related feature request:

- https://github.com/refined-github/refined-github/issues/5394
