### ISSUE TITLE
`clean-conversation-sidebar` broken in repos with triage access

### ISSUE THREAD

**Issue by KaelWD** [refined-github/refined-github#7784]
### Description

Labels shows an unstyled `<details>` and milestone/projects/branches is missing:

![Screenshot_20240905_185600](https://github.com/user-attachments/assets/77d5b337-724e-4dc6-8b09-1fb65a722e94)

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/issues/7784

### Extension version

24.8.30

### Browser(s) used

Chrome 127.0.6533.99

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/7283
