### ISSUE TITLE
`closing-remarks` saying "doesn't appear in any tags" when it does appear in two tags

### ISSUE THREAD

**Issue by aryairani** [refined-github/refined-github#7787]
https://github.com/unisonweb/unison/pull/5332

<img width="851" alt="image" src="https://github.com/user-attachments/assets/5884b40a-34b5-4eb4-9532-7d34dbabda15">

https://github.com/unisonweb/unison/commit/9af301da7fddfa21bb7b3b8b7b34cbbc14cb1e2a

<img width="669" alt="image" src="https://github.com/user-attachments/assets/445103f0-add7-4bd2-aeec-6109b7be349d">

I was expecting it to show at least the `release/0.5.26` tag, visible in the merge commit screenshot.

**Comment by fregante** [comment]
If you click the info icon you’d know why.

**Comment by fregante** [comment]
As for the released tag, it’s just a cache issue. It works:

![IMG_5189](https://github.com/user-attachments/assets/a4154a5d-d367-447a-b54a-3b54462dfc75)

**Comment by aryairani** [comment]
> If you click the info icon you’d know why.

Hm, I did click on the info icon but still didn't know why neither tag was showing.  Here's what it says when you click the info icon:

> The feature asks GitHub what tags the merge commit appears in and it will show the first one in the list. Number-less tags and "nightly" tags are excluded.
>
> There are a number of limitations we face:
>
> Tags are sorted alphabetically, the first one is picked. If you tag your repo consistently this is not an issue
> The sorting cannot be changed, we just [fetch it from GitHub](https://github.com/refined-github/refined-github/issues/7208#issuecomment-1923390182)
> The exact merge commit needs to appear under the tag, rebased commits are ignored

I tag my repo consistently and the exact merge commit appears under the tag.

**Comment by aryairani** [comment]
> It’s just a cache issue. It works:

Thanks — is there some way to clear the cache when this is happening? https://github.com/unisonweb/unison/branch_commits/9af301da7fddfa21bb7b3b8b7b34cbbc14cb1e2a was already showing the right results at the time.
