### ISSUE TITLE
Keyboard shortcut to edit issue/PR title

### ISSUE THREAD

**Issue by catdevnull** [refined-github/refined-github#7788]
### Description

would love to have a shortcut (maybe "e"?) to quickly edit an issue's or PR's title 

### Example URLs

any issue that you have edit rights to, for example https://github.com/refined-github/refined-github/issues/7787

**Comment by fregante** [comment]
Keys are limited and actions are many. We’ve been asked to assign the e key to edit comments before. This action is even less common than that one
