### ISSUE TITLE
How to collapse the right sidebar on issues and pull requests?

### ISSUE THREAD

**Issue by ElijahLynn** [refined-github/refined-github#7801]
How to collapse the right sidebar on issues and pull requests?

![screenshot-20240910-09-56-28-PT](https://github.com/user-attachments/assets/ee34108a-160b-4b53-95d6-81645c360655)

**Comment by fregante** [comment]
We don’t have that feature here

**Comment by ElijahLynn** [comment]
Thanks for that reply. Is that something we could consider for a feature request? If so I can open a new issue for that.

**Comment by fregante** [comment]
I don’t see the use for collapsing sections. We recently removed a feature that collapsed files too

**Comment by ElijahLynn** [comment]
> I don’t see the use for collapsing sections. We recently removed a feature that collapsed files too

Okay, thanks for the feedback. 

I suppose maybe what I am wanting is more like a zen mode for people with ADHD. For example we have a feature to remove a bunch of the issue updated noise, it would be kinda like that. To help me focus on the issue and tasks inside the issue.
