### ISSUE TITLE
`clean-conversation-headers` removes author from sticky header 

### ISSUE THREAD

**Issue by bartgol** [refined-github/refined-github#7802]
### Description

When scrolling down on a PR, a part at the top is anchored, showing the PR name and, below something like "userXYZ wants to merge N commits into main from my-feature-branch".

However, I  don't see the user name anymore. The line simply says "wants to merge ...". I tried to use the "identify feature" feature of refined gh, and during the identification process I _do_ see the user name in certain iterations. At the end of the identification process, refined gh tells me the feature I'm looking for is "expand-all-hidden-comments". It seemed odd, but I gave it a try and disabled that option, but the bug still persist (i.e., no user name in the top portion).

I'm attaching two screenshots, one during the identification process (at the end) and one outside of the identification process.

![after-identify-feature](https://github.com/user-attachments/assets/c7d097e4-d4bc-433e-92d6-41e96f07a06f)
![outside-identify-feature](https://github.com/user-attachments/assets/c7fde135-0eb9-42f5-9ecb-a53a4e7c22c2)

### How to replicate the issue + URL

Here's the PR I was looking at, but I seriously doubt it's a repo-specific issue, since I notice this on all repos...

https://github.com/E3SM-Project/scream/pull/2980

### Extension version

24.8.30

### Browser(s) used

Chrome Version 127.0.6533.99 (Official Build) (64-bit)

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Indeed. We remove it from the main header because the author is available 100px below it, in the PR description. For the sticky header this logic doesn’t apply so we should restore it.
