### ISSUE TITLE
`more-dropdown-links` duplicated on security tab

### ISSUE THREAD

**Issue by Snoopy1866** [refined-github/refined-github#7806]
### Description

![image](https://github.com/user-attachments/assets/89c543a6-6a30-4a4a-a088-68f4f3433f72)

Look at the picture, when I click (correctly speaking, switch click) the left tabs for _N_ times, the buttons displayed in the top-right three dots also repeated _N_ times.

### How to replicate the issue + URL

**How to replicate**: same as description
**URL**: all public repo's security page, for example: https://github.com/PyStatPower/PyStatPower/security

### Extension version

24.8.30

### Browser(s) used

Chrome 128.0.6613.138

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Likely due to the console error:
```
undefined is not an object (evaluating 'menuItem.removeAttribute')
onlyShowInDropdown@webkit-masked-url://hidden/:44:10
```

**Comment by kovsu** [comment]
It's a wired thing. It only happen on `security-tab`.

**Comment by kovsu** [comment]
It's a weird thing. It only happens on `security-tab`.

**Comment by fregante** [comment]
Likely reason:

https://github.com/refined-github/refined-github/blob/9a70bc1ea2aded61e311eddb275c6efc24baff86/source/features/clean-repo-tabs.tsx#L21

It should also happen on the Insights tab, but AJAX navigation fails there so our code runs on a fresh document every time.

**Comment by kovsu** [comment]
I'm trying use `observe` in `more-dropdown-links`. It doesn't have the problem. What's your opinion? @fregante 

https://github.com/user-attachments/assets/21d87ded-6006-4b7c-a42d-aea986f0ac5f

**Comment by fregante** [comment]
I think it fails the overflow logic. When you resize the window, GitHub's code will hide the tab and show the item in the dropdown. If the item hasn't been added yet it will fail.

**Comment by fregante** [comment]
Oh sorry I got confused. Maybe it's not relevant here. I'm not sure how it's relevant to this issue
