### ISSUE TITLE
Bisect link to "CSS-only feature" is broken

### ISSUE THREAD

**Issue by sersorrel** [refined-github/refined-github#7807]
### Description

The bisect popup links to the wiki page "Undo-unwanted-styles":

https://github.com/refined-github/refined-github/blob/2583024c7f8eb01ebd74d339849f1d551af80c70/source/helpers/bisect.tsx#L38

but that page doesn't exist.

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/wiki

### Extension version

24.8.30

### Browser(s) used

Firefox 130

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
The page was removed. The link can be dropped too. PR welcome
