### ISSUE TITLE
Support ⌘D in text areas

### ISSUE THREAD

**Issue by privatenumber** [refined-github/refined-github#7811]
### Description

<kbd>Cmd+D</kbd> is a common shortcut in IDEs to quickly multi-select:
https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor

Since a lot of IDE features are supported in GitHub's Markdown text area, I always expect it to work but it doesn't. It would be nice if this can be supported.

### Example URLs

Any page with a Markdown editor text area. For example:
https://github.com/refined-github/refined-github/issues/new

**Comment by fregante** [comment]
There’s no way to do multi-selections in browsers, you’d have to load a whole editor like CodeMirror. There are some extensions that do that and they have drawbacks
