### ISSUE TITLE
Add dark and tinted icons support in iOS app

### ISSUE THREAD

**Issue by rakleed** [refined-github/refined-github#7818]
### Description

Could you please add support for dark and tinted icons in iOS app?

Useful link: https://developer.apple.com/design/human-interface-guidelines/app-icons#iOS-iPadOS

![IMG_6031](https://github.com/user-attachments/assets/fb9ccf98-d8c3-4bae-bc70-c2fdf95a5975)

### Example URLs

N/A

**Comment by fregante** [comment]
It’s not really something that matters since you never need to use the app, but I think this would be an easy change. Cc @sindresorhus 


![IMG_5695](https://github.com/user-attachments/assets/e9559c10-8ced-48f0-9314-6e8ec2ba7f24)
