### ISSUE TITLE
`batch-mark-files-as-viewed`  ignores current file filter

### ISSUE THREAD

**Issue by kopach** [refined-github/refined-github#7819]
### Description

Mark/unmark multiple files as “Viewed” in the PR Files tab Feature ignores "hidden" files
It wasn't the case before.

### How to replicate the issue + URL

Go to thi URL:
https://github.com/refined-github/refined-github/pull/7813/files
1. In file filter hide `*.md` file.
2. mark first file as viewed
3. holding "shift" - mark last file as viewed
4. clear all filters
5. observe as hidden `*.md` file is also selected

Expected
Only visible files shoud be selected

### Extension version

24.9.21

### Browser(s) used

Firefox 130

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by kopach** [comment]
Same case for Toggle All while holding `ALT` key

**Comment by fregante** [comment]
Related:

 - https://github.com/refined-github/refined-github/issues/6764

**Comment by fregante** [comment]
Relatively easy, just add `&& file.checkVisibility()` here:

https://github.com/refined-github/refined-github/blob/c6054c02414af028a51582b76e7c6ab7836130d0/source/features/batch-mark-files-as-viewed.tsx#L42
