### ISSUE TITLE
Some features dont work in the florisboard organisation

### ISSUE THREAD

**Issue by lm41** [refined-github/refined-github#7820]
### Description

Hello,
when looking at repositories in the florisboard organisation some of the features aren't working.
I've created a personal access token with the standard settings except the delete-repo permission as i'm not using that feature.
For example, the release tab at the top is not displayed, or the repo-header-info right next to the repo name.
![image](https://github.com/user-attachments/assets/ae50749a-9098-42b0-a1d0-fe1293fa9a0b)
Those features are working in other organisations I'm a member in. https://github.com/goxlr-on-linux/goxlr-utility
![image](https://github.com/user-attachments/assets/0e661eca-d3b3-48c1-b75b-1491504b2bfc)

### How to replicate the issue + URL

Just go to the repository and the features aren't there :man_shrugging: 
https://github.com/florisboard/florisboard

### Extension version

24.9.21

### Browser(s) used

Firefox, Iridium (Chrome)

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by lm41** [comment]
![Screenshot_20240923-145054.png](https://github.com/user-attachments/assets/a657e383-f951-4c34-94c1-b8cdd179ce05)

...

**Comment by fregante** [comment]
I see features working:

<img width="402" alt="Screenshot" src="https://github.com/user-attachments/assets/9afaaafa-6493-473e-ab8c-93b5eee79c5f">

**Comment by fregante** [comment]
Check for errors in the console. This is likely to be a token issue. Since you're part of the org, maybe the token is disabled for it internally.

**Comment by lm41** [comment]
Weird. 
I've tested it with 2 different browsers on 2 different PCs with and without incognito mode on. Could it be that my personal access token is broken for this organization?

**Comment by fregante** [comment]
Likely a restriction within the organization: https://docs.github.com/en/organizations/managing-programmatic-access-to-your-organization/setting-a-personal-access-token-policy-for-your-organization#enforcing-an-approval-policy-for-fine-grained-personal-access-tokens

The restriction doesn't apply to me because the repo is public and my access is read-only; my guess is that since your account has write access, the organization is able to block it entirely.

**Comment by patrickgold** [comment]
Hey there,

admin of the `florisboard` org here. We were able to fix the issue, it was indeed an issue with the token settings of the org. In particular: Going to `Organization settings > Personal Access tokens > Settings > Tokens (Classic)` you can restrict the usage of classic tokens:

![image](https://github.com/user-attachments/assets/78217a01-161d-418e-936f-f155c5f70d6e)

Then Refined GitHub does not work on repos for that org. Allowing it fixes the issue and Refined works without issues.
