### ISSUE TITLE
Highlight on `default-branch-button` feature is distracting

### ISSUE THREAD

**Issue by anoadragon453** [refined-github/refined-github#7821]
### Description

While reading a rendered markdown document that's on a non-default branch today, I saw that the branch name was now highlighted in the UI. This is https://github.com/refined-github/refined-github/pull/7804

The page I was on: https://github.com/matrix-org/matrix-spec-proposals/blob/andybalaam/owner-state-events/proposals/3757-restricting-who-can-overwrite-a-state-event.md

Screenshot:

![image](https://github.com/user-attachments/assets/958b9131-a0fa-4454-a49d-735861242dec)

While this is a new change, and I may get used to it after a few days, my immediate reaction was that it was distracting while scrolling down the page (as it's in a sticky header).

Personally I don't find this change too necessary -- the presence of the back button already signalled to me that I wasn't on the default branch. But if some people found that more highlighting was needed, perhaps we could do so some other way?

### Example URLs

https://github.com/matrix-org/matrix-spec-proposals/blob/andybalaam/owner-state-events/proposals/3757-restricting-who-can-overwrite-a-state-event.md

**Comment by fregante** [comment]
Yeah the idea was to make it immediately obvious that you're seeing content that is not on `main`, as generally you'd want to see the latest version (or be aware that it is not.)

For this to happen, it has to _distract_ you. The previous button _informed_ you if you looked at it but it didn't _warn_ you.

We just need to find the right compromise between the GitHub default (zero information) and the most distracting design (`<blink>UR NOT ON MAIN</blink>)`

I think the current style has the right amount of distraction, but I'm open to exploration.
