### ISSUE TITLE
How to disable auto adding `type=source` in `Repositories` tab?

### ISSUE THREAD

**Issue by SherkeyXD** [refined-github/refined-github#7823]
When I open `Your Repositories`, or other people's `Repositories` tab, `type=source` is automatically added to the url, making it looks like `https://github.com/{USERNAME}?tab=repositories&type=source`, and the tab become like this

![image](https://github.com/user-attachments/assets/1b117550-e3b3-4251-baba-8e6ed02b727d)

Is there any way to turn this off? I've tried searching `Repositories`, `source` and `sort` in the settings, but none of them seems to match the function.

**Comment by fregante** [comment]
`hide-user-forks`

**Comment by fregante** [comment]
In the future you can use the “identity feature” button in the Debugging section
