### ISSUE TITLE
Keep sensitive settings as GitHub defaults

### ISSUE THREAD

**Issue by Ender-Wang** [refined-github/refined-github#7832]
### Description

- I would strongly suggest keeping sensitive github settings as default in redined-github, or having a walk-through when installing the extension to changes default github behavior such as PR head branch auto delete.
- Correct me if I am wrong, installed this amazing extensions a long time ago, cannot really remember if I was prompted to check the PR head branch auto delete.
- I thought there were some actions or branch settings or default settings do delete the head branch after PR merged, then I checked all of them, and just realized that I have refine-github installed (Gotta admit, you are doing an amazing job with this extension! I haven't even realized it's a third party tool lmao).

- Post Edit: I did not see "via Refined GitHub" in the branch delete log as shown in the official demo screenshot:
![image](https://github.com/user-attachments/assets/3e4b1c48-7d4b-4955-8016-14252b24aa7c)
Instead, I just got:
![CleanShot_2024-09-26_11-38-47](https://github.com/user-attachments/assets/d6288603-6f7c-4e84-af28-ed6782f9e5e0)

### Example URLs

![CleanShot_2024-09-26_11-27-51](https://github.com/user-attachments/assets/24cb4261-84f5-4605-914d-a20062781aca)

**Comment by fregante** [comment]
Discussed many times
