### ISSUE TITLE
`download-folder-button` appears redundant next to native "Download zip"

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7834]
### Description

Not sure why we're adding it there. All "repo root" pages have a "download zip" button so we shouldn't add it to that dropdown. 

<img width="273" alt="Screenshot 7" src="https://github.com/user-attachments/assets/562d6361-fef0-45ee-92df-085ff97ae2b6">

### How to replicate the issue + URL

See in "Code" dropwodn

https://github.com/sindresorhus/eslint-plugin-unicorn/tree/version-46

### Extension version

24.8.20

### Browser(s) used

Safari

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by kovsu** [comment]
https://github.com/refined-github/refined-github/blob/3f63d52736565dcf501725a91640a52a7cbd0783/source/features/download-folder-button.tsx#L23

👆 It's the reason.

**Comment by fregante** [comment]
Where is it even taking `a[aria-keyshortcuts="d"]` from?? It's not on the page
