### ISSUE TITLE
`repo-age`: 

### ISSUE THREAD

**Issue by stephenjason89** [refined-github/refined-github#7840]
### Description

When you create a new repository it caches the repo age and first commit indefinitely using cacheByRepo.
The issue arises when you delete the repo and create a new one. It still references the old commits from the old repo.

### How to replicate the issue + URL

Try it here https://github.com/stephenjason89/bun-pulse

Clicking the repo age results in
<img width="1121" alt="image" src="https://github.com/user-attachments/assets/ebdb3f63-cd1e-4cf7-b937-b4fd81cfc69d">

I think we should invalidate the cache every so often.

### Extension version

24.9.21

### Browser(s) used

edge

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Thank you for the repo, but deleting, re-recreating and clicking the repo age isn't something that happens often. This is just a drawback of cache.

**Comment by stephenjason89** [comment]
@fregante It is the same case when you force push to override your initial commit.

**Comment by stephenjason89** [comment]
@fregante It is the same case when you force push to override your initial commit. Perhaps we can invalidate cache at a much longer time period instead of having it indefinitely?

**Comment by stephenjason89** [comment]
Thank you for your response, @fregante. While I was waiting, I went ahead and created a PR that sets the maxAge of webext-storage-cache to 30 days. I wasn't aware that the cache is set to indefinite by default and had assumed it was. Please let me know if this PR is necessary, or feel free to close it if it's not.
