### ISSUE TITLE
`select-notifications`: misaligned

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7852]
### Description

It’s hard to tell? But I think it’s 1-2 pixel higher. This should be fixed by letting the browser align by baseline rather than tweaking via +1px/-1px

![IMG_5876](https://github.com/user-attachments/assets/0a5e6287-6e5e-431b-af42-016cd3f95aae)

### How to replicate the issue + URL

https://github.com/notifications

### Extension version

24.8.20

### Browser(s) used

Safari

**Comment by AbhinRustagi** [comment]
I'd be happy to work on this

**Comment by AbhinRustagi** [comment]
@fregante This isn't being duplicated on my Safari

**Comment by fregante** [comment]
This issue isn't about duplication
