### ISSUE TITLE
`default-branch-button`: Button has pink corruption on GHES

### ISSUE THREAD

**Issue by JakeMerdichAMD** [refined-github/refined-github#7857]
### Description

On Github Enterprise Server, the `default-branch-button` feature causes the branch button to appear with pink corruption. 

![image](https://github.com/user-attachments/assets/0e162988-074c-44ce-b09c-e15fad31dcdf)

### How to replicate the issue + URL

1. Have access to a GHES server (3.12.7)
2. Ensure a PAT for the server is added to the extension
3. Navigate to the equivalent of https://github.com/refined-github/refined-github/tree/sandbox/keep-branch
4. Observe ugly pink corruption.

### Extension version

24.10.1

### Browser(s) used

Firefox (130.0 Win64)

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
`fuchsia` is doing its job 😁 

- https://github.com/refined-github/refined-github/pull/7804#issuecomment-2357444089

This is likely due to the lack of old variables names. Presumably this specific commit should be reverted: [`11f51bc` (#7804)](https://github.com/refined-github/refined-github/pull/7804/commits/11f51bcf9ba0e5fbce5e4aa3bf8cb925e9bcf122)

Can you try those variable names?

**Comment by fregante** [comment]
It should look like this in the end. Finding the right names for the variables is the challenge.


<img width="937" alt="image" src="https://github.com/user-attachments/assets/881a53fd-9765-4769-8e7a-c16dfd06a6c4">

<img width="914" alt="image" src="https://github.com/user-attachments/assets/1485adb1-30d4-4cb3-b6a8-97e0a016709a">

<img width="917" alt="image" src="https://github.com/user-attachments/assets/ac0e084d-4f6e-4176-b0b4-4ad507453845">

<img width="926" alt="image" src="https://github.com/user-attachments/assets/99b630dd-9e40-4e78-9402-5da9ecfb71c8">

**Comment by fregante** [comment]
Great! How does that exact CSS look on the light theme?

**Comment by JakeMerdichAMD** [comment]
Just like your image, as far as I can tell.

GHES:
![image](https://github.com/user-attachments/assets/020868eb-14cb-44f1-aa79-ec978a40ad8d)
![image](https://github.com/user-attachments/assets/364ee815-24f3-4c57-87e0-b822a043db9b)

Cloud:
![image](https://github.com/user-attachments/assets/9e3cfb6a-1f06-4069-8b2d-139e79e48c23)
![image](https://github.com/user-attachments/assets/dbb5eec0-877b-4d1b-bcd9-99954c65995c)


Also see menu does not get incorrect colors on GHES, which I only noticed while testing the CSS:
![image](https://github.com/user-attachments/assets/5e729272-9241-4133-9386-6ad68b31ae29)
Before:
![image](https://github.com/user-attachments/assets/d860957a-3822-4a06-bf87-4bc21889224c)

**Comment by fregante** [comment]
> Just like your image, as far as I can tell.

Thank you! If you have time, I'd accept a PR. Or I'll fix it at some point.

I'll probably hotfix it too in https://github.com/refined-github/yolo

> Also see menu does not get incorrect colors on GHES, which I only noticed while testing the CSS:

That's just because of your selector, it just needs to be `.rgh-highlight-non-default-branch` and `.rgh-highlight-non-default-branch svg` respectively

**Comment by JakeMerdichAMD** [comment]
> That's just because of your selector, it just needs to be .rgh-highlight-non-default-branch and .rgh-highlight-non-default-branch svg respectively

Unfortunately, that does not work-- it's what I showed in the plain revert (though also the menu turns blue instead of pink). 

The specifiers are different because in GHES but not cloud:

 - The full menu is a child of the button, so random parts of it inherit the highlighted color. In cloud, it's not a child.
 - There's a `summary.btn` child that re-applies the normal background and border color instead of inheriting the highlight from the parent (`details.rgh-highlight-non-default-branch`). In cloud, they don't use details/summary so the color not overridden.

I'm not sure if it makes more sense to modify the javascript parts to tweak where the class is applied instead?

**Comment by fregante** [comment]
I think we can just publish some CSS to hide the pink areas and leave the rest as "progressive enhancement". You'll start seeing the correct colors once your GHE version is updated

However I don't know how to do that while also preserving the `fuchsia` for the future.

The second best bet would be to use your suggested code, but with more specific selectors so that they don't leak into the dropdown.

**Comment by busches** [comment]
Not sure what version of GHE OP is using, but I can confirm it's happening on 3.13, which is one minor version behind the latest.

**Comment by JakeMerdichAMD** [comment]
3.12.7 here.
