### ISSUE TITLE
Update instructions in iOS Safari shell app

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7858]
The instructions on the iOS version are a bit out of date. That path kinda works but it has a lot more steps _(like scroll all the way down, find "Extensions" in the huge list of Safari options, look for Refined GitHub in the extension list, open it, enable it, …)_

The steps via the browser may be harder to explain but are way shorter:

<table>
<tr>
<th>Current instructions
<th>Actual flow
<tr>
<td>

![vlcsnap-2024-10-04-23h54m51s328](https://github.com/user-attachments/assets/378e7650-33b6-4b28-b7ab-3d11b48e6bd4)

<td>

https://github.com/user-attachments/assets/d5c73817-2a10-45e0-ba50-ed3948c50e50

</table>

cc @sindresorhus

**Comment by sindresorhus** [comment]
![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-05 at 03 09 31](https://github.com/user-attachments/assets/4ddddc40-2018-4a5a-a132-8d335d09ebc2)

The button opens this repo, so we don't have to explain that the user has to go to GitHub to try it out.

*I'm aware the icon is not 100% the same as the Safari one, but it's as close as I could get and I think it's good enough.*

**Comment by sindresorhus** [comment]
Alternatively, the button could open a super simple webpage that explained the steps to the user. This may be even better as it would be include in Safari and it could even show an arrow to the correct toolbar button. But not sure it's worth the effort, and it would not be something that would be bundled in the app, so it would be work for you.

**Comment by fregante** [comment]
Yeah I was thinking about that. I think it’s worth it, even if I have to set up 3 versions (iOS iPad macOS). The app can then have a “open instructions” button. 

Let’s keep the macOS version unchanged for now, instructions for iOS/iPad are simpler.

**Comment by fregante** [comment]
By the way I think the iOS wrapper can detect whether the extension is enabled, just like on macOS. It would be great to have that so you can show a button depending on the situation:

- Disabled: Show instructions 
- Enabled: See Refined GitHub on GitHub

**Comment by sindresorhus** [comment]
> By the way I think the iOS wrapper can detect whether the extension is enabled, just like on macOS.

No. The API is annoyingly only available on macOS.

> Let’s keep the macOS version unchanged for now, instructions for iOS/iPad are simpler.

We don't need to change macOS, as there we open the extension settings directly.

**Comment by sindresorhus** [comment]
How about this?

![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-05 at 05 38 33](https://github.com/user-attachments/assets/b746e1da-2638-4736-8f21-a014c085821d)

**Comment by fregante** [comment]
A barebones version is now available at:

- https://refined-github.github.io/ios/enable.html
- Source: https://github.com/refined-github/refined-github.github.io/blob/main/ios/enable.html




<table>
<tr>
<td>SE iOS 17
<td>SE iOS 18
<td>16 iOS 18

<tr>
<td>

![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-05 at 18 06 04 Medium](https://github.com/user-attachments/assets/86c03e4d-745d-4d60-9b78-414cd09aeebd)

<td>

![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-05 at 18 06 05 Medium](https://github.com/user-attachments/assets/3bdee60d-c26c-4082-9251-f8bb7204d822)
<td>

![Simulator Screenshot - iPhone 16 - 2024-10-05 at 18 06 15 Medium](https://github.com/user-attachments/assets/79a77f9a-313c-4239-9b38-f79bda7ff5da)


</table>

Claude did most but the arrow was completely out of its reach, so I got one from Google Images.

Next:

- [ ] Point the iOS app to it
- [ ] Flip position on iPad

**Comment by fregante** [comment]
iPad and dark mode ready too

<table><tr><td>

![Simulator Screenshot - iPad (10th generation) - 2024-10-05 at 18 29 20 Medium](https://github.com/user-attachments/assets/dacdad27-e606-4af5-b199-b5140ed5cfb8)

<td valign=top>

![Simulator Screenshot - iPad (10th generation) - 2024-10-05 at 18 29 24 Medium](https://github.com/user-attachments/assets/44b3556b-f23a-4ce5-82a3-73a2b60043d3)

</table>

**Comment by fregante** [comment]
The infortunate part is that Refined GitHub does not have access to GitHub.io, so we can't easily detect whether the extension was enabled on this page. 

But it's ok because the instructions are technically always valid. Once the extension is enabled, the new welcome screen will open:

- #7854 

https://github.com/user-attachments/assets/217de10e-95d3-4671-8d89-0fb1183e3732

**Comment by sindresorhus** [comment]
I was thinking that we just leave the iOS 17 version as is. No point in wasting time customizing for an older OS when the current instructions there already work.

**Comment by sindresorhus** [comment]
> Check again, my other extensions know when they’re enabled in at least one profile.

Only for content blockers: https://developer.apple.com/documentation/safariservices/sfcontentblockermanager/getstateofcontentblocker(withidentifier:completionhandler:)

**Comment by fregante** [comment]
> we just leave the iOS 17 version as is.

That page doesn't have any version-specific setup instructions, why would the app have that? It's the same for everyone. The only thing changed is that on iOS 18 they moved Safari into Apps and the bottom-left icon is different.

**Comment by sindresorhus** [comment]
> That page doesn't have any version-specific setup instructions, why would the app have that? It's the same for everyone. The only thing changed is that on iOS 18 they moved Safari into Apps and the bottom-left icon is different.

Just generally safer. Then you don't have to remember if anything changed. But sure, we'll do it for both OS versions.

**Comment by fregante** [comment]
Can you try to open an extension page on the Get Started button? For example

```
safari-web-extension://D59D52CA-2E3F-47AF-9068-5F012AB92CD9/assets/options.html
```

This is because the button now always points to this instructions page, but the extension has no access to it, so I can't update it dynamically to say "Extension already enabled"

This is what I'd rather have:

1. User taps "Get started"
2. Browser opens to `/assets/launch.html`

This local page will contain:

```js
const destination = await chrome.permissions.contains({origins: ['https://github.com/*']})
	? 'https://github.com/refined-github/refined-github/wiki'
	: 'https://refined-github.github.io/ios/enable.html'

location.replace(destination);
```

**Comment by sindresorhus** [comment]
> Failed to open URL safari-web-extension://D59D52CA-2E3F-47AF-9068-5F012AB92CD9/assets/options.html: Error Domain=NSOSStatusErrorDomain Code=-10814 "(null)" UserInfo={_LSLine=279, _LSFunction=-[_LSDOpenClient openURL:fileHandle:options:completionHandler:]}

Seems like it's not a supported URL scheme, at least from the outside.

**Comment by fregante** [comment]
Yeah even web pages cannot link to them, you'd have to look for a specific API I think. Is there a way to open the options page? I think that could also be a good entry point.

**Comment by sindresorhus** [comment]
> Is there a way to open the options page?

No. Only on macOS.

https://developer.apple.com/documentation/safariservices/sfsafariapplication/showpreferencesforextension(withidentifier:completionhandler:)
