### ISSUE TITLE
`html-preview-link` missing

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7860]
### Description

<img width="879" alt="Screenshot" src="https://github.com/user-attachments/assets/e40a5d22-c1b3-447d-bd90-357a3e99b583">

Side feature request: perhaps we should attempt to use the GitHub.io URL if the repo name has that, like we do for `html-preview-link`

### How to replicate the issue + URL

https://github.com/refined-github/refined-github.github.io/blob/main/ios/enable.html

### Extension version

24.8.20

### Browser(s) used

Safari

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by Lall-091** [comment]
> ### Description
> <img alt="Screenshot" width="879" src="https://private-user-images.githubusercontent.com/1402241/373865227-e40a5d22-c1b3-447d-bd90-357a3e99b583.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MjIwMTMsIm5iZiI6MTcyODUyMTcxMywicGF0aCI6Ii8xNDAyMjQxLzM3Mzg2NTIyNy1lNDBhNWQyMi1jMWIzLTQ0N2QtYmQ5MC0zNTdhM2U5OWI1ODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTBUMDA1NTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWI3MTIxZmJiZjExNWFmYzc1NWZiNjA1OThiNWUwMmIxYjU3NzI0NmNjNTY5OTVjMjBhYTRjMWQ1NWYzNjE0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.DDVl8yytgBVrO678PDxHxSmIXPlXC2mPoBtvNwmGdQM">
> Side feature request: perhaps we should attempt to use the GitHub.io URL if the repo name has that, like we do for `html-preview-link`
> 
> ### How to replicate the issue + URL
> https://github.com/refined-github/refined-github.github.io/blob/main/ios/enable.html
> 
> ### Extension version
> 

> 24.8.20

> 
> ### Browser(s) used
> Safari
> 
> ### Token ⚠️
> * [x]  I set a token in the options page. I understand that some features require a token to work.
