### ISSUE TITLE
Show exact number of stars

### ISSUE THREAD

**Issue by Giorgi** [refined-github/refined-github#7861]
### Description

Repos that have more than 1000 stars don't show the exact number of stars unless you go to `/stargazers` URL of the repo. It will be nice if the exact number can be shown on the main page.

![image](https://github.com/user-attachments/assets/d2f61d30-0463-407f-8378-0cc244dac6ce)

![image](https://github.com/user-attachments/assets/c1048d0d-14aa-41b5-ae16-0c26149f7d00)

### Example URLs

https://github.com/Giorgi/EntityFramework.Exceptions

**Comment by fregante** [comment]
Just hover the number:

<img width="224" alt="Screenshot" src="https://github.com/user-attachments/assets/b04802df-d077-4376-b3b9-6d9afad9a175">
