### ISSUE TITLE
Show all clone URLs at once

### ISSUE THREAD

**Issue by sersorrel** [refined-github/refined-github#7867]
### Description

I often have to clone repos on different machines; some of them have an SSH key I've added to my GitHub account, but others don't. As a result, I end up switching between the "HTTPS" and "SSH" tabs of the clone dialog frequently:

![image](https://github.com/user-attachments/assets/28029293-5363-4784-8093-7419ea836dd6)

which is irritating.

It doesn't take up much more screen space to show both HTTPS and SSH clone URLs, and even the `gh` invocation, simultaneously (if you drop the explanatory text, it actually ends up a few pixels smaller than the original):

![image](https://github.com/user-attachments/assets/db5baf52-92ae-4b25-8fdc-78871d1fb1b3) ![image](https://github.com/user-attachments/assets/2ce07a6d-61ab-42bc-b87c-5cc94038ccbc)

and this is exactly what GitLab does already:

![image](https://github.com/user-attachments/assets/a0b88f5f-371b-4210-a9d0-6e21a834bdd5)

I'd like it if Refined GitHub could bring the GitLab behaviour to GitHub.

### Example URLs

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
It looks like the component creates/destroys the DOM containing each field, so this isn't easily feasible. If GitHub made this possible via CSS, I'd probably be more open to adding this feature.



> some of them have an SSH key I've added to my GitHub account, but others don't

Why not just always use HTTPS? Or `gh-cli`, which gives you the entire command to paste

**Comment by sersorrel** [comment]
> Why not just always use HTTPS?

Unless I'm mistaken, I don't think I can push via HTTPS (since I have 2FA enabled on my GitHub account).

> Or `gh-cli`, which gives you the entire command to paste

similarly to my original point, I can't rely on `gh` being installed on every system I work on.

**Comment by fregante** [comment]
> I have 2FA enabled on my GitHub account

Me too and I use HTTPS exclusively. Basically I think you have to use a token. 
https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git

**Comment by sersorrel** [comment]
hm, ok. I don't think any of the available options really work for me, but thank you for the link!
