### ISSUE TITLE
Add a Copy button to Issue and PR titles and Listviews

### ISSUE THREAD

**Issue by akirk** [refined-github/refined-github#7870]
### Description

When talking about a Github issue somewhere else, it's cumbersome to get a nice link into the clipboard, i.e. a link that has the issue text and the issue number.

A solution would be to introduce a copy icon like it already exists for the branch name that utilizes the browser's [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) for a rich text copy.

These would be the icons:
![Screenshot 2024-10-08 at 15 28 10](https://github.com/user-attachments/assets/6b7cc374-d8d1-4373-bd46-a4191b2520fa)

![Screenshot 2024-10-08 at 15 27 56](https://github.com/user-attachments/assets/b82352fb-9580-4c20-9593-44845973f235)

![Screenshot 2024-10-08 at 15 27 52](https://github.com/user-attachments/assets/75606a2c-fbf2-4b36-bacd-a8e563fcc703)

And this would be the copied text:
[Add a Copy button to Issue and PR titles and Listviews](https://github.com/refined-github/refined-github/issues/7870) #7870

### Example URLs

https://github.com/refined-github/refined-github/issues
https://github.com/refined-github/refined-github/issue/7870

**Comment by fregante** [comment]
What would be the use of this?

**Comment by akirk** [comment]
It's about copying it richtext formated, i.e. using HTML so that it can be pasted in places like Google Docs or other word processors. See my implementation https://github.com/akirk/refined-github/blob/13287f31a57c4ae59daa1ac7771d8ae432a336d8/source/features/copy-issue-link.tsx#L19-L25

**Comment by fregante** [comment]
This seems rather niche. Products used for project management already support link previews, including the current status. For example Notion:

![image](https://github.com/user-attachments/assets/8a7e42ac-8910-47b3-9cc2-b7e048ef1a35)

Google Docs also supports "smart chips" for this purpose: https://developers.google.com/workspace/add-ons/guides/preview-links-smart-chips

Using this add-on for example: https://workspace.google.com/u/0/marketplace/app/link_previews/215545697761

**Comment by fregante** [comment]
Being niche, I'd suggest implementing this via userscript, much easier than adding it here.

**Comment by akirk** [comment]
Here is such a user script: https://gist.github.com/akirk/e92612a35620eafe32f6964f83d2258b
