### ISSUE TITLE
Make default filters configurable

### ISSUE THREAD

**Issue by AbhinRustagi** [refined-github/refined-github#7878]
### Description

The default sorting filter for issues is `sort:updated-desc is:issue is:open`. Just from a user focus pov, this can be made customizable. The user should be able to set this by adjusting the extension settings and those can be stored. This idea can be extended to other areas where default filtering is applied.

### Example URLs

-

**Comment by fregante** [comment]
We don't add configuration to Refined GitHub, see:

https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options
