### ISSUE TITLE
Remove [skip ci] from squash merge message

### ISSUE THREAD

**Issue by sevenc-nanashi** [refined-github/refined-github#7896]
### Description

The commit description of squash merge includes all commit messages in the PR by default.
So, if the PR contains a commit with `[skip ci]`, the merge commit will include `[skip ci]`, thus the Ci will not run.
Here's the example:
![image](https://github.com/user-attachments/assets/48a0c3b0-affb-4b52-90b8-1f95fa426dc3)
![image](https://github.com/user-attachments/assets/cc066602-46e3-4aed-9164-b5de1ce9a07e)

So, it would be great if Refined GitHub removes these `[skip ci]`s in the message from default message.

I've checked guideline:
- 1: I googled around but I couldn't find that
- 2: I think so?
- 3: This feature would not require other options than whether if it's enabled or not.
- 4: I don't think this feature requires so much codes.
- 5: It does not require external server.
- 6: It does not require HTTP traffic.
- 7: It is not for Projects.

### Example URLs

https://github.com/sevenc-nanashi/skip-ci-demo

**Comment by fregante** [comment]
> The commit description of squash merge includes all commit messages in the PR by default.

We already address this in `clear-pr-merge-commit-message`

**Comment by fregante** [comment]
Did you set the token in the options?
