### ISSUE TITLE
"Unexpected end of JSON input" in Personal token input field

### ISSUE THREAD

**Issue by Mollering** [refined-github/refined-github#7897]
### Description

Trying to add a generated token into the field, and get always this error message:
![image](https://github.com/user-attachments/assets/540f417b-f8a6-4068-be71-d0e7025e0d6e)
I can't add a token.

### How to replicate the issue + URL

It happens in the extension options page.
Private domain.

### Extension version

24.10.11

### Browser(s) used

Microsoft Edge for Business Version 128.0.2739.79 (Official build) (64-bit)

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
That's because the API isn't available where we expect it, try opening this in your browser:

```
https://your ghe domain.com/api
```
What does that page show?

Also, what does your GHE base URL look like? Can you teach GitHub's dashboard at `/` or is it in a subfolder?

**Comment by fregante** [comment]
I think I found the bug: https://github.com/refined-github/refined-github/pull/7905
