### ISSUE TITLE
`conversation-activity-filter` dropdown missing from issues

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7901]
### Description

The dropdown is missing:

<img width="519" alt="Screenshot 19" src="https://github.com/user-attachments/assets/16cf814f-eed9-474f-8ec9-5493787afc29">

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/issues/3686

### Extension version

24.10.11

### Browser(s) used

Chrome

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by joshuapease** [comment]
I'm noticing this issue as well.

**Comment by fregante** [comment]
I broke this in August 🥲 the feature only works on PRs now

https://github.com/refined-github/refined-github/pull/7645
