### ISSUE TITLE
Disabling `clean-repo-tabs` and enabling `more-dropdown-links` causes unused horizontal line

### ISSUE THREAD

**Issue by Villy-P** [refined-github/refined-github#7913]
### Description

When option `clean-repo-tabs` is turned off and `more-dropdown-links` is turned on, the horizontal line that should separate the `Security` and `Insights` tab and the more dropdown links is still there, even though it is not separating the two items.

Only `more-dropdown-links`:
![image](https://github.com/user-attachments/assets/f7e1ac8e-dc31-49de-a5ac-5cb3539438fa)

### How to replicate the issue + URL

You can see this on the [Refined Github](https://github.com/refined-github/refined-github) page.

### Extension version

24.10.14

### Browser(s) used

Vivaldi

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Thank you for the report, but it's not a big deal. While we try to keep features from being interdependent, I don't expect people to actually disable them. In this case the two features are actually acting on the same widget so we might even merge them at some point.
