### ISSUE TITLE
`unreleased-commits` suggests drafting a new release even when no rights to do so, redirects to homepage when clicked

### ISSUE THREAD

**Issue by whisperity** [refined-github/refined-github#7919]
### Description

`unreleased-commits` (identified by the add-on's helper feature) adds a `+` button prompting me to create a new release for the unreleased commits, even for repositories where I do not have the right to do so. When clicked, I will get redirected to the homepage http://github.com.

### How to replicate the issue + URL

Open a project where you have no rights to create releases for (in my case a public repo was https://github.com/distcc/distcc), and click on the `+` sign created by `unreleased-commits`. 

### Extension version

24.10.14

### Browser(s) used

Firefox 130.0.1

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by whisperity** [comment]
> That's weird, we do have a check for this specifically:
> 
> https://github.com/refined-github/refined-github/blob/f30ca4a22528e9720e23b85d4cd38f074d64b179/source/features/unreleased-commits.tsx#L101

I was able to add a breakpoint to the line

https://github.com/refined-github/refined-github/blob/f30ca4a22528e9720e23b85d4cd38f074d64b179/source/features/unreleased-commits.tsx#L100

and if I execute **`await`**` userHasPushAccess()` in the console, I get `false`. In fact, refined-github repository is also a good candidate as I can't push here.

Evaluating `(!userHasPushAccess())` returns `false` even if I run it on a repo where I do have push access to. I guess the change here checks the success flag/status of the `Promise` object and not the actual queried value? As doing `(!await userHasPushAccess())` seems to return `true` for this repository, it seems to indicate this is the reason for the issue.

**Comment by fregante** [comment]
Ugh I caught another such bug in the code before. Yes, it needs an await. PR welcome if you can build the project and test it
