### ISSUE TITLE
Text Search + File Highlighting Capabilities like Sourcegraph project possible ?

### ISSUE THREAD

**Issue by Greatz08** [refined-github/refined-github#7920]
### Description

In Sourcegraph we can search for any text and all the files of that repo be it code file or text/md file or any other file will show that specific word been highlighted with reference to file name which is pretty awesome as i sometime forget exact file name but do remember some unique keywords with which i can easily find that file from web ui of that project repo. This will be very helpful for everyone if it would be possible to add something like that so thought to share with you :-) 
Following image is the showcase of what i mean where i searched for `refine` keyword in this github repo inside sourcegraph and it showed all the files and highlighted refine word too. I know sourcegraph has different ui and other things still i dont know if it is possible or not but if it is then it will be great addition to this project for sure. 

![image](https://github.com/user-attachments/assets/fa8fdf41-f262-4bf8-9f59-e4313fc4aabb)

At last Thank you very much for this awesome open source project :-))

### Example URLs

https://sourcegraph.com/github.com/refined-github/refined-github/-/tree/build

Here you can test what i told . you can search for any word and it will show the exact files of repo with highlighted keyword which you searched for.

(Sourcegraph has open source code available btw which you can study for help if needed)

**Comment by fregante** [comment]
Like this? https://github.com/search?q=repo%3Arefined-github%2Frefined-github%20refined&type=code

**Comment by fregante** [comment]
> btw your response was crazy fast

You had commented a few seconds before I opened GitHub 😅 

> when we are in main repo

What do you mean? You can do that on any repo by just typing in the search bar that appears on every page on GitHub
