### ISSUE TITLE
`clean-conversation-headers` missing from PR Commits tab

### ISSUE THREAD

**Issue by ChinaGodMan** [refined-github/refined-github#7927]
### Description

`clean-conversation-headers`   Why doesn't it take effect in the "Commits" tab on  Pull requests?

https://github.com/user-attachments/assets/c9d5003b-f143-4543-a166-f30a52a9478e

### How to replicate the issue + URL

Report  URL: [commits](https://github.com/ChinaGodMan/UserScriptsHistory/pull/63/commits)

### Extension version

24.10.14

### Browser(s) used

Google Chrome[129.0.6668.101 x64]

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Are there any errors in the console?

The only applicable difference is that the author should not be removed from the header on that page.

**Comment by ChinaGodMan** [comment]
> Are there any errors in the console?
> 
> The only applicable difference is that the author should not be removed from the header on that page.

There is no error message in the console

**Comment by kovsu** [comment]
Fixed by https://github.com/refined-github/refined-github/pull/8001

<img width="1085" alt="image" src="https://github.com/user-attachments/assets/0da85595-d3cf-498e-8aba-422f2f14b546">
