### ISSUE TITLE
``more-dropdown-links``: add links to repository nav bar if there is enough horizontal space

### ISSUE THREAD

**Issue by Andrew6rant** [refined-github/refined-github#7928]
### Description

On large monitors, there is plenty of empty space between the repository navigation tabs (Code, Issues, Pull Requests, etc) and the `more-dropdown-links` meatball menu.

I'd suggest to add the links to the repo tab bar if the viewport allows (unless the user has the `clean-repo-tabs` feature enabled).

![more-dropdown-links suggestion](https://github.com/user-attachments/assets/8b17a8c7-19f7-4ad9-99b5-58040c32157f)

### Example URLs

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
It does make sense but those links barely belong to that menu in the first place, they exist as extra utility links and I feel that they would clutter the main view.

**Comment by Andrew6rant** [comment]
> I feel that they would clutter the main view.

I mean, it might look a bit cluttered (here's a quick CSS mockup):
![more-dropdown-links links added to repository navigation bar](https://github.com/user-attachments/assets/c2d3e259-c278-4913-9a49-84db79280400)

But it's one less click to access these buttons. Many people prefer functionality over minimalism. If someone would rather have a cleaner nav bar, they would just use the `clean-repo-tabs` feature, which could add these back to the dropdown like they currently are.

**Comment by fregante** [comment]
I don't really want to add features that only work when something is disabled, this smells like an option, which [I'm allergic to](https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options). The main issue here is that since nobody sees it by default, it will easily be broken when we need to update the code.
