### ISSUE TITLE
``link-to-changelog-file``: merge into the `Releases|Tags` pill

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7934]
### Description

Before

<img width="340" alt="Screenshot 5" src="https://github.com/user-attachments/assets/45ba9e3b-53a4-40b8-b5fb-a17ff0400d15">

After

<img width="340" alt="Screenshot 6" src="https://github.com/user-attachments/assets/63c3fb4c-75ad-47d8-a403-211facb599f9">

The tooltip explains it enough, I think.

This change will help make room for #7932 

### Example URLs

https://github.com/jestjs/jest/releases

**Comment by shivam-shukla-71** [comment]
May I try?

**Comment by fregante** [comment]
Sure
