### ISSUE TITLE
`linkify-code` breaks code search

### ISSUE THREAD

**Issue by iamstarkov** [refined-github/refined-github#7951]
### Description

when I search in [`path:.npmrc`](https://github.com/search?q=path%3A.npmrc&type=code) files on GitHub its all get broken
![Screenshot 2024-10-24 at 17 30 50](https://github.com/user-attachments/assets/bd60ee8e-529b-4482-8c1f-8ac55c1863c8)

### How to replicate the issue + URL

try for yourself https://github.com/search?q=path%3A.npmrc&type=code

### Extension version

24.10.1

### Browser(s) used

Safari Version 18.0.1 (20619.1.26.31.7)

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by iamstarkov** [comment]
If I disable `linkify-code` feature it all works again
![Screenshot 2024-10-24 at 17 33 39](https://github.com/user-attachments/assets/b7419962-0b0b-4d70-9148-484ce18dabfa)

**Comment by fregante** [comment]
Thanks for the report! I disabled the feature via hotfix. It seems that either it's been broken for 5+ months or GitHub pushed an update now (more likely). 

A total guess is that the view is React and the altered DOM confuses React.

**Comment by iamstarkov** [comment]
thank you!
