### ISSUE TITLE
`select-notifications` doesn't work anymore 

### ISSUE THREAD

**Issue by huehnerlady** [refined-github/refined-github#7960]
### Description

When I use the select by dropdown box and select merge, nothing is selected.

![image](https://github.com/user-attachments/assets/f2c1979f-05b7-445c-9ded-b6a1a88d59fb)

### How to replicate the issue + URL

https://github.com/notifications?query=is%3Aunread

Click on `Select By`

![image](https://github.com/user-attachments/assets/d73362c3-28f0-421c-83d0-8b37ecd1ccec)

### Extension version

24.10.24

### Browser(s) used

Brave Browser Version 1.71.118 Chromium: 130.0.6723.70 (Official Build) (arm64) and Chrome Version 130.0.6723.70 (Official Build) (arm64)

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
It works for me in Safari (v24.10.1) so I probably broke it in a recent commit.

**Comment by fregante** [comment]
Indeed I broke it in https://github.com/refined-github/refined-github/commit/bd513e8b8cbe7370b684d8329bc92b142fbdc3c4#diff-7bba6acffb1997d5cd58b14024a2a335dece3d7a8ed76bfbf33609d7578df815

**Comment by huehnerlady** [comment]
thanks for the quick fix ❤️
