### ISSUE TITLE
`select-notifications`: Failed to execute 'querySelector' on 'Element': The provided selector is empty.

### ISSUE THREAD

**Issue by SocketSomeone** [refined-github/refined-github#7967]
### Description

```
Error: Failed to execute 'querySelector' on 'Element': The provided selector is empty.
    at elementExists (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/npm/select-dom.js:34:46)
    at HTMLElement.handleSelection (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/features/select-notifications.js:63:16)
```

### How to replicate the issue + URL

https://github.com/notifications

### Extension version

24.10.24

### Browser(s) used

Yandex

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/7960

**Comment by forestk** [comment]
Will a fix for this be released?

**Comment by fregante** [comment]
In 5 minutes

**Comment by forestk** [comment]
@fregante All thanks!
