### ISSUE TITLE
Refined GitHub logs errors that are unrelated to the extension 

### ISSUE THREAD

**Issue by piotrekkr** [refined-github/refined-github#7976]
Hello. Long time ago I've asked about option to always show all workflows on the list instead of "Show more workflows...". Today I tried to use tempermonkey user script on Firefox as it was suggested by @fregante. Somehow `click()` breaks Refined github and do not show any other workflows after click was fired. Here is my userscript:

```javascript
// ==UserScript==
// @name         GH show all workflows
// @namespace    http://tampermonkey.net/
// @version      2024-10-28
// @description  try to take over the world!
// @author       You
// @match        https://github.com/*/*/actions
// @match        https://github.com/*/*/actions/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=github.com
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    setTimeout(function () {
        console.log('DEBUG1');
        //document.querySelector('#item-e88427dd-7e28-4f08-8faf-e4e93bcfd992')?.click(); // DOING NOTHING
        //document.querySelector('#item-b6e7a6a9-5ec4-4a5b-a354-8dfd48be19e0 > span:nth-child(1)')?.click(); // DOING NOTHING
        //document.querySelector('#item-7fcf04b9-043f-4661-bef3-a698043a4e62 > span:nth-child(1) > span:nth-child(1)')?.click(); // DOING NOTHING
        document.querySelector('div.ActionListItem')?.click() // this "works" but breaks Refined Github
        console.log('DEBUG2');
    }, 2000);
})();

```
Console output:

![image](https://github.com/user-attachments/assets/6cbf4304-c3b1-4a81-895d-b4e3272fa003)

Any idea how can I properly "click" on "Show more workflows..."? 
Thank you.

**Comment by piotrekkr** [comment]
Okay so I need to wait for new version of this extension. Did I get this right? Thanks

**Comment by fregante** [comment]
It doesn't affect your code, your code is just producing the error and Refined GitHub is showing your error.

**Comment by piotrekkr** [comment]
Okay. I'm a bit confused. I do `click()` on div and it somehow produces this error. It is later catched by refined github. Did I understand this correctly? 

Do you maybe know why it is producing error in first place? To me it is just simple click event and it should work just fine. How should I trigger it so it will not produce error? I'm not JS wizard so I'll be grateful for any suggestions on what I'm doing wrong here. Thank you.

**Comment by fregante** [comment]
I don't know either, you'd have to ask on stackoverflow or to whoever wrote that userscript.
