### ISSUE TITLE
Tokens?

### ISSUE THREAD

**Issue by nollinvoyd** [refined-github/refined-github#7978]
Is Refined Github for regular users?  I was on your wiki Security page. I think I have a vague idea of what a token is.  In this case the user granting certain permissions to the system for enhanced functionality? But does it apply to regular users?

**Comment by fregante** [comment]
Did you install the extension?

**Comment by fregante** [comment]
The token lets Refined GitHub act on your behalf towards GitHub. "Acting" can be simply to read data from GitHub repositories. This applies to all users. Without it, a lot of data just is not accessible to the extension so most features won't work.
