### ISSUE TITLE
Prevent accidental merge

### ISSUE THREAD

**Issue by nerdCopter** [refined-github/refined-github#7986]
### Description

Request some feature or logic to the merge button to further prevent accidental merges -- some "idiot blocker".

reasoning: I have access to many repos.  sometimes i have many PR's tabbed in my browser.  i have accidentally merged a wrong PR due to my idiocy. 
- Maybe some extra warning displaying the repo name might prevent such.  but if im ignorant, it might still happen.
- Maybe better some check-mark designed as a two-stage merge.
- Or maybe **_better_** yet, some check-mark at repo-level that has to be enabled to enable the merge-button. (Since i have access, but am not the guy that does the official merging.)

### Example URLs

https://github.com/refined-github/refined-github/pull/7979

**Comment by fregante** [comment]
> * Maybe some extra warning displaying the repo name might prevent such.  but if im ignorant, it might still happen.

The URL is always visible. The more information on the page, the more to ignore. If we add the repo name, some other arguably more important piece of information will lose.



> * Maybe better some check-mark designed as a two-stage merge.

Merging is already two step:

1. Click merge to open mergeability dialog
2. Click merge to finalize it

> * Or maybe **_better_** yet, some check-mark at repo-level that has to be enabled to enable the merge-button. (Since i have access, but am not the guy that does the official merging.)

They exist and they're called branch protections: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches


I'm open to more ideas possibly. This is somewhat related to:

- https://github.com/refined-github/refined-github/issues/2579

**Comment by nerdCopter** [comment]
agree.
- i dont have access to branch-protections (settings) on the repos.
- i was thinking a "don't allow **_ME_** to merge" option.

i will close the ticket, but maybe something you could further ponder on.

**Comment by nerdCopter** [comment]
alternative: uBlock origin, just block the element:
![image](https://github.com/user-attachments/assets/0d53b532-efb7-44e2-a058-19d986154c98)
