### ISSUE TITLE
⚠️ Features broken on new PR commit view page (beta)

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7988]
### Description

There's some overlap with https://github.com/refined-github/refined-github/issues/7808 but this also has more PR features to take care of.

GitHub is also reportedly working on a PR page redesign so there's some overlap with that one too.

<img width="626" alt="Screenshot 4" src="https://github.com/user-attachments/assets/87582103-7749-41ce-883c-fbdec7c9968c">

### How to replicate the issue + URL

- https://github.com/refined-github/refined-github/pull/7893/commits
- [`32352f7` (#7981)](https://github.com/refined-github/refined-github/pull/7981/commits/32352f73b951779f7e07e15be5fecc4ebe62e664)

### Likely affected features

These contain the explicit `isPRCommit` check, it's not a complete list:

- [x] `patch-diff-links`
- [x] `pagination-hotkey`
- [x] `previous-next-commit-buttons`
- [ ] `action-pr-link`
- [x] `useful-not-found-page`
- [x] `linkify-commit-sha`
- [x] `pr-commit-lines-changed`

These have `isCommitList`

- [x] `conventional-commits`
- [x] `dim-bots`
- [x] `easy-toggle-commit-messages`
- [x] `mark-merge-commits-in-list`
- [ ] `parse-backticks`
- [x] `rgh-dim-commits`
- [ ] `rgh-linkify-features`
- [x] `toggle-everything-with-alt`

**Comment by kovsu** [comment]
> https://github.com/refined-github/refined-github/pull/7987/commits

I think this is test url [`32352f7` (#7981)](https://github.com/refined-github/refined-github/pull/7981/commits/32352f73b951779f7e07e15be5fecc4ebe62e664). Like [patch-diff-links](https://github.com/refined-github/refined-github/blob/main/source/features/patch-diff-links.tsx) hasn't applied in  https://github.com/refined-github/refined-github/pull/7987/commits

**Comment by fregante** [comment]
They've both been updated. For example the `clean-conversation-headers` applies to all PR pages as well. I added your test URL above

**Comment by fregante** [comment]
There are a couple that I haven't checked, but I think one is broken: `action-pr-link`

1. Open https://github.com/download-directory/download-directory.github.io/pull/146/commits
2. Click on a commit's checks link
3. Click "details"
4. URL does not have `?pr=146`

<img width="947" alt="Screenshot 5" src="https://github.com/user-attachments/assets/e1263700-42eb-410d-b25f-951ae9185889">
