### ISSUE TITLE
`.` should open GitHub dev "web editor" also at compare tab

### ISSUE THREAD

**Issue by koppor** [refined-github/refined-github#7992]
### Description

I am editing a file using the normal homepage of GitHub. Then I commit. GitHub porposes to open a PRs. I want to edit more files. I need to manually to navigate to https://github.dev to open the respective editor. 

It would be helpful if <kbd>.</kbd> would open the respective GitHub Dev web editor.

### Example URLs

https://github.com/refined-github/refined-github/compare/main...koppor:refined-github:patch-1 -> https://github.dev/koppor/refined-github/tree/patch-1

**Comment by fregante** [comment]
Simple feature, I can accept a PR: https://github.com/refined-github/refined-github/wiki/Contributing

**Comment by fregante** [comment]
I'll close this for now, but PR still welcome if you want to work on it.
