### ISSUE TITLE
`linkify-code` doesn't linkify inline links like `https://x.com`

### ISSUE THREAD

**Issue by BlazeFTL** [refined-github/refined-github#7995]
### Description
Is is possible to make theose links Clickable?

![Screenshot_2024-11-02-12-44-10-538_org mozilla fenix](https://github.com/user-attachments/assets/f11275f2-b0ab-4a34-b061-3dce8240375e)

### Extension version

24.10.28

### Browser(s) used

Firefox Nightly Android

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Yes we never supported inline links. Live example:

- `https://example.com`

But it works here:

```
https://example.com
```

**Comment by fregante** [comment]
It's a small change, PR welcome. The main difference is that the code should avoid already-linked elements, like `<a><code></a>`:

- [`the whole code is a link https://google.com`](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
- https://github.com/refined-github/refined-github/issues/7995


and `<code><a></code>`, as seen on https://github.com/refined-github/refined-github/commits/main/?after=62f91b26a6af3263a123c6c52266308af4e82328+34
