### ISSUE TITLE
Tabs are still 8 spaces

### ISSUE THREAD

**Issue by thockin** [refined-github/refined-github#8018]
### Description

Overview says "- Reduces tabs’ size to 4 spaces instead of 8." but I still see 8

### How to replicate the issue + URL

https://github.com/kubernetes/kubernetes/pull/128601/files

https://github.com/thockin/kubernetes/blob/master/cmd/fieldnamedocscheck/field_name_docs_check.go

### Extension version

24.10.28

### Browser(s) used

Chrome

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by busches** [comment]
You're missing the rest of the quote of the feature
> where GitHub doesn't follow [the user’s preferences.](https://github.com/settings/appearance)

Please check your tab settings in https://github.com/settings/appearance. The feature calls out the spots RGH is overriding it from 8 to 4, https://github.com/refined-github/refined-github/blob/main/source/features/tab-size.css

**Comment by fregante** [comment]
Indeed there are a lot more details in the CSS file itself.

In short Refined GitHub only sets a new default value, without necessarily overriding the user's setting.

**Comment by thockin** [comment]
Would you believe I had no idea there were themes with a tabstop setting?  TIL.  Thanks.
