### ISSUE TITLE
Max-height on issue/PR comment box

### ISSUE THREAD

**Issue by corywatilo** [refined-github/refined-github#8026]
### Description

When you're writing a long issue or PR description, the `<textarea>` automatically grows with its content – which is great until you want to toggle to preview mode, or use one of the action bar controls. Then you have to scroll all the way up to the top of the page.

It seems like this would easily be solved by setting a `max-height` on the textarea, which would allow scrolling within the pane while keeping all the controls accessible.

## Before

<img width="1722" alt="image" src="https://github.com/user-attachments/assets/348ca6d5-ec81-479b-9fed-9990e8856544">

## After

Here I set a `max-height` of `calc(100vh - 120px)` which perfectly fits the entire editor inside the viewport.

<img width="1759" alt="image" src="https://github.com/user-attachments/assets/c9aed53b-3e3c-4d08-8a41-10d0e67d2daf">

### Example URLs

```
https://github.com/*/*/issues/new
```

**Comment by fregante** [comment]
That's already a feature, but the opposite. You can disable `fit-textareas`
