### ISSUE TITLE
Firefox hanging on selecting issue/PR labels

### ISSUE THREAD

**Issue by joostlek** [refined-github/refined-github#8039]
### Description

Since yesterday, an issue similar to #7176 occurs again where opening the label dropdown will freeze the whole page. It also seems to makes it unable to open any new github tabs for the next several minutes as they will seem like they are still loading for an eternity.

This issue started happening when I opened my macbook yesterday. Before that I did not notice anything. I was still running 24.11.5 (I did not notice any slowdown with that version in the days before that with that version). I updated to 24.11.9 and it still happened. And I don't believe firefox updated in the meantime my macbook was closed.

### How to replicate the issue + URL

It happens for me on every issue or PR in https://github.com/home-assistant/core. We have quite a lot of labels so that might be the cause. I remember that in that last issue you got access to a similar repo with 1000+ labels. I will try to see what I can do to replicate this in a more public environment.

### Extension version

24.11.9

### Browser(s) used

Firefox

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by joostlek** [comment]
I will identify further, but wanted to put it out here since reproducing is easy, but harder to diagnose since everything freezes

**Comment by joostlek** [comment]
![output](https://github.com/user-attachments/assets/f282d7a0-4ff6-46a4-9c15-142add0abf1d)

**Comment by joostlek** [comment]
I still have `quick-comment-edit` disabled from last time

**Comment by joostlek** [comment]
Is there a good way to diagnose what it could be? The identify-feature doesn't work since its freezing with the rest of the page

**Comment by fregante** [comment]
Try disabling all the feature in the debugging section, but this is likely to be related to `:has()` in the CSS again.

**Comment by fregante** [comment]
> I remember that in that last issue you got access to a similar repo with 1000+ labels

Thanks for reminding me. I still have access to it but I don't see any slowdowns: https://github.com/dakrone/label-test/issues/1

![token](https://github.com/user-attachments/assets/a44f1d55-357e-42f5-baf5-a5daa4143850)

**Comment by joostlek** [comment]
Oh that is interesting. The HA core repo has 2241 labels. I also don't experience this with repos with a smaller amount of labels

**Comment by joostlek** [comment]
Would it otherwise be a possibility to limit the amount of shown labels? Because I never manually scroll down that list and always use the search, so maybe that can be a workaround

**Comment by fregante** [comment]
> Try disabling all the feature in the debugging section, but this is likely to be related to `:has()` in the CSS again.

I just checked the last two version and did not see any new/altered `:has()` selectors, which is what caused the issue last time: https://github.com/refined-github/refined-github/compare/24.10.28...24.11.9

> Would it otherwise be a possibility to limit the amount of shown labels? Because I never manually scroll down that list and always use the search, so maybe that can be a workaround

Try this CSS in the options and reload the page:


```css
.js-filterable-label:nth-child(5) ~ label {
  display: none;
}
```

Does it improve the speed? We can change the number to, like, 50

**Comment by joostlek** [comment]
It does only show 5 labels, but it completely froze again. I still have all the features turned off btw.

<img width="464" alt="image" src="https://github.com/user-attachments/assets/4fd49c45-578d-41ba-b3d6-f9386aa9af79">

I'd have expected it to be a performance thing with displaying :/

Would suspect now that there is something in memory going wrong

**Comment by joostlek** [comment]
> I just checked the last two version and did not see any new/altered :has() selectors, which is what caused the issue last time: 

I also don't believe the reason is because of a new version as I was running the 24.11.5 yesterday when it happened (and I don't believe firefox automatically updates when the macbook lid is closed, it didn't look like it was updated at least). And I think if it happened in the days before I would have noticed. So I would suspect it would be github that changed something, but I know too little about how they work and how that affects the extension to properly suspect them :)

**Comment by fregante** [comment]
Yeah this sounds like a selector issue again:

- not caused by JS
- not related to painting/layout operations

It's unfortunate that this time I can't repro it but I'm glad it only happens when there is a disproportionate amount of labels, so it's not urgent. 

If you can build the extension locally (see Contributing in our Wiki), reproduce the issue first and then gradually drop imports from `refined-github.ts` until the issue is gone. This would help us locate the slow selector.

**Comment by fregante** [comment]
@jryans do you have any advice to debug selector performance? Last time I was completely lost trying to debug this.

**Comment by joostlek** [comment]
I think I just got that working, and I commented the whole file out and it keeps happening

**Comment by joostlek** [comment]
Oh hmm, when I turn on the debugging tool to log every loaded plugin into the console I still see them, so something is off
<img width="258" alt="image" src="https://github.com/user-attachments/assets/7275b0a7-a795-4666-ba04-b4f50b34332e">

**Comment by joostlek** [comment]
Ah nvm, I wasn't building yet. It works now and the labels still work

**Comment by joostlek** [comment]
`table-input` is the reason why it freezes, without it, it works fine

**Comment by fregante** [comment]
You mean when you remove it from the build right? The CSS does have some very complex `:has()` + `:focus` logic in it. I might have to revert that change and just use JS

**Comment by joostlek** [comment]
Oh yes. Like said, if I disabled it via the extension it still didn't work. So if I comment that line out, it works and behaves like normal.

I know CSS, but now I read this, I don't know CSS anymore :P

**Comment by fregante** [comment]
Out of curiosity, does the performance improve if you use `.rgh-tic:hover` everywhere instead of just `:hover`?

**Comment by joostlek** [comment]
```diff
diff --git a/source/features/table-input.css b/source/features/table-input.css
index e52b3ad7..9546ccbd 100644
--- a/source/features/table-input.css
+++ b/source/features/table-input.css
@@ -35,23 +35,23 @@
 }
 
 .rgh-tic:hover div,
-.rgh-tic:is(:nth-of-type(5n + 1)):has(~ :hover:nth-of-type(5n + 1)) div,
+.rgh-tic:is(:nth-of-type(5n + 1)):has(~ .rgh-tic:hover:nth-of-type(5n + 1)) div,
 .rgh-tic:is(:nth-of-type(5n + 1), :nth-of-type(5n + 2)):has(
-		~ :hover:nth-of-type(5n + 2)
+		~ .rgh-tic:hover:nth-of-type(5n + 2)
 	)
 	div,
 .rgh-tic:is(
 		:nth-of-type(5n + 1),
 		:nth-of-type(5n + 2),
 		:nth-of-type(5n + 3)
-	):has(~ :hover:nth-of-type(5n + 3))
+	):has(~ .rgh-tic:hover:nth-of-type(5n + 3))
 	div,
 .rgh-tic:is(
 		:nth-of-type(5n + 1),
 		:nth-of-type(5n + 2),
 		:nth-of-type(5n + 3),
 		:nth-of-type(5n + 4)
-	):has(~ :hover:nth-of-type(5n + 4))
+	):has(~ .rgh-tic:hover:nth-of-type(5n + 4))
 	div,
 .rgh-tic:is(
 		:nth-of-type(5n + 1),
@@ -59,7 +59,7 @@
 		:nth-of-type(5n + 3),
 		:nth-of-type(5n + 4),
 		:nth-of-type(5n + 5)
-	):has(~ :hover:nth-of-type(5n + 5))
+	):has(~ .rgh-tic:hover:nth-of-type(5n + 5))
 	div {
 	border-color: #79b8ff;
 	background-color: var(
```
this seems to work better indeed!

**Comment by joostlek** [comment]
(Also, slight disclaimer, I did not test the `table_input` feature with this change as I don't exactly know where I can find and use that)

**Comment by fregante** [comment]
Yeah it should work. The feature has been disabled for a while and now it only works on a beta UI. You can it on the comment field on https://togithub.com/eslint/eslint/issues/17733 for example.

**Comment by fregante** [comment]
![teamwork](https://github.com/user-attachments/assets/bdbe6627-ef33-4696-835c-4660dae075c1)

**Comment by jryans** [comment]
> @jryans do you have any advice to debug selector performance? Last time I was completely lost trying to debug this.

Not sure I have any magic general purpose advice unfortunately... but it is generally better to "anchor" pseudo-selectors (`:foo`) by prefixing them with something more specific like an ID, class, etc. and indeed that seems to have worked here.
