### ISSUE TITLE
`submission-via-ctrl-enter-everywhere` broken

### ISSUE THREAD

**Issue by kovsu** [refined-github/refined-github#8049]
### Descriptio

The selector in `release` page is broken. And it already have `js-quick-submit` in textarea.

<img width="1243" alt="image" src="https://github.com/user-attachments/assets/97301b0d-2c3b-476a-b92e-8df0ec7a129b">

<img width="1225" alt="image" src="https://github.com/user-attachments/assets/638a62cc-01b7-4ab5-944a-104ecaf05caf">

### How to replicate the issue + URL

- New file: https://github.com/refined-github/sandbox/new/default-a
- Edit file: https://github.com/refined-github/sandbox/blob/default-a/editable
- New release: https://github.com/refined-github/sandbox/releases/new
- Edit release: https://github.com/refined-github/sandbox/releases/edit/cool

### Extension version

24.11.9

### Browser(s) used

Chrome

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by kovsu** [comment]
The selector in `file` may also need update. Should we drop this feature?

**Comment by fregante** [comment]
> The selector in `file` may also need update. Should we drop this feature?

yes, it works natively everywhere now

**Comment by fregante** [comment]
Can you also disable it in yolo? See how it's done in the other `broken-features` and include a reference to this issue _in the commit message itself_

**Comment by fregante** [comment]
Finally dropping one of the longest feature names 😃 

```js
importedFeatures.sort((a,b) => b.length - a.length).slice(0, 6)
```
```diff
[
  "linkify-notification-repository-header",
  "command-palette-navigation-shortcuts",
  "stop-redirecting-in-notification-bar",
- "submission-via-ctrl-enter-everywhere",
  "new-repo-disable-projects-and-wikis",
  "extend-conversation-status-filters"
]
```

**Comment by kovsu** [comment]
> Can you also disable it in yolo? See how it's done in the other `broken-features` and include a reference to this issue _in the commit message itself_

How can I know `Minimum working version`

**Comment by fregante** [comment]
It's empty
