### ISSUE TITLE
`pr-branch-auto-delete` is broken for me

### ISSUE THREAD

**Issue by NoahAndrews** [refined-github/refined-github#8055]
### Description

Here's a log from me merging a PR whose branch should get auto-deleted: (ndr: deleted, no relevant logs)

### How to replicate the issue + URL

Merge https://github.com/refined-github/sandbox/pull/100 and (hopefully) observe that the branch doesn't auto-close. I do have "Allow edits by maintainers" checked on that PR, and hopefully that's good enough. I can reproduce this even when I have full write access to the software in question.

### Extension version

24.11.12

### Browser(s) used

Chrome 130.0.6723.117

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
We have a number of exceptions now, does any of these match your branch?

https://github.com/refined-github/refined-github/blob/5106ef18bcc81cbf213c6e7b5bedb611bd3d67e2/source/features/pr-branch-auto-delete.tsx#L13

**Comment by fregante** [comment]
Merging that test PR won't delete the branch because the branch is not mine, the button won't appear for me, even if you granted *edit* access.

**Comment by fregante** [comment]
I can confirm it's not working

**Comment by kovsu** [comment]
I'm back to https://github.com/refined-github/refined-github/tree/b22f2c9a8c519596a831bceae2f1f571285a18d8, it works. So https://github.com/refined-github/refined-github/tree/d47243ff5752e637c11501925089d3b6115e725f has the problem make it doesn't work.

**Comment by kovsu** [comment]
https://github.com/user-attachments/assets/a13df7c7-491d-4e5d-8b4e-aca28ab26434

**Comment by fregante** [comment]
Glad to hear someone uses and expects the feature, it's probably the most controversial one 😅

**Comment by NoahAndrews** [comment]
Gotta save those seconds!
