### ISSUE TITLE
`unread-anywhere` keyboard shortcut conflict in Firefox

### ISSUE THREAD

**Issue by grahamperrin** [refined-github/refined-github#8060]
### Description

- https://github.com/refined-github/refined-github/pull/8008

The conflict with Firefox is unfortunate: 

![image](https://github.com/user-attachments/assets/3e921907-79f1-427d-a453-bd438b4c4fc2)

<https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly>

### Example URLs

Sorry, I can't recall where I was before the unexpected opening of ten other tabs. Probably at a GitHub URL. 

My bad, I should have mentally translated the mention of <kbd>cmd</kbd> at

- https://github.com/refined-github/refined-github/releases/tag/24.11.5

– to the <kbd>Ctrl</kbd> Control key (on e.g. FreeBSD).

**Comment by fregante** [comment]
Totally, it's always the issue with keyboard shortcuts. You'd have to disable the feature for now until we find a solution. Perhaps we should use `g u`, as a "go to unread notifications"

<img width="443" alt="Screenshot" src="https://github.com/user-attachments/assets/d709bd22-69ce-4cf4-9603-9700b1377a61">

**Comment by grahamperrin** [comment]
Thanks!
