### ISSUE TITLE
Missing align on long filenames in release page

### ISSUE THREAD

**Issue by ciro-mota** [refined-github/refined-github#8065]
### Description

When accessing a release that has a very long file name I come across this lack of alignment with especially the dates "escaping" from the page's session block. Below is the same page with and without the active extension.

![2024-11-14_14-34](https://github.com/user-attachments/assets/1b938b89-2573-4d9a-aea4-e4e76bac22e5)
![2024-11-14_14-35](https://github.com/user-attachments/assets/cc0138c2-7ec5-44cf-a729-214ddd860484)

### How to replicate the issue + URL

- https://github.com/hkint/xiaomi-ax3000t-immortalwrt-hanwckf-firmware-build/releases/tag/ImmortalWrt_2024.11.13-0026

### Extension version

24.11.12

### Browser(s) used

Firefox 132.0

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
This might just need a flex-shrink somewhere. We can place it in GitHub-bugs.css

**Comment by fregante** [comment]
They just miscalculated the col size, this is too big:

<img width="212" alt="Screenshot 2" src="https://github.com/user-attachments/assets/7d76689a-b6c5-49b6-9e53-bfd847adac5d">

but if I set it to 65% it works:

<img width="1047" alt="Screenshot 3" src="https://github.com/user-attachments/assets/f2f3bb50-88d9-4a1b-b0b4-5862cbe3548b">

**Comment by fregante** [comment]
Better yet, just wrap the text to avoid this unnecessary loss of information:

```css
.Truncate>.Truncate-text {
	whitespace: wrap;
}
```

of course the selector needs to be more specific

<img width="746" alt="Screenshot 5" src="https://github.com/user-attachments/assets/c59a5735-b5f1-4200-b2ea-64d8860db742">
