### ISSUE TITLE
Ghost locked issues

### ISSUE THREAD

**Issue by joostlek** [refined-github/refined-github#8088]
### Description

So for some reason, I have one user on the github repository where the issues seems to be "locked", after which I can't react emoji. But I also can't unlock the conversation. 
<img width="1326" alt="image" src="https://github.com/user-attachments/assets/8fb68660-424f-412d-b8f8-07544ecfbc95">

I made this issue just for tracking, maybe it rings a bell. Now I have a dev env I will try to see if something specific causes it

### How to replicate the issue + URL

https://github.com/home-assistant/core/issues/131006

### Extension version

24.11.12

### Browser(s) used

Firefox

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Did they block you? That sounds like the reason. 

The bugfix is already in a PR:

- #7842

**Comment by joostlek** [comment]
I would not be surprised if they did. This is their alt account, and he did mention blocking mee om their main account.
