### ISSUE TITLE
Seeing pink boarder on notifications button

### ISSUE THREAD

**Issue by arishoham** [refined-github/refined-github#8097]
### Description

the notifications button on github enterprise on a pull request page has a pink boarder around the selected button

![image](https://github.com/user-attachments/assets/2cc78238-624a-4b7e-8c00-09221ad2e818)

### How to replicate the issue + URL

cannot send a link due to github enterprise

### Extension version

24.11.21

### Browser(s) used

chrome

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Duplicate
