### ISSUE TITLE
`scrollable-areas`: scrollbar doesn't stick to the right in markdown file's code blocks

### ISSUE THREAD

**Issue by Veetaha** [refined-github/refined-github#8099]
### Description

Take a look at the code blocks in the README here: https://github.com/elastio/bon#struct-builder. The scroll bars appear in the middle of the block. I think they stick to the widest code line in that block.

![image](https://github.com/user-attachments/assets/2bd3990f-087d-4f2f-895d-e9acc5e2d08e)

### How to replicate the issue + URL

Take a look at the README in https://github.com/elastio/bon#struct-builder

### Extension version

24.11.21

### Browser(s) used

Chrome v131.0.6778.86 (Official Build) (64-bit)

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Thanks! This is actually not intentional. The feature should only apply to comments, not any markdown area.

cc @ToBinio https://github.com/refined-github/refined-github/pull/7952

**Comment by fregante** [comment]
Oh actually it's likely https://github.com/refined-github/refined-github/pull/8089 @kovsu

**Comment by fregante** [comment]
CSS hotfixed for now
