### ISSUE TITLE
Displaying Contribution Data in GitHub contribution graph

### ISSUE THREAD

**Issue by prem-k-r** [refined-github/refined-github#8104]
### Description

The current GitHub contribution graph/chart lack specific data insights within the graph. 
![image](https://github.com/user-attachments/assets/28b555dd-931d-44e3-a254-6fb866bd4db0)

I propose including additional data (as shown in the attached image), such as:
- Total Contributions: A numerical display summarizing contributions over the year.
- This Week’s Contributions: Contributions within the current week.
- Best Contribution Day: The day with the highest number of contributions.
- Also `Today` (Missing in the image below)
- Average Contributions Per Day: A simple calculation for user insights.
- Streak Details: Longest streak and the current streak for added motivation.

This enhancement would provide users with data insights. Note that this request is specifically for the 2D graph, not the 3D isometric contribution graph as in the following image.
![image](https://github.com/user-attachments/assets/bed9c96f-03e4-47c7-bacb-dd0903911cd3)

### Example URLs

`https://github.com/{username}`

for example:
```
https://github.com/prem-k-r
```

**Comment by fregante** [comment]
This could be its own extension or possibly part of GitHub, I don’t think it's data that's easily available.

**Comment by prem-k-r** [comment]
GitHub's GraphQL API provides detailed information about user contributions. It can be used.

**Comment by fregante** [comment]
This is not something Refined GitHub is for. The extension provides small enhancements, not entire new views. Every feature longer than 200 lines is painful to maintain (when compounded by 200 features, 7 years so far, frequent GitHub changes)

**Comment by prem-k-r** [comment]
Sorry, I may have made you misunderstand with the earlier image.

![IMG_20241126_204851](https://github.com/user-attachments/assets/455c75c1-04f1-4f17-822f-2ebc900caa9d)

I understand this may be beyond the scope of this project.
Thank you for your time.
