### ISSUE TITLE
Link to Compare View from Branches

### ISSUE THREAD

**Issue by andymerts** [refined-github/refined-github#8106]
### Description

When viewing the list of branches, it would be very convenient if the ahead/behind numbers were hyperlinked to take me to the /compare/{selected}...{main} view

### Example URLs

https://github.com/refined-github/refined-github/branches

**Comment by fregante** [comment]
Hmmm it feels like we had this feature at some point. I remember wrapping that -/+ widget in a `<a>`, or maybe there's an open request for it already.

**Comment by fregante** [comment]
@yakov116 @kidonng am I misremembering? What feature used to make this widget clickable?

<img width="133" alt="Screenshot" src="https://github.com/user-attachments/assets/6e93e418-06ff-406e-be1c-58dd1451bde6">

**Comment by yakov116** [comment]
The layout used to be different and there was a compare button as seen from the pictures in this PR
https://github.com/refined-github/refined-github/pull/3116

**Comment by fregante** [comment]
The screenshotted widget has been there for a while though. My guess is that we experimented linkifying it for some other feature, but I can't find anything like it.

**Comment by fregante** [comment]
The link is already there:

<img width="343" alt="Screenshot 1" src="https://github.com/user-attachments/assets/938ffa9a-8904-43b8-a68a-2f795642eb34">

**Comment by andymerts** [comment]
My common scenario, and the reason for this request, is to look at what's new in our main branch since a release branch was created to assist in putting together documentation for an upcoming release.

The two ways I've found to accomplish this from the `/branches` view are to start a PR and swap the direction so I'm PR'ing `main` into an old release branch (not what I want to do, feels very unintuitive), or click the branch name and then click the "This branch is N commits behind main" link to get to the `/compare/releases/xyz...main` view.

If there's no interest in a convenience link on each of the commits ahead/behind indicators, I can continue using these workarounds despite them feeling very kludgy. I was hoping for something similar to the experience in Azure DevOps like below:

![image](https://github.com/user-attachments/assets/aca474d3-746f-4c5c-b853-fa78ddc32756)

Each of those numbers (other than the zeros) are hyperlinks to their branch compare view showing the commits and file differences.

I really enjoy the enhancements to the GitHub UI your extension provides, and appreciate your consideration 🙂
