### ISSUE TITLE
`pr-branch-auto-delete` - Allow inputting custom branch names to be excluded

### ISSUE THREAD

**Issue by VasilisThePikachu** [refined-github/refined-github#8107]
### Description

We can keep adding on popular branch names that would be long term usually but we can't cover them all. Allowing the user to input their own branch names would be ideal.

### Example URLs

N/A

**Comment by fregante** [comment]
We can't add further options to Refined GitHub, see:

https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#3-it-doesnt-require-options

**Comment by fregante** [comment]
> Allowing the user to input their own branch names would be ideal.

Just protect the branches. If your repo allows the branch to be deleted, then the branch will be deleted. Murphy's Law.

Just protect the branches.

**Comment by fregante** [comment]
https://github.com/refined-github/refined-github/wiki/Extended-feature-descriptions#pr-branch-auto-delete
