### ISSUE TITLE
`restore-file`: Add confirmation modal before discarding changes

### ISSUE THREAD

**Issue by uncenter** [refined-github/refined-github#8108]
### Description

The discard changes / restore file feature is useful, however I've mistakenly clicked on the item in the dropdown multiple times when trying to, say, view the raw contents of a file. I don't want to disable the feature entirely, but having a confirmation modal would be very helpful.

### Example URLs

Any pull request with which you have editor permissions over to actually discard the changes, e.g. https://github.com/refined-github/refined-github/pull/8090.

**Comment by fregante** [comment]
I'll close this issue, but please send a PR if you're interested. It just needs `if (confirm())` somewhere
