### ISSUE TITLE
Direct access to workflow build artifacts

### ISSUE THREAD

**Issue by Coldblackice** [refined-github/refined-github#8109]
### Description

Unless I'm overlooking it, downloading a repo's build artifacts requires a handful of clicks/navigating/filtering: 

1. Clicking a repo's "Actions" tab
2. Clicking a workflow from the top-left list of workflows
3. Clicking to filter that workflow's runs by status, e.g. by "_Success_" (I'm not sure why Github doesn't have a filter for "_**Has artifacts**_"
4. Clicking into workflow run entries to check if each run has artifacts
5. Scrolling to bottom of a run's page to see if it has artifacts (and if they're unexpired)
6. And finally, if artifacts exist, if artifacts are unexpired, clicking to download the desired artifacts

It would be phenomenally useful if these could be accessed directly from repos' root pages, whether a hover box from the "_Actions_" link which shows a list of workflows with most-recent-successful-runs-with-artifacts, or simply direct linking those artifacts themselves).

A variation of this could be an ability to checkbox "favorite" specific workflows, and then have a flashing alert icon on a repo's page to indicate that there is a new build artifact since last visit, or recent X days, etc. 

This could additionally be interfaced into the Github inbox/notifications, new workflow artifacts being a notification/alert on its own, with direct links to the artifacts (or at least the particular run).

Granted, there exists an alternative method to this via the "Nightly.link" option, however it's externally hosted and requires manually editing workflow URLs to reach artifact links. Even then, this doesn't always work on all build workflows.

A variation of this feature -- also useful on its own, in addition to above -- would be a function that checks and highlights workflows and workflow-runs that have unexpired, downloadable artifacts, without having to browse into and out of runs, workflow by workflow, run by run.

For example, in the top-left list of Workflows on the "_Actions_" page, this addon could sort that list by _**Most-recent-artifact**_. Similarly, in the list of a workflow's run, individual runs with downloadable/unexpired artifacts could become highlighted/bolded/colored as an indicator, as a sort of visualized filter indicator, pre-applied.

/$0.02

### Example URLs

https://github.com/refined-github/refined-github
https://github.com/refined-github/refined-github/actions

**Comment by fregante** [comment]
This is too involved and niche for Refined GitHub.

I'd advise working with nightly.link to:

- add a way to access all workflows at once
- fix _"this doesn't always work on all build workflows."_

As for the notifications, if you control the repo you can configure it to send out notifications either via email or by adding a comment to a specific issue, to which you can subscribe (just an idea).
