### ISSUE TITLE
Allow uploading patch from the UI

### ISSUE THREAD

**Issue by kasperk81** [refined-github/refined-github#8125]
### Description

https://github.com/orgs/community/discussions/146387

It would be nice to allow patches via web interface, how phabricator handles it: a text area where we past the stuff.

### Example URLs

https://www.jesusamieiro.com/applying-patches-with-git-and-curl-or-wget/

**Comment by fregante** [comment]
Why would they send a patch via email? Creating a patch requires them to have the whole repo checked out. What's stopping them from opening a proper PR?

**Comment by fregante** [comment]
> PRs and MRs are relatively new concepts.

Probably time they learn them, I'm not interested in supporting workflows from the 90s in 2025

**Comment by fregante** [comment]
Also not possible via API, the commit would lose all metadata: https://stackoverflow.com/questions/43769489/how-to-create-a-commit-from-a-diff-or-patch-using-githubs-api

**Comment by fregante** [comment]
Linus doesn't use GitHub.com. When he gets an email, he applies the patch file via command line. Instead of switching to GitHub.com to apply the patch, switch to the terminal and use `pbpaste | git apply`
