### ISSUE TITLE
`unread-anywhere`: opens force-pushed PRs to wrong commit link

### ISSUE THREAD

**Issue by bo0tzz** [refined-github/refined-github#8129]
### Description

When using this feature to open a notification of a PR that was force-pushed to, the link it opens is invalid (I can't work out exactly in which way), showing the "404" type page in the Files changed tab ("We went looking everywhere, but couldn’t find those commits.") and not marking the PR notification as read. The link I'm getting sent to is https://github.com/immich-app/static-pages/pull/67/files/aa7d6b615de3ff6e51faae1f78afaa07c2d8b2f1..d54c27dfa45013b51b29c7ef48606d0cfe53c5a4

However, opening the link manually from the notifications page works as expected and takes me to the PR's discussion tab. Manually reproducing the code from `openUnreadNotifications` in the browser console also works as expected:
```javascript
document.querySelectorAll("a.js-navigation-open")[0].href
// -> "https://github.com/immich-app/static-pages/pull/67?notification_referrer_id=NT_kwDOALEJ-LQxMzU0OTg2MjQ5MDoxMTYwMjQyNA&notifications_query=is%3Aunread#issue-comment-box" 
```

### How to replicate the issue + URL

I can reproduce this on https://github.com/immich-app/static-pages/pull/67 by marking its notification as unread, but I don't think there's a way to do that if you weren't already subscribed to it, so I'm not really sure how someone else can reproduce this easily.

### Extension version

24.12.2

### Browser(s) used

Firefox

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

As a sidenote, thanks for this great feature, I use it _constantly_!

**Comment by fregante** [comment]
This is a GitHub bug, also documented in https://github.com/refined-github/refined-github/issues/4648


We just open the links that GitHub provides, actually loading the same notifications HTML page that you would otherwise open. 

Anyway thanks for testing out this somewhat hidden feature. 🙏

**Comment by fregante** [comment]
Funny thing, we actually added a feature to fix that bug, but the feature does not run here. 

- https://github.com/refined-github/refined-github/pull/7104

Reopening to silently apply the same treatment within `unread-anywhere` (regardless of the enabled/disabled status of that other feature)

**Comment by bo0tzz** [comment]
Ha, I did think it might be a github bug somehow but was thrown off by not being aware that refined-github fixes it :laughing:.

Can the `trimLink` from `pr-notification-link` just be imported for use in `unread-anywhere`, or does it need to be extracted to a shared utility file or such?

**Comment by fregante** [comment]
It should be exported directly, this shows the two features are linked. Since it acts on a HTMLAnchorElement, the input type should be altered to be `HTMLAnchorElement | URL`, which is compatible but allows us to use it on a `new URL()` object

**Comment by fregante** [comment]
> Ha, I did think it might be a github bug somehow but was thrown off by not being aware that refined-github fixes it 😆.

Happens a lot, this is why people who want to disable most features are missing out. There are so many small improvements that you never thought you needed. 😅
