### ISSUE TITLE
Formatting broken with 24.12.9 on Firefox (✅ Fix inside)

### ISSUE THREAD

**Issue by etiennebacher** [refined-github/refined-github#8142]
### Description

Multiple formatting issues (fonts, text of tabs is overlapping, etc.).

This is with the extension **disabled**: 

![image](https://github.com/user-attachments/assets/6d2189fd-1f81-45cd-bb63-515d4a566bb1)

This is with the extension **enabled**: 

![image](https://github.com/user-attachments/assets/a1242625-e9e8-4597-9dc0-37cd3fce2a99)

### How to replicate the issue + URL

For example https://github.com/refined-github/refined-github, but it appears on all types of pages: issues, PR, github dashboard, user page, etc.

This issue appeared today with the latest version (24.12.9).

### Extension version

(24.12.9)

### Browser(s) used

Firefox 133 on Ubuntu 24.04

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by thom4parisot** [comment]
Example of Notifications page

![image](https://github.com/user-attachments/assets/46d21977-5ed3-4628-8811-4e057023e201)

**Comment by rithviknishad** [comment]
@fregante Could #8140 be the reason?

**Comment by sersorrel** [comment]
Some completely nonsense content is being fetched as a hotfix:

![image](https://github.com/user-attachments/assets/372bc6a8-28b2-4a55-864d-d026e11e9f0d)

**Comment by sainak** [comment]
Clearing RGH cache fixed it for me
https://github.com/refined-github/refined-github/wiki#-debugging

**Comment by fregante** [comment]
Ah crap. I'm on it

**Comment by fregante** [comment]
@sersorrel's PR fixed the issue. 

# Click "Fetch hotfixes" in the options to fix the issue

**Comment by Mte90** [comment]
I can confirm that clearing the cache fixed it, just click on https://github.com/refined-github/refined-github/wiki#-debugging and on "options page" automatically open the extension settings page.

**Comment by fregante** [comment]
The bug was introduced by https://github.com/refined-github/refined-github/pull/8128. I'm glad that I also added https://github.com/refined-github/refined-github/pull/8127 to see and re-fetch the hotfixes just in time 😅 

I opened a PR to fix the fetching mechanism at the root.

Let's keep this PR open for visibility, the issue should be resolved for everyone within 6 hours.

**Comment by fregante** [comment]
# 🏷️ I released 24.12.10 just for Firefox

This also fixes https://github.com/refined-github/refined-github/issues/8144. Chrome was not affected.

Thanks for reporting the issue!
