### ISSUE TITLE
Firefox: `broken-features.csv` and `strings.json` aren't loaded due to CSP violation

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [refined-github/refined-github#8144]
### Description

I don't know if this is related to recent issues like https://github.com/refined-github/refined-github/issues/8142, but I noticed in the Firefox devtools that on every load I get the following errors:

![image](https://github.com/user-attachments/assets/0e74e7a3-76e2-4af5-a7e0-2279fe172c51)

I don't know what these files contain or what functionality might be broken by not loading them.

### How to replicate the issue + URL

1. Load any GitHub repo, like https://github.com/refined-github/refined-github
2. Observe CSV errors in the devtools

### Extension version

24.12.9

### Browser(s) used

Firefox 133.0

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Yes it's also https://github.com/refined-github/refined-github/pull/8128. The fix is to load those files in the background instead (via webext-msg)
