### ISSUE TITLE
`show-names` replaces names incorrectly

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#8147]
### Description

- user: kidonng
- full name: Kid
- shown name: Kid
- expected name: kidonng (Kid)

### How to replicate the issue + URL

See these two users and their replaced names:

- https://togithub.com/refined-github/refined-github/issues/4979
- https://togithub.com/sindresorhus/write-json-file/issues/3

### Extension version

24.11.12

### Browser(s) used

Safari

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Likely cause:

- https://github.com/refined-github/refined-github/pull/7714/files

**Comment by kovsu** [comment]
Beacause `kidonng` starts with `Kid`, so`isUsernameAlreadyFullName` will return `true` here

https://github.com/refined-github/refined-github/blob/6f15ac1c2668b1d1d800611f6114cdc29daa70cc/source/github-helpers/index.ts#L55

**Comment by fregante** [comment]
Unclear what I was fixing, so it's easy to just drop it

https://github.com/refined-github/refined-github/pull/7899/files/1d60bcee278dadbb45cd501d56f0b4552a48dced#diff-10ea2ac1855ba73fe69bd22a445847d89960717eef20641fb46c5ddaab234ee8
