### ISSUE TITLE
GitHub Material Icons or VS Code Icons in GitHub UI

### ISSUE THREAD

**Issue by adarshan-intel** [refined-github/refined-github#8149]
**Feature Request: Option to Select GitHub Material Icons or VS Code Icons in GitHub UI**

**Description:**
It would be beneficial to have an option in the GitHub UI that allows users to select and use GitHub Material Icons or VS Code icons. This feature would enhance the visual appeal and customization of the user interface, making it more user-friendly and engaging.

**Benefits:**
- Improved visual customization
- Enhanced user experience
- Consistency with other tools like VS Code

**Use Case:**
Users who prefer a more personalized and visually consistent interface across their development tools would find this feature particularly useful.

### Example URLs

Can we have an implementation like we have here - https://github.com/material-extensions/material-icons-browser-extension?
I know its a big ask but can someone look into this?

**Comment by fregante** [comment]
Point 1 here https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22
