### ISSUE TITLE
Custom CSS override not working on GitHub pages in Firefox

### ISSUE THREAD

**Issue by Adam-Kay** [refined-github/refined-github#8154]
### Description

I use a custom CSS override to change the heat color on the commit date for files, as I like green more as an indicator of recency rather than orange. When I recently moved from Chrome to Firefox, I found that despite exporting and re-importing my existing settings, this no longer worked for me.

Here is the setting that I set in the Custom CSS section:
![image](https://github.com/user-attachments/assets/cf0945a6-c123-43b4-8eaf-d66f486ecd99)
<details><summary>CSS in text <i>(click to view)</i></summary>
<p>

```css
:root {
	--rgh-heat-color: #59aa41;
}
```

</p>
</details> 

and the end result on GitHub pages (still orange):
![image](https://github.com/user-attachments/assets/dca9ff98-19af-4d25-be28-3f1fec6bfff4)

I looked into the developer console and saw that the variable was not being overridden correctly
![image](https://github.com/user-attachments/assets/937abd58-0dcb-4606-9298-54dd65116ab1)

Is this a bug in the latest Firefox version of the extension?

### How to replicate the issue + URL

https://github.com/roblatour/Push2Run (any GitHub URL)

#### Steps to reproduce:
1) Set **Custom CSS** to the following:
	```css
	:root {
		--rgh-heat-color: #59aa41;
	}
	```
2) It does not take effect.

### Extension version

24.12.10

### Browser(s) used

Firefox 133.0.3

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
GitHub Pages is not on GitHub.com, but are custom websites _hosted on GitHub's server._ There's no overlap with GitHub.com and Refined GitHub. 

You can use a user style extension

**Comment by fregante** [comment]
The injection is working, you'll have to use `!important` or the appropriate selector. `:root` is less specific than `:root [data-rgh-heat="3"]`

**Comment by Adam-Kay** [comment]
> you'll have to use `!important`

This worked! Not sure why the functionality changed between Chrome and Firefox but either way, resolved now. Thanks!
