### ISSUE TITLE
Link the website on Chrome web store page

### ISSUE THREAD

**Issue by Michael21107** [refined-github/refined-github#8179]
### Description

The overview section of the Chrome web store page of the extension says to ''see the website for a full list of features,'' however, the only website it could be referring to is in the support section, much further down the page. Adding a simple link in the overview text would allow more intuitive access to the user.

### Example URLs

https://chromewebstore.google.com/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf

**Comment by fregante** [comment]
This is not allowed by the store
