### ISSUE TITLE
Consider enabling "Apply" button in Watch dialog when no events are selected

### ISSUE THREAD

**Issue by sersorrel** [refined-github/refined-github#8183]
### Description

If you click "Watch" > "Custom" on a repo, you can select specific events to be notified about (rather than "everything", "nothing", or the default "only mentions/when participating"). However, if you uncheck all the options in that dialog, the apply button becomes disabled:

![image](https://github.com/user-attachments/assets/7dbb4865-0017-44bb-9892-437e33f6c435)

I find it moderately frustrating that this is the case; IMO, clicking apply in this state should just set the watching state to "Participating and @mentions", given the "Custom" option is described as "events you want to be notified of in addition to participating and @mentions."

### Example URLs

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
I think the current behavior is correct.

1. You open a dialog that lets you choose specific events to follow
2. You close the dialog, cancelling your intent to choose events

Changing a setting outside this dialog isn't right, it should stay whatever was selected before opening the "custom" dialog.

**Comment by fregante** [comment]
I'm not a fan of the Follow dropdown as a whole, but that's a different story. See:

- https://github.com/refined-github/refined-github/issues/6090

**Comment by fregante** [comment]
> if you uncheck all the options in that dialog

If that's your intent, why are you in that dialog in the first place? You made 4-8 clicks to make an action that can be made in 2. 🤷‍♂️

**Comment by sersorrel** [comment]
for example, I am getting a painful number of release notifications for a repository, and wish to unsubscribe from those, but I don't remember what (if any) other types of notifications I'm subscribed to.
