### ISSUE TITLE
Keyboard shortcuts to navigate and collapse files in diffs

### ISSUE THREAD

**Issue by hkdobrev** [refined-github/refined-github#853]
It would be lovely if we can use <kbd>j</kbd>/<kbd>k</kbd> to go through files in the "Files changed" tab and use <kbd>Spacebar</kbd> to toggle collapsing.

![image](https://user-images.githubusercontent.com/506129/33761728-bbb9349c-dc12-11e7-94f6-e8e850d10dad.png)

**Comment by bfred-it** [comment]
For reference, it's there but it doesn't work:

<img width="557" alt="shortcuts in pr view" src="https://user-images.githubusercontent.com/1402241/33779617-9a0789a4-dc88-11e7-84a3-c600e1e3f8d5.png">

**Comment by sindresorhus** [comment]
*For anyone that wants this, please also send this feature request to GitHub: support@github.com*

**Comment by yakov116** [comment]
@fregante can we combine this issue with #3319

**Comment by fregante** [comment]
That issue is for bugs, this is an enhancement

**Comment by fregante** [comment]
4 years are enough, sorry peeps 😅

**Comment by yannxaver** [comment]
Are there any intentions to implement this? I think this would be an immensely useful feature :)

**Comment by cheap-glitch** [comment]
> Are there any intentions to implement this? I think this would be an immensely useful feature :)

Moving through files in diffs with <kbd>j</kbd> / <kbd>k</kbd> is already implemented in `keyboard-navigation`. It just needs to support <kbd>Space</kbd> for toggling.

@yannxaver Please open a new issue if you request this so we can track it. It should be relatively easy to implement, feel free to take a stab at it :)

**Comment by fregante** [comment]
@cheap-glitch the issue already exists, it's the PR that's missing. We don't need to *track* this
